#!/usr/bin/env python3
"""chessboard-orbits-and-bond-reflections, independent run 2 of 2 (worker w-jonathonsmac4f50-j53ce, claude-opus-5).

Six-axis rule: values are the six axis directions (indices 0..5, antipodal pairs (0,1), (2,3), (4,5)); the weight of a bond is
K(s,t) = p (equal), q (antipodal), r (orthogonal).  Static law on a torus: prod over bonds of K, normalised.

A1 (exact)  orbits of one direction-1 bond on (Z/L)^d under the group generated by
              site-plane reflections  x_i -> 2k - x_i        (through the sites x_i = k)
              bond-plane reflections  x_i -> 2k + 1 - x_i     (through the midpoints of the direction-i bonds)
            enumerated by breadth-first search on the bond's base point; a direction-1 bond {x, x+e1} maps to the
            direction-1 bond with base 2k - x_1 - 1 (site plane, i = 1), 2k - x_1 (bond plane, i = 1), or the reflected
            base (i != 1).
A2 (exact)  the 6 x 6 weight matrix W = (p - r)I + (q - r)P + r J (P the antipodal pairing) has eigenvalues p + q + 4r,
            p - q (three times) and p + q - 2r (twice), so W is positive semidefinite iff p >= q and p + q >= 2r.
N1 (numerical, labelled)  reflection positivity through a bond plane on the 4 x 2 torus: the full Gram matrix
            <F theta(G)> over indicators of the half-torus configurations (1296 x 1296), at three weight triples inside the
            region and one outside.
N2 (numerical, labelled)  the same on the 4 x 4 torus over the column basis (1296 functions of the column next to the plane),
            computed with transfer matrices."""
import itertools
import sys
from collections import deque

import numpy as np
import sympy as sp

FAILS = []


def check(label, ok, detail):
    print(("ok   " if ok else "FAIL ") + f"{label}: {detail}", flush=True)
    if not ok:
        FAILS.append(label)


def orbit(L, d, groups):
    """orbit of the direction-1 bond with base (0,...,0) under the chosen reflection families"""
    start = tuple([0] * d)
    seen = {start}
    Q = deque([start])
    while Q:
        x = Q.popleft()
        for i in range(d):
            for k in range(L):
                for g in groups:
                    y = list(x)
                    if i == 0:
                        y[0] = (2 * k - x[0] - (1 if g == "site" else 0)) % L
                    else:
                        y[i] = (2 * k - x[i] + (0 if g == "site" else 1)) % L
                    y = tuple(y)
                    if y not in seen:
                        seen.add(y)
                        Q.append(y)
    return len(seen)


def K(i, j, p, q, r):
    return p if i == j else (q if i == (j ^ 1) else r)


def main():
    # ---------------- A1
    rows = []
    ok = True
    for L, d in ((4, 2), (6, 2), (8, 2), (4, 3), (6, 3)):
        n = L ** d
        o_site = orbit(L, d, ["site"])
        o_bond = orbit(L, d, ["bond"])
        o_both = orbit(L, d, ["site", "bond"])
        rows.append((L, d, n, o_site, o_bond, o_both))
        ok &= o_both == n
    check("A1", ok, "orbit of one direction-1 bond (of L^d such bonds) on (Z/L)^d: " +
          "; ".join(f"L={L} d={d}: {n} bonds, site planes {os} ({os/n:.2f}), bond planes {ob} ({ob/n:.2f}), both {obo} ({obo/n:.2f})"
                    for L, d, n, os, ob, obo in rows) +
          " - site planes reach a half in 2D and a quarter in 3D, as expected; bond planes reach a half in BOTH dimensions, "
          "not all of them: a bond-plane reflection in direction 1 sends the base x_1 to 2k - x_1 and so preserves its parity, "
          "while the site-plane reflection sends it to 2k - x_1 - 1 and flips it; together they are transitive")

    # ---------------- A2
    p, q, r = sp.symbols("p q r", positive=True)
    W = sp.Matrix(6, 6, lambda i, j: p if i == j else (q if i == (j ^ 1) else r))
    ev = W.eigenvals()
    want = {p + q + 4 * r: 1, p - q: 3, p + q - 2 * r: 2}
    ok = {sp.simplify(k): v for k, v in ev.items()} == {sp.simplify(k): v for k, v in want.items()}
    line = [(pp, sp.simplify((sp.Integer(pp) - 1 >= 0) & (sp.Integer(pp) + 1 - 4 >= 0))) for pp in (2, 3, 4, 5)]
    check("A2", ok, f"W = (p-r) I + (q-r) P + r J has eigenvalues {{p+q+4r: 1, p-q: 3, p+q-2r: 2}} (symbolic), so W is positive semidefinite "
          f"iff p >= q and p + q >= 2r (the first eigenvalue is automatic for positive weights); on the line (p, 1, 2) that is p >= 1 and "
          f"p >= 3, i.e. p >= 3: " + ", ".join(f"p={pp}: {'in' if bool(v) else 'out'}" for pp, v in line))

    # ---------------- N1: 4 x 2 torus, full half-torus basis
    def gram_4x2(pp, qq, rr):
        # sites (i, j), i in Z/4, j in Z/2; reflection theta(i, j) = (3 - i, j) through the bond planes between i=1,2 and i=3,0
        halfs = list(itertools.product(range(6), repeat=4))          # (c0_0, c0_1, c1_0, c1_1): columns 0 and 1, rows 0 and 1
        idx = {h: n for n, h in enumerate(halfs)}
        wA = np.zeros(len(halfs))
        for h in halfs:
            c0, c1 = h[:2], h[2:]
            w = K(c0[0], c0[1], pp, qq, rr) * K(c1[0], c1[1], pp, qq, rr)      # vertical bonds (2 rows: one bond per column)
            w *= K(c0[0], c1[0], pp, qq, rr) * K(c0[1], c1[1], pp, qq, rr)      # the horizontal bond inside the half
            wA[idx[h]] = w
        # crossing bonds: column 1 of A with its mirror (column 2 = mirror of column 1), and column 0 with its mirror (column 3)
        Kmat = np.array([[K(i, j, pp, qq, rr) for j in range(6)] for i in range(6)], float)
        M = np.zeros((len(halfs), len(halfs)))
        arr = np.array(halfs)
        for n, h in enumerate(halfs):
            cross = (Kmat[h[2], arr[:, 2]] * Kmat[h[3], arr[:, 3]] * Kmat[h[0], arr[:, 0]] * Kmat[h[1], arr[:, 1]])
            M[n] = wA[n] * wA * cross
        M /= M.sum()
        return M
    res1 = []
    okn = True
    for (pp, qq, rr) in ((3, 1, 2), (5, 1, 2), (4, 1, 1), (2, 1, 2)):
        M = gram_4x2(pp, qq, rr)
        lam = np.linalg.eigvalsh((M + M.T) / 2)
        inside = pp >= qq and pp + qq >= 2 * rr
        res1.append((pp, qq, rr, inside, lam.min(), lam.max()))
        okn &= (lam.min() > -1e-12 * max(1.0, lam.max())) == inside
    check("N1", okn, "(numerical, labelled) 4 x 2 torus, the full Gram matrix of <F theta(G)> over the 1296 indicators of the half-torus "
          "configurations: " + "; ".join(f"(p,q,r)=({pp},{qq},{rr}) {'inside' if ins else 'outside'} the region: smallest eigenvalue "
          f"{lo:+.3e} (largest {hi:.3e})" for pp, qq, rr, ins, lo, hi in res1) +
          " - positive semidefinite exactly on the region p >= q, p + q >= 2r")

    # ---------------- N2: 4 x 4 torus, column basis by transfer matrices
    cols = list(itertools.product(range(6), repeat=4))
    arr = np.array(cols)
    res2 = []
    okn2 = True
    for (pp, qq, rr) in ((3, 1, 2), (5, 1, 2), (4, 1, 1), (2, 1, 2)):
        Kmat = np.array([[K(i, j, pp, qq, rr) for j in range(6)] for i in range(6)], float)
        A = np.array([Kmat[c[0], c[1]] * Kmat[c[1], c[2]] * Kmat[c[2], c[3]] * Kmat[c[3], c[0]] for c in cols])
        T = np.ones((len(cols), len(cols)))
        for row in range(4):
            T *= Kmat[np.ix_(arr[:, row], arr[:, row])]
        U = (A[:, None] * T)
        Z = np.trace(np.linalg.matrix_power(U, 4))
        back = T @ np.diag(A) @ T @ np.diag(A) @ T       # [T D T D T](c2, c1)
        M = (A[:, None] * T * A[None, :]) * back.T / Z
        lam = np.linalg.eigvalsh((M + M.T) / 2)
        inside = pp >= qq and pp + qq >= 2 * rr
        res2.append((pp, qq, rr, inside, lam.min(), lam.max()))
        okn2 &= (lam.min() > -1e-9 * max(1.0, lam.max())) == inside
    check("N2", okn2, "(numerical, labelled) 4 x 4 torus, the Gram matrix over the 1296 indicators of the column next to the plane (transfer "
          "matrices): " + "; ".join(f"(p,q,r)=({pp},{qq},{rr}) {'inside' if ins else 'outside'}: smallest eigenvalue {lo:+.3e} "
          f"(largest {hi:.3e})" for pp, qq, rr, ins, lo, hi in res2) + " - the same region")

    print("=" * 90)
    if FAILS:
        print(f"SUMMARY: FAILED checks {FAILS}")
        return 0
    site_frac = ", ".join(f"L={L} d={d}: {os}/{n}" for L, d, n, os, ob, obo in rows)
    print("SUMMARY: site-plane reflections move a direction-1 bond over half the direction-1 bonds in 2D and a quarter in 3D (" + site_frac +
          "), bond-plane reflections over a half in both dimensions, and the two families together are transitive; reflection positivity "
          "through a bond plane holds exactly on p >= q and p + q >= 2r (eigenvalues p+q+4r, p-q thrice, p+q-2r twice), i.e. p >= 3 on the "
          "line (p, 1, 2), and the Gram matrices on the 4 x 2 and 4 x 4 tori are positive semidefinite inside that region and indefinite at "
          "(2, 1, 2) outside it")
    print("HIT: the task's expectation that bond-plane reflections reach ALL direction-1 bonds is wrong: they reach exactly half of them in "
          "both dimensions (" + ", ".join(f"L={L} d={d}: {ob}/{n}" for L, d, n, os, ob, obo in rows) + "), because a bond-plane reflection in "
          "direction 1 maps the base x_1 to 2k - x_1 and preserves its parity; transitivity needs both families (site and bond planes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
