#!/usr/bin/env python3
"""deferred-20260924-formation-packets, first pass (worker w-macbookpro9927a-jb986, claude-opus-5-5).

PR8635's excluded cooling source: local Rokhsar-Kivelson (RK) cooling of the record-ring (link) model by the jumps
L_p = (1/2) m_p on the flip pairs of each plaquette.  Recovered here and turned into a parameter-free statement:
the RK state is the unique stationary state for every positive rate vector and every Hermitian H with H u = 0 as soon
as u is a cyclic vector of the algebra generated by the L_p^T.  Exact integer / modular arithmetic throughout; ranks
modulo a prime are lower bounds for rational ranks and are always paired with an exact upper bound.
"""
import hashlib
import subprocess
import sys
import time
from itertools import combinations, product

import numpy as np
import sympy as sp

T0 = time.time()
FAILS = []


def check(tag, ok, msg=""):
    print(("PASS " if ok else "FAIL ") + tag + (": " + msg if msg else ""))
    if not ok:
        FAILS.append(tag)


# ================================================================= V: the frozen sources, verified against the manifest
HEAD = "ff1edc030d8a2aaec9aab16a2354e7cc113ef8cf"
SRC = ".claude/science/mobile-record-formation-20260920/campaign12h_third/"
pins = [(HEAD, SRC + "local_gauge_record_cooling_check.py", "9faf0f87d0574368feb0f656308308c269d3df922bfff7576a8d6d10182b5552"),
        (HEAD, SRC + "LOCAL_FIELD_PUBLICATION_README.md", "920f0bfd9b8e"),
        ("origin/main", "scripts/local_gauge_record_cooling_check.py", "1dfd370af4b92bcff307a91314e610750e7b7961184a547f2f33d094027a8282")]
okV = True
got = []
for ref, path, want in pins:
    try:
        blob = subprocess.run(["git", "show", ref + ":" + path], capture_output=True, check=True).stdout
        h = hashlib.sha256(blob).hexdigest()
        okV &= h.startswith(want)
        got.append(h[:12])
    except subprocess.CalledProcessError:
        okV = False
        got.append("missing")
check("V1 frozen sources", okV, "original helper %s (manifest 9faf0f87d057), README %s, landed extract on main %s (manifest "
      "1dfd370af4b9)" % tuple(got))


# ================================================================= A: the recovered local algebra (one flip pair and a spectator)
l = sp.Matrix([[1, -1, 0], [1, -1, 0], [0, 0, 0]]) / 2       # L = |+><-| on the pair (0,1), spectator 2
Pm, Pp, I3 = l.T * l, l * l.T, sp.eye(3)
a_, b_ = sp.symbols("a b", positive=True)


def chan(q):   # the pair channel in the original's vec convention: K0 (x) K0 + (1 - q^2) L (x) L, K0 = 1 + (q - 1)P-
    K0 = I3 + (q - 1) * Pm
    return sp.kronecker_product(K0, K0) + (1 - q ** 2) * sp.kronecker_product(l, l)


D = sp.kronecker_product(l, l) - (sp.kronecker_product(I3, Pm) + sp.kronecker_product(Pm, I3)) / 2
okA = (l * l == sp.zeros(3) and Pm ** 2 == Pm and Pp ** 2 == Pp and Pm * Pp == sp.zeros(3)
       and (chan(a_) * chan(b_) - chan(a_ * b_)).applyfunc(sp.expand) == sp.zeros(9)
       and (-sp.diff(chan(a_), a_).subs(a_, 1) / 2 - D).applyfunc(sp.expand) == sp.zeros(9))
check("A1 recovered local algebra", okA, "L = |+><-| is a partial isometry with L^2 = 0; the pair channels compose, "
      "Phi_a Phi_b = Phi_ab; -d/da Phi_a at a = 1, halved, is the dissipator D[L]")


# ================================================================= the ring model: geometry, flip graph, jumps
def geometry(shape, periodic):
    nd = len(shape)
    verts = list(product(*[range(n) for n in shape]))
    vset = set(verts)

    def sh(v, a):
        q = list(v)
        q[a] += 1
        if periodic:
            q[a] %= shape[a]
        q = tuple(q)
        return q if q in vset else None

    edges = [(v, a, sh(v, a)) for v in verts for a in range(nd) if sh(v, a) is not None]
    ei = {(v, a): j for j, (v, a, w) in enumerate(edges)}
    faces = []
    for v in verts:
        for a, b in combinations(range(nd), 2):
            va, vb = sh(v, a), sh(v, b)
            if va is None or vb is None or (va, b) not in ei or (vb, a) not in ei:
                continue
            raised = (ei[(v, a)], ei[(va, b)])
            lowered = (ei[(vb, a)], ei[(v, b)])
            if len(set(raised + lowered)) < 4:
                continue
            faces.append((sum(1 << e for e in raised), sum(1 << e for e in lowered), raised, lowered))
    return edges, faces


def components(ne, faces):
    seen = bytearray(1 << ne)
    out = []
    for s0 in range(1 << ne):
        if seen[s0]:
            continue
        seen[s0] = 1
        comp, stack = [s0], [s0]
        while stack:
            c = stack.pop()
            for r, lo, _, _ in faces:
                if (c & r == 0 and c & lo == lo) or (c & r == r and c & lo == 0):
                    d = c ^ r ^ lo
                    if not seen[d]:
                        seen[d] = 1
                        comp.append(d)
                        stack.append(d)
        out.append(sorted(comp))
    return out


def flip_pairs(states, faces):   # per plaquette: oriented pairs (a -> b), b = a with the plaquette raised
    idx = {c: i for i, c in enumerate(states)}
    rows = []
    for r, lo, _, _ in faces:
        row = [(idx[c], idx[c ^ r ^ lo]) for c in states if c & r == 0 and c & lo == lo]
        if row:
            rows.append(row)
    return rows


P = 2147483647


def rank_modp(M, p=None):
    p = P if p is None else p
    M = np.array(M, dtype=np.int64) % p
    n, m = M.shape
    r = 0
    for c in range(m):
        if r == n:
            break
        nz = np.nonzero(M[r:, c])[0]
        if len(nz) == 0:
            continue
        pr = r + nz[0]
        if pr != r:
            M[[r, pr]] = M[[pr, r]]
        M[r] = (M[r] * pow(int(M[r, c]), p - 2, p)) % p
        rows = np.nonzero(M[:, c])[0]
        rows = rows[rows != r]
        if len(rows):
            M[rows] = (M[rows] - np.outer(M[rows, c], M[r]) % p) % p
        r += 1
    return r


def cyclic_dim(d, rows):   # dim of span{ w 1 : w a word in the B_q = m_q^T }, B_q x = sum_pairs (x_a + x_b)(e_a - e_b)
    def B(row, x):
        y = np.zeros(d, dtype=np.int64)
        for a, b in row:
            s = (x[a] + x[b]) % P
            y[a] = (y[a] + s) % P
            y[b] = (y[b] - s) % P
        return y
    basis = [np.ones(d, dtype=np.int64)]
    frontier = list(basis)
    rk = 1
    while frontier and rk < d:
        new = [B(row, x) for x in frontier for row in rows]
        cand = np.array(basis + new)
        r2 = rank_modp(cand)
        if r2 == rk:
            break
        # keep an independent set: greedy
        keep = list(basis)
        for v in new:
            if rank_modp(np.array(keep + [v])) > len(keep):
                keep.append(v)
        frontier = keep[len(basis):]
        basis = keep
        rk = len(basis)
    return rk


# ================================================================= F and U over every component of seven geometries
geoms = [((2, 2), False), ((3, 2), False), ((2, 2, 2), False), ((3, 3), False), ((4, 2), False), ((4, 3), False),
         ((2, 2), True), ((3, 2), True), ((3, 3), True)]
tot = cyc = sepok = conn = 0
maxd = 0
per_geom = []
for shape, per in geoms:
    edges, faces = geometry(shape, per)
    comps = components(len(edges), faces)
    nbig = 0
    for st in comps:
        d = len(st)
        if d < 2:
            continue
        rows = flip_pairs(st, faces)
        tot += 1
        nbig += 1
        maxd = max(maxd, d)
        # separating function F2 = sum_j 3^j (2 c_j - 1): injective, constant displacement per plaquette
        F = [sum(3 ** j * (2 * ((c >> j) & 1) - 1) for j in range(len(edges))) for c in st]
        okF = len(set(F)) == d
        ix = {c: i for i, c in enumerate(st)}
        fi = 0
        for r, lo, raised, lowered in faces:
            prs = [(ix[c], ix[c ^ r ^ lo]) for c in st if c & r == 0 and c & lo == lo]
            if prs:
                delta = 2 * (sum(3 ** e for e in raised) - sum(3 ** e for e in lowered))
                okF &= all(F[j] - F[i] == delta for i, j in prs) and delta != 0
        sepok += okF
        # connectivity of the flip graph: the common kernel of the jumps is the constants (rank of stacked m_q = d - 1)
        stack = []
        for row in rows:
            m = np.zeros((d, d), dtype=np.int64)
            for a, b in row:
                m[a, a] += 1; m[b, a] += 1; m[a, b] -= 1; m[b, b] -= 1
            stack.append(m)
        conn += rank_modp(np.vstack(stack)) == d - 1
        cyc += cyclic_dim(d, rows) == d
    per_geom.append("%s%s:%d" % ("x".join(map(str, shape)), "p" if per else "o", nbig))
check("F1 separating function", sepok == tot, "F2 = sum_j 3^j s_j is injective with a constant non-zero displacement "
      "per plaquette on all %d components (d >= 2) of %s" % (tot, ", ".join(per_geom)))
check("U1 cyclic dark vector", cyc == tot and conn == tot, "on every one of them (d up to %d) the all-ones vector is cyclic "
      "for the algebra of the m_q^T (rank mod p = d = dimension) and the jumps' common kernel is the constants" % maxd)


# ================================================================= R: the original's finite control, reproduced independently
def lindblad_int(rows, d, gam, hh):   # 8G for L_q = m_q/2, H = sum h_q P_q^-, vec convention of the original
    I = np.eye(d, dtype=np.int64)
    re = np.zeros((d * d, d * d), dtype=np.int64)
    h8 = np.zeros((d, d), dtype=np.int64)
    for q, row in enumerate(rows):
        m = np.zeros((d, d), dtype=np.int64)
        for a, b in row:
            m[a, a] += 1; m[b, a] += 1; m[a, b] -= 1; m[b, b] -= 1
        pm4 = m.T @ m                                   # = 4 P_q^-
        re += gam[q] * (2 * np.kron(m, m) - np.kron(I, pm4) - np.kron(pm4, I))
        h8 += 2 * hh[q] * pm4
    im = -(np.kron(I, h8) - np.kron(h8.T, I))
    return re, im


okR = True
dims = []
for shape in [(2, 2), (3, 2), (2, 2, 2)]:
    edges, faces = geometry(shape, False)
    comps = [c for c in components(len(edges), faces)]
    st = max(comps, key=len)
    d = len(st)
    rows = flip_pairs(st, faces)
    gam = [q + 1 for q in range(len(rows))]
    hh = [(-1) ** q * (q + 2) for q in range(len(rows))]
    re, im = lindblad_int(rows, d, gam, hh)
    p2 = 65537                                          # 256^2 = -1 mod p2: a square root of -1
    M = (re + 256 * im) % p2
    rk = rank_modp(M, p2)
    one = np.ones(d * d, dtype=np.int64)
    okR &= rk == d * d - 1 and not np.any(re @ one) and not np.any(im @ one)
    dims.append(d)
check("R1 original finite control", okR, "largest components of the open 2x2, 3x2, 2x2x2 boxes (d = %s), rates p+1 and "
      "h_p = (-1)^p (p+2): 8G has rank d^2 - 1 mod 65537 and annihilates vec(u u^T) exactly: nullity one" % dims)

# ================================================================= C: the countercontrol, where the dark vector is not cyclic
rows_c = [[(0, 1), (2, 3)], [(1, 2), (3, 0)]]
cd_ = cyclic_dim(4, rows_c)
m1 = sp.zeros(4); m2 = sp.zeros(4)
for (mm, row) in ((m1, rows_c[0]), (m2, rows_c[1])):
    for a, b in row:
        mm[a, a] += 1; mm[b, a] += 1; mm[a, b] -= 1; mm[b, b] -= 1
L1, L2 = m1 / 2, m2 / 2
v = sp.Matrix([1, 1, -1, -1]) / 2
w = sp.Matrix([-1, 1, 1, -1]) / 2
rho = (v * v.T + w * w.T) / 2


def dissip(Lm, r):
    return Lm * r * Lm.T - (Lm.T * Lm * r + r * Lm.T * Lm) / 2


okC = cd_ == 2 and (dissip(L1, rho) + dissip(L2, rho)) == sp.zeros(4) and L1 * sp.ones(4, 1) == sp.zeros(4, 1) and \
    L2 * sp.ones(4, 1) == sp.zeros(4, 1)
check("C1 countercontrol", okC, "the original's four-state alternating cycle: connected with a unique common dark vector, "
      "but the cyclic span of u is 2-dimensional, and (vv^T + ww^T)/2 is a second stationary state; no separating F exists "
      "there (F(2) = F(0) is forced)")

print("time %.0f s" % (time.time() - T0))
if FAILS:
    print("SUMMARY: ROUTE FAILS AT " + ", ".join(FAILS))
    sys.exit(1)
print("SUMMARY: PARTIAL. Recovered PR8635's excluded local RK cooling (jumps L_p = m_p/2 on the flip pairs of each plaquette "
      "of the record-ring model, H = sum h_p P_p^-) and its finite control (nullity one at one parameter point on three open "
      "boxes, reproduced). New and exact: (i) the RK state |u><u| is the unique stationary state for EVERY rate vector "
      "gamma > 0 and EVERY Hermitian H with H u = 0 whenever u is a cyclic vector of the algebra generated by the L_p^T "
      "(proof: a stationary state's support is invariant under the jumps and orthogonal to every L_p^T u); (ii) cyclicity "
      "holds on all %d components of nine open and periodic boxes, and the separating F2 exists on all of them; (iii) the "
      "countercontrol fails exactly cyclicity. Open: the missing note's 'separating F implies convergence' in general." % tot)
print("HIT: in the record-ring model's local RK cooling, the RK state is the unique stationary state for every positive rate "
      "vector and every Hermitian H annihilating it as soon as the uniform vector is cyclic for the algebra of the "
      "transposed jumps; this holds exactly on all %d flip components of nine small open and periodic boxes (up to 4x3 open and 3x3 periodic), replacing "
      "the frozen source's single-parameter control" % tot)
