import json,hashlib,subprocess
from pathlib import Path
R=Path('/private/tmp/review-drain-20260915'); repo=R/'integration-resume'; sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
inv=json.load(open(R/'drain8028-original-inventory.json')); orig=R/'drain8028-originals'; note='docs/GAUGE_WILSON_UNIFORM_STATIC_SOURCE_ENERGY_BOUNDS_BOUNDED_THEOREM_NOTE_2026-09-07.md'
rows=[]
for x in inv['original_paths']:
 p=x['path']; y=dict(x)
 if p.startswith('.claude/'):
  d='Preserve exact historical payload; no historical audit/review verdict imported as current authority.'
  if p.endswith(('DERIVATION.md','PRIMARY_REVIEW.md')):d+=' Full mathematical argument read; canonical proof covers durable result, root derivation additionally makes nonnegativity explicit.'
 elif p.startswith('docs/audit/data/'):d='Exclude generated audit authority from live proposal; preserve exact original historically.'
 elif p in ('docs/audit/scripts/build_citation_graph.py','scripts/audit_packet_script_deps.py'):d='Port only original single claim-helper mapping into current-main union; never overwrite repaired current tool.'
 elif p.startswith('logs/'):d='Preserve original historical cache; regenerate canonical cache only after corrected source/input freeze.'
 else:d='Retain complete mathematical content with finding-scoped reproducibility/history corrections; final candidate confirmation pending.'
 y['disposition']=d;rows.append(y)
parents=['docs/GAUGE_WILSON_FULL_CUBE_COMPACT_INTERACTING_HAMILTONIAN_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-07.md','docs/GAUGE_WILSON_COMPACT_CUBE_LOW_ELECTRIC_SPECTRUM_RITZ_GAP_BOUNDED_THEOREM_NOTE_2026-09-07.md','docs/GAUGE_WILSON_STATIC_SOURCE_GEODESIC_PERTURBATION_BOUNDED_THEOREM_NOTE_2026-09-07.md']
parentmap={}
for p in parents[:2]:parentmap[p]={'sha256':hashlib.sha256(subprocess.check_output(['git','show','49777d85533d8403cd3e30471e1123bc2c05fd56:'+p],cwd=repo)).hexdigest(),'context':'current main at review start; exact same-session premise read reused'}
prior=json.load(open(R/'drain8027-final-review.json'))
# Prior final record supplies exact accepted pending parent bytes.
parentmap[parents[2]]={'context':'Reviewed corrected PR8027, pending landing at review start; must bind actual author candidate parent before capture','prior_report':str(R/'drain8027-final-review.json'),'prior_report_sha256':sha(R/'drain8027-final-review.json')}
findings=[{'id':'F1','repair':'Add literal own-note plus all three actual parent proof-identity AUDIT_INPUT_PATHS to both standalone runners; retain180s/180MiB. Pins are proof identity, not runtime data reads.'},{'id':'F2','repair':'Canonical TOTAL: PASS=32 FAIL=0 and PASS=42 FAIL=0; each includes one resource predicate. Add canonical cache links and recapture each once after cold confirmation.'},{'id':'F3','repair':'Durably preserve all76 original versions including68 history entries, syntax failure and generated authority; replace .claude historical links and frame old author/review/timing claims as historical.'},{'id':'F4','repair':'Port honest N1–N8 applicability/scope with analytical imported theorem versus finite controls; no universal no-go PASS, numerical threshold, thermodynamic potential or physically selected source claim. Keep all quantitative mathematics.'},{'id':'F5','repair':'Make E_xy>=E0 explicit by restriction of H_full tensor identity to charged sector, as already given in full historical root derivation; no new hypothesis.'},{'id':'F6','repair':'Add only exact helper mapping in both current tools preserving all current entries and verify both actual discovery APIs.'}]
proof={
'full_closure':'Full canonical/native/root derivations, independent historical reviews/preregistrations, both canonical runners and historical code differences read. No material mathematical defect found.',
'free_support':'Peter–Weyl occupied components and simultaneous center Gauss action force both endpoint trialities into one occupied component; >=L occupied links each cost4/a. This includes arbitrary reps and baryonic intertwiners.',
'import':'Actual primary Yarotsky math-ph/0411042v1 section2 equations7–15 read, especially energyregular creation estimate8 and weighted column estimate14. Inhomogeneous bounded finite-range perturbations and infinite-dimensional onsite spaces covered; translation invariance not needed here.',
'sector':'Unique normalized ground and unique exponential creation coordinates imply each coefficient invariant under product gauge action. S and inverse intertwine charged sector. Finite-volume energyregular coefficients give bounded commutators/domain preservation.',
'ghost':'Product ghost-vacuum ground and uniqueness imply each creation coefficient vacuum on ghosts; creation operators commute each ghost-vacuum projector. Joint charged/ghost sector retains actual graph distance, no shortcut.',
'amplification_resolvent':'Nine endpoint components cost sqrt9=3 by triangle/Cauchy. On charged blocks H0>=L; eta*L/(L-z)<1 yields Neumann inverse below(1-eta)L. Finite-volume bounded similarity and norm equivalence suffice; no uniform similarity norm claimed.',
'upper':'Unique positive neutral full ground times normalized path matrix has unit total pointwise norm. Traceless-generator cross term vanishes for both orientations and Casimir8/3 gives4/a per simple-path edge; potential unchanged. Restriction gives nonnegativity.',
'scope':'Supplied compactSU3 Hamiltonian and supplied static fundamental probes; finite actual subgraphs, existential small-r threshold uniform in graph size/distance. No framework selection, explicit physical tension, temporal-loop equality, continuum or infinite-volume potential existence.',
'negative_discipline':'Quantitative lower/upper bounds and exact sector/representation support reasoning are directly proved. Historical failed alternatives/toys do not certify a broad negative packet. N1–N8 must state this scope honestly; no substantive mathematical result requires deferral.'}
pdf=R/'check8028/yarotsky.pdf'; txt=R/'check8028/yarotsky.txt';external={'url':'https://arxiv.org/pdf/math-ph/0411042v1','downloaded_pdf':str(pdf),'pdf_sha256':sha(pdf),'extracted_text':str(txt),'text_sha256':sha(txt),'read_scope':'Finite-volume hypotheses and section2 equations7–15 actually read; later quasiparticle assertions not imported.'}
(R/'check8028/external-provenance.json').write_text(json.dumps(external,indent=2)+'\n')
out={'status':'ORIGINAL SCIENCE REVIEW COMPLETE; FINDING-SCOPED REPAIRS AND FINAL CAPTURES PENDING','reviewer_session':'/root/review_8012','head':inv['head'],'delta_base':inv['delta_base'],'review_base':'49777d85533d8403cd3e30471e1123bc2c05fd56','original_dispositions':rows,'findings':findings,'proof_review':proof,'inputs':{'repository_parents':parentmap,'authority':json.load(open(R/'drain8028-authority-reuse.json')),'external_mathematics':external,'original_science_hashes':{x['path']:x['sha256'] for x in inv['original_paths'] if x['path']==note or x['path'].startswith('scripts/gauge_')}},'independent_controls':{'program':str(R/'check8028/control.py'),'program_sha256':sha(R/'check8028/control.py'),'receipt':str(R/'check8028/control.json'),'receipt_sha256':sha(R/'check8028/control.json'),'passed':16,'boundary':'Independent finite exact algebra, no original runner imports or executions; not a proof of the imported coordinate theorem.'},'resource_plan':{'primary_and_helper':'Two sequential standalone captures after source cold confirmation, each180s/180MiB process-tree resource monitoring','expected_counts':[32,42],'resource_predicates_in_counts':[1,1],'no_primary_executed_by_reviewer':True},'current_main_preservation':'Only new note/two runners/caches/history plus additive two helper map entries. Original generated graph authority not transplanted. Actual 8027 landing/input identities to check at author freeze.','closure':'All unique durable mathematical content suitable for acceptance after listed repairs and exact source/input confirmation; no substantive unique science identified for deferral. Original review is not final source PASS.','references':{str(R/'drain8028-original-inventory.json'):sha(R/'drain8028-original-inventory.json'),str(R/'drain8028-review-fetch.json'):sha(R/'drain8028-review-fetch.json'),str(R/'check8028/history-payload-inventory.json'):sha(R/'check8028/history-payload-inventory.json')},'no_source_edits':True}
f=R/'drain8028-original-review.json';assert not f.exists();f.write_text(json.dumps(out,indent=2)+'\n')
(R/'drain8028-original-review.md').write_text('# PR8028 original review\n\nFull mathematical review complete. No material mathematical defect found. Final source acceptance awaits reproducibility and historical-scope repairs plus two bounded captures.\n\nThe actual imported coordinate estimate supports the charged-sector resolvent argument; gauge equivariance, domain preservation and ghost restriction are justified. The path-matrix Dirichlet upper bound is valid at all finite couplings. Sixteen independent exact algebra controls passed.\n\nAll 76 original paths have explicit dispositions in the JSON report. Preserve all original mathematics/history; do not transplant generated audit authority or overwrite current helper maps.\n\n'+ '\n'.join('- '+x['id']+': '+x['repair'] for x in findings)+'\n')
print(f,sha(f))
