"""Refuting pass, block 18 (supervisor seat, disjoint machinery from the runner's checks):
(R1) the cube's rotation group generated from two generators (a 90-degree rotation about z and a 120-degree rotation about the
     (1,1,1) diagonal) instead of enumerating signed permutations; group order and orbit sizes recomputed;
(R2) the stabilizer classification from the rotation axes directly: the fixed unit directions of each nontrivial rotation are
     collected and compared with the 26 axis points (6 + 8 + 12);
(R3) the frame's equivariance with a second rotation (a rational rotation about the (1,1,1) axis is not rational; use the
     signed permutation (x,y,z) -> (y,z,x), an element of the cube group) and a second pair;
(R4) M1 by a symbolic rotation angle: the orbit map theta -> R_theta s is injective on [0, 2 pi) iff the orthogonal component of s
     is nonzero (the map's derivative in theta has norm equal to that component).
Run from the pack: the runner is imported from the repository's scripts/ directory."""
import importlib
import sys
from itertools import product
from pathlib import Path

import sympy as sp

ROOT = Path(__file__).resolve().parents[5]
sys.path.insert(0, str(ROOT / "scripts"))
r18 = importlib.import_module("admissibility_rule_menus_neighbour_generated_supports_and_cube_orbit_menus_2026_09_15")
def mm(A, B):
    return tuple(tuple(sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)) for i in range(3))
gz = ((0, -1, 0), (1, 0, 0), (0, 0, 1))          # 90 degrees about z
gd = ((0, 0, 1), (1, 0, 0), (0, 1, 0))           # (x,y,z) -> (z,x,y): 120 degrees about (1,1,1)
I3 = ((1, 0, 0), (0, 1, 0), (0, 0, 1))
G = {I3}
frontier = [I3]
while frontier:
    new = []
    for A in frontier:
        for g in (gz, gd):
            B = mm(g, A)
            if B not in G:
                G.add(B); new.append(B)
    frontier = new
print("R1 group generated by two rotations has order", len(G), "; equals the signed-permutation enumeration:", G == set(r18.rotations()))
def apply(Mx, v):
    return tuple(sum(Mx[i][j] * v[j] for j in range(3)) for i in range(3))
sizes = {v: len({apply(Mx, v) for Mx in G}) for v in ((1, 0, 0), (1, 1, 1), (1, 1, 0), (1, 2, 3))}
print("R1 orbit sizes from the generated group:", sizes)
# R2: fixed directions of nontrivial rotations
fixed = set()
for Mx in G:
    if Mx == I3:
        continue
    A = sp.Matrix(Mx) - sp.eye(3)
    ns = A.nullspace()
    assert len(ns) == 1
    v = ns[0]
    v = v / sp.gcd(list(v))
    v = tuple(int(x) for x in v)
    fixed.add(v); fixed.add(tuple(-x for x in v))
def norm_dir(v):
    g = sp.gcd(list(v)); return tuple(int(x / g) for x in v)
axes = {norm_dir(apply(Mx, (1, 0, 0))) for Mx in G} | {norm_dir(apply(Mx, (1, 1, 1))) for Mx in G} | {norm_dir(apply(Mx, (1, 1, 0))) for Mx in G}
print("R2 fixed directions of the 23 nontrivial rotations:", len(fixed), "; equal to the 26 axis points (6 + 8 + 12):", fixed == axes, len(axes))
# R3 frame equivariance with a cube-group element and another pair
q1 = sp.Matrix([sp.Rational(3, 5), sp.Rational(4, 5), 0]); q2 = sp.Matrix([0, sp.Rational(5, 13), sp.Rational(12, 13)])
def frame(a, b):
    e1 = a; e2 = b - (a.dot(b)) * a; e2 = e2 / sp.sqrt(e2.dot(e2)); return sp.Matrix.hstack(e1, e2, e1.cross(e2))
g = sp.Matrix(gd)
print("R3 frame equivariance under the cube rotation (x,y,z)->(z,x,y) on a second pair:", sp.simplify(frame(g * q1, g * q2) - g * frame(q1, q2)) == sp.zeros(3, 3))
# R4 symbolic angle
th = sp.symbols("theta", real=True)
Rth = sp.Matrix([[sp.cos(th), -sp.sin(th), 0], [sp.sin(th), sp.cos(th), 0], [0, 0, 1]])
a, b, c = sp.symbols("a b c", real=True)
s_ = sp.Matrix([a, b, c])
d = sp.simplify((Rth * s_).diff(th))
print("R4 |d/dtheta (R_theta s)|^2 =", sp.simplify(d.dot(d)), "= a^2 + b^2: the orbit is a circle of that radius, degenerate iff the orthogonal component vanishes")
