#!/usr/bin/env python3
"""Render the repo-front-door status snapshot from audit pipeline outputs."""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DATA_DIR = REPO_ROOT / "docs" / "audit" / "data"
OUT_PATH = REPO_ROOT / "docs" / "repo" / "FRONT_DOOR_STATUS.md"
DIVERGENCE_PATH = (
    REPO_ROOT
    / "docs"
    / "publication"
    / "ci3_z3"
    / "PUBLICATION_AUDIT_DIVERGENCE.md"
)


def load_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def status_counts() -> tuple[dict[str, int], int, int]:
    summary = load_json(DATA_DIR / "effective_status_summary.json")
    counts = summary["effective_status_counts"]
    boxed_decorations = sum(
        value for status, value in counts.items() if status.startswith("decoration_under_")
    )
    retained_grade = (
        counts.get("retained", 0)
        + counts.get("retained_no_go", 0)
        + counts.get("retained_bounded", 0)
        + boxed_decorations
    )
    return counts, boxed_decorations, retained_grade


def publication_gap_summary() -> tuple[int | None, list[tuple[str, str, int]]]:
    if not DIVERGENCE_PATH.exists():
        return None, []
    text = DIVERGENCE_PATH.read_text(encoding="utf-8")
    total_match = re.search(
        r"Total non-retained-grade rows in publication tables:\*\*\s+(\d+)",
        text,
    )
    total = int(total_match.group(1)) if total_match else None
    rows: list[tuple[str, str, int]] = []
    in_summary = False
    for line in text.splitlines():
        if line.startswith("## Summary by criticality"):
            in_summary = True
            continue
        if in_summary and line.startswith("## "):
            break
        if not in_summary or not line.startswith("| "):
            continue
        parts = [part.strip() for part in line.strip("|").split("|")]
        if len(parts) != 3 or parts[0] in {"criticality", "---"}:
            continue
        try:
            rows.append((parts[0], parts[1].strip("`"), int(parts[2])))
        except ValueError:
            continue
    return total, rows


def table(rows: list[tuple[str, str | int]]) -> str:
    out = ["| Metric | Value |", "|---|---:|"]
    for key, value in rows:
        out.append(f"| {key} | {value} |")
    return "\n".join(out)


def main() -> None:
    counts, boxed_decorations, retained_grade = status_counts()
    summary = load_json(DATA_DIR / "effective_status_summary.json")
    queue = load_json(DATA_DIR / "audit_queue.json")
    load_bearing = load_json(DATA_DIR / "load_bearing_summary.json")
    ledger = load_json(DATA_DIR / "audit_ledger.json")
    divergence_total, divergence_rows = publication_gap_summary()

    rows = ledger.get("rows", {})
    total_rows = len(rows)
    applied_audits = sum(
        1
        for row in rows.values()
        if row.get("audit_status") not in {None, "unaudited", "audit_in_progress"}
    )
    ready = [row for row in queue.get("queue", []) if row.get("ready")]

    lines: list[str] = [
        "<!-- AUTO-GENERATED by docs/audit/scripts/render_front_door_status.py -->",
        "<!-- generated: pipeline-derived -->",
        "",
        "# Front Door Status Snapshot",
        "",
        "**Auto-generated.** Refresh with `bash docs/audit/scripts/run_pipeline.sh`.",
        "This file summarizes the generated audit state that the root README links to.",
        "It is not a physics claim surface and should not be edited by hand.",
        "",
        "## Audit Surface",
        "",
        table(
            [
                ("Ledger rows", total_rows),
                ("Applied audit verdicts", applied_audits),
                ("Retained-grade rows, including boxed decorations", retained_grade),
                ("Retained positive theorems", counts.get("retained", 0)),
                ("Retained no-go rows", counts.get("retained_no_go", 0)),
                ("Retained bounded rows", counts.get("retained_bounded", 0)),
                ("Boxed decorations under retained parents", boxed_decorations),
                ("Open gates", counts.get("open_gate", 0)),
                ("Unaudited rows", counts.get("unaudited", 0)),
                ("Retained-pending-chain rows", summary.get("retained_pending_chain_count", 0)),
                ("Audited conditional rows", counts.get("audited_conditional", 0)),
                ("Audited renaming rows", counts.get("audited_renaming", 0)),
                ("Audited numerical-match rows", counts.get("audited_numerical_match", 0)),
                ("Citation cycles detected", summary.get("cycles_detected", 0)),
            ]
        ),
        "",
        "Source: [`docs/audit/AUDIT_LEDGER.md`](../audit/AUDIT_LEDGER.md) and",
        "[`docs/audit/data/effective_status_summary.json`](../audit/data/effective_status_summary.json).",
        "",
        "## Audit Queue",
        "",
        table(
            [
                ("Total pending rows", queue.get("total_pending", 0)),
                ("Ready rows", queue.get("ready_count", 0)),
                ("Cycle-break targets", queue.get("cycle_break_target_count", 0)),
                ("Critical pending", queue.get("by_criticality", {}).get("critical", 0)),
                ("High pending", queue.get("by_criticality", {}).get("high", 0)),
                ("Medium pending", queue.get("by_criticality", {}).get("medium", 0)),
                ("Leaf pending", queue.get("by_criticality", {}).get("leaf", 0)),
            ]
        ),
        "",
        "Next ready rows by queue order:",
        "",
    ]
    if ready:
        for row in ready[:8]:
            note_path = row.get("note_path")
            if note_path:
                target = f"[`{row['claim_id']}`](../../{note_path})"
            else:
                target = f"`{row['claim_id']}`"
            lines.append(
                f"- {target} - {row.get('criticality', 'unknown')}; "
                f"{row.get('queue_reason', 'queued')}"
            )
    else:
        lines.append("- none")

    lines.extend(
        [
            "",
            "Source: [`docs/audit/AUDIT_QUEUE.md`](../audit/AUDIT_QUEUE.md) and",
            "[`docs/audit/data/audit_queue.json`](../audit/data/audit_queue.json).",
            "",
            "## Publication Gap",
            "",
        ]
    )
    if divergence_total is not None:
        lines.append(
            f"- Non-retained-grade cited rows in publication tables: **{divergence_total}**."
        )
        if divergence_rows:
            lines.append("")
            lines.append("| Criticality | Effective status | Count |")
            lines.append("|---|---|---:|")
            for criticality, status, count in divergence_rows[:12]:
                lines.append(f"| {criticality} | `{status}` | {count} |")
    else:
        lines.append("- Divergence report unavailable.")
    lines.extend(
        [
            "",
            "Source: [`docs/publication/ci3_z3/PUBLICATION_AUDIT_DIVERGENCE.md`](../publication/ci3_z3/PUBLICATION_AUDIT_DIVERGENCE.md).",
            "",
            "## Load-Bearing Topology",
            "",
            table(
                [
                    ("Citation-graph nodes", load_bearing.get("node_count", 0)),
                    (
                        "Critical nodes",
                        load_bearing.get("criticality_counts", {}).get("critical", 0),
                    ),
                    (
                        "High nodes",
                        load_bearing.get("criticality_counts", {}).get("high", 0),
                    ),
                    (
                        "Medium nodes",
                        load_bearing.get("criticality_counts", {}).get("medium", 0),
                    ),
                    (
                        "Leaf nodes",
                        load_bearing.get("criticality_counts", {}).get("leaf", 0),
                    ),
                ]
            ),
            "",
            "Top load-bearing rows by graph score:",
            "",
        ]
    )
    for row in load_bearing.get("top_25_by_load_bearing_score", [])[:8]:
        lines.append(
            f"- `{row['claim_id']}` - {row['criticality']}; "
            f"{row['transitive_descendants']} descendants; score {row['load_bearing_score']:.3f}"
        )

    lines.append("")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
