"""A30 q1_1d: 1D jam surface as wall + capture channel (supplied toy, Option R).

Half chain: sites j = 1..M unrecorded, site 0 recorded (the jam; compression makes it a
hard wall: no hopping into it).  H = -t sum (|j><j+1| + h.c.) + eps |1><1| on sites >= 1.
Capture channel at the gate-open surface site 1:
  (rate)     no-record branch generated by H_eff = H - i Gam/2 |1><1|   (c = Gam*tau, tau->0)
  (per tick) each tick: psi <- K U0 psi, U0 = exp(-i H tau), K = 1 - kap |1><1|,
             kap = 1 - sqrt(1 - f)  (A9 instrument: Kraus sqrt(f) P_occ at site 1 = record,
             sqrt(1 - f n_1) = no record).  Capture probability = norm lost.
Exact formulas checked here (derived in REPORT step 1.x):
  rate:     R = -(t + V e^{-ik}) / (t + V e^{ik}),  V = eps - i Gam/2
  per tick: R = -1 + 2 kap sin k / (t tau D),  D = 1 - kap + kap*S(k),
            S = 1/2 + sin k/(t tau) + i (1/pi) PV int_0^pi sin^2 q cot((phi(q)-phi(k))/2) dq,
            phi(q) = 2 t tau cos q   (eps = 0; valid below the aliasing bound 2 t tau < pi)
Independent check: wavepackets evolved in real time; captured fraction vs the
packet-averaged 1 - |R(k)|^2.
"""
import signal
import numpy as np
from scipy.integrate import quad
from scipy.fft import dst, idst
from scipy.sparse import diags
from scipy.sparse.linalg import expm_multiply

signal.alarm(55)
t = 1.0


def R_rate(k, Gam, eps=0.0):
    V = eps - 0.5j * Gam
    return -(t + V * np.exp(-1j * k)) / (t + V * np.exp(1j * k))


def S_tick(k, tau):
    phi = lambda q: 2 * t * tau * np.cos(q)
    pk = phi(k)

    def f(q):
        d = (phi(q) - pk) / 2.0
        if abs(q - k) < 1e-12:
            return np.sin(k) ** 2 * 2.0 / (-2 * t * tau * np.sin(k))
        return np.sin(q) ** 2 * (q - k) / np.tan(d)
    pv, _ = quad(f, 0.0, np.pi, weight='cauchy', wvar=k, limit=400)
    return 0.5 + np.sin(k) / (t * tau) + 1j * pv / np.pi


def R_tick(k, f, tau):
    kap = 1.0 - np.sqrt(1.0 - f)
    D = 1.0 - kap + kap * S_tick(k, tau)
    return -1.0 + 2.0 * kap * np.sin(k) / (t * tau * D)


# ---------------------------------------------------------------- packets
M = 1200
j = np.arange(1, M + 1)
qgrid = np.pi * np.arange(1, M + 1) / (M + 1)          # Dirichlet modes sin(q j), q in (0,pi)
Eq = -2 * t * np.cos(qgrid)


def packet(x0, s, k0):
    psi = np.exp(-((j - x0) ** 2) / (4 * s * s)) * np.exp(-1j * k0 * j)   # moving left
    return psi / np.linalg.norm(psi)


def mode_weights(psi):
    # coefficients on orthonormal Dirichlet modes sqrt(2/(M+1)) sin(q j)
    c = dst(psi.real, type=1, norm='ortho') + 1j * dst(psi.imag, type=1, norm='ortho')
    return np.abs(c) ** 2


def run_rate(k0, Gam, eps, s=40.0):
    x0 = M // 2
    psi = packet(x0, s, k0)
    w = mode_weights(psi)
    pred = np.sum(w * (1 - np.abs(R_rate(qgrid, Gam, eps)) ** 2))
    off = -t * np.ones(M - 1)
    dg = np.zeros(M, dtype=complex)
    dg[0] = eps - 0.5j * Gam
    H = diags([off, dg, off], [-1, 0, 1], format='csr')
    v = 2 * t * max(np.sin(k0), 0.05)
    T = 2.0 * x0 / v * 0.9
    out = expm_multiply(-1j * H * T, psi)
    return 1 - np.linalg.norm(out) ** 2, pred


def run_tick(k0, f, tau, s=40.0):
    x0 = M // 2
    psi = packet(x0, s, k0)
    w = mode_weights(psi)
    pred = np.sum(w * (1 - np.abs(R_tick_vec(qgrid, f, tau)) ** 2))
    kap = 1.0 - np.sqrt(1.0 - f)
    ph = np.exp(-1j * Eq * tau)
    v = 2 * t * max(np.sin(k0), 0.05)
    n = int(2.0 * x0 / v * 0.9 / tau)
    for _ in range(n):
        c = (dst(psi.real, type=1, norm='ortho') + 1j * dst(psi.imag, type=1, norm='ortho')) * ph
        psi = idst(c.real, type=1, norm='ortho') + 1j * idst(c.imag, type=1, norm='ortho')
        psi[0] *= (1 - kap)
    return 1 - np.linalg.norm(psi) ** 2, pred


_cache = {}


def R_tick_vec(qs, f, tau):
    key = (f, tau)
    if key not in _cache:
        # tabulate on a coarse grid, interpolate (formula is smooth in q)
        qq = np.linspace(1e-3, np.pi - 1e-3, 400)
        RR = np.array([R_tick(q, f, tau) for q in qq])
        _cache[key] = (qq, RR)
    qq, RR = _cache[key]
    return np.interp(qs, qq, RR.real) + 1j * np.interp(qs, qq, RR.imag)


print("=== (a) rate model: captured fraction, packet run vs exact formula (s=40, M=1200) ===")
for (k0, Gam, eps) in [(np.pi / 2, 2.0, 0.0), (0.6, 2.0, 0.0), (2.4, 0.5, 0.0),
                       (1.0, 8.0, 0.0), (1.2, 2.0, 2.0), (1.2, 4.0, -1.0)]:
    pa, pr = run_rate(k0, Gam, eps)
    print(f"k0={k0:.3f} Gam={Gam:4.1f} eps={eps:+.1f}: packet {pa:.6f}  formula {pr:.6f}  diff {pa-pr:+.1e}")

print("\n=== (b) per-tick model (eps=0): packet run vs exact per-tick formula ===")
for (k0, f, tau) in [(np.pi / 2, 0.19, 0.1), (1.0, 0.5, 0.2), (0.6, 1.0, 0.3), (2.0, 0.3, 0.5)]:
    pa, pr = run_tick(k0, f, tau)
    print(f"k0={k0:.3f} f={f:.2f} tau={tau:.2f} (dose 2t tau={2*t*tau:.2f}): packet {pa:.6f}  formula {pr:.6f}  diff {pa-pr:+.1e}")

print("\n=== (c) rate model: critical coupling and Zeno (eps=0) ===")
ks = np.linspace(0.05, np.pi - 0.05, 200)
Gs = np.linspace(0.01, 20, 4000)
worst = 0.0
for k in ks:
    A = 1 - np.abs(R_rate(k, Gs)) ** 2
    g_opt = Gs[np.argmax(A)]
    worst = max(worst, abs(g_opt - 2.0))
    assert abs(A.max() - 2 * np.sin(k) / (1 + np.sin(k))) < 1e-6
print(f"argmax_Gam A(k,Gam) = 2t for all 200 k: max |Gam_opt - 2| = {worst:.4f} (grid 0.005); A_max = 2 sin k/(1+sin k) to 1e-6")
for k in [0.3, np.pi / 2]:
    for G in [20.0, 100.0, 1000.0]:
        A = 1 - abs(R_rate(k, G)) ** 2
        print(f"Zeno: k={k:.3f} Gam={G:7.1f}: A={A:.5e}  8 t sin k/Gam={8*np.sin(k)/G:.5e}")
for G in [0.5, 2.0, 8.0]:
    for k in [1e-3, 1e-2]:
        A = 1 - abs(R_rate(k, G)) ** 2
        print(f"threshold: Gam={G} k={k:.0e}: A={A:.4e}  A/k={A/k:.4f}  (2tGam/(t^2+Gam^2/4)={2*G/(1+G*G/4):.4f})")
print("black only where V = -t e^{ik}: eps=0 -> k=pi/2, Gam=2t; A(pi/2,2)=", 1 - abs(R_rate(np.pi / 2, 2.0)) ** 2)

print("\n=== (d) per-tick: Zeno for sure capture (f=1) as the tick shrinks; best f per dose ===")
for tau in [0.5, 0.2, 0.1, 0.05, 0.02, 0.01]:
    A = 1 - abs(R_tick(np.pi / 2, 1.0, tau)) ** 2
    Rr = R_tick(np.pi / 2, 1.0, tau)
    print(f"f=1 tau={tau:5.2f}: A(k=pi/2) = {A:.5f}   R = {Rr.real:+.4f}{Rr.imag:+.4f}i  (hard wall at site 1 would be R=-e^(-2ik)=+1)")
for tau in [0.05, 0.1, 0.25, 0.5]:
    fs = np.linspace(0.005, 1.0, 200)
    A = np.array([1 - abs(R_tick(np.pi / 2, f, tau)) ** 2 for f in fs])
    i = np.argmax(A)
    print(f"dose 2t tau={2*tau:.2f}: best f = {fs[i]:.3f} (rate-matched 1-exp(-2t tau)={1-np.exp(-2*tau):.3f}), A_max(k=pi/2) = {A[i]:.5f}")
for tau in [0.1, 0.5]:
    for k in [1e-2, 3e-2]:
        A = 1 - abs(R_tick(k, 1 - np.exp(-2 * tau), tau)) ** 2
        print(f"per-tick threshold: tau={tau} k={k:.0e}: A={A:.4e}, A/k={A/k:.4f}")
