import json,pathlib,hashlib,subprocess,datetime
r=pathlib.Path('/private/tmp/review-drain-20260915');inv=json.loads((r/'drain8167-original-inventory.json').read_text());p=r/'drain8167-originals/.claude/science/physics-loops/toe-compact-winding-20260916';sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest();gh=json.loads((r/'check8167/final-github.json').read_text());assert gh['headRefOid']==inv['head'] and gh['state']=='OPEN' and not gh['isDraft']
m=json.loads((p/'MANIFEST.json').read_text());assert len(m['files'])==115
for x in m['files']:assert sha(p/x['path'])==x['sha256'] and (p/x['path']).stat().st_size==x['bytes']
repo=str(r/'integration-resume');status=subprocess.check_output(['git','-C',repo,'diff','--name-status',inv['merge_base'],inv['head']],text=True);assert all(x.startswith('A\t') for x in status.splitlines())
existing=subprocess.check_output(['git','-C',repo,'ls-tree','-r','--name-only',inv['main'],'--','.claude/science/physics-loops/toe-compact-winding-20260916'],text=True);assert not existing
for x in inv['files']:
 path=x['path'];rel=path.split('toe-compact-winding-20260916/')[1]
 if rel.startswith('notes/') and 'SPARSE_' not in rel: disposition='narrowed';reason='Preserve complete positive identities/proof and conditional limit; canonical packaging, explicit inputs and negative-certification separation pending.'
 elif rel.startswith('notes/'):disposition='deferred';reason='Complete explicit construction and limit reviewed with no material mathematical defect; negative implication certification remains blocked by N1. Preserve entire argument, never relabel to bypass gate.'
 elif rel in ['evidence/compact_cover_source_check.py','evidence/compact_score_check.py']:disposition='narrowed';reason='Preserve mathematical checks; add canonical note/input pins, honest counted assertions and evidence wrapper before final capture.'
 elif rel=='evidence/sparse_loop_counterexample_check.py':disposition='deferred';reason='Preserve finite construction checks with deferred negative theorem; do not misstate numerical check as all-volume certificate.'
 else:disposition='deferred';reason='Exact historical recovery/provenance, including failures, operational state and mutations; not live scientific or audit authority.'
 x.update(disposition=disposition,reason=reason,recovery=str(r/'drain8167-originals'/path),git_recovery=inv['head']+':'+path)
report=dict(schema_version=1,pr=8167,review_kind='original-independent-science-review',reviewer_session='/root/review_8167',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),head=inv['head'],merge_base=inv['merge_base'],current_main_for_review=inv['main'],declared_base=gh['baseRefName'],fresh_github_head_verified=gh['headRefOid'],github_state=gh['state'],github_draft=gh['isDraft'],verdict='POSITIVE_SOURCE_SALVAGE_WITH_DEFERRED_NEGATIVE_CERTIFICATION',landing_ready=False,formal_retained_grade=False,audit_verdict=None,material_math_findings=[],
findings=[dict(id='8167-N1',category='AUDIT_COMPATIBILITY',path='NO_GO_DISCIPLINE_CHECKLIST.md',lines='3-22',finding='The source honestly supplies one constructive refutation and explicitly disclaims formal packet PASS. Scope checks are not five independent families. Negative implication and related negative class exclusions cannot receive packet PASS under current rule.',disposition='Preserve complete source and branch; defer negative certification, without invented routes or positive-label bypass.'),dict(id='8167-PACKAGE',category='AUDIT_COMPATIBILITY',finding='All changed paths are branch-local packet material; three raw JSON outputs are not canonical cache envelopes, and there are no canonical source rows/helper declarations or N5 cached certificate lines.',disposition='Canonicalize surviving positive science with accurate note/input pins, source registration and fresh bounded evidence; archive exact historical payload; same-session final confirmation required.')],
claims_and_boundaries=[
'Finite compact cover theorem: normalized Haar requires (2pi)^E kernel factor. The exact trace retains initial Q fundamental cell, all intermediate real coordinates and terminal winding w. Every finite graph and g,T>0; no Gauss projection or thermodynamic limit.',
'Normalized background derivatives: Phi_ab=<S_ab>-Cov(S_a,S_b), and cubic contact/covariance/cumulant formula derived by differentiating normalized expectations. Actual periodic-observable insertion differs from nonlinear background partition derivatives. Free-circle derivatives are exact checks, not uniform-coupling/volume exclusions.',
'Finite-thermal compact sine MGF: positive electric Dyson trace coefficients remove phases, then coordinate positivity bounds amplitude increase, yielding exp(t² H2/2) for real time-dependent L2 sources. It controls actual sin(B)/g observables, not principal flux or integer fillings.',
'Static exact curl Ward identity and conditional Gaussian theorem: h=Cu, fixed beta and fixed g, bounded H2, vanishing H3 and deterministic L2 contact concentration imply the displayed quantitative MGF bound. Supplied stationary spatially ergodic Gibbs loop state gives weighted contact concentration. No supplied state existence/uniqueness, beta-uniform limit, physical Gauss projection or photon pole.',
'Sparse construction: side6 isolated oriented unit loops, q=p^4, random origin, independent plane/offset marks and 24 product-sign sequences yield stationary ergodic symmetric current law and joint vertex bound. Diffuse filling limit is rho product of four independent normals plus independent Gaussian noise; kappa4=78rho^4 and real MGF lower bound diverges. Complete construction is mathematically supported; formal negative implication certification remains deferred.'
],
proof_assessment='CONDITIONAL for supplied-model/state results; CLOSED algebra within stated finite domains. Actual full compact principal-flux/photon target remains OPEN. No equivalent-gap near-closure framing.',
imports={'supplied':'Rotor Hamiltonian, g,beta, full thermal trace, source class and Gibbs state with local compact-loop specification; construction probability law explicitly supplied. None selected by axioms or approved primitives.','mathematics':'Feynman-Kac, covering kernels, bounded perturbation/Dyson trace expansion, spectral perturbation, elementary iid CLT and mean ergodic theorem; applications derived explicitly.','empirical':'None.','siblings':'PR8165 and PR8166 motivate the problem only. No estimate or result from their unlanded heads is required by these proofs; do not add false load-bearing dependency edges.'},
required_author_fix_scope=[
'Keep complete positive cover/source and sine-score proof bodies, exact constants and quantitative Gaussian estimate; retain all source/state/temperature and Gauss-sector boundaries.',
'Preserve full sparse construction, failed side4 adjacency claim/correction, initial Fourier 2/3 refinement failure, nine current and nine historical mutated sources and errors, diagnostics and all116 path identities. Unlanded negative certification keeps branch recovery handle.',
'Canonical source/runners need markdown dependency and input bindings; no unlanded sibling theorem dependency is necessary. If consolidation creates supporting-proof owners, bind all complete proof sources.',
'Primary runners are finite challenges, not proofs of infinite-volume law. Preserve 120-second contracts and actual fixture sizes/tolerances. Canonical cache must follow genuine final execution; no historical restamping.',
'No formal N1 PASS, no disguised negative claim as positive theorem to bypass procedural gate. Root must decide exact deferred-versus-positive source boundary and return final affected bytes to this reviewer.',
'Root owns combined pipeline/evidence/strict checks, exact-current-main preservation, landing and remote closure; none performed in this independent review.'
],
read_scope={'source':'Complete three final proof notes, final runners, mutation harness, focused verifier, packet Markdown/state, original note/source historical diffs and mutation source diffs. Manifest and raw JSON data parsed/source-bound; repetitive numeric leaves not each treated as new proofs.','authority':'Frozen main mandatory memo, primitive registry/procedure and all primitive sources; review-loop setup/units/science/fixes/salvage/operations/compatibility; no-go N1-N8 and proof governance. Repo status/queue/harness context inspected for relevant authority; no audit verdict used as premise.','complete_original_inventory':'116 added paths; no deletions or modifications relative actual merge base. Entire original prefix absent at frozen main, so original import overwrites no current source in that prefix. Final canonical current-main interaction check remains required.'},
source_cost=json.loads((r/'drain8167-provenance-checks.json').read_text())['cost'],
checks={'independent_controls':json.loads((r/'check8167/independent_controls.json').read_text()),'primary_reruns':0,'pipeline_runs':0,'syntax_files':25,'manifest_entries_verified':115,'mutated_source_error_pairs_verified':18,'current_main_prefix_absent':True,'final_remote_head_unchanged':True},
original_dispositions=inv['files'],
lenses={'CodeRunnerReviewer':'Finite math checks clean; canonical evidence packaging pending.','PhysicsClaimReviewer':'Conditional/support boundaries explicit.','ProofObligationReviewer':'CONDITIONAL','ImportSupportReviewer':'DISCLOSED','NatureRetentionReviewer':'BOUNDED, no retained grade','NoGoDisciplineReviewer':'FAIL N1 packet, honest scope otherwise; not a mathematical refutation of the construction.','LabelingConventionReviewer':'NOT APPLICABLE','RepoGovernanceReviewer':'FIX canonical placement and provenance separation','AuditCompatibility':'FIX, no audit authority edits allowed'},
branch_recovery='Preserve physics-loop/toe-compact-winding-20260916 while any negative certification/source remains unlanded.',bound_artifacts={})
for f in [r/'drain8167-original-inventory.json',r/'drain8167-original.patch',r/'drain8167-head-fetch.json',r/'drain8167-provenance-checks.json',r/'check8167/independent_controls.py',r/'check8167/independent_controls.json',r/'check8167/final-github.json'] : report['bound_artifacts'][str(f.relative_to(r))]=sha(f)
report['authority_inputs']=[dict(path=str(f.relative_to(r/'check8167/authority')),sha256=sha(f),revision=inv['main']) for f in sorted((r/'check8167/authority').rglob('*')) if f.is_file()]
f=r/'drain8167-original-review.json';assert not f.exists();f.write_text(json.dumps(report,indent=2)+'\n')
md='''# PR8167 original independent review

Positive compact-source science is suitable for canonical salvage. The full packet is not landing-ready: its negative certification explicitly lacks the five real N1 route families, and canonical source/evidence packaging is absent. No material mathematical defect was found in the final three proofs.

Preserve the full sparse-loop construction and proof, including its exact non-Gaussian limit, as deferred science/recovery. Do not invent routes or relabel the negative implication to bypass N1. Preserve the head branch while this work remains unlanded.

The cover identities retain Haar normalization, initial fundamental cell, terminal windings, contact and mixture terms. The sine-score theorem is a positive conditional result for the supplied compact Hamiltonian: fixed finite temperature, actual sine observables, and static exact curls with deterministic contact concentration for its Gaussian conclusion. Supplied spatial ergodicity gives that concentration. It establishes no principal-flux field limit, physical Gauss-sector thermal result, vacuum selection, or photon phase.

Independent controls passed: direct log-image differentiation; exact Bernoulli moment propagation across 256 sign environments; pointwise amplitude-phase and Taylor identities. No primary runner was rerun. Three current raw source/output pairs, 18 current/historical mutation pairs, 115 manifest entries and 25 Python syntax files were checked. All 116 original paths have explicit dispositions and recovery identities in the JSON report.

PR8165/8166 are context, not necessary proof dependencies. Complete current proofs are self-contained. Preserve original side4 adjacency error and passing-but-insufficient check, subsequent side6 repair, Fourier 2/3 refinement failure and unchanged 0.003 tolerance at 3/4. Canonical source registration, final cache capture, same-session affected-source confirmation and root combined gates remain required.

Frozen head: 5265ddd85815fe92e55342f4352f5e675b84703c. Actual merge base: 6dda46fc1af02827e9c6b64b2f7d05c381a3ce07. Current-main context: 631d6b36cd1e9b860763ebcad36e40a2bbe7439c. Remote head remained unchanged and ready/open at final check.
'''
(r/'drain8167-original-review.md').write_text(md);print(f,sha(f))
