"""A54 c5 (Q3): which flux sector does empty space choose under light's dressed ring -K sum_p S_p (Z2 form)?
(1) One coarse cube (12 link qubits, A52 c3b geometry): dense diagonalisation in the charge-free sector.
(2) Coarse tori: exact stabilizer bookkeeping -- are the uniform assignments S_p = +1 / S_p = -1 (all G_v = +1)
    consistent with every relation of the group generated by {S_p, G_v}?
(3) Z^eta with |eta cap dp| odd for all p: flips every S_p, multiplies hop t_l by (-1)^{eta_l} (= pi flux for
    the charges) -- light alone cannot tell K from -K.   Usage: c5_flux.py"""
import signal, sys, itertools, time
signal.alarm(110)
from a54lib import *

t0 = time.time()
# ---------- (1) one cube ----------
Tof, _ = family(ALL_C3_T[0])
CORN = [tuple(c) for c in itertools.product([0, 2], repeat=3)]
LINKS = sorted({tuple(int(v) for v in (np.array(c) + np.array(d))) for c in CORN for d in DIRS
                if all(0 <= x <= 2 for x in np.array(c) + np.array(d))})
lid = {l: k for k, l in enumerate(LINKS)}
def legs_in(v):
    return [i for i in range(6) if all(0 <= x <= 2 for x in np.array(v) + 2 * np.array(DIRS[i]))]
def lk(v, j):
    return lid[tuple(int(t) for t in np.array(v) + np.array(DIRS[j]))]
def cube_ends(l):
    x = np.array(l); a = [k for k in range(3) if x[k] % 2][0]; e = np.zeros(3, int); e[a] = 1
    return tuple(int(t) for t in x - e), 2 * a, tuple(int(t) for t in x + e), 2 * a + 1
def cube_hop(l, recs):
    v, i, w, ip = cube_ends(l); z = 0
    for (c, leg) in ((v, i), (w, ip)):
        T = Tof[recs[c]]
        for j in legs_in(c):
            if j != leg and T[leg][j]:
                z ^= 1 << lk(c, j)
    return (1 << lid[l], z, 0)
def cube_faces():
    out = []
    for a, b in [(0, 1), (0, 2), (1, 2)]:
        for s in (0, 2):
            c = [0, 0, 0]; k = 3 - a - b; c[k] = s
            v0 = tuple(c); ea = 2 * a; eb = 2 * b
            def nb(v, i): return tuple(int(t) for t in np.array(v) + 2 * np.array(DIRS[i]))
            v1 = nb(v0, ea); v2 = nb(v1, eb); v3 = nb(v0, eb)
            out.append([lk(v0, ea), lk(v1, eb), lk(v2, ea + 1), lk(v3, eb + 1)])
    return out
def sector_matrix(P, idx):
    """Pauli string P restricted to the basis states idx (closed under P), built directly (no 4096^2 array)."""
    x, z, ph = P; posn = {int(s): k for k, s in enumerate(idx)}
    M = np.zeros((len(idx), len(idx)), complex)
    for k, s in enumerate(idx):
        s = int(s)
        M[posn[s ^ x], k] = (1j ** ph) * (-1) ** popc(s & z)
    return M
rng = np.random.default_rng(3)
for rname, recs in [('uniform', {c: F0 for c in CORN}), ('random', {c: BD[rng.integers(8)] for c in CORN})]:
    hops = {l: cube_hop(LINKS[l], recs) for l in range(12)}
    faces = cube_faces(); Sop = []
    for f in faces:
        P = (0, 0, 0)
        for l in f: P = pmul(hops[l], P)
        Sop.append(P)
    gauss = []
    for c in CORN:
        z = 0
        for j in legs_in(c): z ^= 1 << lk(c, j)
        gauss.append((0, z, 0))
    dim = 4096; st = np.arange(dim)
    free = np.ones(dim, bool)
    for g in gauss:
        free &= np.array([popc(int(s) & g[1]) % 2 == 0 for s in st])
    idx = np.nonzero(free)[0]
    Sd = [sector_matrix(P, idx) for P in Sop]
    herm = max(np.abs(S - S.conj().T).max() for S in Sd)
    for K in (1.0, -1.0):
        H = -K * sum(Sd)
        E, V = np.linalg.eigh(H)
        g0 = V[:, 0]; deg = int(np.sum(E < E[0] + 1e-9))
        sp = [float(np.real(g0.conj() @ S @ g0)) for S in Sd]
        print("cube (%s records), charge-free dim %d, K=%+d: E0 = %.6f, degeneracy %d, <S_p> in ground state = %s, gap %.3f"
              % (rname, len(idx), K, E[0], deg, [round(s, 6) for s in sp], E[deg] - E[0]))
    print("   S_p hermiticity residual %.1e; phases of the six S_p: %s" % (herm, [P[2] for P in Sop]))
# ---------- (2) tori: stabilizer consistency ----------
def relations(gens):
    """gens: list of Pauli strings. returns list of (subset bitmask, sign) spanning the products equal to +-identity."""
    rows = []  # (x, z, combo)
    piv = {}
    rels = []
    for k, g in enumerate(gens):
        x, z = g[0], g[1]; combo = 1 << k
        key = (x << 4096) | z
        while key:
            b = key.bit_length() - 1
            if b not in piv:
                piv[b] = (key, combo); break
            key ^= piv[b][0]; combo ^= piv[b][1]
        if key == 0:
            P = (0, 0, 0)
            for j in range(len(gens)):
                if (combo >> j) & 1: P = pmul(P, gens[j])
            assert P[0] == 0 and P[1] == 0 and P[2] % 2 == 0
            rels.append((combo, 1 if P[2] == 0 else -1))
    return rels
for shape in [(2, 2, 2), (2, 2, 3), (3, 3, 3), (4, 4, 4), (3, 4, 4)]:
    tor, recs, hops, dcol, loops, dp, Ddp = setup(shape, 0, 'random', seed=4)
    S = stabilizer_signs_ok(tor, hops, loops); NP = len(S)
    G = [gauss_string(tor, v) for v in tor.corners]
    rels = relations(S + G)
    res = {}
    for name, sv in (('S_p=+1 (zero flux)', 1), ('S_p=-1 (pi flux)', -1)):
        bad = 0
        for combo, sign in rels:
            prod = 1
            for j in range(NP):
                if (combo >> j) & 1: prod *= sv
            bad += prod != sign
        res[name] = bad
    # (3) eta
    Ge = GF2()
    for p in range(NP):
        row = 1
        for l in bits_of(dp[p]): row ^= 1 << (l + 1)
        Ge.add(row)
    eta = Ge.solve(tor.n)
    if eta is not None:
        flipS = sum(not anticomm((0, eta, 0), S[p]) for p in range(NP))
        hop_sign = sum(anticomm((0, eta, 0), hops[l]) != ((eta >> l) & 1) for l in range(tor.n))
        etxt = "eta found (|eta| = %d links): S_p not flipped %d; hop sign rule violations %d" % (popc(eta), flipS, hop_sign)
    else:
        etxt = "no eta (odd plaquette count in some torus plane)"
    print("torus %s: %d independent relations; violated by uniform S=+1: %d, by uniform S=-1: %d; %s" % (
        shape, len(rels), res['S_p=+1 (zero flux)'], res['S_p=-1 (pi flux)'], etxt))
print("done (%.1f s)" % (time.time() - t0))
