from pathlib import Path
import sys,json,hashlib,subprocess,re,ast
r=Path('/private/tmp/review-drain-20260915');w=r/'author-pool/author-backlog';sys.path[:0]=[str(w/'docs/audit/scripts'),str(w/'scripts')]
import build_citation_graph as g, audit_packet_script_deps as a
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)};bind=lambda ps:[{'path':p,'sha256':sha(w/p)} for p in sorted(set(ps))];git=lambda *args:subprocess.check_output(['git','-C',str(w),*args],text=True).strip()
report=r/'review-8058-provisional.json';review=json.loads(report.read_text());rr=ref(report);paths=git('diff','--cached','--name-only').splitlines();notes=[];helpers=set();parents=set();runtime=set();context=set()
for note,stem in [('NATIVE_ZERO_PENALTY_L4_DELAYED_SPLITTING','native_zero_penalty_l4_delayed_splitting'),('NATIVE_WEAK_ELECTRIC_SPECTATOR_GAP','native_weak_electric_spectator_gap'),('NATIVE_THIRD_ORDER_STAR_VERTEX','native_third_order_star_vertex')]:
 n='docs/'+note+'_NOTE_2026-09-08.md';primary='scripts/'+stem+'_2026_09_08.py';body=(w/n).read_text();hs=g.helper_runner_paths_for_claim(g.claim_id_from_path(w/n),primary);assert set(hs)=={'scripts/'+x+'.py' for x in a.transitive_helpers(Path(primary).stem)};cs=sorted(p.relative_to(w).as_posix() for p in g.extract_citations(body,w/n));ps=[p for p in cs if '/work_history/' not in p];parents.update(ps);context.update(set(cs)-set(ps));helpers.update(hs)
 for file in [primary,*hs]:
  runtime.add(file)
  for node in ast.parse((w/file).read_text()).body:
   if isinstance(node,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='AUDIT_INPUT_PATHS' for t in node.targets):runtime.update(ast.literal_eval(node.value))
 notes.append(dict(path=n,claim_id=g.claim_id_from_path(w/n),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type=g.extract_claim_type_hint(body)[1],primary_runner=primary,helpers=sorted(hs),citations=cs,repository_dependencies=ps,dependency_rationale='Linked native dictionary/instrument and finite endpoint/parent theorems supply the actual model and isolation or coefficient context. Historical packet is provenance, not authority. Finite graph, Clifford, analytic and residual arguments are reviewed mathematical proof rather than repository premise aliases.'))
context.update(['docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json','docs/ai_methodology/skills/review-loop/SKILL.md']);tooling=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/ai_methodology/skills/review-loop/scripts/review_receipt.py','docs/ai_methodology/skills/review-loop/scripts/review_workspace.py']
record=dict(schema_version=1,unit_id='PR8052-8053-8058',constituents=[dict(id='PR'+str(c['pr']),head=c['head'],delta_base=c['original_base'],dispositions=dict(rr,json_pointer='/constituent_dispositions/'+str(c['pr']))) for c in review['constituents']],source=dict(base=review['review_base'],commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),inputs=dict(runtime=bind(runtime),helpers=bind(helpers),parents=bind(parents),context=bind(context),tooling=bind(tooling)),reviewer=dict(session=review['reviewer_session'],report=rr,references=review['independent_controls']+[review['working_science_report'],review['archive_anchor']]),notes=notes,non_science_notes=[dict(path=p,rationale='Exact historical proof/control/provenance packaging; historical source and reviews are not new authority. Complete present claims are in the three canonical notes; archive README explains recovery.',review_reference=rr) for p in paths if p.endswith('.md') and p not in [n['path'] for n in notes]])
out=r/'8058-unit-preexecution-v1.json';assert not out.exists();out.write_text(json.dumps(record,indent=2)+'\n');print(record['source']['tree'],[(n['path'],len(n['helpers']),len(n['repository_dependencies'])) for n in notes]);print('parents',*sorted(parents),sep='\n')
