from pathlib import Path
import json,re
w=Path('/private/tmp/review-drain-20260915/author-pool/author-backlog');o=Path('/private/tmp/review-drain-20260915');a=json.loads((o/'8058-archive-anchor.json').read_text());notes={8052:'docs/NATIVE_ZERO_PENALTY_L4_DELAYED_SPLITTING_NOTE_2026-09-08.md',8053:'docs/NATIVE_WEAK_ELECTRIC_SPECTATOR_GAP_NOTE_2026-09-08.md',8058:'docs/NATIVE_THIRD_ORDER_STAR_VERTEX_NOTE_2026-09-08.md'}
primary={8052:'scripts/native_zero_penalty_l4_delayed_splitting_2026_09_08.py',8053:'scripts/native_weak_electric_spectator_gap_2026_09_08.py',8058:'scripts/native_third_order_star_vertex_2026_09_08.py'}
for pr,n in notes.items():
 p=w/n;s='\n'.join(x.rstrip() for x in p.read_text().splitlines())+'\n';s=s.replace('../'+a[str(pr)]['prefix']+'HANDOFF.md',a[str(pr)]['mapping'][a[str(pr)]['prefix']+'HANDOFF.md'][5:]);s+='\nThe [canonical runner cache](../logs/runner-cache/'+Path(primary[pr]).stem+'.txt) records the current bounded invocation. Archived author campaigns retain their historical scope and are not current execution verdicts.\n';p.write_text(s)
p=w/primary[8052];s=p.read_text().replace('resource,runpy,signal','resource,importlib.util,signal');old="for key,count in [('electric',964),('spectator',87509),('isolation',5091)]:\n part=runpy.run_path(str(root/f'scripts/native_zero_penalty_{key}_exact_2026_09_08.py'))['out']\n if part['checks']!=count:raise RuntimeError('predicate coverage changed '+key)\n parts[key]=part";new="def execute_helper(path,key,count):\n spec=importlib.util.spec_from_file_location(path.stem,path);module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)\n part=module.out\n if part['checks']!=count:raise RuntimeError('predicate coverage changed '+key)\n parts[key]=part\n"+'\n'.join(f"execute_helper(root / 'scripts' / 'native_zero_penalty_{k}_exact_2026_09_08.py','{k}',{c})" for k,c in [('electric',964),('spectator',87509),('isolation',5091)]);assert old in s;s=s.replace(old,new)
s=s.replace('per_element: actual electric pair flux toggles.','per_element: executed actual electric pair flux toggles and finite graph cut controls.').replace('per_site: small cuts and incident-pair matching.','per_site: executed small cuts and incident-pair matching on the declared finite graphs.').replace('per_mode: active parity and spectator projection.','per_mode: executed active parity and spectator projection controls in the supplied finite Clifford models.').replace('per_block: fixed-flux compression and canonical normalization.','per_block: finite fixed-flux compression is executed; the general canonical-normalization argument is analytical in the note.').replace('lattice_wide: L4 constant square, winding sectors and isolation.','lattice_wide: executed L4 constant-square and winding controls; general-torus cut and isolation proofs are analytical, not an exhaustive flux-sector run.');p.write_text(s)
for k in ('electric','spectator','isolation'):
 p=w/f'scripts/native_zero_penalty_{k}_exact_2026_09_08.py';p.write_text('AUDIT_TIMEOUT_SEC=180\n# Proof identity, not computational data.\nAUDIT_INPUT_PATHS=('+repr(notes[8052])+',)\n'+p.read_text())
p=w/notes[8052];s=p.read_text().replace('Actual isolated mutants remove','Historical isolated mutants removed').replace('They must fail actual operator or geometry predicates.','The archived campaign recorded failures of actual operator or geometry predicates; the current primary does not rerun that campaign.');p.write_text(s)
p=w/primary[8053];s=p.read_text().replace('resource,runpy,signal','resource,importlib.util,signal');old=" symmetry=runpy.run_path(str(root/'scripts/native_weak_electric_magnetic_symmetry_2026_09_08.py'))['out']";new=" spec=importlib.util.spec_from_file_location('magnetic_symmetry',root / 'scripts' / 'native_weak_electric_magnetic_symmetry_2026_09_08.py');module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)\n symmetry=module.out";assert old in s;s=s.replace(old,new);p.write_text(s)
data='outputs/native_weak_electric_spectator_gap_2026_09_08_inputs/';runtime=[data+'FRAME_RESULT.json',data+'PREFIXES.json']+[data+f'bridge_{b}.{ext}' for b in (0,3,9,12,36,96) for ext in ('json','npz')]
helpernames=['rational_core','candidate_decoder','rational_replay','magnetic_symmetry']
for name in helpernames:
 p=w/f'scripts/native_weak_electric_{name}_2026_09_08.py';inputs=[notes[8053]]
 if name!='magnetic_symmetry':inputs+=runtime
 if name=='rational_replay':inputs += [f'scripts/native_weak_electric_{n}_2026_09_08.py' for n in ('rational_core','candidate_decoder')]
 p.write_text('AUDIT_TIMEOUT_SEC=180\n# Proof/source and exact supplied runtime identities.\nAUDIT_INPUT_PATHS='+repr(tuple(inputs))+'\n'+p.read_text())
p=w/notes[8053];s=p.read_text();s+='\nThe primary total7960 comprises7959 mathematical checks and one resource guard. Its rational replay consumes the exact preserved bridge, frame and prefix bytes; the general finite-gap conclusion additionally uses the analytical proof and its isolation/parity premises.\n';p.write_text(s)
# Preserve all names in INPUTS.json using an explicit original-name to raw-path map.
prefix=a['8058']['prefix'];mapping=a['8058']['mapping'];inputname=prefix+'evidence/native-l4-third-vertex-post-review/INPUTS.json';names={n:mapping[prefix+'evidence/native-l4-third-vertex-run-1085/'+n] for n in ('RESULT.json','SOLVE_VECTORS.json')};rawpaths=[mapping[inputname],*names.values()]
p=w/'scripts/native_third_order_star_vertex_replay_2026_09_08.py';s=p.read_text();start=" start=time.monotonic();D=root/";line=next(x for x in s.splitlines() if x.startswith(start));s=s.replace(line," start=time.monotonic();data={name:root/path for name,path in "+repr(names)+".items()};pins=json.loads((root/"+repr(mapping[inputname])+").read_text())")
s=s.replace('(D/name).read_bytes()','data[name].read_bytes()').replace("(D/'SOLVE_VECTORS.json').read_text()","data['SOLVE_VECTORS.json'].read_text()").replace("(D/'RESULT.json').read_text()","data['RESULT.json'].read_text()").replace('import json,hashlib,signal,resource,time','import json,hashlib,signal,resource,time,sys')
s=s.replace(" if resource.getrusage(resource.RUSAGE_SELF).ru_maxrss>384*1048576:raise ValueError('RSS')"," rss_bytes=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*(1 if sys.platform=='darwin' else 1024)\n if rss_bytes>384*1048576:raise ValueError('RSS')").replace("'rss_bytes':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss","'rss_bytes':rss_bytes")
p.write_text('AUDIT_TIMEOUT_SEC=180\nAUDIT_INPUT_PATHS='+repr(tuple([notes[8058]]+rawpaths))+'\n'+s)
p=w/'scripts/native_third_order_star_vertex_two_mode_2026_09_08.py';p.write_text('AUDIT_TIMEOUT_SEC=180\n# Proof identity, not computational data.\nAUDIT_INPUT_PATHS=('+repr(notes[8058])+',)\n'+p.read_text())
p=w/primary[8058];s=p.read_text()
for old in [inputname,*[prefix+'evidence/native-l4-third-vertex-run-1085/'+n for n in names]]:s=s.replace(old,mapping[old])
s=s.replace('hashlib,runpy,signal,time,resource','hashlib,importlib.util,signal,time,resource,sys').replace("p.add_argument('--json',action='store_true');p.parse_args()","p.add_argument('--json',action='store_true');args=p.parse_args()")
s=s.replace(" replay=runpy.run_path(str(root/AUDIT_INPUT_PATHS[4]))['check'](root)\n two=runpy.run_path(str(root/AUDIT_INPUT_PATHS[5]))['check']()"," spec=importlib.util.spec_from_file_location('vertex_replay',root / 'scripts' / 'native_third_order_star_vertex_replay_2026_09_08.py');module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)\n replay=module.check(root)\n spec=importlib.util.spec_from_file_location('vertex_two_mode',root / 'scripts' / 'native_third_order_star_vertex_two_mode_2026_09_08.py');module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)\n two=module.check()")
s=s.replace('rss=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss','rss=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*(1 if sys.platform==\'darwin\' else 1024)')
line=next(x for x in s.splitlines() if x.startswith(' print(json.dumps(dict('));s=s.replace(line,line.replace(' print(json.dumps(dict(',' result=dict(').replace('),indent=2))',")\n (root/'scripts/native_third_order_star_vertex_2026_09_08.json').write_text(json.dumps(result,indent=2)+'\\n');print(json.dumps(result,indent=2))\n if not args.json:\n  print('per_element: exact saved rational residuals reconstructed from literal ordered CAR actions; no new physical solves.')\n  print('per_site: the delivered one-star L4 active space and its recorded source/neighbor geometry are replayed.')\n  print('per_mode: four quadratic-field inverse cases and two absolute coefficients are executed as declared.')\n  print('per_block: thirty saved residual vectors, decomposition, singleton normalization and cross-path equality are checked.')\n  print('lattice_wide: only the declared local L4 channel is replayed; general reconstruction is analytical, with no full-sixth or bulk conclusion.')\n  print('TOTAL: PASS=40 FAIL=0')"));p.write_text(s)
p=w/notes[8058];s=p.read_text().replace('Status: independent structural derivation, pending review.','Historical status at the original derivation stage: independent structural derivation, then pending review.').replace('No such solves were executed here.','No such solves had been executed at that historical derivation stage; the subsequent original run is recorded below.').replace('Post-data analytical derivation, pending cold review.','Historical status at the post-data derivation stage: then pending cold review.');p.write_text(s)
