from pathlib import Path
import sys,json,hashlib,subprocess,copy
r=Path('/private/tmp/review-drain-20260915');w=r/'author-pool/author-backlog';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));git=lambda *x:subprocess.check_output(['git','-C',str(w),*x],text=True).strip()
f=json.loads((r/'8061-author-recapture-final-freeze.json').read_text());pre=json.loads((r/'8061-author-recapture-preexecution.json').read_text());old=json.loads((r/'review-8061-provisional.json').read_text());rec=json.loads((r/'8061-unit-recapture-preexecution-v2.json').read_text());assert git('write-tree')==f['tree'] and not git('diff','--name-only')
for p,h in (f['source_paths']|f['inputs']).items():assert sha(w/p)==h,p
for p,h in (pre['nonoutput_sources']|pre['inputs']).items():assert sha(w/p)==h,p
receipts=[];payload={}
for pr,stem,total in [(8059,'native_l6_sixth_prefix_gap_certificate_2026_09_08',6489),(8061,'native_l6_nonlinear_star_vertex_2026_09_09',8)]:
 p=r/('8059-author-final-execution.json' if pr==8059 else '8061-author-recapture-execution.json');d=json.loads(p.read_text());assert d['status']=='ok' and d['exit_code']==0 and not d.get('stderr') and f'TOTAL: PASS={total} FAIL=0' in d['stdout'];assert d['elapsed_sec']<180
 wd=d['whole_tree_watchdog'];assert wd['samples']>0 and wd['peak_tree_rss_bytes']<=384*1048576 and not wd['violations'];assert sha(Path(d['capture_script']))==d['capture_script_sha256'];assert d['capture_script_sha256']==(json.loads((r/'8061-author-preexecution.json').read_text())['capture_script_sha256'] if pr==8059 else pre['capture_script_sha256'])
 receipts.append(ref(p));original=json.loads((r/f'check8061/original-{pr}/outputs'/f'{stem}.json').read_text());actual=json.loads((w/'outputs'/f'{stem}.json').read_text())
 fields=['status','certificate_groups','geometry','minimum','common_floor','native_units','rows','scope'] if pr==8059 else ['status','scope','geometry','replay','claims']
 for key in fields:assert actual[key]==original[key],(pr,key)
 if pr==8059:assert len(actual['rows'])==6489
 else:
  env=actual['runtime_environment'];assert sha(Path(env['python_executable']))==env['python_sha256'];assert sha(Path(env['numpy_origin']))==env['numpy_sha256'];assert env['numpy_native_sha256']
  for file,h in env['numpy_native_sha256'].items():assert sha(Path(file))==h
 payload[str(pr)]=dict(exact_original_math_fields_equal=fields,actual_elapsed_sec=d['elapsed_sec'],sampled_whole_tree_peak_bytes=wd['peak_tree_rss_bytes'],watchdog_samples=wd['samples'],total=total,runtime_environment=actual.get('runtime_environment'),output_sha256=sha(w/'outputs'/f'{stem}.json'))
# Actual source identity and complete original-to-final mappings; no old report rewritten.
new=copy.deepcopy(old);new.update(status='FINAL VERDICT: PASS WITH BOUNDED CLAIMS',tree=f['tree'],source_hashes=f['source_paths'],actual_inputs=f['inputs'],executions=receipts,payload_confirmation=payload,preexecution_record=ref(r/'8061-unit-recapture-preexecution-v2.json'),preflight=ref(r/'8061-recapture-preflight.json'),original_provisional_report=ref(r/'review-8061-provisional.json'),helper_semantics=ref(r/'check8061/helper-ast-confirmation.json'),final_freeze=ref(r/'8061-author-recapture-final-freeze.json'),final_cache_check_owner='/root; not executed by reviewer',scope='Finite supplied L6 prefix denominators and saved-vector fixed-reference nonlinear vacuum-image certificate only. Not all-flux/bulk/full sixth-order cancellation or nonlinear-dressing impossibility.',capture_precision='Reported RSS is sampled supervisor/descendant sum at stated interval, not an impossible claim of continuous measurement. Explicit local floating-operation assumptions remain premises.')
for rows in new['constituent_dispositions'].values():
 for row in rows:
  if row['final_path']:row['final_sha256']=sha(w/row['final_path'])
  row['disposition']=row['disposition'].replace('Final output awaits actual capture.','Actual final output has been captured and all mathematical payload fields match frozen original exactly.')
md=(r/'review-8061-working.md').read_text();md=md.replace('source verdict pending corrected final execution and immutable binding.','FINAL VERDICT: PASS WITH BOUNDED CLAIMS.');md=md.replace('No canonical source execution has yet been authorized by this review.','The final corrected sources completed the two actual bounded canonical captures below after the successful single schema2 preflight.')
md+='\n## Final same-session confirmation\n\nFinal staged tree '+f['tree']+' on '+f['base']+'. All frozen source and56 declared input hashes were checked. After the first identity-guard rejection, only8061 diagnostics and its source-manifest pin changed.8059 was not rerun. All eight helper ASTs remain identical to originals after removal of added cap/input declarations. The actual default8061 route runs the complete saved-vector replay with verified-byte loaders and records the actual interpreter/NumPy/native binary identities.\n\n'
for pr,d in payload.items():md+=f"- PR{pr}: TOTAL {d['total']}/0; {d['actual_elapsed_sec']:.6f}s under180s; sampled whole supervisor/descendant peak {d['sampled_whole_tree_peak_bytes']} bytes under384MiB. Every original mathematical output field exactly matches.\n"
md+='\nThe first8061 attempt reached a mathematical PASS output but was rejected by the cache identity guard because its progress sidecar changed the outputs directory generation. Its exact source, output, progress and stderr are preserved; its full stdout and watchdog summary were unavailable, so it is not accepted execution evidence. Only the corrected8061 run was repeated after a fresh cold confirmation and preflight. Diagnostics now stay outside repository input ancestors, and capture exceptions preserve watchdog receipts.\n'
md+='\nThe independent projection control’s imported error ceiling is now discharged by the fresh full residual replay. All762 historical paths and seven proof-source paths retain exact original bytes (decoded where compressed); the five current proof fragments are schema2 supporting science, not historical exemptions. All814 original dispositions remain explicit, including the two excluded generated manifest changes. Current-main sources are preserved: the final proposal is additions only. No source acceptance is inferred from historical review grades. Root owns the single final shared cache check and subsequent integration gate; neither is claimed here.\n'
mp=r/'review-8061.md';jp=r/'review-8061.json';assert not mp.exists() and not jp.exists();mp.write_text(md);new['capture_wrapper']=ref(r/'8061-author-recapture.py');new['failed_attempt']=ref(r/'8061-first-capture-failure.json');new['failed_attempt_binding']=ref(r/'check8061/failed-capture-binding.json');new['affected_provisional_report']=ref(r/'review-8061-affected-provisional.json');new['final_science_report']=ref(mp);jp.write_text(json.dumps(new,indent=2)+'\n');rr=ref(jp)
rec['source']['tree']=f['tree'];rec['source']['paths']=[dict(path=p,sha256=h) for p,h in sorted(f['source_paths'].items())]
for c in rec['constituents']:c['dispositions']=dict(rr,json_pointer='/constituent_dispositions/'+c['id'][2:])
rec['reviewer']['report']=rr;rec['reviewer']['references'] += receipts+[ref(mp),ref(r/'check8061/helper-ast-confirmation.json'),ref(r/'8061-author-recapture-final-freeze.json'),ref(r/'8061-recapture-preflight.json')]
for section in ['non_science_notes','supporting_proofs']:
 for item in rec[section]:item['review_reference']=rr
# Bind final output/cache bytes wherever existing input lists include them; scientific input identities must be unchanged.
for group,values in rec['inputs'].items():
 for item in values:item['sha256']=sha(w/item['path'])
path=r/'8061-unit-final-v2.json';assert not path.exists();path.write_text(json.dumps(rec,indent=2)+'\n');binding=dict(tree=f['tree'],review=ref(jp),science=ref(mp),record=ref(path),payload_confirmation=payload);(r/'8061-review-final-binding.json').write_text(json.dumps(binding,indent=2)+'\n');print(json.dumps(binding,indent=2))
