from pathlib import Path
import json,re
w=Path('/private/tmp/review-drain-20260915/author-pool/author-backlog');b=Path('/private/tmp/review-drain-20260915');a=json.loads((b/'8061-archive-anchor.json').read_text());proofdir=w/'docs/work_history/repo/review_feedback/pr8061-proof-sources';pm=json.loads((proofdir/'archive-manifest.json').read_text());proofmap={e['original_path']:str((proofdir/e['stored_path']).relative_to(w)) for e in pm['entries']};current=[v for k,v in proofmap.items() if Path(k).name not in ('third_order_parent.md','projection_cold.md')];(b/'8061-proof-source-map.json').write_text(json.dumps(proofmap,indent=2)+'\n')
for old in proofmap:(w/old).unlink()
p=w/'scripts/native_l6_sixth_prefix_gap_certificate_2026_09_08.py';s=p.read_text()
for old,new in a['8059']['mapping'].items():s=s.replace(old,new)
s=s.replace('hashlib,runpy,signal,time,resource','hashlib,importlib.util,signal,time,resource,sys').replace("ap.parse_args()","args=ap.parse_args()")
s=s.replace("resource.getrusage(resource.RUSAGE_SELF).ru_maxrss>384*1048576","resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*(1 if sys.platform=='darwin' else 1024)>384*1048576")
s=s.replace("core=runpy.run_path(str(root/AUDIT_INPUT_PATHS[4]));geom=runpy.run_path(str(root/AUDIT_INPUT_PATHS[5]))","spec=importlib.util.spec_from_file_location('gap_arithmetic',root/'scripts/native_l6_sixth_prefix_gap_arithmetic_2026_09_08.py');core=importlib.util.module_from_spec(spec);spec.loader.exec_module(core)\n  spec=importlib.util.spec_from_file_location('gap_geometry',root/'scripts/native_l6_sixth_prefix_gap_geometry_2026_09_08.py');geom=importlib.util.module_from_spec(spec);spec.loader.exec_module(geom)")
for n in ('baseline','gap'):s=s.replace("core['"+n+"']",'core.'+n)
s=s.replace("geom['check']",'geom.check').replace("rss_bytes=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,","rss_bytes=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss*(1 if sys.platform=='darwin' else 1024),")
s=s.replace('  print(json.dumps(payload,indent=2))',"  (root/'outputs/native_l6_sixth_prefix_gap_certificate_2026_09_08.json').write_text(json.dumps(payload,indent=2)+'\\n')\n  print(json.dumps({k:v for k,v in payload.items() if k!='rows'},indent=2))\n  if not args.json:\n   print('TOTAL: PASS=6489 FAIL=0')\n   print('per_cone: exact prefix geometry covers only the six declared finite L6 supports.')\n   print('per_mode: every declared proper mask has its fixed-parity rational denominator bound checked.')\n   print('per_boundary_sample: saved finite-support coverage is checked; no boundary ensemble is sampled.')\n   print('half_slab: no half-slab field or stochastic slab evolution is executed by this certificate.')\n   print('lattice_wide: all6489 declared proper masks replay; no all-flux or all-volume enumeration.')")
p.write_text(s)
note59='docs/NATIVE_L6_SIXTH_PREFIX_GAP_CERTIFICATE_NOTE_2026-09-08.md';note61='docs/NATIVE_L6_NONLINEAR_STAR_VERTEX_NOTE_2026-09-09.md';parent='docs/NATIVE_THIRD_ORDER_STAR_VERTEX_NOTE_2026-09-08.md'
for name in ('arithmetic','geometry'):
 p=w/f'scripts/native_l6_sixth_prefix_gap_{name}_2026_09_08.py';p.write_text('AUDIT_TIMEOUT_SEC=180\nAUDIT_INPUT_PATHS='+repr(tuple([note59]+[v for k,v in a['8059']['mapping'].items() if '/live_inputs/' in k]))+'\n'+p.read_text())
manifestpath=w/'outputs/native_l6_nonlinear_star_vertex_2026_09_09_inputs/SOURCE_MANIFEST.json';manifest=json.loads(manifestpath.read_text());newkeys=[proofmap.get(k,k) for k in manifest];newkeys.append(parent);inputs=sorted(set(newkeys+[str(manifestpath.relative_to(w))]))
p=w/'scripts/native_l6_nonlinear_star_vertex_2026_09_09.py';s=p.read_text().replace('"""Portable saved-candidate certificate. --verify performs the full replay; never a solve."""','"""Canonical full saved-candidate replay; no solves. Explicit readiness mode is historical only."""')
s=s.replace('AUDIT_TIMEOUT_SEC=180','AUDIT_TIMEOUT_SEC=180\nAUDIT_INPUT_PATHS='+repr(tuple(inputs)))
start=s.index('def load(alias,name):');end=s.index('\ndef claims',start);loaders=''
for alias,name in [('canonical_geometry','geometry'),('envelope','envelope'),('transport','transport'),('fp_guard','fp_guard'),('validate_coefficients','validate_coefficients'),('canonical_replay','review')]:
 path=f'scripts/native_l6_nonlinear_vertex_{name}_2026_09_09.py';loaders+=f"def load_{alias}():\n p=ROOT/{path!r};data=p.read_bytes()\n require(hashlib.sha256(data).hexdigest()==json.loads((INPUT/'SOURCE_MANIFEST.json').read_text())[str(p.relative_to(ROOT))],'verified source bytes')\n spec=importlib.util.spec_from_file_location({alias!r},ROOT/{path!r});m=importlib.util.module_from_spec(spec);sys.modules[{alias!r}]=m;spec.loader.exec_module(m);m.P=INPUT\n return m\n\n"
s=s[:start]+loaders+s[end:];s=s.replace("ap.add_argument('--verify',action='store_true');args=ap.parse_args()","ap.add_argument('--verify',action='store_true');ap.add_argument('--readiness-only',action='store_true');args=ap.parse_args()\n require(not (args.verify and args.readiness_only),'incompatible verify/readiness flags')\n if not (sys.flags.isolated and sys.flags.dont_write_bytecode) or any(os.environ.get(k)!='1' for k in ('OPENBLAS_NUM_THREADS','OMP_NUM_THREADS','VECLIB_MAXIMUM_THREADS')):\n  env=dict(os.environ);env.update({k:'1' for k in ('OPENBLAS_NUM_THREADS','OMP_NUM_THREADS','VECLIB_MAXIMUM_THREADS')});os.execve(sys.executable,[sys.executable,'-I','-B',str(Path(__file__).resolve()),*sys.argv[1:]],env)")
s=s.replace("load('canonical_geometry','geometry').check(INPUT)","load_canonical_geometry().check(INPUT)")
s=s.replace("  for alias,name in [('envelope','envelope'),('transport','transport'),('fp_guard','fp_guard'),('validate_coefficients','validate_coefficients'),('canonical_replay','review')]:imported[alias]=load(alias,name)","  imported['envelope']=load_envelope()\n  imported['transport']=load_transport()\n  imported['fp_guard']=load_fp_guard()\n  imported['validate_coefficients']=load_validate_coefficients()\n  imported['canonical_replay']=load_canonical_replay()")
s=s.replace('if not args.verify:','if args.readiness_only:').replace("  require(not output.exists(),'fresh canonical output')\n",'')
s=s.replace("print(output.read_text())","print(output.read_text())\n  if not args.json:\n   print('TOTAL: PASS=7 FAIL=0')\n   print('per_cone: actual saved-candidate replay is restricted to the declared finite L6 star support.')\n   print('per_mode: the complete108-mode linear vacuum-action comparison is certified by the stated projection proof.')\n   print('per_boundary_sample: seven saved full vectors are replayed; no new candidate sampling or solve is performed.')\n   print('half_slab: no half-slab simulation is executed; four fresh residuals certify the saved vectors.')\n   print('lattice_wide: the supplied finite L6 certificate is replayed; no all-volume interacting claim is tested.')")
p.write_text(s)
for name in ('geometry','envelope','transport','fp_guard','validate_coefficients','review'):
 p=w/f'scripts/native_l6_nonlinear_vertex_{name}_2026_09_09.py';data=[k for k in inputs if k.startswith('outputs/') and not k.endswith('SOURCE_MANIFEST.json')];p.write_text('AUDIT_TIMEOUT_SEC=180\nAUDIT_INPUT_PATHS='+repr(tuple([note61,parent]+current+data))+'\n'+p.read_text())
# Current proof fragments move byte-exact; cold review and the old parent snapshot remain recoverable history.
p=w/note61;s=p.read_text();s=s.replace('../outputs/native_l6_nonlinear_star_vertex_2026_09_09_inputs/proofs/third_order_parent.md','NATIVE_THIRD_ORDER_STAR_VERTEX_NOTE_2026-09-08.md')
for old,new in proofmap.items():
 target=new if old.endswith(('third_order_parent.md','projection_cold.md')) else new
 replacement='work_history/repo/review_feedback/pr8061-proof-sources/README.md' if old.endswith(('third_order_parent.md','projection_cold.md')) else target.removeprefix('docs/')
 s=s.replace('../'+old,replacement)
s=s.replace('third-order star theorem, pinned upstream snapshot','third-order star theorem, current reviewed source')
s+='\n\n## Current execution and historical provenance\n\nThe canonical default runner performs the full saved-vector replay under isolated Python, disabled bytecode and single-thread numerical libraries. It does not solve for new vectors. The accepted status fields and old receipts are historical integrity checks, not a current review verdict. The original8058 snapshot and projection cold review remain exactly recoverable in the [proof-source mapping](work_history/repo/review_feedback/pr8061-proof-sources/README.md); the linked current8058 theorem is the actual parent. The five linked mathematical proof fragments remain current scientific inputs, byte-identical to the originals.\n\n[Canonical cache](../logs/native_l6_nonlinear_star_vertex_2026_09_09.txt).\n';p.write_text('\n'.join(l.rstrip() for l in s.splitlines())+'\n')
p=w/note59;s=p.read_text();s+='\n\n## Current execution and historical provenance\n\nThe canonical replay writes all6489 rational rows to the tracked output and reports a concise stdout certificate. Historical candidate-generation and mutation campaigns are preserved as original evidence, not new executions. The exact five live ledgers remain raw runtime inputs. [Historical packet](work_history/repo/review_feedback/pr8059-evidence/README.md). [Canonical cache](../logs/native_l6_sixth_prefix_gap_certificate_2026_09_08.txt).\n';p.write_text('\n'.join(l.rstrip() for l in s.splitlines())+'\n')
readme=proofdir/'README.md';readme.write_text(readme.read_text()+'\n## Current scientific source distinction\n\nThe raw projection, adapted-frame, four-solve, real-sign and real-error fragments are current scientific inputs to the canonical8061 claim. Their exact original arguments require full independent review. The compressed third-order parent snapshot and projection cold-review prose are historical provenance; current canonical8058 supplies the actual parent. The original-path manifest preserves every byte and disposition separately.\n')
(b/'8061-author-source-plan.json').write_text(json.dumps({'proofmap':proofmap,'current_proofs':current,'manifest_keys':newkeys,'primary_inputs':inputs},indent=2)+'\n')
