from pathlib import Path
import subprocess,json,hashlib
r=Path('/private/tmp/review-drain-20260915');w=r/'review-slot-one'
n=w/'docs/FORMATION_ORDER_COVARIANCE_AND_ISOTROPIC_BINARY_ORDER_BLIND_CLASSIFICATION_BOUNDED_THEOREM_NOTE_2026-09-13.md'
s=w/'scripts/formation_order_covariance_and_isotropic_binary_order_blind_classification_2026_09_13.py'
t=n.read_text()
def rep(a,b):
 global t
 assert a in t,a
 t=t.replace(a,b)
rep('the two consecutive sites are lattice neighbours and the adjacent-pair exchange identity fails on that background','the two consecutive sites are lattice neighbours and the adjacent-pair exchange identity fails on some positive-probability ordered prefix and pair assignment')
rep('the identity forcing this is that the path3 matching residual equals (pminus-pplus)^2','two-site equality forces the empty-site probability into (0,1), path3 marginal matching forces pminus=pplus, and a star argument forces every f(m,k), m<=6, to that constant')
rep('So a sequential single-site formation process, whose\nphysical content includes an order, is never itself lattice-covariant.','This excludes a fixed invariant deterministic order. It does not exclude a\ncovariant random order law, covariance when the order is transformed with\nthe data, or an order-blind terminal record law.')
rep('Admissibility still supplies one covariant nearest-neighbor rule, and Record\nsays records form. The rule may be applied along any order.','Admissibility supplies one covariant nearest-neighbor rule, and Record says\nrecords form. This note separately declares a binary sequential product\nconstruction in which a kernel is applied along a supplied finite order;\nit does not derive that process construction from the axioms.')
rep('on every recorded background. On the isotropic binary alphabet the interior order-blind kernels are the\nonly independent rules:', 'on every ordered prefix and assignment having positive prefix probability.\nNull prefixes impose no exchange constraint. On the isotropic binary alphabet\norder-blindness in the interior class allows only independent rules:')
rep('`(pminus - pplus)^2`.','`(pminus - pplus)^2`; a star with up to six mutually nonadjacent leaves\nthen extends constancy to every allowed neighbour count.')
a=t.index('The physical formation order is not selected.');b=t.index('## Machine status and trace',a)
t=t[:a]+'''The physical formation order is not selected. The note selects neither order
and selects neither rule. Its witnesses compare conditional record laws
under explicitly supplied orders in a declared binary model. The
[`REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md`](REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md)
classifies values at law-admissible realized states; it supplies neither an
order measure nor a process selector. It does not by itself classify the
choice between stochastic laws as registered data. No two full four-axiom
worlds or covariant possibility-carrier embeddings are constructed here,
so framework-wide nonselection is not proved. Illustrative extensions are
owner decisions and are not adopted.

'''+t[b:]
rep('"the axioms do not force a unique sequential formation law; order-dependent record statistics remain registered data until a clause supplies an order, a covariant order-law, joint covariant formation, or order-blindness"','"the declared varying binary product kernel gives different record laws under supplied orders; no physical process selector or full-axiom model comparison is provided"')
rep('No infinite-volume statement, no physical-law selection','No infinite-volume formation-process claim, no physical-law selection')
rep('A\nquantity that changes with the realized formation order is of that kind\nunless the rule is order-blind.','This does not automatically classify alternative stochastic laws as values\nof one law-admissible realized state. The supplied process construction and\norders remain explicit mathematical inputs.')
rep('No order is supplied.','No physical order is selected; the finite test orders and the binary\nproduct construction are supplied mathematical inputs.')
rep('| exchange identity characterizes order-blindness | the symmetric group is generated by adjacent transpositions |','| exchange on positive-probability ordered prefixes characterizes order-blindness | cancel a positive common prefix after summing the normalized suffix; adjacent transpositions generate the symmetric group |')
rep('| interior isotropic binary order-blind kernels are independent | path3 matching residual equals `(pminus-pplus)^2` |','| interior isotropic binary order-blind kernels are independent | two-site interiority, exact path3 polynomial expansion, and positive star-leaf cancellation through six neighbours |')
a=t.index('Translations do not help:');b=t.index('## Theorem 2',a)
t=t[:a]+'''Translations alone do allow an invariant total order: the lexicographic
order on `Z^3` is translation-invariant, since translating both points
preserves their first differing coordinate and its sign. The obstruction
above is the finite nontrivial rotation orbit, not free translation action.

This is a statement about fixed invariant orders. A covariant local rule
can be applied along a non-invariant order, with covariance of the family
when that order is transformed as well. A covariant probability law over
orders or an order-blind terminal law is a different requirement.

'''+t[b:]
a=t.index('If `x` and `y` are lattice neighbours,');b=t.index('The runner executes',a)
t=t[:a]+'''Fix also the values on the common ordered prefix and let `W` be their
prefix product probability. For a neighbouring pair with values `a,b`,
write `L = r(a | S_x) r(b | S_y union {x:a})` and
`R = r(b | S_y) r(a | S_x union {y:b})`. The two joint probabilities
are `W L Q` and `W R Q`, where `Q` is the same conditional suffix product:
after the pair, every later site sees the same earlier sites and values.
Summing `Q` over all suffix assignments gives one by successive conditional
normalization. Thus equality of the two joint laws is equivalent to
`W (L-R) = 0` for every prefix assignment and pair assignment. If `W>0`,
this is precisely exchange; if `W=0`, both laws vanish regardless of `L-R`.

Adjacent transpositions generate the symmetric group. Consequently order
independence on every finite window is equivalent to exchange on every
positive-probability ordered prefix for each lattice-adjacent pair. If all
conditionals are strictly positive, every geometric prefix assignment is
positive and the unweighted criterion applies to all such backgrounds.
Geometric realizability alone is insufficient when zero probabilities occur.

For example, set `f(m,0)=0`, `f(1,1)=1/2`, and `f(m,k)=1/3` for
`m>=2,k>0`. Every empty-start finite product process is all-zero under
every order. On the unreachable plus prefix `z` of `z—x—y`, however,
with `x=1,y=0`, the local products for `x,y` and `y,x` are respectively
`1/4` and `1/3`. The zero prefix weight removes this apparent obstruction.

'''+t[b:]
a=t.index('On a three-site path `L—M—R`, two orders');b=t.index('The independent kernel',a)
t=t[:a]+'''Write `p=pplus=f(1,1)`, `q=pminus=f(1,0)`, and `c=p0=f(0,0)`.
The hypothesis gives `p,q in (0,1)`; interiority of `c` must be derived.
On a two-site edge, matching the orders on the `+,-` configuration yields
`c(1-p)=(1-c)q`, so `c=q/(1-p+q) in (0,1)`.

On the three-site path `L—M—R`, compare chain order `L,M,R` with
ends-first `L,R,M`. In the ends-first law, `R` is independent of `L`
with plus probability `c`. In the chain law, conditional on `L=+`,
its plus probability is `p^2+(1-p)q`; conditional on `L=-`, its minus
probability is `(1-q)^2+q(1-p)`. Both conditioning events have positive
probability because `c in (0,1)`. Matching these marginals therefore gives

```text
c = p^2 + (1-p)q,
1-c = (1-q)^2 + q(1-p).
```

Adding and subtracting one gives the exact polynomial expansion

```text
0 = p^2 + (1-p)q + (1-q)^2 + q(1-p) - 1
  = p^2 - 2pq + q^2 = (q-p)^2.
```

Thus `p=q=c`. This identity is algebraic for all real `p,q`; the runner's
rational samples are controls, not a proof of universality.

To cover every `m<=6`, choose a star consisting of one lattice site and
any `m` of its six axial nearest neighbours. These leaves are mutually
nonadjacent. In leaves-first order a prescribed leaf assignment with `k`
pluses has positive probability `B=c^k(1-c)^(m-k)`; the center-plus joint
is `B f(m,k)`. In center-first order the center has plus probability `c`
and, conditional on it, each leaf has plus probability `f(1,1)=c`, so the
same joint is `c B`. Order-blindness and `B>0` imply `f(m,k)=c` for all
`0<=k<=m<=6`. No positivity assumption on the higher-neighbour slots was
needed. This establishes the declared isotropic classification; it makes
no classification claim for geometric orbits outside that class.

'''+t[b:]
a=t.index('The axioms as written do not force');b=t.index('None of these is adopted here.',a)
t=t[:a]+'''The declared binary product construction leaves a physical process choice
unresolved. The following are illustrative, nonexhaustive proposals for an
owner decision, not minimal separating axioms or consequences established
by two full-axiom worlds:

1. restrict this sequential model to order-blind kernels (in its interior
   isotropic binary class, these are constant and fail the variation condition);
2. specify a construction for joint formation on covariant sets;
3. supply a covariant probability law on formation orders;
4. allow a supplied order to remain process data, without demanding that
   its conditional terminal law be invariant under rotations.

'''+t[b:]
a=t.index('Lemma C is a one-line group fact');b=t.index('## Verification',a)
t=t[:a]+'''Lemma C is a finite-orbit argument for fixed orders on `Z^3`. The exchange
criterion includes positive prefix probability and normalized suffix
cancellation. Two-site interiority, the path3 polynomial identity, and the
star argument prove the interior isotropic binary classification through
all six neighbour slots. The witness compares supplied orders for one
declared covariant binary kernel on three small graphs. It establishes
order dependence within that construction, without proving two complete
four-axiom models, an axiom-level nonselection theorem, or a physical process.

'''+t[b:]
n.write_text(t)
u=s.read_text();needle='    return checks.finish()'
assert u.count(needle)==1
u=u.replace(needle,'''    # Regression controls for the positive-prefix and six-neighbour proof gaps.
    points = tuple(product(range(-1, 2), repeat=3))
    shift = (2, -3, 1)
    checks.check(
        "translation-lexicographic-counterexample",
        all((a < b) == (tuple(a[i] + shift[i] for i in range(3))
                       < tuple(b[i] + shift[i] for i in range(3)))
            for a in points for b in points),
        "lexicographic order is translation-invariant; finite samples control the written general proof",
    )

    def null_prefix_plus(m, k):
        if k == 0:
            return Fraction(0)
        return Fraction(1, 2) if m == 1 else Fraction(1, 3)

    null_laws = {joint_vector(order, 3, path_edges, null_prefix_plus)
                 for order in permutations(range(3))}
    checks.check(
        "null-prefix-unweighted-exchange-counterexample",
        len(null_laws) == 1 and next(iter(null_laws))[0] == 1
        and site_factor(null_prefix_plus, 1, [1]) * site_factor(null_prefix_plus, 0, [1]) == Fraction(1, 4)
        and site_factor(null_prefix_plus, 0, []) * site_factor(null_prefix_plus, 1, [1, 0]) == Fraction(1, 3),
        "all-zero path laws agree although unreachable plus-prefix local products are 1/4 and 1/3",
    )
    star_ok = True
    for m in range(7):
        star_edges = undirected_edges(tuple((0, j) for j in range(1, m + 1)))
        center_first = tuple(range(m + 1))
        leaves_first = tuple(range(1, m + 1)) + (0,)
        c = Fraction(2, 5)
        def star_kernel(n, k):
            return c if n < 2 else Fraction(k + 1, n + 2)
        for values in product((0, 1), repeat=m):
            k = sum(values)
            mass = c ** k * (1-c) ** (m-k)
            config = (1,) + values
            star_ok &= mass > 0
            star_ok &= formation_probability(center_first, config, star_edges, star_kernel) == c * mass
            star_ok &= formation_probability(leaves_first, config, star_edges, star_kernel) == mass * star_kernel(m, k)
    checks.check(
        "star-positive-leaf-cancellation-through-six",
        star_ok,
        "center-first and leaves-first joint factorizations checked for every binary leaf assignment through six neighbours",
    )
    print("per_element: exact binary probabilities and rational witness joints")
    print("per_site: all 23 nonidentity proper cubic rotations move a tested seed")
    print("per_mode: no Fourier-mode calculation is claimed")
    print("per_block: path3, plaquette, 2x3 census and star controls through six neighbours")
    print("lattice_wide: written rotation and exchange/star proofs; no infinite-volume formation-process claim")
    return checks.finish()''')
s.write_text(u)
subprocess.run(['git','add','--',str(n.relative_to(w)),str(s.relative_to(w))],cwd=w,check=True)
subprocess.run(['git','diff','--cached','--check'],cwd=w,check=True)
result={'tree':subprocess.check_output(['git','write-tree'],cwd=w,text=True).strip(),'changed':{str(p.relative_to(w)):hashlib.sha256(p.read_bytes()).hexdigest() for p in(n,s)},'primary_executed':False,'old_cache_retained_pending_new_capture':True}
(r/'8096-author-fixed-cold.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps(result))
