from pathlib import Path
import json,subprocess,hashlib,sys
w=Path.cwd();r=w.parent;j=json.loads((r/'check8098/inventory.json').read_text());g=lambda *a:subprocess.check_output(['git',*a],text=True).strip();assert not g('status','--porcelain');base=g('rev-parse','HEAD');patch=subprocess.check_output(['git','diff','--binary',j['original_base'],j['head'],'--',*j['canonical']]);(r/'8098-author-original-source.patch').write_bytes(patch);subprocess.run(['git','apply','--index'],input=patch,check=True)
sys.path.insert(0,str(w/'docs/ai_methodology/skills/review-loop/scripts'));import review_workspace as op
prefix='.claude/science/physics-loops/native-weyl-gauge-response-20260913/';dest=w/'docs/work_history/repo/review_feedback/pr8098-evidence';m=op.archive(w,j['head'],prefix,dest,['REVIEW_HISTORY.md'],'pr8098');(r/'8098-author-archive.json').write_text(json.dumps(m,indent=2)+'\n');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();mh=sha(dest/'archive-manifest.json');op.verify_archive(dest,mh)
runner=w/next(p for p in j['canonical'] if p.endswith('.py'));s=runner.read_text();needle=' print(json.dumps(result,indent=2))';assert s.count(needle)==1;s=s.replace(needle,needle+"\n print('TOTAL: PASS='+str(result['check_count'])+' FAIL=0')");runner.write_text(s)
subprocess.run(['git','add','--',*j['canonical'],str(dest)],check=True);paths=g('diff','--cached','--name-only').splitlines();subprocess.run(['python3','scripts/vocab_lint.py','--fix','--report-path',str(r/'8098-author-vocab.json'),*paths],check=True);subprocess.run(['git','add','--',*paths],check=True)
for args in [('diff','--check'),('diff','--cached','--check'),('diff','HEAD','--check')]:subprocess.run(['git',*args],check=True)
(r/'8098-author-packaging.json').write_text(json.dumps({'base':base,'tree':g('write-tree'),'source_paths':{p:sha(w/p) for p in paths},'archive_manifest_sha256':mh,'change':'Actual-count TOTAL footer only; no mathematical changes. No original canonical output/cache. No scientific execution.'},indent=2)+'\n');print(len(paths),g('write-tree'))
