from pathlib import Path
import json,hashlib,subprocess,importlib.util,re
r=Path('/private/tmp/review-drain-20260915');w=r/'drain-author8143';rp=r/'drain8143-final-review.json';report=json.loads(rp.read_text());inv=json.loads((r/'drain8143-inventory.json').read_text())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)};bind=lambda paths:[{'path':p,'sha256':sha(w/p)} for p in sorted(set(paths))];git=lambda *args:subprocess.check_output(['git','-C',str(w),*args],text=True).strip()
spec=importlib.util.spec_from_file_location('rr',w/'docs/ai_methodology/skills/review-loop/scripts/review_receipt.py');rr=importlib.util.module_from_spec(spec);spec.loader.exec_module(rr);g,c,a=rr.repository_apis(w)
n='docs/FULL_DOMAIN_MATRIX_KERNEL_AND_AUTONOMOUS_PROJECTIVE_RECORD_CORRIDOR_BOUNDED_THEOREM_NOTE_2026-09-15.md';primary='scripts/full_domain_matrix_kernel_and_autonomous_projective_record_corridor_2026_09_15.py';body=(w/n).read_text();paths=git('diff','--cached','--name-only').splitlines();assert git('write-tree')==report['source_tree'];citations=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/n));parents=[p for p in citations if p.startswith('docs/')];assert len(parents)==2;assert c.declared_input_paths(primary) is None;assert g.helper_runner_paths_for_claim(g.claim_id_from_path(w/n),primary)==[]
context={x['path'] for x in report['context_inputs']}
for x in report['context_inputs']:assert sha(w/x['path'])==x['sha256']
tooling=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
m=re.search(r'^claim_id:\s*(.+)$',body,re.M)
record={'schema_version':2,'unit_id':'PR8143-final','constituents':[{'id':'8143','head':inv['head'],'delta_base':inv['delta_base'],'dispositions':dict(ref(rp),json_pointer='/original_dispositions')}],'source':{'base':report['source_base'],'commit':git('rev-parse','HEAD'),'tree':git('write-tree'),'paths':bind(paths),'deleted_paths':[]},'inputs':{'runtime':[],'helpers':[],'parents':bind(parents),'context':bind(context),'tooling':bind(tooling)},'reviewer':{'session':'/root/review_8011','report':ref(rp),'references':report['references']},'notes':[{'path':n,'claim_id':g.claim_id_from_path(w/n),'declared_claim_id':m[1] if m else None,'claim_type':'bounded_theorem','primary_runner':primary,'helpers':[],'citations':citations,'repository_dependencies':parents,'dependency_rationale':'Current axiom authority delimits baseline. The linked local-append projective-history construction is an explicitly supplied benchmark, not a framework-derived generator. Its exact scoped grants were independently reviewed; no new physical process is adopted.'}],'non_science_notes':[{'path':p,'rationale':'Exact historical author conformance/handoff provenance or recovery navigation; no independent review or audit authority. Original mutation/validation JSON evidence retained unchanged.','review_reference':ref(rp)} for p in paths if p.endswith('.md') and p!=n],'supporting_proofs':[]}
p=r/'drain8143-unit-final.json';assert not p.exists();p.write_text(json.dumps(record,indent=2)+'\n');print('Final record',len(paths),'source paths')
