from pathlib import Path
import ast,collections,difflib,gzip,hashlib,json,subprocess
R=Path('/private/tmp/review-drain-20260915');W=R/'author-draft-slot';P=R/'drain8030-originals';review=json.loads((R/'drain8030-original-review.json').read_text());sha=lambda b:hashlib.sha256(b).hexdigest();rows=review['original_dispositions'];assert len(rows)==89
note='docs/GAUGE_WILSON_WEAK_WINDOW_QUANTITATIVE_BOUNDS_AND_HAAR_CONTACT_FDD_BOUNDED_THEOREM_NOTE_2026-09-07.md';oldnote='docs/GAUGE_WILSON_UNIFORM_WEAK_CONTINUUM_CORRELATION_BOUNDARY_BOUNDED_THEOREM_NOTE_2026-09-07.md';runners=['scripts/gauge_wilson_uniform_weak_scaling_controls_2026_09_07.py','scripts/gauge_wilson_haar_contact_fdd_controls_2026_09_07.py'];parents=list(review['inputs']['repository_parents']);hist='docs/work_history/review_loop/pr8030';owned=[];manifest=[]
def put(path,data):
 p=W/path;assert not p.exists(),path;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data if isinstance(data,bytes) else data.encode());owned.append(path)
for i,e in enumerate(rows):
 b=Path(e['recovery_path']).read_bytes();assert sha(b)==e['sha256'];assert subprocess.check_output(['git','-C',str(W),'cat-file','blob',e['blob']])==b
 dest=f'{hist}/originals/{i:03d}-{Path(e["path"]).name}.gz';put(dest,gzip.compress(b,mtime=0));assert gzip.decompress((W/dest).read_bytes())==b
 disposition='Exact original preserved, historical only; original negative-classification certification deferred, not rejected mathematically.'
 canonical=note if e['path']==oldnote else e['path'] if e['path'] in runners else None
 manifest.append({k:e[k] for k in ['path','mode','blob','sha256']}|{'stored':dest,'encoding':'gzip, exact decoded original bytes','archive_sha256':sha((W/dest).read_bytes()),'canonical_path':canonical,'disposition':disposition})
put(hist+'/manifest.json',json.dumps({'head':review['head'],'delta_base':review['delta_base'],'paths':manifest},indent=2)+'\n')
put(hist+'/README.md','# PR8030 partial mathematical salvage and exact recovery\n\nThe [manifest](manifest.json) records all 89 originals, including 81 historical paths, their modes, blobs and decoded SHA256 identities. Every gzip payload preserves exact source bytes, including original negative arguments, earlier source-alignment/FDD wording, base64 differences, failed paths and raw outputs. The manifest and archived payloads preserve original source independently of branch retention.\n\nThe canonical note retains quantitative estimates, actual Haar contact finite-dimensional distributions, the conditional gap/locality ratio and the complete optional moment/skew argument. Certification of the original separated-field exclusion remains deferred because the current N1 attack requirement was not met. This is not a mathematical disproof and is not a relabeled positive exclusion. Historical reviews, timing and claims of independence are historical only; original outputs are not fresh canonical evidence. The coordinator must preserve the original branch for this partial salvage.\n')
original=(P/oldnote).read_text();native=original.split('# A precise continuum-correlation boundary inside a uniform weak-electric window\n',1)[1].split('\n\n# Independent contact proof with explicit remainder constants',1)[0]
# Exact boundaries: no Markdown/formula matching or general link rewriting.
native=native[native.index('## 1. One consistent supplied model and a uniform window'):]
native=native.split('## 6. Exact conclusion and next residual',1)[0]
native=native.replace('## 2. Fixed-support fields at positive physical separation','## 2. Quantitative fixed-support estimate at positive physical separation')
remove1='This rules out a nonzero separated-point connected limit for this specified class under the uniform-window hypothesis. '
assert remove1 in native;native=native.replace(remove1,'The estimate above is retained; certification of the original separated-field exclusion is deferred under N1. ')
remove2='Thus a statement that uniform weak coupling forbids EVERY nontrivial continuum limit would be false. The theorem excludes nonzero off-diagonal connected correlations for the stated renormalized local field class while allowing nontrivial contact data.'
assert remove2 in native;native=native.replace(remove2,'The retained result here is the actual contact finite-dimensional distribution construction and its displayed bounds. The original separated-field negative classification is not certified by this partial salvage.')
native=native.replace('## 4. An actual contact-limit adverse to an overbroad no-go','## 4. Actual Haar contact finite-dimensional distributions')
for a,b in [('reviewed34 gap bound and35 Lieb–Robinson estimate','reviewed uniform-gap bound and local-observable Lieb–Robinson estimate'),('The35 link metric','The local-observable source link metric'),('the34 lower bound','the uniform-gap lower bound')]:native=native.replace(a,b)
contact=original.split('# Independent contact proof with explicit remainder constants\n\n',1)[1]
contact=contact.replace('# Exact Haar contact-limit sharpness example','## Full contact proof with explicit remainder constants')
contact=contact.replace('**Type:** bounded_theorem, conditional on the supplied u=0 compact-link product Haar ground, spatial mesh and field normalization. Root exposed the candidate before the prospective contract. This proof froze before reading native40. No generic central limit theorem is imported.','This proof is conditional on the supplied u=0 compact-link product Haar ground, spatial mesh and field normalization. Its original candidate-exposure and freeze narrative is historical provenance. No generic central limit theorem is imported.')
contact=contact.replace('It demonstrates why a separated-correlation obstruction must retain its contact-term exclusion.','The construction and its stated FDD scope are retained independently of the deferred negative-classification certification.')
rootpath='.claude/science/physics-loops/uniform-weak-continuum-boundary-20260907/evidence/root_contact/ROOT_DERIVATION.md';root=(P/rootpath).read_text();optional=root.split('## Actual independent variables',1)[1].split('## Why this sharpens the continuum boundary',1)[0];optional='## Actual independent variables'+optional
optional=optional.replace("a polynomial budget consistent with block40's assumptions. This construction is therefore not an exception to its separated-correlation conclusion.",'a polynomial budget consistent with the quantitative norm assumptions above. The FDD construction is retained without certifying the original negative classification.')
header=f'''---\nclaim_id: {Path(note).stem.lower()}\nclaim_type: bounded_theorem\nbodyType: bounded_theorem\nrunner: {runners[0]}\nupstream_dependencies: {json.dumps(parents)}\nclaim_scope: "Partial salvage: quantitative uniform-window estimates, actual Haar contact FDD, conditional gap/LR ratio and optional Haar moments. Original separated-field negative certification deferred under N1."\nnegative_certification_status: deferred\n---\n\n# Quantitative weak-window bounds and Haar contact FDD: partial salvage\n\n**Type:** bounded_theorem\n\n```yaml\nactual_current_surface_status: conditional-support\nconditional_surface_status: conditional-support\ntrace_class: upstream_support\nreachability_to_target: supports\naudit_required_before_effective_retained: true\nbare_retained_allowed: false\nhypothetical_axiom_status: null\nadmitted_observation_status: null\n```\n\nThis note retains the displayed quantitative clustering and weighted-smearing estimates, the actual positive Haar contact finite-dimensional distributions, and the conditional gap/Lieb–Robinson ratio. The optional third/fourth moments and finite-mesh skew formula are preserved in full below. These are conditional results for supplied model, norm, mesh and time choices.\n\n**Deferred:** the original separated-field exclusion has not met the current N1 negative-certification requirement. Its mathematical argument is not disproved, but this partial salvage does not certify that classification or rename it as a positive theorem. The complete original exclusion proof is preserved exactly in the [recovery archive](work_history/review_loop/pr8030/README.md); its branch must remain available under the partial-salvage disposition.\n\n## Actual mathematical inputs\n\n'''
labels=['compact Hamiltonian source','volume-uniform gap source','local-observable approximation and locality source','selected infinite static-source sector source']
for p,label in zip(parents,labels):
 assert sha((W/p).read_bytes())==review['inputs']['repository_parents'][p]['sha256'];header+=f'- [{label}]({Path(p).name}).\n'
header+='\nUse the same whole-range neutral state and the direct Yarotsky0411042 equation16 import stated below; no periodic-boundary identification is introduced. Original authorship, exposure, timing and independence statements in the recovery packet are historical.\n\n'
footer='''\n## Accepted scope and deferred certification\n\nRetained: equations (1)–(3), the weighted pairwise smearing bound with every stated hypothesis, actual u=0 Haar contact FDD and its explicit logarithmic remainder, and the conditional gap/LR scale comparison. No tightness, dynamics, physical speed or coupling selection follows. The original separated-field negative classification remains procedurally deferred; the listed scope controls are not five independent failed in-domain mechanisms.\n\nThe two programs execute finite exact arithmetic and actual finite plaquette-disjointness controls. Analytical clustering, asymptotic estimates and FDD convergence are not numerical executions. Scaling TOTAL18 includes one resource predicate; contact TOTAL13 counts scientific controls, with a separate resource guard.\n\n'''
for p in runners:footer+=f'- [Program {Path(p).stem}](../{p}); [current cache](../logs/runner-cache/{Path(p).stem}.txt).\n'
new=header+native+'\n'+contact+'\n## Optional exact Haar moments and finite-mesh skew proof\n\n'+optional+footer;put(note,new)
# Independent preservation check: compare literal mathematical lines, not the rewriting routine.
def mathlines(s):return collections.Counter(x for x in s.splitlines() if x.startswith(' ') and x.strip())
source_native=original.split('## 1. One consistent supplied model and a uniform window',1)[1].split('## 6. Exact conclusion and next residual',1)[0]
source_contact=original.split('# Independent contact proof with explicit remainder constants\n\n',1)[1]
source_optional=root.split('## Actual independent variables',1)[1].split('## Why this sharpens the continuum boundary',1)[0]
assert mathlines(new)==mathlines(source_native)+mathlines(source_contact)+mathlines(source_optional)
patch=list(difflib.unified_diff(original.splitlines(True),new.splitlines(True),fromfile=oldnote,tofile=note));inputs=[note]+parents
for p in runners:
 old=(P/p).read_text();s=old;assert 'AUDIT_INPUT_PATHS' not in s
 pins='AUDIT_INPUT_PATHS = '+repr(inputs)+'\n_REPO_ROOT = Path(__file__).resolve().parents[1]\n_INPUT_TEXT = {p: (_REPO_ROOT / p).read_text() for p in AUDIT_INPUT_PATHS}\n'
 for q in inputs:
  txt=new if q==note else (W/q).read_text();title=next(x for x in txt.splitlines() if x.startswith('# '));pins+=f'assert {title!r} in _INPUT_TEXT[{q!r}]\n'
 pins+='assert "|connected(A_ell,B_ell)| <= K ell^(−p−q) exp(−mu r/(2ell))" in _INPUT_TEXT['+repr(note)+']\n'
 s=s.replace('AUDIT_TIMEOUT_SEC = 180\n','AUDIT_TIMEOUT_SEC = 180\n'+pins,1)
 s=s.replace("print('TOTAL: '+str(expected))","print('TOTAL: PASS='+str(expected)+' FAIL=0')")
 # JSON is an output only; writing never targets scripts/.
 s=s.replace("    _finite(out)\n", "    _finite(out)\n    _output = _REPO_ROOT / ('logs/runner-cache/'+Path(__file__).stem+'.json')\n    _output.parent.mkdir(parents=True, exist_ok=True)\n    _output.write_text(json.dumps(out, sort_keys=True, indent=2, allow_nan=False)+'\\n')\n",1)
 if 'haar_contact' in p:s=s.replace('mesh remainder exponent; resource/interface guards not added to mathematical count','mesh remainder exponent only; analytical FDD limit not executed; resource/interface guards excluded from scientific count')
 else:s=s.replace('fixed-scale LR upper and positive resources; no convergence validation','fixed-scale LR upper arithmetic and one resource predicate; analytical clustering and limits not executed')
 ast.parse(s);put(p,s);patch.extend(difflib.unified_diff(old.splitlines(True),s.splitlines(True),fromfile=p+' original',tofile=p+' canonical'))
 # All scientific statements after imports preserved exactly except scope string.
 baseline=old[old.index('from fractions import Fraction as F'):old.index('\n_emit(out,')]
 actual=s[s.index('from fractions import Fraction as F'):s.index('\n_emit(out,')];assert baseline==actual
receipt={'status':'PARTIAL SALVAGE AUTHOR PREPARATION; ORIGINAL REVIEWER COLD CONFIRMATION PENDING','base':subprocess.check_output(['git','-C',str(W),'rev-parse','HEAD'],text=True).strip(),'note':note,'runners':runners,'parents':[{'path':p,'sha256':sha((W/p).read_bytes())} for p in parents],'inputs':inputs,'helper_map_plan':{Path(note).stem.lower():[runners[1]]},'original_count':89,'history_count':81,'branch_preservation_required':True,'accepted_scope':'Quantitative decay/smearing estimates; actual positive Haar contact FDD; conditional gap/LR ratio; complete optional Haar moments and skew proof.','deferred_scope':'Original separated-field negative classification certification under unmet N1; no negative PASS or relabeled positive exclusion.','math_verification':'All indented mathematical lines of retained source sections match independently counted literal original lines; entire scientific runner calculations byte-identical. No generic Markdown regex applied.','resource_plan':review['resource_plan'],'files':[{'path':p,'sha256':sha((W/p).read_bytes())} for p in owned],'claim_mapping':{'original_main_sections1_to5':'quantitative mathematics retained; two exclusion-promotion sentences replaced by explicit deferral','original_main_section6':'full exact negative conclusion retained in original gzip recovery only; certification deferred','primary_contact':'complete proof and constants retained','root_contact':'complete moment/FDD/skew proof before original negative-summary section retained','all_other_originals':'exact89-original archive, no current authority/cache claim'},'remaining':['Original reviewer confirms accepted/deferred scope','Root guarded freshbase advance if needed, two additive helper-map unions, stagedschema2 and cheap check','Two sequential bounded captures and original reviewer finalsource/evidence confirmation; branch remains']}
assert len(owned)==94
(R/'drain8030-author-prepared-v1.json').write_text(json.dumps(receipt,indent=2)+'\n');(R/'drain8030-author-corrections-v1.patch').write_text(''.join(patch));print('94 untracked paths prepared')
