from pathlib import Path
import json,hashlib,subprocess,sys,re,gzip,ast
r=Path('/private/tmp/review-drain-20260915');w=r/'drain-author-slot';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));bind=lambda ps:[dict(path=p,sha256=sha(w/p)) for p in sorted(set(ps))];git=lambda *a:subprocess.check_output(['git','-C',str(w),*a],text=True).strip()
orig=next(x for x in json.load(open(r/'drain8153-original-inventory.json')) if x['number']==8151);m=json.load(open(w/'docs/work_history/review_loop/pr8151/original-manifest.json'));disps=[]
for e in m:
 assert hashlib.sha256(gzip.decompress((w/e['stored']).read_bytes())).hexdigest()==e['sha256']
 disps.append(dict(original_path=e['path'],original_sha256=e['sha256'],final_path=e['stored'],final_sha256=sha(w/e['stored']),disposition='Original complete version preserved byte-exact; spectrum/reflection/counting/finite controls salvaged separately, contour implications explicitly conditional, original unconditional phase and orbit conclusions deferred. Retain original branch.',recovery=e['recovery']))
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as a,runner_cache as c
d=json.load(open(r/'drain8151-author-live.json'));p=d['note'];primary=d['runner'];body=(w/p).read_text();ast.parse((w/primary).read_text());cites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/p));assert not a.transitive_helpers(Path(primary).stem);inputs=list(c.declared_input_paths(w/primary));api=r/'drain8151-author-cache-api-v1.json';api.write_text(json.dumps({'primary':primary,'timeout':c.declared_timeout_for(w/primary),'declared_inputs':inputs,'declared_input_fingerprint':c.declared_input_fingerprint(w/primary),'cache_status':c.cache_status(w/primary),'helpers':[]},indent=2)+'\n')
paths=git('diff','--cached','--name-only').splitlines();review=ref(r/'drain8151-original-review.json');control=ref(r/'check8151/controls.json');report={'status':'AUTHOR DRAFT ONLY; ORIGINAL INDEPENDENT COLD CONFIRMATION REQUIRED','author':'/root/resume_8077','base':git('rev-parse','HEAD'),'tree':git('write-tree'),'original_dispositions':disps,'claim_dispositions':{'T1':'Full spectrum/signed-permutation proof retained.','T2':'Full SOS proof retained with real-valued F and positive symmetric weights explicit; corrected20 ring functions per triple and3 torus functions at312.','T3':'False dissemination replacement removed from live proof; exact two finite probability inequalities retained; parity defect identified with original independent control provenance.','T4':'All-direction event count retained, explicit p>=m counting and p<m trivial cases; no arbitrary bond-set corollary.','T5':'Full contour counting/series retained as conditional implication under unproved uniform planar bad-bond probability hypothesis;216 remains parameter arithmetic only.','T6':'Finite-limit and uniqueness-contradiction proof retained conditional on independently supplied uniform correlation hypothesis; false orbit bound/state-identification removed, full original archived.','T7':'Conditional in-plane implication plus exact finite cube controls; unconditional3D phase conclusion deferred.','negative_gate':'Original N1/N2 insufficient, unconditional phase verdict and negative certification deferred; original branch retained.'},'preservation':'26 additions only relative current main0ee1a0396c; no tracked main source modified. All22 originals decoded hashes verified, full original proofs/history/programs retained.','execution_plan':{'timeout_seconds':180,'process_tree_rss_limit_bytes':3221225472,'concurrency':1,'cost_review':'Original preserved cache claims18.10s at900s cap; not reused as fresh evidence. Source enumerates three six-to-eight-site probability tables (largest6^8), with report retaining two tables; bounded180s and3GiB proposed for single root capture. No scientific arithmetic/domains/tolerances changed.','authorization':'No primary execution by author; root capture only after original reviewer cold confirmation and cheap receipt.'},'checks':'AST/fences/forbidden/classical-name placement and vocab clean, staged whitespace clean; no pipeline/cache/primary run.','references':[review,control,ref(api)]};handoff=r/'drain8151-author-source-handoff-v1.json';handoff.write_text(json.dumps(report,indent=2)+'\n');hr=ref(handoff)
notes=[dict(path=p,claim_id=g.claim_id_from_path(w/p),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type='bounded_theorem',primary_runner=primary,helpers=[],citations=cites,repository_dependencies=['docs/MINIMAL_AXIOMS_2026-06-29.md'],dependency_rationale='Static finite model and specification defined in full; uniqueness note is contrast/context only, supplies no phase bound. Standard mathematical imports stated in source; additional uniform probability hypotheses explicitly unproved.')]
context=cites+inputs+['docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md'];tooling=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
record={'schema_version':2,'unit_id':'PR8151','constituents':[dict(id='PR8151',head=orig['headRefOid'],delta_base=orig['delta_base'],dispositions=dict(hr,json_pointer='/original_dispositions'))],'source':dict(base=git('rev-parse','HEAD'),commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),'inputs':dict(runtime=bind([primary]),helpers=[],parents=bind(['docs/MINIMAL_AXIOMS_2026-06-29.md']),context=bind(context),tooling=bind(tooling)),'reviewer':dict(session='/root/review_8011 original review; affected confirmation pending',report=review,references=[hr,ref(api),control]),'notes':notes,'supporting_proofs':[],'non_science_notes':[dict(path='docs/work_history/review_loop/pr8151/README.md',rationale='Original historical recovery instructions, not scientific authority.',review_reference=review)]}
f=r/'drain8151-author-unit-draft-v1.json';f.write_text(json.dumps(record,indent=2)+'\n');print(ref(f));print(report['tree'])
