from pathlib import Path
import ast,json,hashlib,gzip,subprocess,sys,os,re
R=Path('/private/tmp/review-drain-20260915');W=R/'drain-author-slot';j=json.loads((R/'drain8177-author-prepared-v1.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def dump(name,x):
 p=R/name;assert not p.exists();p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
run=W/j['primaries'][0];note=W/j['canonical_notes'][0];body=note.read_text();tree=ast.parse(run.read_text());const={n.targets[0].id:ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ['FORBIDDEN','FENCES','N5_LINES','INPUT_SHA256','MUTATION_GATE','CLASSICAL_NAMES','ALLOWED_NAME_SECTIONS']}
assert not [x for x in const['FORBIDDEN'] if x in body],[x for x in const['FORBIDDEN'] if x in body];assert all(x in body for x in const['FENCES']);assert all(len(x.split(':',1)[1].strip())>=40 for x in const['N5_LINES'])
assert not re.findall(r'(?<![\w.])\d+\.\d+(?![\w.])|\bfloat\(|\.evalf\(|\bN\(',run.read_text().split('float-scan-marker-line')[0])
sections=re.split(r'^## ',body,flags=re.M);off=[]
for sec in sections[1:]:
 if not any(sec.split('\n',1)[0].strip().startswith(a) for a in const['ALLOWED_NAME_SECTIONS']):off.extend(n for n in const['CLASSICAL_NAMES'] if n in sec)
off.extend(n for n in const['CLASSICAL_NAMES'] if n in sections[0]);assert not off
# Metadata modules only, no scientific primary/helper function imported or run.
os.chdir(W);sys.path[:0]=[str(W/'scripts'),str(W/'docs/audit/scripts')];import runner_cache as c;import audit_packet_script_deps as a;import build_citation_graph as g
inputs=list(c.declared_input_paths(run));assert len(inputs)==4;assert all(sha(W/p)==const['INPUT_SHA256'][p] for p in inputs)
m=json.loads((W/j['original_manifest']['path']).read_text());assert len(m['entries'])==50
for e in m['entries']:
 raw=gzip.decompress((W/e['recovery']['path']).read_bytes());assert hashlib.sha256(raw).hexdigest()==e['original_sha256'];assert hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==e['original_blob'];assert sha(W/e['recovery']['path'])==e['recovery']['sha256']
assert hashlib.sha256(gzip.decompress((W/m['original_delta']['path']).read_bytes())).hexdigest()==m['original_delta']['decoded_sha256']
api=dict(schema_version=1,kind='read-only-source-discovery-not-execution',base=j['base'],primary=j['primaries'][0],primary_sha256=sha(run),runtime_inputs=[dict(path=p,sha256=sha(W/p),role='proof source' if p==j['canonical_notes'][0] else 'framework authority' if 'MINIMAL_AXIOMS' in p else 'explicit product-model/comparison parent; finite proof self-contained') for p in inputs],input_fingerprint=c.declared_input_fingerprint(run),declared_timeout=c.declared_timeout_for(run),packet_transitive_helpers=sorted(a.transitive_helpers(run.stem)),graph_helpers=g.helper_runner_paths_for_claim(g.claim_id_from_path(note),j['primaries'][0]),citations=[str(p.relative_to(W)) for p in g.extract_citations(body,note)],graph_primary=g.extract_runner(body,j['canonical_notes'][0]),framework_dependencies=inputs[1:],mathematical_premise_notes=inputs[2:],mathematical_imports=['finite graph trees and level induction','weight-preserving word lift injection; relaxed occupancy and collisions','nonnegative polynomial height iteration and exact rational certificates'],deferred_role='Complete corrected negative argument plus original full note, not live supporting proof or premise; global construction/physical implications remain unsupported',registry_changes_required=False,primary_imported=False,primary_executed=False,static_compile=True,original_archives_verified=50,original_delta_verified=True)
assert api['packet_transitive_helpers']==[] and api['graph_helpers']==[] and api['graph_primary']==j['primaries'][0]
dump('drain8177-source-input-discovery-v1.json',api)
authorities=['docs/MINIMAL_AXIOMS_2026-06-29.md','docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/audit/data/axiom_premise_nodes.json','docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md']
oldbind=json.loads((R/'drain8173-adapter-authority-v1.json').read_text())['authority'];oldhash={x['path']:x['sha256'] for x in oldbind};assert all(sha(W/p)==oldhash[p] for p in authorities)
resource=dict(schema_version=1,kind='proposed-resource-plan-not-execution',primary=j['primaries'][0],timeout_seconds=120,memory_limit_bytes=384*1024*1024,limits_status='Unmeasured corrected-source proposal; original timeout900s; external process-tree sampled RSS/wall limits, preserve failures without implicit retry',historical_cache=dict(path='drain8177-original/head/logs/runner-cache/admissibility_rule_six_axis_formation_threshold_rooted_inequality_reduces_the_unit_budget_to_the_tight_sibling_lemma_and_the_one_processed_child_count_2026_09_17.txt',elapsed_seconds=1.39,scope='Historical source cache only; original reviewer did not run full baseline'),independent_original_finite_control=json.loads((R/'check8177/finite-receipt.json').read_text()),cost=dict(brute_force='B:140 accepted seeded33 realizations in3x3x5 window with4..10live sites; <=2^9node subsets per queried site, arrow choices at most3 per nonseed; <=45fork candidate pairs. E:60 accepted seeded34 realizations with5..10live sites, two costs and both restrictions. Original rejection loops have no deterministic proposal cap: external watchdog required.',large_fixtures='ZA112sites/ZB200sites; level-capped single-seed subset dynamic programs at fixed root/predecessors; sequential small state maps, no dense numerical lattice/eigensolver.',arithmetic='Eight fixed Fraction polynomial certificates plus one full-slot comparison and n2,n3 symbolic slot identity; exact coefficients unchanged.',imports='SymPy and stdlib; no local helper. No top-level solver/search or historical missing module promoted.',memory='Independent finite control sampled57568KiB RSS, not a full corrected-primary measurement.384MiB is a proposed external ceiling with headroom; no claim of measured success.'),expected_completed_checks=18,count_scope='A4+B3+C2+D3+E1+F4+G1; packaging and reporting included',stdout_only=True,json_outputs=[],other_output_writes=[],cache_destination=f'logs/runner-cache/{run.stem}.txt',mutations=const['MUTATION_GATE'],new_targeted_mutation=dict(name='predecessor_profile_wrong',target='C1',mechanism='Require incorrect ZB[-1,-1,-1] rather than true[-1,-1,0]',expected_exit_code=1,expected_total='PASS=17 FAIL=1',status='proposed only; no execution'),unchanged_mutation_reruns_requested=False,primary_runs=0,simulation_runs=0,mutation_runs=0)
dump('drain8177-resource-plan-v1.json',resource)
assert not subprocess.check_output(['git','diff','--name-only'],text=True);assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True)
paths=subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines();assert set(paths)=={x['path'] for x in j['source']}
for x in j['source']:assert sha(W/x['path'])==x['sha256']
existing={Path(p).name for p in subprocess.check_output(['git','ls-files','docs'],text=True).splitlines()};new=[p for p in paths if p.startswith('docs/') and Path(p).name not in ['README.md','SKILL.md']];assert not [p for p in new if Path(p).name in existing];assert len({Path(p).name for p in new})==len(new)
refs=['drain8177-author-prepared-v1.json','drain8177-source-freeze-v1.json','drain8177-author-dispositions-v1.json','drain8177-author-corrections-v1.patch','drain8177-source-input-discovery-v1.json','drain8177-resource-plan-v1.json','drain8177-review-original.json','drain8177-review-original.md']
dump('drain8177-author-handoff-v1.json',dict(schema_version=1,kind='author-preparation-handoff-not-source-pass',pr=8177,base=j['base'],head=j['head'],owner='PR8177-author',source_count=56,original_count=50,source_freeze=dict(path=str(R/'drain8177-source-freeze-v1.json'),sha256=sha(R/'drain8177-source-freeze-v1.json')),references=[dict(path=str(R/p),sha256=sha(R/p)) for p in refs],authority=[dict(path=p,sha256=sha(W/p),read_reuse='Prior same-author complete authority read, verified bytes unchanged from PR8173 authority binding') for p in authorities],branch_preservation_required=True,tracked_and_index_clean=True,document_basename_collision_check=dict(all_new_docs_checked=True,exceptions=['README.md','SKILL.md'],collisions=[]),primary_runs=0,simulation_runs=0,mutation_runs=0,staged=False,registry_changes=False,pending='Root-dispatched original same-session affected review; no source or landing PASS asserted.'))
print(json.dumps({p:sha(R/p) for p in refs+['drain8177-author-handoff-v1.json']},indent=2))
