import ast,copy,difflib,gzip,hashlib,json,shutil,subprocess
from pathlib import Path
R=Path('/private/tmp/review-drain-20260915');W=R/'review-meta-slot';P=R/'drain8167-originals/.claude/science/physics-loops/toe-compact-winding-20260916'
sha=lambda b:hashlib.sha256(b).hexdigest()
pin=lambda p:dict(path=p,sha256=sha((W/p).read_bytes()))
assert json.loads((R/'review-meta-slot.json').read_text())['owner']=='PR8167-author'
assert subprocess.check_output(['git','-C',str(W),'rev-parse','HEAD'],text=True).strip()=='ea403fe1c5e71418c95b976e72a11df375c0a655'
assert not subprocess.check_output(['git','-C',str(W),'diff','--name-only']).strip()
assert not subprocess.check_output(['git','-C',str(W),'diff','--cached','--name-only']).strip()
review=json.loads((R/'drain8167-original-review.json').read_text());assert sha((R/'drain8167-original-review.json').read_bytes())=='ad566688ec255c2a878cbddc3c73a17e451bbd6a5dc677fd4d41391156dd093b'
orig=['EXACT_COMPACT_COVER_AND_SOURCE_IDENTITIES.md','COMPACT_SINE_SCORE_DOMINATION_AND_STATIC_CURL_LIMIT.md'];notes=['COMPACT_ROTOR_COVER_SOURCE_IDENTITIES_BOUNDED_THEOREM_NOTE_2026-09-16.md','COMPACT_ROTOR_SINE_SCORE_STATIC_CURL_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-16.md'];oldrun=['compact_cover_source_check','compact_score_check'];runs=['compact_rotor_cover_source_check_2026_09_16','compact_rotor_sine_score_check_2026_09_16']
changes=[[
('This is the same definition used in PR8166 at frozen head\n02bfa4eb99fce8329619a476775299567f735d4b. Its unreviewed derivative estimates\nare not imported here. In particular0<=F_T<=2PT.','The bridge definition is complete here and imports no sibling derivative\nestimate. In particular0<=F_T<=2PT.'),
('Dropping the integer term changes the observable. Small density or bounded\ncomponents of m_n do not alone control its diffuse-source contribution;\nthe separate sparse-loop counterexample tests exactly that kind of gap.','Dropping the integer term changes the observable. Equation (5) retains\nthat term in the exact definition.'),
('The sparse\nfilling geometry in PR8166 supplies possible supports. It does not\nsupply the normalized activities or their source derivatives.','The normalized activities and their source derivatives remain targets\nfor a further constructive comparison.'),
("The local Hamiltonian path specification is additional information that\nthe sparse-loop counterexample lacks. A proof exploiting it could still\nexclude the counterexample's long-range sign structure. No axiom update\nis inferred from the present missing estimate.",'The local Hamiltonian path specification is part of the supplied compact\nlaw. Further comparison work can use that structure. No axiom update is\ninferred from the present open target.')],
[('## 6. Scope relative to the campaign target','## 6. Scope of the source and state theorem'),
("This result uses the extra Gibbs weight and shift identity absent from the\nsparse-loop construction. It prevents that construction's exploding MGFs\nfor the actual sine score and controls a particular diffuse source sector.\nIt does not prove the desired full compact-to-real magnetic comparison:",'This result uses the supplied Gibbs weight and exact shift identity to\ncontrol a particular diffuse sine-source sector. Its scope for a further\ncompact-to-real magnetic comparison is as follows:')]]
scopes=['Exact finite-graph compact cover and normalized source identities for the supplied rotor Hamiltonian, with full thermal trace and all windings.','Actual compact sine-source MGF bound and conditional static exact-curl Gaussian limit at fixed g and finite beta, with explicit deterministic contact concentration or supplied spatial ergodicity.']
diffs=[];pres=[]
for j,name in enumerate(notes):
 old=(P/'notes'/orig[j]).read_text();body=old[old.index('## 1.'):];trans=[]
 for a,b in changes[j]:
  assert body.count(a)==1,a;body=body.replace(a,b);trans.append(dict(original=a,canonical=b,reason='Narrow live scope or remove non-load-bearing sibling/counterexample implication; complete original remains exact recovery.'))
 end='For the scope of negative statements, see the [N1-N8 review](../NO_GO_DISCIPLINE_CHECKLIST.md).';assert body.count(end)==1;body=body.replace(end,'The separate sparse-loop construction and its negative implication are\npreserved as deferred historical science in the recovery packet. They are\nnot a live claim of this note.');trans.append(dict(original=end,canonical='Explicit deferred historical boundary',reason='No import of uncertified universal negative conclusion.'))
 header='---\nclaim_id: '+name[:-3].lower()+'\nclaim_type: bounded_theorem\nrunner: scripts/'+runs[j]+'.py\nclaim_scope: '+json.dumps(scopes[j])+'\nupstream_dependencies: []\n---\n\n'
 status='**Type:** bounded_theorem\n\n```yaml\nactual_current_surface_status: conditional-support\nconditional_surface_status: conditional-support\ntrace_class: upstream_support\nreachability_to_target: supports\naudit_required_before_effective_retained: true\nbare_retained_allowed: false\nhypothetical_axiom_status: null\nadmitted_observation_status: null\n```\n\n'
 intro=scopes[j]+' The complete proof is self-contained below. No result from PR8165 or PR8166 is a mathematical premise. The Hamiltonian, coupling, thermal state and source class are supplied, not selected from framework axioms. No audit verdict is asserted.\n\n'
 tail='\n\n## Evidence and historical boundary\n\nPrimary runner: `scripts/'+runs[j]+'.py`. The runner retains all original arithmetic, fixtures, assertions and tolerances. Its 120-second timeout is unchanged; a 768 MiB external process-tree cap is proposed from the finite dense matrices and library overhead, not measured RSS. JSON is written under `logs/runner-cache/`. `TOTAL: PASS=2 FAIL=0` counts the two completed diagnostic families, not dynamic assertions or exhaustive theorem coverage. Static assertion count is separately labelled.\n\n'
 tail+='The [exact historical recovery](work_history/repo/review_feedback/pr8167-evidence/README.md) preserves all 116 original paths, modes, blobs and hashes, including the complete sparse construction and calculation, every current/historical mutation, failed side4 adjacency claim and passing-but-insufficient check, and failed Fourier2/3 refinement. The universal sparse-geometry negative implication is deferred with its full proof and branch recovery handle. It is neither a live bounded conclusion nor mathematically refuted by the procedural N1 limitation.\n\n'
 tail+='## No-Go Discipline Gate\n\n**N1 — Actual scope.** This note states the positive identities or conditional source theorem above. The separate sparse-law universal negative conclusion is absent from the live claim; formal negative certification is deferred, with no invented five-route coverage.\n\n**N2 — Premises.** The supplied rotor model, full thermal trace and stated source/state conditions are the exact premises. Open extensions are not counted as independent impossibility walls.\n\n**N3 — Imports.** Normalized Haar measure, all windings, Feynman-Kac, electric Dyson expansion and standard differentiation/ergodic tools are explicit. No empirical fit or native model-selection claim is made.\n\n**N4 — Controls.** Free-circle derivatives and gapped finite rotors calibrate the displayed identities at their actual finite domains. The complete sparse-law proof and eighteen current/historical mutation sources and errors remain historical, not present execution evidence.\n\n**N5 — Resolution.** Finite Fourier/image and matrix challenges exercise the specified formulas. No numerical thermodynamic, beta-infinity, principal-flux or photon proof is claimed. Executed certificates state exactly the two diagnostic families completed.\n\n**N6 — Positive content.** Exact compact normalization, contact/mixture identities and the bounded sine-source/static-curl results preserve their complete arguments. A stronger physical-source comparison remains open.\n\n**N7 — State boundary.** Fixed finite temperature and supplied contact concentration or ergodicity are not physical thermal Gauss projection, vacuum selection or a photon pole. No model-wide obstruction is claimed.\n\n**N8 — Reopening.** Further source/state/temperature control can extend these results. The deferred sparse construction remains available in full for an honestly completed future certification.\n'
 text=header+old.splitlines()[0]+'\n\n'+status+intro+body.rstrip()+tail
 assert [x for x in old.splitlines() if x.startswith('    ')]==[x for x in text.splitlines() if x.startswith('    ')]
 target=W/'docs'/name;assert not target.exists();target.write_text(text)
 pres.append(dict(original='notes/'+orig[j],canonical='docs/'+name,all_indented_formula_lines_exact=True,full_positive_argument_preserved=True,exact_prose_transformations=trans))
 diffs.extend(difflib.unified_diff(old.splitlines(True),text.splitlines(True),fromfile='original/notes/'+orig[j],tofile='docs/'+name))
cert=[['image/Fourier kernels and three source derivatives; one/two-plaquette Ward identities','finite one/two-plaquette systems; no thermodynamic simulation','images8/10, Fourier120/160 at120 digits; rotor cutoffs up to24 and two-coordinate cutoff12','all original coupling, time, endpoint and source fixtures completed','checked and not executed — all-volume or photon limits are not part of these finite calculations'],['actual sine-source matrices, amplitude/phase factors and static-curl Ward/Taylor controls','2x2 plaquette complex in a zero-harmonic Fourier electric sector; not full physical thermal Gauss trace','Fourier cutoffs3/4, dimensions343/729; original nonexact source control retained','two thermal parameter pairs, three source strengths and independent-rotor copy counts1/16/256/4096','checked and not executed — infinite-volume conditional Gaussian result uses its full analytic contact-concentration proof']]
plans=[]
for j,stem in enumerate(runs):
 old=(P/'evidence'/(oldrun[j]+'.py')).read_text();inputs=['docs/'+notes[j]];hashes={p:sha((W/p).read_bytes()) for p in inputs}
 src=old.replace('AUDIT_TIMEOUT_SEC=120','AUDIT_TIMEOUT_SEC=120\nAUDIT_MEMORY_MB=768\nAUDIT_INPUT_PATHS='+repr(inputs)+'\nEXPECTED_INPUT_SHA256='+repr(hashes),1)
 assert src.count('    print(json.dumps(out,indent=2,sort_keys=True))')==1;src=src.replace('    print(json.dumps(out,indent=2,sort_keys=True))','    _emit(out)',1)
 count=sum(isinstance(n,ast.Assert) for n in ast.walk(ast.parse(old)))
 extra='\n\ndef _check_inputs():\n    root = Path(__file__).resolve().parents[1]\n    for name in AUDIT_INPUT_PATHS:\n        if hashlib.sha256((root / name).read_bytes()).hexdigest() != EXPECTED_INPUT_SHA256[name]:\n            raise RuntimeError("input identity mismatch: " + name)\n\ndef _emit(report):\n    report["input_sha256"] = dict(EXPECTED_INPUT_SHA256)\n    report["completed_diagnostic_families"] = 2\n    report["total_unit"] = "completed diagnostic families, not dynamic assertions"\n    report["static_source_assert_statements"] = '+str(count)+'\n    output = Path(__file__).resolve().parents[1] / "logs" / "runner-cache" / (Path(__file__).stem + ".json")\n    output.parent.mkdir(parents=True, exist_ok=True)\n    output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\\n")\n    print(json.dumps(report, indent=2, sort_keys=True))\n    print("TOTAL: PASS=2 FAIL=0")\n'
 for label,detail in zip(['per_element','per_site','per_mode','per_block','lattice_wide'],cert[j]):extra+='    print('+repr(label+': '+detail+'.')+')\n'
 src=src[:src.index("if __name__")]+extra+"\nif __name__ == '__main__':\n    _check_inputs()\n    main()\n"
 a=ast.parse(old);b=ast.parse(src);bf={n.name:n for n in b.body if isinstance(n,ast.FunctionDef)}
 for n in [n for n in a.body if isinstance(n,ast.FunctionDef)]:
  expected=copy.deepcopy(n)
  if n.name=='main':expected.body[-1].value=ast.Call(func=ast.Name(id='_emit',ctx=ast.Load()),args=[ast.Name(id='out',ctx=ast.Load())],keywords=[])
  assert ast.dump(expected,include_attributes=False)==ast.dump(bf[n.name],include_attributes=False)
 out=W/'scripts'/(stem+'.py');assert not out.exists();out.write_text(src);out.chmod(0o755);compile(src,str(out),'exec')
 pres.append(dict(original='evidence/'+oldrun[j]+'.py',canonical='scripts/'+stem+'.py',all_original_computational_ASTs_exact=True,only_exception='Final report emitter wrapper; identical existing report and all calculations',static_assert_count=count))
 diffs.extend(difflib.unified_diff(old.splitlines(True),src.splitlines(True),fromfile='original/evidence/'+oldrun[j]+'.py',tofile='scripts/'+stem+'.py'))
 plans.append(dict(runner='scripts/'+stem+'.py',source_sha256=sha(src.encode()),ordered_inputs=[pin(p) for p in inputs],timeout_sec=120,proposed_external_process_tree_limit_bytes=768*1024**2,resource_basis='Maximum dense625-dimensional two-plaquette eigenproblem with several real/complex work arrays;120-digit scalar circle sums.' if j==0 else 'Maximum dense729-dimensional Fourier sector; four cosine/sine matrices and thermal eigenvector/complex source work arrays. Dozens of matrix-sized temporaries plus BLAS/Python overhead; no volume sweep.',cap_status='source-derived proposal, not measured peak RSS',capture_status='not run',json_output='logs/runner-cache/'+stem+'.json',completed_family_total=2,N5=cert[j]))
archive=W/'docs/work_history/repo/review_feedback/pr8167-evidence';m=json.loads((archive/'archive-manifest.json').read_text());assert len(m['entries'])==116
(archive/'README.md').write_text('# Exact compact winding source recovery and deferred science\n\nAll 116 original paths at `5265ddd85815fe92e55342f4352f5e675b84703c` retain separate path/mode/Git-blob/raw-SHA identities in `archive-manifest.json`. Complete original notes and all three calculations remain readable under `kept/`. The full sparse-current construction and its universal negative implication are deferred scientific source, not a live bounded row and not discarded or mathematically refuted. Preserve the original branch `physics-loop/toe-compact-winding-20260916` while this conclusion remains unlanded.\n\nThe archive includes every nine current and nine historical mutant source/error pair, side4 adjacency defect and passing-but-insufficient old test, side6 correction, failed Fourier2/3 refinement and original0.003 tolerance retained at3/4, plus diagnostic IO failure and its correction. Historical outputs and author status are provenance only. No new execution or audit verdict is supplied by this archive.\n\nLive positive sources:\n\n'+'\n'.join('- `docs/'+n+'`' for n in notes)+'\n')
original={e['path']:e for e in review['original_dispositions']};mapping=[]
canon={str(P/'notes'/o):'docs/'+n for o,n in zip(orig,notes)};canon.update({str(P/'evidence'/(o+'.py')):'scripts/'+n+'.py' for o,n in zip(oldrun,runs)})
for e in m['entries']:
 o=original[e['original_path']];stored=archive/e['stored_path'];raw=gzip.decompress(stored.read_bytes()) if e['encoding']=='gzip' else stored.read_bytes()
 assert sha(raw)==e['raw_sha256']==o['sha256'] and e['original_mode']==o['mode'] and e['git_blob']==o['blob'];assert raw==Path(o['recovery']).read_bytes()
 target=canon.get(o['recovery']);sparse='SPARSE_LOOPS_WITH_NONGAUSSIAN' in e['original_path'] or 'sparse_loop_counterexample_check.py' in e['original_path']
 disposition='Complete positive source canonicalized; exact original and removed negative/context implications recovered separately' if target else ('Deferred complete sparse construction/calculation, including universal negative implication; exact historical scientific recovery, preserve branch' if sparse else 'Exact historical/provenance and failure recovery; no current status or execution imported')
 mapping.append(dict(original_path=e['original_path'],original_mode=e['original_mode'],original_blob=e['git_blob'],original_sha256=e['raw_sha256'],disposition=disposition,recovery=str(stored.relative_to(W)),recovery_encoding=e['encoding'],final_path=target,final_sha256=sha((W/target).read_bytes()) if target else None))
for n,obj in [('preservation',pres),('full-mapping',mapping),('input-resource-plan',plans)]:
 p=R/('drain8167-author-'+n+'-v1.json');assert not p.exists();p.write_text(json.dumps(obj,indent=2)+'\n')
(R/'drain8167-author-correction-v1.diff').write_text(''.join(diffs))
prepared=dict(status='UNTRACKED_AUTHOR_PREPARED_V1_ORIGINAL_REVIEWER_AFFECTED_CONFIRMATION_PENDING',owner='PR8167-author',base='ea403fe1c5e71418c95b976e72a11df375c0a655',worktree=str(W),notes=[pin('docs/'+n) for n in notes],runners=[pin('scripts/'+n+'.py') for n in runs],original_review_sha256=sha((R/'drain8167-original-review.json').read_bytes()),archive_manifest=pin(str((archive/'archive-manifest.json').relative_to(W))),originals=116,claim_dispositions=[dict(claim=x,disposition='Live complete positive theorem; exact finite example/calibration remains scoped') for x in review['claims_and_boundaries'][:4]]+[dict(claim=review['claims_and_boundaries'][4],disposition='Deferred complete scientific construction and negative implication, exact readable archive; original branch must remain')],primaries_executed=0,staged=False)
(R/'drain8167-author-prepared-v1.json').write_text(json.dumps(prepared,indent=2)+'\n')
print(json.dumps(dict(notes=2,runners=2,originals=116,primary_executions=0)))
