from pathlib import Path
import hashlib,json,subprocess,sys,re,gzip
r=Path(__file__).resolve().parent;w=r/'author-draft-slot'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));bind=lambda ps:[dict(path=p,sha256=sha(w/p)) for p in sorted(set(ps))]
git=lambda *a:subprocess.check_output(['git','-C',str(w),*a],text=True).strip()
review=r/'drain8152-original-review.json';original=next(x for x in json.loads((r/'drain8153-original-inventory.json').read_text()) if x['number']==8152)
mapping=json.loads((w/'docs/work_history/review_loop/pr8152/original-manifest.json').read_text());disps=[]
for e in mapping:
 p=e['stored'];assert hashlib.sha256(gzip.decompress((w/p).read_bytes())).hexdigest()==e['sha256']
 disps.append(dict(original_path=e['path'],original_sha256=e['sha256'],final_path=p,final_sha256=sha(w/p),disposition='Exact original recovered; canonical positive constructions and finite witnesses separately narrowed. Exhaustive/minimal negative certification deferred; incorrect general seed-generation and Born-support assertions withdrawn. Preserve original branch.',recovery=e['head']+':'+e['path']))
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as a,runner_cache as c
paths=git('diff','--cached','--name-only').splitlines();p=next(p for p in paths if p.startswith('docs/ADMISSIBILITY_RULE_COVARIANT_FRAME'));body=(w/p).read_text();primary=re.search(r'^runner: (.+)$',body,re.M)[1]
cites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/p));deps=[x for x in cites if x.startswith('docs/POSSIBILITY_') or x=='docs/MINIMAL_AXIOMS_2026-06-29.md'];inputs=c.declared_input_paths(w/primary);assert len(inputs)==3 and not a.transitive_helpers(Path(primary).stem)
api=r/'drain8152-author-cache-api-v1.json';assert not api.exists();api.write_text(json.dumps({'primary':primary,'primary_sha256':sha(w/primary),'timeout':c.declared_timeout_for(w/primary),'declared_inputs':list(inputs),'declared_input_fingerprint':c.declared_input_fingerprint(w/primary),'cache_status':c.cache_status(w/primary),'helpers':[]},indent=2)+'\n')
tools=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
context=cites+list(inputs)+['docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md','docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md']
handoff={'status':'AUTHOR DRAFT; ORIGINAL COLD CONFIRMATION REQUIRED','author':'/root','base':git('rev-parse','HEAD'),'tree':git('write-tree'),'original_dispositions':disps,'original_review':ref(review),'changes':'Positive covariant atomic-kernel construction with normalized frame and Borel/ordered-slot data; explicit orbit examples; supplied antipodal induction; aligned and tilted overlap values. Classification/minimality deferred, all original proofs preserved. Runner math expanded only with direct displayed-frame binding and exact tilted overlap witness; authority/text/scope labels corrected.','execution_plan':{'timeout_seconds':60,'process_tree_rss_limit_bytes':512*1048576,'basis':'Current bounded capture proposal for tiny exact workload; original900s declaration remains in archive. No primary executed. Original independent cold confirmation required.'}}
h=r/'drain8152-author-source-handoff-v1.json';assert not h.exists();h.write_text(json.dumps(handoff,indent=2)+'\n');rr=ref(h)
record={'schema_version':2,'unit_id':'PR8152','constituents':[dict(id='PR8152',head=original['headRefOid'],delta_base=original['delta_base'],dispositions=dict(rr,json_pointer='/original_dispositions'))],'source':dict(base=git('rev-parse','HEAD'),commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),'inputs':dict(runtime=bind([primary]),helpers=[],parents=bind(deps),context=bind(context),tooling=bind(tools)),'reviewer':dict(session='/root/review_8012 original session; affected-source confirmation pending',report=ref(review),references=[rr,ref(api),ref(r/'drain8152-independent-control.json')]),'notes':[dict(path=p,claim_id=g.claim_id_from_path(w/p),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type='bounded_theorem',primary_runner=primary,helpers=[],citations=cites,repository_dependencies=deps,dependency_rationale='Current axiom boundary and conditional Bloch/covariance representations only. Finite atomic kernels, weights, slots, seed and overlap function explicitly supplied; no physical selector or exhaustive negative classification imported.')],'supporting_proofs':[],'non_science_notes':[dict(path=q,rationale='Historical recovery instructions, not active proof or scientific authority.',review_reference=ref(review)) for q in paths if q.endswith('.md') and q!=p]}
out=r/'drain8152-author-unit-draft-v1.json';assert not out.exists();out.write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(ref(out)));print('TREE',record['source']['tree'])
