from pathlib import Path
import json,hashlib,subprocess,sys,re,gzip,ast
r=Path('/private/tmp/review-drain-20260915');w=r/'drain-author-slot';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));bind=lambda ps:[dict(path=p,sha256=sha(w/p)) for p in sorted(set(ps))];git=lambda *a:subprocess.check_output(['git','-C',str(w),*a],text=True).strip()
orig=json.load(open(r/'drain8154-original-inventory.json'));o=json.load(open(r/'drain8156-original-inventory.json'));orig+=o if isinstance(o,list) else [o];manifest=json.load(open(w/'docs/work_history/review_loop/pr8154/original-manifest.json'));disps={str(n):[] for n in (8154,8155,8156,8157)}
for e in manifest:
 assert hashlib.sha256(gzip.decompress((w/e['stored']).read_bytes())).hexdigest()==e['sha256']
 disps[str(e['pr'])].append(dict(original_path=e['path'],original_sha256=e['sha256'],final_path=e['stored'],final_sha256=sha(w/e['stored']),disposition='Complete original version preserved byte-exact in deterministic gzip; scientific scope repaired in live positive-bound note and runner; deferred original negative arguments retained with branch.',recovery=e['recovery']))
assert all(len(x)==22 for x in disps.values())
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as a,runner_cache as c
live=json.load(open(r/'drain8154-author-live.json'));apirows=[];notes=[];parents=[];context=[];primaries=[]
for n,d in sorted(live.items()):
 p=d['note'];primary=d['runner'];body=(w/p).read_text();ast.parse((w/primary).read_text());cites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/p));helpers=a.transitive_helpers(Path(primary).stem);assert not helpers;inputs=list(c.declared_input_paths(w/primary));assert all((w/x).is_file() for x in inputs)
 apirows.append(dict(pr=n,primary=primary,timeout=c.declared_timeout_for(w/primary),declared_inputs=inputs,declared_input_fingerprint=c.declared_input_fingerprint(w/primary),cache_status=c.cache_status(w/primary),helpers=[]));deps=sorted(set(inputs[1:]) & set(cites));assert set(inputs[1:])<=set(cites)
 notes.append(dict(path=p,claim_id=g.claim_id_from_path(w/p),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type='bounded_theorem',primary_runner=primary,helpers=[],citations=cites,repository_dependencies=deps,dependency_rationale='Supplied sphere static law and mathematical imports stated explicitly; linked actual parents supply conditional representation or corrected quantitative implication, not physical selection. Full retained proof is in this note.'))
 parents+=inputs[1:];context+=cites+inputs;primaries.append(primary)
api=r/'drain8154-author-cache-api-v1.json';api.write_text(json.dumps(apirows,indent=2)+'\n');reviews=[ref(r/'drain8154-original-review.json'),ref(r/'drain8156-original-review.json')];controls=[ref(r/'check8154/controls.json'),ref(r/'check8156/controls.json')];paths=git('diff','--cached','--name-only').splitlines();assert len(paths)==98
report=dict(status='AUTHOR DRAFT; ORIGINAL INDEPENDENT COLD CONFIRMATION REQUIRED',author='/root/resume_8077',base=git('rev-parse','HEAD'),tree=git('write-tree'),original_dispositions=disps,claim_dispositions={n:d['scope'] for n,d in live.items()},canonical_mapping=json.load(open(r/'drain8154-author-pathmapping.json')),preservation='Only98 additions; all tracked main files untouched. All88 original path occurrences decoded and hash verified, grouped22 perPR. Original branches retained; no original cache restamped.',execution_plan=dict(timeouts={n:300 if n in ('8155','8156') else 180 for n in live},process_tree_rss_limit_bytes=1073741824,concurrency=1,cost_review='Historical cache elapsed8154 0.60s,8155 2.89s,8157 1.31s,8156 24.11s, not fresh evidence. Domains unchanged: symbolic finite integrals/shells;8155 dense343x343 Fraction matrix and16 matvecs;8156 repeated exact N1000 sums. Limits180/300s and1GiB are proposed bounded capture envelopes. No author science execution.',authorization='Root capture only after original cold confirmation and cheap receipt.'),references=reviews+controls+[ref(api)],negative_certificate='Withheld; no new five-route claim or physical classification; original complete arguments archived.')
handoff=r/'drain8154-author-source-handoff-v1.json';handoff.write_text(json.dumps(report,indent=2)+'\n');hr=ref(handoff);context+=['docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md'];tooling=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
record=dict(schema_version=2,unit_id='PR8154-8155-8156-8157',constituents=[dict(id='PR'+str(u['number']),head=u['headRefOid'],delta_base=u['delta_base'],dispositions=dict(hr,json_pointer='/original_dispositions/'+str(u['number']))) for u in sorted(orig,key=lambda x:x['number'])],source=dict(base=git('rev-parse','HEAD'),commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),inputs=dict(runtime=bind(primaries),helpers=[],parents=bind(parents),context=bind(context),tooling=bind(tooling)),reviewer=dict(session='/root/review_8011 original review; affected confirmation pending',report=reviews[0],references=[hr,ref(api)]+reviews[1:]+controls),notes=notes,supporting_proofs=[],non_science_notes=[dict(path='docs/work_history/review_loop/pr8154/README.md',rationale='Byte-exact original recovery documentation only, not live scientific authority.',review_reference=reviews[0])]);f=r/'drain8154-author-unit-draft-v1.json';f.write_text(json.dumps(record,indent=2)+'\n');print(ref(f));print(report['tree'])
