import pathlib,json,re,hashlib,subprocess,collections
root=pathlib.Path('/private/tmp/review-drain-20260915');repo=root/'integration-resume';main='0ea56ccd19205c66ccfb664fb391ed4de39fa415';base='6ad6a2184b7c2067e597528e0964753874493b4a';head='ccca36e505a4cc5d0cd4735b377c15d69042fc41'
def digest(b):return hashlib.sha256(b).hexdigest()
def git(*args):return subprocess.check_output(['git',*args],cwd=repo)
def save(name,d):
 p=root/name
 assert not p.exists(),p
 p.write_text(json.dumps(d,indent=2)+'\n' if not isinstance(d,str) else d);p.chmod(0o444)
inv=json.load(open(root/'drain8159-original-inventory.json'))['original_paths']
paths=[dict(p) for p in inv if re.search(r'/(?:BLOCK[1-6](?:_|\.)|block[1-6](?:_|/))',p['path'])]
for p in paths:
 data=pathlib.Path(p['recovery_path']).read_bytes();assert digest(data)==p['sha256'];assert git('rev-parse',head+':'+p['path']).decode().strip()==p['blob']
 p['read_scope']='complete note/runner/evidence/review; historical source reconstructed through full diff against the fully read final source; exact-identical JSON prefixes read once'
 if '/notes/' in p['path']:p['disposition']='preserve_original_unchanged; conditional positive mathematics or narrowly scoped failed-route record; no full-field or full-axiom closure'
 elif '/review/' in p['path']:p['disposition']='preserve_history_unchanged; prior failures and personal review are not independent authority'
 else:p['disposition']='preserve_original_unchanged; finite author evidence only, no primary recapture performed'
parents=[]
scopes={
'docs/FINITE_CLOCK_GAUSSIAN_SMOOTHING_POSITIVE_LOCAL_ELECTRIC_EXTENSION_AND_FLUX_SCALING_EQUIVALENCE_BOUNDED_THEOREM_NOTE_2026-09-15.md':'complete source, including real C3 extension, carrier and centered MGF',
'docs/NATIVE_RECORD_SUPPORT_PRESERVING_PRIORITY_FORMATION_BOUNDED_THEOREM_NOTE_2026-09-07.md':'complete source, including exterior repair and supplied iid-priority boundary',
'docs/FORMATION_ORDER_COVARIANCE_AND_ISOTROPIC_BINARY_ORDER_BLIND_CLASSIFICATION_BOUNDED_THEOREM_NOTE_2026-09-13.md':'complete source; initial truncated opening recovered separately',
'docs/FINITE_CLOCK_SCORE_GAUSSIAN_MAXWELL_SCALING_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-14.md':'lines110-220 exact lattice law, Poisson covariance, centered MGF and all-source distinction only',
'docs/FIXED_CLOCK_TRANSVERSE_SPECTRAL_CONCENTRATION_AND_LINEAR_ENERGY_BAND_BOUNDED_THEOREM_NOTE_2026-09-15.md':'lines80-245 source, centered MGF, contact covariance and spectral scope only; no full-source acceptance',
'docs/FIXED_COUPLING_HAAR_VILLAIN_FULL_SCORE_GAUSSIAN_MAXWELL_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-15.md':'lines1-240 actual free-box flux unfolding and real auxiliary tilt identity; no full Haar infrared-proof acceptance'}
for p,scope in scopes.items():
 b=git('show',main+':'+p)
 try:old=git('show',base+':'+p);unchanged=b==old
 except subprocess.CalledProcessError:unchanged=None
 parents.append({'path':p,'revision':main,'blob':git('rev-parse',main+':'+p).decode().strip(),'sha256':digest(b),'read_scope':scope,'same_as_delta_base':unchanged})
p='.claude/science/physics-loops/toe-phase-selection-20260914/BLOCK27_ALL_COMPONENT_MIXED_COEFFICIENT.md';rev='e3fc0b7707dce894ef98e7981a9feaf6041708f8';b=git('show',rev+':'+p)
parents.append({'path':p,'revision':rev,'blob':git('rev-parse',rev+':'+p).decode().strip(),'sha256':digest(b),'read_scope':'complete historical mathematical premise; anchored moments/fillings/support graph independently examined, not current retained authority'})
authorities=json.load(open(root/'drain8159-family4-authority-identities.json'))
for a in authorities: assert digest(git('show',main+':'+a['path']))==a['sha256']
save('drain8159-family5-input-identities.json',{'current_main':main,'parents':parents,'authorities_reused_after_exact_hash_check':authorities})
positive=[
'BLOCK1: positive finite-volume hybrid/logistic generators on the supplied filtered carrier; rate moments, integrated identities and a specific negative pointwise-curvature witness. Small mean rate is not an L2-small multiplication bound or field theorem.',
'BLOCK2: two-root integer phase energy reserves; signed sine operator; stable forest and cut completion give every FIXED-order subtracted remainder O_n(a^3). All-length Gaussian-dressed compatible loop sums and continuous quadratic symbols apply to the expressly defined restricted loop functional, not the full physical pressure.',
'BLOCK2: determinant softened exclusion, cofactor cyclic realizations and complete contact-resource sums retain source bounds for each prescribed derivative graph. One-sided maps do not commute; scalar boundary realizations change with cyclic order. No arbitrary residual or branching sum is supplied.',
'BLOCK3: full-M2-domain, proper-support supplied global record laws differ by a proved nearest-neighbor covariance gap; common-slot order-independence gives independence a.e. with explicit null-profile and directional escapes. Full-foundation nonselection remains FAIL/unproved because the actual kinetic carrier and interpretation are missing.',
'BLOCK4: cubic Green energy bound H=1/4+pi^2/64, Gaussian feature registers and degree cost product(d!)^(3/4); exact tree/cycle normalization. Divergence of the displayed upper-majorant series is not divergence of physical coefficients.',
'BLOCK5: declared full-inner naturality support restrictions, sharp continuous generated-algebra support, Borel inverse-corner escape and compatible noncentral seed. Internal action/common fiber/regularity are supplied, not selected by lattice covariance; no physical kinetic completion.',
'BLOCK6: exact finite positive two-sector auxiliary law, integer filling invariance, real-MGF source normalization, independent-noise dual-clock identification and smooth-test coupling. Planar loops refute only a fixed integrable unshifted quadratic regulator; translation survives and duality alone does not prove Gaussianity.']
history=['All original initial failures and mutants preserved byte-for-byte.','Curvature cancellation fixed by separate continuous/jump subtraction with unchanged tolerance.','Exact rank elimination replaced by trace of verified idempotent; forest visited-set correction predates scientific assertions.','mpmath zero parse and numpy derivative dtype fixes preserve formulas; source phase-i and three missing cut terms genuinely reject mutants.','Random Fourier-feature fixture initially violates declared cap; final explicitly normalizes it into the hypothesis and adds sharper bound, not a physics change.','Symbolic M2/Hermite equalities repaired by exact expansion/coefficient comparison; original failures remain.','Block6 stdout prints case dictionaries before later dual-lattice fields are appended; final JSON contains those fields. This is consistent with final runner order, not evidence of a stale stdout mismatch.','Ordinary Python assertions-active execution contract assumed; no unsupported -OO blocker.']
external=[{'url':'https://arxiv.org/html/1411.1107v1','read_scope':'section2.1.3 eq16 complete; finite smooth forest identity/factorization only'}, {'url':'https://arxiv.org/html/hep-th/9409094v1','read_scope':'sectionIII Taylor theorem/proof and theoremIV.5 positivity/proof; finite identities only'}, {'url':'https://arxiv.org/pdf/math/0701129v2','read_scope':'Theorem1 ALT positive-matrix hypotheses, r>=1 reverse direction; not whole paper'}, {'url':'https://arxiv.org/html/1205.4599v3','read_scope':'section2.3 reversibility/admissibility and Proposition2.4 identity/proof; no entropy decay estimate imported'}]
report={'schema':'scoped-original-scientific-review-v1','pr':8159,'family':5,'head':head,'delta_base':base,'current_main':main,'scientific_verdict':'CONDITIONAL_POSITIVE_CANDIDATES_NO_CONSEQUENTIAL_MATH_DEFECT_FOUND','landing_verdict':'PENDING_CANONICAL_PACKAGING_SHARED_PATH_DISPOSITIONS_AND_SAME_SESSION_FINAL_REVIEW','path_dispositions':paths,'positive_candidates':positive,'findings':[],'rejected_claims':['full fixed-finite-clock physical Gaussian field from coefficientwise or restricted-loop bounds','full-axiom model nonselection or forced axiom update from supplied record kernels','unrestricted centrality from a declared action/regularity contract','physical divergence or all-method obstruction from failed common majorants/regulators','duality or covariance alone implies full Gaussianity'],'read_scope':{'family_originals':len(paths),'final_notes':sum('/notes/' in p['path'] for p in paths),'final_runners':sum('/evidence/' in p['path'] and p['path'].endswith('.py') for p in paths),'shared_context_only':{'HANDOFF.md':'lines1-440, complete BLOCK1-6 history','READING_LEDGER.md':'lines1-310, complete BLOCK1-6 literature history','APPROACH_REGISTRY.md':'lines1-100, BLOCK1-6 entries','NO_GO_LEDGER.md':'complete file read; final shared disposition reserved','README.md':'complete six-family map read earlier; final shared disposition reserved'}},'input_identities_artifact':str(root/'drain8159-family5-input-identities.json'),'current_main_loss_check':'Read actual main, not train73. Exact authorities unchanged. Relevant existing parents compared with delta base; originals are additions and must all remain recoverable. No canonical/current-source mutation in this review. Historical BLOCK27 is explicitly not promoted to current authority.','independent_control':{'source':str(root/'drain8159-family5-controls.py'),'source_sha256':digest((root/'drain8159-family5-controls.py').read_bytes()),'result':str(root/'drain8159-family5-controls.json'),'result_sha256':digest((root/'drain8159-family5-controls.json').read_bytes()),'scope':'bounded independently written exact algebra controls, no campaign imports or primary execution'},'history_preservation':history,'external_formula_sources':external,'original_inventory_sha256':digest((root/'drain8159-original-inventory.json').read_bytes()),'scope_excludes':'No whole-PR PASS, audit grade, physical phase, native law/action selection, or canonical final acceptance.'}
save('drain8159-family5-original-review.json',report)
md='# PR8159 original family5 review\n\n**Result:** conditional positive candidates; no consequential mathematical defect found in the reviewed BLOCK1–6 scope. This is not whole-PR or canonical landing acceptance.\n\nOriginal head `'+head+'`; actual main `'+main+'`. Reviewed '+str(len(paths))+' exact originals, '+str(report['read_scope']['final_notes'])+' notes and '+str(report['read_scope']['final_runners'])+' final runners, plus their evidence, historical variants, failures and declared helpers. Exact path identities/dispositions are in the JSON.\n\n## Scientific dispositions\n\n'+'\n\n'.join('- '+p for p in positive)+'\n\n## Verification and boundaries\n\nBounded independently written controls pass: rate recurrence, signed-loop residual counterexample, indirect-contact BKAR cancellation, Gram mixed derivative/PSD boundary, parent-rank covariance gap, nonreversible order escape, shear support, inverse corner, auxiliary resolvent and non-Gaussian self-duality. No campaign primary was executed or recaptured.\n\nAll prior failures and unique failed routes remain preserved. Same-author history is not independent proof. The complete six mandatory authorities were reused only after fresh exact hash comparison. Actual imported source sections and primary formula hypotheses are identified in the JSON; no full-paper or unrelated parent-proof acceptance is asserted.\n\n**Open:** all-graph summation, physical state/boundary matching and fixed-law full-field limit; actual kinetic realization and full-foundation compatibility of record constructions. Shared campaign originals and canonical packaging still require final dispositions/review.\n'
save('drain8159-family5-original-review.md',md)
# Exact union, recording coverage only, not scientific acceptance by aggregation.
covered=collections.defaultdict(list);reports=[]
for f in sorted(root.glob('drain8159-family*-original-review.json')):
 d=json.load(open(f)); reports.append({'path':str(f),'sha256':digest(f.read_bytes()),'family':d['family']})
 for p in d.get('path_dispositions',d.get('original_path_dispositions',[])):covered[p['path']].append(d['family'])
union=[]
for p in inv:
 q=dict(p);q['reviewed_families']=covered[p['path']]
 if q['reviewed_families']:q['coverage_status']='explicit_original_scientific_disposition_in_family_report; canonical acceptance remains separate'
 else:q['coverage_status']='SHARED_ORIGINAL_FINAL_DISPOSITION_PENDING';q['needed']='Read/reconcile complete final shared artifact against all six bounded family reports; preserve unique history and assign exact archive/canonical routing. Partial contextual reads are not whole-file acceptance.'
 union.append(q)
coverage={'schema':'original-coverage-union-v1','pr':8159,'head':head,'inventory_sha256':report['original_inventory_sha256'],'total_originals':len(inv),'explicit_family_dispositions':sum(bool(x['reviewed_families']) for x in union),'pending_shared_dispositions':sum(not x['reviewed_families'] for x in union),'whole_pr_verdict':'NOT_ACCEPTED_BY_FAMILY_AGGREGATION','reports':reports,'paths':union}
save('drain8159-six-family-original-coverage.json',coverage)
save('drain8159-six-family-original-coverage.md','# PR8159 six-family original coverage\n\n**351 / 366 originals have explicit bounded family dispositions. Fifteen shared originals still need final shared dispositions. No whole-PR PASS follows from this union.**\n\nAll six original reports remain immutable. Exact mode/blob/SHA identities and family membership are in the coverage JSON.\n\n## Shared originals still requiring final disposition\n\n'+'\n'.join('- '+p['path'] for p in union if not p['reviewed_families'])+'\n\nSome shared histories, README and NO_GO_LEDGER have been read in context; that does not replace a final whole-file reconciliation against all families. Complete the shared-file read and scientific/history routing, preserve all unique original material, and independently review the resulting canonical delta/current-main joins before accepting the whole PR.\n')
for name in ['drain8159-family5-controls.py','drain8159-family5-controls.json']:(root/name).chmod(0o444)
print(json.dumps({'family5_originals':len(paths),'notes':report['read_scope']['final_notes'],'runners':report['read_scope']['final_runners'],'union':coverage['explicit_family_dispositions'],'pending':coverage['pending_shared_dispositions'],'parents':[(p['path'],p.get('same_as_delta_base')) for p in parents]},indent=2))
