import pathlib,json,hashlib,subprocess,sys,gzip
r=pathlib.Path('/private/tmp/review-drain-20260915');w=r/'drain-author-slot';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda n:json.loads((r/n).read_text());cold=load('drain8153-preexecution-review.json');e=load('drain8153-execution-8153.json');f=load('drain8153-author-final-freeze.json')
def git(*a):return subprocess.check_output(['git','-C',str(w),*a])
assert git('write-tree').decode().strip()==f['tree']=='f175573422a68503054ed53f0235f73b1755dea9';assert not git('diff','--name-only')
for x in cold['source']['paths']:
 assert sha((w/x['path']).read_bytes())==x['sha256'];assert git('show',':'+x['path'])==(w/x['path']).read_bytes()
for rows in cold['inputs'].values():
 for x in rows:assert sha((w/x['path']).read_bytes())==x['sha256']
sys.path.insert(0,str(w/'scripts'));import runner_cache as c
runner=w/e['runner'];cache=c.cache_path_for(runner);cache_rel=cache.relative_to(w).as_posix();assert c.cache_status(runner)=='fresh';b=cache.read_text();assert e['stdout'].strip()==b.split('----- stdout -----\n',1)[1].split('----- stderr -----',1)[0].strip();assert e['exit_code']==0 and not e['stderr'];assert e['stdout'].count('PASS: ')==17 and 'TOTAL: PASS=17 FAIL=0' in e['stdout'];assert e['whole_tree_watchdog']['limit_bytes']==3*1024**3 and not e['whole_tree_watchdog']['violations']
change=git('diff','--name-status',cold['source']['tree'],f['tree']).decode().strip();assert change=='A\t'+cache_rel
rows=cold['original_dispositions']
for x in rows:
 assert sha(gzip.decompress((w/x['final_path']).read_bytes()))==x['original_sha256']
 if x['original_path'].startswith('logs/'):
  x['canonical_replacement']=dict(path=cache_rel,sha256=sha(cache.read_bytes()),scope='Fresh17/0 evidence of repaired positive-source runner; original cache retained byte-exact in archive.')
paths=cold['source']['paths']+[dict(path=cache_rel,sha256=sha(cache.read_bytes()))]
refs=[dict(path=str(r/x),sha256=sha((r/x).read_bytes()))for x in ['drain8153-preexecution-review.json','drain8153-author-unit-draft-v2.json','drain8153-author-source-handoff-v2.json','drain8153-gaussian-import-bibliography-v1.json','drain8153-author-cheap-v1.json','drain8153-execution-8153.json','drain8153-author-final-freeze.json','drain8153-capture.py','drain8153-capture-resource-deviation.json']]
o=dict(status='FINAL SOURCE PASS — POSITIVE BOUNDED SALVAGE; NO AUDIT VERDICT',reviewer='/root/review_8011',source=dict(base=f['base'],tree=f['tree'],paths=paths),inputs=cold['inputs'],actual_api=cold['actual_api'],original_identity=cold['original_identity'],original_dispositions=rows,current_main=cold['current_main'],affected_confirmation='Only fresh canonical cache added after independently confirmed cold source. All staged/working source bytes and all declared runtime/parent/context/tooling hashes remain identical. All22 original decoded payload hashes reconfirmed. Actual stdout matches cache,17/0,empty stderr; cache API fresh. No scientific rerun or final receipt preflight by reviewer.',execution=dict(exit_code=e['exit_code'],checks_pass=17,checks_fail=0,elapsed_seconds=e['elapsed_sec'],timeout_seconds=e['timeout_sec'],watchdog=e['whole_tree_watchdog'],resource_deviation='Cold plan proposed1GiB, but actual copied adapter configured3GiB. Actual sampled peak108527616bytes below both; do not claim1GiB enforcement or continuous memory maximum.1GiB was a proposed operational guard, not mathematical premise or original stricter science limit. Accept actual bounded180s/3GiB execution with preserved deviation; no rerun to restamp provenance.'),scope='Legendre positivity, imported Gaussian domination with exact hypothesis/parameter mapping, component infrared bound, magnetization-square liminf, finite zero-field Bogoliubov bound and every nonzero limiting momentum-sequence sandwich. No selected extremal-state transverse channel, real-space1/r, physical identity, or universal negative certificate.',external_method=cold['mathematical_import'],independent_controls_reused=cold['independent_controls_reused'],branch_disposition='Preserve original branch for unlanded physical/universal claims; exact original proof/history archived.',references=refs,next='Root owns one final schema2 --cache preflight and integration; no primary rerun needed.')
p=r/'drain8153-final-review.json';assert not p.exists();p.write_text(json.dumps(o,indent=2)+'\n');(r/'drain8153-final-review.md').write_text('# PR8153 final source review\n\nPASS for the narrowed positive component Fourier bounds, with Gaussian domination explicitly imported. Full22-path recovery remains bound; unsupported transverse/physical/universal claims are deferred and the original branch must remain.\n\nFresh primary evidence:17/0,1.57674seconds,180-second cap. The actual sampled watchdog limit was3GiB, differing from the proposed1GiB; observed peak108,527,616bytes, no violations. This discrepancy is preserved and disclosed; no rerun or restamp. All non-cache source and input bytes are unchanged. Root owns final schema2/cache preflight.\n');print(sha(p.read_bytes()))
