import pathlib,json,hashlib,subprocess,sys,copy
r=pathlib.Path('/private/tmp/review-drain-20260915');w=r/'drain-author-slot';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda n:json.loads((r/n).read_text());old=load('drain8154-final-review.json');draft=load('drain8154-current-main-draft-v2.json');advance=load('drain8154-current-main-advance-v2.json')
def git(*a):return subprocess.check_output(['git','-C',str(w),*a])
assert git('write-tree').decode().strip()==advance['new_tree']=='6ff84ef74a8308b9589548e8963b870c7eaf29c2';assert git('rev-parse','HEAD').decode().strip()==advance['new_base']=='9ff59dc9caf61444b8bf3bd3d0d13ea53ace1dac';assert not git('diff','--name-only')
for x in old['source']['paths']:assert sha((w/x['path']).read_bytes())==x['sha256']and git('show',':'+x['path'])==(w/x['path']).read_bytes()
assert draft['source']['paths']==old['source']['paths'] or {x['path']:x['sha256']for x in draft['source']['paths']}=={x['path']:x['sha256']for x in old['source']['paths']}
changes=[]
for group,rows in old['inputs'].items():
 new={x['path']:x for x in draft['inputs'][group]};assert set(new)=={x['path']for x in rows}
 for x in rows:
  h=sha((w/x['path']).read_bytes());assert h==new[x['path']]['sha256']
  if h!=x['sha256']:changes.append(dict(group=group,path=x['path'],old_sha256=x['sha256'],new_sha256=h))
assert {x['path']for x in changes}=={'scripts/audit_packet_script_deps.py','docs/audit/scripts/build_citation_graph.py'}
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as p,runner_cache as c
p.SCRIPTS_DIR=w/'scripts';api=[]
for a in old['actual_api']:
 runner=w/a['primary'];gh=list(g.resolve_helper_runner_paths(str(runner)));ph=sorted(p.transitive_helpers(runner.stem));assert gh==ph==[];assert c.cache_status(runner)=='fresh';assert g.extract_claim_type_hint((w/a['note']).read_text())==tuple(a['type'])or list(g.extract_claim_type_hint((w/a['note']).read_text()))==a['type'];api.append(dict(primary=a['primary'],graph_helpers=gh,packet_helpers=ph,cache_status='fresh'))
diff=git('diff',advance['old_base'],advance['new_base'],'--','scripts/audit_packet_script_deps.py','docs/audit/scripts/build_citation_graph.py');assert sum(1 for l in diff.decode().splitlines()if l.startswith('+')and not l.startswith('+++'))==2;assert not [l for l in diff.decode().splitlines()if l.startswith('-')and not l.startswith('---')]
o=copy.deepcopy(old);o['source']=dict(base=advance['new_base'],tree=advance['new_tree'],paths=old['source']['paths']);o['inputs']=draft['inputs'];o['current_context_addendum']={'prior_report':{'path':str(r/'drain8154-final-review.json'),'sha256':sha((r/'drain8154-final-review.json').read_bytes())},'old_base':advance['old_base'],'new_base':advance['new_base'],'tooling_changes':changes,'review':'Read exact two-line additive8025 helper mapping diff. Keys concern a distinct gauge-Wilson claim/runner; no algorithm or fourunit mapping changed. Both actual helper APIs still returnempty for allfourprimaries; allcache_statusfresh. All102source/cache and allotherboundinputbytes remainexact. Original proofs/controls/captures/dispositions remainvalid and immutable. No scientific rerun, no finalsharedpreflight byreviewer.','actual_api_confirmation':api,'tool_diff_sha256':sha(diff),'stale_check_boundary':'Coordinator reported old-context sharedcheck active duringadvance; preserve its actual result separately, do not infer successfulcurrent-context validation. Root ownsnew finalcheck.'};o['current_main_preservation']+=' Currentmain9ff59dc adds8025 independent gauge-Wilson material andtwo explicithelpermap entries; no fourunit source or scientificpremise changed.'
for name in ['drain8154-current-main-advance-v2.json','drain8154-current-main-draft-v2.json','drain8154-current-context-confirm-v2.py']:o['references'].append(dict(path=str(r/name),sha256=sha((r/name).read_bytes())))
pth=r/'drain8154-final-review-v2.json';assert not pth.exists();pth.write_text(json.dumps(o,indent=2)+'\n');(r/'drain8154-final-review-v2.md').write_text('# Current-context confirmation\n\nFinal source PASS remains valid at tree `'+advance['new_tree']+'` on current main9ff59dc. All102science/archive/cache paths are byte-identical; onlytwo boundtooling hashes changed through unrelated8025 explicithelper mappings. Bothactualresolvers andcachefreshness remainunchanged. All88originaldispositions andfourcapture receipts are retained. No scientific rerun; priorreport unchanged.\n');print(sha(pth.read_bytes()));print(json.dumps(changes,indent=2))
