from pathlib import Path
import json,hashlib,re,difflib
b=Path(__file__).resolve().parent;w=b/'review-draft-slot';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));oldp=b/'drain8159-author-canonical-draft-v3.json';d=json.loads(oldp.read_text());plan=json.loads((b/'drain8159-author-ownership-plan-v2.json').read_text())
for e in d['files']:assert sha(w/e['path'])==e['sha256'],e['path']
spec={
'3':('Supplied record laws and common-order kernels; foundation nonselection remains unproved','Current bounded results are the supplied global record-law constructions and exact covariance-separation and common-kernel order lemmas. Full-foundation model nonselection is REJECTED AS UNPROVED: kinetic-carrier matching, approved-primitive matching and physical interpretation are missing. Statements in the preserved original arguments do not supply those bridges. This is a substantive open obligation, not a proved exclusion merely awaiting a procedural certificate.'),
'5':('Supplied-action support classification; unrestricted exclusion deferred','Current bounded results are the exact conditional support and invariance statements under the explicitly supplied full-inner action and regularity hypotheses. No native algebra-action selection or unrestricted prohibition of noncentral kernels is accepted. Any promoted class-wide no-go beyond those conditional equations has DEFERRED N1 NEGATIVE CERTIFICATION and requires its actual route packet; the supplied-action support classification is not relabeled to evade that requirement.'),
'6':('Positive auxiliary identity and regulator estimates; exclusion certification deferred','Current bounded mathematics consists of the positive auxiliary identity, explicit planar-loop sequence and lower bounds, and the translation-escape calculation, with all original hypotheses. The class-wide statement that no fixed integrable unshifted quadratic regulator uniformly bounds the declared planar-loop family has DEFERRED N1 NEGATIVE CERTIFICATION. Its reviewed mathematical derivation is preserved below, but this landing does not accept or certify that negative claim. No five distinct in-domain attack routes have been established; finite controls and the positive identity do not certify exhaustion.'),
'18':('Positive cyclic generator bounds; exclusion certification deferred','Current bounded mathematics consists of the declared cone characterization, nonnegative jump mixture, nearest-neighbor envelope and coefficient estimates. The class-wide impossibility of canceling the quartic cosine error in the full declared all-time entrywise-positive cyclic generator cone at fixed continuous-symbol curvature has DEFERRED N1 NEGATIVE CERTIFICATION. Its reviewed mathematical derivation is preserved below, but this landing does not accept or certify that negative claim. No actual five independent failed-route packet has been established. Other bases, auxiliaries and representations remain outside the stated domain; they are not fabricated in-domain attacks.')}
patch=[];changed=[]
for n,(title,scope) in spec.items():
 p=plan['owners'][n]['canonical_note'];old=(w/p).read_text();s=re.sub(r'^claim_scope: .+$',lambda m:'claim_scope: '+json.dumps(title+'; supplied hypotheses and full mathematical arguments retained.'),old,count=1,flags=re.M);s=re.sub(r'^# .+$',lambda m:'# '+title,s,count=1,flags=re.M)
 marker='## Scope and actual premises\n\n';assert s.count(marker)==1;s=s.replace(marker,marker+'## Partial salvage disposition\n\n'+scope+'\n\nThe complete original text below is retained for mathematical context and recovery. Its class-wide exclusion and foundation-selection interpretations remain subject to the explicit dispositions here; historical headings or review language do not override them.\n\n',1)
 s+='\n## Certification and recovery conclusion\n\n'+scope+'\n\nN1 certification is not granted by a changed label, numerical agreement, or this preservation of the original proof. The original route records remain available below and in the exact archive. The original branch must remain as the recovery handle when this PR is closed after partial salvage.\n'
 (w/p).write_text(s);changed.append(p);patch.extend(difflib.unified_diff(old.splitlines(True),s.splitlines(True),fromfile=p+' v3',tofile=p+' v4'))
p='docs/work_history/review_loop/pr8159/README.md';old=(w/p).read_text();s=old+'\n## Partial salvage and retained branch\n\nThe canonical notes preserve the reviewed bounded mathematics. Negative-claim certification is explicitly deferred for the positive-generator-cone quartic-cancellation exclusion and uniform unshifted integrable-quadratic-regulator exclusion, and for any unrestricted support/selected-action no-go. Full-foundation nonselection remains unproved. These dispositions are not mathematical disproofs of the reviewed scoped estimates.\n\nThe original PR8159 branch at `ccca36e505a4cc5d0cd4735b377c15d69042fc41` must be preserved as the recovery handle on closure after partial salvage. All366 originals remain exact in this archive. No negative-certification or audit PASS is supplied.\n';(w/p).write_text(s);changed.append(p);patch.extend(difflib.unified_diff(old.splitlines(True),s.splitlines(True),fromfile=p+' v3',tofile=p+' v4'))
pf=b/'drain8159-partial-salvage-scope-v4.patch';assert not pf.exists();pf.write_text(''.join(patch))
proofs=json.loads((b/'drain8159-author-full-proof-map-v3.json').read_text())
for x in proofs:
 raw=(b/'drain8159-block27-original-proof.md').read_text() if x['original']=='EXTRA_BLOCK27' else (b/'drain8159-originals'/x['original']).read_text()
 def target(m):return m[1]+' (`'+m[2]+'`)' if re.search(r'\.(?:md|py|json|txt|log|yaml|yml|csv|pdf|gz)$',m[2].split('#',1)[0]) else m[0]
 body=re.sub(r'\[([^\]]+)\]\((?!https?://)([^)]+)\)',target,raw);body=re.sub(r'^(#{1,6}) ',lambda m:'#'*min(6,len(m[1])+2)+' ',body,flags=re.M)
 assert hashlib.sha256(body.encode()).hexdigest()==x['verified_complete_body_sha256'];assert (w/x['canonical_owner']).read_text().count(body)==1;x['canonical_owner_sha256']=sha(w/x['canonical_owner'])
pp=b/'drain8159-author-full-proof-map-v4.json';pp.write_text(json.dumps(proofs,indent=2)+'\n')
api=json.loads((b/'drain8159-author-input-discovery-v3.json').read_text())
for x in api['programs']:
 for e in x['runtime_closure']:e['sha256']=sha(w/e['path'])
for x in api['mathematical_premise_closure']:
 for e in x['parents']:e['sha256']=sha(w/e['path'])
ap=b/'drain8159-author-input-discovery-v4.json';ap.write_text(json.dumps(api,indent=2)+'\n')
for e in d['files']:e['sha256']=sha(w/e['path'])
d['status']='PARTIAL SALVAGE SCOPE V4; ORIGINAL REVIEWER CONFIRMATION REQUIRED';d['predecessor']=ref(oldp);d['closure_disposition']='Partial salvage only; preserve original branch and explicitly defer negative certification/unproved foundation nonselection.'
np=b/'drain8159-author-canonical-draft-v4.json';np.write_text(json.dumps(d,indent=2)+'\n')
rp=b/'drain8159-partial-salvage-scope-v4.json';rp.write_text(json.dumps({'draft':ref(np),'patch':ref(pf),'fullproofs':ref(pp),'discovery':ref(ap),'changed_paths':changed,'source_basis':ref(b/'drain8159-negative-certification-disposition-v1.json'),'preserved':'All72 full original/imported bodies unchanged from correctedv3; all41programs unchanged. Only four owner wrappers and historical README changed.','source_runs':0,'required':'Same-session affected scope confirmation; future full staged cold and capture gates.'},indent=2)+'\n');print(ref(np));print(ref(rp))
