from pathlib import Path
import json,hashlib,subprocess,sys,re
r=Path('/private/tmp/review-drain-20260915');w=r/'drain-author-slot';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));bind=lambda ps:[dict(path=p,sha256=sha(w/p)) for p in sorted(set(ps))];git=lambda *a:subprocess.check_output(['git','-C',str(w),*a],text=True).strip()
original=json.loads((r/'drain8150-original-inventory.json').read_text());mapping=json.loads((w/'docs/work_history/review_loop/pr8150/original-manifest.json').read_text());disps={}
for e in mapping:
 p=e['stored'];disps.setdefault(str(e['pr']),[]).append(dict(original_path=e['path'],original_sha256=e['sha256'],final_path=p,final_sha256=sha(w/p),disposition='Exact original bytes preserved in deterministic gzip; valid positive identities and finite witnesses separately narrowed into canonical source. Original negative certification deferred and original branches must remain recoverable.',recovery=e['head']+':'+e['path']))
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as a,runner_cache as c
notes=[];context=[];parents=[];runners=[];apis=[]
for name in json.loads((r/'drain8150-new-names.json').read_text()):
 p='docs/'+name;body=(w/p).read_text();primary=re.search(r'^runner: (.+)$',body,re.M)[1];cites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/p));context+=cites;runners.append(primary);deps=[x for x in cites if x.startswith('docs/ADMISSIBILITY') or x=='docs/MINIMAL_AXIOMS_2026-06-29.md'];parents+=deps
 assert not a.transitive_helpers(Path(primary).stem)
 inputs=c.declared_input_paths(w/primary);context+=list(inputs or [])
 apis.append(dict(primary=primary,primary_sha256=sha(w/primary),timeout=c.declared_timeout_for(w/primary),declared_inputs=list(inputs or []),declared_input_fingerprint=c.declared_input_fingerprint(w/primary),cache_status=c.cache_status(w/primary),helpers=[]))
 notes.append(dict(path=p,claim_id=g.claim_id_from_path(w/p),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type='bounded_theorem',primary_runner=primary,helpers=[],citations=cites,repository_dependencies=deps,dependency_rationale='Supplied positive six-axis pair rule and records-only model. Actual linked parent product identity, sufficient one-neighbour factorization, census multiset lemma and rectangle exact value only; broader negative conclusions not imported. Original same-session cold confirmation pending.'))
api=r/'drain8150-author-cache-api-v1.json';api.write_text(json.dumps(apis,indent=2)+'\n')
paths=git('diff','--cached','--name-only').splitlines();allnotes=[n['path'] for n in notes];context+=allnotes
context+=['docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md']
tools=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
report={'status':'AUTHOR DRAFT; ORIGINAL INDEPENDENT COLD CONFIRMATION REQUIRED; NOT SCIENTIFIC PASS','author':'/root/resume_8077','base':git('rev-parse','HEAD'),'tree':git('write-tree'),'original_dispositions':disps,'claim_dispositions':{'PR8148':'R1 causal scheduling identity (not posterior), value-blind mixture; R2 exact finite witnesses; R3 seeded connected-tree sufficient construction; R4/R5 coefficient/difference identities retained with original universal exclusions deferred; R6 finite rank retained. Remove gravity/static equivalence and primitive statistical grant.','PR8149':'U1 positive-law uniqueness/model convention retained; U2 arbitrary fixed-boundary sufficiency and repeated-value lemma retained, necessity proof gap explicit; U3 primary five-star-class/24plaquette finite witnesses distinguished from historical seven classes; U4 finite environments and one-site identity only, universal conclusion deferred; U5 no axiom selector.','PR8150':'X1 exact constant-pattern flip and strictness retained; X2 sufficient mixture construction and linear difference identity plus finite samples retained; necessity/cycle exclusions deferred; X3 constant-boundary flip identity and finite samples, universal mixture exclusion deferred; X4 scheduling weight boundary explicit.'},'preservation':'No base tracked file changed. All66 original versions recoverable by decoded hashes; three notes renamed to positive-scope names; runner basenames retained. No canonical old cache installed.','execution_plan':{'timeout_seconds_per_runner':300,'process_tree_rss_limit_bytes':3221225472,'concurrency':1,'authorization':'Pending original cold source confirmation and cheap receipt; no primary has been executed. Preserve failures; do not repeat independent controls.'},'checks':'AST, literal fences/forbidden/classical-name placement and vocabulary passed; archive decoded hashes verified; staged whitespace clean. No science execution, no cache or pipeline.','references':[ref(r/'drain8150-original-review.json'),ref(r/'drain8150-original-inventory.json'),ref(r/'drain8150-independent-controls.json'),ref(api)]}
rp=r/'drain8150-author-source-handoff-v1.json';rp.write_text(json.dumps(report,indent=2)+'\n');rr=ref(rp);review=ref(r/'drain8150-original-review.json')
rec={'schema_version':2,'unit_id':'PR8148-8149-8150','constituents':[dict(id='PR'+str(d['number']),head=d['headRefOid'],delta_base=d['delta_base'],dispositions=dict(rr,json_pointer='/original_dispositions/'+str(d['number']))) for d in original],'source':dict(base=git('rev-parse','HEAD'),commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),'inputs':dict(runtime=bind(runners),helpers=[],parents=bind(parents),context=bind(context),tooling=bind(tools)),'reviewer':dict(session='/root/review_8011 original review; final affected-source confirmation pending',report=review,references=[rr,ref(api),ref(r/'drain8150-independent-controls.json')]),'notes':notes,'supporting_proofs':[],'non_science_notes':[dict(path=p,rationale='Historical recovery instructions, not current scientific authority.',review_reference=review) for p in paths if p.endswith('.md') and p not in allnotes]}
f=r/'drain8150-author-unit-draft-v1.json';f.write_text(json.dumps(rec,indent=2)+'\n');print(ref(f));print(report['tree']);print('source',len(paths),'notes',len(notes))
