from pathlib import Path
import json,hashlib,subprocess,sys,re
r=Path('/private/tmp/review-drain-20260915');w=r/'drain-author8146';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));bind=lambda ps:[dict(path=p,sha256=sha(w/p)) for p in sorted(set(ps))];git=lambda *a:subprocess.check_output(['git','-C',str(w),*a],text=True).strip()
original=json.loads((r/'drain8146-original-review-report.json').read_text());mapping=json.loads((r/'drain8146-author-original-map-draft.json').read_text());disps={}
for e in mapping:
 p=e['stored'];disps.setdefault(str(e['pr']),[]).append(dict(original_path=e['original'],original_sha256=e['sha256'],final_path=p,final_sha256=sha(w/p),disposition='Exact original bytes preserved in deterministic gzip; live constructive science separately repaired; unproved/excessive original claims and negative certification remain deferred, original branch must remain recoverable.',recovery=e['head']+':'+e['original']))
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as a,runner_cache as c
notes=[];context=[];parents=[];runners=[];apis=[]
for pr,decl in original['original_runtime_declarations'].items():
 p=decl['paths'][0];body=(w/p).read_text();primary=re.search(r'^runner: (.+)$',body,re.M)[1];cites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/p));context+=cites;runners.append(primary);deps=[x for x in decl['paths'][1:] if x in cites];parents+=deps
 assert not a.transitive_helpers(Path(primary).stem)
 inputs=c.declared_input_paths(w/primary); context+=list(inputs or [])
 apis.append(dict(primary=primary,primary_sha256=sha(w/primary),timeout=c.declared_timeout_for(w/primary),declared_inputs=list(inputs or []),declared_input_fingerprint=c.declared_input_fingerprint(w/primary),cache_status=c.cache_status(w/primary),helpers=[]))
 notes.append(dict(path=p,claim_id=g.claim_id_from_path(w/p),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type='bounded_theorem',primary_runner=primary,helpers=[],citations=cites,repository_dependencies=deps,dependency_rationale='Finite positive six-axis product rule under supplied formation class; linked predecessor arguments used only within explicit parameter, nonvanishing and invariance hypotheses. Independent final premise/gate confirmation remains pending.'))
api=r/'drain8146-author-cache-api-v2.json';api.write_text(json.dumps(apis,indent=2)+'\n')
paths=git('diff','--cached','--name-only').splitlines();allnotes=[n['path'] for n in notes];context+=allnotes
context+=[p for p in original['source_input_context_hashes'] if (w/p).is_file()]
tools=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
report={'status':'AUTHOR DRAFT ONLY; INDEPENDENT COLD CONFIRMATION REQUIRED; NOT SCIENTIFIC PASS','author':'/root/resume_8077','base':git('rev-parse','HEAD'),'tree':git('write-tree'),'original_dispositions':disps,'claim_dispositions':original['claim_dispositions'],'repairs':'12 finding repairs drafted: exterior-cylinder DLR; witness-only opposite distinctness; explicit mixture law; X4 no law distinction; both majority inequalities; spatially invariant S0; prescribed rectangle/axial S5; conditional T4; witnessed Q1f; six-letter p=r; explicit probability imports; broader negative certificate deferred with complete originals.','open_gate':'X3 exhaustive exceptional classification remains live with full exact proof and requires original reviewer explicit claim/gate disposition. No negative gate PASS inferred.','preservation':'Base590 all tracked files unchanged; additions only. All116 original occurrences recoverable with verified decompressed hashes; all full scientific original notes/programs archived too.','execution_plan':{'timeout_seconds_per_runner':300,'process_tree_rss_limit_bytes':3221225472,'concurrency':1,'authorization':'Pending cold source confirmation and cheap receipt. One bounded final capture each; preserve any failure. No repeated independent controls.'},'checks':'AST parsing and text fence consistency only; no science run, no cache refresh, no pipeline.','references':[ref(r/'drain8146-original-review-report.json'),ref(r/'drain8146-findings-provisional.md'),ref(api)]}
rp=r/'drain8146-author-source-handoff-v2.json';rp.write_text(json.dumps(report,indent=2)+'\n');rr=ref(rp);review=ref(r/'drain8146-original-review-report.json')
rec={'schema_version':2,'unit_id':'PR8138-8139-8141-8142-8146','constituents':[dict(id='PR'+str(d['pr']),head=d['head'],delta_base=d['merge_base'],dispositions=dict(rr,json_pointer='/original_dispositions/'+str(d['pr']))) for d in original['original_constituents']],'source':dict(base=git('rev-parse','HEAD'),commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),'inputs':dict(runtime=bind(runners),helpers=[],parents=bind(parents),context=bind(context),tooling=bind(tools)),'reviewer':dict(session='/root/review_8012 original scientific review; final confirmation pending',report=review,references=[rr,ref(api)]),'notes':notes,'supporting_proofs':[],'non_science_notes':[dict(path=p,rationale='Historical source recovery instructions, no autonomous scientific authority.',review_reference=review) for p in paths if p.endswith('.md') and p not in allnotes]}
f=r/'drain8146-author-unit-draft-v2.json';f.write_text(json.dumps(rec,indent=2)+'\n');print(ref(f));print(report['tree']);print('source',len(paths),'notes',len(notes))
