import sympy as s,json,time,signal
from pathlib import Path
signal.alarm(30);start=time.monotonic();checks=[]
def ck(n,x):assert bool(x),n;checks.append(n)
a=s.Matrix([1,0,0]);b=s.Matrix([s.Rational(3,5),s.Rational(4,5),0]);e2=(b-a.dot(b)*a)/s.sqrt(1-a.dot(b)**2)
bad=s.Matrix.hstack(a,e2,a.cross(b));good=s.Matrix.hstack(a,e2,a.cross(e2))
ck('original_displayed_frame_not_rotation',bad.det()==s.Rational(4,5) and bad.T*bad!=s.eye(3));ck('normalized_frame_rotation',good.det()==1 and good.T*good==s.eye(3))
q=s.Matrix([0,0,1]);r=s.Matrix([s.Rational(4,5),0,s.Rational(3,5)])
ck('antipodal_measurement_nontrivial',((1+q.dot(r))/2,(1-q.dot(r))/2)==(s.Rational(4,5),s.Rational(1,5)))
# At orthogonal seeds ex,ey the frame is I: rotations generated by this F cannot create ez,
# but the supplied reference support {ez} does so immediately.
f=s.Matrix.hstack(s.Matrix([1,0,0]),s.Matrix([0,1,0]),s.Matrix([0,0,1]));ck('reference_support_is_extra_data',f==s.eye(3) and f*s.Matrix([0,0,1]) not in [s.Matrix([1,0,0]),s.Matrix([0,1,0])])
# Explicit covariance family of atomic measures, with free copy probability.
p=s.symbols('p',real=True);ck('antipodal_weights_not_fixed',s.simplify(p+(1-p))==1)
x=s.symbols('x',real=True);theta=s.symbols('theta',real=True)
# Continuous circle support exists when finite-atomic premise removed.
point=s.Matrix([s.cos(theta),s.sin(theta),0]);ck('circle_support_on_sphere',s.trigsimp(point.dot(point))==1)
out={'checks':checks,'count':len(checks),'elapsed':time.monotonic()-start,'scope':'Finding-directed independent exact controls; no original primary or duplicate group census run.'}
Path('/private/tmp/review-drain-20260915/drain8152-independent-control.json').write_text(json.dumps(out,indent=2)+'\n')
