import ast,copy,difflib,gzip,hashlib,json
from pathlib import Path
R=Path('/private/tmp/review-drain-20260915');W=R/'author-draft-slot';P=R/'drain8165-originals/.claude/science/physics-loops/toe-compact-ground-path-20260916'
def sha(b):return hashlib.sha256(b).hexdigest()
def pin(p):return {'path':p,'sha256':sha((W/p).read_bytes())}
assert json.loads((R/'author-draft-slot.json').read_text())['owner']=='PR8165-author'
notes=['COMPACT_ROTOR_SAMPLED_MAGNETIC_EVENT_BOUNDED_THEOREM_NOTE_2026-09-16.md','COMPACT_ROTOR_MAGNETIC_EXCURSION_BOUNDED_THEOREM_NOTE_2026-09-16.md','COMPACT_ROTOR_SPATIAL_GROUND_PATH_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-16.md','COMPACT_ROTOR_TEMPORAL_OSCILLATION_COARSE_CURRENT_BOUNDED_THEOREM_NOTE_2026-09-16.md']
orig=['BLOCK01_SAMPLED_MAGNETIC_EVENT_BOUND.md','BLOCK02_CONTINUOUS_TIME_MAGNETIC_EXCURSIONS.md','BLOCK03_SPATIAL_PATH_LIMIT.md','BLOCK04_TEMPORAL_OSCILLATIONS_AND_COARSE_CURRENTS.md']
runners=['compact_rotor_geometry_and_heat_check_2026_09_16','compact_rotor_reflection_and_path_check_2026_09_16','compact_rotor_coarse_current_check_2026_09_16']
oldrun=['block01_geometry_and_rotor_check','block02_reflection_and_path_check','block03_coarse_current_check'];prim=[0,1,1,2]
scopes=['Joint sampled magnetic-event bounds for the supplied compact rotor ground law on even spatial tori L>=4 at fixed positive g and T.','Whole-interval magnetic-excursion bounds for the same supplied rotor ground law, with volume-uniform constants at fixed positive g and T.','Subsequential infinite-volume continuous compact ground paths, their local Brownian-bridge specification and transferred excursion bounds.','Joint temporal oscillations and conserved integer coarse currents of the supplied compact rotor path law at fixed positive time scale T.']
aliases={'Block01':'the sampled-event note','Block02':'the magnetic-excursion note','Block03':'the spatial-path-limit note'}
diffs=[];preservation=[]
for j,name in enumerate(notes):
 old=(P/'notes'/orig[j]).read_text();body=old[old.index('## 1.'):]
 # Explicit prose substitutions only. Every indented formula line remains byte-identical.
 out=[]
 for line in body.splitlines(keepends=True):
  if not line.startswith('    '):
   for a,b in aliases.items():line=line.replace(a,b)
   line=line.replace('[the review](../review/PERSONAL_REVIEW.md)','the historical personal review preserved in the recovery packet')
   line=line.replace('draft PR8164','the contextual PR8164 construction').replace('theorems in draft','theorems in the historical draft')
   line=line.replace('this campaign','the original source review')
  out.append(line)
 body=''.join(out)
 deps=notes[:j]
 header='---\nclaim_id: '+name[:-3].lower()+'\nclaim_type: bounded_theorem\nrunner: scripts/'+runners[prim[j]]+'.py\nclaim_scope: '+json.dumps(scopes[j])+'\nupstream_dependencies: '+json.dumps([x[:-3].lower() for x in deps])+'\n---\n\n'
 status='**Type:** bounded_theorem\n\n```yaml\nactual_current_surface_status: conditional-support\nconditional_surface_status: conditional-support\ntrace_class: upstream_support\nreachability_to_target: supports\naudit_required_before_effective_retained: true\nbare_retained_allowed: false\nhypothetical_axiom_status: null\nadmitted_observation_status: null\n```\n\n'
 intro=scopes[j]+' This is a positive conditional theorem for the explicitly supplied Hamiltonian, geometry and limit order, not a derivation of that Hamiltonian from framework axioms. No audit verdict or retained promotion is asserted.\n\n'
 if deps:intro+='Load-bearing mathematical parents: '+', '.join('['+x+']('+x+')' for x in deps)+'. These are supplied-model proof dependencies, not retained axioms.\n\n'
 if j==2:intro+='The complete path-law construction below includes both reversible tightness and the actual compact local Brownian-bridge specification; the latter is part of the result.\n\n'
 if j==3:intro+='The infinite-volume application uses the full spatial-path-limit proof, including its local compact path specification, together with the sampled-event and excursion proofs.\n\n'
 boundary='\n\n## Evidence and execution boundary\n\nPrimary runner: `scripts/'+runners[prim[j]]+'.py`. The reflection/path runner jointly supports the magnetic-excursion and spatial-path-limit notes.\n\n'
 boundary+='The three calculations retain every original fixture, arithmetic operation, assertion and tolerance. Each retains a 120-second timeout. A 512 MiB external process cap is proposed from the bounded representations and library overhead; it is not a measured peak or a completed execution. Each runner reads and hash-pins its declared source-note inputs and writes JSON under `logs/runner-cache/`. `TOTAL: PASS=3 FAIL=0` counts three completed diagnostic families, not three assertions or exhaustive theorem coverage. The JSON separately labels the static source assertion count.\n\n'
 boundary+='The [historical recovery packet](work_history/repo/review_feedback/pr8165-evidence/README.md) preserves all 88 original paths, modes, blobs and byte hashes, all four full working proofs, all three calculations, eleven mutation histories and the failed Fourier attempt. Historical output is not current-source execution evidence. PR8164 is contextual comparison only; no theorem or status is imported from it.\n\n'
 boundary+='## No-Go Discipline Gate\n\n**N1 — Actual routes.** Formal negative-packet certification is deferred: the source does not supply five qualifying refuted routes. The actual approach registry and finite countercontrols are preserved; no extra routes are invented. This does not negate the positive supplied-model proofs or the exact finite counterexamples.\n\n**N2 — Shared scope.** One supplied Hamiltonian and the stated compact geometry underlie the chain. Reflection/chessboard is a shared mathematical premise; future source-response, harmonic-sector and microscopic-current obligations are not independent walls proved here.\n\n**N3 — Conditions.** Compact Haar angles, the full thermal trace followed by its neutral ground limit, even L>=4, fixed positive g and T, and the oriented principal branch are explicit. No limiting-state uniqueness, positive-semidefinite constrained kernel or finite-clock Brownian behavior is assumed.\n\n**N4 — Credit and failures.** Biskup supplies the matched chessboard theorem; the finite smooth reversible identity is derived and credited. The failed Fourier cutoff attempt, exact subsequent refinement, eleven mutation outcomes and prior source versions remain recoverable without treating them as current captures.\n\n**N5 — Resolution.** Finite geometry, circle/rotor matrices and integer cochains test the stated identities and constants. Volume-uniform bounds, continuous-path tightness and the infinite-volume specification are analytic proofs, not exhaustive numerical runs. The five execution-scope lines report only the program that actually finishes.\n\n**N6 — Partial closure.** Sampled events, full excursions, a continuous-path spatial limit and a fixed-T current construction are successive positive results. No new primitive is proposed.\n\n**N7 — Strongest boundary.** Rare coarse conserved currents do not by themselves give a photon, a native Hamiltonian, a unique vacuum, microscopic T->0 control, exhaustive harmonic sectors or physical electric reconstruction. These are open extensions, not impossibility claims.\n\n**N8 — Reopening.** Smooth-field/current weighting and source-response control may resolve the remaining physical questions. The periodic spatial subsequence is not equated with the contextual free-box state. No broad negative certification is claimed.\n'
 text=header+old.splitlines()[0]+'\n\n'+status+intro+body.rstrip()+boundary
 target=W/'docs'/name;assert not target.exists();target.write_text(text)
 assert [x for x in old.splitlines() if x.startswith('    ')]==[x for x in text.splitlines() if x.startswith('    ')]
 # Reversibly reconstruct the whole proof body using the recorded exact transformed lines.
 pairs=[{'original':a,'canonical':b} for a,b in zip(old[old.index('## 1.'):].splitlines(True),body.splitlines(True)) if a!=b]
 assert len(old[old.index('## 1.'):].splitlines())==len(body.splitlines())
 preservation.append({'original':'notes/'+orig[j],'canonical':'docs/'+name,'full_proof_body_line_count':len(body.splitlines()),'formula_lines_exact':True,'prose_line_transformations':pairs,'original_body_sha256':sha(old[old.index('## 1.'):].encode()),'canonical_body_sha256':sha(body.encode())})
 diffs.extend(difflib.unified_diff(old.splitlines(True),text.splitlines(True),fromfile='original/notes/'+orig[j],tofile='docs/'+name))
certs=[['all original oriented faces, trial integrals and compact one-face heat comparisons','periodic geometry L=4,6,8 and all original reflection planes','Fourier cutoffs48/64 and finite-difference meshes384/768/1536; no rigorous tail enclosure','sampled and excursion parameter constants at the original fixed couplings','checked and not executed — full lattice ground law and infinite-volume theorem are analytic, not numerically sampled'],['all original reflection, indefinite-kernel and moment diagnostics','12-link binary strip4096 states; this clock model is only an algebra control','reduced16 and reflection128 matrices, rotor cutoffs32/48, original free-circle and clock controls','three strip parameter pairs, original moment time/coupling grid and even powers2/4/6/10','checked and not executed — continuous-path tightness and compact infinite-volume specification use the complete proof'],['exact oriented coboundary, integrality, conservation, dual divergence and witnesses','five seeded integer fields on a four-dimensional L4 torus; not ground-law samples','checked and not executed — no physical spectrum is computed by this cochain program','link dissemination at L4/6/8 and original80-digit fixed-coupling parameter checks','finite periodic cochain support and degree counts completed; infinite-Z4 current law uses the full spatial-path-limit proof']]
plans=[]
for k,stem in enumerate(runners):
 old=(P/'evidence'/(oldrun[k]+'.py')).read_text();inputs=['docs/'+x for x in notes[:[2,3,4][k]]];hashes={x:sha((W/x).read_bytes()) for x in inputs}
 src=old.replace('AUDIT_TIMEOUT_SEC = 120','AUDIT_TIMEOUT_SEC = 120\nAUDIT_MEMORY_MB = 512\nAUDIT_INPUT_PATHS = '+repr(inputs)+'\nEXPECTED_INPUT_SHA256 = '+repr(hashes),1)
 src=src.replace('# Scientific inputs are defined below; the only repository integrity read\n# is this source file for its SHA256. Raw outputs are not audit caches.','# Numerical fixtures remain defined below. Declared proof inputs and this\n# source are hash-bound; JSON diagnostics alone are not audit verdicts.',1)
 src=src.replace('Personal challenges to Blocks01-02','Finite challenges to sampled magnetic events and excursions',1).replace('reflection/path steps in Blocks01-03','reflection, excursion and spatial-path-limit steps',1)
 assert src.count('    print(json.dumps(ans,indent=2,sort_keys=True))')==1
 src=src.replace('    print(json.dumps(ans,indent=2,sort_keys=True))','    _emit(ans)',1)
 count=sum(isinstance(n,ast.Assert) for n in ast.walk(ast.parse(old)))
 extra='\n\ndef _check_inputs():\n    root = Path(__file__).resolve().parents[1]\n    for name in AUDIT_INPUT_PATHS:\n        if hashlib.sha256((root / name).read_bytes()).hexdigest() != EXPECTED_INPUT_SHA256[name]:\n            raise RuntimeError("input identity mismatch: " + name)\n\ndef _emit(report):\n    report["input_sha256"] = dict(EXPECTED_INPUT_SHA256)\n    report["completed_diagnostic_families"] = 3\n    report["total_unit"] = "completed diagnostic families, not dynamic assertions"\n    report["static_source_assert_statements"] = '+str(count)+'\n    output = Path(__file__).resolve().parents[1] / "logs" / "runner-cache" / (Path(__file__).stem + ".json")\n    output.parent.mkdir(parents=True, exist_ok=True)\n    output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\\n")\n    print(json.dumps(report, indent=2, sort_keys=True))\n    print("TOTAL: PASS=3 FAIL=0")\n'
 for label,detail in zip(['per_element','per_site','per_mode','per_block','lattice_wide'],certs[k]):extra+='    print('+repr(label+': '+detail+'.')+')\n'
 start=src.index("if __name__")
 src=src[:start]+extra+"\nif __name__ == '__main__':\n    _check_inputs()\n    main()\n"
 # Compare all original computational function ASTs: only final report wrapper differs.
 a=ast.parse(old);b=ast.parse(src);af={n.name:n for n in a.body if isinstance(n,ast.FunctionDef)};bf={n.name:n for n in b.body if isinstance(n,ast.FunctionDef)}
 for n,node in af.items():
  expected=copy.deepcopy(node)
  if n=='main':expected.body[-1].value=ast.Call(func=ast.Name(id='_emit',ctx=ast.Load()),args=[ast.Name(id='ans',ctx=ast.Load())],keywords=[])
  assert ast.dump(expected,include_attributes=False)==ast.dump(bf[n],include_attributes=False),n
 target=W/'scripts'/(stem+'.py');assert not target.exists();target.write_text(src);target.chmod(0o755);compile(src,str(target),'exec')
 preservation.append({'original':'evidence/'+oldrun[k]+'.py','canonical':'scripts/'+stem+'.py','original_computational_function_ASTs_exact':True,'only_main_AST_exception':'final print JSON wrapper replaced by _emit(ans); report and all computations unchanged','static_assert_statements':count,'original_fixture_tolerances_and_arithmetic_preserved':True})
 diffs.extend(difflib.unified_diff(old.splitlines(True),src.splitlines(True),fromfile='original/evidence/'+oldrun[k]+'.py',tofile='scripts/'+stem+'.py'))
 plans.append({'runner':'scripts/'+stem+'.py','source_sha256':sha(src.encode()),'ordered_inputs':[pin(x) for x in inputs],'timeout_sec':120,'proposed_external_process_tree_limit_bytes':512*1024**2,'resource_status':'source-derived proposal; not measured RSS or execution authorization','capture_status':'not run','json_output':'logs/runner-cache/'+stem+'.json','completed_family_total':3,'static_assert_statements':count,'scope':certs[k]})
archive=W/'docs/work_history/repo/review_feedback/pr8165-evidence';manifest=json.loads((archive/'archive-manifest.json').read_text());assert len(manifest['entries'])==88
(archive/'README.md').write_text('# Historical compact rotor source recovery\n\nAll 88 original paths at `c228dbcfc0a6b71639316915f460c32dbf479723` retain their separate modes, Git blobs and raw SHA-256 identities in `archive-manifest.json`. Four complete proofs and the historical scope/review records remain readable under `kept/`; deterministic payloads preserve the three calculations and all development sources, streams and eleven mutation histories. This is historical provenance, not current execution evidence or audit authority.\n\nThe Fourier32/48 attempt failed its unchanged 1e-10 tolerance; Fourier48/64, further diagnostic cutoffs and finite differences are preserved without turning them into a rigorous tail enclosure. The coarse-current before-timeout source also precedes its independent witness-loss assertion. All stronger provisional wording remains recoverable. Formal negative-packet certification lacks five qualifying routes and remains deferred; the canonical notes state positive conditional results and retain exact finite counterexamples.\n\nCanonical complete proofs:\n\n'+'\n'.join('- `docs/'+x+'`' for x in notes)+'\n')
review=json.loads((R/'drain8165-original-review.json').read_text());original={x['path']:x for x in review['original_inventory']};mapping=[]
canon={str(P/'notes'/x):'docs/'+y for x,y in zip(orig,notes)};canon.update({str(P/'evidence'/(x+'.py')):'scripts/'+y+'.py' for x,y in zip(oldrun,runners)})
for e in manifest['entries']:
 o=original[e['original_path']];stored=archive/e['stored_path'];raw=gzip.decompress(stored.read_bytes()) if e['encoding']=='gzip' else stored.read_bytes()
 assert sha(raw)==e['raw_sha256']==o['sha256'];assert e['git_blob']==o['blob'] and e['original_mode']==o['mode'];assert raw==Path(o['recovery_path']).read_bytes()
 target=canon.get(o['recovery_path']);mapping.append({'original_path':e['original_path'],'original_mode':e['original_mode'],'original_blob':e['git_blob'],'original_sha256':e['raw_sha256'],'disposition':'complete canonical source; packaging changes only; original exactly recovered' if target else 'historical development/provenance preserved exactly; no current status imported','recovery':str(stored.relative_to(W)),'recovery_encoding':e['encoding'],'final_path':target,'final_sha256':sha((W/target).read_bytes()) if target else None})
for name,obj in [('preservation',preservation),('full-mapping',mapping),('input-resource-plan',plans)]:
 out=R/('drain8165-author-'+name+'-v1.json');assert not out.exists();out.write_text(json.dumps(obj,indent=2)+'\n')
(R/'drain8165-author-correction-v1.diff').write_text(''.join(diffs))
prepared={'status':'UNTRACKED_AUTHOR_PREPARED_V1_NOT_REVIEWED_OR_EXECUTED','base':'631d6b36cd1e9b860763ebcad36e40a2bbe7439c','worktree':str(W),'owner':'PR8165-author','notes':[pin('docs/'+x) for x in notes],'runners':[pin('scripts/'+x+'.py') for x in runners],'original_review_sha256':sha((R/'drain8165-original-review.json').read_bytes()),'archive_manifest':pin(str((archive/'archive-manifest.json').relative_to(W))),'original_dispositions':88,'negative_certification':'DEFERRED; no five qualifying N1 routes; no broad negative theorem claimed','resource_assessment':review['resource_assessment'],'evidence':[{'path':str(p),'sha256':sha(p.read_bytes())} for p in [R/('drain8165-author-'+n+'-v1.json') for n in ['preservation','full-mapping','input-resource-plan']]+[R/'drain8165-author-correction-v1.diff']],'remaining':['Original reviewer early affected review','Coordinator exact-current-main and actual metadata discovery','Cold-source confirmation and resource freeze','Coordinator three serial captures and combined validation'],'primary_executions':0,'staged':False}
(R/'drain8165-author-prepared-v1.json').write_text(json.dumps(prepared,indent=2)+'\n')
print(json.dumps({'status':prepared['status'],'notes':4,'runners':3,'originals':88,'primary_executions':0}))
