import pathlib,json,hashlib,subprocess,sys
r=pathlib.Path('/private/tmp/review-drain-20260915');w=r/'review-meta-slot';root=r/'drain8153-originals/8151';sha=lambda b:hashlib.sha256(b).hexdigest()
u=next(x for x in json.loads((r/'drain8153-original-inventory.json').read_text())if x['number']==8151)
def git(*a):return subprocess.check_output(['git','-C',str(w),*a])
assert json.loads((r/'drain8151-review-head-check.json').read_text())['headRefOid']==u['headRefOid']
assert set(git('diff','--name-only',u['delta_base'],u['headRefOid']).decode().splitlines())=={x['path']for x in u['original_paths']}
rows=[]
for x in u['original_paths']:
 b=git('show',u['headRefOid']+':'+x['path']);mode,typ,blobpath=git('ls-tree',u['headRefOid'],'--',x['path']).decode().split(None,2);blob=blobpath.split('\t')[0];assert mode==x['mode'] and blob==x['blob'] and sha(b)==x['sha256']
 role='historical context and author evidence; preserve exact full bytes, no author verdict imported'
 if x['path'].startswith('docs/audit/'):role='generated citation manifest; exclude as authority, preserve historical bytes, regenerate only from accepted source'
 elif x['path'].startswith('docs/'):role='original theorem/proof; current claimed phase chain fails source review; preserve whole proof and branch; narrow positive salvage pending'
 elif x['path'].startswith('scripts/'):role='primary exact finite controls; preserve original; narrow labels and add decisive geometry/orbit controls in author copy'
 elif x['path'].startswith('logs/'):role='historical20/0 cache; not evidence for missing infinite-volume proof; preserve and supersede only after affected source capture'
 rows.append(dict(x,disposition=role,recovery=u['headRefOid']+':'+x['path']))
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')]
import runner_cache as c,build_citation_graph as g,audit_packet_script_deps as p
runner=next(root/x['path']for x in rows if x['path'].startswith('scripts/'));note=next(root/x['path']for x in rows if x['path'].startswith('docs/')and x['path'].endswith('.md'));p.SCRIPTS_DIR=root/'scripts'
inputs=[]
for name in c.declared_input_paths(runner):
 f=root/name if (root/name).exists()else w/name;inputs.append(dict(path=name,sha256=sha(f.read_bytes()),source=str(f)))
context=[]
for path in ['docs/MINIMAL_AXIOMS_2026-06-29.md','docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/audit/data/axiom_premise_nodes.json','docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md']:
 context.append(dict(path=path,sha256=sha((w/path).read_bytes()),read_scope='current authority, exact source reused from same-session premise review; no statistical or phase grant'))
findings=[
 {'id':'F1','severity':'material proof gap','target':'T3 dissemination/T4 corollary/T5/T7','finding':'Site reflection preserves each vertex coordinate parity. A canonical direction1 bond only reaches even transverse rows. On side4, orbit8 versus16 edges in2D,16 versus64 in3D. At independent spins the actual2D event probability1225/5184 differs from all-direction1500625/26873856. Full-N all-bond bound cannot be substituted. Phase threshold216 and LRO/coexistence chain not established.','repair':'Preserve proof; defer unconditional phase conclusion or supply independently reviewed corrected geometry/event normalization and all resulting constants. Positive T1/T2/full-direction counting and finite instances remain useful.'},
 {'id':'F2','severity':'false group inference','target':'T6(v)','finding':'A nonuniform distribution(1,...,6)/21 has48 images under cube group, not <=6. Equal one-site marginal does not imply equal Gibbs states; symmetric one-site marginal does not characterize whole-state symmetry.','repair':'Remove orbit2..6 and state-identification claims; conditional uniqueness contradiction inT6(i–iv) can remain with explicit LRO hypothesis and standard imports.'},
 {'id':'F3','severity':'scope','target':'T2/T4','finding':'T2 square proof is for real-valued F (complex version needs conjugation). T4 proof uses p>=m; for p<m result is only trivial since6m/p>1.','repair':'State real-valued F or Hermitian form and split counting/trivial regimes.'},
 {'id':'F4','severity':'evidence scope','target':'note B2/history','finding':'Primary uses20ringF at each of2triples,3torusF onlyat(3,1,2). Old control uses simple vertical pairs while current side2 torus doubles them. Old refuter calls removed plaquette_neighbors; its complete present script cannot reproduce final output against current primary.','repair':'Correct actual counts/domains; preserve old evidence as historical source-dependent output, not fresh reproducible authority.'},
 {'id':'F5','severity':'negative certificate/premise','target':'N1–N8 and trace','finding':'N1 has proof checks plus an out-of-target undecided band, notfive actual distinct exact-target attacks;N2 merely asserts independence. Currentstatic/Green carrier attribution is not implied by corrected8147 auxiliaryGaussian scope.','repair':'Explicitly defer negative certification and phase verdict; retain conditional positive identities/witnesses and honest phase-obligation boundary. Do not manufacture attacks or make new axioms.'}]
refs=[]
for path in ['drain8153-original-inventory.json','drain8153-pr8151-original.patch','drain8151-review-head-check.json','drain8151-review-acquire.json','check8151/controls.py','check8151/controls.json']:
 refs.append(dict(path=str(r/path),sha256=sha((r/path).read_bytes())))
o=dict(status='ORIGINAL REVIEW COMPLETE; MATERIAL FINDINGS; AUTHOR SALVAGE PENDING',reviewer='/root/review_8011',unit=u['number'],head=u['headRefOid'],delta_base=u['delta_base'],current_main='0ee1a0396c2160605397ecf42f3602215a572c67',original_dispositions=rows,read_coverage='Full original canonical note and runner; complete changed history delta; complete two control scripts and outputs. Inherited campaign state/history is provenance, not scientific authority, previously inspected in this same session; complete full files preserved. Current uniqueness-parent premises/objects, target/scope and TheoremI read; no numerical threshold certification from that parent is imported into this unit.',findings=findings,actual_api=dict(type=g.extract_claim_type_hint(note.read_text()),timeout=c.declared_timeout_for(runner),graph_helpers=list(g.resolve_helper_runner_paths(str(runner))),packet_helpers=sorted(p.transitive_helpers(runner.stem)),runtime_inputs=inputs),context=context,independent_controls=json.loads((r/'check8151/controls.json').read_text()),external_methods={'consulted_primary_source':'https://www.math.ucla.edu/~biskup/PDFs/papers/Prague-School.pdf','read_scope':'Definition4.7 and Theorem4.8: overlapping site-reflection blocks and reflected block functions; corroborates need to use actual reflected event rather than translation of canonical lower edge. No numerical constant imported.','original_imports':'Planar cut-cycle/Jordan separation, consistent finite-dimensional extension, reverse martingale. Original extremal decomposition also used but not listed among its three named imports; remove orbit inference rather than conceal this import.'},current_main_loss='No edits to review checkout. Canonical original note/runner/cache are new relative main; campaign historical files overlap main and must archive, not overwrite. Generated manifest excluded as submitted authority. Current uniqueness-parent silent region supplies no strong-coupling conclusion.',salvage='Spectrum and signed-permutation symmetry; real site-reflection sum-of-squares; explicitly normalized finite chessboard instances; full-direction bad-bond counting with domain split; contour arithmetic as conditional bound; torus-limit and uniqueness contradiction conditional on separately supplied proven uniform correlation bound. Unconditional threshold216/Z2/Z3 phase result not accepted. Preserve original branches and full proofs.',references=refs,execution='One independent stdlib geometry/group/algebra control,0.0021s; no primary executions or fullpipeline. Original cap900sec; final resource plan must be bound after corrections.',final_source_verdict='NOT YET PASS; affected author correction required')
p=r/'drain8151-original-review.json';assert not p.exists();p.write_text(json.dumps(o,indent=2)+'\n');(r/'drain8151-original-review.md').write_text('# PR8151 original review\n\nMaterial findings prevent the claimed strong-coupling phase theorem from passing. Site-reflection dissemination covers only parity-selected transverse rows; the proof incorrectly substitutes the all-direction bad-bond event. The stated extremal-state orbit bound is also unsupported (a nonuniform six-value marginal can have48 images).\n\nUseful salvage remains: spectrum, real reflection-positivity identity, exact finite witnesses, counting/series identities and conditional limit implications. Preserve the complete original proof and branch; do not label negative certification complete. Full22-path dispositions and controls are in the JSON. No primary executed.\n');print(sha(p.read_bytes()))
