import json,pathlib,hashlib,sys,subprocess
r=pathlib.Path('/private/tmp/review-drain-20260915');w=r/'review-meta-slot';o=r/'drain8158-originals/8158'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
u=json.loads((r/'drain8158-original-inventory.json').read_text())[0]; prior=json.loads((r/'drain8156-original-review.json').read_text())
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')]
import runner_cache as c,build_citation_graph as g,audit_packet_script_deps as a
runner=next((o/'scripts').glob('*.py')); note=next((o/'docs').glob('*.md'))
inputs=[]
for p in c.declared_input_paths(runner):
 q=o/p if (o/p).exists() else w/p;inputs.append({'path':p,'sha256':sha(q),'source':str(q)})
for row in prior['context']+prior['methodology']:assert sha(w/row['path'])==row['sha256'],row
rows=[];coll=[]
for x in u['original_paths']:
 assert sha(o/x['path'])==x['sha256']
 p=x['path'];d='Preserve exact historical source/proof/control version; author certificates are not current authority.'
 if p.startswith('docs/audit/'):d='Exclude generated citation manifest; regenerate from accepted current source.'
 elif p.startswith('docs/'):d='Replace by narrowed positive component-factorization note; archive complete original and preserve branch for deferred universal claims.'
 elif p.startswith('scripts/'):d='Correct geometry/scope and source bindings without changing valid finite arithmetic; preserve original.'
 elif p.startswith('logs/'):d='Preserve original historical cache; current corrected source requires fresh bound capture.'
 rows.append({**x,'original_path':p,'original_sha256':x['sha256'],'disposition':d,'recovery':u['headRefOid']+':'+p})
 if (w/p).exists():coll.append({'path':p,'current_sha256':sha(w/p),'original_sha256':x['sha256'],'action':'Preserve existing current-main bytes; no overwrite by original packet.'})
f=[{'id':'F1','scope':'Title, Q3(d), N1','finding':'Universal topology iff unsupported: constant rule is an exception; arbitrary-component sector criterion does not prove nonvanishing; factors with overlapping arguments can in general cancel. Three-or-more attachments unproved.','repair':'Defer universal negative certificate; retain exact product-factor constancy criterion and specified bridge/path witnesses.'},{'id':'F2','scope':'Q4(a), D1/D4','finding':'Square plus site attached to adjacent corners has triangle, impossible in bipartite nearest-neighbour cubic lattice. Three quoted TVs are correct abstract-graph diagnostics.','repair':'Label abstract graph explicitly throughout note/runner; do not claim lattice fixture.'},{'id':'F3','scope':'Q2','finding':'Zero-attachment components are also constant.','repair':'Use at most one recorded attachment; transitivity/covariance and finite positive normalization explicit.'},{'id':'F4','scope':'Q5 and primitive/framework compliance','finding':'Supplied finite measures do not certify every axiom sentence. Integrated hidden sites can induce dependence beyond recorded nearest neighbours.','repair':'State conditional mathematical constructions, no full framework-model or reading-selection certificate.'},{'id':'F5','scope':'Q5 cross-lane transfer','finding':'Marginalization transfers uniformly bounded linear expectations/probabilities, not arbitrary nonlinear law properties; torus equality requires no hidden sites.','repair':'Restrict statements accordingly; keep clauses unadopted proposals.'}]
d={'status':'COMPLETE ORIGINAL REVIEW; NARROW SOURCE FIXES REQUIRED; NOT FINAL PASS','reviewer':'/root/review_8011','unit':8158,'current_main':'9ff59dc9caf61444b8bf3bd3d0d13ea53ace1dac','head':u['headRefOid'],'delta_base':u['delta_base'],'delta_sha256':u['patch_sha256'],'original_dispositions':rows,'current_main_collisions':coll,'source':{'note':str(note),'note_sha256':sha(note),'runner':str(runner),'runner_sha256':sha(runner)},'actual_api':{'type':g.extract_claim_type_hint(note.read_text()),'timeout':c.declared_timeout_for(runner),'graph_helpers':g.resolve_helper_runner_paths(str(runner)),'packet_helpers':sorted(a.transitive_helpers(runner.stem)),'runtime_scientific_inputs':inputs},'context':prior['context'],'methodology':prior['methodology'],'findings':f,'claim_dispositions':{'Q1':'Retain exact component factorization and conditional-average identity.','Q2':'Retain sufficient at-most-one attachment statement.','Q3a-c':'Retain six-axis spectral decomposition and exact bridge/path iff constant rule within stated fixture.','Q3d':'Retain sector criterion only, not arbitrary component nonvanishing.','Q3e':'Retain sphere bridge factor and strict dot-product monotonicity for beta>0.','Q4a':'Retain exact numbers as abstract graph only.','Q4b-c':'Retain actual cube and pendant-forest lattice witnesses.','Q5':'Narrow to supplied readings and linear averaging; no all-axiom models or arbitrary cross-lane transfer.','N1-N8':'No universal negative certification accepted; preserve original branch and full historical proof.'},'independent_controls':json.loads((r/'check8158/controls.json').read_text()),'read_coverage':'Full canonical note and runner; complete changed historical proof/control delta and outputs. Inherited campaign history is provenance only. Actual static parent direct cancellation and finite positive Brook ratio proof read; current possibility parent conditional representation scope reused by exact hash. Six mandatory authorities and methodology unchanged by hash.','external_methods':'Finite sums, transfer matrix traces, finite group orbit decomposition and elementary spherical integral are directly checked; no external theorem import required.','current_main_loss':'Original history and generated-manifest collisions recorded individually; archive originals without replacing current-main versions. No deletions proposed.','resource_boundary':'No primary or mutation campaign rerun. Independent20-control implementation only. Original primary declares900 seconds; author must freeze actual bounded capture contract before execution.','references':[{'path':str(r/p),'sha256':sha(r/p)}for p in ['drain8158-original-inventory.json','drain8158-pr8158-fetch.json','drain8158-pr8158-original.patch','check8158/controls.py','check8158/controls.json']]}
p=r/'drain8158-original-review.json';p.open('x').write(json.dumps(d,indent=2)+'\n');print(sha(p),len(rows),len(coll),d['actual_api'])
(r/'drain8158-original-review.md').open('x').write('# PR8158 original review\n\nSource fixes required. Retain component factorization, at-most-one attachment sufficiency, exact bridge/path criteria and finite witnesses. Defer the universal topology iff and framework-model certification. The triangle-containing fixture is an abstract graph only; its exact numbers are valid. Averaging transfer must be restricted to uniform linear bounds.\n\nAll22 original paths are bound in the JSON report. Independent controls passed20/0; no primary executed. Preserve original branch and exact historical source.\n')
