from pathlib import Path
import ast,difflib,hashlib,json,os,shutil,subprocess,sys
sys.dont_write_bytecode=True
R=Path('/private/tmp/review-drain-20260915');W=R/'review-meta-slot';O=R/'drain8172-original'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p))
note='docs/SIX_AXIS_POINT_SENSITIVITIES_FINITE_ISLAND_HEALING_AND_DIRECTED_RECURRENCE_BOUNDS_BOUNDED_THEOREM_NOTE_2026-09-16.md';runner='scripts/six_axis_point_sensitivities_finite_island_healing_directed_recurrence_bounds_2026_09_16.py';archive='docs/work_history/repo/review_feedback/pr8172-evidence'
oldnote=(W/note).read_text();newnote=oldnote.replace('*The eroder bound* (block 12\'s S2, re-proved).','*The eroder bound.*')
(W/note).write_text(newnote)
p=W/archive/'README.md';s=p.read_text().replace('This archive does not overwrite','The original tar headers use group-writable permissions (for example 0664), while the inventory preserves the original Git modes (for example 100644). After extraction, restore each file mode from its inventory entry; the original tar bytes are unchanged. This archive does not overwrite');p.write_text(s)
p=W/archive/'DEFERRED_SCIENCE.md';s=p.read_text();head,raw=s.split('## Complete raw block28 outputs, unchanged',1)
for a,b in [('seed1','seed 1'),('seed2','seed 2'),('seed3','seed 3'),('seed31','seed 31'),('seed4','seed 4'),('seed28','seed 28'),('L128','L = 128'),('L256','L = 256'),('L16','L = 16'),('L24','L = 24'),('L32','L = 32'),('L64','L = 64'),('/T4000',' / T = 4000'),('/T8000',' / T = 8000'),('/1500',' / 1500'),('/2000',' / 2000'),('no3.6','no 3.6'),('or3.7','or 3.7'),('no3.7','no 3.7'),('has2,','has 2,'),('has3.5','has 3.5'),('has3.6','has 3.6'),('scan9,','scan 9,'),('side1,','side 1,'),('has16','has 16'),('has3.','has 3.'),('above1','above 1'),('loose18','loose 18'),(',300',', 300'),('and200','and 200'),('and120','and 120'),('PR8170','PR 8170'),('PR8171','PR 8171')]:head=head.replace(a,b)
p.write_text(head+'## Complete raw block28 outputs, unchanged'+raw)
p=W/runner;s=p.read_text();decl={n.targets[0].id:n for n in ast.parse(s).body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name)};n=decl['EXPECTED_INPUT_SHA256'];pins=ast.literal_eval(n.value);pins[note]=sha(W/note);lines=s.splitlines(True);lines[n.lineno-1:n.end_lineno]=['EXPECTED_INPUT_SHA256 = '+repr(pins)+'\n'];s=''.join(lines).replace("block 01's note (on main)","the finite-window product-rule note");s=s.rstrip()+'\n';p.write_text(s)
compile(ast.parse(s),runner,'exec')
inv=json.loads((O/'inventory.json').read_text());oldnp=next(Path(e['original']['snapshot']) for e in inv['paths'] if e['path'].startswith('docs/') and e['path'].endswith('.md'));oldrp=next(Path(e['original']['snapshot']) for e in inv['paths'] if e['path'].startswith('scripts/'))
(R/'drain8172-author-correction-v2.diff').write_text(''.join(difflib.unified_diff(oldnp.read_text().splitlines(True),newnote.splitlines(True),fromfile=str(oldnp),tofile=note))+''.join(difflib.unified_diff(oldrp.read_text().splitlines(True),s.splitlines(True),fromfile=str(oldrp),tofile=runner)))
maprows=json.loads((R/'drain8172-author-full-mapping-v1.json').read_text())
for e in maprows:
 if e['final_path']:e['final_sha256']=sha(W/e['final_path'])
(R/'drain8172-author-full-mapping-v2.json').write_text(json.dumps(maprows,indent=2)+'\n')
sys.path[:0]=[str(W/'scripts'),str(W/'docs/audit/scripts')]
import runner_cache as c,audit_packet_script_deps as a,build_citation_graph as g
cid=g.claim_id_from_path(W/note);ins=list(c.declared_input_paths(W/runner));assert ins==list(pins) and all(sha(W/p)==pins[p] for p in ins)
helpers=list(g.helper_runner_paths_for_claim(cid,runner));packet=list(a.helper_runner_paths_for_claim(cid,Path(runner).stem));trans=list(a.transitive_helpers(Path(runner).stem));resolved=list(g.resolve_helper_runner_paths(runner));assert not any([helpers,packet,trans,resolved]);assert c.declared_timeout_for(W/runner)==900
cites=sorted(p.relative_to(W).as_posix() for p in g.extract_citations(newnote,W/note));assert cites==sorted(ins[1:]+[archive+'/README.md'])
metadata=dict(status='ACTUAL METADATA APIS ONLY; NO SCIENCE EXECUTION',claim_id=cid,note=note,runner=runner,helpers=helpers,packet_helpers=packet,transitive_helpers=trans,resolved_helpers=resolved,citations=cites,ordered_inputs=[dict(path=p,sha256=sha(W/p)) for p in ins],parents=ins[1:],timeout=900,memory_mb=768,input_fingerprint=c.declared_input_fingerprint(W/runner),registry_edits_needed=False)
(R/'drain8172-author-discovery-v1.json').write_text(json.dumps(metadata,indent=2)+'\n')
context=['docs/ADMISSIBILITY_RULE_STATIC_SIX_AXIS_REFLECTION_IDENTITIES_AND_CONDITIONAL_CONTOUR_BOUNDS_BOUNDED_THEOREM_NOTE_2026-09-15.md','docs/ADMISSIBILITY_RULE_CUBIC_WALK_RETURN_SUM_AND_SPHERE_STATIC_MAGNETIZATION_SUFFICIENT_BOUND_BOUNDED_THEOREM_NOTE_2026-09-15.md','docs/ADMISSIBILITY_RULE_THREE_DIMENSIONAL_FORMATION_LAW_ORDERED_PHASE_STABILITY_OF_THE_NOISY_LEVEL_AUTOMATON_EXPLICIT_THRESHOLD_SIX_INVARIANT_LAWS_BOUNDED_THEOREM_NOTE_2026-09-16.md']
tree=ast.parse(s);decl={n.targets[0].id:n.value for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name)};checks=[n.args[0].value for n in ast.walk(tree) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and n.func.attr=='check' and n.args and isinstance(n.args[0],ast.Constant)];assert len(checks)==11
resource=dict(runner=dict(path=runner,sha256=sha(W/runner)),ordered_inputs=metadata['ordered_inputs'],mathematical_parents=[dict(path=p,sha256=sha(W/p),role='Framework/menu/product conditional vocabulary; no phase or coupling theorem imported') for p in ins[1:]],mathematical_closure='Full exact finite conditional enumeration and majority deviations; full eroder/noise coupling with explicit recenter and original complete polynomial count; full supplied nonnegative recurrence comparison. Standard finite counting, induction and union bound only. No simulation data or unlanded sphere contraction premise.',context_only=[dict(path=p,sha256=sha(W/p)) for p in context],timeout_sec=900,proposed_external_process_tree_limit_bytes=768*1024*1024,source_basis='Inherited900-second primary cap; three finite sensitivities (216 triples times5 alternatives times6 outputs), original300 seeded islands in [-4,4]^2 and original120 region counts, six translated examples, fixed symbolic polynomial, six-step recurrence. Original fixtures unchanged; no lattice simulation or large arrays. 768MiB symbolic/import headroom proposed, unmeasured. Preserve any resource failure.',json_output='logs/runner-cache/'+Path(runner).stem+'.json',mutation_json_pattern='logs/runner-cache/'+Path(runner).stem+'--<mutation>.json',stdout='logs/runner-cache/'+Path(runner).stem+'.txt',checks_source_derived_not_executed=checks,mutation_names=ast.literal_eval(decl['MUTATION_GATE']),mutation_status='Eight pending current mathematical mutations (six originals plus two correction-specific); two original prose-policy mutations retired but preserved exactly in historical source. No outcomes claimed.',primary_executions=0,simulation_executions=0)
(R/'drain8172-author-input-resource-plan-v1.json').write_text(json.dumps(resource,indent=2)+'\n')
paths=subprocess.check_output(['git','-C',str(W),'ls-files','--others','--exclude-standard'],text=True).splitlines();assert set(paths)=={note,runner}|{p.relative_to(W).as_posix() for p in (W/archive).rglob('*') if p.is_file()};assert len(paths)==31
freeze=[];dest=R/'drain8172-prepared-v1-source';assert not dest.exists()
for path in paths:
 p=W/path;q=dest/path;q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,q);freeze.append(dict(path=path,sha256=sha(p),mode=oct(p.stat().st_mode&0o777),immutable_copy=str(q)))
(R/'drain8172-prepared-v1-source-freeze.json').write_text(json.dumps(dict(files=freeze),indent=2)+'\n')
prepared=dict(status='UNTRACKED AUTHOR PREPARATION; ORIGINAL REVIEWER CONFIRMATION PENDING',owner='PR8172-author',base=inv['current_main'],original_head=inv['head'],original_merge_base=inv['merge_base'],notes=[dict(path=note,sha256=sha(W/note))],runners=[dict(path=runner,sha256=sha(W/runner))],archive_manifest=dict(path=archive+'/archive-manifest.json',sha256=sha(W/archive/'archive-manifest.json')),deferred_science=dict(path=archive+'/DEFERRED_SCIENCE.md',sha256=sha(W/archive/'DEFERRED_SCIENCE.md')),source_files=len(paths),originals=24,inherited_packet_entries=79,branch_retention_required=True,primary_runs=0,mutations=0,simulations=0,staged=False,original_report=ref(R/'drain8172-review-original.json'))
(R/'drain8172-author-prepared-v1.json').write_text(json.dumps(prepared,indent=2)+'\n')
print(json.dumps(prepared,indent=2));print('prepared SHA',sha(R/'drain8172-author-prepared-v1.json'));print('freeze SHA',sha(R/'drain8172-prepared-v1-source-freeze.json'))
