import pathlib,json,hashlib,subprocess,sys
r=pathlib.Path('/private/tmp/review-drain-20260915');w=r/'review-meta-slot';root=r/'drain8153-originals/8153';sha=lambda b:hashlib.sha256(b).hexdigest()
u=next(x for x in json.loads((r/'drain8153-original-inventory.json').read_text())if x['number']==8153)
def git(*a):return subprocess.check_output(['git','-C',str(w),*a])
assert json.loads((r/'drain8153-review-head-check.json').read_text())['headRefOid']==u['headRefOid']
assert set(git('diff','--name-only',u['delta_base'],u['headRefOid']).decode().splitlines())=={x['path']for x in u['original_paths']}
rows=[]
for x in u['original_paths']:
 b=git('show',u['headRefOid']+':'+x['path']);mode,typ,blobpath=git('ls-tree',u['headRefOid'],'--',x['path']).decode().split(None,2);blob=blobpath.split('\t')[0];assert mode==x['mode'] and blob==x['blob'] and sha(b)==x['sha256']
 role='historical context and author evidence; preserve exact full bytes, no author verdict imported'
 if x['path'].startswith('docs/audit/'):role='generated citation manifest; exclude as authority, preserve historical bytes, regenerate only from accepted source'
 elif x['path'].startswith('docs/'):role='original theorem/proof; Gaussian-domination reproof and transverse/physical interpretation fail source review; preserve whole proof and branch; narrow positive salvage pending'
 elif x['path'].startswith('scripts/'):role='primary symbolic controls; preserve original; no proof of Gaussian domination or infinite-volume identification'
 elif x['path'].startswith('logs/'):role='historical17/0 cache; not evidence for missing infinite-volume proof; preserve and supersede only after affected source capture'
 rows.append(dict(x,disposition=role,recovery=u['headRefOid']+':'+x['path']))
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')]
import runner_cache as c,build_citation_graph as g,audit_packet_script_deps as p
runner=next(root/x['path']for x in rows if x['path'].startswith('scripts/'));note=next(root/x['path']for x in rows if x['path'].startswith('docs/')and x['path'].endswith('.md'));p.SCRIPTS_DIR=root/'scripts'
inputs=[]
for name in c.declared_input_paths(runner):
 f=root/name if (root/name).exists()else w/name;inputs.append(dict(path=name,sha256=sha(f.read_bytes()),source=str(f)))
context=[]
for path in ['docs/MINIMAL_AXIOMS_2026-06-29.md','docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/audit/data/axiom_premise_nodes.json','docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md']:
 context.append(dict(path=path,sha256=sha((w/path).read_bytes()),read_scope='current authority, exact source reused from same-session premise review; no statistical or phase grant'))
findings=[
{'id':'F1','target':'G2 Gaussian domination','finding':'Shifted spins are not unit: claimed exp(-beta|u-v|²/2)=exp(-beta)exp(beta u.v) is false. Correct norm factors are necessary. G1 positivity on sphere and informal repeated reflections do not establish the asserted extremum for arbitrary twist.','repair':'Use a precise Gaussian-domination theorem import with all hypotheses/normalization, or supply corrected proof. Remove arbitrary site-factor extension unless its actual symmetry hypotheses are proved.'},
{'id':'F2','target':'lead/trace/G5/N1–N8','finding':'Universal formation/discrete-model exclusions, only-candidate and gravity identification are unsupported; corrected8147 auxiliary Gaussian and8151 conditional phase scope do not imply them. Four N1 routes including unattempted/out-of-target cases and asserted N2 independence are not negative certification.','repair':'Withdraw negative/physical classification; retain supplied-model positive bounds and explicitly deferred obligations.'},
{'id':'F3','target':'G4/G5','finding':'Zero-field finite torus is O(3) invariant with equal components; no selected magnetization direction or extremal ordered-state transverse correlation is proved. Momentum comparability alone does not prove pointwise real-space1/r.','repair':'State zero-field component Fourier bounds, finite-volume magnetization-square liminf and explicit momentum sequences only.'},
{'id':'F4','target':'G1/G2 Fourier','finding':'Reflection form needs real F or conjugation. Self-inverse momentum has cos norm N, sine0 and requires separate same-bound calculation, not merely a strengthening claim.','repair':'State Hermitian/real scope and compute self-inverse case explicitly.'},
{'id':'F5','target':'G3/G5 limits','finding':'Integrability alone does not justify singular Riemann sums; use lattice shell count near0. A subsequence attaining magnetization liminf does not establish global structure-factor liminf.','repair':'Use N^-1 sum_{0<|k|<=delta}1/E<=Cdelta+O(1/L); apply all-N root bound with eventual M_N²>=M²-eta, k_N→k≠0.'},
{'id':'F6','target':'birth-kernel comparison','finding':'(1+t)/2 has nonnegative Legendre coefficients1/2,1/2,0,...; it is positive semidefinite, with missing strict positivity.','repair':'Remove assertion of failure of positivity/RP; distinguish degeneracy.'}]
refs=[]
for path in ['drain8153-original-inventory.json','drain8153-pr8153-original.patch','drain8153-review-head-check.json','drain8153-review-acquire.json','check8153/controls-before-fix.py','check8153/control-attempt1.json','check8153/controls.py','check8153/controls.json']:
 refs.append(dict(path=str(r/path),sha256=sha((r/path).read_bytes())))
o=dict(status='ORIGINAL REVIEW COMPLETE; MATERIAL FINDINGS; AUTHOR SALVAGE PENDING',reviewer='/root/review_8011',unit=8153,head=u['headRefOid'],delta_base=u['delta_base'],current_main=git('rev-parse','HEAD').decode().strip(),original_dispositions=rows,read_coverage='Complete canonical note and runner, changed historical proof/review/state text, both independent historical control scripts and outputs. Inherited campaign material is historical context previously read in this session, not authority; all complete original files identity-verified and retained. Current possibility parent supplies conditional representation definitions, not formation/statistical selection or phase claims.',findings=findings,actual_api=dict(type=g.extract_claim_type_hint(note.read_text()),timeout=c.declared_timeout_for(runner),graph_helpers=list(g.resolve_helper_runner_paths(str(runner))),packet_helpers=sorted(p.transitive_helpers(runner.stem)),runtime_inputs=inputs),context=context,independent_controls=json.loads((r/'check8153/controls.json').read_text()),external_methods={'url':'https://www.math.ucla.edu/~biskup/PDFs/papers/Prague-School.pdf','author':'Marek Biskup','title':'Reflection Positivity and Phase Transitions in Lattice Spin Models','local_pdf_sha256':'bba0f0c68a11e5d3125e57f6f8ba3f62af1b0c05093916d46a160a11c324632e','read_scope':'Theorem4.6 and proof, printedpp40–41/PDFpages39–40, infrared derivation Eqs4.16–4.29. Primary source consulted to verify actual Gaussian-domination hypotheses. Full third-party text remains local.','mapping':'Identical compact single-site measure uniform S², even periodic NN torus, ordered normalized NN J=1/6, source parameter b=3beta/2, h=-phi e gives beta/2 times unordered gradient energy. This is a real mathematical import if used; do not label reference-only.'},current_main_loss='Review checkout unchanged. New canonical source must not replace current parent or campaign histories. Archive complete original histories and generated manifest as historical evidence; generated manifest is not authority. Current corrected8147 and8151 do not support original universal comparative claims.',salvage='Legendre positivity, correctly imported finite Gaussian domination and infrared bound, sum rule and controlled magnetization-square liminf, zero-field Bogoliubov finite identity/root bound and explicit momentum-sequence sandwich. No extremal transverse-state/real-space/gravity identification or universal candidate exclusion.',references=refs,execution='No primary executed. One independent control first failed due complex abs-squared rounding, preserved; corrected exact squared-norm control58/0 in0.00104sec. Original cap900sec; author final contract pending.',final_source_verdict='NOT YET PASS; affected author correction required')
p=r/'drain8153-original-review.json';assert not p.exists();p.write_text(json.dumps(o,indent=2)+'\n');(r/'drain8153-original-review.md').write_text('# PR8153 original review\n\nThe original source does not pass: the shifted-spin Gaussian identity is false, the extremization proof is incomplete, and zero-field component bounds are promoted to unsupported transverse/physical and universal exclusion claims.\n\nUseful supplied-model bounds remain available with a precise Gaussian-domination import, explicit finite-volume and momentum limits, and withdrawal of negative certification. All22 original paths and inputs are bound in the JSON. Independent controls passed58/0 after a preserved control-only numerical-fixture correction; no primary was executed.\n');print(sha(p.read_bytes()))
