from pathlib import Path
import json,hashlib,ast,subprocess,shutil,difflib,os,sys,gzip,re
R=Path('/private/tmp/review-drain-20260915');W=R/'author-draft-slot';old=json.loads((R/'drain8171-author-prepared-v1.json').read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
run=W/old['primaries'][0];before=run.read_text();after=before.replace('"certified", "converge", "emergent"','"certified", "emergent"');assert before!=after
run.write_text(after);compile(after,str(run),'exec')
# Remove only an obsolete lexical ban conflicting with the compact-Feller proof's ordinary mathematical convergence term.
rows=[];snap=R/'drain8171-prepared-source-v2';assert not snap.exists()
for x in old['source']:
 p=W/x['path'];rows.append(dict(path=x['path'],mode=x['mode'],sha256=sha(p.read_bytes())));(snap/x['path']).parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,snap/x['path'])
new={**old,'source':rows,'snapshot':str(snap),'supersedes':'drain8171-author-prepared-v1.json','revision':2,'narrow_v2_change':'Remove obsolete forbidden-word converge from packaging list; compact-Feller weak convergence is legitimate mathematical prose. No arithmetic, fixtures, note or input pins changed.'}
for name,data in [('drain8171-author-prepared-v2.json',new),('drain8171-source-freeze-v2.json',dict(schema_version=1,base=new['base'],source=rows))]:
 p=R/name;assert not p.exists();p.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
(R/'drain8171-author-corrections-v2.patch').write_text((R/'drain8171-author-corrections-v1.patch').read_text()+''.join(difflib.unified_diff(before.splitlines(True),after.splitlines(True),fromfile='prepared-v1/'+old['primaries'][0],tofile='prepared-v2/'+old['primaries'][0])))
# Only repository metadata APIs are imported. Primary remains unexecuted.
os.chdir(W);sys.path[:0]=[str(W/'scripts'),str(W/'docs/audit/scripts')];import runner_cache as c;import audit_packet_script_deps as a;import build_citation_graph as g
note=W/old['canonical_notes'][0];body=note.read_text();tree=ast.parse(after);constants={n.targets[0].id:ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ['FORBIDDEN','FENCES','N5_LINES','INPUT_SHA256']}
assert not [x for x in constants['FORBIDDEN'] if x in body]
assert all(x in body for x in constants['FENCES']);assert all(len(x.split(':',1)[1].strip())>=40 for x in constants['N5_LINES'])
inputs=list(c.declared_input_paths(run));assert all(sha((W/p).read_bytes())==constants['INPUT_SHA256'][p] for p in inputs)
manifest=json.loads((W/old['original_manifest']['path']).read_text());assert len(manifest['entries'])==18
for e in manifest['entries']:assert sha(gzip.decompress((W/e['recovery']['path']).read_bytes()))==e['sha256']
assert not subprocess.check_output(['git','diff','--name-only'],text=True);assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True)
assert set(subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines())=={x['path'] for x in rows}
api=dict(schema_version=1,kind='read-only-source-discovery-not-execution',base=new['base'],primary=old['primaries'][0],primary_sha256=sha(run.read_bytes()),runtime_inputs=[dict(path=p,sha256=sha((W/p).read_bytes()),role='proof source' if p==old['canonical_notes'][0] else 'framework authority' if 'MINIMAL_AXIOMS' in p else 'context only, not mathematical premise') for p in inputs],input_fingerprint=c.declared_input_fingerprint(run),declared_timeout=c.declared_timeout_for(run),packet_transitive_helpers=sorted(a.transitive_helpers(run.stem)),graph_helpers=g.helper_runner_paths_for_claim(g.claim_id_from_path(old['canonical_notes'][0]),old['primaries'][0]),citations=[str(p.relative_to(W)) for p in g.extract_citations(body,note)],graph_primary=g.extract_runner(body,old['canonical_notes'][0]),mathematical_dependencies=['docs/MINIMAL_AXIOMS_2026-06-29.md'],mathematical_imports=['countable products and iterated kernels on standard Borel spaces','compact metrizable countable product of spheres','weak sequential compactness of probability laws on compact metric spaces','uniform density of continuous cylinder functions','finite marginal determination'],registry_changes_required=False,primary_imported=False,primary_executed=False,static_compile=True,original_archives_verified=18,tracked_and_index_clean=True)
(R/'drain8171-source-input-discovery-v2.json').write_text(json.dumps(api,indent=2,ensure_ascii=False)+'\n')
plan=dict(schema_version=1,kind='proposed-resource-and-execution-contract-not-execution',primary=old['primaries'][0],timeout_seconds=60,memory_limit_bytes=384*1024*1024,limits_status='proposed unmeasured for corrected source; requires original reviewer confirmation and root dispatch',historical_measurement=dict(original_timeout_seconds=900,elapsed_seconds=0.55,source='original archived cache; original runner and original inputs only',peak_memory_bytes=None),cost=dict(symbolic='Three one-dimensional exponential integrals, derivatives/simplifications in at most six symbolic scalar variables, 3x3 matrices, one power series to order26 and one to order8.',rational='10+6+5 finite scalar enclosures; largest exponential argument144, default Taylor n=330; linear scalar Fraction accumulation, no exponential-size arrays.',imports='SymPy imported once; no local helper or simulator imports; top-level sqrt enclosure only.',memory='No large arrays or lattice configurations; interpreter and symbolic expression management dominate. 384MiB watchdog is proposed, not measured peak or proven bound.'),expected_completed_checks=16,count_scope='A4+B4+C2+D1+F4+G1; finite symbolic/rational and packaging checks, not infinite-plane execution',stdout=True,json_outputs=[],other_output_writes=[],cache_destination=f'logs/runner-cache/{run.stem}.txt',mutations='10 existing mutation routes available; historical census only; any future mutation dispatch is root-owned',no_primary_run=True)
(R/'drain8171-resource-plan-v2.json').write_text(json.dumps(plan,indent=2,ensure_ascii=False)+'\n')
print(json.dumps({k:sha((R/k).read_bytes()) for k in ['drain8171-author-prepared-v2.json','drain8171-source-freeze-v2.json','drain8171-source-input-discovery-v2.json','drain8171-resource-plan-v2.json']},indent=2))
