from pathlib import Path
import hashlib,json,subprocess,sys,re,gzip,ast
r=Path('/private/tmp/review-drain-20260915');w=r/'drain-author-slot';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));bind=lambda ps:[dict(path=p,sha256=sha(w/p)) for p in sorted(set(ps))];git=lambda *a:subprocess.check_output(['git','-C',str(w),*a],text=True).strip();d=json.load(open(r/'drain8161-author-prepared-v2.json'));original=next(x for x in json.load(open(r/'drain-next-topology-wave10-details.json')) if x['number']==8161);m=json.load(open(w/'docs/work_history/review_loop/pr8161/original-manifest.json'));disps=[]
for e in m:
 assert hashlib.sha256(gzip.decompress((w/e['stored']).read_bytes())).hexdigest()==e['sha256'];disps.append(dict(original_path=e['path'],original_sha256=e['sha256'],final_path=e['stored'],final_sha256=sha(w/e['stored']),disposition='Complete original bytes retained. Four final proofs canonicalized without mathematical/domain/tolerance changes; characteristic identity kept as owned current supporting proof; working lemmas mapped to final proofs and all limitations preserved. Historical program/results and30 mutation failures remain historical.',recovery=e['recovery']))
assert len(disps)==47
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as a,runner_cache as c
notes=[];context=[];parents=[];helpers=[];primaries=[];apis=[]
for p in d['notes']:
 body=(w/p).read_text();primary=re.search(r'^runner: (.+)$',body,re.M)[1];primaries.append(primary);cites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/p));context+=cites;hp=g.helper_runner_paths_for_claim(g.claim_id_from_path(w/p),primary);helpers+=hp;deps=d['load_bearing_dependencies'][p];assert set(deps)<=set(cites)
 if p==d['notes'][3]:assert not set(cites)&set(d['notes'][:3])
 notes.append(dict(path=p,claim_id=g.claim_id_from_path(w/p),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type='bounded_theorem',primary_runner=primary,helpers=hp,citations=cites,repository_dependencies=deps,dependency_rationale='Explicit supplied model/reference, complete written proof and identified mathematical imports. Linked prior canonical proofs used only where declared. Coupled-resolvent reference/proof independently defined; comparison names are not graph dependencies.'))
 parents+=deps
for p in d['runners']:
 ast.parse((w/p).read_text());ins=list(c.declared_input_paths(w/p));assert ins and all((w/x).is_file() for x in ins);context+=ins
 apis.append(dict(primary=p,timeout=c.declared_timeout_for(w/p),declared_inputs=ins,declared_input_fingerprint=c.declared_input_fingerprint(w/p),cache_status=c.cache_status(w/p),packet_transitive_helpers=list(a.transitive_helpers(Path(p).stem))))
assert set(primaries+helpers)==set(d['runners']);assert d['supporting_proof'] in c.declared_input_paths(w/d['runners'][0])
api=r/'drain8161-author-cache-api-v1.json';assert not api.exists();api.write_text(json.dumps(apis,indent=2)+'\n');review=ref(r/'drain8161-original-review.json');refs=[review,ref(r/'drain8161-authority-read-appendix.json'),ref(r/'drain8161-independent-controls.json'),ref(r/'drain8161-early-affected-fix-confirmation-v2.json')];paths=git('diff','--cached','--name-only').splitlines();assert len(paths)==61
h=r/'drain8161-author-source-handoff-v1.json';report=dict(status='AUTHOR DRAFT; ORIGINAL COLD CONFIRMATION REQUIRED',author='/root/resume_8077',base=git('rev-parse','HEAD'),tree=git('write-tree'),original_dispositions=disps,claim_dispositions=dict(final_proofs='All four complete original supplied-model proofs preserved; no new physical conclusions.',supporting_proof='Unique bounded characteristic-function identity remains current source owned by Gauss-dressing note, literal primary input and transitively loaded by vertex helper.',working_lemmas='Affine topology/overlap/moment/cluster/compression retained in full Gauss proof; centered-sector/gradient difference in vertex proof; Ward/denominator/node-count in resolvent proof. Exact working originals retained.',negative_scope='Five alternative physical routes explicitly OPEN, not a closed N1 certificate. Reference inverse-domain result and fixed-probe identity remain narrowly stated.',evidence='All original numerical domains/tolerances unchanged. Completed family totals4/3/2/3/3; no claim of counting assertion invocations. Finite-cutoff discrepancy, leakage and phase blindness remain visible.'),preservation='59 owned additions plus exactly2 additive helper-map changes on current main; existing8025/26/27 mappings preserved.47originals decoded/hash verified.',execution_plan=dict(timeouts=d['timeouts_seconds'],process_tree_rss_limit_bytes=d['proposed_external_memory_cap_bytes'],concurrency=1,cost_review=d['resource_assessment'],state='No author primary/control execution; root dispatch after cheap and original cold.'),references=refs+[ref(api)]);assert not h.exists();h.write_text(json.dumps(report,indent=2)+'\n');hr=ref(h)
p=d['supporting_proof'];pcites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations((w/p).read_text(),w/p));context+=pcites+d['notes']+['docs/MINIMAL_AXIOMS_2026-06-29.md','docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md','docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md'];tooling=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
record=dict(schema_version=2,unit_id='PR8161',constituents=[dict(id='PR8161',head=original['headRefOid'],delta_base=original['delta_base'],dispositions=dict(hr,json_pointer='/original_dispositions'))],source=dict(base=git('rev-parse','HEAD'),commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),inputs=dict(runtime=bind(d['runners']+[p]),helpers=bind(helpers),parents=bind(parents),context=bind(context),tooling=bind(tooling)),reviewer=dict(session='/root/review_8161 original session; final affected-source confirmation pending',report=review,references=[hr,ref(api)]+refs[1:]),notes=notes,supporting_proofs=[dict(path=p,canonical_note=d['notes'][0],citations=pcites,rationale='Full current bounded characteristic-function proof at fixed local probes/g, reviewed as unique original science under Gauss-dressing model; no autonomous claim or broad infrared no-go.',review_reference=review)],non_science_notes=[dict(path='docs/work_history/review_loop/pr8161/README.md',rationale='Historical original recovery/working-argument mapping, not autonomous scientific authority.',review_reference=review)])
f=r/'drain8161-author-unit-draft-v1.json';assert not f.exists();f.write_text(json.dumps(record,indent=2)+'\n');print(ref(f));print(record['source']['tree'])
