from pathlib import Path
import json,hashlib,subprocess,sys,re
r=Path('/private/tmp/review-drain-20260915');w=r/'drain-author-slot';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:dict(path=str(p),sha256=sha(p));bind=lambda ps:[dict(path=p,sha256=sha(w/p)) for p in sorted(set(ps))];git=lambda *a:subprocess.check_output(['git','-C',str(w),*a],text=True).strip()
o=json.loads((r/'drain8147-original-review.json').read_text());i=o['original_inventory'];mapping=json.loads((w/'docs/work_history/review_loop/pr8147/original-manifest.json').read_text());disps=[]
for e in mapping:
 p=e['archive'];disps.append(dict(original_path=e['path'],original_sha256=e['sha256'],final_path=p,final_sha256=sha(w/p),disposition='Complete original version preserved byte-exact in deterministic gzip. Live scientific note renamed/narrowed; broad original negative claims deferred, literal-parent and sphere identities corrected; original branch remains recovery handle.',recovery=i['head']+':'+e['path']))
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')];import build_citation_graph as g,audit_packet_script_deps as a,runner_cache as c
p='docs/ADMISSIBILITY_RULE_DIRECTED_GAUSSIAN_PROPAGATOR_OVERLAP_COVARIANCE_GAIN_BOUNDS_BOUNDED_THEOREM_NOTE_2026-09-15.md';body=(w/p).read_text();primary=re.search(r'^runner: (.+)$',body,re.M)[1];cites=sorted(x.relative_to(w).as_posix() for x in g.extract_citations(body,w/p));deps=['docs/MINIMAL_AXIOMS_2026-06-29.md','docs/ADMISSIBILITY_RULE_HERMITIAN_GAUSSIAN_INSTANCE_FORMATION_PRECISION_LDL_BOUNDED_THEOREM_NOTE_2026-09-07.md'];assert all(x in cites for x in deps);assert not a.transitive_helpers(Path(primary).stem)
inputs=c.declared_input_paths(w/primary);api=r/'drain8147-author-cache-api-v2.json';api.write_text(json.dumps(dict(primary=primary,primary_sha256=sha(w/primary),timeout=c.declared_timeout_for(w/primary),declared_inputs=list(inputs),declared_input_fingerprint=c.declared_input_fingerprint(w/primary),cache_status=c.cache_status(w/primary),helpers=[]),indent=2)+'\n')
notes=[dict(path=p,claim_id=g.claim_id_from_path(w/p),declared_claim_id=re.search(r'^claim_id: (.+)$',body,re.M)[1],claim_type='bounded_theorem',primary_runner=primary,helpers=[],citations=cites,repository_dependencies=deps,dependency_rationale='Axiom context does not supply the real Gaussian fixture or value translations. Actual finite Hermitian parent supplies conditional mean and triangular algebra only; literal +1/2 edge sign, complex carrier and finite 2D scope explicitly distinguished.')]
paths=git('diff','--cached','--name-only').splitlines();context=cites+list(inputs)+[x['path'] for x in o['context_inputs']];tools=['docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/axiom_premise_nodes.json','docs/audit/data/doc_authority_registry.json']
report={'status':'AUTHOR DRAFT ONLY; INDEPENDENT COLD SOURCE CONFIRMATION REQUIRED; NO SCIENTIFIC PASS','author':'/root/resume_8077','base':git('rev-parse','HEAD'),'tree':git('write-tree'),'original_dispositions':disps,'claim_dispositions':{'T1':'Retain exact propagator and accumulated overlap covariance.','T2':'Retain finite-level gain bounds and explicit subcritical stationary innovation construction; defer uniqueness/all-stationary nonexistence conclusions.','T3':'Retain exact precision symbol/cosine-entry distinction, critical directional expansions and directed/undirected walk identity with series bounds; defer all-causal kernel exclusion.','T4':'Retain binomial identities/bounds, correct n>=1 in square-root lower sum.','T5':'Additional value symmetry only; critical stable gain not zero-symbol iff; log curvature maximum and auxiliary flat Gaussian, actual Born sphere moments; literal parent sign +1/2 vs separate3Dreal−1/2 fixture; candidate precision evaluation only.','negative_certificate':'Broad exclusions deferred across live titles/claims/proofs/falsifiers; original full proofs and controls archived byte-exact. Original branch must remain.'},'source_preservation':'All22 original versions verified by decompressed SHA; 18 history paths including two real control programs/outputs retained. Currentbase files unchanged; additions only.','execution_plan':{'timeout_seconds':180,'process_tree_rss_limit_bytes':3221225472,'concurrency':1,'authorization':'No scientific execution before original reviewer cold confirmation and cheap preflight; root owns final capture.'},'checks':'AST syntax, exact-text fence/forbidden/placement scan and vocab0; no primary/control run, no cache restamp, no pipeline.','references':[ref(r/'drain8147-original-review.json'),ref(r/'drain8147-independent-controls.json'),ref(api)]}
rp=r/'drain8147-author-source-handoff-v2.json';rp.write_text(json.dumps(report,indent=2)+'\n');review=ref(r/'drain8147-original-review.json');rr=ref(rp)
rec={'schema_version':2,'unit_id':'PR8147','constituents':[dict(id='PR8147',head=i['head'],delta_base=i['delta_base'],dispositions=dict(rr,json_pointer='/original_dispositions'))],'source':dict(base=git('rev-parse','HEAD'),commit=git('rev-parse','HEAD'),tree=git('write-tree'),paths=bind(paths),deleted_paths=[]),'inputs':dict(runtime=bind([primary]),helpers=[],parents=bind(deps),context=bind(context),tooling=bind(tools)),'reviewer':dict(session='/root/review_8011 original scientific review; final confirmation pending',report=review,references=[rr,ref(api)]),'notes':notes,'supporting_proofs':[],'non_science_notes':[dict(path=x,rationale='Historical recovery instructions, no current scientific authority.',review_reference=review) for x in paths if x.endswith('.md') and x!=p]}
f=r/'drain8147-author-unit-draft-v2.json';f.write_text(json.dumps(rec,indent=2)+'\n');print(ref(f));print(report['tree']);print('paths',len(paths))
