import ast,hashlib,json,pathlib,shutil,subprocess,sys
sys.dont_write_bytecode=True
R=pathlib.Path('/private/tmp/review-drain-20260915');W=R/'review-draft-slot'
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
ref=lambda p:{'path':str(p),'sha256':h(p)}
def save(name,value):
 p=R/name
 with p.open('x') as f:json.dump(value,f,indent=2,ensure_ascii=False);f.write('\n')
 return p
D=json.loads((R/'drain8178-author-prepared-v1.json').read_text());V=json.loads((R/'drain8178-review-original.json').read_text())
sys.path[:0]=[str(W/'scripts'),str(W/'docs/audit/scripts')]
import runner_cache as c,build_citation_graph as g,audit_packet_script_deps as a
N=D['note'];P=D['runner'];cid=g.claim_id_from_path(W/N)
assert cid==D['claim_id'];assert g.extract_runner((W/N).read_text(),N)==P
helpers={'graph':g.helper_runner_paths_for_claim(cid,P),'packet':a.helper_runner_paths_for_claim(cid,pathlib.Path(P).stem),'graph_transitive':g.resolve_helper_runner_paths(P),'packet_transitive':sorted(a.transitive_helpers(pathlib.Path(P).stem))}
assert all(x==[] for x in helpers.values())
inputs=list(c.declared_input_paths(W/P));assert inputs==D['runtime_inputs']
fp=c.declared_input_fingerprint(W/P);assert fp and len(fp)==64
citations=sorted(p.relative_to(W).as_posix() for p in g.extract_citations((W/N).read_text(),W/N))
assert inputs[1] in citations
snap=R/'drain8178-current-context-v1';assert not snap.exists();snap.mkdir()
contextpaths=['docs/MINIMAL_AXIOMS_2026-06-29.md','docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/audit/data/axiom_premise_nodes.json','docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md','docs/audit/data/doc_authority_registry.json']
tooling=['scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','docs/audit/scripts/ledger_io.py']
skills=['docs/ai_methodology/skills/review-loop/SKILL.md']
# Preserve the actual repository routed skill revision when present.
skillbase=W/'docs/ai_methodology/skills/review-loop'
if not skillbase.exists():skillbase=W/'.claude/skills/review-loop'
if skillbase.exists():
 skills=[p.relative_to(W).as_posix() for p in sorted(skillbase.rglob('*.md'))]
else:skills=[]
records=[]
for p in dict.fromkeys(inputs+contextpaths+tooling+skills):
 q=snap/p;q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(W/p,q)
 records.append({'path':p,'sha256':h(W/p),'immutable_copy':str(q),'role':'runtime-mathematical-input' if p in inputs else 'tooling' if p in tooling else 'context-not-recursion-premise'})
contract={'stdout':'AUDIT_INPUT_PATHS, per-check PASS/FAIL, five N5 scope lines, TOTAL: PASS=n FAIL=n; mutations also expected/observed family','expected_baseline':'TOTAL: PASS=16 FAIL=0 (planned, not observed)','default_filesystem_output':None,'optional_sidecar':'AUDIT_RESULT_SIDECAR: absolute external per-attempt path; existing parent; exclusive creation; JSON contains passed, failed, failed_families, mutation, expected_mutation_family, input_sha256, scope','json_flag':'No --json contract; do not rerun for JSON','canonical_stdout_cache':'logs/runner-cache/'+pathlib.Path(P).stem+'.txt','preservation_requirement':'Future adapter must retain raw execute_runner return before runner_cache post-identity checks/cache publication; retain failed stdout/stderr/sidecar; no retry.'}
dis=save('drain8178-author-discovery-v1.json',{'base':D['base'],'note':N,'claim_id':cid,'actual_runner':P,'helpers':helpers,'resolved_citations':citations,'ordered_inputs':[{'path':p,'sha256':h(W/p)} for p in inputs],'actual_input_fingerprint':fp,'tooling':[{'path':p,'sha256':h(W/p)} for p in tooling],'context':records,'registry_edits_required':[],'output_contract':contract,'science_executions':0,'final_closure':False,'refresh_required':'Parent coordinator plans helper-map and review-skill main changes before batch cold freeze; compare then-current dependencies/tooling and obtain original same-session affected/cold review.'})
t=ast.parse((W/P).read_text());mutations=ast.literal_eval(next(n.value for n in t.body if isinstance(n,ast.Assign) and any(isinstance(a,ast.Name) and a.id=='MUTATION_GATE' for a in n.targets)))
assert len(mutations)==8
history=R/'check8178/primary-receipt.json';hist=json.loads(history.read_text())
plan=save('drain8178-author-input-resource-plan-v1.json',{'status':'proposed source plan only; future independent affected and cold clearance required','unique_primary_programs':1,'runner':{'path':P,'sha256':h(W/P)},'ordered_inputs':[{'path':p,'sha256':h(W/p)} for p in inputs],'helpers':[],'libraries':['Python standard library','Sympy'],'mathematical_premise_closure':'Complete finite recurrence, covariance, stationary-limit, residual, integer-crossing and finite-bracket proofs inline. Supplied L>=1, sigma2>0, gain-one P, iid real centered site/time noise with covariance sigma2 I and zero initial condition. Actual corrected sphere-kernel source supplies optional A(3beta)/(3beta) parameter and nonlinear observable distinction, not an exact gain-one nonlinear recursion. No simulations, static8173 result, archival claims, audit verdicts or new primitives are premises.','tooling':[{'path':p,'sha256':h(W/p)} for p in tooling],'limits':{'wall_seconds':60,'sampled_aggregate_process_tree_rss_bytes':384*1024*1024,'poll_interval_seconds':0.02,'on_violation':'terminate process group and preserve raw outputs; no implicit retry or cap raise'},'source_basis':'Original same fixed L<=4 exact covariance fixtures, beta<=48 enclosure arithmetic and S64 sum retained; four small exact controls added (16x16 fourth-root transform, tiny-torus residuals, rational ceiling fixtures). No stochastic loop or lattice-size extension. Original declared900-second timeout reduced to measured reviewer60-second policy, subject affected-review acceptance.','actual_original_measurement':{'receipt':ref(history),'elapsed_seconds':hist['elapsed'],'peak_rss_bytes':hist['peak_rss_bytes'],'wall_limit_seconds':hist['plan']['wall_limit_seconds'],'rss_limit_bytes':hist['plan']['rss_limit_bytes'],'applicability':'Original primary only; corrected code not run. Measurement is baseline resource evidence, not new success.'},'planned_checks':{'total':16,'mathematical':11,'metadata':5,'families':{'A':4,'B':2,'C':2,'D':3,'F':4,'G':1}},'declared_mutations':mutations,'future_changed_claim_controls':['fourier_sign_wrong','real_modes_independent_wrong','zero_start_stationary_wrong','integer_crossing_floor_wrong'],'original_mutations_reuse':'Original4 mathematical controls were independently executed in check8178; preserve those exact reports and review applicability instead of automatically rerunning. Original2 prose mutations are historical only. New4 mathematical controls require independent review and future once-only execution if accepted; no baseline rerun.','output_contract':contract,'scientific_execution_count':0,'branch_retention_required':True})
corrections={'8178-1':'Complete recurrence proof restricted to explicitly supplied auxiliary model; actual8170 mean gain and optional aligned variance source linked and pinned.','8178-2':'Negative Fourier multiplier; complete Hermitian covariance and real conjugacy proof; backward-series stationary-law limit with finite-second-moment hypotheses.','8178-3':'Exact finite residual and rho bound, slow O(L²) scale with selected mode, real tau and ceil crossing; no angular interpretation.','8178-4':'Complete finite bracket and all original finite arithmetic retained. Full sharper original argument readably deferred; no sharp asymptotic claimed.','8178-5':'All simulations and raw histories retained exactly; concrete contradictory rows explained. No calibration/size independence/nonlinear memory promotion.','8178-6':'Actual parent Markdown dependency and literal two-input APIs recognized; no helper or registry change. Fences replaced by four targeted mathematical controls, source independently pending.','8178-7':'All21paths and all available base/head/main identities plus delta recovered; complete original note readable; no certificate/no-go authority; branch retained.'}
find=save('drain8178-author-finding-dispositions-v1.json',{'findings':[{'original':x,'author_correction':corrections[x['id']],'independent_affected_confirmation':'pending'} for x in V['findings']],'original_review':ref(R/'drain8178-review-original.json'),'claim_dispositions':[{'claim':'supplied finite-torus mode/covariance/finite bracket','disposition':'live complete positive proof with explicit hypotheses; independent affected confirmation pending'},{'claim':'exact nonlinear gain-one linearization','disposition':'corrected; actual Cartesian mean gain A(3beta), normalized direction differs'},{'claim':'zero-start stationary nonzero modes/transient order V/angular memory time','disposition':'corrected to stationary limit/exact residual/variance scale and ceiling'},{'claim':'sharp logarithmic coefficient/additive constant/equality with infinite plane at L²','disposition':'deferred science; full original readable; proof required to reopen'},{'claim':'nonlinear size-independent diffusion and |m|²tau memory scale','disposition':'deferred science; raw data discrepancies and failed fits retained; observable-specific proof required'},{'claim':'estimator impossibility/formal negative certification','disposition':'not established; diagnostic attempts preserved, no fabricated routes'}]})
refs=[ref(R/n) for n in ['drain8178-author-prepared-v1.json','drain8178-prepared-v1-source-freeze.json','drain8178-author-full-mapping-v1.json','drain8178-author-preservation-v1.json','drain8178-author-correction-v1.diff','drain8178-author-discovery-v1.json','drain8178-author-input-resource-plan-v1.json','drain8178-author-finding-dispositions-v1.json','drain8178-review-original.json','drain8178-review-original.md']]
handoff=save('drain8178-author-handoff-v1.json',{'status':'PREPARED FOR ORIGINAL SAME-SESSION AFFECTED REVIEW; NOT COLD/FNAL CLEARANCE','owner':D['owner'],'base':D['base'],'original_head':D['original_head'],'source_files':D['source_files'],'original_count':21,'source_count':len(D['source_files']),'complete_proofs':'All live finite arguments present in full; original entire note verbatim in readable deferred appendix and exact gzip recovery. Full original delta and every available base/head/main state preserved.','references':refs,'actual_api_discovery':ref(dis),'resource_plan':ref(plan),'registry_changes':[],'science_executions':0,'staging':0,'gates':0,'branch_retention_required':True,'later_main_refresh_required':True})
assert not subprocess.check_output(['git','-C',str(W),'diff','--name-only','HEAD'],text=True).strip()
for x in D['source_files']:assert h(W/x['path'])==x['sha256']
print(json.dumps({'handoff':ref(handoff),'discovery':ref(dis),'resource_plan':ref(plan),'prepared':ref(R/'drain8178-author-prepared-v1.json')},indent=2))
