from pathlib import Path
import json,hashlib,ast,shutil,difflib,sys,subprocess,gzip
sys.dont_write_bytecode=True
R=Path('/private/tmp/review-drain-20260915');W=R/'drain-author-slot';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
prep=json.loads((R/'drain8170-author-prepared-v1.json').read_text());runner=prep['runners'][0]['path'];note=prep['notes'][0]['path'];rp=W/runner;before=rp.read_text();after=before.rstrip()+'\n';rp.write_text(after);rp.chmod(0o755)
patch=R/'drain8170-author-v1-to-v2.diff';assert not patch.exists();patch.write_text(''.join(difflib.unified_diff(before.splitlines(True),after.splitlines(True),fromfile='prepared-v1/'+runner,tofile='prepared-v2/'+runner)))
compile(after,runner,'exec');prep['runners'][0]['sha256']=sha(rp);prep['status']='UNTRACKED AUTHOR PREPARATION V2; ORIGINAL REVIEWER AFFECTED CONFIRMATION REQUIRED';prep['prior_preparation']=dict(path=str(R/'drain8170-author-prepared-v1.json'),sha256=sha(R/'drain8170-author-prepared-v1.json'))
def dump(n,v):
 p=R/n;assert not p.exists();p.write_text(json.dumps(v,indent=2)+'\n');return p
mapping=json.loads((R/'drain8170-author-full-mapping-v1.json').read_text())
for e in mapping:
 if e['final_path']==runner:e['final_sha256']=sha(rp)
dump('drain8170-author-full-mapping-v2.json',mapping)
freeze=json.loads((R/'drain8170-prepared-v1-source-freeze.json').read_text());snap=R/'drain8170-prepared-v2-source';assert not snap.exists();snap.mkdir()
for e in freeze['files']:
 p=W/e['path'];q=snap/e['path'];q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,q);e.update(sha256=sha(p),immutable_copy=str(q));assert e['mode']==oct(p.stat().st_mode&0o777)
dump('drain8170-prepared-v2-source-freeze.json',freeze);dump('drain8170-author-prepared-v2.json',prep)
oldm=json.loads((R/'drain8170-original/manifest.json').read_text());on=next(x['path'] for x in oldm['paths'] if x['path'].startswith('docs/ADMISSIBILITY'));orr=next(x['path'] for x in oldm['paths'] if x['path'].startswith('scripts/'))
diff=''.join(difflib.unified_diff((R/'drain8170-original/source'/on).read_text().splitlines(True),(W/note).read_text().splitlines(True),fromfile=on,tofile=note))+''.join(difflib.unified_diff((R/'drain8170-original/source'/orr).read_text().splitlines(True),after.splitlines(True),fromfile=orr,tofile=runner));(R/'drain8170-author-correction-v2.diff').write_text(diff)
sys.path[:0]=[str(W/'scripts'),str(W/'docs/audit/scripts')]
import runner_cache as c,audit_packet_script_deps as a,build_citation_graph as g
cid=g.claim_id_from_path(W/note);body=(W/note).read_text();assert g.extract_runner(body,note)==runner
helpers=list(g.helper_runner_paths_for_claim(cid,runner));packet=list(a.helper_runner_paths_for_claim(cid,Path(runner).stem));trans=list(a.transitive_helpers(Path(runner).stem));resolve=list(g.resolve_helper_runner_paths(runner));assert helpers==packet==trans==resolve==[]
tree=ast.parse(after);decl={n.targets[0].id:ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ['AUDIT_INPUT_PATHS','EXPECTED_INPUT_SHA256','AUDIT_TIMEOUT_SEC','AUDIT_MEMORY_MB','MUTATION_GATE']}
inputs=list(c.declared_input_paths(rp));assert inputs==list(decl['AUDIT_INPUT_PATHS']);assert decl['EXPECTED_INPUT_SHA256']=={p:sha(W/p) for p in inputs};assert c.declared_timeout_for(rp)==900
cites=sorted(x.relative_to(W).as_posix() for x in g.extract_citations(body,W/note));parents=inputs[1:];assert set(cites)==set(parents+['docs/work_history/repo/review_feedback/pr8170-evidence/README.md'])
dis=dump('drain8170-author-discovery-v2.json',dict(status='ACTUAL METADATA APIs ONLY; NO SCIENCE EXECUTION',claim_id=cid,note=note,runner=runner,helpers=helpers,packet_helpers=packet,transitive_helpers=trans,resolved_helpers=resolve,ordered_inputs=[dict(path=p,sha256=sha(W/p)) for p in inputs],input_fingerprint=c.declared_input_fingerprint(rp),timeout=900,memory_mb=768,citations=cites,parents=parents,registry_edits_needed=False))
context=['docs/ADMISSIBILITY_RULE_THREE_DIMENSIONAL_FORMATION_LAW_ORDERED_PHASE_STABILITY_OF_THE_NOISY_LEVEL_AUTOMATON_EXPLICIT_THRESHOLD_SIX_INVARIANT_LAWS_BOUNDED_THEOREM_NOTE_2026-09-16.md','docs/ADMISSIBILITY_RULE_STATIC_SIX_AXIS_REFLECTION_IDENTITIES_AND_CONDITIONAL_CONTOUR_BOUNDS_BOUNDED_THEOREM_NOTE_2026-09-15.md','docs/ADMISSIBILITY_RULE_SPHERE_STATIC_LAW_FINITE_TORUS_MAGNETIZATION_BOUNDS_BOUNDED_THEOREM_NOTE_2026-09-15.md','docs/ADMISSIBILITY_RULE_CUBIC_WALK_RETURN_SUM_AND_SPHERE_STATIC_MAGNETIZATION_SUFFICIENT_BOUND_BOUNDED_THEOREM_NOTE_2026-09-15.md']
resource=dump('drain8170-author-input-resource-plan-v2.json',dict(runner=dict(path=runner,sha256=sha(rp)),ordered_inputs=[dict(path=p,sha256=sha(W/p)) for p in inputs],mathematical_parents=[dict(path=p,sha256=sha(W/p),role='Framework or finite product-rule vocabulary only; no selection of sphere process') for p in parents],mathematical_closure='Complete corrected moment/series/mean proof, literal local-limit proof and finite-plane proof, declared auxiliary recurrence variance proof and finite six-axis enumeration in canonical note. Standard math imports explicit; no empirical fits or sibling phase theorem used. Deferred auxiliary obstruction and twist/nonlinear histories are recovery, not live dependencies.',context_only=[dict(path=p,sha256=sha(W/p)) for p in context],timeout_sec=900,proposed_external_process_tree_limit_bytes=768*1024*1024,source_basis='Inherited 900-second primary cap; fixed SymPy integrals/differentiation, exact trinomial loops k<=150 twice, 3^k enumeration k<=6, bounded rational exponentials; no arrays/lattice simulation or historical fit execution. 768MiB proposed for symbolic working sets, unmeasured; preserve any failure.',json_output='logs/runner-cache/'+Path(runner).stem+'.json',mutation_json_pattern='logs/runner-cache/'+Path(runner).stem+'--<mutation>.json',stdout='logs/runner-cache/'+Path(runner).stem+'.txt',checks_source_derived_not_executed=17,mutation_names=decl['MUTATION_GATE'],mutation_status='All 14 current mathematical mutations pending independent confirmation/execution; original14 definitions and raw histories preserved. Two retired prose-policy mutations are not silently counted as current.',primary_executions=0,simulation_executions=0))
# Verify all complete historical payloads; no content trimming or resampling.
man=json.loads((W/prep['archive_manifest']['path']).read_text());arc=(W/prep['archive_manifest']['path']).parent
for e in man['entries']:
 p=arc/e['stored_path'];raw=gzip.decompress(p.read_bytes()) if e['encoding']=='gzip' else p.read_bytes();assert hashlib.sha256(raw).hexdigest()==e['raw_sha256'];assert hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==e['git_blob'];assert sha(p)==e['stored_sha256']
report=json.loads((R/'drain8170-review-original.json').read_text())
dispositions=[]
for f in report['findings']:
 resolutions={'8170-1':'False derivative bound removed; positive-series identity and exact counterexample added, old false PASS retained in history.','8170-2':'Exact mean gain A(3beta), quadratic maximum and normalized direction distinguished; auxiliary recursion explicitly supplied, gamma asymptotic corrected.','8170-3':'No nonlinear beta L² scale/exclusion remains active; finite-plane bound preserved literally.','8170-4':'Full rows/raw NaNs and signed projections retained in recovery; corrected observable/cadence discussion, no live universal exponent inference.','8170-5':'Historical fit not promoted; missing split inputs explicit, reopening requires deterministic pinned parser. No fabricated missing projection or rerun.','8170-6':'Settled phase map withdrawn; current-main PR8168 formation proof context and conditional static scope distinguished.','8170-7':'Broad certification withheld; full auxiliary contradiction and twist obligation readable in deferred science; five historical entries not called five closed independent routes.','8170-8':'Actual two-parent Markdown links and literal input pins; no helper registry edits; final topology/cache/gate reserved for coordinator.'}
 dispositions.append(dict(finding=f['id'],disposition=resolutions[f['id']],status='AUTHOR CORRECTION; INDEPENDENT CONFIRMATION PENDING'))
dump('drain8170-author-finding-dispositions-v2.json',dispositions)
assert not subprocess.check_output(['git','-C',str(W),'diff','--name-only','HEAD'],text=True)
result=dump('drain8170-author-handoff-v2.json',dict(status='PREPARED ONLY; ORIGINAL REVIEWER DISPATCH OWNED BY ROOT',source_freeze=dict(path=str(R/'drain8170-prepared-v2-source-freeze.json'),sha256=sha(R/'drain8170-prepared-v2-source-freeze.json')),prepared=dict(path=str(R/'drain8170-author-prepared-v2.json'),sha256=sha(R/'drain8170-author-prepared-v2.json')),discovery=dict(path=str(dis),sha256=sha(dis)),resources=dict(path=str(resource),sha256=sha(resource)),correction=dict(path=str(R/'drain8170-author-correction-v2.diff'),sha256=sha(R/'drain8170-author-correction-v2.diff')),source_files=30,originals=25,primary_runs=0,mutation_runs=0,simulations=0,registry_edits=[],staged=False,branch_retention_required=True))
print(result.read_text());print('handoff SHA256 '+sha(result))
