from pathlib import Path
import json,hashlib,gzip,difflib
r=Path(__file__).resolve().parent;w=r/'author-draft-slot';o=r/'drain8026-originals'
inventory=json.loads((r/'drain8026-original-inventory.json').read_text());prefix='docs/work_history/review_loop/pr8026';dest=w/prefix;assert not dest.exists();(dest/'objects').mkdir(parents=True)
manifest=[]
for entry in inventory['original_paths']:
 raw=(o/entry['path']).read_bytes();h=hashlib.sha256(raw).hexdigest();assert h==entry['sha256'];stored=prefix+'/objects/'+h+'.gz';p=w/stored
 if not p.exists():p.write_bytes(gzip.compress(raw,mtime=0))
 assert gzip.decompress(p.read_bytes())==raw
 manifest.append(dict(path=entry['path'],mode=entry['mode'],blob=entry['blob'],sha256=h,head=inventory['head'],stored=stored))
(dest/'original-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
(dest/'README.md').write_text('# PR8026 original recovery\n\nHistorical source and execution records, not current science or audit authority. The manifest binds all 87 original paths, modes, blobs and SHA-256 identities from head '+inventory['head']+' against original delta '+inventory['delta_base']+'. Decompress each content-addressed object to recover its exact original bytes.\n\nThe canonical note retains both complete mathematical derivations. The 79 original packet files preserve alternate root and primary proofs, the incorrect Haar-index checker and spuriously passing output, subsequent repairs, prospective plans, raw controls and prior review/validation history. Original caches, generated manifest and stale tool versions are recovery only. Current source maps preserve current-main entries; fresh evidence is captured separately.\n')
note='docs/GAUGE_WILSON_SPATIAL_LOOP_AREA_SUPPRESSION_BOUNDED_THEOREM_NOTE_2026-09-07.md';s=(o/note).read_text()
s=s.replace('[durable packet](../.claude/science/physics-loops/spatial-loop-area-20260907/PROOF_REVIEW.md)','[original recovery archive](work_history/review_loop/pr8026/README.md)')
s=s.replace('## Proof and provenance conventions','The current captures are the [chain cache](../logs/runner-cache/gauge_wilson_spatial_loop_area_chain_check_2026_09_07.txt) and [coefficient cache](../logs/runner-cache/gauge_wilson_spatial_loop_area_coefficients_check_2026_09_07.txt). Each reported total includes one resource check. Neither runner executes its sibling; finite checks do not prove the analytical cluster theorem.\n\n## Proof and provenance conventions\n\nLane names, preregistration, exposure and review statements below describe the original 2026-09-07 development history. They are not evidence of current independent review or current runner performance.')
s=s.replace('The preregistered check.py verifies 19 exact finite identities/controls','The original preregistered check.py recorded 19 exact finite identities/controls').replace('It uses 17.875 MiB and 0.0017 seconds in the preserved run.','That historical run recorded 17.875 MiB and 0.0017 seconds; those values are not current performance measurements.')
s+='''\n## No-go applicability and finite-evidence boundary\n\nN1: The positive theorem covers the supplied compact Hamiltonian, qualifying rectangles, sufficiently small coupling and the selected periodic thermodynamic limit. It does not exclude other physical routes.\nN2: The two literal repository parents and the two explicitly cited external mathematical imports supply the stated premises; no axiom-to-action or physical-confinement derivation is asserted.\nN3: Independent link-center charges give the analytical all-order selection rule. Repeated insertions, nonplanar fillings and periodic constant sheets are included in that proof.\nN4: The periodic complement and transpose/denominator counterexamples identify specific failures of stronger formulations, not exhaustive failure of all alternatives.\nN5: The chain and coefficient runners check finite indexing and rational arithmetic (19 and 33 checks, each including one resource check). They neither prove the imported marked-cluster bound nor determine its analytic radius.\nN6: The explicit complex marked expansion and weighted pinned-cluster criterion justify the volume-uniform analytic bound; finite Taylor coefficients alone do not.\nN7: No universal negative conclusion is certified. A temporal charge potential, lower bound, arbitrary-coupling theorem and continuum or physical identification remain outside this result.\nN8: Both derivations, failed controls, repairs and all original path versions remain recoverable from the linked archive. Historical success does not replace current evidence or independent audit.\n'''
assert not (w/note).exists();(w/note).write_text(s)
parents=['docs/GAUGE_WILSON_FULL_CUBE_COMPACT_INTERACTING_HAMILTONIAN_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-07.md','docs/GAUGE_WILSON_COMPACT_CUBE_LOW_ELECTRIC_SPECTRUM_RITZ_GAP_BOUNDED_THEOREM_NOTE_2026-09-07.md']
paths=[note]
for basename in ['gauge_wilson_spatial_loop_area_chain_check_2026_09_07.py','gauge_wilson_spatial_loop_area_coefficients_check_2026_09_07.py']:
 p='scripts/'+basename;t=(o/p).read_text();t=t.replace('AUDIT_TIMEOUT_SEC = 180','''# These literal paths pin the proof/premise identities; no runtime prose parsing.
AUDIT_INPUT_PATHS = '''+repr([note,*parents])+'''\nAUDIT_TIMEOUT_SEC = 180''');t=t.replace("print('TOTAL: '+str(expected))","print('TOTAL: PASS='+str(expected)+' FAIL=0')")
 assert not (w/p).exists();(w/p).write_text(t);compile(t,p,'exec');paths.append(p)
patch=''.join(''.join(difflib.unified_diff((o/p).read_text().splitlines(True),(w/p).read_text().splitlines(True),fromfile='original/'+p,tofile='corrected/'+p)) for p in paths)
(r/'drain8026-author-corrections-v1.patch').write_text(patch)
print('87 originals preserved; 3 new source files authored; no execution; tool maps pending landed8025')
