from pathlib import Path
import ast,json,hashlib,gzip,subprocess,sys,os,re
R=Path('/private/tmp/review-drain-20260915');W=R/'review-draft-slot';j=json.loads((R/'drain8176-author-prepared-v1.json').read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def dump(name,x):
 p=R/name;assert not p.exists();p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
run=W/j['primaries'][0];note=W/j['canonical_notes'][0];body=note.read_text();tree=ast.parse(run.read_text());const={n.targets[0].id:ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ['FORBIDDEN','FENCES','N5_LINES','INPUT_SHA256','MUTATION_GATE','CLASSICAL_NAMES','ALLOWED_NAME_SECTIONS']}
assert not [x for x in const['FORBIDDEN'] if x in body],[x for x in const['FORBIDDEN'] if x in body];assert all(x in body for x in const['FENCES']);assert all(len(x.split(':',1)[1].strip())>=40 for x in const['N5_LINES'])
assert not re.findall(r'(?<![\w.])\d+\.\d+(?![\w.])|\bfloat\(|\.evalf\(|\bN\(',run.read_text().split('float-scan-marker-line')[0])
sections=re.split(r'^## ',body,flags=re.M);off=[]
for sec in sections[1:]:
 if not any(sec.split('\n',1)[0].strip().startswith(a) for a in const['ALLOWED_NAME_SECTIONS']):off.extend(n for n in const['CLASSICAL_NAMES'] if n in sec)
off.extend(n for n in const['CLASSICAL_NAMES'] if n in sections[0]);assert not off
# Metadata modules only, no scientific primary/helper function imported or run.
os.chdir(W);sys.path[:0]=[str(W/'scripts'),str(W/'docs/audit/scripts')];import runner_cache as c;import audit_packet_script_deps as a;import build_citation_graph as g
inputs=list(c.declared_input_paths(run));assert len(inputs)==3;assert all(sha(W/p)==const['INPUT_SHA256'][p] for p in inputs)
m=json.loads((W/j['original_manifest']['path']).read_text());assert len(m['entries'])==29
for e in m['entries']:
 raw=gzip.decompress((W/e['recovery']['path']).read_bytes());assert hashlib.sha256(raw).hexdigest()==e['original_sha256'];assert hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==e['original_blob'];assert sha(W/e['recovery']['path'])==e['recovery']['sha256']
assert hashlib.sha256(gzip.decompress((W/m['original_delta']['path']).read_bytes())).hexdigest()==m['original_delta']['decoded_sha256']
api=dict(schema_version=1,kind='read-only-source-discovery-not-execution',base=j['base'],primary=j['primaries'][0],primary_sha256=sha(run),runtime_inputs=[dict(path=p,sha256=sha(W/p),role='proof source' if p==j['canonical_notes'][0] else 'framework authority' if 'MINIMAL_AXIOMS' in p else 'context only, not mathematical premise') for p in inputs],input_fingerprint=c.declared_input_fingerprint(run),declared_timeout=c.declared_timeout_for(run),packet_transitive_helpers=sorted(a.transitive_helpers(run.stem)),graph_helpers=g.helper_runner_paths_for_claim(g.claim_id_from_path(note),j['primaries'][0]),citations=[str(p.relative_to(W)) for p in g.extract_citations(body,note)],graph_primary=g.extract_runner(body,j['canonical_notes'][0]),framework_dependencies=['docs/MINIMAL_AXIOMS_2026-06-29.md'],mathematical_premise_notes=[],mathematical_imports=['finite graph/tree connectivity and edge count','exact level dynamic programming and affine-minimum concavity','rational polynomial substitution and completed-square identity'],deferred_role='Complete corrected negative argument plus original full note, not live supporting proof or premise; global construction/physical implications remain unsupported',registry_changes_required=False,primary_imported=False,primary_executed=False,static_compile=True,original_archives_verified=29,original_delta_verified=True)
assert api['packet_transitive_helpers']==[] and api['graph_helpers']==[] and api['graph_primary']==j['primaries'][0]
dump('drain8176-source-input-discovery-v1.json',api)
authorities=['docs/MINIMAL_AXIOMS_2026-06-29.md','docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','docs/audit/data/axiom_premise_nodes.json','docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md']
oldbind=json.loads((R/'drain8173-adapter-authority-v1.json').read_text())['authority'];oldhash={x['path']:x['sha256'] for x in oldbind};assert all(sha(W/p)==oldhash[p] for p in authorities)
resource=dict(schema_version=1,kind='proposed-resource-plan-not-execution',primary=j['primaries'][0],timeout_seconds=60,memory_limit_bytes=384*1024*1024,limits_status='Unmeasured corrected source; proposed external process-tree RSS/time watchdog, fail closed without retry/increase',original_measured_resource=json.loads((R/'check8176/original-primary.json').read_text()),cost=dict(fixed_windows='112,200,112,112,225sites; repeated finite graph reconstruction, no fixture growth',dynamic_program='Exact Fraction subset-level transfers; original measured run reports max2^10states per level, pairwise adjacent-level subset scan and retained backpointers. No dense numerical array or eigensolver.',brute_force='Unchanged seeded32 rejection loop selects4through10live-site fixtures, >=90single-seed and >=25multi-seed accepted; no deterministic bound on rejected proposals, so external wall cap remains necessary.',arithmetic='Four exact polynomial certificates and one SymPy scalar maximum; three added small domain/count checks do not enlarge any original fixture.',imports='SymPy and standard library; no local helper or top-level scientific execution.',memory='Original independent primary measured68485120bytes RSS in2.1415155839640647s; this does not measure corrected source.384MiB proposed with headroom, not a successful resource certificate.'),expected_completed_checks=22,count_scope='A4+B3+C4+D3+E3+F4+G1 includes packaging/resolution checks, not22theorems',stdout_only=True,json_outputs=[],other_output_writes=[],cache_destination=f'logs/runner-cache/{run.stem}.txt',mutations=const['MUTATION_GATE'],changed_claim_mutations=[dict(name=n,target=t,expected_exit_code=1,expected_total='PASS=21 FAIL=1',status='proposed only, not executed') for n,t in [('isolated_seed_cost_wrong','B3'),('zb_mark_count_wrong','C4'),('real_boundary_rounded','E3')]],unchanged_mutation_reruns_requested=False,primary_runs=0,simulation_runs=0,mutation_runs=0)
dump('drain8176-resource-plan-v1.json',resource)
assert not subprocess.check_output(['git','diff','--name-only'],text=True);assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True)
paths=subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines();assert set(paths)=={x['path'] for x in j['source']}
for x in j['source']:assert sha(W/x['path'])==x['sha256']
existing={Path(p).name for p in subprocess.check_output(['git','ls-files','docs'],text=True).splitlines()};new=[p for p in paths if p.startswith('docs/') and Path(p).name not in ['README.md','SKILL.md']];assert not [p for p in new if Path(p).name in existing];assert len({Path(p).name for p in new})==len(new)
refs=['drain8176-author-prepared-v1.json','drain8176-source-freeze-v1.json','drain8176-author-dispositions-v1.json','drain8176-author-corrections-v1.patch','drain8176-source-input-discovery-v1.json','drain8176-resource-plan-v1.json','drain8176-review-original.json','drain8176-review-original.md']
dump('drain8176-author-handoff-v1.json',dict(schema_version=1,kind='author-preparation-handoff-not-source-pass',pr=8176,base=j['base'],head=j['head'],owner='PR8176-author',source_count=35,original_count=29,source_freeze=dict(path=str(R/'drain8176-source-freeze-v1.json'),sha256=sha(R/'drain8176-source-freeze-v1.json')),references=[dict(path=str(R/p),sha256=sha(R/p)) for p in refs],authority=[dict(path=p,sha256=sha(W/p),read_reuse='Prior same-author complete authority read, verified bytes unchanged from PR8173 authority binding') for p in authorities],branch_preservation_required=True,tracked_and_index_clean=True,document_basename_collision_check=dict(all_new_docs_checked=True,exceptions=['README.md','SKILL.md'],collisions=[]),primary_runs=0,simulation_runs=0,mutation_runs=0,staged=False,registry_changes=False,pending='Root-dispatched original same-session affected review; no source or landing PASS asserted.'))
print(json.dumps({p:sha(R/p) for p in refs+['drain8176-author-handoff-v1.json']},indent=2))
