from pathlib import Path
import ast,json,hashlib,shutil,difflib,subprocess,sys,os,gzip,re
R=Path('/private/tmp/review-drain-20260915');W=R/'review-draft-slot';j=json.loads((R/'drain8173-author-prepared-v1.json').read_text());sha=lambda b:hashlib.sha256(b).hexdigest()
note=W/j['canonical_notes'][0];run=W/j['primaries'][0];before=note.read_text();s=before.replace('trace_class: frontier_discovery','trace_class: upstream_support').replace('source_of_blocker_text: author_source','source_of_blocker_text: handoff').replace('No\n  physical order, coupling or infinite-volume state is inferred.','No\n  order or coupling is selected as physical, and no infinite-volume state is inferred.')
assert s!=before;oldhash=sha(note.read_bytes());note.write_text(s);runbefore=run.read_text();run.write_text(runbefore.replace(oldhash,sha(note.read_bytes())));compile(run.read_text(),str(run),'exec')
rows=[dict(x,sha256=sha((W/x['path']).read_bytes())) for x in j['source']];snap=R/'drain8173-prepared-source-v2';assert not snap.exists()
for x in rows:(snap/x['path']).parent.mkdir(parents=True,exist_ok=True);shutil.copy2(W/x['path'],snap/x['path'])
j.update(source=rows,snapshot=str(snap),source_revision=2,prior_prepared_sha256=sha((R/'drain8173-author-prepared-v1.json').read_bytes()),revision_reason='truthful upstream-support trace, existing handoff enum and avoid legacy packaging false positive in explicit non-claim; note pin rebound; no mathematical changes')
def dump(name,x):
 p=R/name;assert not p.exists();p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
dump('drain8173-author-prepared-v2.json',j)
dump('drain8173-source-freeze-v2.json',dict(schema_version=1,base=j['base'],source=rows,snapshot=str(snap),prepared_sha256=sha((R/'drain8173-author-prepared-v2.json').read_bytes())))
p=''.join(difflib.unified_diff(before.splitlines(True),s.splitlines(True),fromfile=j['canonical_notes'][0]+'@v1',tofile=j['canonical_notes'][0]+'@v2'))+''.join(difflib.unified_diff(runbefore.splitlines(True),run.read_text().splitlines(True),fromfile=j['primaries'][0]+'@v1',tofile=j['primaries'][0]+'@v2'))
(R/'drain8173-author-v1-to-v2.patch').write_text(p)
O=R/'drain8173-original/head';d=json.loads((R/'drain8173-review-original.json').read_text())['dispositions'];on=next(x['path'] for x in d if x['path'].startswith('docs/ADMISSIBILITY'));op=next(x['path'] for x in d if x['path'].startswith('scripts/'))
(R/'drain8173-author-corrections-v2.patch').write_text(''.join(difflib.unified_diff((O/on).read_text().splitlines(True),s.splitlines(True),fromfile=on,tofile=j['canonical_notes'][0]))+''.join(difflib.unified_diff((O/op).read_text().splitlines(True),run.read_text().splitlines(True),fromfile=op,tofile=j['primaries'][0])))
# Parse only; never import or run primary.
tree=ast.parse(run.read_text());const={n.targets[0].id:ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ['FORBIDDEN','FENCES','N5_LINES','INPUT_SHA256','MUTATION_GATE','CLASSICAL_NAMES','ALLOWED_NAME_SECTIONS']}
assert not [x for x in const['FORBIDDEN'] if x in s], [x for x in const['FORBIDDEN'] if x in s]
assert all(x in s for x in const['FENCES']);assert all(len(x.split(':',1)[1].strip())>=40 for x in const['N5_LINES'])
sections=re.split(r'^## ',s,flags=re.M);off=[]
for sec in sections[1:]:
 if not any(sec.split('\n',1)[0].strip().startswith(a) for a in const['ALLOWED_NAME_SECTIONS']):off.extend(n for n in const['CLASSICAL_NAMES'] if n in sec)
off.extend(n for n in const['CLASSICAL_NAMES'] if n in sections[0]);assert not off,off
float_hits=re.findall(r'(?<![\w.])\d+\.\d+(?![\w.])|\bfloat\(|\.evalf\(|\bN\(',run.read_text().split('float-scan-marker-line')[0]);assert not float_hits,float_hits
os.chdir(W);sys.path[:0]=[str(W/'scripts'),str(W/'docs/audit/scripts')];import runner_cache as c;import audit_packet_script_deps as a;import build_citation_graph as g
inputs=list(c.declared_input_paths(run));assert all(sha((W/p).read_bytes())==const['INPUT_SHA256'][p] for p in inputs)
manifest=json.loads((W/j['original_manifest']['path']).read_text());assert len(manifest['entries'])==20
for e in manifest['entries']:
 raw=gzip.decompress((W/e['recovery']['path']).read_bytes());assert sha(raw)==e['original_sha256'];assert hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==e['git_blob']
assert not subprocess.check_output(['git','diff','--name-only'],text=True);assert not subprocess.check_output(['git','diff','--cached','--name-only'],text=True)
assert set(subprocess.check_output(['git','ls-files','--others','--exclude-standard'],text=True).splitlines())=={x['path'] for x in rows}
parents=['docs/ADMISSIBILITY_RULE_SPHERE_STATIC_LAW_ZERO_FIELD_COMPONENT_FOURIER_BOUNDS_BOUNDED_THEOREM_NOTE_2026-09-15.md','docs/ADMISSIBILITY_RULE_CUBIC_WALK_RETURN_SUM_AND_SPHERE_STATIC_MAGNETIZATION_SUFFICIENT_BOUND_BOUNDED_THEOREM_NOTE_2026-09-15.md']
api=dict(schema_version=1,kind='read-only-source-discovery-not-execution',base=j['base'],primary=j['primaries'][0],primary_sha256=sha(run.read_bytes()),runtime_inputs=[dict(path=p,sha256=sha((W/p).read_bytes()),role='proof source' if p==j['canonical_notes'][0] else 'framework authority' if 'MINIMAL_AXIOMS' in p else 'context only, not mathematical premise') for p in inputs],input_fingerprint=c.declared_input_fingerprint(run),declared_timeout=c.declared_timeout_for(run),packet_transitive_helpers=sorted(a.transitive_helpers(run.stem)),graph_helpers=g.helper_runner_paths_for_claim(g.claim_id_from_path(note),j['primaries'][0]),citations=[str(p.relative_to(W)) for p in g.extract_citations(s,note)],graph_primary=g.extract_runner(s,j['canonical_notes'][0]),framework_dependencies=['docs/MINIMAL_AXIOMS_2026-06-29.md'],mathematical_premise_notes=[],context_parents=[dict(path=p,sha256=sha((W/p).read_bytes()),role='current-main boundary context only; no bound imported and no runtime read') for p in parents],mathematical_imports=['finite-dimensional real spectral theorem','one-dimensional Gaussian integral and scaling','rotation-invariant sphere surface measure and finite-dimensional differentiation under integral','finite Fourier geometric-sum orthogonality'],registry_changes_required=False,primary_imported=False,primary_executed=False,static_compile=True,original_archives_verified=20,tracked_and_index_clean=True)
assert api['packet_transitive_helpers']==[] and api['graph_helpers']==[];assert api['graph_primary']==j['primaries'][0]
dump('drain8173-source-input-discovery-v2.json',api)
plan=dict(schema_version=1,kind='proposed-resource-and-execution-contract-not-execution',primary=j['primaries'][0],timeout_seconds=60,memory_limit_bytes=384*1024*1024,limits_status='source-derived watchdog proposal, unmeasured for corrected source; requires original reviewer confirmation and root dispatch',historical_measurement=dict(original_timeout_seconds=900,elapsed_seconds=0.37,source='original archived cache; original runner and original inputs only',peak_memory_bytes=None),cost=dict(symbolic='One dense symbolic 64x64 Laplacian (4096 entries), four sequential length64 plane-wave products/simplifications; one4x4 ring and two vectors; three elementary exponential integrals plus a two-angle trigonometric surface integral and four-point rational DFT.',work='No eigensolver, no large configuration array, no FFT sampler or imported local helper. The original matrix/vector fixture is unchanged.',imports='SymPy imported once; stdlib otherwise. No top-level scientific calculation beyond declarations.',memory='Interpreter and symbolic expressions dominate; 384MiB watchdog is proposed, not a measured peak or proved bound.'),expected_completed_checks=14,count_scope='A4+B2+C2+D1+F4+G1; five mathematical checks and nine source/reporting checks',stdout=True,json_outputs=[],other_output_writes=[],cache_destination=f'logs/runner-cache/{run.stem}.txt',mutations=const['MUTATION_GATE'],decisive_control_proposal=dict(global_rotation='Independent bond-polynomial cancellation with a sign mutation and exact N normalization; preserve expected failure. No baseline rerun proposed.',frame='Independent exact rational spin configuration showing sum projected spins=0 and a nonzero fixed-axis total; mutation replacing sample-relative projection with fixed lab projection must fail.',existing_evidence='Original reviewer check8173 independently checked bond cancellation in proof and projected zero mode; no additional controls executed in preparation.'),no_primary_run=True)
dump('drain8173-resource-plan-v2.json',plan)
refs=['drain8173-author-prepared-v2.json','drain8173-source-freeze-v2.json','drain8173-author-dispositions-v1.json','drain8173-author-corrections-v2.patch','drain8173-source-input-discovery-v2.json','drain8173-resource-plan-v2.json','drain8173-review-original.json','drain8173-review-original.md']
dump('drain8173-author-handoff-v2.json',dict(schema_version=1,kind='author-preparation-handoff-not-source-pass',pr=8173,owner='PR8173-author',base=j['base'],head=j['head'],source_count=25,original_count=20,references=[dict(path=str(R/p),sha256=sha((R/p).read_bytes())) for p in refs],immutable_snapshot=str(snap),primary_runs=0,simulation_runs=0,mutation_runs=0,staged=False,registry_changed=False,branch_preservation_required=True,pending='Original same-session affected review and source freeze; root owns staging, captures, gates and integration.'))
print(json.dumps({p:sha((R/p).read_bytes()) for p in refs+['drain8173-author-handoff-v2.json']},indent=2))
