import json,hashlib,re
from pathlib import Path
r=Path('/private/tmp/review-drain-20260915');w=r/'resume-author8083';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:{'path':str(p),'sha256':sha(p)};f=json.load(open(r/'resume8083-author-outputfix-final-freeze.json'));pre=json.load(open(r/'resume8083-author-outputfix-preexecution.json'));assert all(sha(w/p)==h for p,h in f['source_paths'].items());assert all(sha(w/p)==h for p,h in pre['nonoutput_sources'].items());assert all(sha(w/p)==h for p,h in pre['inputs'].items());executions=[]
for n in range(8079,8084):
 p=r/f'resume{n}-author-outputfix-execution.json';x=json.load(open(p));watch=x['whole_tree_watchdog'];assert x['status']=='ok' and x['exit_code']==0 and x['stderr']=='' and x['timeout_sec']==30 and x['elapsed_sec']<30 and not watch['violations'] and 0<watch['peak_tree_rss_bytes']<=384*1048576;total=re.search(r'^TOTAL: PASS=(\d+) FAIL=0$',x['stdout'],re.M);assert total;executions.append({'pr':n,'pass_count':int(total[1]),'seconds':x['elapsed_sec'],'sampled_tree_rss_bytes':watch['peak_tree_rss_bytes'],'receipt':ref(p)})
perpr={
'8079':{'accepted':'Computable residual identity/bound, finite contraction construction and omega5 positive-integral supplier; finite outcomes descriptive.','deferred':'Constant-trial and all-q fixed-first-polynomial negative certification.','closure':'Positive-only salvage; KEEP original recovery branch/head and track deferred negative certification. Do not declare entire original complete.'},
'8080':{'accepted':'Posterior trial-norm bound, quadratic spectral envelope and fixed-parameter constructions; saved intervals descriptive.','deferred':None,'closure':'Own positive claim complete for this review; root combined validation/landing still required.'},
'8081':{'accepted':'Coupled signed-error identity, valid norm remainder bound, reduced signed-dual Gram construction and finite outcomes.','deferred':'Zero-dual exclusion and norm-only optimality/impossibility certification.','closure':'Positive-only salvage; KEEP original recovery branch/head and track deferred negative certification. Do not declare entire original complete.'},
'8082':{'accepted':'Conditional infinite-volume Gaussian determinant bridge, finite source-degree closure, omega79 and high-moment supplier.','deferred':None,'closure':'Own positive claim complete for this review; root combined validation/landing still required.'},
'8083':{'accepted':'Quartic envelope and coupled posterior bounds with unchanged-trial interval comparison.','deferred':None,'closure':'Own positive claim complete for this review; root combined validation/landing still required.'}}
report={'session':'/root/resume_8079_8083','model_review_lane':'Astra low independent review-loop','tree':f['tree'],'source_verdict':'PASS_SCOPED_POSITIVE_SOURCE','negative_certification':'DEFERRED; exact-target N1 quota unmet. No No-Go Discipline Gate PASS; original negative mathematical arguments retained unchanged as historical conditional evidence.','scope':'Full original407 path dispositions and complete load-bearing mathematics previously reviewed; final affected scope/links/input pins/recovery/output metadata and capture artifacts checked. Positive constructions require no deferred negative theorem.','source_confirmation':{'nonoutput_paths_unchanged':len(pre['nonoutput_sources']),'declared_input_paths_unchanged':len(pre['inputs']),'final_source_paths':len(f['source_paths']),'only_capture_changes':'Five UNEXECUTED placeholders replaced by actual outputs and five actual caches added.'},'proof_boundary':'The two Gaussian REVIEW arguments are current scientific runtime inputs despite filenames; old verdict text has no current authority. Two finite-moment docs proofs have explicit schema2 ownership restricted to positive claims.','numerical_closure':{'manifest_bindings':7816,'explicit_binding_role_occurrences':108,'catalog_endpoint_rows':3484,'reused_CAS':'All actual reused storage bytes bound as scientific runtime inputs in unit record; no blanket requirement for9250 umbrella history pins.'},'independent_controls':'Previously completed655 exact rational controls and32 finite Gaussian determinant controls retained; not rerun. These do not constitute native/infinite numerical simulation.','compact_executions':executions,'failed_attempt':'8079 first attempt failed closed due output directory stat mutation; content identities unchanged. Exact failure/partial output/log/watchdog/script/freeze preserved and hash-bound. One root-authorized retry then succeeded. No native producer/oracle replay.','per_pr_claim_disposition':perpr,'integration_boundary':'Source PASS is limited to declared positive scope. Sole final mechanical --cache check follows; root owns combined pipeline/strict/changed-evidence checks, publication, landing and closure. No audit verdict or physical alpha sign.'};rp=r/'resume8083-final-source-review.json';rp.write_text(json.dumps(report,indent=2)+'\n');d=json.load(open(r/'resume8083-unit-v2-preexecution-outputfix.json'));d['unit_id']='pr8079-8083-positive-scope-final';d['source']['tree']=f['tree'];d['source']['paths']=[{'path':p,'sha256':h}for p,h in sorted(f['source_paths'].items())];d['reviewer']['report']=ref(rp);d['reviewer']['references'] += [ref(r/'resume8083-author-outputfix-final-freeze.json'),ref(r/'resume8083-preexecution-preflight-outputfix-bound.json'),ref(r/'resume8083-unit-v2-preexecution-outputfix.json')]+[x['receipt']for x in executions];(r/'resume8083-unit-v2-final.json').write_text(json.dumps(d,indent=2)+'\n');print(f['tree'],sum(x['pass_count']for x in executions))
