import json,hashlib,subprocess,sys,importlib.util
from pathlib import Path
r=Path('/private/tmp/review-drain-20260915');w=r/'resume-author8083';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();f=json.load(open(r/'resume8083-author-preexecution.json'));report=r/'resume8083-cold-confirmation-v3.json'
report.write_text(json.dumps({'session':'/root/resume_8079_8083','tree':f['tree'],'verdict':'CONFIRMED_POSITIVE_SCOPE_SOURCE_ONLY','scope':'Conditional constructive identities, valid enclosure bounds, supplier constructions and finite descriptive certificate outcomes; historical negative certification deferred, no No-Go Gate PASS.','review':'Original full arguments and load-bearing proof sources previously reviewed; affected current scope, recovery, runner input declarations and two output metadata additions reread. Positive claims do not depend on deferred negatives.','controls':'Existing655 rational and32 Gaussian finite independent controls retained, not rerun.','closure':'7816 recovery mappings and108 direct BINDING role occurrences verified;3484 catalog endpoints and geometry exact; reused CAS bytes bound below.','preexecution':'No primary or historical science execution by reviewer. Author captures only after mechanical preflight passes.'},indent=2)+'\n')
ref=lambda p:{'path':str(p),'sha256':sha(p)}
old=json.load(open(r/'resume8083-draft-dispositions.json'));disps={str(n):[] for n in range(8079,8084)}
for x in old['entries']:
 orig=subprocess.check_output(['git','-C',str(w),'show',x['head']+':'+x['path']]);target=x['final_path']
 if x['disposition']=='superseded':target=None
 disps[str(x['pr'])].append({'original_path':x['path'],'original_sha256':hashlib.sha256(orig).hexdigest(),'disposition':x['disposition'],'recovery':x['head']+':'+x['path']+'; '+x['reason'],'final_path':target,'final_sha256':sha(w/target) if target else None})
dp=r/'resume8083-cold-dispositions-v3.json';dp.write_text(json.dumps(disps,indent=2)+'\n')
spec=importlib.util.spec_from_file_location('rr',w/'docs/ai_methodology/skills/review-loop/scripts/review_receipt.py');rr=importlib.util.module_from_spec(spec);spec.loader.exec_module(rr);graph,cache,packet=rr.repository_apis(w)
notes=[];parents=set();helpers=set();citations=set()
for row in json.load(open(r/'resume8083-author-early-api.json')):
 p=row['note'];body=(w/p).read_text();cite={x.relative_to(w).as_posix() for x in graph.extract_citations(body,w/p)};hs=set(graph.helper_runner_paths_for_claim(graph.claim_id_from_path(w/p),row['primary']));deps={x for x in cite if x.startswith('docs/NATIVE_')};parents|=deps;helpers|=hs;citations|=cite
 notes.append({'path':p,'claim_id':graph.claim_id_from_path(w/p),'declared_claim_id':graph.claim_id_from_path(w/p),'claim_type':'bounded_theorem','primary_runner':row['primary'],'helpers':sorted(hs),'citations':sorted(cite),'repository_dependencies':sorted(deps),'dependency_rationale':'Supplied native model, CAR/normal ordering/reference, common impurity gap and Ward identity; later constructive estimators and moment suppliers inherit earlier exact trial/scalar/source data. No deferred negative certification imported as premise.'})
recovery=json.load(open(w/'docs/work_history/repo/review_feedback/pr8079-8083-scientific-recovery/manifest.json'));runtime=set(f['inputs'])|{x['storage']for x in recovery['rows']};tooling={'docs/audit/scripts/build_citation_graph.py','docs/audit/scripts/static_pipeline_checkpoint.py','scripts/runner_cache.py','scripts/audit_packet_script_deps.py','docs/audit/scripts/ledger_io.py','docs/audit/data/doc_authority_registry.json','docs/ai_methodology/skills/review-loop/scripts/review_receipt.py'}
if (w/'docs/audit/data/axiom_premise_nodes.json').exists():tooling.add('docs/audit/data/axiom_premise_nodes.json')
changed=set(f['source_paths']);non=[]
for p in graph.discover_notes():
 q=p.relative_to(w).as_posix()
 if q in changed and q not in {x['path']for x in notes}:
  non.append({'path':q,'rationale':'Exact historical source/evidence duplicate or recovery navigation; no autonomous current claim asserted. Active full mathematical proof sources are separately retained in declared scientific input packets; historical review labels confer no current authority.','review_reference':ref(report)})
rows=lambda paths:[{'path':p,'sha256':sha(w/p)}for p in sorted(paths)]
proofs=json.load(open(r/'resume8083-owned-positive-proof-map.json')); non=[x for x in non if x['path'] not in {p['path'] for p in proofs}]; support=[dict(path=p['path'],canonical_note=p['canonical_note'],citations=sorted(x.relative_to(w).as_posix() for x in graph.extract_citations((w/p['path']).read_text(),w/p['path'])),rationale=p['scope']+' Full positive argument previously reviewed; no negative certification conferred by this ownership.',review_reference=ref(report)) for p in proofs]; units=json.load(open(r/'resume8083-original-deltas.json'));out={'schema_version':2,'unit_id':'pr8079-8083-positive-scope-preexecution','constituents':[{'id':str(x['pr']),'head':x['head'],'delta_base':x['base'],'dispositions':dict(ref(dp),json_pointer='/'+str(x['pr']))}for x in units],'source':{'base':f['base'],'commit':f['base'],'tree':f['tree'],'paths':rows(changed),'deleted_paths':[]},'inputs':{'runtime':rows(runtime),'helpers':rows(helpers),'parents':rows(parents),'context':rows(citations-parents),'tooling':rows(tooling)},'reviewer':{'session':'/root/resume_8079_8083','report':ref(report),'references':[ref(r/n)for n in ['resume8083-provisional-findings.md','resume8083-negative-scope-handoff.md','resume8083-independent-controls-v2.json','resume8083-gaussian-independent.json','resume8083-role-closure-check.json','resume8083-catalog-role-confirmation.json','resume8083-author-preexecution.json','resume8083-author-capture.py']]},'notes':notes,'non_science_notes':non,'supporting_proofs':support,'boundary':'Positive-source confirmation only; deferred negative claim certification remains open. All reused CAS input bytes explicitly bound. Mechanical readiness and subsequent cache checks confer no audit verdict.'};(r/'resume8083-unit-v2-preexecution-owned.json').write_text(json.dumps(out,indent=2)+'\n');print({'notes':len(notes),'non_science_notes':len(non),'runtime':len(runtime),'source':len(changed),'parents':len(parents)})
