import pathlib,json,hashlib,subprocess,datetime
R=pathlib.Path('/private/tmp/review-drain-20260915');O=R/'drain8170-original';m=json.loads((O/'manifest.json').read_text());slot=R/'review-draft-slot'
note=next(x['path'] for x in m['paths'] if x['path'].startswith('docs/ADMISSIBILITY'))
runner=next(x['path'] for x in m['paths'] if x['path'].startswith('scripts/'))
findings=[
 dict(id='8170-1',kind='BUG',priority=1,path=note,lines=[102,104],title='False derivative bound and invalid Langevin proof',detail="At kappa=1, sinh(1)^2>62/45>4/3, so A'(1)>1/4, contradicting A'<=1/(3+kappa^2). The implication from the lower bound on sinh² reverses direction. B2 and the exact control verify coefficients and identities, not this inequality, yet print the false implication as PASS.",fix="Delete derivative upper bound. Prove A(k)<k/3 via f(k)=(k²+3)sinh(k)-3k cosh(k)=sum_{n>=2}4n(n-1)k^(2n+1)/(2n+1)!>0. Update B2 and negative controls to test the actual coefficient/sign argument; preserve historical false PASS unchanged in recovery."),
 dict(id='8170-2',kind='SEMANTIC_BRIDGE',priority=1,path=note,lines=[108,110,145,149],title='Exact conditional mean is not gain one',detail="For common predecessor rotation theta, E[s_perp]=A(3beta)sin(theta), hence derivative A(3beta)<1. Covariance rotates a mean of length A(3beta), not a unit vector. The quadratic exponent has its maximum at the average (negative Hessian); the normalized mean direction has gain one. These do not make the exact noisy nonlinear mean gain one. Combining its exact noise with Gaussian gain is a declared auxiliary model, not an exact linearization theorem for every beta.",fix="Separate exact mean Jacobian A(3beta)/3 times the sum, mode/direction statement, and explicitly supplied gain-one additive-noise recursion. Retain T5 only for that auxiliary recursion; e^-v is a declared proxy, not nonlinear magnetization or an exact sphere observable. Use asymptotic equivalence notation gamma~sqrt(3)/(4pi beta), not convergence to a beta-dependent value."),
 dict(id='8170-3',kind='OVERCLAIM',priority=1,path=note,lines=[137,164,166,174],title='No nonlinear diffusive memory-time theorem',detail="T4 establishes a minorization rate (1-delta^(L²))^t, not a beta L² estimate or lower bound on forgetting time. Two finite sizes and finite single histories cannot exclude finite-size effects, interchange t and L limits, or prove cubic terms always accelerate decay. 256²/20000=3.2768, not >10; 512²=262144, not half a million sites.",fix="Remove the claimed exclusion and attribution to T4. Keep finite-plane uniqueness/rotation invariance and exact L=1 recursion. Describe beta L² as an auxiliary-model heuristic if retained, with nonlinear scaling open."),
 dict(id='8170-4',kind='BUG',priority=2,path=note,lines=[153,157,166],title='Historical table contradicts universal exponent and observable claims',detail="Independent beta12 history has slopes 0.0076 and 0.0103 below gamma≈0.011167; beta24 early slope 0.0055 is below 0.00566. The fit selects m_z where available, whereas prose calls it |m|. Independent beta12 stores only |m|, so its projection cannot be recovered. Historical checker says differences <10^-3, but controls reach 0.01189. Rounded six-axis 1.00000 observations are not proof of zero dissent at all times.",fix="Preserve all rows including below-gamma fits, negative projections and NaNs. Label each observable and rounded sampling cadence; use finite-history exploratory descriptions without universal ordering, monotonicity, plateau exclusion, or asymptotic exponent inference."),
 dict(id='8170-5',kind='MISSING_ARTIFACT',priority=2,path='.claude/science/physics-loops/admissibility-induced-law-20260906/specs/supervisor_control_block26_fit.py',lines=[5,19],title='Fit does not discover landed raw inputs',detail="Fit globs sim_b*_L*_T*.txt/ref_sphere_b*_L*.txt/ref_linear_b*_L*.txt. No such files are in the frozen packet; the data are concatenated in three differently named outputs. It therefore silently emits no rows on the shipped tree. Refuter source now prints m_z but beta12 historical output did not: do not restamp as current execution.",fix="Supply a deterministic parser of the existing concatenated files or pinned split-input materialization, fail on absent expected series, declare actual raw input paths, and reproduce the table cheaply. Do not rerun expensive simulations merely to replace history; maintain historical source/output limitations explicitly."),
 dict(id='8170-6',kind='IMPORTED_VALUE',priority=1,path=note,lines=[19,32,80,205],title='Older phase assertions are promoted despite corrected current-main scope',detail="Current main's static six-axis reflection/contour note defers unconditional phase conclusions. Sphere static sufficient bound is conditional on corrected zero-field parent and explicit mathematical imports. The present finite simulations establish neither side of a settled four-cell memory map. Sibling evidence-address wording does not neutralize conclusions actually used in the headline comparison.",fix="Remove unconditional old static/formation-order and exponential-memory assertions; either link precise current conditional scopes as context or omit the comparison. Keep the fully declared supplied sphere model self-contained. Block01 contributes finite records-only product-rule vocabulary, not a selected sphere law, coupling, schedule or physical process."),
 dict(id='8170-7',kind='NO_GO_OVERCLAIM',priority=2,path=note,lines=[172,174,176,196],title='Negative packet overstates tested resolutions and twist exclusion',detail="N1 mixes diagnostics, one formal route, and unproved finite-size exclusion; it is not five closed distinct attacks on a quantified no-go. Fixed-twist entropy cost proportional to T does not rule out all T-dependent twists/limits. N5 claims infinite-plane simulation though all executions are finite periodic histories; T1-T5 blanket proof is false as submitted.",fix="Keep twist as an unsuccessful outlined attempt with terminal entropy-control obligation open, not closed-negative/no bounded-cost twist theorem. Withhold broad negative certification explicitly; retain valid finite-plane theorem and auxiliary-field variance obstruction separately with honest written-proof versus finite-execution domains. No invented route count or certificate."),
 dict(id='8170-8',kind='AUDIT_COMPATIBILITY',priority=2,path=note,lines=[60,221],title='Dependency and evidence publication wiring absent',detail="Axiom and Block01 are code-formatted paths, not markdown links. Original topology manifest confirms out_degree=0 despite two claimed dependencies. Primary reads only three notes; historical simulations/fit outputs are not declared inputs. Campaign certificates and author PASS records are not current science authority.",fix="Add repo-portable markdown links to actual load-bearing authorities and primary/cache, declare any retained evidence parser inputs, regenerate topology acknowledgment on final current-main candidate. Preserve complete histories in durable recovery, prevent historical certificates from asserting current standing, and defer current cache capture/combined gate to coordinator's authorized placement.")]
d=[]
for p in m['paths']:
 row=dict(p);path=p['path']
 if path==note:status='narrowed';reason='Canonical mathematical core salvage after findings 1-8; original full proof retained.'
 elif path==runner:status='narrowed';reason='Repair false B2 and gain semantics, preserve full finite return-sum and moment families; execution pending.'
 elif path.startswith('logs/'):status='superseded';reason='Historical cache preserved verbatim; cannot certify corrected source.'
 elif path=='docs/audit/data/citation_graph_manifest.json':status='superseded';reason='Rebuild only final intended current-main topology; original zero-edge node is defective.'
 elif '/specs/' in path:status='deferred';reason='Preserve complete historical program/output, including failed fits and missing projection; parser salvage is permitted, original execution not restamped.'
 else:status='deferred';reason='Full campaign context preserved as history only; do not overlay old shared boards on current main. Extract unique attempted-twist/science history with explicit correction if needed.'
 row.update(disposition=status,reason=reason,recovery=str(O/'source'/path),final_source=None);d.append(row)
checks=['Manual reconstruction of T1 moments by differentiated normalizer; exact kappa=1 derivative counterexample; positive-series repair derivation.', 'Manual exact common-rotation conditional mean derivative and quadratic exponent Hessian.', 'Manual T3 Fourier symbol, determinant 1/27, Gaussian integral constants and all-k upper/lower proof, harmonic-tail assembly.', 'Independent integer convolution k<=150 (floating comparison against local-limit constant); output maximum deficit 0.13947154653231575.', 'Manual T4 minorization, monotonicity and rotation-unique invariant-law argument; L=1 tower recursion.', 'Manual auxiliary T5 independent noise path variance/no finite-variance stationary law; account P0=1 in upper sum (143.41322<150).', 'Read complete historical control/refuter algorithms, raw outputs, fit and cached primary; no original primary run.']
meta=json.loads(subprocess.check_output(['gh','pr','view','8170','--repo','jonathonreilly/qubit-lattice-axiom-framework','--json','number,state,isDraft,baseRefName,headRefName,headRefOid,url'],text=True))
status=subprocess.check_output(['git','status','--porcelain=v1','--untracked-files=all','--ignored'],cwd=slot,text=True);head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=slot,text=True).strip();assert head==m['head']==meta['headRefOid'] and not status
report=dict(schema='original-independent-science-review-v1',pr=8170,reviewer_session='/root/review_8170',configuration='gpt-6-astra / low as dispatched',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),original_head=m['head'],actual_merge_base=m['merge_base'],frozen_main=m['main'],declared_base='main',source_manifest=str(O/'manifest.json'),source_manifest_sha256=hashlib.sha256((O/'manifest.json').read_bytes()).hexdigest(),input_bindings=str(O/'input-bindings.json'),input_bindings_sha256=hashlib.sha256((O/'input-bindings.json').read_bytes()).hexdigest(),findings=findings,dispositions=d,checks=checks,resource_plan={'executed':'One standard-library independent script, k<=150 integer recurrence, ~0.55 sec, no simulations; no original primary/full gates/audits.','skipped':'All primary/mutation census and long simulations, full pipeline, lint and evidence gates per dispatch.','future':'Narrow source repair plus cheap historical-data parser; original reviewer affected confirmation; coordinator owns bounded primary/cache and combined integrated validation.'},salvage={'kind':'partial scientific salvage; complete original recovery required','retain':'Correct exact sphere moments and A<k/3 with repaired proof; exact mean Jacobian plus quadratic-mode distinction; T3 local-limit bounds and harmonic estimate; finite-plane Doeblin theorem; explicitly supplied auxiliary-field T5; honest historical finite observations.','defer':'Nonlinear infinite-plane memory decay/exponent, physical selection, nonlinear diffusion scaling, broad twist impossibility, unconditional old phase map.','no_source_loss':'Every original path, full shared-history content, complete proof, scripts and raw outputs preserved with original modes/blobs/hash; base/current-main shared files also snapshotted. No branch deletion warranted for unlanded/deferred science.'},lens_verdicts={'CodeRunner':'FAIL','PhysicsClaim':'BOUNDED after repair; original overclaims','ProofObligations':'FAIL original T1b/T2; CLOSED T3/T4 under declared model, CONDITIONAL auxiliary T5','Imports':'DISCLOSED supplied model, phase imports must narrow','NatureRetention':'not retained/Nature-ready','NoGo':'FAIL N1/N4/N5/N7 scope; certification withheld','Labeling':'not a labeling-only theorem','RepoGovernance':'FIX','AuditCompatibility':'FIX; no verdict applied'},recommendation='NEEDS NARROW SOURCE REPAIR; no landing PASS',original_head_recheck=meta,slot={'path':str(slot),'head':head,'porcelain_including_ignored':status,'release_owner':'root'},iterations=1,commits=0,full_pipeline_count=0,integration_retries=0,scientific_findings=8,source_paths=25)
p=R/'drain8170-review-original.json';assert not p.exists();p.write_text(json.dumps(report,indent=2));p.chmod(0o444)
md=['# PR8170 original independent review','',f"Original `{m['head']}`; actual merge-base `{m['merge_base']}`; frozen current-main `{m['main']}`.",'','**Needs narrow source repair. No landing PASS.** Partial science salvage is viable; complete original recovery is mandatory. One review iteration, 25 original paths, 8 material findings; no commits, primary executions, full pipelines or audit actions.','', '## Findings','']
for f in findings:md += [f"### {f['id']} — {f['title']}",f"{f['path']}:{f['lines'][0]}",'',f['detail'],'','**Narrow repair:** '+f['fix'],'']
md+=['## Independent checks','']+['- '+x for x in checks]+['','## Salvage and provenance','',report['salvage']['retain'],'',report['salvage']['defer'],'',report['salvage']['no_source_loss'],'','Per-path modes, Git blobs, SHA-256 and dispositions are in the JSON report and `drain8170-original/manifest.json`; exact original/current authority/input pins are in `drain8170-original/input-bindings.json`. Bounded control script and output are in `check8170/`. Installed review-loop entry and all used references byte-match frozen current main.','', 'Current-main preservation remains an integration obligation: shared campaign boards and topology cannot be replaced wholesale by this stale branch. No generated train outputs were read or changed.','', '## Return state','',f"PR remains OPEN, non-draft, base main, exact original head rechecked. Slot HEAD `{head}`; tracked/untracked/ignored status empty. Root owns slot release. Reviewer session retained for affected/cold/final confirmation."]
p=R/'drain8170-review-original.md';p.write_text('\n'.join(md)+'\n');p.chmod(0o444)
print(json.dumps({'json':str(R/'drain8170-review-original.json'),'md':str(p),'json_sha256':hashlib.sha256((R/'drain8170-review-original.json').read_bytes()).hexdigest(),'md_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'slot_head':head,'status':status}))
