from pathlib import Path
import json,hashlib
R=Path('/private/tmp/review-drain-20260915');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();h=json.loads((R/'drain8178-author-handoff-v1.json').read_text());refs=lambda p:dict(path=str(p),sha256=sha(p))
checks={
'finite_recurrence':'Complete supplied-law proof accepted: negative Fourier sign, diagonal Hermitian covariance, conjugate real modes, independent times, site and average variance. No nonlinear identity is inferred.',
'stationary_limit':'Backward series converges in mean square by summed geometric tails; stationarity of shifted iid noise establishes invariant law and coupling of truncations establishes convergence. This supplies the asserted limit without Gaussianity or component independence.',
'residual_scale':'Exact residual and rho bound accepted; gap lower bound16/(9L²) follows from representative norm and sine inequality. The explicit lowest candidate gives inverse-log scale asymptotic9L²/(8pi²), which together with upper relaxation bound proves orderL². L1 is separated.',
'variance_scale':'tau is real, first integer crossing ceiling; RMSsqrt2 and scalar-proxy distinction explicit. Reciprocal/exponential-series and alternating arctangent enclosure logic valid for stated positive tested parameters.',
'finite_bracket':'Complete concavity/absolute-sine proof establishes both constants at every finiteL; emptyL1 sum handled. Sharp log coefficient, constant and nonlinear link deferred.',
'new_sign_control':'U with fourth roots and real-space P directly checks UP U*=D; flipped sign differs at non-self-conjugate modes. Exact 16x16 bounded fixture; no empirical approximation.',
'new_conjugacy_control':'UU*=I and UU^T=opposite-mode permutation independently encode Hermitian/pseudo-covariance; erroneous identity differs for L4 modes.',
'new_residual_control':'Exact covariance finite sum subtracts t/L² and compares with separately summed geometric tail and rho^tV; t0 makes false zero residual fail decisively.',
'new_ceiling_control':'Rational nonintegers5/2,7/3 plus integer3 test adjacent inequalities; floor mutant fails nonintegers.',
'historical_recovery':'All21 original paths,37 available states, modes/blob/rawSHA and original delta preserved; decompressed bytes verified against original independent manifest. Full original note appears verbatim readably with explicit correction/deferred boundary.',
'negative_boundary':'No estimator impossibility or five-route certificate survives as active claim. Original failed fits, finite discrepancies and nonlinear/sharp-asymptotic arguments remain retrievable; branch retention required.',
'input_interactions':'Direct linked corrected sphere-kernel parent is the actual optional-parametrization and mean-gain source. Its bytes match already reviewed original-main source. PR8173 static identities are not used as dynamic authority.'}
reuse={
'covariance_recursion_wrong':'Direct reuse: family_c and every called math helper AST unchanged; original C failure remains valid for this mathematical control, not new full-run evidence.',
'multiplier_wrong':'B symbol sign changes positive to negative, which conjugates phi for real k and leaves u=phi*conjugate(phi) exactly unchanged; coefficient4/9->2/9 mutation unchanged. Original decisive B outcome remains applicable at formula scope.',
'memory_time_wrong':'D factor3->2, targets, rational helpers and comparisons unchanged; prose now calls tau a supplied scale. Original D failure reusable at mathematical control scope.',
'lattice_sum_bounds_wrong':'D upper9/16->5/16 and tiny-torus comparisons unchanged; original D failure reusable at mathematical control scope.'}
d=dict(pr=8178,reviewer_session='/root/review_8178',same_session=True,verdict='EARLY_AFFECTED_SOURCE_ACCEPTED',source_acceptance=True,capture_clearance=False,landing_clearance=False,base=h['base'],original_head=h['original_head'],handoff=refs(R/'drain8178-author-handoff-v1.json'),source_coverage=h['source_files'],source_freeze=refs(R/'drain8178-prepared-v1-source-freeze.json'),identity_check=refs(R/'check8178/early-v1-identities.json'),checks=checks,original_findings={f'8178-{i}':'addressed in prepared-v1 source boundary/recovery; final packaging/evidence gates pending' for i in range(1,8)},material_science_blockers=[],blockers=[],execution_authorization='None granted by this report; early source acceptance only. Actual-main/tooling refresh, frozen adapter/current-source cold confirmation and controlled capture still required.',resource_plan_acceptance=dict(wall_seconds=60,sampled_aggregate_process_tree_rss_bytes=402653184,poll_seconds=.02,status='reasonable proposed enforced limit, not a new measured success',basis='original1.125s/91MB plus four small exact controls; no large lattice or stochastic loops; terminate and preserve on violation without automatic retry'),original_control_reuse=reuse,new_controls_pending=list(json.loads((R/'drain8178-author-input-resource-plan-v1.json').read_text())['future_changed_claim_controls']),production_executions=0,science_reruns=0,source_edits=0,staging=0,gates=0,remaining=['Refresh actual-main and helper maps/review skill, checking input/premise interactions.','Complete current source/machine-status/portable-discovery conformance and candidate source freeze; this scientific acceptance does not claim mechanical gate success.','Cold-review exact capture adapter, raw output preservation, source pins and once-only execution plan before baseline.','Execute only authorized final baseline/new controls and verify final evidence, original reviewer same-session final confirmation and coordinator combined gate.'],branch_retention_required=True)
p=R/'drain8178-early-review-v1.json';p.open('x').write(json.dumps(d,indent=2)+'\n')
s='# PR8178 early affected-source review v1\n\n**EARLY AFFECTED SOURCE ACCEPTED. No material scientific blockers found.** This is the original reviewer `/root/review_8178`, same session. No capture, cold, final or landing clearance is granted.\n\nThe complete live finite proofs correctly distinguish the supplied auxiliary recurrence from the nonlinear sphere law. Fourier signs/conjugacy, stationary limit, exact residual, L² relaxation order, real variance scale/ceiling and finite bracket are repaired. Sharp logarithmic and nonlinear diffusion/memory proposals remain fully preserved and explicitly deferred. All seven original finding groups are addressed at this source boundary.\n\nAll43 prepared paths match the handoff; all21 original paths and37 available base/head/main states recover exactly with raw hashes and Git blobs. The full original note is verbatim in the readable deferred appendix. The original branch remains required. The actual sphere-kernel parent is unchanged from the reviewed source and supplies no exact gain-one nonlinear dynamics.\n\nThe four new exact controls are logically decisive for sign, conjugacy, zero-start residual and ceiling. No corrected control or baseline was executed. Original four mathematical mutation results may be reused only at their unchanged mathematical scope; the JSON records each applicability argument. The proposed60-second/384MiB sampled aggregate process-tree limits are reasonable given the original measurement and added small matrices, with fail-and-preserve/no automatic retry.\n\nNext: actual-main/tooling/skill refresh, mechanical conformance and source freeze, exact cold adapter review, authorized once-only capture/new controls, and same-session final confirmation. This report performs no source edit, staging, production baseline, science rerun or gate.\n'
(R/'drain8178-early-review-v1.md').open('x').write(s)
print(sha(p))
