from pathlib import Path
import json,hashlib,subprocess
b=Path('/private/tmp/toe-autonomous-native-ladder-20260907/finite-pw-charged-upper');root=Path('/private/tmp/toe-campaign-20260907/finite-cutoff-static-energy');dest=b/'staging/scripts/gauge_wilson_finite_pw_actual_r1_charged_energy_check_2026_09_07.py'
prior=(b/'staging/scripts/gauge_wilson_finite_pw_charged_energy_controls_2026_09_07.py').read_text();header=prior[:prior.index('import time,resource,json,hashlib,itertools')]
raw=(root/'actual_r1_check.py').read_text();code=raw[raw.index('from fractions'):raw.index('print(json.dumps(result,indent=2))')]
scopes={'per_element':{'checks':5,'scope':'actual Haar Gram/magnetic entries and source-normalization/isometry adverse controls'},'per_site':{'checks':5,'scope':'actual neutral character matrices and full-carrier ground identification'},'per_mode':{'checks':5,'scope':'accepted norm, shell/local budgets and strict finite excess'},'per_block':{'checks':4,'scope':'three exact rational radical enclosures and local energy theorem comparison'},'lattice_wide':{'checks':3,'scope':'failed crude sufficient budget, failed exact-four transfer and distant vacuum normalization adverse; one plaquette only'}}
code+="\nresult.update({'TOTAL':result['check_count'],'source_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'seconds':time.monotonic()-_started,'rss_MiB':_rss()})\n_emit(result,22,"+repr(scopes)+")\n"
dest.write_text(header+code)
r=json.loads(subprocess.check_output(['python3',str(dest),'--json']));old=json.loads((root/'actual_r1_result.json').read_text());meta={'TOTAL','source_sha256','seconds','rss_MiB','N5_scopes','resource_limits'}
assert {k:v for k,v in r.items() if k not in meta}=={k:v for k,v in old.items() if k not in meta}
(b/'ACTUAL_R1_CANONICAL_RESULT.json').write_text(json.dumps(r,sort_keys=True,indent=2,allow_nan=False)+'\n');(b/'ACTUAL_R1_CANONICAL_STDOUT.txt').write_bytes(subprocess.check_output(['python3',str(dest)]));bad=subprocess.run(['python3',str(dest),'--bad'],capture_output=True);assert bad.returncode
receipt={'source':dest.name,'source_sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'original_sha256':hashlib.sha256((root/'actual_r1_check.py').read_bytes()).hexdigest(),'TOTAL':22,'scientific_payload_identical':True,'ignored_metadata':sorted(meta),'count_semantics':'TOTAL aliases original check_count22; resource/interface guards not new mathematical checks','strict_cli_adverse_returncode':bad.returncode,'seconds':r['seconds'],'rss_MiB':r['rss_MiB']};(b/'ACTUAL_R1_PORT_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt,indent=2))
