"""A48 shared helpers: proper cubic turns, Clifford (Pauli-axis) rotations, homomorphisms,
GF(2) solver (from A45 f1), SU(2) lifts, Pauli types."""
import itertools
import numpy as np

# ---------- the 24 proper turns (also = the 24 Clifford rotations of the Pauli axes) ----------
def proper_rotations():
    out = []
    for perm in itertools.permutations(range(3)):
        for signs in itertools.product([1, -1], repeat=3):
            M = np.zeros((3, 3), dtype=int)
            for i, p in enumerate(perm):
                M[p, i] = signs[i]
            if round(np.linalg.det(M)) == 1:
                out.append(M)
    return out

ROT = proper_rotations()
assert len(ROT) == 24
def key(M):
    return tuple(int(round(v)) for v in np.asarray(M).ravel())
RIDX = {key(M): k for k, M in enumerate(ROT)}
MUL = [[RIDX[key(A @ B)] for B in ROT] for A in ROT]
ID = RIDX[key(np.eye(3, dtype=int))]
INV = [next(j for j in range(24) if MUL[i][j] == ID) for i in range(24)]
DIRS = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]
NAMES = ['+x', '-x', '+y', '-y', '+z', '-z']
AXIS = [0, 0, 1, 1, 2, 2]
SIGN = [1, -1, 1, -1, 1, -1]
def dir_index(v):
    return DIRS.index(tuple(int(x) for x in v))
PERM = [[dir_index(R @ np.array(d)) for d in DIRS] for R in ROT]

def order(k):
    g, n = k, 1
    while g != ID:
        g = MUL[g][k]; n += 1
    return n

def rot_about(axis, quarter_turns):
    """index of the rotation by quarter_turns*90deg about a coordinate axis (0,1,2), or by
    120deg*quarter_turns about (1,1,1) if axis == 'd'."""
    if axis == 'd':
        M = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
        out = np.eye(3, dtype=int)
        for _ in range(quarter_turns % 3):
            out = M @ out
        return RIDX[key(out)]
    a = axis; b, c = (a + 1) % 3, (a + 2) % 3
    M = np.eye(3, dtype=int)
    Q = np.zeros((3, 3), dtype=int); Q[a, a] = 1; Q[c, b] = 1; Q[b, c] = -1
    for _ in range(quarter_turns % 4):
        M = Q @ M
    return RIDX[key(M)]

C4 = [rot_about(a, 1) for a in range(3)]
C2 = [rot_about(a, 2) for a in range(3)]
C3d = rot_about('d', 1)

def closure(gens):
    S = {ID}; frontier = [ID]
    while frontier:
        new = []
        for g in frontier:
            for s in gens:
                h = MUL[g][s]
                if h not in S:
                    S.add(h); new.append(h)
        frontier = new
    return sorted(S)

GROUPS = {
    'O (24 turns)': closure([C4[2], C3d]),
    'T (12 even turns)': closure([C2[2], C3d]),
    'D2 (3 axis half-turns)': closure([C2[0], C2[2]]),
    '{1, C2z}': closure([C2[2]]),
}

def homs(group, gens, target=range(24)):
    """all homomorphisms group -> ROT (as dicts index->index), group generated by gens."""
    res = []
    for imgs in itertools.product(list(target), repeat=len(gens)):
        phi = {ID: ID}; frontier = [ID]; ok = True
        while frontier and ok:
            new = []
            for g in frontier:
                for s, im in zip(gens, imgs):
                    h = MUL[g][s]; hi = MUL[phi[g]][im]
                    if h in phi:
                        if phi[h] != hi:
                            ok = False; break
                    else:
                        phi[h] = hi; new.append(h)
                if not ok:
                    break
            frontier = new
        if ok and len(phi) == len(group):
            if all(phi[MUL[a][b]] == MUL[phi[a]][phi[b]] for a in group for b in group):
                res.append(phi)
    return res

# ---------- Pauli types: 0 = I, 1 = X, 2 = Y, 3 = Z ----------
def ptype(k, t):
    """type of the image of Pauli type t under Clifford rotation ROT[k]."""
    if t == 0:
        return 0
    col = ROT[k][:, t - 1]
    return int(np.nonzero(col)[0][0]) + 1

def anti(t1, t2):
    return int(t1 != 0 and t2 != 0 and t1 != t2)

# ---------- GF(2) consistency (A45 f1) ----------
def gf2_consistent(rows):
    pivots = {}
    for mask, rhs in rows:
        m, r = mask, rhs
        while m:
            p = m.bit_length() - 1
            if p in pivots:
                pm, pr = pivots[p]; m ^= pm; r ^= pr
            else:
                pivots[p] = (m, r); break
        if m == 0 and r == 1:
            return False
    return True

def gf2_solve(rows, nvar):
    """return one solution (list of bits) or None."""
    pivots = {}
    for mask, rhs in rows:
        m, r = mask, rhs
        while m:
            p = m.bit_length() - 1
            if p in pivots:
                pm, pr = pivots[p]; m ^= pm; r ^= pr
            else:
                pivots[p] = (m, r); break
        if m == 0 and r == 1:
            return None
    x = [0] * nvar
    for p in sorted(pivots):            # back-substitute from low pivots up
        m, r = pivots[p]
        val = r
        mm = m & ~(1 << p)
        while mm:
            q = mm.bit_length() - 1
            val ^= x[q]; mm &= ~(1 << q)
        x[p] = val
    return x

def link_system(group, statistics, e=None, allow_switch=True):
    """A45's census system: unknowns d(i,j) i != j (30), y_i (6), c_g(i) (6 per element).
    e[i][j] = extra anticommutation (mod 2) of hops i, j from non-link qubits."""
    pairs = [(i, j) for i in range(6) for j in range(6) if i != j]
    dvar = {p: k for k, p in enumerate(pairs)}
    yvar = {i: 30 + i for i in range(6)}
    cvar = {}; nxt = 36
    for gi in group:
        for i in range(6):
            cvar[(gi, i)] = nxt; nxt += 1
    rows = []
    for gi in group:
        P = PERM[gi]
        for (i, j) in pairs:
            m = (1 << dvar[(P[i], P[j])]) ^ (1 << dvar[(i, j)])
            if allow_switch:
                m ^= (1 << cvar[(gi, i)])
            rows.append((m, 0))
    target = 1 if statistics == 'fermion' else 0
    for i in range(6):
        for j in range(i + 1, 6):
            m = (1 << dvar[(i, j)]) ^ (1 << dvar[(j, i)]) ^ (1 << yvar[i]) ^ (1 << yvar[j])
            rows.append((m, target ^ (e[i][j] if e is not None else 0)))
    return rows, nxt, dvar, yvar, cvar

# ---------- SU(2) ----------
I2 = np.eye(2, dtype=complex)
SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]])
SZ = np.diag([1, -1]).astype(complex)
PAUL = [I2, SX, SY, SZ]

def su2_of_rot(R):
    """an SU(2) matrix U with U sigma_a U^dag = sum_b R[b,a] sigma_b."""
    R = np.asarray(R, dtype=float)
    ang = np.arccos(np.clip((np.trace(R) - 1) / 2, -1, 1))
    if abs(ang) < 1e-12:
        return I2.copy()
    if abs(ang - np.pi) < 1e-9:
        # axis from R + I
        Mx = (R + np.eye(3)) / 2
        k = int(np.argmax(np.diag(Mx)))
        n = Mx[:, k] / np.sqrt(Mx[k, k])
    else:
        n = np.array([R[2, 1] - R[1, 2], R[0, 2] - R[2, 0], R[1, 0] - R[0, 1]]) / (2 * np.sin(ang))
    U = np.cos(ang / 2) * I2 - 1j * np.sin(ang / 2) * (n[0] * SX + n[1] * SY + n[2] * SZ)
    # verify
    for a in range(3):
        img = U @ PAUL[a + 1] @ U.conj().T
        tgt = sum(R[b, a] * PAUL[b + 1] for b in range(3))
        assert np.linalg.norm(img - tgt) < 1e-9, "su2 lift failed"
    return U

def rot_axis_angle(n, ang):
    n = np.asarray(n, dtype=float); n = n / np.linalg.norm(n)
    K = np.array([[0, -n[2], n[1]], [n[2], 0, -n[0]], [-n[1], n[0], 0]])
    return np.eye(3) + np.sin(ang) * K + (1 - np.cos(ang)) * (K @ K)

def kron_list(ops):
    out = np.array([[1.0 + 0j]])
    for o in ops:
        out = np.kron(out, o)
    return out

def raise_out(link):
    """U(1) raising of the outward field s*sigma^a on the link in direction `link` (A45)."""
    a = AXIS[link]; b = (a + 1) % 3; c = (a + 2) % 3; s = SIGN[link]
    return (PAUL[b + 1] + s * 1j * PAUL[c + 1]) / 2

def tjunction_phase(t1, t2, t3):
    X1 = t1 @ t2.conj().T @ t3
    X2 = t3 @ t2.conj().T @ t1
    nrm = np.vdot(X2, X2).real
    if nrm < 1e-12:
        return None, None
    c = np.vdot(X2, X1) / nrm
    return c, np.linalg.norm(X1 - c * X2) / np.sqrt(nrm)
