from pathlib import Path
import subprocess,json,hashlib,sys
w=Path('/private/tmp/review-drain-20260915/unit8016');out=Path('/private/tmp/review-drain-20260915');scratch=out/'check8016'
def git(*a):return subprocess.check_output(['git',*a],cwd=w,text=True).strip()
def sha(b):return hashlib.sha256(b).hexdigest()
def blob(ref,p):return subprocess.check_output(['git','show',ref+':'+p],cwd=w)
base=git('rev-parse','HEAD');source=git('diff','--cached','--name-only').splitlines()
weak=next(p for p in source if p.startswith('docs/') and 'WEAK' in p);sad=next(p for p in source if p.startswith('docs/') and 'NONLINEAR' in p);cov=next(p for p in source if p.startswith('docs/') and 'COVARIANCE' in p)
wr=next(p for p in source if p.startswith('scripts/') and 'weak' in p);sr=next(p for p in source if p.startswith('scripts/') and 'adapted' in p);cr=next(p for p in source if p.startswith('scripts/') and 'covariance' in p)
records=[];members=[]
for pr,h,declared in [(8013,'fc49894fc09b33042752f69bf33d637955bee208','main'),(8016,'2343266be6c4faf3ba9112ec1cab56b00c471c52','codex/spatial-wilson-weak-coupling-block20-20260907')]:
 mb=git('merge-base',base,h);paths=git('diff','--name-status',mb,h).splitlines();members.append({'pr':pr,'head':h,'declared_base':declared,'actual_merge_base_to_confirmation_base':mb,'original_path_count':len(paths)})
 for line in paths:
  st,p=line.split('\t',1);d={'pr':pr,'original_path':p,'status':st,'original_blob':git('rev-parse',h+':'+p),'original_sha256':sha(blob(h,p)),'recovery':h+':'+p}
  target=weak if 'weak-coupling' in p else (sad if '/native-originals/' in p or '/orbital-review/' in p or 'structural_runner' in p else cov)
  if p in source:d.update(disposition='narrowed',final_path=p,reason='Scientific statement retained; exact input-to-output binding, scope certificates, historical recovery wording and counts corrected.')
  elif p=='docs/audit/data/citation_graph_manifest.json':d.update(disposition='superseded',reason='Generated topology acknowledgment, requires current combined-tree regeneration, not stale reuse.')
  elif p.endswith('.py'):
   targetr=wr if 'weak-coupling' in p else sr if ('adapted_tree' in p or 'structural_runner' in p) else cr
   if 'before' in p:d.update(disposition='narrowed',final_path=targetr,reason='Failed iterator/prefactor or stale scope output retained only as historical recovery; corrected mathematics/control is canonical, failure explained in note.')
   else:d.update(disposition='superseded',final_path=targetr,reason='Original code scientific core present in combined canonical runner; exact geometry/Gaussian controls now connected.')
  elif any(x in p for x in ['DERIVATION','PREREGISTRATION','DISK_WORD_CERTIFICATE','UNTRUNCATED_NORM_COROLLARY','BETA6_SANITY_PROOF','PROOF_REVIEW','NO_GO_DISCIPLINE','NO_GO_LEDGER','FAILED_CONTROLS','ITERATOR_FAILURE','cube-source-gaussian-review','cube-nonlinear-saddle-review','orbital-review','primary-review','INDEPENDENT_REVIEW','PRIMARY_REVIEW','ORBITAL_REVIEW','ROOT_ACTUAL_CUBE_HS_SPECTRUM_REVIEW']) or '/docs/' in p or '/staging/GAUGE_' in p:
   d.update(disposition='superseded',final_path=target,reason='All valid proof/conditions/constants/obstructions recovered in canonical three-note argument. Prior reviewer authority not imported. Alternate cyclic disk word is equivalent orientation; original failure and finite-target history remain at frozen head.')
  elif p.endswith(('result.json','RESULT.json','canonical-live.json','structural_runner_after_scope_reporting_fix.json')):
   targetr=wr if 'weak-coupling' in p else sr if 'adapted_tree' in p or 'structural_runner' in p or '/native-originals/' in p else cr
   d.update(disposition='superseded',final_path=targetr,reason='Original exact scientific matrices/words/constants compared with regenerated canonical JSON; timing/source identities stay original, fresh cache owns current execution evidence.')
  else:d.update(disposition='rejected',reason='Non-source planning/status/provenance or historical validation receipt. Inspected for unique source obligations; not imported as review/audit authority. Frozen original retains recovery.')
  if 'final_path' in d:
   q=d['final_path'];d.update(final_blob=git('rev-parse',':'+q),final_sha256=sha((w/q).read_bytes()))
  records.append(d)
inputs=[('docs/MINIMAL_AXIOMS_2026-06-29.md','Current premise authority previously read and hash-bound in8011; verified unchanged. Wilson/Haar/source map remain conditional.'),('docs/ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','Current classification procedure; no approved primitive needed.'),('docs/audit/data/axiom_premise_nodes.json','Registry read and unchanged; no unapproved primitive adopted.'),('docs/GAUGE_WILSON_CUBE_SLAB_CHARACTER_MIXING_BOUNDED_THEOREM_NOTE_2026-09-07.md','Exact finite model/full-space stripping; restored Haar gauges; reflection quadratic form and strictly nonzero projected function for fundamental positivity; positive D and source isometry. Earlier perturbative enumeration not used.'),('docs/GAUGE_WILSON_SU3_ALL_WEIGHT_POSITIVE_COEFFICIENT_FORMAL_BRIDGE_NOTE_2026-06-07.md','Normalized Haar, dimension, highest-weight tensor occurrence, positive Wilson character coefficients and uniform expansion; no formal arbitrary-sequence completion imported.'),('docs/GAUGE_TEMPORAL_GAUGE_MIXED_KERNEL_SPATIAL_LINK_FACTORIZATION_NARROW_THEOREM_NOTE_2026-05-10.md','Temporal plaquette exact factorization and normalized Schur/Peter–Weyl eigenvalue convention. No physical transfer identification imported.')]
data={'unit':'PR8013+PR8016','reviewer_session':'/root/review_8011','members':members,'confirmation_base':base,'reviewed_staged_tree':git('write-tree'),'reviewed_source_commits':[],'state':'staged candidate','original_disposition_map':records,'disposition_map_sha256':sha(json.dumps(records,sort_keys=True,separators=(',',':')).encode()),'source_paths':[{'path':p,'blob':git('rev-parse',':'+p),'sha256':sha((w/p).read_bytes())} for p in source],'inputs':[{'path':p,'blob':git('rev-parse','HEAD:'+p),'sha256':sha((w/p).read_bytes()),'coverage':scope} for p,scope in inputs],'runtime_inputs':'Python standard library and SymPy only; runners read own __file__ for source identity, no external mathematical runtime files and no cross-runner execution. SymPy version recorded in checks.','constituent_reconciliation':{'pair_merge_base':git('merge-base',members[0]['head'],members[1]['head']),'8013_is_ancestor_8016':False,'overlap':json.loads((scratch/'constituent-overlap.json').read_text()),'conclusion':'Non-ancestral parent head is fully accounted: fifty paths identical including all science, five differing paths are four historical sync receipts/logs and generated manifest.'},'current_main_loss_check':'Nine source paths are additions absent on confirmation base. No current-main source deleted/replaced. Existing corrected parent definitions retained. Generated manifest deferred for combined regeneration.','claims':{'weak':'fixed finite-character outer-dimension limit and explicit logarithmic rate; fundamental0<R<3; fixed-vacuum norm divergence; finite paired-side-removal control','saddle':'conditional actual nonlinear 136-dimensional gauge-fixed saddle; uniform16-dimensional marginal L2 bound; beta^-4 chart-dilated central HS limit and fixed nonzero branches','covariance':'rational geometry, Haar tangent normalization, central invariant Gaussian spectrum; absolute top-norm asymptotic and finite-beta6 accuracy boundary'},'findings':{'F1':'fixed source packet/runner evidence and accurate historical recovery wording','F2':'fixed computed geometry-to-Gaussian bridge and fixture/determinant assertions; original wrong-weight surviving mutation retained'},'independent_evidence':json.loads((scratch/'independent.json').read_text()),'final_controls':json.loads((scratch/'final-controls.json').read_text()) if (scratch/'final-controls.json').exists() else None,'combined_gate':'pending coordinator; no full pipeline per unit','full_pipeline_count':0,'verdict':'FINAL VERDICT: PASS' if '--final' in sys.argv else 'pending corrections confirmation','verdict_scope':'source only; no audit status or landing grant'}
report=out/'review-8016.md';data['findings_sha256']=sha(report.read_bytes());(out/'review-8016.json').write_text(json.dumps(data,indent=2)+'\n');print(data['reviewed_staged_tree'],data['verdict'])
