#!/usr/bin/env python3
"""J:attack:PR8151 - block 17 (PR #8151), attack pattern (a) WITNESS REALIZABILITY applied to the chessboard step: T3 states that for the
event 'the direction-i bond at the origin corner of the cell is bad' the image in every cell under the site reflections theta_{i,k}
(x_i -> 2k - x_i) is 'the corresponding bond' and that the disseminated event is 'every direction-i bond is bad'; T4 bounds that event by
(6m/p)^N; T5-T7 then use mu_L(B bad) <= (6m/p)^(n/d).  Here the reflection images are computed literally on the tori (Z/2LZ)^d, and the
consequences are evaluated:
  [geometry] the orbit of (cell 0, its canonical direction-1 bond) under the group generated by all theta_{i,k}: for every cell the
     image bond (path-independent), whether it is that cell's canonical bond, and the union of the images (the disseminated event);
  [2D exact] on the 4x4 torus (6 values; exact transfer matrix in floating point at 40 couplings (p, q, r)) the probabilities of the
     canonical-bond event A, of the realized disseminated event D_even (every direction-1 bond with even transverse coordinate bad) and of
     T3's stated D_all (every direction-1 bond bad), and the stated inequalities mu(A) <= mu(D_all)^(1/N), mu(row) <= mu(D_all)^(4/N),
     mu(D_even) <= mu(D_all)^(8/N); the minimal number of bad bonds in D_even and D_all on 4x4 (exact min-plus transfer);
  [3D] an explicit configuration of the realized disseminated event on (Z/2LZ)^3 with only 3N/4 bad bonds (lines with both transverse
     coordinates even alternate, all other lines constant), hence mu(D_even)^(1/N) >= (m/p)^(3/4)/6 for p >= m, which exceeds T4's
     6m/p once p/m > 36^4; and the thresholds the note's own counting gives with the realized events.
HIT if the realized disseminated event differs from 'every direction-i bond is bad' (the geometric claim of T3), or a stated inequality
fails numerically.
"""
import itertools
import math
import sys
import time

import numpy as np


# ------------------------------------------------------------------------------------------------ geometry of the reflections
def reflect_cell(c, i, k, S):
    c = list(c)
    c[i] = (2 * k - c[i] - 1) % S
    return tuple(c)


def reflect_bond(b, i, k, S):
    x, j = b
    y = list(x)
    y[i] = (2 * k - x[i]) % S
    if j == i:                                   # the bond {x, x + e_i} goes to {theta x, theta x - e_i}
        y[i] = (y[i] - 1) % S
    return (tuple(y), j)


def orbit(d, S, j=0):
    c0 = (0,) * d
    b0 = (c0, j)
    seen = {(c0, b0)}
    stack = [(c0, b0)]
    while stack:
        c, b = stack.pop()
        for i in range(d):
            for k in range(S):
                nc, nb = reflect_cell(c, i, k, S), reflect_bond(b, i, k, S)
                if (nc, nb) not in seen:
                    seen.add((nc, nb))
                    stack.append((nc, nb))
    per_cell = {}
    for c, b in seen:
        per_cell.setdefault(c, set()).add(b)
    return per_cell


def geometry_report(d, S):
    per = orbit(d, S)
    N = S ** d
    path_indep = all(len(v) == 1 for v in per.values()) and len(per) == N
    canonical = sum(1 for c, v in per.items() if next(iter(v)) == (c, 0))
    union = set().union(*per.values())
    even = {((x,) + tuple(t), 0) for x in range(S) for t in itertools.product(range(0, S, 2), repeat=d - 1)}
    return N, path_indep, canonical, len(union), union == even


# ------------------------------------------------------------------------------------------------ 2D exact on the 4 x 4 torus
def phi_matrix(p, q, r):
    M = np.full((6, 6), float(r))
    for a in range(6):
        M[a, a] = p
        M[a, a ^ 1] = q
    return M


def torus2d_probs(p, q, r, S=4):
    ph = phi_matrix(p, q, r) / p
    rows = np.array(list(itertools.product(range(6), repeat=S)))
    hor = np.ones(len(rows))
    bad_all = np.ones(len(rows), dtype=bool)
    for x in range(S):
        hor *= ph[rows[:, x], rows[:, (x + 1) % S]]
        bad_all &= rows[:, x] != rows[:, (x + 1) % S]
    bad0 = rows[:, 0] != rows[:, 1]
    V = np.ones((len(rows), len(rows)))
    for x in range(S):
        V *= ph[rows[:, x][:, None], rows[:, x][None, :]]

    def Z(masks):
        M = np.eye(len(rows))
        for lev in range(S):
            w = hor * masks[lev]
            M = M @ (w[:, None] * V)
        return np.trace(M)

    one = np.ones(len(rows))
    Z0 = Z([one] * S)
    pA = Z([bad0.astype(float)] + [one] * (S - 1)) / Z0
    pall = Z([bad_all.astype(float)] * S) / Z0
    peven = Z([bad_all.astype(float) if lev % 2 == 0 else one for lev in range(S)]) / Z0
    prow = Z([bad_all.astype(float)] + [one] * (S - 1)) / Z0
    return pA, prow, peven, pall


def min_bad_2d(S=4, even_only=True):
    """Minimal number of bad bonds on the S x S torus among configurations with every direction-1 bond bad at even rows (even_only) or at
    every row; exact min-plus transfer over rows (6 values)."""
    rows = list(itertools.product(range(6), repeat=S))
    hb = np.array([sum(r[x] != r[(x + 1) % S] for x in range(S)) for r in rows])
    allbad = np.array([all(r[x] != r[(x + 1) % S] for x in range(S)) for r in rows])
    R = np.array(rows)
    vb = np.zeros((len(rows), len(rows)), dtype=np.int64)
    for x in range(S):
        vb += (R[:, x][:, None] != R[:, x][None, :])
    INF = 10 ** 9
    best = INF
    for start in range(len(rows)):
        if not allbad[start]:
            continue
        cost = np.full(len(rows), INF, dtype=np.int64)
        cost[start] = hb[start]
        for lev in range(1, S):
            ok = allbad if (lev % 2 == 0 or not even_only) else np.ones(len(rows), dtype=bool)
            nxt = (cost[:, None] + vb).min(axis=0) + hb
            nxt[~ok] = INF
            cost = nxt
        best = min(best, int((cost + vb[:, start]).min()))
    return best


# ------------------------------------------------------------------------------------------------ 3D construction
def three_d_witness(S):
    """Lines along direction 1 with both transverse coordinates even alternate a, b; all other sites a."""
    a, b = 0, 1
    val = {}
    for x, y, z in itertools.product(range(S), repeat=3):
        val[(x, y, z)] = (a if x % 2 == 0 else b) if (y % 2 == 0 and z % 2 == 0) else a
    N = S ** 3
    bad = 0
    event = True
    for x, y, z in itertools.product(range(S), repeat=3):
        for j, e in enumerate(((1, 0, 0), (0, 1, 0), (0, 0, 1))):
            u = ((x + e[0]) % S, (y + e[1]) % S, (z + e[2]) % S)
            isbad = val[(x, y, z)] != val[u]
            bad += isbad
            if j == 0 and y % 2 == 0 and z % 2 == 0 and not isbad:
                event = False
    return N, bad, event


def main():
    t0 = time.time()
    hits, info = [], []
    # geometry
    geo = []
    for d, S in ((2, 4), (2, 6), (2, 8), (3, 4), (3, 6)):
        N, pi, canon, union, is_even = geometry_report(d, S)
        print(f"[geometry] d = {d}, side {S}: the image of cell 0's canonical direction-1 bond is path-independent in all {N} cells: {pi}; it is "
              f"the canonical bond of its cell in {canon} of {N} cells; the disseminated event is {union} bonds = the direction-1 bonds with all "
              f"transverse coordinates even: {is_even} (T3 states every direction-1 bond, {N} bonds)")
        geo.append((d, S, N, canon, union, is_even))
    if any(g[4] != g[2] for g in geo):
        hits.append("T3 misidentifies the disseminated event: under the site reflections theta_(i,k) the images of 'the canonical direction-1 bond of "
                    "the cell is bad' cover only the direction-1 bonds with even transverse coordinates (" +
                    ", ".join(f"{g[4]} of {g[2]} on (Z/{g[1]}Z)^{g[0]}" for g in geo) + "), and the image is the cell's own canonical bond in only "
                    "1/2 (2D) or 1/4 (3D) of the cells; T4 bounds 'every direction-i bond bad', a strictly smaller event than the one the "
                    "chessboard estimate produces")
    # 2D exact numbers
    worst = {"A": 0.0, "row": 0.0, "even": 0.0}
    viol = []
    grid = [(p, q, r) for p in (1, 1.5, 2, 3, 5, 8, 12, 20, 50, 100) for q, r in ((1, 1), (1, 2), (2, 1), (0.5, 1))]
    for p, q, r in grid:
        pA, prow, peven, pall = torus2d_probs(p, q, r)
        N = 16
        ra, rr, re = pA / pall ** (1 / N), prow / pall ** (4 / N), peven / pall ** (8 / N)
        worst["A"], worst["row"], worst["even"] = max(worst["A"], ra), max(worst["row"], rr), max(worst["even"], re)
        if max(ra, rr, re) > 1 + 1e-9:
            viol.append((p, q, r, ra, rr, re))
    print(f"[2D 4x4] at {len(grid)} couplings: largest ratios mu(A)/mu(D_all)^(1/16) = {worst['A']:.6f}, mu(row)/mu(D_all)^(4/16) = "
          f"{worst['row']:.6f}, mu(D_even)/mu(D_all)^(8/16) = {worst['even']:.6f} (T3 as stated needs <= 1); {len(viol)} violations "
          f"{'e.g. ' + str(tuple(round(x, 4) for x in viol[0])) if viol else ''}")
    if viol:
        hits.append(f"T3 as stated (disseminated event 'every direction-1 bond bad') fails on the 4x4 torus at {len(viol)} couplings, e.g. "
                    f"(p,q,r) = {viol[0][:3]}: ratios {tuple(round(x, 6) for x in viol[0][3:])}")
    mb_even, mb_all = min_bad_2d(4, True), min_bad_2d(4, False)
    print(f"[2D 4x4] minimal number of bad bonds: {mb_even} in the realized disseminated event D_even, {mb_all} in D_all (N = 16); T4's counting "
          f"needs at least N")
    # 3D
    wit_ok = True
    for S in (4, 6):
        N, bad, ev = three_d_witness(S)
        wit_ok = wit_ok and ev and 4 * bad == 3 * N
        print(f"[3D] side {S}: an explicit configuration with every direction-1 bond of even transverse coordinates bad has {bad} bad bonds = "
              f"{bad / N:.2f} N (event holds: {ev}); hence mu(D_even)^(1/N) >= (m/p)^(3/4)/6 for p >= m (Z <= 6^N p^(3N))")
    thr = 36 ** 4
    if wit_ok:
        hits.append(f"T7's per-cell rate: in 3D the realized disseminated event contains configurations with 3N/4 bad bonds (explicit, sides 4 and 6), "
                    f"so mu_L(D_even)^(1/N) >= (m/p)^(3/4)/6, which exceeds T4's 6m/p for p/m > 36^4 = {thr}; the chain T3 + T4 used in T7 therefore "
                    f"does not give epsilon = 6m/p, and T7's threshold p >= 216m is not established by the written argument (the note's own counting "
                    f"with the realized events gives p >= 216^4 m in 3D and p >= 216^2 m in 2D; 2D could be restored to 216m by a lemma giving at "
                    f"least N bad bonds in D_even, which holds on the 4x4 torus)")
    print(f"[3D] (m/p)^(3/4)/6 > 6m/p exactly when p/m > 36^4 = {thr}: beyond that the realized disseminated event cannot obey T4's bound; "
          f"with the note's own counting the realized events give per-cell rates 6(m/p)^(1/2) in 2D (forced N/2 bad bonds; p >= 216^2 m = "
          f"{216 ** 2} m for epsilon <= 1/36) and 6(m/p)^(1/4) in 3D (forced N/4; p >= 216^4 m = {216 ** 4} m); a lemma giving at least N bad "
          f"bonds would restore 6m/p in 2D (4x4 minimum: {mb_even}), while in 3D configurations with 3N/4 bad bonds exist")
    print(f"[time] {time.time() - t0:.0f}s")
    for h in hits[:6]:
        print("HIT: " + h)
    print(f"SUMMARY: attack pattern (a) WITNESS REALIZABILITY on T3's chessboard dissemination - the site reflections theta_(i,k) map the "
          f"canonical direction-1 bond of cell 0 to the canonical bond of the image cell only when the transverse offsets are even; the realized "
          f"disseminated event is the direction-1 bonds with even transverse coordinates (N/2 in 2D, N/4 in 3D), not 'every direction-i bond' as "
          f"T3 states and T4 bounds; on 4x4 the stated inequalities happen to hold (largest ratio {max(worst.values()):.4f}) and D_even needs "
          f"{mb_even} bad bonds, but in 3D D_even contains configurations with 3N/4 bad bonds, so mu(D_even)^(1/N) >= (m/p)^(3/4)/6 > 6m/p for "
          f"p/m > 36^4: T7's threshold p >= 216m is not established by the written chain (2D needs a lemma the note lacks); attack {'FIRES' if hits else 'does not fire'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
