"""T34 Test A7: does the repo's own staggered structure supply a chiral (L-only) weak su(2)?
Rebuilds (independently) the 4D C^16 construction of scripts/frontier_right_handed_sector.py PART 4-5."""
import numpy as np
I2 = np.eye(2, dtype=complex)
sx = np.array([[0, 1], [1, 0]], dtype=complex); sy = np.array([[0, -1j], [1j, 0]], dtype=complex); sz = np.diag([1, -1]).astype(complex)
def k4(a, b, c, d): return np.kron(a, np.kron(b, np.kron(c, d)))
G = [k4(sz, sz, sz, sx), k4(sx, I2, I2, I2), k4(sz, sx, I2, I2), k4(sz, sz, sx, I2)]
G5 = G[0] @ G[1] @ G[2] @ G[3]
I16 = np.eye(16)
assert np.allclose(G5 @ G5, I16) and np.allclose(G5, G5.conj().T)
PL, PR = (I16 + G5) / 2, (I16 - G5) / 2
T = [0.5 * k4(s, I2, I2, I2) for s in (sx, sy, sz)]
print("A7a  KS su(2) vs gamma_5:")
res = []
for k, t in enumerate(T, 1):
    c = np.linalg.norm(t @ G5 - G5 @ t); a = np.linalg.norm(t @ G5 + G5 @ t)
    rel = "commutes" if c < 1e-9 else "anticommutes" if a < 1e-9 else "neither"
    res.append(rel); print(f"    T{k}: {rel}")
A7a = res == ["anticommutes", "commutes", "anticommutes"]
C = sum(t @ t for t in T)
w = np.linalg.eigvalsh(C)
A7b = np.allclose(w, 0.75)
print("A7b  Casimir spectrum on C^16 (all equal 3/4 => 8 doublets, no singlets):", np.unique(w.round(9)), A7b)
# chirality-projected generators and the Lie algebra they generate
def lie_closure(gens, tol=1e-9):
    basis = []
    def add(m):
        v = m.flatten()
        for b in basis: v = v - (b.conj() @ v) * b
        nv = np.linalg.norm(v)
        if nv > tol: basis.append(v / nv); return True
        return False
    for g in gens: add(g)
    changed = True
    while changed:
        changed = False
        cur = [b.reshape(16, 16) for b in basis]
        for x in cur:
            for y in cur:
                if add(x @ y - y @ x): changed = True
    return len(basis)
proj = [PL @ t @ PL for t in T]
print("A7c  ||P_L T_k P_L|| :", [round(float(np.linalg.norm(p)), 6) for p in proj], "; dim of Lie algebra generated by projected generators:", lie_closure(proj))
A7c = lie_closure(proj) == 1
print("     dim of Lie algebra generated by the full T_k (for reference):", lie_closure(T))
# taste commutant
M = np.vstack([np.kron(g, np.eye(16)) - np.kron(np.eye(16), g.T) for g in G])
u, s, vh = np.linalg.svd(M); null = vh[np.sum(s > 1e-8):].conj().T
tastes = [null[:, i].reshape(16, 16) for i in range(null.shape[1])]
ok_comm = all(np.linalg.norm(t @ G5 - G5 @ t) < 1e-8 for t in tastes)
ok_tr = all(abs(np.trace(PL @ t) - np.trace(PR @ t)) < 1e-8 for t in tastes)
A7d = (len(tastes) == 16 and ok_comm and ok_tr)
print("A7d  taste commutant dim", len(tastes), "; commutes with gamma_5:", ok_comm, "; tr on L == tr on R:", ok_tr, "->", A7d)
print("\nSUMMARY A7a", A7a, "A7b", A7b, "A7c", A7c, "A7d", A7d, "->", "ALL PASS" if all([A7a, A7b, A7c, A7d]) else "SOME FAIL")
