"""Round-8 (A34 REVIEW4, C116-C144) corrected late sections 12-14, written once and used for both the local draft and the doc."""
S12_HEAD = "12. Late result: patterned calm backgrounds (A38; checked by me and by one hostile review round)"
S12_LEAD = ("The one background of this kind does not give clean light. Its ripples feel a third of a turn on each square face, never a half (exact), "
            "so with hops between nearest neighbours only they cannot form light-like cones. With richer, finely tuned rules a partly light-like point "
            "appears without the half turn (checked), but heavy ripples sit beside it, and this background is not the calmest state of these rules, which "
            "puts it under section 13's third way out (exact).")
S12_LIST = """- **The question.** Could an empty background whose spots point different ways on different sub-grids (a pattern held in the state, nothing painted on the law) give ripples the twist light-like motion needs?
- **Only one such background exists (exact).** If the pattern repeats every 2×2×2 block of spots and must look the same after any turn of the grid, apart from a shift, the 8 spots of each small cube must point to the cube's 8 corners. My check confirmed every turn maps it onto a shifted copy of itself.
- **One simple rule keeps it calm (exact; my check).** Among rules built from pairs of neighbours, exactly one keeps it unchanging: an equal mix of the ordinary neighbour coupling and the coupling along the link's own direction, with either overall sign. Every other mix of these pair terms, including the handed one, disturbs it (exact). Calm here means unchanging, not lowest in energy (see below).
- **A third of a turn, never a half (exact; my check).** Ripples circling any square face pick up a twist of a third of a turn, with the sign alternating from face to face, under every rule that treats every spot and turn alike, whatever its reach, as long as ripples hop between nearest neighbours at all. My check found exactly this on every face for several rules. The half turn is what light-like cones need when ripples hop only between nearest neighbours; ripples that hop farther are not bound by it (next points). The open route of section 10 cannot even be set up on this background: no half-turn of the grid holds one of its spots fixed, so the sub-grid labels it relies on do not arise.
- **What its ripples do (checked).** With the simple rule, the ripples that cost nothing are the waves whose wave patterns lie on certain lines, lined up with the cube's long diagonals. Ripples near them move at a fixed speed across those lines but not along them, so these are not light-like cones.
- **A partly light-like point, with tuning (checked).** With richer three-spot rules and carefully chosen strengths, some ripples leave a zero-cost point at the same speed in every direction, without the half turn: they travel mainly by longer hops, and the nearest-neighbour hop that carries the third of a turn is tiny there (0.028, against a speed of 1.94). Heavy, slow ripples sit at the same spot and energy beside them, and half of the light-like ripples have negative energy (next point). No sign pattern is painted on, but the background, the extra kinds of rule terms and finely set numbers are all put in by hand.
- **Calm, but not the calmest state (exact; fourth review's check).** Under its calm pair rule, of either sign, this background is not the rule's lowest-energy state: its ripples come in pairs of equal and opposite energy, so some cost less than nothing (on a 4×4×4 grid, 27 of 64 single-ripple states lie below it). The same is true at the partly light-like point, and wherever ripples leave a zero-cost point at a steady speed: such motion always brings energies below the background (A39's positivity lemma). So everything this background offers light falls under section 13's third way out: records cannot track energy, and the background sits among zero-cost pairs of ripples that a small change of the rule could create (argued).
- **Records.** Under the simple rule, records holding the background's own local direction keep it calm and every other content disturbs it (checked). With richer rules, records holding the opposite direction can keep it calm too (checked; clusters of records untested). A single record fixes which of the 8 layouts is in place relative to anything else placed on the grid, which is expected for a pattern held in the state.
- **What stays open.** Backgrounds whose spots share their possibilities instead of each pointing one way (decision 23; section 13 applies to them), patterns with a larger repeat or that respect only some turns (not searched), how this background would sit with the field's 1-of-8 jobs (decision 13), groups of ripples rather than single ones, and how fragile this background is (section 13).
- **Decisions for you (A38).** May the rule carry three-spot or farther-reaching terms (decision 22)? Do finely set strengths count as "no pattern painted on"? May records hold only the background's own direction? Is a 1-of-8 background in which all places are alike acceptable next to the field's 1-of-8 jobs (decision 13)? And is an empty background that is not the calmest state acceptable (section 13)?
"""
S13_HEAD = "13. Late result: can quiet empty space carry light? (A39; checked by me and by one hostile review round)"
S13_LEAD = ("Not as its gentlest ripple, if records can sense every part of the rule's energy and the ripples' zero cost comes from a local change of empty space: "
            "then quiet empty space is automatically the rule's calmest state, and its gentlest ripples spread no faster than ripples in a magnet whose spins "
            "all point one way, so anything light-like would sit above slower ripples (exact, under these conditions).")
S13_LIST = """- **The tension, made exact.** Suppose three things hold: whatever triggers records can sense every part of the rule's energy; empty space is exactly quiet; and the zero cost comes from a local change of empty space that costs nothing when made everywhere in step (as turning a whole magnet costs nothing). Then empty space must be the rule's calmest state, every local piece of the rule must already be at its lowest there, and the gentlest ripple's energy grows no faster than the square of its wavenumber: slow and heavy-like, not light (exact; derived in the lane). The proof limits only the gentlest ripple: a faster ripple above it is not ruled out, but would come with that slower one. Empty space whose zero cost does not come from such a local change, as in ice-like states, is not covered. Every known example of exactly quiet, gapless empty space is slow, including ice-like states at their one exactly quiet point, but the conditions of the general published results were not checked (a comparison recalled from memory, not adopted).
- **Three ways out found, each with a price** (besides the uncovered kind of empty space above).
    - **Light invisible to records.** Records form only on matter, and light is noticed only when matter absorbs it (in real physics, photons are detected this way; a comparison). The price: places that never record; two kinds of places, which with neighbour-pair rules must be written into the rule itself (richer rules are untested); no matter may ever appear out of matter-empty space, not even briefly or from light (real physics does let matter pairs appear that way; a comparison); and matter over its quiet empty background can be heavy but not massless with a filled sea.
    - **Slow, energy-selective recording.** Records form only when energy is actually delivered, slowly, as real detectors do (a comparison). Empty space is then almost, not exactly, quiet, and it must be the calmest state, so this cannot be combined with the third way out. The price: a small memory at every spot, which the axioms do not supply (a memory made of matter is not ruled out, section 7).
    - **Empty space not the calmest state.** It is possible. A39's example paints a sign pattern on the rule; A38's background (section 12) is a second example, using a pattern held in the state, extra rule terms and fine tuning instead. Either way, energies can drop below empty space's, so records cannot track energy (exact). It is probably fragile (argued): it sits among zero-cost pairs of ripples, one with positive and one with negative energy, which any sideways nudge can create (A39's 12-spot toy: 139 states within 0.05 of its energy, against none once a field makes it the calmest state). The toy's survival figures are weaker evidence. Under a slow sideways nudge it survived 99% of the time at the weaker strength and 72% at the stronger, against 100% for the calmest-state version, but that field also opens a gap. Made the calmest state with no gap, the same toy kept 99% and 4%, though its loss went into one zero-cost ripple rather than into pairs (fourth review's check).
- **What does not help.**
    - Light built from pairs of slow ripples, over a calmest-state empty space that keeps the number of flips fixed, is still slow at the bottom (exact for pairs, argued for bigger groups, checked on a 64×64 grid). A light-like branch could only sit above that slow bottom.
    - "Records form only next to records" moves the problem to matter's edges. The light-carrying emptiness tried, a magnet whose neighbouring spins point opposite ways, is not exactly quiet next to a record: in my check its smallest edge value is about 0.006 (A39's ring gives 0.01), shrinking but not vanishing as the record's pull is made stronger, while the aligned emptiness gives zero. Exact quietness there could happen at most at special pull strengths (argued); whether a record's surroundings can be made exactly quiet while light passes farther out is open.
- **A further decision for you.** Which way out, if any? (Light invisible to records ties to decisions 21 and 24; slow energy-selective recording ties to decision 9, memory; empty space that is not the calmest state ties to decisions 17 and 24 and covers A38's background. The shared-possibility background of decision 23, with the plain rule, falls under this result too: if records can sense its energy, it cannot be exactly quiet.)
"""
S14_HEAD = "14. Late result: one pattern of kinds of places for everything? (A40; checked by me and by one hostile review round)"
S14_LEAD = ("Possibly, but not shown: the same 8-way pattern gravity already needs can sort places into kinds that light, gravity and records-bearing matter "
            "could share, with no contradiction found so far. It needs matter to share places with part of gravity, so it is not a clean three-way split, and "
            "three load-bearing pieces are open: how charged matter hops through light's links, whether light settles into the needed state on this grid, and "
            "matter's empty space (argued overall; the pieces are exact or checked as marked).")
S14_LIST = """- **No new pattern (exact).** Any sorting of places into kinds that turns along with gravity's 2×2×2 job pattern must follow that same pattern. So it is the same 1-of-8 choice, not an extra one.
- **Gravity's content sits on only half the places (exact).** One way of writing gravity's rule keeps all of its content on two of the four kinds of place, if the rule may use small groups of places, not just pairs (decision 22).
- **A clean split fails (exact, within 270 arrangements tried).** No arrangement that keeps every kind on its own places lets charged matter feel gravity's slowing of time through rule terms that stay within one place and its six neighbours.
- **The candidate arrangement ("S1").**
    - **Corner places:** matter, together with gravity's stretch parts and its time-slowing. Records lock only matter's share of each such place, and only possibilities with a definite charge; otherwise light's bookkeeping (Gauss's law) breaks at that place (exact; fourth review).
    - **Edge places:** light, as links between the corners.
    - **Face places:** gravity's shear parts.
    - **Cube-centre places:** no job (one place in eight).
- **The twist from light: promising, not shown (symmetry facts exact; the rest open).** Matter hopping from corner to corner passes through light's links. A half-turn twist in light's links around every square needs only one uniform sign in light's rule, not a pattern, and that twisted pattern of links looks the same after every turn of the grid, up to a relabelling that changes nothing physical (exact; my check on all 192 squares for all 24 turns, and the review confirmed that one uniform sign on light's square term respects every turn). But a charged hop through a link respects the turns only if matter at each corner has internal parts that turn with the grid: matter with a single internal state cannot hop through light's links at all (exact; fourth review's check). So this matter is not the simple one-part kind for which light's twist gives exactly light-like motion, and what its ripples do has not been worked out. Matter with internal parts can also get a twist from the rule itself, with no pattern (shown for uncharged matter, with a heavy partner beside the light-like ripples; fourth review's check), so light's twist is one option, not the only one. Whether light really settles into the twisted state on this grid is a comparison with magnet models on a different grid, not shown here.
- **The prices.**
    - Every place holds more than one qubit's worth (argued). Each carries its 8-way job label, as in gravity's own construction; corner and face places also carry gravity's parts, and corners need at least two qubits for charged matter. If every place must have the same room (no place privileged), every place carries all of it.
    - Record's wording would change: a record would lock one possibility of a place's matter share only, not of the whole place. That changes the Record axiom's text and needs your exact wording (as in decision 7); it presupposes the change to more room per place.
    - Matter places are never next-door neighbours, and nothing between them ever records (exact). So records step two places at a time, which departs from your instinct that a record moves at most one grid space per tick (I2) unless that is counted on the coarser grid of matter places. "Records form only next to records" would have to look two places away. And a rule that looks only at next-door neighbours could never let a matter place's odds depend directly on another matter place's record (only indirectly, through how the shared possibilities change), so your Q7 clause "including recorded neighbours" would reach matter only if the rule looks two places away, which changes the nearest-neighbour wording of the rule's axiom.
    - Matter must never appear out of empty space.
    - A simple mass for matter would need yet another, coarser pattern.
    - Light-like matter over empty space that never records has states of negative energy, so its empty space is then not its calmest state: section 13's third way out, now for matter (exact for single particles; A39). A simple mass does not change this. Lifting all of matter's states above zero leaves slower matter states below the light-like point; filling the negative states, as real physics does with its sea, would make empty space record.
    - No region can ever be fully recorded, so your black-hole picture changes: light and gravity run through any cluster of records.
- **Why it matters.** It bundles several of your decisions into one picture: 13 (room per place, now at every place), 17 (matter's twist, possibly from light rather than painted; not yet shown for charged matter), 21 (gravity's places never record, now share by share), 22 (rules on small groups), 24, and A39's "light invisible to records". It also touches 4 (the next-to-records rule), 8 and 27 (how records step), 16, 20, your instincts I2 and I5, Q7's recorded neighbours, and the wording of the Qubit, Record and nearest-neighbour axioms.
"""
S10_OLD = "A late lane (A38, section 12) tested the simplest version, a background whose spots simply point different ways: its ripples feel a third of a turn, never the half turn."
S10_NEW = ("A late lane (A38, section 12) found that this route cannot use a background whose spots each simply point one way: the only such 8-fold background "
           "that respects every turn has no half-turn holding a spot fixed, so the sub-grid labels the route relies on cannot arise (exact; its ripples get a "
           "third of a turn per face instead). The route itself is still untested: it needs a background whose spots share their possibilities, or more room "
           "per place (argued).")
SUM_OLD = ("A late lane (A38) found that the one patterned background whose spots simply point different ways gives ripples a third-turn twist, never the half turn. "
           "Another (A39) found that exactly quiet empty space cannot carry light if records can sense its energy directly and it is the calmest state; light escapes "
           "only by being invisible to records (recorded through matter), by slow energy-selective recording with a memory per spot, or by empty space not being the calmest state.")
SUM_NEW = ("A late lane (A38) found that this route cannot use a background whose spots each simply point one way: the only such background that respects every turn "
           "gives its ripples a third of a turn per face, never the half turn (exact). Its partly light-like point, reached with finely tuned richer rules, has heavy "
           "ripples beside it, and the background is not the calmest state of its rules. Another lane (A39) found that if records can sense every part of the rule's "
           "energy, exactly quiet empty space is automatically the rule's calmest state, and its gentlest ripples are then slow, never light (exact, when the zero cost "
           "comes from a local change of empty space; ice-like empty space is not covered). The ways out found: light invisible to records (recorded only through matter), "
           "slow energy-selective recording with a memory per spot, or empty space that is not the calmest state, which is where A38's point sits. A synthesis lane (A40) "
           "found that the same 8-way pattern gravity needs could sort places into kinds for light, gravity and matter, but only with matter sharing places with part of "
           "gravity, more room at every place, a change to the Record axiom's wording, records stepping two places at a time, and open questions about how charged matter "
           "hops through light's links and about matter's empty space.")
D23_APPEND = " A39: with the plain rule, if records can sense its energy it cannot be exactly quiet; section 13 lists the ways out."
D24_APPEND = " A38: if each spot simply points one way, the only turn-respecting 8-fold pattern has no half-turn holding a spot fixed, so this route needs spots that share their possibilities, or more room per place."
