import pathlib,json,hashlib,datetime
r=pathlib.Path('/private/tmp/review-drain-20260915');c=r/'check8165';inv=json.loads((r/'drain8165-original-inventory.json').read_text());prov=json.loads((r/'drain8165-provenance-checks.json').read_text());gh=json.loads((c/'final-github.json').read_text());assert gh['headRefOid']==inv['head'];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
programs={'block01_geometry_and_rotor_check.py','block02_reflection_and_path_check.py','block03_coarse_current_check.py'}
rows=[]
for x in inv['files']:
 x=dict(x);name=pathlib.Path(x['path']).name
 role='complete-proof' if '/notes/' in x['path'] else 'primary-runner' if name in programs else 'historical-evidence-and-provenance'
 disposition='canonicalize-complete-proof-and-preserve-exact-original' if role=='complete-proof' else 'canonicalize-runner-and-preserve-exact-original' if role=='primary-runner' else 'preserve-exact-original'
 rows.append(dict(**x,role=role,disposition=disposition,canonical_path=None,original_path=x['path'],original_sha256=x['sha256'],recovery=x['recovery_path'],final_path=None,final_sha256=None))
report=dict(schema_version=1,pr=8165,review_kind='original-independent-science-review',reviewer_session='/root/review_8165',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),head=inv['head'],merge_base=inv['merge_base'],current_main_for_review=inv['current_main'],fresh_github_head_verified=gh['headRefOid'],github_state=gh['state'],github_draft=gh['isDraft'],verdict='PASS_WITH_BOUNDED_CLAIMS',landing_ready=False,salvage='All four complete arguments and three primary runners recommended for canonical salvage; source packaging and evidence remain pending.',formal_retained_grade=False,audit_verdict=None,broad_negative_certificate=False,material_math_findings=[],
claims_and_boundaries=[
'Ground magnetic event theorem: supplied full compact rotor H on even spatial tori L>=4, fixed positive g<=1 and fixed observation spacing T. Positive simple ground lies in neutral Gauss/zero-electric-flux sector. Trial energy, site/time conditional-square reflection positivity, chessboard disjoint-cell placement, N/4 disjoint-face packing and M/2 sampled-time duplication yield exponent 1/8. Mixed orientations pay ceil(k/3).',
'Whole-interval magnetic theorem: action-or-Brownian-escape bound from any starting configuration. Actual constrained kernel is symmetric pointwise nonnegative, not assumed positive semidefinite. Hilbert-Schmidt/even trace powers yield exponent 1/4. Magnetic cover clusters use witness multiplicity two, orientation loss three and degree eight.',
'Path limit theorem: reversible forward/backward cancellation yields 3 g^4 a^4 h^2 for scalar functions and 12 g^4 h^2 for circle chords. Countable-link compactness gives subsequential continuous paths. Bounded finite-range compact bridge specification passes by continuity; correct open-threshold Portmanteau argument transfers excursions. No uniqueness, limiting SDE drift or free-box identification.',
'Coarse-current theorem: N/4 distinct disseminated link Brownian coordinates yield temporal oscillation bound. Fixed temporal gauge and fixed positive time block define an exact compact cochain. Principal branch on positive orientations and antisymmetric extension give J=-dm, dJ=0. Fourfold face incidence and six orientations yield 1/24 exponent; degree fourteen gives 196 p_J criterion. Finite integer currents decompose into cycles. No microscopic T->0 limit, exhaustive harmonic sectors, physical electric reconstruction, photon or native Hamiltonian selection.'
],required_author_fix_scope=[
'Preserve all four complete proof bodies and their hypotheses, constants, sector, boundary/support and limit-order explanations. Use descriptive canonical note names and actual markdown dependency links. Four notes are natural; a coherent canonical owner with fully preserved supporting proofs is also acceptable.',
'Keep three primary runners and exact fixtures/tolerances. Original timeout is 120 seconds each. Add actual source-note/formula pins, literal inputs and honest counted assertion TOTAL/N5 output before any new canonical capture. Do not relabel historical raw JSON as canonical cache or fabricate historical check totals.',
'Preserve all 88 exact original paths/modes/blob identities, including 20 Python files, failed Fourier attempt, diagnostic, prior sources, eleven mutation sources/errors and control/review/history documents. Historical packet metadata must remain provenance, never current audit authority.',
'Actual dependencies: note02 uses note01 model/energy/reflection; note03 uses note01 model and note02 excursions; note04 uses note01 reflection/model, note02 excursions and note03 limit. PR8164 is contextual only; no implicit parent theorem or status import.',
'Keep the source N1 limitation explicit. Current schema cannot receive negative packet PASS with fewer than five real qualifying routes. Positive supplied-model theorems and explicit finite counterexamples remain mathematically valid; do not invent failed routes or interpret the packet limitation as a scientific disproof. Canonical negative certificate remains deferred unless honestly completed.',
'Finalize actual source/input discovery and resource bounds before new captures, then obtain this original reviewer session final affected-source confirmation. Root owns combined validation, current-main preservation, landing and closure.'
],history_to_preserve=[
'Fourier cutoffs 32/48 failed unchanged 1e-10 refinement at g=.08 by about 7.56e-8; 48/64 refinement passes same criterion. Diagnostic has cutoffs through96 and independent FD meshes. These are numerical convergence checks, not tail enclosures.',
'Timeout metadata additions are preserved; block03 BEFORE_TIMEOUT source also predates the independent incidence/orientation witness-loss assertion, not merely metadata.',
'Eleven mutations match exact reviewed parent source substitutions and source/output hashes. Reflected face fault raises KeyError, shared-boundary fault fails symmetry before eigenvalues, cochain sign fault fails integrality before dJ. Preserve actual detection scopes.',
'Reviewer control attempt1 underflowed q at g=.004 in machine floating point and incorrectly yielded zero; its source/output remain preserved. Final independent control evaluates exponentials with mpmath and recovers positive 196p_J=.020019856321474305.'
],read_scope=dict(complete='Four proof notes, three complete final programs, all historical source diffs, mutation transformation program and all eleven exact mutant reconstructions/errors, focused verifier, all twenty packet markdown files and manifest/operational state.',numeric_outputs='Final outputs parsed and source-bound hashes checked; quantitative diagnostics, scopes and failure traces inspected. Not every repetitive geometry leaf manually read.',authority='Frozen current-main review-loop identical to installed entry point; mandatory axiom memo, registry procedure/data and all three primitive sources read. Current no-go discipline, proof-search and review setup/unit/operations/salvage/fixes/compatibility/combined/landing/receipt references inspected. No audit status is relied on for the supplied model.',external='Biskup Theorem5.8 statement and proof pages44-46 read; shared boundary blocks, even periods and dimensionwise proof checked. Trutnau symmetric decomposition/time reversal attribution checked; packet also derives needed finite smooth case directly.'),
primary_programs=prov['primary'],actual_local_imports=[],actual_runtime_inputs='No repository mathematical input files or local helper imports. Programs use defined fixtures plus numpy/scipy/mpmath, standard library and own __file__ SHA. Mutation harness reads three local programs and writes scratch mutants; focused verifier reads packet and invokes compilation/git. Neither is primary scientific evidence.',
resource_assessment=dict(primary_timeout_sec=120,primary_execution_this_review=False,actual_sizes=['Geometry L=4,6,8 and maximum Fourier129 by129 eigensystem; sparse FD1536 with expm_multiply.', 'Binary strip4096 states with sparse 12-flip adjacency (~49152 entries), eigsh k=1; dense reduced16 and reflection128 matrices; interacting rotor97.', 'Five integer fields on four-dimensional L4 torus:256 vertices,1024 links,1536 faces,1024 three-cells; dictionary arithmetic;80-digit constants.'],estimate='All are small bounded CPU/memory jobs by representation; no dense4096 eigensystem. A 512 MiB process cap is a reasonable proposed starting budget including Python/scipy overhead, not measured peak RSS. Preserve 120-second metadata, capture serially, record measured resources if executed.',observed_historical_seconds=[x['elapsed_seconds'] for x in prov['primary']]),
proof_obligation_verdict='CLOSED at each declared supplied-model theorem boundary; physical photon/source-response and native-selection target remain OPEN. No target-equivalent premise is used to prove a claimed closed theorem.',no_go_discipline=dict(status='FAIL_FOR_FORMAL_NEGATIVE_PACKET; no mathematical rejection',N1='Actual source does not supply five qualifying refuted routes; no packet PASS.',N2='One supplied model condition; mathematical reflection dependency; downstream future obligations not counted as independent walls.',N3='Compact Haar, full thermal trace then ground limit, even tori, fixed g/T, principal branch and temporal gauge all explicit.',N4='Biskup supports chessboard only; Trutnau supports reversible identity only; PR8164 is context.',N5='Finite circle/rotor, geometry and cochain checks only; infinite volume/continuous path proofs analytic. Canonical five-line execution output absent.',N6='Partial event/path/current closures explicit; no new primitive requirement.',N7='Source-response/current smooth-field weighting may close later; no obstruction claimed against that mechanism.',N8='PR8164 comparisons are scope context; free-box and periodic subsequence states not equated.'),
independent_math=dict(manual=['Conditional-square proof: boundary link paths are fixed by site reflection; no plaquette meets both open halves. Brownian reference and potential factor by half. Time reflection analog fixes endpoint configurations.', 'Chessboard proof works on these half-algebras; link sign flips and time reversal commute by coordinate, arbitrary even rectangular counts follow dimensionwise Cauchy-Schwarz. Sampled face/time repetitions paid explicitly; no independence assertion.', 'Schur row bounds follow dropping nonnegative potentials and retaining disjoint Brownian coordinates. Ground limit carries exp(W E0). Whole-interval K need not be PSD; even-power trace inequality is valid.', 'Martingale fourth moment coefficient: Ito yields3b²h² per martingale; the halves and |x-y|⁴ bound retain coefficient3; cos/sin combine to12. Specification normalized denominator lower bound is exp(-2 n(S)(b-a)/g²).', 'Witness losses: magnetic6 choices with2 face-incidence and3 orientations; coarse6 choices with4 face-incidence and6 orientations. Connected-set tree walk length2s-2 yields degree² criterion.', 'Binary plaquette two-state H has offdiag -4g² and potential contrast2/g²: normalized bad-state probability is4g^8+O(g^16).'],executed=json.loads((c/'independent_controls.json').read_text()),control_scope='Small independent numerical/finite controls only; no original primary, mutation harness, full pipeline, worker or audit run.'),
current_main_loss_check=dict(base=inv['current_main'],original_path_overlap=[],scope='All original files are additions in one previously absent packet tree; no current-main paths replaced. Final canonical source delta requires fresh coordinator preservation/interaction check.'),original_dispositions=rows,original_inventory=inv['files'],provenance_checks=prov,
external_source_checks=[dict(url='https://arxiv.org/pdf/math-ph/0610025',scope='Theorem5.8, proof and shared-boundary setup pages44-46; rectangular extension by the displayed independent-coordinate argument.'),dict(url='https://bibos.math.uni-bielefeld.de/preprints/07-06-262.pdf',scope='Symmetric decomposition and stationary time reversal attribution; direct smooth finite-dimensional derivation is in proof note.')],bound_artifacts={str(p.relative_to(r)):sha(p) for p in [r/'drain8165-fetch.json',r/'drain8165-original-inventory.json',r/'drain8165-original-delta.patch',r/'drain8165-provenance-checks.json',c/'independent_controls.py',c/'independent_controls.json',c/'independent_controls_attempt1.py',c/'independent_controls_attempt1.json',c/'final-github.json']})
(r/'drain8165-original-review.json').write_text(json.dumps(report,indent=2)+'\n')
(r/'drain8165-original-review.md').write_text('''# PR8165 original independent scientific review

Frozen head `c228dbcfc0a6b71639316915f460c32dbf479723`; actual merge base `e0ef7cf4633034a8c1e6d57f5812cc4275bf1349`; current-main context `16574d8f023c06a3ef86fe6d8993a257e0936c81`.

**Scientific disposition: PASS WITH BOUNDED CLAIMS for canonical salvage. Not landing-ready; no audit or formal negative-packet PASS.**

All four complete arguments are worth preserving: sampled magnetic events; whole-interval excursions with indefinite-kernel even-power control; reversible tightness and local compact bridge limits; temporal oscillations and conserved fixed-scale coarse currents. No material mathematical defect found. The supplied Hamiltonian and even-torus/fixed-coupling/fixed-time scope remain explicit. No photon, native-model selection, unique vacuum, microscopic-current refinement or complete harmonic-sector conclusion follows.

The central external chessboard premise was inspected directly in Biskup Theorem 5.8 and its proof. The conditional-square construction supplies the needed link/path reflection algebras, including shared boundaries; dimensionwise proof permits the even rectangular periods. Actual duplicate faces/endpoints and disjoint-edge packing are accounted for. Independent controls reproduce the trial constant, magnetic cover bound and coarse-current bound, plus exact one-four-cube conservation and the indefinite two-state kernel. Initial reviewer floating-point underflow is preserved and corrected with high-precision exponentials.

All 88 original path/mode/blob identities are preserved; the original manifest's 87 non-manifest hashes verify. Three active runners and all historical sources/mutations were read through exact differences; three final output source hashes and all eleven fault transformations verify. No primary rerun occurred. Runners declare120 seconds and have small sparse/dense representations; original timings are not measured memory evidence.

Canonicalization must retain full proofs, three actual runners, real dependencies and complete recovery history. Add source-bound inputs and truthful counted/N5 captures. The source explicitly lacks five refuted routes; current N1 schema forbids negative-packet PASS. Do not invent routes or treat that procedural limitation as disproof of positive supplied-model mathematics. Preserve author state only as historical provenance, never authority.

The JSON companion records the complete dispositions, proof boundaries, inputs, resource assessment, independent controls, failures and hashes. PR remains OPEN/non-draft at unchanged frozen head on final read. Root owns final source fixes, same-session affected confirmation, current-main loss check, combined gate and landing/closure.
''')
print('Report written',len(rows),'dispositions',sha(r/'drain8165-original-review.json'))
