#!/usr/bin/env python3
"""Bind the complete comparison packet while authenticating immutable PRE bytes."""
from pathlib import Path
import datetime,hashlib,json
HERE=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
pre_sha='92f534204e822fbbc38f4cfbd8a5f6d1d33f09b727d7bead68fd22dfb4734faa'
assert sha(HERE/'PRE_SEAL.json')==pre_sha
pre=json.loads((HERE/'PRE_SEAL.json').read_text())
for row in pre['files']:
 p=HERE/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes'],row['path']
bind=json.loads((HERE/'COMPARISON_SOURCE_BINDINGS.json').read_text())
for row in bind['sources']:
 p=HERE/row['snapshot_path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes'],row['snapshot_path']
 # If the original campaign is present, authenticate it without using any
 # absolute private path. Relocated archives use the snapshot's exact hash.
 live=HERE.parent.parent/row['campaign_relative_path']
 if live.exists():assert sha(live)==row['sha256'],str(live)
receipt=json.loads((HERE/'COMPARISON_EXECUTION_RECEIPT.json').read_text())
for row in receipt['executions']:
 assert sha(HERE/row['script_relative_path'])==row['script_sha256']
 assert sha(HERE/row['stdout_path'])==row['stdout_sha256']
 assert sha(HERE/row['stderr_path'])==row['stderr_sha256']
 assert row['exit_code']==row['expected_exit_code']
result=json.loads((HERE/'COMPARISON_RESULTS.json').read_text())
assert result['summary']['scientific_discrepancies']==[]
files=[]
for p in sorted(HERE.rglob('*')):
 if p.is_file() and p.name!='FINAL_SEAL.json':
  assert '__pycache__' not in p.parts,'Unexpected generated bytecode'
  files.append({'path':p.relative_to(HERE).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)})
seal={'stage':'Final source comparison after independent PRE','sealed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'standing':'Conditional scientific comparison only; no audit or landing verdict','PRE_seal_sha256':pre_sha,'PRE_bound_files_authenticated_unchanged':len(pre['files']),'author_seal_sha256':bind['author_seal_sha256'],'comparison_source_bindings_sha256':sha(HERE/'COMPARISON_SOURCE_BINDINGS.json'),'comparison_note_sha256':sha(HERE/'COMPARISON.md'),'comparison_receipt_sha256':sha(HERE/'COMPARISON_EXECUTION_RECEIPT.json'),'scope_supported':['Complete supplied physical 16-state three-leaf star with exact normalized spin shifts, original compensation and unchanged actual formation instruments','Common explicit preparation, initial microscopic energy, all nine actual marked means and full variances, complete initial gain/loss derivative','Exact finite-time number-sector energy relation for this preparation; original author fixed-lambda eigenvector proof checked','Fixed-positive-time microscopic energy scaling; independent PRE Duhamel proof supplies separately attributed uniformity in lambda in [0,1]','Necessary supply inequality only with explicit nonnegative environment, total-energy conservation, finite moments and reproduction of microscopic system energy; bounded-interaction allowance only under its stated decomposition'],'claims_excluded':['General-graph or cube coefficient, repeated births, graph-size or infinite-volume uniformity','Arbitrary initial-state finite-time energy relation, an exact H_lambda eigenstate at lambda>0, or transfer of microscopic moments from trace-distance convergence alone','Autonomous reservoir realization, heat identification, native physical law or lambda selection, empirical prediction, universal reservoir no-go','Uniform asymptotics for varying positive K/delta/kappa or observation times growing with S','Audit verdict, retained status, landing approval or publication change'],'scientific_discrepancies':[],'failures':{'author_historical_reported_failures':2,'complete_preserved_author_failure_reproduced':True,'preserved_failure_exit_code':1,'failure_reason':'Structural equality on an unsimplified exact-zero coefficient; one-line simplify correction, no changed scientific coefficient or tolerance','first_historical_failure_snapshot_recovered':False,'unresolved_execution_failures':[]},'portability':'Scientific snapshots are mapped by exact hashes and relative aliases. Comparisons and runtime copies do not require an absolute private path. Historical immutable records retain original text.','files':files}
(HERE/'FINAL_SEAL.json').write_text(json.dumps(seal,indent=2)+'\n')
# Direct post-write authentication includes every bound artifact.
sealed=json.loads((HERE/'FINAL_SEAL.json').read_text())
for row in sealed['files']:
 p=HERE/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes'],row['path']
print(json.dumps({'FINAL_SEAL_sha256':sha(HERE/'FINAL_SEAL.json'),'COMPARISON_sha256':sha(HERE/'COMPARISON.md'),'bound_files':len(files),'PRE_files_unchanged':len(pre['files']),'comparison_sources':len(bind['sources']),'exact_checks':result['summary']['exact_checks'],'scientific_discrepancies':[]},indent=2))
