#!/usr/bin/env python3
"""Probe: WITNESS_ORBIT_MULTIPLICITY_CYCLE980_BOUNDED_THEOREM_NOTE_2026-08-11.

Independent reconstruction at the SEMANTIC level (machinery disjoint from the
primary's integer matrices and the checker's (permutation, sign) descriptors):

  * gate meanings written from the note's text as maps on 7-bit states
    (wire 0 = centre, wires 1..6 = +x,-x,+y,-y,+z,-z);
  * each word is reduced to its centre-output Boolean function (a 128-entry
    truth table); witnesses are functions that depend on a neighbour bit;
  * the proper cubic group is GENERATED by closure from two quarter turns
    acting on the six direction vectors, and acts on truth tables by
    permuting input bits; orbits and stabilizers are of FUNCTIONS;
  * J is read off the dependence support of each function.

Checked literally (every falsifier bullet of the note): witness set = the 21
stated descriptors; closure; disjoint coverage; |orbit| x |stabilizer| = 24;
orbit sizes 6/12/3 with stabilizers 4/2/8; J = 1/2/0 constant per orbit and
distinct; the eight-row gate-menu table 0,0,1,2,1,2,3,3.

Beyond the note's family (numbers only, outside its claims): the full
48-element cubic group; all 155^2 two-gate words; the same one-gate family on
the d-dimensional star for d = 2, 4, 5.

Prints SUMMARY: lines; HIT: only when a falsifier of the note fires.
"""
import itertools
import math
import sys
import time
from collections import Counter

import numpy as np

HITS = []


def hit(msg):
    HITS.append(msg)
    print("HIT: " + msg)


def summary(msg):
    print("SUMMARY: " + msg)


def directions(d):
    out = []
    for a in range(d):
        for sg in (1, -1):
            v = [0] * d
            v[a] = sg
            out.append(tuple(v))
    return out


def gen_group(d, improper=False):
    """Closure of quarter turns in the coordinate planes (a, a+1) (and the
    inversion if improper) acting on the 2d signed unit vectors; returned as
    permutations of wire labels 1..2d (centre 0 fixed)."""
    D = directions(d)
    idx = {v: t + 1 for t, v in enumerate(D)}

    def quarter(a):
        def f(v):
            w = list(v)
            w[a], w[a + 1] = -v[a + 1], v[a]
            return tuple(w)
        return f
    gens = [quarter(a) for a in range(d - 1)]
    if improper:
        gens.append(lambda v: tuple(-x for x in v))
    gperms = []
    for f in gens:
        gperms.append(tuple([0] + [idx[f(v)] for v in D]))
    ident = tuple(range(2 * d + 1))
    seen = {ident}
    frontier = [ident]
    while frontier:
        nxt = []
        for p in frontier:
            for g in gperms:
                q = tuple(g[p[w]] for w in range(2 * d + 1))
                if q not in seen:
                    seen.add(q)
                    nxt.append(q)
        frontier = nxt
    return sorted(seen), D


def perm_matrix_det(p, D, d):
    # the linear map sending D[t] to D[p[t+1]-1]; columns = images of +e_a
    M = np.zeros((d, d), dtype=int)
    for a in range(d):
        img = D[p[2 * a + 1] - 1]      # +e_a is D[2a]
        M[:, a] = img
    return int(round(np.linalg.det(M)))


def family(d, kinds):
    """The declared quotient: I; X(t); CNOT(c,t) ordered distinct; TOF({a,b},t)
    unordered distinct controls, distinct from t.  Wires 0..2d."""
    W = 2 * d + 1
    words = [("I",)]
    if "X" in kinds:
        words += [("X", t) for t in range(W)]
    if "CNOT" in kinds:
        words += [("CNOT", c, t) for c in range(W) for t in range(W) if c != t]
    if "TOF" in kinds:
        words += [("TOF", a, b, t) for t in range(W) for a, b in itertools.combinations(range(W), 2)
                  if t not in (a, b)]
    return words


def state_map(word, W):
    s = np.arange(1 << W, dtype=np.int64)
    k = word[0]
    if k == "I":
        return s
    if k == "X":
        return s ^ (1 << word[1])
    if k == "CNOT":
        c, t = word[1], word[2]
        return s ^ (((s >> c) & 1) << t)
    a, b, t = word[1], word[2], word[3]
    return s ^ ((((s >> a) & (s >> b)) & 1) << t)


def centre_table(smap):
    return tuple(int(x) for x in (smap & 1))


def depends(tab, W):
    """Neighbour bits the centre output depends on (edge comparisons)."""
    arr = np.array(tab)
    s = np.arange(1 << W)
    return frozenset(w for w in range(1, W) if np.any(arr != arr[s ^ (1 << w)]))


def act_on_table(tab, p, W):
    """(g.f)(s) = f(T_g^{-1} s), T_g moving bit w to bit p[w]."""
    s = np.arange(1 << W)
    pre = np.zeros(1 << W, dtype=np.int64)
    for w in range(W):
        # bit w of T_g^{-1}(s) = bit p[w] of s
        pre |= ((s >> p[w]) & 1) << w
    arr = np.array(tab)
    return tuple(int(x) for x in arr[pre])


def orbits_of(tables, group, W):
    tabset = set(tables)
    closed = True
    remaining = set(tables)
    orbs = []
    stabs = []
    while remaining:
        f = min(remaining)
        imgs = []
        for p in group:
            g = act_on_table(f, p, W)
            imgs.append(g)
            if g not in tabset:
                closed = False
        orb = set(imgs)
        stab = sum(1 for g in imgs if g == f)
        orbs.append(orb)
        stabs.append(stab)
        remaining -= orb
    return orbs, stabs, closed


def J_of(tab, W, D):
    sup = depends(tab, W)
    v = [0] * len(D[0])
    for w in sup:
        v = [a + b for a, b in zip(v, D[w - 1])]
    return sum(x * x for x in v), len(sup)


def run_declared():
    print("=" * 78)
    print("A  declared 155-word family on the radius-one star (d = 3)")
    d = 3
    W = 7
    G, D = gen_group(d)
    dets = Counter(perm_matrix_det(p, D, d) for p in G)
    print(f"  generated proper group: order {len(G)}, determinants {dict(dets)}")
    if len(G) != 24 or set(dets) != {1}:
        raise RuntimeError("group generation error")
    words = family(d, ("X", "CNOT", "TOF"))
    kinds = Counter(w[0] for w in words)
    print(f"  words: {len(words)} = {dict(kinds)}")
    tabs = {}
    wit_words = []
    for w in words:
        t = centre_table(state_map(w, W))
        if depends(t, W):
            wit_words.append(w)
            tabs.setdefault(t, []).append(w)
    print(f"  witness words: {len(wit_words)}; distinct witness functions: {len(tabs)}")
    # stated descriptors: CNOT(d -> C) for the six directions, TOF({a,b} -> C) for the 15 pairs
    stated = set([("CNOT", c, 0) for c in range(1, 7)] +
                 [("TOF", a, b, 0) for a, b in itertools.combinations(range(1, 7), 2)])
    derived = set(wit_words)
    if derived != stated or len(tabs) != 21:
        hit(f"derived witness set differs from the 21 stated descriptors: extra {sorted(derived - stated)[:5]}, "
            f"missing {sorted(stated - derived)[:5]}, functions {len(tabs)}")
    tables = sorted(tabs)
    orbs, stabs, closed = orbits_of(tables, G, W)
    if not closed:
        hit("proper cubic transport is not closed on the derived witness functions")
    cover = Counter(t for o in orbs for t in o)
    if any(v != 1 for v in cover.values()) or set(cover) != set(tables):
        hit("orbits overlap or omit a witness")
    rows = []
    for o, st in zip(orbs, stabs):
        Js = {J_of(t, W, D) for t in o}
        members = sorted(w for t in o for w in tabs[t])
        kind = members[0][0]
        rows.append((kind, len(o), st, Js))
        if len(o) * st != 24:
            hit(f"orbit size {len(o)} x stabilizer {st} != 24")
    for kind, size, st, Js in sorted(rows, key=lambda r: {6: 0, 12: 1, 3: 2}.get(r[1], 9)):
        print(f"  orbit: kind {kind:4s} size {size:2d} stabilizer {st} size*stab {size * st}; (J, arity) values {sorted(Js)}")
    sizes = sorted((r[1], r[2]) for r in rows)
    if sizes != sorted([(6, 4), (12, 2), (3, 8)]):
        hit(f"orbit/stabilizer pairs {sizes} differ from (6,4),(12,2),(3,8)")
    Jvals = [r[3] for r in rows]
    if any(len(j) != 1 for j in Jvals) or len({next(iter(j))[0] for j in Jvals}) != len(Jvals):
        hit(f"J is not constant on an orbit or not separating: {Jvals}")
    Jmap = {r[1]: next(iter(r[3]))[0] for r in rows}
    if Jmap != {6: 1, 12: 2, 3: 0}:
        hit(f"J values by orbit size {Jmap} differ from 6->1, 12->2, 3->0")
    # menu table
    menus = [(), ("X",), ("CNOT",), ("TOF",), ("X", "CNOT"), ("X", "TOF"), ("CNOT", "TOF"), ("X", "CNOT", "TOF")]
    expect = [0, 0, 1, 2, 1, 2, 3, 3]
    got = []
    for m in menus:
        ws = family(d, m)
        ts = sorted({centre_table(state_map(w, W)) for w in ws if depends(centre_table(state_map(w, W)), W)})
        o, _, _ = orbits_of(ts, G, W) if ts else ([], [], True)
        got.append(len(o))
    print("  menu table {I}+: " + ", ".join(f"{'+'.join(m) or '-'}: {g}" for m, g in zip(menus, got)))
    if got != expect:
        hit(f"gate-menu table {got} differs from {expect}")
    return len(words), len(wit_words), sorted(rows, key=lambda r: {6: 0, 12: 1, 3: 2}.get(r[1], 9)), got, G, tabs


def run_Oh(tabs):
    print("=" * 78)
    print("B1  full 48-element cubic group (outside the note's claim)")
    G48, D = gen_group(3, improper=True)
    tables = sorted(tabs)
    orbs, stabs, closed = orbits_of(tables, G48, 7)
    res = sorted(((len(o), s) for o, s in zip(orbs, stabs)), key=lambda x: x[0])
    print(f"  order {len(G48)}; closed {closed}; (orbit size, stabilizer): {res}")
    return len(G48), res


def run_two_gate(G):
    print("=" * 78)
    print("B2  two-gate words over the declared 155-word family (outside the note's cap)")
    W = 7
    words = family(3, ("X", "CNOT", "TOF"))
    maps = [state_map(w, W) for w in words]
    t0 = time.time()
    fun_count = Counter()
    wit_words = 0
    for m1 in maps:
        for m2 in maps:
            comp = m2[m1]
            t = tuple(int(x) for x in (comp & 1))
            fun_count[t] += 1
    wit = {t: c for t, c in fun_count.items() if depends(t, W)}
    wit_words = sum(wit.values())
    orbs, stabs, closed = orbits_of(sorted(wit), G, W)
    size_hist = Counter(len(o) for o in orbs)
    supp_hist = Counter(len(depends(t, W)) for t in wit)
    one_gate = {centre_table(m) for m in maps}
    new_funcs = sum(1 for t in wit if t not in one_gate)
    dt = time.time() - t0
    print(f"  {len(maps) ** 2} two-gate words: witness words {wit_words}; distinct witness functions {len(wit)} "
          f"({new_funcs} not realized by one gate); proper-cubic orbits {len(orbs)} (closed {closed}); "
          f"orbit-size histogram {dict(sorted(size_hist.items()))}; support-size histogram "
          f"{dict(sorted(supp_hist.items()))}; {dt:.1f}s")
    return len(maps) ** 2, wit_words, len(wit), new_funcs, len(orbs), dict(sorted(size_hist.items()))


def run_dims():
    print("=" * 78)
    print("B3  the one-gate family on the d-dimensional radius-one star (outside the note's claim)")
    out = []
    for d in (2, 3, 4, 5):
        W = 2 * d + 1
        G, D = gen_group(d)
        words = family(d, ("X", "CNOT", "TOF"))
        tabs = {}
        for w in words:
            t = centre_table(state_map(w, W))
            if depends(t, W):
                tabs.setdefault(t, []).append(w)
        orbs, stabs, closed = orbits_of(sorted(tabs), G, W)
        res = []
        for o, s in zip(orbs, stabs):
            Js = sorted({J_of(t, W, D)[0] for t in o})
            res.append((len(o), s, Js))
        res.sort(key=lambda r: -r[0])
        exp_order = (2 ** (d - 1)) * math.factorial(d)
        print(f"  d={d}: words {len(words)}, witnesses {len(tabs)} (= 2d + C(2d,2) = {2 * d + math.comb(2 * d, 2)}), "
              f"group order {len(G)} (2^(d-1) d! = {exp_order}), orbits (size, stab, J): {res}, closed {closed}")
        out.append((d, len(words), len(tabs), len(G), res))
    return out


def main():
    t0 = time.time()
    nwords, nwit, rows, menu, G, tabs = run_declared()
    summary(f"A declared family: {nwords} words, {nwit} witness words = 21 stated descriptors, 21 distinct centre "
            f"functions; proper group generated by two quarter turns: order {len(G)}; orbits (kind, size, stabilizer, "
            f"J): " + ", ".join(f"({r[0]}, {r[1]}, {r[2]}, {sorted(j for j, _ in r[3])[0]})" for r in rows)
            + f"; closed, disjoint, size*stab = 24 each; menu table {menu} (note 0,0,1,2,1,2,3,3)")
    n48, r48 = run_Oh(tabs)
    summary(f"B1 full cubic group (order {n48}) on the 21 functions: (orbit size, stabilizer) {r48}")
    n2, w2, f2, new2, o2, h2 = run_two_gate(G)
    summary(f"B2 two-gate words: {n2} words, {w2} witness words, {f2} distinct witness functions ({new2} new vs one "
            f"gate), {o2} proper-cubic orbits, size histogram {h2}")
    dims = run_dims()
    summary("B3 d-dim star one-gate family: " + "; ".join(
        f"d={d}: {nw} words, {nt} witnesses, |G+|={ng}, orbits (size,stab,J) {res}" for d, nw, nt, ng, res in dims))
    print("=" * 78)
    summary(f"hits={len(HITS)}; runtime {time.time() - t0:.0f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
