import pathlib,json,hashlib,subprocess,sys
r=pathlib.Path('/private/tmp/review-drain-20260915');w=r/'review-draft-slot';d=json.loads((r/'drain8025-original-inventory.json').read_text());reuse=json.loads((r/'drain8025-authority-reuse.json').read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
rows=[]
for x in d['original_paths']:
 p=x['path'];assert sha(pathlib.Path(x['recovery_path']))==x['sha256'];role='Historical packet recovery; proof/checker variants read, operational/audit outputs are not authority.'
 if p.startswith('docs/GAUGE'):role='Accepted mathematical content pending packaging and final evidence; sharper canonical bound subsumes the preserved weaker independent proof.'
 elif p in ['docs/audit/scripts/build_citation_graph.py','scripts/audit_packet_script_deps.py']:role='Review exact one-claim helper-map addition as additive union on currentmain, preserve all current entries; never transplant full old file.'
 elif p.startswith('scripts/'):role='Standalone finite diagnostic; mathematical computation sound, missing input/footer/cache scope packaging pending.'
 elif p.startswith('logs/'):role='Historical execution only; preserve and replace live evidence with fresh corrected-source bounded capture.'
 elif p.startswith('docs/audit/data/'):role='Generated topology original preserved for recovery, not imported as authority; regenerate final topology.'
 rows.append({'original_path':p,'original_mode':x['mode'],'original_blob':x['blob'],'original_sha256':x['sha256'],'disposition':role,'recovery':d['head']+':'+p,'extracted_recovery':x['recovery_path'],'final_path':None,'final_sha256':None})
prim='scripts/gauge_wilson_local_observable_finite_region_pw_2026_09_07.py';helper='scripts/gauge_wilson_local_observable_boundary_schmidt_check_2026_09_07.py';note='docs/GAUGE_WILSON_LOCAL_OBSERVABLE_FINITE_REGION_PW_APPROXIMATION_BOUNDED_THEOREM_NOTE_2026-09-07.md'
sys.path[:0]=[str(w/'scripts'),str(w/'docs/audit/scripts')]
import runner_cache as rc,build_citation_graph as graph
api={'type':graph.extract_claim_type_hint((r/'drain8025-originals'/note).read_text()),'runners':[{ 'path':p,'timeout':rc.declared_timeout_for(r/'drain8025-originals'/p),'inputs':rc.declared_input_paths(r/'drain8025-originals'/p)} for p in [prim,helper]],'executed':False};(r/'drain8025-original-api.json').write_text(json.dumps(api,indent=2)+'\n')
findings=[{'id':'F8025-1','finding':'Both runners omit literal proof-identity AUDIT_INPUT_PATHS.','fix':'Bind own note and actual compact-Hamiltonian/cutoff parents, distinguish proofidentity from runtime prose reads; no gap8024 dependency.'},{'id':'F8025-2','finding':'Both default TOTAL lines are noncanonical and note lacks canonicalcache links.','fix':'Preserve29primary/28helper checks including one resource each; canonical TOTAL: PASS=n FAIL=0 and actual cachelinks.'},{'id':'F8025-3','finding':'Live root/primary review chronology and block32 labels are not canonical scientific descriptions.','fix':'Use scientific names and explicit historical recovery; retain all77originals, especially independent weaker proof and corrections.'},{'id':'F8025-4','finding':'N5 lattice_wide PASS resource label and sparse historical N1–N8 need honest application scope.','fix':'Separate finite diagnostics/resource guard from all-orders analytical propagation/Haar/form-domain reasoning; preserve concrete boundary witness without claiming universal no-go or fabricated five-route closure.'}]
proof={'locality':'Strong Dyson and commutator norm inequality apply on separable fullL2 link spaces after onsite conjugation. Actual cited Prop2.1/Lemma2.2/Thm3.1steps1–4 checked. First-face4|X|, successor<=16, n>=distance gives conservative2|X|Theta_d(32vT); no globalvolume norm.','spatial':'Crossing face distance>=r, C<=4N, polynomialN<=3|X|(2r+1)^3. Integrating tail gives C/16 Theta_(r+1)<=N/4 Theta_(r+1); v=0 handled by exactzero tail.','cutoff':'Positive local potential/formenergy plus fullPW cutoff gives g_RQ<=K<=H. Purification inertreference and boundedPVQ extend projected Duhamel to formdomain. Unnormalized-vector expectationdifference<=2||A||delta; normalization adds||A||(1-p), explicitp>0/E<g. No global energy conservation assumption on actual reduced global dynamics.','boundary':'Haar integration of productV gives nine orthonormal right functions; traceUV has9Schmidtcoefficients1/3. DensityI9/9 commutes endpointactions but carries nontrivialfundamentalblock and no constantcomponent. Concrete physical counterexample, not universalnegative certification.','infinite_scope':'Fixed interaction restrictions required for optional norm-Cauchy thermodynamic dynamics. No time-norm-continuity of allboundedonsiteoperators, arbitraryinfinite-statenormality, gap-premise, compiler, diamondbound or physicalselection.'}
refs={}
for n in ['drain8025-metadata-before.json','drain8025-review-fetch.json','drain8025-review-acquire.json','drain8025-original-inventory.json','drain8025-original.patch','drain8025-authority-reuse.json','drain8025-original-api.json','check8025/control.py','check8025/control.json']:
 refs[n]={'path':str(r/n),'sha256':sha(r/n)}
out={'status':'ORIGINAL SCIENCE REVIEW COMPLETE; PACKAGING AND FINAL SOURCE/EVIDENCE CONFIRMATION PENDING','reviewer_session':'/root/review_8012','head':d['head'],'delta_base':d['delta_base'],'declared_base':'codex/volume-uniform-gap-block34-20260907','review_base':'19b73e32772a990f4d9d0792013347943bc80818','original_dispositions':rows,'original_delta':{'paths':77,'history':69,'notes':1,'runners':2,'caches':2,'tool_mappings':2,'generated_topology':1,'deleted':0},'findings':findings,'proof_review':proof,'source_input_context_hashes':reuse['same'],'authority_reuse':reuse,'independent_controls':json.loads((r/'check8025/control.json').read_text()),'external_mathematics':{'url':'https://arxiv.org/pdf/1410.8174v1','pdf_path':str(r/'check8025/nachtergaele-sims.pdf'),'pdf_sha256':sha(r/'check8025/nachtergaele-sims.pdf'),'read_scope':'Prop2.1,Lemma2.2,Thm3.1 proof equations71–73 and domain setup; Thm4.1 fixed-family limit context. Explicit mathematical machinery, no imported numerical velocity.'},'resource_plan':{'primary_or_helper_not_executed':True,'each_final_capture_once_after_cold_and_preflight':True,'timeout_sec':180,'process_tree_rss_mib':180,'expected_counts':{prim:29,helper:28},'cost':'Primary constructs3993finitefaces and radius4BFS; helper uses small9x9SymPy algebra/polynomials. No large-lattice dynamics or oracle reconstruction.'},'current_main_preservation':'Only newnote/tworunners/caches/history plus exactadditive two helper mappings; no stale parent source or old entiretool file transfer. Actual mathematical parents compactHamiltonian+corrected8023cutoff unchanged by verifiedhash. Gap8024 expressly notpremise.','closure':'All unique scientific content can be retained; weaker historical proof is superseded by sharper canonical bound with exact original recovery. No substantive unique deferrednegative theorem identified; final closure awaits actual correctedcandidate.','references':refs,'no_source_edits':True}
p=r/'drain8025-original-review.json';assert not p.exists();p.write_text(json.dumps(out,indent=2)+'\n');print(p,sha(p))
