# POST source and execution evidence

The parent released only `prepared-matter-probe-personal` and, if needed for registers, the exact public PR9131 note and permitted main premises. The frozen author note and seal hashes match the release. All seven author-seal members were read and verified. The root's own source manifest contains private/active checker paths; none was followed. No author Python file was executed or imported.

`freeze_post_sources.py`, run through `run_post_freeze.py`, creates `POST_SOURCE_PINS.json` and immutable-byte copies under `post_sources/`. There are thirteen new input records: eight author files including its seal, the exact main bounded-compensation register parent, the exact public original-readout note, and three procedural references. Four unchanged main scientific copies remain in the sealed PRE. The installed physics-claim-reviewer entry matches its pinned repository source. No model change, delegation, landing review loop, audit or publication action was performed. The author code, result, execution and source metadata are author evidence, not independently reproduced runs.

The source freezer exited zero with empty stderr in 0.17890120903030038 seconds. Its full logs and `POST_FREEZE_EXECUTION.json` preserve command, timing and hashes. The public PR9131 note has SHA256 `99c9f0cdd6f30caa733f75a3c32ffadb3c5264458c0159f1df31130c5b704c6b`; the main bounded target retains `f6cbeb6e0ddaa7d5a7ede3d3f3c2b7f5b22d58adeba8ef84f8aabc10599fb0f9`. Both were read completely. No public-note timing/calibration or independent packet referenced within it was opened separately. Only section C's finite-register construction is needed for this review.

`post_control.py` is newly written after release and uses only the standard library. It reads the declared author result's explicit common-flow/path data as input, then reconstructs the physical root preparation and original primitive moves without importing its builder or my old executable. It checks the common flow, all five loop-flux values, both charged branches and both resolved signs. Twenty initial states, forty old-hop intermediate states and twenty successful outputs satisfy exact integer Gauss. The certificate includes the rejected hop into the birth site. It recomputes the resolved and dephased rational Gram effects and coherent initial factor, and detects missing charge compensation, path deletion and a wrong relative phase. This verifies the actual root preparation rather than assuming it equals my different PRE construction.

The eight named POST checks also compare all ten author timing rows with their reported arithmetic and rounded prose values and bind the author execution hashes. These are arithmetic/source checks only. They do not rerun the Gaussian quadrature, finite timing model, full rotor dynamics, count variance or microscopic process. The author's dephased `1,0` entries are literal analytic annotations; the root's primary coherent effect is genuinely computed. This scope distinction is explicit in `POST.md`.

The own POST control ran at 2026-09-24T21:30:03.565353+00:00, exited zero with empty stderr in 0.05215324996970594 seconds. `POST_CONTROL_EXECUTION.json` records Python 3.13.5/macOS arm64, command and output bindings:

| Artifact | SHA256 |
| --- | --- |
| `post_control.py` | `4302d6bb34fb05ce660ab5325c054426f02807f0a61ec6e28ee6253b89c5f064` |
| `post_control.stdout.txt` | `336f53f38c3f0e722af4aa6b0bef153be4c07510548a892344aa3c2f0d94004d` |
| `POST_CONTROL_RESULTS.json` | `db0339234e5608e7b31575488f5ab765aaa736ea94af6fedf25186640462dc0b` |
| `POST_PATH_CERTIFICATES.json` | `8a512e39fce0e05e7fb70424cc687c8386c449955b9130bd89b031eac0cb1029` |

`verify_post_evidence.py`, run through its separate wrapper, checks all 33 preserved PRE members, all thirteen new input origins, the four reused exact Git science inputs and unchanged current workflow. It verifies both own execution records and full stdout/result equality, then independently parses every serialized field word and charge deviation, checking 20 initial, 40 intermediate and 20 successful final Gauss equalities. Complete serialized coverage is mechanical, not a claim of manual inspection of each repeated word. It does not rerun or import either scientific control.

That verifier exited zero with empty stderr in 0.3697122500743717 seconds. Its result SHA256 is `54233e63ba8ff662a49511d77462df230c650f6ac174b8b2eb9b01ad3c434854`; full logs and `POST_VERIFY_EXECUTION.json` are retained. All root source/code/results, own scientific logs, all twenty compact certificate cases and both complete derivations were inspected. New mathematical obligations were reconstructed analytically: bounded dissipative Duhamel, an alternative first-history count bound, the factorial second moment, repetition coefficient, cap-adjusted register and ordered moment diagonal. These are released-source POST implications, not additions to the blind PRE.

No scientific execution failed during POST, no tolerance was relaxed, and no author result was regenerated. No source repository, editable prompt file or sealed PRE member was edited. The report recommends accurate labeling of the dephasing entries and explicit register second-moment/microscopic-rate qualifications; it applies no audit verdict. All newly delivered files are bound by `POST_SEAL.json`, while the original PRE seal remains unchanged. The final seal verification is a byte/hash preservation check, not scientific validation.
