# Blind reconstruction: read, computation, and failure record

Only the two allowed scientific parent notes were opened. Their complete contents and exact main-revision bytes were checked. Repository AGENTS, the standing planning-branch AGENTS, SCIENCE_WORKFLOW, and the physics-claim-reviewer skill were read as procedural instructions. The inherited model and reasoning effort were retained, and no agent was delegated. No parent runner or other scientific source was opened or executed.

The first batched read returned an outer tool-output truncation. The affected local-compensation parent and workflow were then read completely with bounded outputs. The local-pair parent and reviewer skill were completely visible. The source snapshots preserve their full bytes; the initial truncated display was not treated as complete verification. The instruction pointer was resolved through the existing `origin/ai/execution` Git object without fetching or changing references outside the assigned directory.

The root supplied one narrowly requested parameter-definition clarification, preserved in SUPPLIED_PARAMETERIZATION.md. No root argument, desired filling, control data, or candidate file was disclosed. All formulas and finite controls in this PRE were developed independently from the permitted model definitions.

The analytic alternatives were distinguished explicitly. Full occupancy makes both the actual gated D and all outward F operators zero, so replacing D by an ungated electric sum would answer a different problem. A zero-angle matter vector is not itself a normalizable physical field state; it was realized using finite-support integer Gauss flows and complete cycle-coordinate boxes. The half-filled trial was used as a variational witness, not as a proposed exact minimizing sector. Initial loose local bounds were superseded by an exact exhaustive local certificate; no incompatible result was discarded.

The independently written control was run twice. Attempt 01 succeeded and is preserved in full. Attempt 02 added explicit reconstruction of the three winding cycles and the four-hop cycle-coordinate displacement bound; it also succeeded. All local certificate, Rayleigh and geometric values stayed exactly unchanged. The final physical rows and all 147 local groups and 48 Rayleigh rows were read completely. Both attempts retain their exact source, output, empty stderr and execution receipt. No failed scientific run occurred. No parent or author control was imported or executed.

Final verification will bind the report, code, source pins, full logs and all evidence, then seal the packet read-only. No repository, publication, audit, branch, campaign checkpoint or other packet is changed. The task ends at PRE sealing, before author disclosure.
