# Blind independent PRE: dynamics and energy of the supplied prepared probe

2026-09-24. Conditional mathematics of the supplied compensated model. This is a bounded independent reconstruction, not an audit disposition, a physical preparation protocol, or a claim that the interaction is selected by the native axioms.

The named Root22 preparation and its initial effect are admitted provisional inputs. The new dynamics and output-energy author candidates were not opened. No author builder or runner was imported or executed. All computations below use direct hard-core matter words and integer rotor shifts written in this packet. The complete argument, including the finite-size failures of a tempting simplification, precedes any release of those new candidates.

## 1. Supported result and exact scope

The initial interference effect does not imply that the prepared matter state is stationary or that its cancellation persists. For the actual full pair-form Hamiltonian, this packet gives an exact finite-word criterion for loss of that cancellation, and evaluates it on the admissible cubic tori of sides six and eight. It is strictly positive for both selected resolved signs. Keeping the electric term and the entire original dissipator, the initially small selected rate develops a nonzero leading contribution on times of order \(\tau g^2\).

At fixed graph the supplied preparation has a controlled full rotor energy spread. On both evaluated tori its ordinary variance under \(h=KD+\delta H_4\) is a strictly positive constant times \(\delta^2\), rather than the variance of the old all-A-plus field Hamiltonian. The normalized selected outputs also have controlled ordinary full rotor energy means and variances. Their leading conditional mean change is positive in both examples, but this is not an identified heat or photon-absorption energy.

There remain positive shrinking count windows. The Root22 sufficient choice \(b=o(\tau g^3)\) preserves both small individual count means. A separate comparison of the vacuum/one-particle contrast permits the weaker sufficient condition \(b=o(\tau g^2)\), without preserving the same small background. The critical window \(b=4\tau\eta g^3\) exhibits a computable extra common background. None of these conditions is asserted necessary or optimal.

The analytic formulas are given for any fixed simple cubic torus with even periods at least six. The explicit integer coefficients and strict instability witnesses are checked only for the equal-period tori \(6^3\) and \(8^3\). The table is not promoted to a uniform all-volume formula. Graph, packet, integer strings, \(\tau>0\), and \(\kappa>0\) are fixed before \(g\downarrow0\). All constants may depend on those fixed data. There is no growing-volume estimate, no fixed-duration detector theorem, no resource rate, and no assumption that the supplied preparation is generated by the original births.

## 2. Source identities and provenance

The complete three scientific main sources were read at Git revision

`0e6ad8285096ed668816f18caaa6fbbfbd9c50e8`

in `campaign-working`. Exact Git bytes are copied under `sources/main/`:

| Source | SHA256 |
|---|---|
| `LOCAL_COMPENSATION_COMMON_FIELD_RECORD_LIMIT_BOUNDED_THEOREM_NOTE_2026-09-24.md` | `c63db3296e5705c57693c2deb109e506f336fae4848d3ab0926d13a98929802b` |
| `LOCAL_PAIR_FORM_AND_GENERAL_GRAPH_MAGNETIC_DYNAMICS_BOUNDED_THEOREM_NOTE_2026-09-24.md` | `7c5bc10d0ca1127c2a1ef6f5cf9269caf6e8f023a09a061c2da0d8e033e35a7a` |
| `WEAK_FIELD_WAVE_PACKETS_FROM_MOBILE_RECORD_DYNAMICS_BOUNDED_THEOREM_NOTE_2026-09-24.md` | `651fa7cfd816ca5df8c401959458b7590c2f6ec706af437ef3ce31accb7d3ccf` |

The complete admitted external note is

`prepared-matter-probe-personal/PREPARED_MATTER_INTERFERENCE_PROBE_ROOT.md`,
SHA256 `ab3c1883b032e571efdeb52330d7665c262f70e3f303b3236f32f89accbcd7bf`.

The previously sealed independent count packet is reused only for its fixed-graph global Duhamel comparison and factorial-count argument:

* `unrestricted-record-count-independent/PRE.md`, SHA256 `1fd58a66171c23568841d2527a2091f3992e584cbad970bdb8979a38e4c68e7e`;
* its `PRE_SEAL.json`, SHA256 `b6e0c33fe1286a876f1230759cb62769d57475d76c2ea1a6aae633064e2ba9d0`.

Those old artifacts remain unchanged. Their other provisional research dependencies are not used to establish the present dynamics or energy calculation. The needed Duhamel and count arguments are reproduced below.

`SOURCE_PINS.json` records all 11 exact source copies, origins, byte counts and hashes, including the unchanged applicable AGENTS, SCIENCE_WORKFLOW, reviewer instructions, freshness rule and proof-search governance already read at this revision. The source-pinning run checked the eight Git origins and three expressly authorized external origins. No current campaign checkpoint, new dynamics/output candidate, other active checker packet, or forbidden calibration work was read. Root22's separate controls were described in its note but were not read or run; their numerical observations are not evidence for this PRE.

## 3. Physical state, operators and domains

Store every link from A to B, with \(U_{ab}\) raising \(E_{ab}\) by one. The physical Gauss law is \(\operatorname{div}E=q-1_A\). On \(P\), every A site is occupied; B sites and all charge signs remain part of the matter space. A legal outward hop of charge \(q\) from A to an empty B uses \(U_{ab}^{-q}\); its adjoint refills a vacant A using the actual charge at its occupied B source. It may pull a B record that was already present before the two outward hops. Removing those paths would change \(H_4\).

Write \(F_a\) for the unsigned outward sum. With each unordered overlapping A pair used once,

\[
 S_{ac}=F_cF_aP,\qquad
 H_4=-2\sum_{\{a,c\}:N(a)\cap N(c)\ne\varnothing}S_{ac}^*S_{ac}.
 \tag{1}
\]

Outward operators on distinct A sites commute, including the exclusion case when both attempt the same B destination. Every \(S_{ac}\) is bounded, so \(H_4\) is bounded and self-adjoint at fixed graph. All allowed matter words and intermediate charges in (1) are retained.

For the chosen original resolved mark \(j=(a,b,\sigma)\),

\[
 B_\sigma=Pj_{(a,b,\sigma)}F_aP,\quad M_\sigma=B_\sigma^*B_\sigma,
 \quad \|B_\sigma\|\le5.
 \tag{2}
\]

The full diagonal electric operator on P is

\[
 D(q,E)=\sum_{a\in A,\ b\sim a,\ q_b=0}E_{ab}(E_{ab}-q_a).
 \tag{3}
\]

It is nonnegative on integer fields, self-adjoint on its multiplication domain, and can have unconfined directions in some matter words. The Hamiltonian is \(h=KD+\delta H_4\), self-adjoint on \(D(D)\). Its dissipative extension is the complete original resolved or coherent GKLS instrument, as specified in the parent, with all other marks present. A count of a selected resolved sign below refers to the resolved instrument.

Use the exact Root22 sites, modulo the torus periods:

\[
\begin{split}
a=(0,0,0),\ d=(1,1,0),\ h_0=(2,2,0),\ c=(1,0,0),\ e=(0,1,0),\\
&b=(-1,0,0),\ v_1=(0,-1,0),\ v_2=(0,0,1),\ v_3=(0,0,-1).
\end{split}
\]

The subscript on \(h_0\) distinguishes the site from the Hamiltonian. All A charges are plus except the two minus charges at \(d,h_0\). All \(v_i\) carry plus records. Word \(m_c\) has c occupied plus and e empty; word \(m_e\) has e occupied plus and c empty. All other B sites, including b, are empty. Both words have \(N_0+4\) records.

Let \(E_{\rm com}\) be any fixed integer flow with divergence \(-1\) at d, \(-2\) at \(h_0\), and \(+1\) at each \(v_i\). Its construction along three paths is part of the supplied preparation. Put

\[
 J\phi=\frac{V_{\rm com}}{\sqrt2}
  \left(|m_c\rangle U_{dc}^{-1}-|m_e\rangle U_{de}^{-1}\right)\phi.
 \tag{4}
\]

Each branch separately obeys Gauss, and \(J^*J=I\). The common flow cannot be dropped from the physical state or the electric-domain estimates. Because rotor shifts commute, its scalar angle phase cancels from the magnetic norms and matrix elements used below.

The exact selected output and effect are

\[
 B_\sigma J\phi=\frac{|m_{{\rm out},\sigma}\rangle V_{\rm com}U_{ab}^{\sigma}}
 {\sqrt2}\left(U_{ae}^{-1}U_{dc}^{-1}-U_{ac}^{-1}U_{de}^{-1}\right)\phi,
 \qquad J^*M_\sigma J=1-\Re W_p.
 \tag{5}
\]

The output has a charge \(\sigma\) at a, \(-\sigma\) at b, plus charges at c,e and all \(v_i\), and \(N_0+6\) total records. Equation (5) coherently adds the two allowed destinations before taking a norm; there is no added destination register or branch dephasing.

Take the parent's normalized compact weak-field vacuum and one-particle packets \(\phi_{n,g}\), \(n=0,1\), and set \(\Psi_{n,g}=J\phi_{n,g}\). Write \(\tau=a_{\rm lattice}/c_{\rm light}\), fixed, and

\[
 K=\frac{g^2}{2\tau},\quad \delta=\frac1{4\tau g^2},\quad
 p_{n,g}=\|B_\sigma\Psi_{n,g}\|^2
 =g^2q_n+O(g^4),\quad
 q_0=\frac{v_p}{2}>0,\quad q_1=q_0+|\chi_p|^2.
 \tag{6}
\]

More exactly, the initial excess is \(g^2e^{-g^2v_p/2}|\chi_p|^2\) up to exponentially small cutoff errors. The packet densities are even after rescaling, apart from exponentially small cutoff tails. This remains true for a complex linear combination of one-particle modes: its modulus squared is even. No assertion that the charged state subsequently follows the vacuum field Hamiltonian is made.

## 4. Gauss and harmonic fibers precede a flat-angle limit

The reference field is invariant under both gradient angle translations and the three constant-link angle translations. Equivalently its electric fields have zero divergence and zero winding flux. Let

\[
 \mathcal S=(\operatorname{im}\operatorname{div}^{T}\oplus\mathcal H)^{\perp},
 \quad \mathcal Q=\mathcal S/(2\pi P_{\mathcal S}\mathbb Z^{\mathcal E}),
 \tag{7}
\]

where \(\mathcal H\) is the space of constant coordinate-link fields, converted to the stored A-to-B orientations. The weak-field packet is localized near zero in \(\mathcal Q\), not in the gradient and harmonic directions. Conditional on a transverse coordinate x, those removed directions carry normalized Haar measure on their compact fiber. The fixed charged strings in (4) add phases and correlations; they do not turn the Haar-distributed harmonic angles into zero angles.

This distinction gives a simple exact rule for finite Laurent words. A dressed vector has the form

\[
 w(\theta)=\frac1{\sqrt2}\sum_{m,k}c_{m,k}|m\rangle e^{ik\cdot\theta}
 \tag{8}
\]

when starting from (4). For each term, the omitted common flow plus k has divergence \(q(m)-1_A\). Thus two terms in the same matter word have a divergence-free difference. Define the oriented harmonic signature

\[
 \mathsf h(k)_\mu=\sum_{e\in\mathcal E}k_e\,d_{e,\mu},
 \tag{9}
\]

where \(d_e\) is the signed unit coordinate step from A to B, including the actual sign of a periodic boundary step. Fiber integration kills a cross term unless its divergence and all three harmonic signatures vanish. At transverse x=0 the surviving term has phase one. Therefore

\[
 \|w\|_{\rm flat\ fiber}^2
 =\frac12\sum_{m,s}\left|\sum_{k:\mathsf h(k)=s}c_{m,k}\right|^2.
 \tag{10}
\]

Inner products obey the corresponding polarized rule. For a single normalized matter word the factor \(1/2\) is absent. This is an elementary integration of characters on the compact fiber. It does not assume a classification of all magnetic minima or localization of harmonic angles.

Keeping only the matter word and summing all its k coherently would instead evaluate every link angle at zero. That operation is not (10). Although each H4 action has only four hops, products with the preparation strings and conjugate paths can enclose a noncontractible loop on the finite tori used here. Even side eight has a nonzero discrepancy in the second moment. The full discrepant rows are preserved below and in the logs.

For any fixed smooth scalar matrix element, first average its gradient/harmonic fibers. Its remaining transverse function is smooth on a chart of \(\mathcal Q\). Integrating its Taylor expansion against the normalized even rescaled packet gives its value at zero plus \(O(g^2)\); constant terms cancel correctly between normalized packets, linear terms vanish, and cutoff errors are exponentially small. This supplies every flat-fiber limit used below. It is not substitution of a normalizable state at exactly zero angles.

## 5. Exact magnetic moments and their full rotor meaning

Omit only the common scalar phase and write

\[
 v(\theta)=\frac{|m_c\rangle e^{-i\theta_{dc}}-|m_e\rangle e^{-i\theta_{de}}}{\sqrt2}.
\]

On the flat transverse fiber define normalized Haar averages

\[
 \mu=\int v^*H_4v,\quad
 \nu=\int\|H_4v\|^2-\mu^2,\quad
 \gamma_\sigma=\int\|B_\sigma H_4v\|^2.
 \tag{11}
\]

All matrices here are finite matter matrices of finite Laurent polynomials; the integrals are exactly computable by (10). In particular \(B_\sigma v=0\) everywhere on this fiber, by the contractible plaquette identity (5). Since \(\|B_\sigma\|\le5\),

\[
 0\le\gamma_\sigma\le25\nu.
 \tag{12}
\]

This follows by writing \(B_\sigma H_4v=B_\sigma(H_4-\mu)v\) before integrating. A positive \(\gamma_\sigma\) proves both lack of magnetic stationarity and nonzero variance; nonzero variance alone would not prove that this selected mark ceases to cancel.

The primitive enumeration gives the following exact integers. The mean was cross-checked with only two outward hops using \(\mu=-2\sum\|S_{ac}v\|_{\rm flat\ fiber}^2\), independently of the inward-hop action used for the second moment.

| Torus | \(\mu\) | \(\int\|H_4v\|^2\) | \(\nu\) | \(\gamma_- =\gamma_+\) |
|---|---:|---:|---:|---:|
| \(6^3\) | -64199 | 4127007446 | 5495845 | 7956600 |
| \(8^3\) | -159212 | 25353977392 | 5516448 | 7982020 |

For each of the four side/sign rows there is an explicit final matter/harmonic group with coefficient \(-1100/\sqrt2\). Its 44 retained Laurent terms are printed in full. They sum to -1100, obey Gauss with the common flow, and share the stated harmonic signature. This group alone contributes 605000 to \(\gamma_\sigma\). The full norm gives the table. The compact and original copies of all witness terms were also traversed by the separate evidence checker; this is bookkeeping validation of the saved evidence, not a second independent physics computation.

For comparison, incorrectly setting every link angle to zero gives:

| Torus | Wrong \(\nu\) | Wrong \(\gamma_- =\gamma_+\) |
|---|---:|---:|
| \(6^3\) | 5502897 | 8133884 |
| \(8^3\) | 5516460 | 7984376 |

The means happen to agree in these rows. That agreement is insufficient to validate the second moments or the stability coefficient. No all-period formula is inferred from either pair of rows.

The smooth dressed packets satisfy

\[
 \|D\Psi_{n,g}\|\le Cg^{-2},\qquad
 \langle H_4\rangle_{\Psi_{n,g}}=\mu+O(g^2),\qquad
 \operatorname{Var}_{\Psi_{n,g}}(H_4)=\nu+O(g^2).
 \tag{13}
\]

For the first estimate, in each of the two matter words (3) is a finite sum of second-order electric derivatives and first-order terms. The fixed integer strings shift derivatives by fixed constants. The rescaled smooth Hermite packet has derivatives of order k bounded by \(C_k g^{-k}\). No lower confinement bound for D is needed.

Consequently the *ordinary full rotor Hamiltonian* has

\[
 \boxed{\quad
 \langle h\rangle_{\Psi_{n,g}}=\frac{\mu}{4\tau g^2}+O(\tau^{-1}),\qquad
 \operatorname{Var}_{\Psi_{n,g}}(h)=\frac{\nu}{16\tau^2g^4}
                  +O(\tau^{-2}g^{-2}).\quad}
 \tag{14}
\]

Here the electric mean is \(O(\tau^{-1})\), \(\|KD\Psi\|=O(\tau^{-1})\), and the electric/magnetic cross term in \(\|h\Psi\|^2\) is at most \(O(\tau^{-2}g^{-2})\). The same bound controls the corresponding centering terms. This proves (14), including the remainder, without deleting D. Ordinary second moment means \(\|h\Psi\|^2\); membership in \(D(h)\) suffices for this quadratic moment.

For either tabulated graph, \(\Delta h=\sqrt\nu/(4\tau g^2)[1+O(g^2)]\). A scalar energy offset removes neither this variance nor \(\gamma_\sigma\). The negative extensive mean is relative to the supplied Hamiltonian convention and is not by itself a preparation cost or a ground-state claim. Both packet occupations have the same leading coefficients in (14).

## 6. The full dynamics disturb the cancellation

Put \(V(s)=e^{-i\delta sH_4}\), \(U(s)=e^{-ihs}\), and \(r=\delta s\). For \(|r|\le r_0\), all angle derivatives through second order of the finite matrix multiplier \(e^{-irH_4(\theta)}\) are uniformly bounded at fixed graph. Products with the dressed packet therefore obey

\[
 \sup_{0\le u\le s}\|D V(u)\Psi_{n,g}\|\le C_{r_0}g^{-2}.
\]

On the smooth core, Duhamel in the orientation with the electric term acting on V gives

\[
 (U(s)-V(s))\Psi=-iK\int_0^s U(s-u)D V(u)\Psi\,du,
 \quad \|(U(s)-V(s))\Psi\|\le C_{r_0}s/\tau.
 \tag{15}
\]

The smooth vectors and this integrable domain bound justify extension by the strong integral. One does not require an operator-norm bound on D or a new invariant field-only sector.

Let

\[
 F_\sigma(r)=\int\|B_\sigma e^{-irH_4}v\|^2
 \tag{16}
\]

over the same flat fiber. For fixed r in a compact small interval, weak-field localization and (15) imply

\[
 \langle M_\sigma\rangle_{U(4\tau g^2r)\Psi_{n,g}}
       =F_\sigma(r)+O(g^2).
 \tag{17}
\]

Taylor expansion of the bounded magnetic evolution, using \(B_\sigma v=0\), gives

\[
 F_\sigma(r)=\gamma_\sigma r^2+O(|r|^3).
 \tag{18}
\]

The error constants are finite graph constants. Thus a positive tabulated \(\gamma_\sigma\) yields \(F_\sigma(r)>0\) for all sufficiently small fixed positive r. This establishes actual disturbance of the flat cancellation for those physical preparations. It is more specific than concluding instability from an energy uncertainty estimate.

For completeness, write \(G=\sum_m\|B_m\|^2\) for the full chosen instrument. Its bounded dissipator has trace-class norm at most \(2\kappa G\). Duhamel between the full trace-preserving semigroup \(T_\kappa(s)\) and the unitary channel \(\mathcal U_s\) gives

\[
 \|T_\kappa(s)-\mathcal U_s\|_{1\to1}\le2\kappa Gs.
 \tag{19}
\]

The underlying Hamiltonian may be unbounded; its unitary channel is an isometry and the perturbation is bounded. In particular the change in the expectation of \(M_\sigma\) is at most \(2\|M_\sigma\|\kappa Gs\). For fixed \(\kappa\tau\), this is \(O(g^2)\) at the time in (17). Equations (17)-(18) therefore hold to the same limiting order for the *full unconditioned state*, with every other event allowed. They do not condition on no preceding global event, and do not replace the original dissipator by a no-jump law.

The result concerns the indicated shrinking times. It neither extrapolates (18) to a damping law nor establishes survival, decay, or detection at a fixed positive physical duration. The electric term is small in this particular comparison because \(s=O(\tau g^2)\) and the initial packet has controlled derivatives, not because it is absent from the generator.

## 7. Positive short count windows and their noise

Let \(N_\sigma([0,b])\) count every selected resolved mark in the full process initialized in \(\Psi_{n,g}\), with other marks and earlier marks within the window unrestricted. Its exact mean is

\[
 m_n=\kappa\int_0^b
  \operatorname{Tr}(M_\sigma T_\kappa(s)|\Psi_{n,g}\rangle\langle\Psi_{n,g}|)\,ds.
 \tag{20}
\]

There is a finite physical birth cap on this finite graph. No independent-event assumption is used in (20).

### 7.1 The individual rare-count regime supplied in Root22

The domain bound \(\|h\Psi\|\le C/(\tau g^2)\) and (6) imply

\[
 |\|B_\sigma U(s)\Psi\|^2-p_{n,g}|
 \le C\left(\frac{s}{\tau g}+\frac{s^2}{\tau^2g^4}\right).
\]

Indeed \(\|(U(s)-I)\Psi\|\le s\|h\Psi\|\); expanding the squared B norm retains the small factor \(\|B\Psi\|=O(g)\) in its cross term. Combining this with (19) and integrating proves

\[
 m_n=\kappa b\left[g^2q_n+O(g^4)+
  O\!\left(\frac b{\tau g}+\frac {b^2}{\tau^2g^4}+\kappa Gb\right)\right].
 \tag{21}
\]

At fixed graph and \(\kappa\tau>0\), the positive choice \(b=o(\tau g^3)\) gives

\[
 \frac{m_n}{\kappa b g^2}\longrightarrow q_n,\qquad
 \frac{m_1-m_0}{\kappa b g^2}\longrightarrow |\chi_p|^2.
 \tag{22}
\]

This independently reproduces the sufficient Root22 proof, rather than inferring persistence of cancellation. The latter in fact fails on the longer time scale in section 6.

### 7.2 A contrast-only improvement

The two packet densities are normalized, even in the rescaled transverse coordinate, and have uniformly bounded rescaled second moments. For any smooth transverse scalar f, their expectation difference is bounded by \(Cg^2\|f\|_{C^2}\), up to exponential tails. Apply this after fiber averaging to

\[
 f_r(\theta)=v(\theta)^*e^{irH_4(\theta)}M_\sigma(\theta)
                         e^{-irH_4(\theta)}v(\theta).
\]

At fixed graph and \(|r|\le r_0\), \(\|\overline f_r-\overline f_0\|_{C^2}\le C|r|\). A bounded derivative of this finite smooth matrix expression proves the estimate. Constant terms cancel between the two normalized packet densities and linear terms integrate to zero. Hence the magnetic contrast changes from its initial value by at most \(Cg^2|r|\). Using (15) separately for each packet and then (19),

\[
 \frac{m_1-m_0}{\kappa b}
   =p_{1,g}-p_{0,g}+O\!\left(\frac b\tau+\kappa Gb\right),
       \qquad \delta b\le r_0.
 \tag{23}
\]

Therefore \(b=o(\tau g^2)\) suffices for the contrast limit in (22), provided \(\chi_p\ne0\). This statement permits common matter-induced backgrounds larger than \(g^2\). It does not retain the individual limits in (22), their signal-to-noise denominator, or a detection-resource advantage. It also relies on the specified parity and finite moments of these two packets; an arbitrary pair of preparations does not automatically obey this improved estimate.

### 7.3 A controlled critical window showing the extra background

Fix \(\eta>0\) and choose \(b=4\tau\eta g^3\). For \(s\le b\), \(r=\delta s\le\eta g\). On each flat fiber, the amplitude \(B_\sigma e^{-irH_4}v\) vanishes at transverse x=0,r=0. Its joint Taylor expansion begins with the term linear in the transverse angle and the term \(-irB_\sigma H_4v\). The squared first term averages to \(g^2q_n\). The squared second term averages to \(r^2\gamma_\sigma\). The mixed term is linear in the rescaled transverse coordinate and integrates to zero. Polynomial-Gaussian moment bounds and smooth coefficients bound the remaining averaged terms by \(O(g^3)\), uniformly for \(0\le r\le\eta g\).

Equation (15) has amplitude error \(O(g^3)\) here, while the magnetic output amplitude is \(O(g)\), so its effect on the probability is \(O(g^4)\). The dissipative error is \(O(\kappa G\tau g^3)\). Thus, with no deleted electric or background dynamics,

\[
 \boxed{\quad
 \frac{m_n}{\kappa b g^2}\longrightarrow q_n+\frac{\gamma_\sigma\eta^2}{3},
 \qquad
 \frac{m_1-m_0}{\kappa b g^2}\longrightarrow|\chi_p|^2.
 \quad}
 \tag{24}
\]

The factor \(1/3\) is \(b^{-1}\int_0^b(s/b)^2ds\). This formula uses the full finite-graph coefficient (11), with harmonic averaging. It demonstrates a positive, common matter background at the critical window on the evaluated tori. It is not a lower bound ruling out useful longer windows with a different criterion or a different supplied state.

### 7.4 Count variance and repetitions

Let \(\lambda=\kappa\|B_\sigma\|^2\le25\kappa\). The two-selected-mark factorial intensity at ordered times is bounded by \(\lambda^2\): apply the positive marked map twice and trace preservation between them. This remains true when every other event is unrestricted. Hence

\[
 0\le\mathbb E[N_\sigma(N_\sigma-1)]\le\lambda^2b^2,
 \quad
 \max(0,m_n-m_n^2)\le\operatorname{Var}(N_\sigma)
       \le m_n+\lambda^2b^2-m_n^2.
 \tag{25}
\]

Both the regime (22) and the critical regime (24) have \(m_n\asymp\kappa b g^2\) and \(\kappa b/g^2\to0\). Thus \(\operatorname{Var}(N_\sigma)/m_n\to1\) there. A Poisson law is not assumed or proved.

For N independent *supplied* preparations in each arm, \(\chi_p\ne0\), and exact control of those two preparation laws, the squared signal-to-standard-error ratio is asymptotic to

\[
 \frac{N\kappa b g^2|\chi_p|^4}{v_p+|\chi_p|^2}
 \tag{26}
\]

in (22), and has denominator \(v_p+|\chi_p|^2+2\gamma_\sigma\eta^2/3\) in (24). A prescribed sign-error tolerance follows with a sufficiently large constant in a Chebyshev bound. No cost of coherent preparation, strings, reset, timing, mode delivery, or finite microscopic apparatus is included. Formula (26) is not asserted in the wider contrast-only regime (23).

## 8. Normalized initial selected outputs

This section answers the additional energy-accounting question for each resolved sign. Define, at every fixed positive g,

\[
 X_{\sigma,n,g}=\frac{B_\sigma\Psi_{n,g}}{\sqrt{p_{n,g}}}.
 \tag{27}
\]

Normalization must occur before the weak-field limit. Dividing the flat zero vector from (5) would be meaningless. If \(\ell_p x\) is the plaquette angle in rescaled coordinates, the normalized reference field profile converges, after factoring the fixed output string and an irrelevant phase, to

\[
 \frac{(\ell_p x)\psi_n(x)}{\sqrt{2q_n}},\qquad
 \int |\ell_p x|^2|\psi_n(x)|^2dx=2q_n>0.
 \tag{28}
\]

The reference density in (28) is again even. Vacuum input gives a one-excitation reference profile; one-particle input generally gives an even combination including zero and two reference excitations. These are harmonic reference profiles at preparation, not energy eigenstates of the charged full Hamiltonian.

The exact finite-g factor is a smooth sine divided by its nonzero norm. Differentiating it through second order, using \(p_{n,g}\asymp g^2\), gives \(\|D X_{\sigma,n,g}\|\le Cg^{-2}\). For example, a derivative of the sine contributes \(O(1/g)\), and a second derivative of the total normalized product contributes at most \(O(g^{-2})\) in norm; Gaussian tails and cutoff commutators have the same controlled bounds. There is no electric-domain singularity beyond the ordinary rescaling already used in (13).

For each output word let \(u_\sigma(\theta)\) be that unit matter vector with one of the two fixed path phases in (5), omitting the common scalar phase only for magnetic computation. Define

\[
 \mu_{{\rm out},\sigma}=\int u_\sigma^*H_4u_\sigma,
 \qquad
 \nu_{{\rm out},\sigma}=\int\|H_4u_\sigma\|^2-\mu_{{\rm out},\sigma}^2.
 \tag{29}
\]

Both paths differ by a contractible plaquette and agree on the flat fiber. The normalized curvature weighting in (28) does not change the leading flat-fiber constants. The exact finite-g reference density is even up to cutoff tails, so its smooth magnetic matrix elements differ from their flat value by \(O(g^2)\). Repeating the full electric accounting in (14) proves

\[
 \langle h\rangle_{X_{\sigma,n,g}}=
        \frac{\mu_{{\rm out},\sigma}}{4\tau g^2}+O(\tau^{-1}),\qquad
 \operatorname{Var}_{X_{\sigma,n,g}}(h)=
        \frac{\nu_{{\rm out},\sigma}}{16\tau^2g^4}
                          +O(\tau^{-2}g^{-2}).
 \tag{30}
\]

The independent full pair-form action gives:

| Torus | Resolved sign | \(\mu_{{\rm out},\sigma}\) | \(\int\|H_4u_\sigma\|^2\) | \(\nu_{{\rm out},\sigma}\) | \(\mu_{{\rm out},\sigma}-\mu\) |
|---|---:|---:|---:|---:|---:|
| \(6^3\) | -1 | -62190 | 3874573900 | 6977800 | 2009 |
| \(6^3\) | +1 | -62190 | 3873977172 | 6381072 | 2009 |
| \(8^3\) | -1 | -157200 | 24718856504 | 7016504 | 2012 |
| \(8^3\) | +1 | -157200 | 24718256696 | 6416696 | 2012 |

The full control also preserves the incorrect all-zero-angle comparator variances: respectively 6996664, 6396208, 7016584 and 6416760. The mean was again checked by the positive two-outward-hop Gram sum.

Thus for these examples the conditional change of ordinary *rotor h* expectation is

\[
 \langle h\rangle_X-\langle h\rangle_\Psi=
 \begin{cases}2009/(4\tau g^2)+O(\tau^{-1}),&6^3,\\
 2012/(4\tau g^2)+O(\tau^{-1}),&8^3.
 \end{cases}
 \tag{31}
\]

It is positive for sufficiently small g for both signs, independent of n at leading order. This is a conditional state-expectation comparison under the supplied h, not a trajectorywise spectral energy transfer. The GKLS specification supplies no reservoir energy observable or energy-conserving autonomous dilation that would identify (31) with heat. It is also not the removal of one \(O(\tau^{-1})\) field photon: the leading shift and both large variances come from the supplied charged matter preparation and the original formation operation. A heat, work, or absorption interpretation requires a separately specified balance model and an appropriate measured energy distribution.

The coherent original edge mark \(B_++B_-\) has orthogonal final sign ranges for its initial norm, so its initial effect is twice (5). The full coherent instrument retains output coherences. No equality of its subsequent states with the resolved instrument, and no coherent-output energy table, is inferred by adding the two rows above. The full semigroup comparison (19) applies to either complete specified instrument with its own G; the resolved count and resolved conditional outputs in this report retain their actual labels.

## 9. Ordinary microscopic energy is a different operator question

This short distinction is necessary to prevent the rotor h calculation from being silently advertised as a microscopic ordinary-energy theorem. The authorized compensation parent specifies

\[
 H_{\epsilon,S}=\delta\epsilon^{-4}(W+\epsilon T_S+\epsilon^2 C_S),
 \quad PC_SP=M_S+\frac{D}{S(S+1)},\quad
 M_S=PT_S^2P,\quad \epsilon^2S(S+1)=\delta/K.
 \tag{32}
\]

For any normalized *bare P vector* x in the finite physical spin space, C preserves P and \(T_Sx\) lies in the one-vacancy sector. The two terms of \(H_{\epsilon,S}x\) are orthogonal. Therefore, exactly,

\[
 \langle H_{\epsilon,S}\rangle_x
    =\delta\epsilon^{-2}\langle C_S\rangle_x
    =\delta\epsilon^{-2}\langle M_S\rangle_x+K\langle D\rangle_x,
\]
\[
 \operatorname{Var}_x(H_{\epsilon,S})
    =\delta^2\epsilon^{-6}\langle M_S\rangle_x
       +\delta^2\epsilon^{-4}\operatorname{Var}_x(C_S).
 \tag{33}
\]

These identities use the full ordinary microscopic Hermitian Hamiltonian, not an effective slow generator or a no-jump eigenvalue. For physical spin-box approximants of the fixed-g smooth states here, D moments converge; strong bounded convergence of the finite rotor products gives \(\langle M_S\rangle\to\langle M\rangle\), with \(M=\sum_aF_a^*F_a\). Thus the scaled ordinary mean and variance in (33) have, at each fixed g, leading coefficients \(\langle M\rangle\). This is an ordered \(S\to\infty\) statement, not a uniform simultaneous g/S resource rate.

For the preparation in (4) there is a further exact identity,

\[
 J^*MJ=(|\mathcal E|-24)I-\Re W_p.
 \tag{34}
\]

Each of the four occupied B sites removes six legal outward edges, giving the diagonal part. The only cross-branch collision of outward words comes from a common plus A neighbor of c and e. On these simple tori their common A neighbors are a and d; d has minus charge and yields distinct final matter charges, so only a contributes. Its two path phases give the negative plaquette cross term. The small independent single-hop polynomial control checks all coefficients of (34) on both enumerated tori.

For each single output matter word in (5), the six occupied B sites remove 36 outward edges and distinct destinations produce orthogonal matter words. Hence, for any field vector in that fixed matter word,

\[
 \langle M\rangle_X=|\mathcal E|-36,
 \qquad \langle M\rangle_\Psi=|\mathcal E|-24-\langle\Re W_p\rangle_{\phi_{n,g}}.
 \tag{35}
\]

For sides six/eight the weak-field input values are 623/1511 and the output values are 612/1500. The difference tends to -11 as \(g\to0\). Thus even the leading conditional expectation comparison of *bare-P microscopic Hamiltonian values on these chosen approximating states* has a different scale and sign from (31). This is not a contradiction: (14), (30) and (33) are assertions about different operators and limit questions.

In particular, \(X_{\sigma,n,g}\) is the normalized **effective** initial B output. At microscopic time zero a bare P state has no empty A site, so the original microscopic formation j has zero immediate output. Its actual subsequent microscopic post-jump state requires the preceding virtual/initial-layer dynamics. This packet does not replace that state by x in (33), does not infer its ordinary energy from density convergence, and does not claim an actual microscopic jump heat of either sign. The microscopic identities are supplied to distinguish the notions, not to close that separate post-jump problem.

## 10. Evidence, failures and remaining obligations

The control inventory is deliberately bounded. `primitive_dynamics_control.py` enumerates a single H4 action and then the original selected birth on side six. `topology_and_gram_control.py` adds side eight and cross-checks both means with positive Gram norms. `output_energy_control.py` acts once on each normalized-output matter word for both sides/signs. `single_hop_energy_control.py` checks (34) using only outward paths. Later scripts reuse only the independent primitive helpers written here; they are not four fully independent implementations. No time propagation, large parent calculation, author runner or microscopic post-jump simulation was performed.

All path coefficients are integers, the normalization arithmetic uses exact rational numbers, and the norms in the tables are exact finite sums. There are 9760/13246 nonzero H4 Laurent terms for the two prepared inputs, and 16338/19689 terms for each subsequent selected sign. The first calculation directly checks Gauss on every retained term with the specified common flow. The output calculation does the same for all its retained terms. The evidence checker reads every saved JSON payload, traverses all 44-term instability witnesses in both their original and compact copies, checks their adjacency/Gauss/harmonic signatures, verifies every table subtraction and bound (12), and checks source/result/stdout identities. It does not independently recreate all H4 paths.

The actual science-run wall times were 1.6946813750546426 seconds, 8.516209915978834 seconds, 5.925221249926835 seconds and 0.06178129091858864 seconds, respectively. All exited zero with empty stderr. The source pinning and saved-evidence inspection have their own complete execution records. No execution failure is hidden. The all-link-angles-zero route fails to give the stated physical second moments and instability coefficients; its complete unfavorable rows remain part of this packet rather than being discarded.

Core evidence identities are:

| Artifact | SHA256 |
|---|---|
| `primitive_dynamics_control.py` | `f24031d1dc29abecae15dc47adf5a7eb1cadd83957f241fbc7a9bcdd321d8e2c` |
| `PRIMITIVE_DYNAMICS_RESULTS.json` | `99fc9bc4fe2ba955786ef7c4568530115e2c27106e32643cc6500e621c429da2` |
| `topology_and_gram_control.py` | `3ec0cdf6beb3e46f1129c272c0eef558a2df202e10035959daa04add36e204e9` |
| `TOPOLOGY_GRAM_RESULTS.json` | `12b5f76860d94008911e3d6bbe252f737373f6c0e20b4227b459420273dca42e` |
| `output_energy_control.py` | `2953f3d05511572527fe345ea79f501eabe773b8950268d36c23c74b1f030794` |
| `OUTPUT_ENERGY_RESULTS.json` | `da454f116779c0a47aeb110aa2042f68a44a2a5a822940fa01e043116b8aca86` |
| `single_hop_energy_control.py` | `97a5ac743c1ac534ec673fb3cdac212010f278a375d01ee0f33afdcd9137e41e` |
| `SINGLE_HOP_ENERGY_RESULTS.json` | `effde2b7c1d9f171410cfeb977c3a9b56518b47efe373bf33f672872a216477c` |
| `SOURCE_PINS.json` | `ee19e1ca0614a3709a1c16a76604ca569fa59d2ae6c8e9ae1c2b88d273b7b609` |
| `EVIDENCE_CHECK.json` | `9eaa4851783d4215f1d504d911ccea2142e5aaf078aa2ddcee4bb890686d894f` |

The final PRE seal binds this report, all source copies, code, complete result files, stdout/stderr and execution/evidence records. Generated Python bytecode is excluded as a transient cache. No repository, publication, audit state, original source, earlier sealed packet or editable instruction file was changed.

The unresolved scope is explicit:

* Root22's coherent charged preparation and packet are supplied mathematical inputs. A preparation history, stabilization mechanism, physical apparatus, reset cost, or native selection is not established.
* The strict instability and energy coefficients in the tables are finite-size results for the stated two tori. Equations (10)-(11) and (29) define the corresponding quantities on other fixed admitted tori; their numerical signs and exact values have not been silently extrapolated.
* The count statements begin at the supplied preparation time. A long waiting interval before an arriving photon, a fixed-duration signal survival law, an optimal bandwidth, and finite experimental parameter selection remain open.
* Original matter, Gauss, electric terms and full original channels are retained. A vacuum field Hamiltonian after preparation, localization of harmonic angles, or a fictitious destination measurement would change the problem.
* Rotor ordinary-energy moments, bare-P microscopic ordinary-energy moments, the actual microscopic post-jump energy distribution, and reservoir heat are distinct. Only the first two, in the precise senses above, are evaluated here. Trace-norm convergence of densities supplies none of the missing unbounded-energy conclusions on its own.
* All weak-field and, where mentioned, spin limits are ordered with the fixed data stated above. No arbitrary simultaneous schedule, uniform volume rate, or resource necessity is concluded.

This closes the authorized bounded PRE reconstruction and leaves it frozen for a later separately released-source comparison.
