# POST46 evidence verification receipt

The released equations agree with PRE46. Required prose repair: remove the assertion that only the zero-field basis vector has zero magnetic-current expectation; every physical electric basis vector and normal diagonal mixture does too. Exact replacement and proof are in POST.md §2. No source was edited.

Source capture verified the author seal plus all 15 members, all 31 PRE members plus the PRE seal, and six permitted live model/instruction origins. Four historical42 paths mentioned inside author source pins were not opened. POST_SOURCE_PINS.json and POST_PRESERVATION_BASELINE.json record the exact scope and identities.

The new complete verify_post_readonly.py and record_post_verification.py were inspected before their one run. The former only reads allowed data and prints JSON; the latter explicitly records fresh output. Neither imports or executes historical or author code. The fresh run used Python -B, exit 0, empty stderr, 1.5653212501201779 seconds externally, with all 77 observed files byte/stat unchanged. Full source snapshot, stdout, stderr and before/after receipt are in post_verification_attempt01/. Recorder streams are retained separately. No failed POST attempt occurred.

Read-only exact checks covered every one of the author's 8480 primitive rows, 180 real covariance entries, all means, edge currents, vertex drifts and mark norms. Every primitive row was matched to previously sealed independent star data. Five complete graph summaries, five complex polarization conversions, both Fourier rows, 553 stored PRE magnetic terms, 25 zero diagonal current terms, two nonzero circulation labels and the prior nonzero coherent-cycle current were checked. The root read-only compact payload matches these reconstructions. Author source/snapshot/output/receipts and all seal bindings agree.

The complete final/working proof, every distinct author code file including writers as inert text, source metadata, execution records, root compact output and all new verifier output were read. All five 6-by-6 covariance matrices, associated compact arrays and the complete working/final diff were read without truncation. Long raw vectors were checked by exact code, not all manually read. An initial batched display was tool-truncated; the omitted code and records were subsequently reread completely. This was a display limit, not a failed scientific or verification execution.

Manual reasoning covered the sign conversion, bounded commutator/domain extension, all-normal-state mild-equation justification, primitive orthogonality for both original instruments, full-generator first derivatives, Hermitian versus bilinear covariance, volume/phase normalization and the finite-wavevector cosine remainder. These analytic conclusions are not delegated to finite controls. Author numerical controls concern initial gains only; their finite scope is retained.

PRE46 remains unchanged, including its original preseal prose repair, full logs and failed-shortcut record. Its stronger integrated, norm, time-remainder, Fourier-matrix and coherent-field results remain PRE-attributed. The new POST finding is not relabeled as blind PRE work. No applied audit status, publication claim, empirical comparison or derivative transfer is made.
