# Mathematical approach registry

| Family | Object / formulation | Mechanism or invariant | Terminal obligation | Strength vs target | Status | Concrete evidence | Reopen condition |
|---|---|---|---|---|---|---|---|
| Fixed-profile scalar | (q_S=\langle\eta_\infty,P_SB_SP_S\eta_\infty\rangle) | Strong profile convergence and finite-core truncation | Bound the scalar phase at (t=1/4) | target-equivalent | active | Exact reduction and Cauchy tail | New uniform spectral or propagation estimate |
| Entrywise kernel | (K_S(a,b;t)) for each fixed pair | Fixed-entry decay plus finite-support approximation | Prove all fixed entries vanish | stronger than target | active | Exact spectral identity and finite diagnostics | Entrywise stationary-phase theorem with finite-spin control |
| Discrete WKB / global transport with alias control | 15-band Jacobi family | Bloch phases, two avoided crossings, central normal form, global eigenphase quantization | Uniform branch phases and overlap amplitudes, followed by a discrete oscillatory-sum bound including aliases | target-equivalent | active | Frozen-cell matrices and central coefficient match | Verified global transfer/connection formula and alias-aware sum estimate |
| Matrix-valued Egorov / adiabatic bands | 15-by-15 operator-valued semiclassical symbol with (h=1/S) | Superadiabatic band projectors and transported observables | Extend bounded-time, uniformly gapped Egorov control to time (O(h^{-1})), while resolving crossings | unknown/comparable | provisional | Stiepan-Teufel gives an (O(h^2)) Egorov estimate for an isolated band on bounded times; present model has closing gaps | Prove stable iteration away from crossing tubes and match each tube with the two-band normal form |
| Spectral commutator | (\mathrm{ad}_{N_S}) on observables | Separate zero/near-resonant pairs and organize off-diagonal amplitudes | Pointwise phase-sum cancellation at theta=tC | unknown/comparable | provisional | Exact diagonal/off-diagonal split; a commutator identity alone controls a time derivative or average, not the value at one large time | Combine with global eigenphase expansion and discrete oscillatory-sum bound |
| Homogeneous Fourier | (N_\infty=2I-U-U^*) | Bessel kernel and stationary phase | Relate the reference decay to finite-spin (N_S) at (tC) | weaker | provisional | Exact (O(S^{-1})) reference formula; finite-spin transfer remains open | Uniform long-time comparison theorem |
| Prepared-state endpoint strip | Electric endpoint cap and spectral split | Weighted barrier, arcsine low-energy law, and strong-profile transfer | Bound actual-state and reduced-scalar endpoint terms uniformly in phase; make them vanish as the strip shrinks | weaker | conditional-support complete | The limsup strip mass is at most acos(1-8 delta)/pi; Eq. (11) transfers it to q_S, and V is diagonal | Couple the interior WKB expansion to the endpoint remainder |
| Arithmetic subsequence | Actual spin-index readout sequence | Exact or interval-certified phase separation | Prove two subsequences stay separated | stronger than target if no limit | unexplored | No certified witness; scans only | Uniform eigenphase expansion with controlled remainder |
| Native premise bridge | Framework axioms and supplied model | Explicit construction/independence witnesses | Derive or refute selection of supplied dynamics | separate upstream obligation | unexplored | Sources classify dynamics as supplied | Separate axiom-to-model campaign after this limit question |
| Primitive five-cell Bloch and cross-fiber character | Exact five-site Casimir family with a slowly varying cell coordinate | Period-three multiplication shifts the five-cell Bloch fiber by (4 pi/3); the principal inter-fiber phase has two nondegenerate joint critical points | Establish a global finite-spin propagation/overlap estimate including genuine five-cell Bragg gaps and aliases | target-equivalent support route | active | Exact identity on 2,001 signed edges; deterministic Fourier-shift and 5x5 symbol checks; exact Hessian determinant 24 | Prove uniform transport from the frozen symbol, then estimate the actual prepared-profile correlation |
| Five-site Schur/Weyl reduction | Two-energy resolvent of the exact Jacobi matrix and period-three multiplication | Eliminate four sites per block with a rational Schur pencil | Uniform resolvent-to-selected-time conversion with pole control | target-equivalent | provisional | Exact block determinant and finite rational identity checks | Derive uniform pole/residue asymptotics that retain the two-energy observable |
| Imaginary-time reversible-chain kernel | Exact reversible generator for the full staggered evolution | Rewrite readout as a weighted squared transition kernel at complex time | Pointwise weighted residue estimate for the actual kernel | target-equivalent | blocked-equivalent | Exact rates and normalization; residue lumpability counterexample | Obtain a complex-time kernel estimate that is specific to the supplied rates |
| Weighted lag-sum/arithmetic | Actual eigenphase differences and signed readout weights | Abel summation with lag variation and discrete exponential sums | Summable bound with actual weights, aliases, and exceptional pairs | stronger sufficient criterion | open | Exact phase decomposition; leading moment law; rational certified curvature samples | Derive five-cell eigenphase/overlap transport or a controlled resonant contribution |
| Weighted lag/alias diagnostic | Finite actual eigenvalues, prepared-profile coefficients, and cosine-character overlaps | Compute the exact finite double sum, lag weights, first phase differences, and per-lag Abel bound | A uniform weighted estimate as spin grows | exploratory finite test | completed finite check | At S=24,48,96 the spectral/direct identity error is below 3.1e-15; positive-lag Abel bounds for twice the readout sum are 96.97, 213.99, and 475.73 | Replace the one-lag triangle bound with a uniform two-dimensional cancellation estimate or controlled alias weights |
| Random-phase concentration | Independent auxiliary phases and diffuse prepared weights | Haar variance bounded by maximum eigenweight | Show the deterministic phases share the needed cancellation | failed for exact target | rejected inference | Near-identity spectral-rounding witness gives revival outside exact coefficient family | Reopen only with a direct deterministic phase/weight estimate |
| Exact residue conservation | Commutator of the actual generator with the period-three readout | Compute the (0,1) matrix element | Would require an exact symmetry or conserved output | weaker route | rejected | ([G_S,O])_{0,1}=-C+4-2/C\ne0) for every integer (S>=1) | No conservation route; seek non-symmetry asymptotics |

No family is marked `candidate-complete`. Reaching the scalar (q_S) is not closure of the readout target.
