# Independent energy-coherence PRE execution record

1. The three specifically allowed model notes were hash-verified against the dispatch and snapshotted. Their complete bodies had already been read in this same independent session and were not redundantly re-read. The current workflow and local AGENTS pointer also matched the previously read instruction revision.
2. The supplied primary reference https://arxiv.org/pdf/2112.04694v1 was opened with the web PDF reader. Equation (2), its pure-state normalization and following basic-properties paragraph were checked. No iid, periodicity or clock-bit conversion theorem was used. The exact versioned PDF was downloaded read-only for a source snapshot and hashed.
3. CHECKPOINT.md recorded the bounded objective, isolation and active routes. No root checkpoint, energy-coherence-personal, autonomous-process-personal, or other new checker packet was read.
4. coherence_checks.py was written from the supplied primitive model and standard finite QFI formula. It imported no repo/campaign builder. Its complete run succeeded; full stdout/stderr is in coherence_checks.log, and every result is in COHERENCE_CHECK_RESULTS.json. It combined exact rational physical-word counts with finite floating matrix consistency checks. No expensive microscopic propagation or audit runner was invoked.
5. PRE.md was written from the independent derivation. Its exact, approximate, mean/variance, and sharpness boundaries are explicit. The previously read planning AGENTS bytes were revalidated unchanged and snapshotted. A short explanation of fidelity data-processing hypotheses was added before sealing.
6. Every local source and snapshot was rehashed at the end. SOURCE_VALIDATION.log records all matches. The versioned external PDF snapshot hash was rechecked locally; no claim of a second live PDF retrieval is made. All work files were frozen read-only and bound by PRE_SEAL.json before any source release.

Reproduction: `python3 coherence_checks.py > coherence_checks.log 2>&1` in this directory, with Python and NumPy. No tool or scientific check failed in this task. No source, axiom, audit, publication, or editable instruction file was changed.
