# PRE46 verification and preservation report

The complete three permitted model parents, complete new proof, both scientific source programs, recorder and read-only verifier were read. The scientific programs were each executed once with exit 0, unchanged source and empty stderr. No prior or author code was imported or run.

The inspected `verify_readonly.py` only reads pinned sources/data and prints a result. It has no write operations, subprocesses or scientific-program imports. Its separate receipt writer ran it once at 2026-09-25 09:41:49 UTC, exit 0, empty stderr, elapsed 0.04508229088969529 seconds. All 27 observed files retained identical hashes, size, mode and modification timestamp during this run. They comprise the then-current 21 packet files and six permitted live scientific/procedural origins. Full before/after inventories and stream hashes are retained.

The verifier checked all forty physical matter columns on K(2,4), their three recorded gated-electric costs, 553 magnetic terms and 217 dissipative terms. It checked the full off-diagonal current-divergence equalities, Gauss increments, number conservation and the reverse-column relations required by Hermiticity. The primitive source independently executes the full hops/births and their adjoints for both instruments and at each of three flux offsets; the verifier checks the stored column algebra without rerunning that code. The forty matter words divide into one N=2, twenty-four N=4 and fifteen N=6 words. This is a finite primitive fixture; its graph is not a degree-six cubic torus.

It also checked every one of the 140 initial branch rows for degree zero through six, all seven mean vectors/covariance matrices, eighteen complex-test field kernels, and the nonzero coherent-field circulation current. The kernel values on each diagonal field entry are loss 48, mean_f=144+84i, mean_g=120-144i, and Hermitian covariance derivative 324-1704i, in the stored coefficient units; off-diagonal field entries vanish for both instruments. The normalized coherent-field Hamiltonian current is twice delta times the displayed cycle incidence, with zero divergence.

All eighteen Fourier mean rows and 108 Hermitian covariance rows were checked in exact integer cyclotomic coefficients, together with each geometry's graph size and normalization. The complete compact output was read: forty current summaries, seven full star moment groups, all eighteen kernel rows, the coherent-current example, all three geometry summaries and all 126 Fourier rows. The 770 long raw current vectors and 140 primitive branch rows were mechanically verified in full; they are not all claimed as manually read one by one. Full unabridged data remain in the attempt outputs.

No scientific execution failed. One pre-seal prose correction was made after verification: the sentence describing values -60 kappa/+60 kappa now explicitly says these are the initial charge-mean derivatives, not the means. The actual initial means are zero as the unchanged equations already stated. `history/PRE_before_mean_derivative_wording.md` preserves the exact preceding note, and `PRE_WORDING_REPAIR.diff`/`.json` bind the sole replacement. No equation, scientific program or data value changed. The controls and read-only verifier do not consume PRE.md as scientific input, so no scientific run was repeated or restamped for this prose correction. The final sealer checks that the old observed PRE bytes match the preserved snapshot and that the new note differs only by the recorded phrase.

The normal-state continuity and uniform fixed-graph time remainder are analytic statements, not claims established by finite controls. The domain proof uses the bounded diagonal charge observable in the trace-class mild equation and never differentiates an undefined electric mean. The remainder uses the exact scalar first-sector survival weight and the bounded observable generator; it supplies no volume-uniform or microscopic derivative transfer. All frequency, detection, empirical and physical-unit limitations in PRE remain in force.

`SOURCE_PINS.json` binds six unchanged origins and their snapshots. The final seal includes every new program, complete stream, receipt, source, proof and preserved wording history. The manifest/receipt/sealing tools are explicitly writers confined to this new packet. No author46 or forbidden packet was accessed, and no external publication, audit or repository state was changed.
