# POST read and preservation log

The released root35 candidate and all nine seal members were read completely as source/evidence, including the proof, working scratch, code, every scientific JSON row, stdout/stderr, source metadata, local review record and execution receipt. Copies under `post_sources/native-ground-filling-personal/` preserve their exact bytes plus the author seal. None of those programs was imported or executed.

The 147 local rows were displayed in two complete TSV extracts (`POST_ROOT_LOCAL_r1.tsv`, 72 rows, and `POST_ROOT_LOCAL_r2.tsv`, 75 rows). `POST_ROOT_REMAINING_ROWS.json` preserves the full remaining scientific and execution-related payload: 26 artificial ambient-set averages, four torus geometries, 28 selected occupancies, thresholds and metadata. All were read. The complete root note was also recovered in bounded line ranges after compaction.

Three later diagnostic schema-display tool returns were truncated (an aggregate read, an unbounded first-item display, and a display that accidentally retained the nested `pattern_rows` key). They were not taken as completed evidence reads. The previously completed TSV/remaining-payload reads and the subsequent full 14,166-byte POST verification stdout supplied the complete relevant evidence. These were output-budget failures, not scientific failures or changed results. No report or verdict rests on an unread tail of a truncated response.

The genuinely read-only `post_check.py` was independently written for source/payload correspondence. It was run once against the canonical path; its source snapshot, complete stdout, empty stderr and true execution receipt are preserved in `post_verification_attempt01/`. That run exited zero. It matched all 147 local counts and multiplicities against immutable PRE data, calculated the five union-maxima rows from those counts, checked 26 artificial averages and 28 finite-torus rows with the PRE's falling-factorial organization, verified four strict half-filling excesses, and matched the two geometries present in both stored packets. It performed no new physical simulation and no author-code execution.

The sealed PRE utility `verify_pre.py` writes three named PRE files despite its read-only description. It was only parsed as source/AST here. Its actual calls and line numbers are retained in the new stdout. It was never executed during POST; no historical file was rewritten or its permission relaxed. The root's warning and reported non-execution are preserved in POST.md.

The author's source inventory lists four historical one-pair context entries. Only the entries within this released inventory were read; their referenced files were never opened, resolved for inspection or live-hash-checked. They remain outside this POST. No active candidate, other checker packet, campaign checkpoint/outcome, parent runner, publication or audit state was accessed or changed.

All 35 PRE seal members and the PRE seal were verified byte-identical before final POST sealing. All nine released author members, their seal, the explicit own anchors and permitted live parent/instruction sources were checked by exact SHA256. The root working scratch artifact and all prior PRE control attempts remain untouched. No scientific discrepancy, control failure or required theorem correction was found; the old verifier's mutation behavior is the explicit retained tooling limitation.

Before final sealing, two local report-formatting escapes were corrected: the opening inline-math delimiter in the first paragraph and an accidental form-feed in a LaTeX fraction. `POST_FORMAT_REPAIR.diff` preserves that narrow draft change. No scientific value or source was changed; a control-character scan of the corrected report is clear.
