# Released-source recovery review of original local charge covariance

2026-09-25. No required mathematical or correspondence repair was identified in the frozen candidate within this review's scope. The current, initial covariance and local finite-time estimate are supported as conditional mathematics of the supplied finite common model and minimum-number preparation. This is a **new released-source recovery review**, not either original reviewer's final approval, a new blinded derivation, a retained audit verdict, or authorization to publish or merge.

The reviewed worktree is `/Users/jonreilly/Documents/Codex/physics-sync-2026-09-24-fifth/local-charge-observation-publication`, branch `codex/mobile-record-local-charge-observation-20260925`, at base/HEAD `60c5f194d940a7bbaf1cdd545296e31d74a02f1a`. The frozen manifest is `LOCAL_CHARGE_OBSERVATION_FROZEN_SOURCES.json`, SHA256 `ab6385c5cde92eef0512a455934dc90600ac711dbb2e613c43b198a43848005d`. All 14 frozen files match. All three scientific parents equal their base-revision bytes.

| Final source | SHA256 |
| --- | --- |
| Canonical note, `docs/ORIGINAL_LOCAL_CHARGE_CURRENT_AND_FINITE_TIME_COVARIANCE_BOUNDED_THEOREM_NOTE_2026-09-25.md` | `087ba77c29a8d44a88aa3bb493d34bd1db64e10115a935a7521ea8895a12359e` |
| Wrapper, `scripts/original_local_charge_current_and_finite_time_covariance_2026_09_25.py` | `d7c2f48c8f8b238ac8b37183d91fff4553a50ceb635f2750b8bcaa995e66a731` |
| Runtime `current_noise_controls.py` | `62169110439e5e36b63bfc9b71eb24cc74b9d213b95e1ca5c70fcf682c463f36` |
| Runtime `local_support_controls.py` | `0209208aad50e24832a054d82ae2cec42a1cc57bb440a7bfea3093c141b1f263` |
| Local pair-form parent | `7c5bc10d0ca1127c2a1ef6f5cf9269caf6e8f023a09a061c2da0d8e033e35a7a` |
| Common field/record-limit parent | `c63db3296e5705c57693c2deb109e506f336fae4848d3ab0926d13a98929802b` |
| Formation-balance parent | `2ae8d264eaff3ab47ecf4ec41fa21178ff444546bcc2e36d885d092732e30516` |

I read the entire canonical note, both complete runtime programs, wrapper, all three unchanged parents and the four sealed PRE/POST arguments. I also read the qualification, publication build/verify writers, historical failed verifier, graph-manifest writer and runner-cache implementation as inert text. The complete seven presentation replacements were inspected. Part I is exactly the qualified46 body after its two recorded presentation replacements and heading adjustment; Part II is exactly the author47 body after its five recorded replacements and heading adjustment. Those bodies begin at canonical lines 78 and 279. The new introduction, frontmatter and concluding scope were read directly. Capturing other historical files establishes their identity and recovery path; it is not a claim that every captured historical program or large raw array was manually read.

The finite-model premises are supplied, not derived from repository axioms or nature. The relevant imported content is the finite physical matter/rotor space, full gated diagonal D, local magnetic pair form, original formation channels, finite trace-class process and number-sector rules. The new result does not need the infinite-volume conclusions discussed in the formation-balance parent or microscopic error transfer. Their historical provisional language does not supply extra authority here. Procedural source identities are captured; the installed physics-claim-reviewer entry matches the candidate's copy. No network refresh or claim of review against the moving latest main was made. No model or reasoning-effort change was requested or made.

The affected proof and scope checks are as follows.

- **Current and first derivative.** With links oriented A to B, the written current is minus the formal adjoint-generator image of E. Commuting a finite gated shift word with E multiplies it by its fixed integral shift; D commutes with E. This supplies the bounded current extension and the stated continuity signs without assuming an electric first moment. For bounded matter-charge functions, pairing the finite-graph mild equation removes the free D evolution and gives the scalar derivative. This does not differentiate an undefined electric expectation or claim operator-norm continuity of rotor conjugation.
- **Initial compression.** Summed Gauss law and minimum record number force all A plus and all B empty. Each original branch has charge increment `(sigma-1)e_a - sigma e_b + e_c` and field increment `sigma e_ab-e_ac`. At fixed recorded edge, different destinations and signs have orthogonal final matter words. The charge-function compression is therefore scalar on arbitrary normal incoming fields. It gives the weighted Dirichlet covariance slope with coefficient `4 kappa(d_a-1)`. The coherent edge sum is unnormalized; its initial diagonal statistics agree with resolved signs, without equating their recycling maps or later states. Connected covariance has the same first slope because initial relative-charge means vanish.
- **Zero-field qualification.** Canonical line 180 contains the exact POST46 replacement. Every physical electric basis vector has zero Hamiltonian-current expectation, including a nonzero circulation basis field, since the diagonal matrix element of the commutator with E is zero. Boundedness extends this to normal diagonal mixtures. Coherent fields can have nonzero circulation current. Zero field is sufficient, not necessary. The qualified copy differs from the original46 note by precisely this prose substitution; the original seal and text remain intact.
- **Finite-time proof.** The two weak-star Duhamel identities are valid after pairing with trace class. Joint continuity of the paired integrand follows from trace-class continuity, weak-star continuity and uniform boundedness. The first compressed term is the same scalar at every time because Pmin commutes with D. Applying C*, one electric halo, then C* gives `J(X)J(X2)||O||`; the triangle integration contributes `t^2/2`. The product-of-means term is retained. Complete positivity and contractivity concern the full propagator with every later birth and number sector, not a one-birth truncation.
- **Domain of the constants.** Canonical line 295 explicitly assumes a finite simple bipartite graph of degree at most six. The magnetic commutator bound `4 delta 6^4=5184 delta`, coherent/resolved star bound `600 kappa`, support counts and coarse volume-independent constants are valid there. Coherent output ranges are orthogonal on the full allowed tensor space. Locality is counted in the ambient matter/rotor tensor product and restricted to the invariant Gauss space. Strongly commuting D terms require only one electric enlargement. No degree-independent extension to unbounded-degree graphs is asserted.
- **Readout and PRE distinctions.** At canonical lines 63–69, PRE47's charge-diagonal observable is expressly a bounded function of matter charges, hence commuting with D; arbitrary field-off-diagonal operators are excluded. The root quotient is `Cov(a,b)/Var(b)`, whereas PRE47 uses Pearson normalization `Cov(a,b)/sqrt(Var(a)Var(b))`. Equal first limits do not make them equal at finite time. PRE47's formation-factor estimate remains separately attributed and restricted to `0 <= t < 1/[337(12130560 delta+93600 kappa)]` at degree six. Its colored-series proof discards exactly the zero pure-Hamiltonian expectations before bounding positive colored-word sums. The root's two-Duhamel estimate is valid for every finite time but can be uninformative; no numerical dominance between the two bounds is asserted.
- **Ratio and boundary cases.** The cubic first coefficients are `N_aa=N_bb=120 kappa`, `N_ab=-20 kappa`. The root ratio bound follows by writing `Cov+Var_b/6` and using the positive denominator `120 kappa-t M_bb`. Kappa zero gives no ratio law. Constant charge tests vanish, and degree-one A sites contribute no formations. A nonedge's zero initial coefficient does not imply permanent absence of correlation. The Fourier slope and cosine remainder use degree six and full-site normalization; the simple degree-three cube is not assigned those factors.
- **Tree and physical limitations.** PRE47's six-vertex tree has two A and four B sites, number sectors 2, 4 and 6, and a genuine second-birth diagnostic. The historical three-A/three-B six-site preparation has capacity for only one birth. The note distinguishes them explicitly at line 71. Neither is cubic time propagation. The note makes no measured-charge identification, preparation selection, detector derivation, physical time/length calibration, infinite-volume construction, volume-uniform Fourier remainder, joint microscopic short-time transfer, empirical agreement or TOE claim.

The new `compare_read_only.py` imports no author or previous checker code and executes no program. Its caller executes only this newly inspected comparator. It checks all 177,399 current-control and 249,500 finite-time-control non-timing scalar leaves, recursively including types and structure, against the stored publication execution. Only the explicitly named top-level elapsed fields are excluded. Both runtime files equal their sealed author files and attempt snapshots exactly. The successful publication run is retained evidence, not a new author run performed during this review.

The comparator additionally checks every one of the 8,480 current primitive rows, complete geometric coverage, Gauss increments, hard-core/color/number constraints, branch distinctions, currents, means and 180 covariance entries. Each local row agrees with the sealed PRE46 star data. The L4/L6 rows also agree with PRE47's primitive records and both complete initial covariance matrices; the plus-only mutation remains different. This is released-source data reconstruction with the target formulas already exposed, not a new blinded derivation.

All 18 local support tests on sides 4, 6, 8, 12, 16 and 20 were reconstructed through global common-B incidence. The comparison covers 14,916 serialized atom occurrences and 23,487 group occurrences, exact rational covariance polynomials and ratio windows. The side-12 versus side-16/20 magnetic-halo counts remain 1710 versus 1713 even though the halo size is 741. On sides 16/20 the displayed constants agree, and `t=5/12223805590224` gives exact error bound `1/60` with positive variance denominator at delta=kappa=1. This is a conservative model-time interval, not seconds or a breakdown-time estimate. All five compact current groups and all six compact support/bound groups were read. Large raw vectors and sets were checked mechanically, not all manually read.

The existing PRE47 tree data has 90 full physical words, 40 effective words and 24 finite-time rows. The smallest stored N=6 probability is `2.5592833328030667e-8`. The comparator checked this scope and the stored Pearson normalization; it did not rerun numerical evolution or renew a numerical propagator certification. The complete PRE/POST arguments and all their sealed-member hashes preserve the previous independent coverage. Seven seals bind 15 author46, 3 qualification, 31 PRE46, 32 POST46, 17 author47, 39 PRE47 and 42 POST47 member entries. Their exact seal hashes are in `COMPARISON02.stdout.json`.

The wrapper's declared inputs include both runtimes, the canonical note and all three parents. The cache input fingerprint was reconstructed from bytes and lengths without importing `runner_cache`; it is `3b9e82f6cbffbeea7c9d1f08bd5b065d974e5c33a7201679c0db6c077cc6471b`. The entire cache text, wrapper result, artifact hashes, empty stderr streams and successful execution receipt correspond exactly. The graph changes from 6,667 to 6,668 nodes and 14,678 to 14,681 edges. Every old node is unchanged; the single new node's dependency hash matches precisely the three named parent IDs. This is a manifest/source check, not an executed audit pipeline.

The historical `PREMATURE_GRAPH_DEPENDENCY_FAILURE.json` and failed verifier were preserved and read. The record reports dependent commands invoked before graph generation finished, followed by rejection of unchanged base topology. The saved failed-verifier hash matches. The writers' ordering is consistent with failure before their intended manifest/freeze writes. I did not repeat those historical commands or treat the failed attempt as successful evidence.

The two interrupted publication-check directories were captured as history, and neither was used as a completed review. While this recovery was underway, the parent reported that the original47 checker had returned and sealed its final comparison. Its new report and new seal were not opened before this report was sealed. This review's first comparator attempt stopped at its preservation gate: 57 already captured files inside that previously partial47 directory had changed mode from 0644 to 0444 and ctime. The complete failed source, streams and receipt are retained in `attempt01/`, and the exact changes are in `CONCURRENT_PARTIAL_REVIEW_CHANGES.json`. The comparator was narrowed to allow only those externally reported sealing metadata changes, while still requiring every captured byte, length, mtime and inode to match. All 332 captured originals retain their bytes; 275 retain their full checked byte/stat identity. No scientific source changed. This exception is disclosed rather than claimed as uninterrupted stat preservation.

The successful second comparator run began at `2026-09-25T11:06:24.508799+00:00`, took `2.5570055411662906` seconds, returned zero and had empty stderr. Its source SHA256 is `387d3c4bde61db0a6d791b4a23620d4a8757a4ee5ad339a993d85a9ebcfa1918`; its complete 44,247-byte stdout SHA256 is `1be9524b6ca3b0b4ada376c6ffd1bb48e7f65f4fd2e0c303a957cddd915508be`. `COMPARISON02.execution.json` binds the command, program and streams. `SOURCE_PINS.json`, snapshots and the final preservation record provide exact recovery paths.

No publication, old evidence, PR, checkpoint or editable prompt file was edited. No author program, historical writer, numerical propagator, pipeline, audit, merge, publication action, external message or subagent dispatch was performed. Only this new recovery directory was written. The remaining operational decision is the parent's reconciliation of the recovered report with original-reviewer evidence and whatever later integration checks are separately authorized. The physical preparation/readout/calibration obligations remain open. Stop at this report and its seal.
