# Review history

| Pass | Scope and identity | Result | Limits |
|---|---|---|---|
| Campaign-selection review | Ten workers compared next routes at the wall | Selected exact-side fixed-time electric scalar reduction | Selection only; did not review final authored content |
| Author mathematical check | Main source revision `c288aa9cfeea8fd2256fe4b71a60c401d64f7ce6`; upstream hashes pinned in notes and runners | Re-derived the (S^{-2}) weighted Jacobi/Duhamel estimate and path reflection | Same author session; not independent source review |
| Author endpoint-tail derivation | Current exact-side note and endpoint-barrier proof | Combined the arcsine limit of the prepared-state low-energy spectral mass with the high-energy cap barrier to obtain the uniform-in-phase endpoint-strip bound | Author derivation; limiting statement is analytic, finite runner scan is only corroboration |
| Dense finite identity check | Exact runner at current candidate source | Dense exponentials confirm echo, factorization, reflection; dense pinching confirms spectral diagonal split to 1.1e-17; endpoint diagnostic compares low spectral mass to the arcsine law | Floating-point finite-spin checks only |
| Canonical runner precompute | `scripts/precompute_audit_runners.py`, three runners, `--allow-non-main --push-mode none --force --concurrency 3` | All three succeeded before the latest exact-runner additions | Refresh against final candidate hashes |
| Independent final-source review | Author cold-read all four candidate notes and all four primary runners at base `0e6ad8285096ed668816f18caaa6fbbfbd9c50e8` | Author self-review complete; no independent reviewer | Do not claim independent review-loop PASS or formal audit |
| Formal audit | Not run | Deferred | Only the audit lane may write a verdict |
| Next-route selection, 2026-09-24 | Ten distinct route passes: seven isolated agent reviews plus three author exact checks after the platform agent-thread cap | Selected primitive five-site transfer and cross-fiber readout geometry | Route selection only; the seven worker reports did not review final authored files, and the author passes are not independent |
| Personal five-site theorem/runner check | Candidate sources at base `0e6ad8285096ed668816f18caaa6fbbfbd9c50e8`; paired deterministic runner and full note | Re-derived the signed five-site substitution, Bloch fiber action, four crossing-slope/gap formulas, lobe-action normalization, scalar (1/S) correction, and stationary Hessians; finite runner corroborates the displayed identities | Same author; runner verification is not independent review; compact-bulk and local-symbol scope only |
| Personal weighted lag/alias diagnostic | `outputs/postmark_moving_index_2026_09_24/weighted_alias_diagnostic.py`; exact-side finite Jacobi runner and the proposed profile scalar | For S=24,48,96 the direct cosine-character evolution and spectral double sum agree within (3.1\times10^{-15}); the positive-lag Abel upper bound is too broad at those sampled sizes | Float64/complex128 finite diagnostics; no interval enclosures, asymptotic theorem, or physical-readout discrepancy |
| Axiom-boundary check | `docs/MINIMAL_AXIOMS_2026-06-29.md` at `origin/main` `0e6ad8285096ed668816f18caaa6fbbfbd9c50e8` | The memo explicitly says Admissibility does not select a Hamiltonian and Record does not provide record-production dynamics | Confirms that this supplied-model calculation is conditional; it does not prove the model un-derivable and does not force an axiom update |
| Personal final-source read and Schur/Weyl discriminator | Four new theorem notes, four paired runners, and `outputs/postmark_moving_index_2026_09_24/attempt_logs/schur_weyl_two_energy_probe.py` | Cold-read the note proofs; fixed the exact-side runner so the echo check exponentiates the conjugated generator independently. Derived the exact anchor pencil and the two-energy character weight; finite reconstructions agree below `5e-14` for S=1,2,3,5 | Author-only; no independent source review. The Schur identity is valid away from eliminated-block poles, and finite algebra checks do not bound the selected-time phase sum |

The exact runner had earlier author-code failures preserved in the full attempt log; they were repaired before the latest successful run. They were not scientific counterexamples. The author cold-read all four current theorem notes and all four primary runners. The dense echo check exponentiates `V N V*` independently, with nine deliberate mutations detected; the five-site slope check samples `u=1/2`, with its three mutations detected. All four canonical caches and all current-source mutation receipts match. An isolated disposable copy was verified against the author candidate at base `0e6ad8285096ed668816f18caaa6fbbfbd9c50e8`: all 129 changed paths had matching bytes and modes. On that copy, full-pipeline pass 1 completed all 18 stages using `--stage-citation-manifest`; strict audit lint reported no errors, and changed-evidence checked four rows with zero failures or control failures. Its complete logs and hashes are preserved outside both worktrees under `/Users/jonreilly/Documents/Codex/research_runs/postmark_campaign_20260924/`. This pass predates the present checkpoint edits; the final frozen packaged-candidate pass is recorded as `combined_pipeline_pass_final.log`, `strict_audit_lint_pass_final.log`, and `changed_evidence_pass_final.log` in that same directory. No independent scientific review or formal audit is claimed.

## Review-loop conformance sections — author preflight

This is an author conformance pass, not an independent review-loop receipt or audit verdict. I checked the proposed delta section by section against `docs/ai_methodology/REVIEW_LOOP_PR_CONFORMANCE_SPEC.md` at `origin/main` revision `0e6ad8285096ed668816f18caaa6fbbfbd9c50e8`.

1. **Self-containment:** the four new theorem notes, four runners, and their declared inputs are either on this branch's reviewed delta or on the selected `origin/main`; the current-hash changed-evidence check found all four rows complete. No rejected-branch input is pinned.
2. **Cache and execution discipline:** all four new runners declare `AUDIT_TIMEOUT_SEC = 3600`; their canonical caches were force-refreshed from final runner/input bytes. Machine-emitted caches were not manually edited.
3. **Claim-scope honesty:** the notes state finite-family/conditional support, identify the supplied dynamics and output map, and leave the interior fixed-time phase sum open. No runner headline claims a global propagation or readout limit.
4. **Negative-claim gate:** N1-N8 is not applicable. The source notes make bounded positive support claims and do not assert a no-go, route foreclosure, or bounded result with named walls. Finite alias measurements are reported as samples, not a no-go.
5. **Proof obligations:** the theorem notes give their exact bounded targets, hypotheses, proved and open dependencies, boundary/degenerate scope, and strongest missing step. None frames a target-equivalent terminal obligation as proof-complete.
6. **Runner validity:** current-source mutation checks are recorded in `outputs/postmark_moving_index_2026_09_24/attempt_logs/`; independent author checks include manual derivation, symbolic algebra, exact finite identities, and dense-matrix recomputation. These are author checks, not independent science review.
7. **Packet completeness:** no helper runner is declared; each note points to its primary runner and current receipt/cache. Changed-evidence preflight reports four rows checked with no failures or control failures.
8. **Links and generated artifacts:** the candidate adds theorem-note graph nodes. The citation manifest was regenerated by the pipeline; the stage-18 node/edge delta was inspected and intentionally staged. No audit ledger, queue, prompt, or effective-status output is staged.
9. **Note structure:** all four theorem machine-status blocks use `conditional-support` / `bounded_theorem` with explicit import and trace fields. The loop `TRACE_GATE.md` YAML was corrected to keep `next_trace_action` at the top level.
10. **Propose/ratify boundary:** no author audit verdict, effective-status edit, auditor rationale, or regenerated audit authority surface is included. The citation manifest is the only allowed generated artifact.
11. **Sourced facts and counts:** changed science statements were cold-read in their complete source notes; the package uses repository source text for claim descriptions and current diff data for the four-note/four-runner count. The PR body will avoid unverified aggregate counts.
12. **Combined candidate gates:** the exact frozen candidate was verified as 129 byte/mode-identical paths against the author index at base `0e6ad8285096ed668816f18caaa6fbbfbd9c50e8`. The isolated copy passed all 18 pipeline stages with `--stage-citation-manifest`; stage 18 accepted the reviewed node/edge delta. Strict audit lint ended `OK: no errors`, and changed-audit evidence reported `checked=4 failures=0 control_failures=0`. Final complete logs are under `/Users/jonreilly/Documents/Codex/research_runs/postmark_campaign_20260924/` as `combined_pipeline_pr_candidate_final.log`, `strict_audit_lint_pr_candidate_final.log`, and `changed_evidence_pr_candidate_final.log`. This is author validation only; no independent science review or formal audit is claimed.

No section is marked as independently passed. Formal audit remains pending.
