# Read, computation and failure log

All four permitted main notes were read completely, in bounded outputs, and compared byte-for-byte with their Git objects at 60c5f194d940a7bbaf1cdd545296e31d74a02f1a. Their snapshots and full hashes are in SOURCE_PINS.json. The expressly allowed root36 common-law note was read completely; its author seal was read only to bind that declared dependency. None of the other files listed in that seal was opened. The new root37 packet and every other active checker/research packet and campaign checkpoint remained unread.

The current AGENTS pointer, science workflow, reviewer skill, freshness reference, proof-search-governance reference and cached standing instruction ref were checked against the unchanged identities whose complete instruction reads were already completed in the preceding task. Their snapshots are included. The standing ref is eb1f1ca8338848cf2046582e13aef372d8540937. No fetch or outside-directory write was used. The explicit inherited-model, unchanged-effort and no-delegation brief takes precedence over generic landing-review defaults. No retained/audit workflow was invoked.

The reconstruction was organized around five separate obligations: Hermitian rotated energy coercivity; the exact finite-spin fourth coefficient; form and formation-loss comparison on a D-bounded family; mixed high/low coherence control; and spectral-infimum transfer without compactness. Root36 is a provisional input to the final energy/activity corollary. Prior completed root35 knowledge is historical context, not fresh scientific independence.

primitive_attempt01 failed before any scientific result: the new script unpacked a two-component edge tuple as three variables. The full source, empty stdout, 719-byte traceback and true receipt remain unchanged. PRIMITIVE_ATTEMPT_REPAIR.diff records the single-line enumeration repair. Attempt02 succeeded and all 45 rows plus the complete remaining scalar/flux payload were read. PRIMITIVE_REVIEW.tsv preserves the full compact row display.

Attempt03 adds six nonzero-D or circulation columns to test both sides of the finite-spin anticommutator more directly. Its complete source, result/stdout, empty stderr and true receipt are preserved, as is PRIMITIVE_NONZERO_D_EXTENSION.diff. All 45 earlier rows and the scalar/flux payload are unchanged. The six new rows and changed graph counts were read completely; PRIMITIVE_FINAL_REVIEW.tsv contains all 51 final rows. The final 13,035 primitive Gauss checks are exact at spin one. The seven scalar groups contain 556 integer checks. The eight large-flux rows evaluate the stated analytic fractional/square-root coefficient; they are not an independent large-spin many-body simulation.

The separate microscopic square control succeeded on its first execution. All five spin rows and every one of the 20 mixed/coherent rows, counterexample rows, source/timer fields and exact-zero diagnoses were read from the complete 16,137-byte JSON output. The numerical negative rotated high weight near -5.33e-15 is preserved as roundoff around an analytically zero population, not clipped or interpreted as a negative probability.

The first attempt to write the PRE through functions.exec failed at JavaScript parsing with “SyntaxError: missing ) after argument list” because unescaped Markdown backticks closed a raw template string. No tool operation or file write occurred in that attempt. The PRE was then written without those backticks and fully read in two bounded outputs. This was a report-delivery failure, not a scientific calculation failure.

The insufficient routes are preserved in APPROACH_REGISTRY.md and PRE section 8: density convergence does not imply energy convergence; actual bounded energy does not supply electric tightness; magnetic operator convergence on D-bounded inputs can fail; and bare P preparation does not imply bounded microscopic energy. The successful proof uses one-sided energy forms and explicit high-band/coherence estimates instead.

verify_pre.py is newly written and genuinely read-only: it reads/hashes/parses evidence and runs only exact git-show reads of explicitly pinned source objects, then prints JSON. It does not write any file or import/execute any scientific control. Its outer recorder writes only new verification output files within this assigned directory. All scientific attempts, including the failed one, remain intact. No source/publication/audit state was edited and no agent was delegated.
