# Independent scientific comparison and execution record

The separate checker sealed PRE before receiving the new root derivation or
Laurent certificates. It reconstructed the generic dissipative bound and named
the missing global singular-value obligation. POST then used a different
primitive construction, from single-hop sector matrices and their Gram
difference, and verified all 120 rational identities and all 32 ranks exactly.
Each rank has both a nonzero integer minor and exact kernel witnesses. Four
altered inputs were rejected. The checker used the inherited model/effort and
did not delegate, import a root builder, or repeat modular discovery.

The complete publication note and primary runner were read. The entire
regenerated witness, primitive metadata and result were compared with the
independently checked algebra; the complete execution envelope was inspected.
POST.md states the evidence boundary and finds no consequential mathematical
defect under the declared imports. This is not a formal audit or retained grade.

The copied reports, scripts and data are unchanged historical evidence. Their
seals retain original source paths and hashes; these are provenance, not a
claim that every old frozen-input path is included in this publication checkout.
The original complete checker directory, including frozen source snapshots,
remains at /Users/jonreilly/Documents/Codex/physics-sync-2026-09-24-fifth/rotor-upper-tail-independent.
All PRE and POST seal entries were reverified before copying this packet.

The self-contained primary runner is the portable reproduction route. It
regenerates the full rational witness from primitive cube hops and checks every
coefficient over the rationals. Its final source-bound execution passed in
49.273 seconds with a declared 900-second timeout. The four primary PASS
families are finite certificates, ranks/coefficient bounds and mutation
controls; the written analytic proof supplies the infinite-time theorem.

The regenerated witness is about 22 MB and is not a versioned runtime input.
Its hash and byte count are bound in the compact result and cache, and the
runner writes it to the documented output path. The exact generated bytes
are also preserved outside the publication tree as SECOND_PUBLICATION_FULL_WITNESS.json
in the fifth campaign evidence directory. The independent full comparison
confirms its coefficient list and shifts match the separately checked witness.

The root cold-reviewed the complete final argument, primary runner and
independent verifier/comparison scripts, and inspected their complete logs and
result bindings. Source refresh, vocabulary, compilation, explicit file
allowlist, citation-manifest delta and exact-tree receipt are separate
mechanical checks. The combined pipeline, strict audit lint, changed-evidence
landing gate and independent retained audit remain pending. Nothing is merged.
