"""Distinct TOE walls (T-ids) as clusters of lane walls. Supervisor (Opus 5.5) dedupe, 2026-09-29."""
C = [
("T01","The formation law is not fixed: no order, rate, unit, or where/when records form",["L01-W1","L01-W2","L02-W1"]),
("T02","The axioms contain no dynamics or action, and nothing selects one",["L02-W2","L02-W4","L03-W10"]),
("T03","What a record is: a sharp birth costs bond energy, and a unitary Born wave cannot raise the record count",["L02-W3","L03-W5","L03-W6","L01-W3","L01-W4","L04-W9"]),
("T04","Record identity: which record is which, and field flips versus permanence",["L01-W10","L06-W13"]),
("T05","The statistical bridge (Born-type odds, odds to frequencies) is not derivable and is parked",["L03-W1","L02-W6","L01-W14","L03-W9"]),
("T06","Born trace-form conditions and the typed action-to-odds interface",["L03-W2","L03-W3","L02-W5"]),
("T07","Quantum equilibrium: why records start distributed as |psi|^2",["L03-W8"]),
("T08","Records plus local odds cannot carry quantum (Bell) correlations",["L03-W4","L01-W7"]),
("T09","No propagation from records, odds or one-qubit ticks (waves need signed weights; no cone)",["L01-W8","L02-W8","L04-W3","L02-W9"]),
("T10","Pointer basis and redundant local observability are not derived",["L03-W7","L01-W5"]),
("T11","No bridge from records or ticks to a clock with a rate",["L04-W1","L01-W11"]),
("T12","Z^3 read as spacetime gives a 2D-skewed law or an excluded 3+1",["L04-W2"]),
("T13","Dimension and signature counts are declared (one time, odd time, three space)",["L04-W4","L04-W5","L04-W11"]),
("T14","One speed for every field is a premise and is not protected under interactions",["L04-W6","L04-W7","L06-W11","L14-W16"]),
("T15","The Euclidean tick that protects the cone is not the real-time step (and sets the exponent 16)",["L04-W8","L07-W4"]),
("T16","The arrow of time needs a low-record past",["L01-W6","L04-W10","L13-W5"]),
("T17","One record per site breaks the exact energy-momentum books of interacting matter",["L01-W9","L02-W11","L14-W13"]),
("T18","The exchange sign: nothing forces fermions over hard-core bosons",["L05-W1","L02-W13","L05-W11","L05-W12"]),
("T19","A local fermion on one qubit per site: the string / extra-qubit trilemma",["L05-W2","L05-W3","L03-W11"]),
("T20","Spin-1/2 and the Dirac law are supplied",["L05-W4","L05-W5"]),
("T21","Rest energy (mass) has no source in the rules",["L05-W6","L02-W12"]),
("T22","Chirality: every free local walker has a mirror twin; the chiral weak SU(2) is added",["L05-W7","L06-W15"]),
("T23","The orientation (handedness) bit is not fixed",["L05-W8","L08-W5","L11-W2"]),
("T24","Doublers: eight or sixteen copies with no rule to keep or remove them",["L05-W9"]),
("T25","Matter content and species labels (SM table, taste cube, dark sector host) are supplied",["L05-W10","L08-W3","L09-W1","L10-W8","L12-W1"]),
("T26","The gauge group and the colour carrier are not selected from the carrier",["L06-W1","L06-W2"]),
("T27","Non-abelian gauge links have no account in one-qubit-per-site records",["L06-W3"]),
("T28","The gauge action and g_bare = 1 (beta = 6) are supplied",["L06-W4","L16-W3"]),
("T29","The plaquette value and the vertex power are declared inputs",["L06-W6","L16-W4","L07-W6"]),
("T30","No controlled bridge from the Planck lattice to physical scales (transmutation, 17 decades)",["L06-W7","L16-W2","L07-W7","L06-W16"]),
("T31","The hierarchy formula: where alpha_LM^16 comes from, what v is, and its trial factors",["L07-W3","L07-W5","L07-W12"]),
("T32","Confinement and the mass gap of the physical SU(3) theory are not derived",["L06-W8"]),
("T33","Weak and hypercharge couplings, alpha_em and the unit charge are not derived",["L06-W5","L16-W5","L06-W14"]),
("T34","The Higgs doublet, electroweak breaking and the Higgs mass are supplied",["L07-W1","L07-W2","L07-W10"]),
("T35","The top Yukawa and the absolute mass anchor are uncontrolled",["L07-W8","L09-W8","L07-W9"]),
("T36","No rule differentiates generations; Yukawa hierarchy free; running cannot make ratios",["L09-W2","L07-W11","L16-W6"]),
("T37","Sector dial spread (r = 1/2 leptons vs quarks) and the mass scheme",["L08-W6","L09-W9","L08-W7"]),
("T38","Koide r = 1/2: count the paired mode once or twice (occupancy grain)",["L08-W1","L11-W6"]),
("T39","Brannen phase delta = 2/9: from an exact fraction to an angle in radians",["L08-W2"]),
("T40","The absolute charged-lepton scale is a free number",["L08-W4"]),
("T41","Cross-sector quark determinant readout (theta mass side) is an open obligation",["L08-W8","L09-W11","L11-W5","L11-W7"]),
("T42","Strong CP gauge side: the theta-free gauge weight is imported; no topological charge",["L11-W1","L11-W3"]),
("T43","Strong CP mass side on a supplied surface, and no link between the two halves of theta-bar",["L11-W4","L11-W8"]),
("T44","The CKM atlas's building blocks are supplied identifications",["L09-W3","L09-W12"]),
("T45","The quark CP phase: why arctan sqrt5",["L09-W4"]),
("T46","Down-quark route: the 5/6 exponent and the scale choice",["L09-W5"]),
("T47","Up-quark route and the Route-2 E-center readout",["L09-W6","L09-W7"]),
("T48","Two flavour mechanisms (circulant leptons, tensor/Schur quarks) do not meet",["L09-W10"]),
("T49","Neutrinos: Dirac or Majorana, and the absolute mass scale",["L10-W1","L10-W2"]),
("T50","The atmospheric-gap success stands on posited bridges",["L10-W3"]),
("T51","The neutrino mass pattern beyond the atmospheric gap is wrong or absent",["L10-W4"]),
("T52","PMNS mixing angles are set by data; three mixing routes are incompatible",["L10-W5","L10-W7"]),
("T53","PMNS CP phase and octant forecast rests on a one-bit sheet choice",["L10-W6"]),
("T54","The dark-matter candidate has incompatible charges and identities",["L12-W2"]),
("T55","The dark mass 16 v was found by scanning against the target",["L12-W3"]),
("T56","The dark annihilation coupling is chosen, not derived",["L12-W4"]),
("T57","R = R_base x S is a group-theory identity presented as the dark-to-baryon ratio",["L12-W5"]),
("T58","The baryon asymmetry is imported; leptogenesis and its CP sign are not derived",["L12-W6","L13-W7","L13-W8"]),
("T59","Cosmic history (expansion, thermal state, abundances) is supplied",["L12-W7","L13-W4","L13-W6"]),
("T60","Vacuum energy and the zero of energy",["L13-W1","L14-W18"]),
("T61","A fixed regular lattice brings Planck-size shape and mass-type terms that must be tuned",["L16-W8","L14-W15"]),
("T62","The size of the cosmos (R_Lambda/a, H_0) is put in by hand; S^3 versus flat",["L13-W2","L13-W3"]),
("T63","Inflation and the primordial spectrum are asserted",["L13-W9"]),
("T64","No finite-site graviton with Einstein's spectrum (the gravity wall; exercised 2026-09-29)",["L14-W1","L14-W2","L14-W3","L14-W5"]),
("T65","The owner-level gravity exits that keep finite sites have no bounded test",["L14-W4"]),
("T66","Nonlinear closure of gravity's constraint algebra on the fixed lattice",["L14-W6"]),
("T67","The geometric carrier is supplied; no Record-to-geometry map; Einstein's action not derived",["L14-W7","L14-W8","L14-W17"]),
("T68","The curvature member (light bending x2) is declared, not forced",["L14-W9"]),
("T69","The source/action bridge: what sources gravity and with what readout",["L14-W10","L02-W7"]),
("T70","Newton's constant in lattice units and a = l_P are not derived",["L14-W11","L16-W1","L15-W5"]),
("T71","That gravity attracts (the coupling sign) is not derived",["L14-W12"]),
("T72","Universality of free fall holds only under a list of conditions",["L14-W14"]),
("T73","The axioms define no entropy; five candidates disagree",["L15-W2"]),
("T74","The black-hole 1/4 is a supplied count (BP); entanglement gives 1/6 without a selector",["L15-W1","L15-W3","L15-W4"]),
("T75","No lattice horizon and no lattice Hawking radiation",["L15-W6","L15-W7"]),
("T76","The frozen-box black hole: no formation rule, volume not area, clause C1, no holography",["L15-W8","L01-W13","L14-W19","L15-W9"]),
("T77","Balance-law (Gauss/ice) patterns are not outputs of local formation and break covariance",["L01-W12","L06-W12","L02-W10"]),
("T78","The photon's light-speed dispersion in the qubit-link model is not established",["L06-W9"]),
("T79","The Maxwell dynamics class is supplied",["L06-W10"]),
("T80","Record dynamics keeps adding free dimensionless constants",["L16-W7","L01-W15"]),
("T81","Ordered-phase thresholds are proved far from where they are observed",["L02-W14"]),
]
