"""Kill-check K1 for T34 (Claude Sonnet 5.5).
Question: is the attack's dichotomy 'the staggered su(2) either flips L/R or is vector-like' exhaustive on the
repo's 4D C^16?  Test the third candidate: the self-dual part of Spin(4) = Cl^even(4), built from the SAME gamma
matrices as frontier_right_handed_sector.py PART 4.  Prediction (before running): it closes su(2), commutes with
gamma_5, has Casimir 3/4 on C^8_L and 0 on C^8_R  (i.e. IS a chiral su(2) with weak-neutral R), but is a
spacetime (spin) generator, not an internal one."""
import numpy as np
I2=np.eye(2,dtype=complex); sx=np.array([[0,1],[1,0]],dtype=complex); sz=np.diag([1,-1]).astype(complex)
def k4(a,b,c,d): return np.kron(a,np.kron(b,np.kron(c,d)))
G=[k4(sz,sz,sz,sx),k4(sx,I2,I2,I2),k4(sz,sx,I2,I2),k4(sz,sz,sx,I2)]
G5=G[0]@G[1]@G[2]@G[3]; I=np.eye(16)
PL,PR=(I+G5)/2,(I-G5)/2
S=lambda m,n: 0.25j*(G[m]@G[n]-G[n]@G[m])   # Sigma_{mn} = (i/4)[G_m,G_n], Hermitian
eps=lambda i,j,k: int(np.sign((j-i)*(k-i)*(k-j)))
res={}
for sgn,name in ((+1,'A'),(-1,'B')):
    J=[]
    for k in (1,2,3):
        i,j=[a for a in (1,2,3) if a!=k]
        # J_k = 1/2 ( eps_kij Sigma_ij*(1/1) + sgn * Sigma_0k * i-phase ) ; fix phase numerically below
        Jk = 0.5*(0.5*sum(eps(k,a,b)*S(a,b) for a in (1,2,3) for b in (1,2,3)) + sgn*S(0,k))
        J.append(Jk)
    # normalise so that [J1,J2]=iJ3 up to scale, test closure
    c12=J[0]@J[1]-J[1]@J[0]
    ok_alg = np.allclose(c12,1j*J[2]) or np.allclose(c12,-1j*J[2])
    Cas=sum(j@j for j in J)
    wL=np.linalg.eigvalsh((PL@Cas@PL)[np.abs(np.diag(PL))>0.5][:, np.abs(np.diag(PL))>0.5]) if False else None
    # spectra on chiral subspaces
    def spec(P):
        w,v=np.linalg.eig(P@Cas@P); return np.unique(np.round(w[np.abs(np.diag(P))>-1].real,6))
    print(f"self-dual candidate {name}: closes su(2) (|[J1,J2]|=|J3|): {ok_alg}; hermitian: {all(np.allclose(j,j.conj().T) for j in J)}")
    print("   [J_k,gamma5]=0 for all k:",all(np.allclose(j@G5,G5@j) for j in J))
    print("   ||J_k P_R||:",[round(float(np.linalg.norm(j@PR)),6) for j in J]," ||J_k P_L||:",[round(float(np.linalg.norm(j@PL)),6) for j in J])
    print("   Casimir eigenvalues on C^16:",np.unique(np.round(np.linalg.eigvalsh((Cas+Cas.conj().T)/2),6)))
    print("   Casimir trace on L, R:",round(float(np.trace(PL@Cas).real),4),round(float(np.trace(PR@Cas).real),4),
          " (L: 8 states, R: 8 states; spin-1/2 on all L would give 6.0 and 0)")
    # commutes with taste commutant?
    M=np.vstack([np.kron(g,np.eye(16))-np.kron(np.eye(16),g.T) for g in G])
    u,s,vh=np.linalg.svd(M); null=vh[np.sum(s>1e-8):].conj().T
    tastes=[null[:,i].reshape(16,16) for i in range(null.shape[1])]
    print("   commutes with all 16 taste operators:",all(np.linalg.norm(j@t-t@j)<1e-8 for j in J for t in tastes))
    print("   is it in the algebra generated by the KS T_k of the attack?  (odd/even check) [J,G_mu] nonzero:",
          any(np.linalg.norm(j@g-g@j)>1e-8 for j in J for g in G))
