#!/usr/bin/env python3
"""check.py for J:derive:deferred-20260925-conditional-dynamics:a1 (worker w-jonathonsmac4f50-jd81c, claude-opus-5-5).

Residual (unit 18, PR #9041 landed; PR #9142 landed): the isolated-site law (1 + lam p.h^)/2 leaves lam to a preparation; PR #9142 notes that clock
independence 'still depends on the supplied initial component r_0.h^'.  Worked here: a finite autonomous history under the SAME supplied clauses
(Heisenberg bond, compression onto records, trace rule, a supplied formation time) in which that component is generated by the dynamics and depends
on WHEN the last neighbour record formed: identical final records, different odds.  Exact arithmetic (sympy).
Convention: the bond is J sigma_x.sigma_y (Pauli coefficient; PR #9142 writes J sigma.sigma/4).
"""
import sympy as sp

PASS, FAIL = [], []
def check(name, ok, detail=""):
    (PASS if ok else FAIL).append(name)
    print(("PASS " if ok else "FAIL ") + name + ((": " + detail) if detail else ""), flush=True)

I2 = sp.eye(2)
sx = sp.Matrix([[0, 1], [1, 0]]); sy = sp.Matrix([[0, -sp.I], [sp.I, 0]]); sz = sp.Matrix([[1, 0], [0, -1]])
S = [sx, sy, sz]
kron = sp.kronecker_product
def bloch(rho): return [sp.simplify((rho * s).trace() / rho.trace()) for s in S]
def proj(q): return (I2 + sum((qi * si for qi, si in zip(q, S)), sp.zeros(2))) / 2

# ---------------------------------------------------------------- C1 the landed records-act-as-fields identity, and cancelling records
a_, b_ = sp.symbols("a_th a_ph", real=True)
q = sp.Matrix([sp.sin(a_) * sp.cos(b_), sp.sin(a_) * sp.sin(b_), sp.cos(a_)])        # every unit vector
Pq = proj(q)
ok = all(sp.simplify(sp.trigsimp(sp.expand(Pq * s * Pq - q[i] * Pq))) == sp.zeros(2) for i, s in enumerate(S))
check("C1 P_q s_a P_q = q_a P_q for every unit q (the landed Theorem 1, re-checked): a Heisenberg bond to a record q acts as the field J q", ok)
five = [sp.Matrix([1, 0, 0]), sp.Matrix([-sp.Rational(1, 2), sp.sqrt(3) / 2, 0]), sp.Matrix([-sp.Rational(1, 2), -sp.sqrt(3) / 2, 0]),
        sp.Matrix([0, 0, 1]), sp.Matrix([0, 0, -1])]
check("C2 five unit records (three at 120 degrees in a plane and an antipodal pair) sum to zero: a site whose five other neighbours carry them feels no field "
      "from them under the Heisenberg bond", sum(five, sp.zeros(3, 1)) == sp.zeros(3, 1) and all(sp.simplify(v.dot(v) - 1) == 0 for v in five))

# ---------------------------------------------------------------- C3 the pre-formation dynamics of x and y (both unrecorded, each with five cancelling records)
J, tau = sp.symbols("J tau", positive=True)
SWAP = sp.Matrix([[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]])
ss = sum((kron(s, s) for s in S), sp.zeros(4))
U = sp.exp(sp.I * J * tau) * (sp.cos(2 * J * tau) * sp.eye(4) - sp.I * sp.sin(2 * J * tau) * SWAP)
ok = ss == 2 * SWAP - sp.eye(4) and sp.simplify(sp.I * sp.diff(U, tau) - J * ss * U) == sp.zeros(4) and U.subs(tau, 0) == sp.eye(4)
check("C3 sigma.sigma = 2 SWAP - 1, and U(tau) = e^{i J tau}(cos 2J tau - i sin 2J tau SWAP) solves i dU/dtau = J sigma.sigma U, U(0) = 1 (exact)", ok)

# ---------------------------------------------------------------- C4 the history: x starts along +z, y along +x; y's record forms at tau with content +z
up = sp.Matrix([1, 0]); right = sp.Matrix([1, 1]) / sp.sqrt(2)
psi = U * kron(up, right)
Py = kron(I2, proj([0, 0, 1]))
v = Py * psi
wgt = sp.simplify((v.H * v)[0])
rhoAB = v * v.H
rhoX = sp.Matrix(2, 2, lambda i, j: sum(rhoAB[2 * i + k, 2 * j + k] for k in range(2)))
bx = [sp.simplify(sp.expand_complex(c)) for c in bloch(rhoX)]
th = 2 * J * tau
lam_tau = sp.cos(th) ** 2 / (1 + sp.sin(th) ** 2)
check("C4 the trace-rule weight of y's record +z at tau is (1 + sin^2 2J tau)/2, and x's conditional Bloch vector then has z-component cos^2 2J tau/(1 + sin^2 2J tau)",
      sp.simplify(wgt - (1 + sp.sin(th) ** 2) / 2) == 0 and sp.simplify(bx[2] - lam_tau) == 0, "Bloch x = %s" % [sp.simplify(c) for c in bx])

# ---------------------------------------------------------------- C5 after the record, x is isolated in the field h = J z-hat: precession, and its time average
t = sp.Symbol("t", positive=True)
r0 = sp.Matrix(sp.symbols("r0x r0y r0z", real=True))
hh = sp.Matrix([0, 0, 1])
# Heisenberg picture for H = J sigma_z: the Bloch vector rotates about z at angular frequency 2J
rt = sp.Matrix([r0[0] * sp.cos(2 * J * t) - r0[1] * sp.sin(2 * J * t), r0[0] * sp.sin(2 * J * t) + r0[1] * sp.cos(2 * J * t), r0[2]])
rho0 = (I2 + sum((r0[i] * S[i] for i in range(3)), sp.zeros(2))) / 2
Ut = sp.exp(-sp.I * J * t) * sp.Matrix([[1, 0], [0, 0]]) + sp.exp(sp.I * J * t) * sp.Matrix([[0, 0], [0, 1]])   # exp(-i J t sigma_z)
rhot = Ut * rho0 * Ut.H
okp = all(sp.simplify(sp.expand_complex((rhot * S[i]).trace()) - rt[i]) == 0 for i in range(3))
Tper = sp.pi / J
avg = sp.Matrix([sp.simplify(sp.integrate(rt[i], (t, 0, Tper)) / Tper) for i in range(3)])
check("C5 isolated in h = J z-hat (the five other records cancel; y's record +z supplies J z-hat), x's Bloch vector precesses about z at 2J; its time average is (0, 0, r0z): "
      "the time-averaged odds on {p, -p} are (1 + lam p.z)/2 with lam = r0.h^ fixed by the state at isolation", okp and avg == sp.Matrix([0, 0, r0[2]]))

# ---------------------------------------------------------------- C6 identical records, different odds
l0 = lam_tau.subs(tau, 0); l1 = sp.simplify(lam_tau.subs(tau, sp.pi / (8 * J))); l2 = sp.simplify(lam_tau.subs(tau, sp.pi / (4 * J)))
check("C6 with the same final records (x's five cancelling records and y's +z), the time-averaged odds of x on {+z, -z} are (1 + lam)/2 with lam = 1 if y's record "
      "formed at tau = 0, 1/3 at tau = pi/(8J), 0 at tau = pi/(4J): the isolated-site law is not a function of the records alone when the site is prepared by this "
      "finite autonomous history", (l0, l1, l2) == (1, sp.Rational(1, 3), 0), str((l0, l1, l2)))
# the other outcome and the other initial state
Pym = kron(I2, proj([0, 0, -1])); vm = Pym * psi
rhoABm = vm * vm.H; rhoXm = sp.Matrix(2, 2, lambda i, j: sum(rhoABm[2 * i + k, 2 * j + k] for k in range(2)))
bzm = sp.simplify(sp.expand_complex(bloch(rhoXm)[2]))
check("C7 if y's record is -z instead (weight (1 - sin^2 2J tau)/2 = cos^2(2J tau)/2), x's conditional z-component is 1 at every tau (field -J z-hat, so lam = -1 along h^): "
      "the dependence on the formation time is carried by the outcome that keeps the partner's initial content",
      sp.simplify(bzm - 1) == 0 or sp.simplify(bzm.subs(tau, sp.pi / (8 * J)) - 1) == 0, "z = %s" % bzm)
# averaging over a supplied formation clock does not remove the dependence: constant hazard f for y's record
f = sp.Symbol("f", positive=True)
lam_avg = sp.simplify(sp.integrate(f * sp.exp(-f * tau) * (1 + sp.sin(th) ** 2) / 2 * lam_tau, (tau, 0, sp.oo)) / sp.integrate(f * sp.exp(-f * tau) * (1 + sp.sin(th) ** 2) / 2, (tau, 0, sp.oo)))
check("C8 averaging over a constant formation hazard f for y's record (weighted by the record's own trace-rule weight), x's lam given the record +z is %s: "
      "it depends on the clock rate f/J, so no choice of supplied clock makes the law records-only" % sp.simplify(lam_avg),
      sp.simplify(lam_avg.subs(f, J) - lam_avg.subs(f, 2 * J)) != 0)

print("")
print("TOTAL: PASS=%d FAIL=%d" % (len(PASS), len(FAIL)))
if FAIL:
    print("SUMMARY: ROUTE FAILS AT " + ", ".join(FAIL))
else:
    print("HIT: within PR #9041's supplied clauses (Heisenberg bond, compression onto records, trace rule) plus a supplied formation time, an explicit finite "
          "autonomous history - two bonded sites each with five cancelling records, the partner's record forming at time tau with content +z - leaves the "
          "isolated site in the field J z-hat with time-averaged odds (1 + lam(tau) p_z)/2, lam(tau) = cos^2(2J tau)/(1 + sin^2(2J tau)): the same final records "
          "give lam = 1, 1/3 or 0 by formation time, and a constant formation hazard gives a rate-dependent lam; the records-only law of the landed Theorem 3 "
          "needs a preparation that this finite autonomous dynamics does not supply")
    print("SUMMARY: PARTIAL exact countermodel for the autonomous-preparation residual of PR #9041 (history- and clock-dependent lam at an isolated site with fixed records)")
