#!/usr/bin/env python3
"""Reproduce the independently written controls, save receipts, seal PRE.
No autonomous-clock author source is accessed. Every output remains here.
"""
from pathlib import Path
import datetime,hashlib,json,os,platform,subprocess,sys,time
import numpy,scipy,sympy
HERE=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
bind=json.loads((HERE/'SOURCE_BINDINGS.json').read_text())
for row in bind['sources']:
 p=HERE/row['snapshot_path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes'],row['snapshot_path']
receipts=[]
for name,result_name in [('exact_clock_control','EXACT_CLOCK_RESULTS.json'),('finite_clock_dynamics_control','FINITE_CLOCK_DYNAMICS_RESULTS.json'),('clock_uniformity_control','CLOCK_UNIFORMITY_RESULTS.json')]:
 script=HERE/(name+'.py');out=HERE/(name+'.stdout');err=HERE/(name+'.stderr');start=time.monotonic()
 with out.open('wb') as stdout,err.open('wb') as stderr:
  run=subprocess.run([sys.executable,str(script)],cwd=HERE,env={**os.environ,'PYTHONDONTWRITEBYTECODE':'1'},stdout=stdout,stderr=stderr)
 row={'script':script.name,'script_sha256':sha(script),'exit_code':run.returncode,'wall_seconds':time.monotonic()-start,'stdout':out.name,'stdout_sha256':sha(out),'stderr':err.name,'stderr_sha256':sha(err),'result':result_name}
 receipts.append(row)
 assert run.returncode==0,row
 assert err.read_bytes()==b'',row
 row['result_sha256']=sha(HERE/result_name)
receipt={'stage':'author-blind independent clock PRE','completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'python':platform.python_version(),'python_executable':sys.executable,'libraries':{'numpy':numpy.__version__,'scipy':scipy.__version__,'sympy':sympy.__version__},'source_bindings_sha256':sha(HERE/'SOURCE_BINDINGS.json'),'source_files_authenticated':len(bind['sources']),'runs':receipts,'scope':'Three new independent implementations; no campaign builders imported. The full-instrument finite-battery/collision source is an admitted premise.','unresolved_execution_failures':[],'retained_mathematical_failed_routes':['Equal collision durations on the nonlinear spin clock retain nonzero interior-time error','Omitting the free-evolution counterphase retains an extra endpoint free rotation','Endpoint-only transfer does not prove uniform physical-time convergence','Uniform one-time channel convergence does not transfer derivatives or multitime intervention processes']}
(HERE/'EXECUTION_RECEIPT.json').write_text(json.dumps(receipt,indent=2)+'\n')
(HERE/'WORKING_STATUS.md').write_text('''# Current checkpoint for this owned independent task

Stage: author-blind PRE complete. The argument, three full controls and
execution receipt are sealed by PRE_SEAL.json. Authenticate its file inventory
before reuse. Do not edit PRE-bound bytes after sealing.

Result: a finite positive spin clock with an inverse collision grid and an
explicit physical free-evolution counterphase gives a finite-horizon uniform
diamond-norm channel approximation while conserving system plus battery free
energy exactly. All clock, coherent preparation, flag and interaction resources
are stated. The supplied full-instrument packet remains a mathematical premise.

Failed routes and limits are retained in PRE_RECONSTRUCTION.md and
DEVELOPMENT_RECORD.md. Author comparison is unperformed and is the only next
scientific step, after the parent releases frozen clock-author paths. No broader
frontier work, git mutation, publication edit, audit verdict or axiom adoption.
''')
files=[]
for p in sorted(HERE.rglob('*')):
 if p.is_file() and p.name not in ('PRE_SEAL.json','PRE_SEAL.sha256'):
  assert '__pycache__' not in p.parts,'Unexpected generated bytecode'
  files.append({'path':p.relative_to(HERE).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)})
seal={'stage':'PRE independent finite autonomous clock reconstruction','sealed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'author_clock_comparison_performed':False,'source_bindings_sha256':sha(HERE/'SOURCE_BINDINGS.json'),'premise_note_sha256':bind['premise_note_sha256'],'premise_author_seal_sha256':bind['premise_author_seal_sha256'],'scope_supported':['Finite positive clock and one time-independent finite Hamiltonian with exact system-plus-battery free-energy conservation','Uniform reduced one-time channel approximation on fixed physical interval [0,T], all inputs including references, conditional on the supplied finite-battery/collision premise','Explicit inverse clock grid and physical free-evolution counterphase','Positive clock energy and variance, pure flags, coherent battery/clock preparation, interaction norm and recurrence accounted for'],'explicit_limits':['No independent certification of the whole supplied battery/collision packet','No exact unbinned event-time instrument, general multitime intervention process, normalized rare-event guarantee or initial dissipative-derivative convergence','No all-time irreversible or fixed-resource asymptotic reservoir; exact clock recurrence after 2T','No native physical law, electric-parameter selection, locality/efficiency/robustness theorem, empirical prediction, audit or landing verdict'],'failures':receipt['retained_mathematical_failed_routes'],'unresolved_execution_failures':[],'open':'Source comparison with frozen autonomous clock author work, not yet accessed','files':files}
(HERE/'PRE_SEAL.json').write_text(json.dumps(seal,indent=2)+'\n')
pre_hash=sha(HERE/'PRE_SEAL.json')
(HERE/'PRE_SEAL.sha256').write_text(pre_hash+'  PRE_SEAL.json\n')
for row in files:
 p=HERE/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes'],row['path']
print(json.dumps({'PRE_SEAL_sha256':pre_hash,'PRE_note_sha256':sha(HERE/'PRE_RECONSTRUCTION.md'),'bound_artifacts':len(files),'bound_sources':len(bind['sources']),'successful_controls':len(receipts),'author_clock_sources_accessed':False,'unresolved_execution_failures':[]},indent=2))
