"""Write final immutable source review after explicit numerical-difference review."""
from pathlib import Path
import json,hashlib,subprocess,sys
r=Path('/private/tmp/review-drain-20260915');w=r/'author-slot-one';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert len(sys.argv)==3,'expected exact final tree and reviewed difference assessment'
tree,assessment=sys.argv[1:];assert subprocess.check_output(['git','-C',str(w),'write-tree'],text=True).strip()==tree
record=json.loads((r/'8095-unit-v1-preexecution.json').read_text());report=json.loads((r/'review-8095-preexecution.json').read_text())
stem=Path(record['notes'][0]['primary_runner']).stem;receiptpath=r/('8095-execution-'+stem+'.json');receipt=json.loads(receiptpath.read_text());comparison=r/'8095-reviewer-payload-comparison.json';assert comparison.exists()
paths=subprocess.check_output(['git','-C',str(w),'diff','--cached','--name-only',record['source']['base']],text=True).splitlines();bindings=[dict(path=p,sha256=sha(w/p)) for p in paths]
latest=subprocess.check_output(['git','-C',str(w),'rev-parse','origin/main'],text=True).strip()
refs=[r/'8095-unit-v1-preexecution.json',r/'review-8095-preexecution.json',r/'8095-preexecution-preflight.json',receiptpath,r/('8095-execution-'+stem+'-started.json'),r/'8095-author-capture.py',r/'8095-author-capture.log',comparison,r/'check8095/final-bind.py',r/'check8095/finalize-record.py']
report.update(status='PASS_WITH_BOUNDED_CLAIMS',final_verdict='PASS WITH BOUNDED CLAIMS',source_tree=tree,source_paths=bindings,remaining=[],executions=[dict(runner=receipt['runner'],total_pass=274,total_fail=0,elapsed_sec=receipt['result']['elapsed_sec'],timeout_sec=60,cache_sha256=receipt['cache_sha256'])],final_confirmation='All staged source and input hashes confirmed; 173 decoded historical payloads and 176 original dispositions retained. Only the new designated canonical cache was added after preexecution freeze. One actual 274/0 capture, no primary rerun. Sixteen independent exact controls and full written proof review support the bounded source verdict.',numerical_evidence_assessment=assessment,current_main_context=dict(commit=latest,assessment='All inherited proof/premise, mandatory authority, methodology and tooling inputs match latest main exactly. New native flux/electric-density notes concern a separate supplied full-carrier Hamiltonian; their scope does not supply or change the classical metric/complex-spinor ansatz here. The independently reviewed campaign meta note proposes questions and adds no axiom or proof premise.'),references=report['references']+[dict(path=str(p),sha256=sha(p)) for p in refs])
final=r/'review-8095-final.json';assert not final.exists();final.write_text(json.dumps(report,indent=2)+'\n');ref=dict(path=str(final),sha256=sha(final))
record['unit_id']='pr8095-final';record['source']['tree']=tree;record['source']['paths']=bindings;record['reviewer']['report']=ref
for c in record['constituents']:c['dispositions']=dict(ref,json_pointer='/original_dispositions/'+c['id'])
for x in record['non_science_notes']:x['review_reference']=ref
record['reviewer']['references'] += [dict(path=str(p),sha256=sha(p)) for p in refs]
record['boundary']='Final independent source PASS WITH BOUNDED CLAIMS. Shared final cache preflight and combined integration remain separate; no audit outcome or native quantum metric theorem.'
fp=r/'8095-unit-v1-final.json';assert not fp.exists();fp.write_text(json.dumps(record,indent=2)+'\n')
md=r/'review-8095.md';assert not md.exists();md.write_text('# PR8095 independent source review\n\n**PASS WITH BOUNDED CLAIMS** at tree `'+tree+'`.\n\nFull proof, primary and all 176 original path dispositions reviewed; 173 historical payloads preserved exactly. Sixteen independent exact controls passed. One fresh capture completed 274/0 under the 60-second cap, with unchanged source/input bytes and a fresh canonical cache.\n\nThe result is a supplied classical metric/spinor construction, an ansatz-restricted coefficient classification, and finite native source consistency. It does not derive native quantum geometry, physical source selection, or gravitational constants. Historical failed refinement and ineffective mutation remain explicit.\n\nFinal report SHA256: `'+sha(final)+'`. Final v1 record SHA256: `'+sha(fp)+'`. Integration and audit are separate.\n')
print(json.dumps(dict(tree=tree,report_sha256=sha(final),record_sha256=sha(fp),source_paths=len(paths)),indent=2))
