from pathlib import Path
import json,hashlib,subprocess
w=Path('/private/tmp/review-drain-20260915/unit8039');o=Path('/private/tmp/review-drain-20260915');h='96827c8023a008b5616464fe5d66369b8fa4424f'
def git(*a):return subprocess.check_output(['git',*a],cwd=w,text=True).strip()
def sha(b):return hashlib.sha256(b).hexdigest()
def blob(ref,p):return subprocess.check_output(['git','show',ref+':'+p],cwd=w)
base=git('rev-parse','HEAD');mb=git('merge-base',base,h);sources=git('diff','--cached','--name-only').splitlines();note=next(p for p in sources if p.startswith('docs/'));runner=next(p for p in sources if p.startswith('scripts/'));rows=[]
for line in git('diff','--name-status',mb,h).splitlines():
 st,p=line.split('\t',1);d={'original_path':p,'status':st,'original_blob':git('rev-parse',h+':'+p),'original_sha256':sha(blob(h,p)),'recovery':h+':'+p}
 if p in sources:d.update(disposition='narrowed',final_path=p,reason='Original science retained; complete recovered control scope and accurate historical provenance/cached execution.')
 elif p=='docs/audit/data/citation_graph_manifest.json':d.update(disposition='superseded',reason='Generated topology manifest reserved for combined current-tree regeneration.')
 elif '/mutations/' in p:d.update(disposition='rejected',reason='Intentionally false historical source mutants and their failure logs, not scientific source. Failure mode remains recoverable.')
 elif p.endswith('/check.py'):d.update(disposition='superseded',final_path=runner,reason='Original exact checker retained in canonical computation; independent nonuniform/all-label/p=q boundary controls salvaged, with duplicate2x3 core already covered.')
 elif any(x in p for x in ['DERIVATION.md','PREREGISTRATION.md','ORIENTATION_MIXTURE.md','SOURCE_BINDING.md','NATIVE_PROOF_REVIEW.md','CANONICAL_PORT_REVIEW.md','BEFORE_WHITESPACE_NOTE.md.gz','NO_GO_LEDGER.md']):d.update(disposition='superseded',final_path=note,reason='Valid proof/conditions and mixture scope retained in canonical note. Independent row-stationarity/monotone-class routes establish same claims as leaf-removal/martingale route; no extra theorem lost. Compressed predecessor differs only whitespace. Prior reviews are historical evidence, not authority.')
 elif p.endswith(('RESULT.json','result.json','LIVE_STDOUT.txt','LIVE_RESULT.json','BEFORE_WHITESPACE_LIVE_STDOUT.txt')):d.update(disposition='superseded',final_path=runner,reason='Exact probability/control payload recoverable in canonical execution; historical timing and source hashes preserved only at original head.')
 else:d.update(disposition='rejected',reason='Non-source historical process/status/identity/validation artifacts; inspected for unique science obligations; not landed as audit or review authority.')
 if 'final_path' in d:
  q=d['final_path'];d.update(final_blob=git('rev-parse',':'+q),final_sha256=sha((w/q).read_bytes()))
 rows.append(d)
prev=json.load(open(o/'review-8011.json'));inputs=[]
for d in prev['inputs']:
 q=d['path'];assert sha((w/q).read_bytes())==d['sha256'];e={k:d[k] for k in ['path','blob','sha256']}
 if 'MONOTONE_ORDER' in q:e['coverage']='Current P1,P2 and P7(a) proofs and finite-menu/product definitions, read in prior8011 session; unchanged exact bytes reverified. Needed rectangle density, normalized DAG and opposite-corner identity. P4–P6 and strip machinery are not needed.'
 elif 'FINITE_WINDOW' in q:e['coverage']='Inherited six-projector menu/orbit/product and records-only probability definition only; unchanged prior necessary source read. Static-law classification not used.'
 else:e['coverage']=d['coverage']
 inputs.append(e)
data={'unit':'PR8039','reviewer_session':'/root/review_8011','original_head':h,'declared_base':'main','original_merge_base':mb,'confirmation_base':base,'reviewed_staged_tree':git('write-tree'),'source_state':'staged candidate','original_path_count':len(rows),'deleted_original_paths':[],'disposition_map':rows,'disposition_map_sha256':sha(json.dumps(rows,sort_keys=True,separators=(',',':')).encode()),'source_paths':[{'path':p,'blob':git('rev-parse',':'+p),'sha256':sha((w/p).read_bytes())} for p in sources],'inputs':inputs,'runtime_inputs':'Canonical runner reads only note and monotone parent bytes for declared SHA256 binding; mathematical arithmetic is standalone standard-library. Both source inputs and runner hash match fresh cache.','current_main_loss_check':'All three science paths are additions absent on confirmation base. Current corrected monotone parent preserved, no overwritten/deleted main science; generated manifest regenerated at combined gate.','claims':['All translated subrectangle consistency and unique chosen cylinder extension to plane','All-positive nonconstant two diagonal classes differ; constant boundary iid','Finite-set Gibbs specification with axial-logK and SW–NE+logH potentials; no Gibbs uniqueness claim','Positive-event discrepancy from original axial specification and any convex mixture of the two classes; equal mixture restores square-dihedral symmetry only'],'independent_evidence':json.load(open(o/'check8039/independent.json')),'final_controls':json.load(open(o/'check8039/final-controls.json')),'findings':{'F1':'fixed: canonical recovered controls, honest historical recovery and fresh bound cache'},'proof_obligations':'CONDITIONAL and closed at supplied positive symmetric six-state orbit rule/records-only rectangle scope, with standard countable probability extension and conditional-expectation convergence. No physical order/action/instrument selection.','lenses':{'code':'PASS','physics':'BOUNDED','proof':'CONDITIONAL','imports':'DISCLOSED','nature_retention':'BOUNDED','no_go':'honest finite-family scope, N1–N8 present; no universal no-go or fabricated exhaustive route claim','labeling':'PASS','governance':'source PASS; combined gate pending'},'full_pipeline_count':0,'combined_gate':'coordinator pending','findings_sha256':sha((o/'review-8039.md').read_bytes()),'verdict':'FINAL VERDICT: PASS','verdict_scope':'source only; no audit or landing authority'}
(o/'review-8039.json').write_text(json.dumps(data,indent=2)+'\n');print(data['reviewed_staged_tree'],data['verdict'])
