"""T134 - DOES CURVATURE SPLIT THE TASTE DEGENERACY?

R76 established that the framework's fibre is 2^{d/2} EXACTLY degenerate Dirac
fermions, and that the degeneracy is structural: from {Gamma_a, Gamma_b} =
2 (g^-1)_ab it follows that (Gamma.s)^2 = (s.g^-1.s) I, so every level is exactly
2^{d-1}-fold degenerate.  I recorded that as closing the generations route.

But that argument assumes CONSTANT g.  On a curved manifold the Kahler-Dirac
operator is D = d + delta and D^2 is the Hodge Laplacian, whose Weitzenbock terms
differ per form degree -- which is exactly what made a_1 differ per degree in
T131.  Equivalently: Lambda*(M) = S (x) S*, and D corresponds to the Dirac
operator TWISTED by the dual spinor bundle S*.  That twist is trivial only if S*
is flat.  So the degeneracy is protected by flatness, not by the algebra alone,
and curvature is a candidate splitting mechanism -- generated by the framework's
OWN gravity, which is the kind of mechanism the generations question needs.

This is a positive-path question and it has a clean numerical answer.  Build the
full DEC Hodge Laplacian on 0-, 1- and 2-forms on a triangulated surface and look
at the degeneracy pattern of the combined spectrum on Lambda* (rank 4 = 2 tastes
in d=2):
   * exact 2-fold degeneracies everywhere -> curvature does NOT split; route closed.
   * splitting that scales with the curvature -> a real mechanism; route open.

The round sphere is a trap here: it is a symmetric space, so its Hodge spectra on
all three degrees collapse onto l(l+1) and nothing splits for reasons that have
nothing to do with the general case.  It is the CONTROL, not the test.  The test
is a generic, non-symmetric metric.

DEC.  With S_k the diagonal Hodge stars and d_k the coboundaries, put
   B_k = S_{k+1}^{1/2} d_k S_k^{-1/2}
so the symmetrised Laplacians are simply
   A_0 = B_0^T B_0,   A_1 = B_1^T B_1 + B_0 B_0^T,   A_2 = B_1 B_1^T.
VALIDATION before any physics: McKean-Singer, sum_k (-1)^k Tr e^{-t A_k} = chi
exactly and independently of t.  If that fails the implementation is wrong."""
import numpy as np, itertools, sys
sys.path.insert(0,"/private/tmp/claude-502/-Users-jonBridger-Projects-Physics-baremetal-probes--claude-worktrees-gravity-toe-lane-work-427b0b/25068357-42e8-431c-96c9-c149512f0305/scratchpad")
from opus_t121 import icosphere

def dec(P,Fc):
    """Full DEC on a triangulated surface: returns B_0, B_1 and the areas."""
    E={}; 
    def eid(i,j):
        k=(min(i,j),max(i,j))
        if k not in E: E[k]=len(E)
        return E[k]
    for f in Fc:
        for a in range(3): eid(f[a],f[(a+1)%3])
    V=len(P); NE=len(E); NF=len(Fc)
    d0=np.zeros((NE,V))
    for (i,j),e in E.items(): d0[e,j]=1.0; d0[e,i]=-1.0
    d1=np.zeros((NF,NE))
    for fi,f in enumerate(Fc):
        for a in range(3):
            i,j=f[a],f[(a+1)%3]; e=E[(min(i,j),max(i,j))]
            d1[fi,e]+= 1.0 if i<j else -1.0
    # Hodge stars
    Adual=np.zeros(V); Aface=np.zeros(NF); s1=np.zeros(NE)
    for fi,f in enumerate(Fc):
        p=[P[i] for i in f]
        A=0.5*np.linalg.norm(np.cross(p[1]-p[0],p[2]-p[0])); Aface[fi]=A
        for a in range(3): Adual[f[a]]+=A/3.0
        for a in range(3):                       # cotangent at vertex a, opposite edge
            b,c=(a+1)%3,(a+2)%3
            u=p[b]-p[a]; v=p[c]-p[a]
            cot=float(u@v)/max(np.linalg.norm(np.cross(u,v)),1e-300)
            e=E[(min(f[b],f[c]),max(f[b],f[c]))]; s1[e]+=0.5*cot
    S0=Adual; S1=np.abs(s1); S2=1.0/Aface
    B0=(np.sqrt(S1)[:,None]*d0)/np.sqrt(S0)[None,:]
    B1=(np.sqrt(S2)[:,None]*d1)/np.sqrt(S1)[None,:]
    return B0,B1,Aface.sum()

def spectra(P,Fc):
    B0,B1,area=dec(P,Fc)
    A0=B0.T@B0; A1=B1.T@B1+B0@B0.T; A2=B1@B1.T
    f=lambda M: np.linalg.eigvalsh(0.5*(M+M.T))
    return f(A0),f(A1),f(A2),area

def bumpy(P,amp,mode=3):
    """generic, NON-symmetric radial deformation -- breaks the sphere's symmetry"""
    Q=[]
    for p in P:
        x,y,z=p
        r=1.0+amp*(z**3 - 0.7*x*y*z + 0.4*x**2*y)
        Q.append(p*r)
    return np.array(Q)

print("T134  does curvature split the Kahler-Dirac taste degeneracy?  (d=2, taste count 2)")
print()
P,Fc=icosphere(3)
print(f"   mesh: {len(P)} vertices, {len(Fc)} faces")
for nm,Q in (("ROUND sphere (control -- symmetric space)",P),
             ("BUMPY  amp=0.15 (generic curvature)",bumpy(P,0.15)),
             ("BUMPY  amp=0.30 (more curvature)",bumpy(P,0.30))):
    l0,l1,l2,area=spectra(Q,Fc)
    # McKean-Singer validation
    print(f"\n   {nm}   area={area:.5f}")
    print(f"      McKean-Singer  sum_k (-1)^k Tr e^(-t A_k)  must equal chi = 2, for every t:")
    ms=[float(np.sum(np.exp(-t*l0))-np.sum(np.exp(-t*l1))+np.sum(np.exp(-t*l2))) for t in (0.05,0.2,1.0,5.0)]
    print(f"         t=0.05,0.2,1,5 -> " + "  ".join(f"{v:.9f}" for v in ms))
    # the combined Lambda* spectrum and its degeneracy pattern
    lam=np.sort(np.concatenate([l0,l1,l2]))
    lam=lam[lam>1e-8]
    print(f"      lowest 16 nonzero eigenvalues of the FULL Lambda* operator:")
    print("         " + "  ".join(f"{v:.5f}" for v in lam[:8]))
    print("         " + "  ".join(f"{v:.5f}" for v in lam[8:16]))
    # measure pairing: consecutive pairs should be equal if 2-fold degenerate
    d=np.abs(lam[1:32:2]-lam[0:32:2])/lam[0:32:2]
    print(f"      consecutive-pair relative splitting, lowest 16 pairs:"
          f"  max {d.max():.3e}   median {np.median(d):.3e}")
print()
print("   Round sphere near zero and bumpy growing with amplitude = curvature splits")
print("   the tastes, and the framework's own gravity is a generation mechanism.")
print("   All three near zero = the degeneracy survives curvature; route stays closed.")
