"""T35 - THE CONCLUSIVE DIFFEOMORPHISM TEST (first order, metric AND matter).
T32's second-order test is not conclusive: the quadratic form of a
diffeomorphism-invariant action annihilates pure-gauge modes only about a
STATIONARY background, and flat space here is not stationary (T26: the
conformal variation is nonzero -- an uncancelled cosmological term).

The first-order test needs no stationarity.  If W[g,m] = W[phi*g, phi*m] for
every diffeomorphism phi, then along the curve generated by any vector field xi
      dW/dh = 0   IDENTICALLY, on any background.
Infinitesimally, with a xi that points along axis 1 and depends on x_1 only:
      delta g_11 = 2 d_1 xi_1        delta m = xi_1 d_1 m
Both pieces are computed and SUMMED.  A diff-invariant action gives
      (metric piece) + (matter piece) = 0.
The background is deliberately inhomogeneous (m varies), so neither piece is
zero by symmetry -- the cancellation, if it happens, is the real thing."""
import numpy as np, itertools
def carrier(D):
    B=[]
    for k in range(D+1): B+=[tuple(c) for c in itertools.combinations(range(D),k)]
    return B,{b:i for i,b in enumerate(B)}
def ops(D):
    B,IDX=carrier(D); NF=len(B)
    def epsm(a):
        M=np.zeros((NF,NF))
        for Sx in B:
            if a in Sx: continue
            T=tuple(sorted(Sx+(a,))); M[IDX[T],IDX[Sx]]=(-1)**sum(1 for i in Sx if i<a)
        return M
    def iota(a,gi):
        M=np.zeros((NF,NF))
        for Sx in B:
            for pos,i in enumerate(Sx):
                T=tuple(x for x in Sx if x!=i); M[IDX[T],IDX[Sx]]+=(-1)**pos*gi[a,i]
        return M
    return [epsm(a) for a in range(D)],iota,NF
def Wfun(D,L,mfield,gfield,WAVE=1):
    """mfield[x], gfield[x] = full metric at slice x (depends on x_WAVE only)."""
    EPS,iota,NF=ops(D)
    gi=[np.linalg.inv(gfield[x]) for x in range(L)]
    IOT=[[iota(a,gi[x]) for a in range(D)] for x in range(L)]
    GAM=[[EPS[a]+IOT[x][a] for a in range(D)] for x in range(L)]
    trans=[a for a in range(D) if a!=WAVE]
    tot=0.0
    for pidx in itertools.product(range(L),repeat=D-1):
        p={a:2*np.pi*pidx[i]/L for i,a in enumerate(trans)}
        Q=np.zeros((L*NF,L*NF),dtype=complex)
        for x in range(L):
            i=x*NF
            Q[i:i+NF,i:i+NF]+=mfield[x]*np.eye(NF)
            for a in trans: Q[i:i+NF,i:i+NF]+=1j*np.sin(p[a])*GAM[x][a]
            for sgn in (+1,-1):
                y=(x+sgn)%L; j=y*NF
                Q[i:i+NF,j:j+NF]+=0.25*sgn*(2*EPS[WAVE]+IOT[x][WAVE]+IOT[y][WAVE])
        tot+=float(np.real(np.linalg.slogdet(Q)[1]))
    return tot
def dW(D,L,m0,mu,pw,nw,e=1e-4,which="both"):
    """xi_1(x)=sin(2 pi nw x/L);  m(x)=m0+mu cos(2 pi pw x/L)."""
    xs=np.arange(L)
    xi  = np.sin(2*np.pi*nw*xs/L)
    dxi = (2*np.pi*nw/L)*np.cos(2*np.pi*nw*xs/L)
    m   = m0 + mu*np.cos(2*np.pi*pw*xs/L)
    dm  = -mu*(2*np.pi*pw/L)*np.sin(2*np.pi*pw*xs/L)
    def fields(h):
        g=[np.eye(D) for _ in range(L)]
        mm=list(m)
        for x in range(L):
            if which in ("both","metric"): g[x]=np.eye(D); g[x][1,1]=1.0+2*h*dxi[x]
            if which in ("both","matter"): mm[x]=m[x]+h*xi[x]*dm[x]
        return mm,g
    mp,gp=fields(+e); mm_,gm=fields(-e)
    return (Wfun(D,L,mp,gp)-Wfun(D,L,mm_,gm))/(2*e)
print("T35  d=4  L=8  m0=0.9  mu=0.35  matter wave p=1.  xi wavenumber nw scanned.")
print("     A diffeomorphism-invariant action must give metric + matter = 0.")
print()
print(f"  {'nw':>3} {'metric piece':>18} {'matter piece':>18} {'SUM':>18} {'|sum|/max|piece|':>18}")
for nw in (1,2,3):
    a=dW(4,8,0.9,0.35,1,nw,which="metric")
    b=dW(4,8,0.9,0.35,1,nw,which="matter")
    c=dW(4,8,0.9,0.35,1,nw,which="both")
    rel=abs(c)/max(abs(a),abs(b),1e-30)
    print(f"  {nw:3d} {a:+18.8f} {b:+18.8f} {c:+18.8f} {rel:18.6f}", flush=True)
print()
print("  long-wavelength check (L=12, xi and matter both at the longest wavelength):")
for L in (8,10,12):
    a=dW(4,L,0.9,0.35,1,1,which="metric"); b=dW(4,L,0.9,0.35,1,1,which="matter")
    c=dW(4,L,0.9,0.35,1,1,which="both"); V=L**4
    print(f"   L={L:2d}  metric={a:+.6f}  matter={b:+.6f}  SUM={c:+.6f}  "
          f"SUM/V={c/V:+.8f}  rel={abs(c)/max(abs(a),abs(b)):.6f}", flush=True)
print()
print("  READING: rel ~ 0 means the two pieces cancel -> the action IS diff invariant")
print("  and T32's second-order gauge response is a non-stationarity artefact.")
print("  rel ~ 1 means it is genuinely not diff invariant.")
