#!/usr/bin/env python3
"""J:attack-b:PR8180 — SAME TEST BOTH SIDES on T2 symmetries, not the known HITs.

T2: formation 1-u = k^T M k + O(k^4), order-6 predecessor symmetry;
comparator E = |k|^2 + O(k^4), 48 signed-permutation cubic symmetry.
Apply the identical small-k expansion and the identical two group-invariance
tests to both kernels (1-u embedded as independent of k3).
A HIT if both pass or both fail the same test in the same representation.
"""
from __future__ import annotations

import itertools
import sys

import sympy as sp


def hits(msg: str) -> int:
    print(f"HIT: {msg}")
    print(f"SUMMARY: HIT - {msg}")
    return 0


def main() -> int:
    k1, k2, k3 = sp.symbols("k1 k2 k3", real=True)
    phi = (1 + sp.exp(sp.I * k1) + sp.exp(sp.I * k2)) / 3
    u = sp.simplify(sp.expand_complex(sp.conjugate(phi) * phi))
    one_u = (4 * sp.Rational(1, 9)) * (
        sp.sin(k1 / 2) ** 2 + sp.sin(k2 / 2) ** 2 + sp.sin((k1 - k2) / 2) ** 2
    )
    E = 2 * (1 - sp.cos(k1)) + 2 * (1 - sp.cos(k2)) + 2 * (1 - sp.cos(k3))

    M = sp.Matrix([[2, -1], [-1, 2]]) / 9
    quad = (sp.Matrix([k1, k2]).T * M * sp.Matrix([k1, k2]))[0]
    # series of 1-u and k^T M k through degree 3 must match; O(k^4) remainder
    s_form = sp.series(one_u, k1, 0, 4).removeO()
    s_form = sp.series(s_form, k2, 0, 4).removeO()
    s_quad = sp.expand(quad)
    if sp.expand(s_form - s_quad) != 0:
        # allow leftover degree 4 if series mixed; compare homogeneous deg 2
        h2_f = sum(
            term
            for term in sp.Poly(sp.expand(s_form), k1, k2).as_expr().as_ordered_terms()
            if sp.total_degree(term, k1, k2) == 2
        )
        if sp.expand(h2_f - s_quad) != 0:
            return hits(f"formation quadratic form != k^T M k: {s_form} vs {s_quad}")
    print("formation 1-u = k^T M k + O(k^4): True")

    sE = sp.series(sp.series(sp.series(E, k1, 0, 4).removeO(), k2, 0, 4).removeO(), k3, 0, 4).removeO()
    iso = k1**2 + k2**2 + k3**2
    h2_E = sp.expand(sE).as_poly(k1, k2, k3)
    # take degree-2 part
    deg2 = 0
    for mon, c in h2_E.terms():
        if sum(mon) == 2:
            deg2 += c * k1 ** mon[0] * k2 ** mon[1] * k3 ** mon[2]
    if sp.expand(deg2 - iso) != 0:
        return hits(f"comparator quadratic form {deg2} != |k|^2")
    print("comparator E = |k|^2 + O(k^4): True")

    ev = sorted(sp.simplify(e) for e in M.eigenvals())
    if ev != [sp.Rational(1, 9), sp.Rational(1, 3)]:
        return hits(f"M ev {ev}")
    print("M eigenvalues 1/9, 1/3: True")

    # order-6 group generated by s: (k1,k2)->(k2,k1) and r: (k1,k2)->(k1-k2,-k2)
    def s_map(a, b):
        return b, a

    def r_map(a, b):
        return a - b, -b

    gens = []
    seen = set()
    queue = [(k1, k2)]
    while queue:
        a, b = queue.pop()
        key = (sp.expand(a), sp.expand(b))
        if key in seen:
            continue
        seen.add(key)
        gens.append((a, b))
        for fa, fb in (s_map(a, b), r_map(a, b)):
            queue.append((fa, fb))
    if len(seen) != 6:
        return hits(f"predecessor group has {len(seen)} != 6 elements: {seen}")
    print(f"predecessor group order {len(seen)}: True")

    def inv6(expr):
        for a, b in gens:
            e2 = expr.xreplace({k1: a, k2: b})
            if sp.simplify(expr - e2) != 0:
                return False
        return True

    form6 = inv6(one_u)
    # E in the plane k3=0
    Eplane = E.subs(k3, 0)
    comp6 = inv6(Eplane)
    print(f"order-6 invariance: formation={form6} comparator-plane={comp6}")
    if form6 == comp6:
        return hits(
            "order-6 invariance does not separate: both "
            f"{'invariant' if form6 else 'not invariant'}"
        )

    # 48 signed permutations of (k1,k2,k3)
    def cube48():
        out = []
        for perm in itertools.permutations((k1, k2, k3)):
            for signs in itertools.product((-1, 1), repeat=3):
                out.append(tuple(signs[i] * perm[i] for i in range(3)))
        return out

    orb = cube48()
    if len(orb) != 48:
        return hits(f"|signed perms|={len(orb)} != 48")

    def inv48(expr):
        for a, b, c in orb:
            e2 = expr.xreplace({k1: a, k2: b, k3: c})
            if sp.simplify(expr - e2) != 0:
                return False
        return True

    # formation as 3d function independent of k3
    form48 = inv48(one_u)
    comp48 = inv48(E)
    print(f"48-group invariance: formation={form48} comparator={comp48}")
    if form48 == comp48:
        return hits(
            "48-group invariance does not separate: both "
            f"{'invariant' if form48 else 'not invariant'}"
        )

    print(
        "SUMMARY: pattern has no purchase on this note: the same small-k and "
        "group-invariance tests separate the kernels as written (formation is "
        "order-6 and not 48, comparator is 48 and not order-6 on the plane)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
