from pathlib import Path
import subprocess,json,hashlib,ast
O=Path('/private/tmp/review-drain-20260915');R=O/'unit8036';H='6067254e3bca867aa6e737f7aa2bb6078e5d622d'
def git(*a):return subprocess.check_output(['git','-C',str(R),*a],text=True).strip()
def sha(b):return hashlib.sha256(b).hexdigest()
assert not git('diff','--name-only'),'unstaged changes remain'
paths=git('diff','--cached','--name-only').splitlines();base=git('rev-parse','HEAD')
rows=[dict(path=p,blob=git('rev-parse',':'+p),sha256=sha((R/p).read_bytes()),coverage='Complete changed source/certificate; actual consumer contexts for tooling paths') for p in paths]
p=next(p for p in json.load(open(O/'topology.json'))['prs'] if p['number']==8036);ds=[]
for d in p['original_delta']:
 path=d['path'];target=None
 if path in paths:target=path;status='accepted unchanged' if git('rev-parse',':'+path)==d['new_blob'] else 'narrowed';reason='Canonical scientific claim/evidence retained; wrapper discovery/output and provenance corrections where changed.'
 elif path.startswith('outputs/'):
  target='logs/runner-cache/native_product_gibbs_preparation_2026_09_08.txt';status='superseded';reason='Original whole output and each helper output exactly matched original canonical full stdout JSON; current canonical cache retains complete fresh outputs. No unique numeric science lost.'
 elif path.startswith('.claude/'):
  target='docs/work_history/repo/review_feedback/native_product_gibbs_preparation_2026_09_08/MUTATION_RECORD.json';status='accepted unchanged';reason='Exact original ten-mutation evidence relocated and linked; no recovered survivor checkpoint asserted.'
 else:status='rejected';reason='Stale generated citation manifest; recompute on exact integrated current main.'
 ds.append(dict(original_path=path,original_blob=d['new_blob'],disposition=status,reason=reason,final_path=target,final_blob=git('rev-parse',':'+target) if target else None,recovery=H+':'+path))
inputs=[]
for f,role in [('docs/NATIVE_EDGE_RECORD_MATTER_INSTRUMENT_AND_ENERGY_LEDGER_BOUNDED_THEOREM_NOTE_2026-09-05.md','Consumed complete definitions and theorems1-3: native physical edge/CAR algebra,tree parity dictionary,leaf event,post-record signs and support. Energy apparatus theorem not consumed.'),('docs/NATIVE_EDGE_RECORD_LOCAL_CYCLE_TRANSPORT_AND_LEDGER_BOUNDED_THEOREM_NOTE_2026-09-05.md','Complete source read; phase operator form consumed only; arbitrary angles separately supplied,not inferred from numeric0.7 pulse.'),('docs/MINIMAL_AXIOMS_2026-06-29.md','Already read in same reviewer session; verified byte-identical on this base.'),('docs/audit/data/axiom_premise_nodes.json','Already read in same session; exact unchanged bytes verified.'),('docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md','Prior complete read reused after exact byte comparison; no units input.'),('docs/KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','Prior complete read reused after exact byte comparison; not a control-law supplier.'),('docs/REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md','Prior complete read reused after exact byte comparison; does not supply ready state.')]:
 inputs.append(dict(path=f,blob=git('rev-parse',base+':'+f),sha256=sha((R/f).read_bytes()),coverage=role))
claims=[dict(claim='General finite path Gibbs-filter construction',disposition='accepted under explicit supplied apparatus',domain='finite m>=2,real symmetric zero-diagonal nearest-neighbor h,finite beta>=0,all ready inputs',proof='CONDITIONAL',content=['tree product-ready rank2^m and even-matter maximally mixed functional','empty/filled-leaf contractions and complete2^m history instrument','adjacent phase/hopping SO mode synthesis including residual signs','full Kraus c exp(-beta H/2)P;reference-stable identity','Gibbs functional on supplied mixed-ready state;success product and2^-m bound'],inputs=['native ordinary edge/CAR carrier','unrecorded sharp leaf preparations and mixed remaining qubits','arbitrary programmed hopping/difference-phase angles','Born/Lueders event and deletion convention','supplied h and beta']),dict(claim='Odd three-mode encoded density/hopping filter',disposition='accepted only on stated rank4 correlated parity code',proof='CONDITIONAL',content=['restricted quadratic identity,not ambient operator identity','complete8outcome native leaf instrument','exact r=3/5 spectral amplitudes and probability/energy/hopping values'],limits=['no general interacting many-mode compiler','no autonomous formation,energy supply,temperature or Hamiltonian selection'])]
record=dict(pr=8036,reviewer_session='/root/backlog_topology',original_head=H,original_merge_base=p['merge_base'],confirmation_base=base,reviewed_tree=git('write-tree'),source_verdict='PASS',landing_verdict='not issued',final_paths=rows,original_dispositions=ds,disposition_map_sha256=sha(json.dumps(ds,sort_keys=True).encode()),claim_dispositions=claims,proof_inputs=inputs,findings=[dict(id='8036-1',status='resolved same session',issue='Missing unique mutation provenance and unsupported checkpoint-preservation claim'),dict(id='8036-2',status='resolved same session',issue='Dynamic wrapper omitted three helpers from actual source discovery')],evidence=[dict(path=str(f),sha256=sha(f.read_bytes())) for f in (O/'check8036').glob('*.json')],limits='Review is conditional source acceptance,not independent audit or integrated-current-main validation. All later source/input/helper changes require same-session confirmation.')
(O/'review-8036.json').write_text(json.dumps(record,indent=2)+'\n');print(record['reviewed_tree'],len(paths))
