"""
Audit companion (exact, sympy) for
LOCAL_TOMOGRAPHY_FROM_QUBIT_COMPLEX_STRUCTURE_NARROW_THEOREM_NOTE_2026-06-03.md

Bounded theorem: the local-tomography admission pinned by the companion no-go
TENSOR_COMPOSITION_REQUIRES_LOCAL_TOMOGRAPHY_... is NOT a separate input
beyond axiom A1. It is the composite-level expression of the qubit's complex
unit i. Mechanism: a COMPLEX algebra has dim_sa = dim_C (the unit i splits it
as A = A_sa + i A_sa), and dim_C is multiplicative under the complex tensor
product, so local tomography is automatic; the real rebit (no i) has
dim_sa = n(n+1)/2 != dim and fails. Each site algebra M_2(C) contains the
global element i*1, so the composite generated by the sites is complex with
ONE shared i (the C-linear embeddings send i -> i*1), hence M_4(C), hence
locally tomographic. The same i is omega = s1 s2 s3 that fixes d_s=3.

Hardy / Chiribella-D'Ariano-Perinotti (local tomography distinguishes
complex from real QM) and Wootters (real-QM non-tomography) are comparators
only; the runner reproves the finite-dimensional facts directly.

No PDG values, no fitted selectors, no lattice numerics consumed.
"""
import sympy as sp
from sympy import I, eye, zeros, Matrix

R = []
def chk(label, ok): R.append((label, bool(ok)))
def kron(A, B):
    a, b = A.shape[0], B.shape[0]
    M = zeros(a*b, a*b)
    for i in range(a):
        for j in range(a):
            for k in range(b):
                for l in range(b):
                    M[i*b+k, j*b+l] = A[i, j]*B[k, l]
    return M

def sa_complex(n): return n*n          # Hermitian n x n
def dimC(n):       return n*n          # complex dim of M_n(C)
def sa_real(n):    return n*(n+1)//2   # symmetric n x n

s0 = eye(2)
s1 = Matrix([[0, 1], [1, 0]])
s2 = Matrix([[0, -I], [I, 0]])
s3 = Matrix([[1, 0], [0, -1]])

# (M1) THE MECHANISM: a complex algebra has observable dimension = complex
#      dimension, because the imaginary unit i splits it (Cartesian decomposition).
chk("M1  dim_sa(M_n C) = n^2 = dim_C(M_n C) for n=2,3,4 (i makes sa-dim = complex-dim)",
    all(sa_complex(n) == dimC(n) for n in (2, 3, 4)))
a, b, c, d, e, f, g, h = sp.symbols('a b c d e f g h', real=True)
Mc = Matrix([[a + I*b, c + I*d], [e + I*f, g + I*h]])
H1 = (Mc + Mc.conjugate().T)/2
H2 = (Mc - Mc.conjugate().T)/(2*I)
chk("M1b exhibit M = H1 + i H2 with H1,H2 Hermitian (i splits the algebra: A = A_sa + i A_sa)",
    sp.simplify(Mc - (H1 + I*H2)) == zeros(2, 2)
    and sp.simplify(H1 - H1.conjugate().T) == zeros(2, 2)
    and sp.simplify(H2 - H2.conjugate().T) == zeros(2, 2))

# (M2) dim_C multiplicative under (x)_C  =>  dim_sa multiplicative  =>  LOCAL TOMOGRAPHY.
chk("M2  complex => local tomography: dim_sa(M2(x)M2) = 16 = 4*4 = dim_sa(M2)*dim_sa(M2)",
    sa_complex(4) == sa_complex(2)*sa_complex(2))

# (M3) CONTRAST: the rebit lacks i, so dim_sa = n(n+1)/2 is NOT multiplicative -> fails (9 != 10).
chk("M3  real (no i) fails: dim_sa(M2R)^2 = 3*3 = 9 != 10 = dim_sa(M4R)",
    sa_real(2)**2 == 9 and sa_real(4) == 10)

# (M4) EACH SITE CONTAINS THE GLOBAL i*1: the imaginary unit of M_2(C) is i*1 (i times the
#      shared identity); it is a single global element, the SAME in every site algebra.
chk("M4  the imaginary unit of M_2(C) is i*1 (i*I2), a single element common to every site",
    sp.simplify((I*s0) - I*s0) == zeros(2, 2) and (I*s0)[0, 0] == I)

# (M5) THE REDUCTION: two commuting complex-qubit factors AUTOMATICALLY share one global i,
#      because each contains i*1 and the unit is shared: (i I2)(x)I2 = I2(x)(i I2) = i I4.
iA = kron(I*s0, s0)
iB = kron(s0, I*s0)
iG = I*eye(4)
chk("M5  shared global i: (i I2)(x)I2 = I2(x)(i I2) = i*I4 (both factors' i coincide -> complex composite)",
    sp.simplify(iA - iG) == zeros(4, 4) and sp.simplify(iB - iG) == zeros(4, 4))

# (M6) the shared-i composite generated by two commuting M_2(C) is exactly M_4(C)
#      (16 products independent) -> dim_sa = 16 = 4*4 -> locally tomographic. No room for extras.
basisC = [s0, s1, s2, s3]
prod = [kron(x, y) for x in basisC for y in basisC]
Mr = Matrix.hstack(*[v.reshape(16, 1) for v in prod])
chk("M6  composite = M2(C)(x)M2(C) = M4(C): 16 products span (rank 16), no extra observables",
    Mr.rank() == 16)

# (M7) TRIPLE DUTY: the same global i is omega = s1 s2 s3 -- the complex unit that the d_s=3
#      note reads as the third spatial direction. One i: dimension AND composition.
chk("M7  the global i IS omega = s1 s2 s3 (same complex unit that fixes d_s=3)",
    sp.simplify(s1*s2*s3 - I*s0) == zeros(2, 2))

PASS = sum(1 for _, o in R if o)
FAIL = sum(1 for _, o in R if not o)
for l, o in R:
    print(("PASS" if o else "FAIL"), "-", l)
print("\n%d PASS, %d FAIL" % (PASS, FAIL))
if FAIL:
    raise SystemExit(1)
print(
    "\nREDUCTION verified: local tomography is the composite shadow of the qubit's complex unit i.\n"
    "complex => dim_sa = dim_C => multiplicative => local tomography (M1-M2); the rebit lacks i and\n"
    "fails 9 != 10 (M3). Each site contains the global i*1 (M4), so two complex qubits share one i\n"
    "(M5) and generate exactly M_4(C) (M6); that same i is the d_s=3 volume element (M7). So the\n"
    "local-tomography admission collapses into axiom A1 (one complex i), NOT a separate input."
)
