#!/usr/bin/env python3
r"""FS rotation-exchange discrete-insufficiency narrow no-go -- audit companion.

Companion to
docs/FS_ROTATION_EXCHANGE_DISCRETE_INSUFFICIENCY_NARROW_NO_GO_NOTE_2026-05-28.md

This runner verifies, in exact symbolic linear algebra (sympy, no floats), the
finite-dimensional facts behind the no-go: on the one-qubit operator algebra
over the Z^3 spatial substrate, even granting the on-site spinor 2pi = -1 sign
(the route premise), that sign is NOT sufficient to force fermionic
anticommutation (CAR) over hard-core-boson statistics (CCR-type), because the
discriminator is the CROSS-SITE (graded vs ungraded) relation, not the on-site
rotation sign.

Demonstrations (all exact, on C^2 (x) C^2 = C^4 unless noted):

  (1) ON-SITE 2pi SIGN.  U_2pi = exp(2 pi i S_3) with S_3 = sigma_3 / 2 acts as
      -I_2 on a single site.  Lifted to two sites, U_2pi (x) I and I (x) U_2pi
      act as (-I_2)(x)I and I(x)(-I_2) respectively -- each is -I_4 on the whole
      space (since (-I_2)(x)I_2 = -I_4).  This is a GLOBAL on-site sign, an
      element of the on-site SU(2); it carries NO two-site-exchange information.

  (2) TWO-SITE EXCHANGE = SWAP.  The exchange operator P (tensor swap) acts as
      +1 on the symmetric sector and -1 on the antisymmetric sector; P^2 = I,
      eigenvalues {+1 (x3), -1 (x1)}.  P is an element of S_2 subset U(4)
      permuting the two tensor factors.

  (3) THE BRIDGE GAP (decisive).  P is NOT a function of the on-site 2pi
      rotation.  Concretely:
        - U_2pi (x) I = I (x) U_2pi = -I_4  (both the same scalar matrix),
          so they cannot distinguish the symmetric from the antisymmetric
          sector -- they act as -1 on BOTH.
        - P is non-scalar (it has both +1 and -1 eigenvalues), so P is not in
          the algebra generated by {U_2pi(x)I, I(x)U_2pi} (which is just scalars
          here).  No product/linear combination of the on-site 2pi rotations
          equals P.
      The continuum engine (Finkelstein-Rubinstein) that would identify P with
      a 2pi rotation lives in pi_1 of a CONTINUOUS configuration space; the
      bare discrete site set does not supply that continuous exchange homotopy.

  (4) HARD-CORE BOSON: ungraded (commutes at separation).  The bare ladders
      a_x = sigma_+ on distinct sites COMMUTE: [sigma_+ (x) I, I (x) sigma_+] = 0.
      On-site nilpotent: (sigma_+)^2 = 0, per-site Fock dim 2 -- spin-1/2.  This
      object carries the SAME on-site 2pi = -1 sign (it lives on the same C^2)
      yet is BOSONIC.  So "spin-1/2 + 2pi=-1 => fermion" proves too much.

  (5) JORDAN-WIGNER DRESSED LADDER: graded (anticommutes at separation).  With
      c_0 = sigma_+ (x) I and c_1 = sigma_3 (x) sigma_+, {c_0, c_1} = 0 and
      {c_0, c_1^dag} = 0 -- cross-site CAR (fermionic).

  (6) SAME ALGEBRA, DIFFERENT FRAME.  Both the hard-core-boson generators
      {sigma_+(x)I, sigma_3(x)I} and the JW-fermion generators {c_0, c_1} close
      to the SAME full matrix algebra M_4(C) (complex dim 16 = dim End(C^4)).
      The fermion/boson distinction is therefore NOT in the ungraded algebra or
      the on-site sign; it is exactly the cross-site (anti)commutator -- graded
      locality.  This is the existing statistics-agnostic retained_no_go,
      restated and confirmed.

Verdict the runner supports: the discriminator between CAR and hard-core-boson
statistics is the CROSS-SITE relation (graded vs ungraded), NOT the on-site
2pi = -1 sign.  The on-site sign is invisible to that discriminator (it is the
same scalar -I_4 in both frames).  Therefore the rotation-exchange route does
not close FS from the retained inputs.

Pure exact symbolic linear algebra.  No PDG / fitted / scale / mass input,
no g_bare, no lattice-action carrier.  Asserts NO audit status.
"""

from __future__ import annotations

import sympy as sp

PASS = 0
FAIL = 0


def check(name: str, cond: bool, detail: str = "") -> bool:
    global PASS, FAIL
    if cond:
        PASS += 1
        st = "PASS"
    else:
        FAIL += 1
        st = "FAIL"
    msg = f"  [{st}] {name}"
    if detail:
        msg += f"  ({detail})"
    print(msg)
    return cond


# ---- exact 2x2 building blocks (sympy, no floats) ----
I2 = sp.eye(2)
SX = sp.Matrix([[0, 1], [1, 0]])
SY = sp.Matrix([[0, -sp.I], [sp.I, 0]])
SZ = sp.Matrix([[1, 0], [0, -1]])
SP = (SX + sp.I * SY) / 2   # sigma_+ = |0><1|
SM = (SX - sp.I * SY) / 2   # sigma_-
S3 = SZ / 2                 # spin-3 generator S_3 = sigma_3/2


def kron(A: sp.Matrix, B: sp.Matrix) -> sp.Matrix:
    """Exact Kronecker (tensor) product of two sympy matrices."""
    return sp.Matrix(sp.kronecker_product(A, B))


def comm(A: sp.Matrix, B: sp.Matrix) -> sp.Matrix:
    return A * B - B * A


def anticomm(A: sp.Matrix, B: sp.Matrix) -> sp.Matrix:
    return A * B + B * A


def is_zero(M: sp.Matrix) -> bool:
    return sp.simplify(M) == sp.zeros(*M.shape)


def is_scalar_matrix(M: sp.Matrix):
    """Return the scalar c if M = c*I, else None (exact)."""
    n = M.shape[0]
    if M.shape[1] != n:
        return None
    c = M[0, 0]
    if is_zero(sp.Matrix(M) - c * sp.eye(n)):
        return sp.simplify(c)
    return None


def matrix_exp_2pi_S3() -> sp.Matrix:
    """U_2pi = exp(2 pi i S_3) on a single site, exact via sympy.exp."""
    return sp.simplify((2 * sp.pi * sp.I * S3).exp())


def algebra_dim(generators, dim: int) -> int:
    """Complex dimension of the unital *-algebra generated by `generators`
    inside M_dim(C): close under products + adjoints, measure span rank.

    Exact rank via sympy on the vectorized (flattened) matrices.
    """
    gens = list(generators) + [g.conjugate().T for g in generators]

    def span_rank(mats):
        rows = [list(m) for m in mats]          # row-major flatten
        return sp.Matrix(rows).rank()

    basis = [sp.eye(dim)]
    while True:
        cur = span_rank(basis)
        candidates = list(basis)
        for g in gens:
            for b in basis:
                candidates.append(g * b)
                candidates.append(b * g)
        # greedily extend an independent set
        newbasis = list(basis)
        for c in candidates:
            if span_rank(newbasis + [c]) > span_rank(newbasis):
                newbasis.append(c)
                if span_rank(newbasis) >= dim * dim:
                    return dim * dim
        if span_rank(newbasis) <= cur:
            return cur
        basis = newbasis


def main() -> int:
    print("=" * 78)
    print("FS ROTATION-EXCHANGE DISCRETE-INSUFFICIENCY -- audit companion")
    print("on-site 2pi=-1 sign is NOT the discriminator; cross-site relation is")
    print("=" * 78)

    # =====================================================================
    # (1) on-site 2pi rotation sign U_2pi = exp(2 pi i S_3) = -I_2
    # =====================================================================
    print("\n" + "-" * 78)
    print("(1) on-site spinor 2pi rotation U_2pi = exp(2 pi i S_3) acts as -I_2")
    print("-" * 78)
    U2pi = matrix_exp_2pi_S3()
    c_site = is_scalar_matrix(U2pi)
    check("U_2pi = exp(2 pi i sigma_3/2) = -I_2 (on a single site)",
          c_site == -1, detail=f"U_2pi = ({c_site})*I_2")
    # 4pi returns to +I (the double-cover identity)
    U4pi = sp.simplify((4 * sp.pi * sp.I * S3).exp())
    check("U_4pi = exp(4 pi i sigma_3/2) = +I_2 (2O double-cover: 4pi -> +1)",
          is_scalar_matrix(U4pi) == 1)

    # =====================================================================
    # (2) two-site EXCHANGE operator P (tensor swap): +1 sym, -1 antisym
    # =====================================================================
    print("\n" + "-" * 78)
    print("(2) two-site exchange P (tensor swap): +1 on symmetric, -1 on antisymmetric")
    print("-" * 78)
    # SWAP on C^2 (x) C^2
    P = sp.Matrix([
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ])
    check("P^2 = I_4 (P is an involution / element of S_2)", is_zero(P * P - sp.eye(4)))
    # symmetric basis vectors are +1 eigenvectors; antisymmetric is -1
    e0 = sp.Matrix([1, 0]); e1 = sp.Matrix([0, 1])
    sym1 = kron(e0, e0)
    sym2 = kron(e1, e1)
    sym3 = (kron(e0, e1) + kron(e1, e0))
    antisym = (kron(e0, e1) - kron(e1, e0))
    check("P (|00>) = +|00>  (symmetric, +1)", is_zero(P * sym1 - sym1))
    check("P (|11>) = +|11>  (symmetric, +1)", is_zero(P * sym2 - sym2))
    check("P (|01>+|10>) = +(...)  (symmetric, +1)", is_zero(P * sym3 - sym3))
    check("P (|01>-|10>) = -(...)  (ANTIsymmetric, -1)", is_zero(P * antisym + antisym))
    eigs = P.eigenvals()
    check("P spectrum = {+1 (mult 3), -1 (mult 1)}",
          eigs.get(sp.Integer(1)) == 3 and eigs.get(sp.Integer(-1)) == 1,
          detail=f"eigenvals = {dict(eigs)}")

    # =====================================================================
    # (3) THE BRIDGE GAP: P is NOT a function of the on-site 2pi rotation
    # =====================================================================
    print("\n" + "-" * 78)
    print("(3) bridge gap: the on-site 2pi sign carries NO two-site-exchange info")
    print("-" * 78)
    U2pi_L = kron(U2pi, I2)   # 2pi rotation of the left site
    U2pi_R = kron(I2, U2pi)   # 2pi rotation of the right site
    cL = is_scalar_matrix(U2pi_L)
    cR = is_scalar_matrix(U2pi_R)
    check("U_2pi (x) I = -I_4 (left-site 2pi rotation is a global sign)",
          cL == -1, detail=f"= ({cL})*I_4")
    check("I (x) U_2pi = -I_4 (right-site 2pi rotation is a global sign)",
          cR == -1, detail=f"= ({cR})*I_4")
    check("U_2pi (x) I == I (x) U_2pi (both the SAME scalar -I_4)",
          is_zero(U2pi_L - U2pi_R))
    # the on-site rotations act as -1 on BOTH sym and antisym -> cannot select
    check("on-site 2pi acts as -1 on the SYMMETRIC sector (same as antisym)",
          is_zero(U2pi_L * sym3 + sym3))
    check("on-site 2pi acts as -1 on the ANTISYMMETRIC sector (same as sym)",
          is_zero(U2pi_L * antisym + antisym))
    # P is non-scalar => not in the (scalar) algebra generated by the on-site 2pi rotations
    check("P is NOT a scalar matrix (it separates sym from antisym)",
          is_scalar_matrix(P) is None)
    onsite_alg_dim = algebra_dim([U2pi_L, U2pi_R], 4)
    check("algebra <U_2pi(x)I, I(x)U_2pi> = scalars only (complex dim 1)",
          onsite_alg_dim == 1, detail=f"dim = {onsite_alg_dim}")
    # no scalar equals the non-scalar P => the on-site rotations cannot produce P
    check("no element of <on-site 2pi rotations> equals P "
          "(scalars cannot equal the non-scalar exchange)",
          onsite_alg_dim == 1 and is_scalar_matrix(P) is None)

    # =====================================================================
    # (4) HARD-CORE BOSON: ungraded -- commutes at separation; same C^2 site
    # =====================================================================
    print("\n" + "-" * 78)
    print("(4) hard-core boson: bare ladders COMMUTE across sites (bosonic/ungraded)")
    print("-" * 78)
    a0 = kron(SP, I2)         # sigma_+ on site 0
    a1 = kron(I2, SP)         # sigma_+ on site 1
    a1d = kron(I2, SM)
    check("[sigma_+ (x) I, I (x) sigma_+] = 0 (commute at separation -> BOSONIC)",
          is_zero(comm(a0, a1)))
    check("[sigma_+ (x) I, I (x) sigma_-] = 0 (commute at separation)",
          is_zero(comm(a0, a1d)))
    check("{sigma_+ (x) I, I (x) sigma_+} != 0 (they do NOT anticommute)",
          not is_zero(anticomm(a0, a1)))
    check("on-site nilpotent (sigma_+)^2 = 0 (per-site Fock dim 2 -> spin-1/2)",
          is_zero(SP * SP))
    # the hard-core boson lives on the SAME C^2 and carries the SAME 2pi=-1 sign
    check("hard-core boson site sees the SAME on-site U_2pi = -I_2 "
          "(spin-1/2 + 2pi=-1, yet BOSONIC)",
          is_scalar_matrix(matrix_exp_2pi_S3()) == -1)

    # =====================================================================
    # (5) JORDAN-WIGNER dressed ladder: graded -- anticommutes at separation
    # =====================================================================
    print("\n" + "-" * 78)
    print("(5) Jordan-Wigner dressed ladders ANTICOMMUTE across sites (fermionic/CAR)")
    print("-" * 78)
    c0 = kron(SP, I2)         # c_0 = sigma_+ (x) I  (string of length 0)
    c1 = kron(SZ, SP)         # c_1 = sigma_3 (x) sigma_+  (string prod_{y<1} sigma_3)
    c0d = kron(SM, I2)
    c1d = kron(SZ, SM)
    check("{c_0, c_1} = 0 (cross-site CAR -> FERMIONIC)", is_zero(anticomm(c0, c1)))
    check("{c_0, c_1^dag} = 0 (x != y)", is_zero(anticomm(c0, c1d)))
    check("{c_1, c_0^dag} = 0 (x != y)", is_zero(anticomm(c1, c0d)))
    check("on-site {c_0, c_0^dag} = I_4", is_zero(anticomm(c0, c0d) - sp.eye(4)))
    check("on-site (c_0)^2 = 0", is_zero(c0 * c0))
    check("on-site (c_1)^2 = 0", is_zero(c1 * c1))

    # =====================================================================
    # (6) SAME full matrix algebra M_4(C): statistics is a FRAME choice
    # =====================================================================
    print("\n" + "-" * 78)
    print("(6) hard-core-boson and JW-fermion generators span the SAME algebra M_4(C)")
    print("-" * 78)
    hcb_dim = algebra_dim([a0, kron(SZ, I2), a1, kron(I2, SZ)], 4)
    jw_dim = algebra_dim([c0, c1], 4)
    check("hard-core-boson algebra <sigma_+(x)I, sigma_3(x)I, I(x)sigma_+, I(x)sigma_3> "
          "= M_4(C) (complex dim 16)",
          hcb_dim == 16, detail=f"dim = {hcb_dim}")
    check("JW-fermion algebra <c_0, c_1> = M_4(C) (complex dim 16)",
          jw_dim == 16, detail=f"dim = {jw_dim}")
    check("both frames live on the SAME algebra (16 = dim End(C^4)) -> the "
          "discriminator is the cross-site relation, NOT the on-site sign",
          hcb_dim == jw_dim == 16)

    # =====================================================================
    # (7) N5 EXECUTION CERTIFICATE: what this runner actually resolves
    # =====================================================================
    print("\n" + "-" * 78)
    print("(7) N5 execution certificate -- what this runner resolves")
    print("-" * 78)
    print("  per_element: checked -- every operator is built and tested "
          "individually in exact sympy: U_2pi = -I_2 and U_4pi = +I_2, the swap "
          "P with P^2 = I_4, the nilpotents (sigma_+)^2 = (c_0)^2 = (c_1)^2 = 0 "
          "and the on-site {c_0, c_0^dag} = I_4.")
    print("  per_site: checked -- the two Qubit sites of C^2 (x) C^2 are "
          "resolved separately: the left lift U_2pi (x) I and the right lift "
          "I (x) U_2pi are each shown to be the same scalar -I_4, and the "
          "ladders a_0, a_1 and c_0, c_1 are placed site by site.")
    print("  per_mode: checked -- the exchange eigen-modes are resolved one at "
          "a time: |00>, |11> and |01>+|10> are +1 modes of P while |01>-|10> "
          "is the single -1 mode (spectrum {+1 x3, -1 x1}), and the on-site 2pi "
          "sign is verified to act as -1 on both mode types alike.")
    print("  per_block: checked -- the generated *-algebras are compared as "
          "blocks: <U_2pi(x)I, I(x)U_2pi> closes at complex dim 1 (scalars), "
          "while the hard-core-boson and Jordan-Wigner generator sets each "
          "close at dim 16 = M_4(C), one and the same block.")
    print("  lattice_wide: checked and not executed -- the Z^3 substrate is "
          "named in the premise but only two sites are instantiated here, with "
          "a Jordan-Wigner string of length at most one; the graph-braid pi_1 "
          "and graded-locality structures that need the full lattice stay open.")

    # =====================================================================
    # VERDICT
    # =====================================================================
    print("\n" + "=" * 78)
    print("VERDICT")
    print("=" * 78)
    if FAIL == 0:
        print(
            "  THE ROTATION-EXCHANGE ROUTE DOES NOT CLOSE FS FROM RETAINED INPUTS.\n"
            "  (1) The on-site spinor 2pi rotation U_2pi = exp(2 pi i S_3) = -I_2 is a\n"
            "      single-site element of the on-site SU(2); lifted to two sites it is\n"
            "      the SAME global scalar -I_4 on the left or right factor.\n"
            "  (2) Two-site EXCHANGE is the tensor swap P (an element of S_2 subset\n"
            "      U(4)): +1 on the symmetric sector, -1 on the antisymmetric sector.\n"
            "  (3) BRIDGE GAP: the on-site 2pi rotation generates only scalars (dim 1),\n"
            "      acts as -1 on BOTH the symmetric and antisymmetric sectors, and\n"
            "      therefore cannot equal the non-scalar P.  Nothing connects the\n"
            "      on-site rotation sign to the two-site exchange operator.  The\n"
            "      Finkelstein-Rubinstein engine that would identify them lives in the\n"
            "      pi_1 of a CONTINUOUS configuration space, which the bare discrete\n"
            "      site set does not supply.\n"
            "  (4) The HARD-CORE BOSON shares every premise (spin-1/2, dim-2, same\n"
            "      on-site 2pi = -1 sign, on-site nilpotent) yet is BOSONIC: its bare\n"
            "      ladders COMMUTE at separation.  'spin-1/2 + 2pi=-1 => fermion'\n"
            "      proves too much.\n"
            "  (5) JW-dressing makes the SAME ladders ANTICOMMUTE (cross-site CAR).\n"
            "  (6) Both frames span the SAME full algebra M_4(C); the ONLY difference\n"
            "      is the cross-site (anti)commutator = GRADED LOCALITY, which is not\n"
            "      in the retained set.\n\n"
            "  Honest scope: this prunes the rotation-exchange ROUTE from the retained\n"
            "  inputs; it does NOT foreclose FS absolutely.  Two named future-closure\n"
            "  paths remain OPEN: (a) a lattice-native discrete-homotopy / graph-braid\n"
            "  pi_1 construction; (b) a graded-locality / fermion-parity-superselection\n"
            "  principle.  FS remains an admission candidate on the discrete substrate,\n"
            "  'unsolved / needs-new-structure', not 'impossible'.\n"
        )
    print("=" * 78)
    if FAIL:
        print(f"PASS={PASS} FAIL={FAIL}")
        return 1
    print(f"PASS={PASS} FAIL=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
