#!/usr/bin/env python3
"""Cycle 190: carry five recurrent literals to one generated consumer patch.

This bounded probe takes the compact spacing-12 Cycle-180 recurrent bundle,
uses the retained H0/H1 cable grammar to leave recurrent endpoint support, and
materializes one generated terminal bit before the retained grammar forks it.
One fork branch remains a literal H0/H1 cable.  The other terminates into a
value-neutral MEMBER5 status tree.  The all-five status lineage and the five
ordered literal lineages meet only at five terminal consumer records.

No 32-valued payload is introduced.  This runner has no authority.  It edits
no foundation, axiom, primitive, registry, policy, audit, queue, predecessor,
commit, push, or PR surface.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from itertools import product
from pathlib import Path

import compact_five_literal_lane_spacing_cycle180_2026_07_16 as c180
import physical_literal_bit_cable_probe_2026_07_15 as cable


ROOT = Path(__file__).resolve().parents[1]
NOTE = (
    ROOT
    / "docs"
    / "work_history"
    / "repo"
    / "review_feedback"
    / "BARE_METAL_LITERAL_EGRESS_BIND_CYCLE190_NOTE_2026-07-16.md"
)

c178 = c180.c178
c172 = c180.c172
c171 = c178.c171
c53 = c178.c53
cell = c178.cell

Coord = tuple[int, int, int]
RoleMap = dict[Coord, str]

SPACING = c180.MINIMUM_DISJOINT_SPACING
WORDS = c178.WORDS
H0 = c178.H0
H1 = c178.H1
FRAME = cable.FRAME

# Exact price: one fresh inert supplied cap role and one fresh dynamic,
# value-neutral status role.  Cable FRAME/GUIDE furniture is retained.
EGRESS_CAP = "EGRESS_CAP"
MEMBER5 = "MEMBER5"
NEW_ROLES = frozenset((EGRESS_CAP, MEMBER5))

OFFSETS = c180.offsets(SPACING)
ENDPOINTS = tuple(
    c172.shift(c172.payload_site(c172.COPY_X[-1]), offset)
    for offset in OFFSETS
)
LANE_Y = tuple(site[1] for site in ENDPOINTS)

PASS = 0
FAIL = 0


def check(label: str, condition: bool, detail: object = "") -> None:
    global PASS, FAIL
    if condition:
        PASS += 1
        print("PASS", label, "::", detail)
    else:
        FAIL += 1
        print("FAIL", label, "::", detail)


def add(left: Coord, right: Coord) -> Coord:
    return tuple(a + b for a, b in zip(left, right))  # type: ignore[return-value]


def manhattan(left: Coord, right: Coord) -> int:
    return sum(abs(a - b) for a, b in zip(left, right))


def lattice_path(
    start: Coord,
    waypoints: tuple[Coord, ...],
) -> tuple[Coord, ...]:
    """Nearest-neighbour path excluding start and including each waypoint."""

    current = list(start)
    path = []
    for waypoint in waypoints:
        axes = tuple(
            axis for axis in range(3)
            if current[axis] != waypoint[axis]
        )
        if len(axes) > 1:
            raise ValueError(("non-axis-waypoint", tuple(current), waypoint))
        if not axes:
            continue
        axis = axes[0]
        while current[axis] != waypoint[axis]:
            current[axis] += 1 if waypoint[axis] > current[axis] else -1
            path.append(tuple(current))
    if len(path) != len(set(path)):
        raise ValueError(("path-self-contact", start, waypoints))
    return tuple(path)


def merge_records(*parts: RoleMap) -> RoleMap:
    merged: RoleMap = {}
    for part in parts:
        for site, role in part.items():
            prior = merged.setdefault(site, role)
            if prior != role:
                raise ValueError(("record-conflict", site, prior, role))
    return merged


def base_parts(word: tuple[int, ...]):
    source_lanes = c180.source_parts(word, SPACING)
    output_lanes = c180.output_parts(word, SPACING)
    initial = c180.merge_disjoint(source_lanes)
    expected = c180.merge_disjoint(output_lanes)
    exits = c180.merge_disjoint(c180.exit_parts(SPACING))
    return source_lanes, output_lanes, initial, expected, exits


# ---------------------------------------------------------------------------
# Retained typed cable geometry
# ---------------------------------------------------------------------------

STEM_PATHS: list[tuple[Coord, ...]] = []
STATUS_CABLE_PATHS: list[tuple[Coord, ...]] = []
LITERAL_CABLE_PATHS: list[tuple[Coord, ...]] = []
TERMINAL_BITS: list[Coord] = []
STATUS_PORTS: list[Coord] = []
CONSUMER_SITES: list[Coord] = []
BIT_PARENTS: list[Coord] = []

for endpoint, y in zip(ENDPOINTS, LANE_Y, strict=True):
    # Stop one cell before the old failed terminal seam.  The retained stem
    # leaves TERMINAL_BITS as an open port.  That port is generated by the
    # priced terminal row and is then the common source of two retained cables.
    stem = tuple((x, y, -1) for x in range(-26, -46, -1))
    terminal_bit = (-46, y, -1)
    status_path = (
        terminal_bit,
        (-46, y, 0),
        (-47, y, 0),
        (-48, y, 0),
    )
    literal_path = (
        (terminal_bit,)
        + tuple((-46, y, z) for z in range(-2, -31, -1))
        + tuple((x, y, -30) for x in range(-47, -89, -1))
    )
    STEM_PATHS.append(stem)
    STATUS_CABLE_PATHS.append(status_path)
    LITERAL_CABLE_PATHS.append(literal_path)
    TERMINAL_BITS.append(terminal_bit)
    STATUS_PORTS.append((-49, y, 0))
    BIT_PARENTS.append((-88, y, -30))
    CONSUMER_SITES.append((-89, y, -30))

STEM_PATHS = tuple(STEM_PATHS)
STATUS_CABLE_PATHS = tuple(STATUS_CABLE_PATHS)
LITERAL_CABLE_PATHS = tuple(LITERAL_CABLE_PATHS)
TERMINAL_BITS = tuple(TERMINAL_BITS)
STATUS_PORTS = tuple(STATUS_PORTS)
BIT_PARENTS = tuple(BIT_PARENTS)
CONSUMER_SITES = tuple(CONSUMER_SITES)

CABLE_PATHS = tuple(
    path
    for lane_paths in zip(
        STEM_PATHS,
        STATUS_CABLE_PATHS,
        LITERAL_CABLE_PATHS,
        strict=True,
    )
    for path in lane_paths
)

CABLE_PARENTS: dict[Coord, frozenset[Coord]] = {}
for path in CABLE_PATHS:
    for previous, target in zip(path[:-1], path[1:], strict=True):
        prior = CABLE_PARENTS.setdefault(target, frozenset((previous,)))
        if prior != frozenset((previous,)):
            raise ValueError(("cable-parent-conflict", target, prior, previous))

CABLE_DYNAMIC = frozenset(CABLE_PARENTS)


# ---------------------------------------------------------------------------
# Value-neutral all-five status tree and terminal ordered consumer
# ---------------------------------------------------------------------------

NODE_KIND: dict[Coord, str] = {}
NODE_LANE: dict[Coord, int | None] = {}
CUSTOM_PARENTS: dict[Coord, frozenset[Coord]] = {}


def place_node(
    site: Coord,
    kind: str,
    lane: int | None,
    parents: frozenset[Coord],
) -> Coord:
    if site in NODE_KIND or site in CABLE_DYNAMIC or site in TERMINAL_BITS:
        raise ValueError(("dynamic-overlap", site, NODE_KIND.get(site), kind))
    if not parents or any(manhattan(site, parent) != 1 for parent in parents):
        raise ValueError(("nonlocal-parent", site, parents))
    NODE_KIND[site] = kind
    NODE_LANE[site] = lane
    CUSTOM_PARENTS[site] = parents
    return site


def add_path(
    parent: Coord,
    waypoints: tuple[Coord, ...],
    kind: str,
    lane: int | None,
) -> Coord:
    previous = parent
    for site in lattice_path(parent, waypoints):
        place_node(site, kind, lane, frozenset((previous,)))
        previous = site
    return previous


def add_join(left: Coord, right: Coord, target: Coord) -> Coord:
    return place_node(target, "status", None, frozenset((left, right)))


# H0 and H1 both terminate into the same value-neutral per-lane status leaf.
for lane, (port, status_path) in enumerate(
    zip(STATUS_PORTS, STATUS_CABLE_PATHS, strict=True)
):
    place_node(
        port,
        "status",
        lane,
        frozenset((status_path[-1],)),
    )

pair_parents: list[tuple[Coord, Coord]] = []
for left_lane, right_lane, join_y in ((0, 1, 9), (2, 3, 33)):
    ends = []
    for lane, parent_y in ((left_lane, join_y - 1), (right_lane, join_y + 1)):
        y = LANE_Y[lane]
        ends.append(
            add_path(
                STATUS_PORTS[lane],
                ((-56, y, 0), (-56, parent_y, 0)),
                "status",
                lane,
            )
        )
    pair_parents.append(tuple(ends))  # type: ignore[arg-type]

J01 = add_join(*pair_parents[0], (-56, 9, 0))
J23 = add_join(*pair_parents[1], (-56, 33, 0))

J01_PARENT = add_path(
    J01,
    ((-66, 9, 0), (-66, 20, 0)),
    "status",
    None,
)
J23_PARENT = add_path(
    J23,
    ((-66, 33, 0), (-66, 22, 0)),
    "status",
    None,
)
J0123 = add_join(J01_PARENT, J23_PARENT, (-66, 21, 0))

J0123_PARENT = add_path(
    J0123,
    ((-76, 21, 0), (-76, 39, 0)),
    "status",
    None,
)
J4_PARENT = add_path(
    STATUS_PORTS[4],
    ((-76, LANE_Y[4], 0), (-76, 41, 0)),
    "status",
    4,
)
JFINAL = add_join(J0123_PARENT, J4_PARENT, (-76, 40, 0))

# Leave the tree plane, run to y=3, then descend and cross all five ordered
# consumer rows exactly once at x=-90, z=-30.
STATUS_BUS_END = add_path(
    JFINAL,
    (
        (-90, 40, 0),
        (-90, 3, 0),
        (-90, 3, -30),
        (-90, 51, -30),
    ),
    "status",
    None,
)
STATUS_PARENTS = tuple((-90, y, -30) for y in LANE_Y)

for lane, (bit_parent, status_parent, consumer) in enumerate(
    zip(BIT_PARENTS, STATUS_PARENTS, CONSUMER_SITES, strict=True)
):
    place_node(
        consumer,
        "consumer",
        lane,
        frozenset((bit_parent, status_parent)),
    )

CUSTOM_DYNAMIC = frozenset(NODE_KIND)
JOIN_SITES = frozenset((J01, J23, J0123, JFINAL))

EXTENSION_PARENTS = {
    **CABLE_PARENTS,
    **{
        site: frozenset((stem[-1],))
        for site, stem in zip(TERMINAL_BITS, STEM_PATHS, strict=True)
    },
    **CUSTOM_PARENTS,
}
EXTENSION_DYNAMIC = frozenset(EXTENSION_PARENTS)


def extension_role(site: Coord, word: tuple[int, ...]) -> str:
    if site in NODE_KIND:
        kind = NODE_KIND[site]
        if kind == "status":
            return MEMBER5
        lane = NODE_LANE[site]
        if lane is None:
            raise ValueError(("consumer-without-lane", site))
        return c178.bit_role(word[lane])
    lane = next(
        lane
        for lane, paths in enumerate(
            zip(STEM_PATHS, STATUS_CABLE_PATHS, LITERAL_CABLE_PATHS, strict=True)
        )
        if site in set().union(*map(set, paths)) or site == TERMINAL_BITS[lane]
    )
    return c178.bit_role(word[lane])


def extension_expected(word: tuple[int, ...]) -> RoleMap:
    return {
        site: extension_role(site, word)
        for site in EXTENSION_DYNAMIC
    }


# ---------------------------------------------------------------------------
# Supplied apparatus and exact local-law compilation
# ---------------------------------------------------------------------------

REFERENCE_WORD = (0, 0, 0, 0, 0)
(
    _REFERENCE_SOURCE_LANES,
    _REFERENCE_OUTPUT_LANES,
    REFERENCE_INITIAL,
    REFERENCE_BASE_EXPECTED,
    REFERENCE_EXITS,
) = base_parts(REFERENCE_WORD)

CAPS: RoleMap = {}
for endpoint, terminal, port in zip(
    ENDPOINTS,
    TERMINAL_BITS,
    STATUS_PORTS,
    strict=True,
):
    CAPS[add(endpoint, (0, 1, 0))] = EGRESS_CAP
    CAPS[add(endpoint, (0, 0, -1))] = EGRESS_CAP
    CAPS[add(terminal, (0, 1, 0))] = EGRESS_CAP
    CAPS[add(port, (0, 0, 1))] = EGRESS_CAP
for consumer in CONSUMER_SITES:
    CAPS[add(consumer, (0, 0, 1))] = EGRESS_CAP
    CAPS[add(consumer, (0, 0, -1))] = EGRESS_CAP
for join in JOIN_SITES:
    CAPS[add(join, (0, 0, 1))] = EGRESS_CAP


def build_cable_scaffold() -> tuple[RoleMap, frozenset[Coord]]:
    all_records: RoleMap = {}
    observed_ports: set[Coord] = set()
    observed_expected: set[Coord] = set()
    fixed = merge_records(REFERENCE_INITIAL, REFERENCE_BASE_EXPECTED, CAPS)
    for lane in range(5):
        items = tuple(
            (H0, path)
            for path in (
                STEM_PATHS[lane],
                STATUS_CABLE_PATHS[lane],
                LITERAL_CABLE_PATHS[lane],
            )
        )
        records, expected, ports = cable.multi_path_core(
            items,
            constraints=fixed,
            extra_protected=(
                CUSTOM_DYNAMIC
                | set(REFERENCE_EXITS)
                | set(CONSUMER_SITES)
            ),
        )
        all_records = merge_records(all_records, records)
        observed_expected.update(expected)
        observed_ports.update(ports)
    wanted_ports = set(TERMINAL_BITS) | set(STATUS_PORTS) | set(CONSUMER_SITES)
    if observed_expected != set(CABLE_DYNAMIC):
        raise ValueError((
            "cable-expected-mismatch",
            len(observed_expected ^ set(CABLE_DYNAMIC)),
        ))
    if observed_ports != wanted_ports:
        raise ValueError(("cable-port-mismatch", observed_ports ^ wanted_ports))
    remove = (
        set(REFERENCE_INITIAL)
        | set(REFERENCE_BASE_EXPECTED)
        | set(TERMINAL_BITS)
        | set(CABLE_DYNAMIC)
    )
    scaffold = {
        site: role
        for site, role in all_records.items()
        if site not in remove
    }
    return scaffold, frozenset(observed_ports)


CABLE_SCAFFOLD, OBSERVED_TERMINAL_PORTS = build_cable_scaffold()


def build_scaffold() -> RoleMap:
    scaffold = dict(CABLE_SCAFFOLD)
    occupied_dynamic = (
        set(REFERENCE_INITIAL)
        | set(REFERENCE_BASE_EXPECTED)
        | set(REFERENCE_EXITS)
        | set(EXTENSION_DYNAMIC)
    )
    for target in sorted(CUSTOM_DYNAMIC):
        for direction in c53.DIRECTIONS:
            neighbour = add(target, direction)
            if neighbour in occupied_dynamic:
                continue
            scaffold.setdefault(neighbour, FRAME)
    overlap = set(scaffold) & occupied_dynamic
    if overlap:
        raise ValueError(("scaffold-dynamic-overlap", tuple(sorted(overlap))[:5]))
    return scaffold


SCAFFOLD = build_scaffold()


def base_certificates():
    certificates = {}
    old = c171.FULL_RAW
    c171.FULL_RAW = c178.FULL_RAW
    try:
        for word in WORDS:
            _sources, _outputs, initial, expected, exits = base_parts(word)
            certificate = c171.causal_certificate(initial, expected, exits)
            if not certificate["ok"]:
                raise ValueError(("base-certificate-failed", word, certificate))
            certificates[word] = certificate
    finally:
        c171.FULL_RAW = old
    return certificates


BASE_CERTIFICATES = base_certificates()


def compile_table():
    values: dict[c53.Signature, set[str]] = defaultdict(set)
    tags: dict[c53.Signature, set[str]] = defaultdict(set)
    for word in WORDS:
        _sources, _outputs, initial, base_expected, _exits = base_parts(word)
        augmented_initial = merge_records(initial, SCAFFOLD)
        extension = extension_expected(word)
        all_expected = {**base_expected, **extension}

        # Preserve any recurrent firing signature modified by the egress caps
        # or retained cable furniture.  Only genuinely changed rows are added.
        for target, parents in BASE_CERTIFICATES[word]["dependencies"].items():
            premise = {
                neighbour: augmented_initial[neighbour]
                for direction in c53.DIRECTIONS
                if (neighbour := add(target, direction)) in augmented_initial
            }
            premise.update({
                parent: base_expected[parent]
                for parent in parents
            })
            raw = c53.local_signature(premise, target)
            wanted = frozenset((base_expected[target],))
            if c178.FULL_RAW.get(raw) == wanted:
                continue
            signature = c53.canonical_signature(raw)
            values[signature].add(base_expected[target])
            tags[signature].add("recurrent-adapter")

        for target, parents in EXTENSION_PARENTS.items():
            premise = {
                neighbour: augmented_initial[neighbour]
                for direction in c53.DIRECTIONS
                if (neighbour := add(target, direction)) in augmented_initial
            }
            premise.update({
                parent: all_expected[parent]
                for parent in parents
            })
            raw = c53.local_signature(premise, target)
            wanted = frozenset((extension[target],))
            if c178.FULL_RAW.get(raw) == wanted:
                continue
            signature = c53.canonical_signature(raw)
            values[signature].add(extension[target])
            if target in TERMINAL_BITS:
                tags[signature].add("terminal-egress")
            elif target in STATUS_PORTS:
                tags[signature].add("status-conversion")
            elif target in CONSUMER_SITES:
                tags[signature].add("consumer")
            elif NODE_KIND.get(target) == "status":
                tags[signature].add("status-tree")
            else:
                tags[signature].add("cable-adapter")
    return values, tags


COMPILED_VALUES, ROW_TAGS = compile_table()
COMPILE_CONFLICTS = {
    signature: frozenset(outputs)
    for signature, outputs in COMPILED_VALUES.items()
    if len(outputs) != 1
}
COMPILED_TABLE = {
    signature: next(iter(outputs))
    for signature, outputs in COMPILED_VALUES.items()
    if len(outputs) == 1
}
NEW_RAW = cell.merge_raw(*(
    cell.raw_orbit(signature, output)
    for signature, output in COMPILED_TABLE.items()
))
NEW_RAW_CONFLICTS = {
    signature: outputs
    for signature, outputs in NEW_RAW.items()
    if len(outputs) != 1
}
FULL_RAW = cell.merge_raw(c178.FULL_RAW, NEW_RAW)
FULL_CONFLICTS = {
    signature: outputs
    for signature, outputs in FULL_RAW.items()
    if len(outputs) != 1
}
BASE_OVERLAP = set(c178.FULL_RAW) & set(NEW_RAW)


def apparatus(word: tuple[int, ...]):
    source_lanes, output_lanes, initial, base_expected, exits = base_parts(word)
    extension = extension_expected(word)
    overlap = (
        (set(initial) & set(SCAFFOLD))
        | (set(base_expected) & set(SCAFFOLD))
        | (set(exits) & set(SCAFFOLD))
        | (set(base_expected) & set(extension))
    )
    if overlap:
        raise ValueError(("apparatus-overlap", tuple(sorted(overlap))[:5]))
    return (
        merge_records(initial, SCAFFOLD),
        {**base_expected, **extension},
        exits,
        source_lanes,
        output_lanes,
        base_expected,
        extension,
    )


def ownership(output_lanes) -> dict[Coord, int]:
    owners = {}
    for lane, records in enumerate(output_lanes):
        for site in records:
            prior = owners.setdefault(site, lane)
            if prior != lane:
                raise ValueError(("owner-conflict", site, prior, lane))
    return owners


def causal_ancestry(certificate, output_lanes):
    base_owner = ownership(output_lanes)
    ancestry: dict[Coord, frozenset[int]] = {}
    remaining = set(certificate["dependencies"])
    while remaining:
        ready = {
            target
            for target in remaining
            if certificate["dependencies"][target] <= ancestry.keys()
        }
        if not ready:
            raise RuntimeError(("ancestry-cycle", len(remaining)))
        for target in ready:
            if target in base_owner:
                value = frozenset((base_owner[target],))
            else:
                value = frozenset().union(*(
                    ancestry[parent]
                    for parent in certificate["dependencies"][target]
                ))
            ancestry[target] = value
        remaining -= ready
    return ancestry


def intended_extension_ancestry() -> dict[Coord, frozenset[int]]:
    ancestry = {
        endpoint: frozenset((lane,))
        for lane, endpoint in enumerate(ENDPOINTS)
    }
    remaining = set(EXTENSION_DYNAMIC)
    while remaining:
        ready = {
            target
            for target in remaining
            if EXTENSION_PARENTS[target] <= ancestry.keys()
        }
        if not ready:
            raise RuntimeError(("intended-ancestry-cycle", len(remaining)))
        for target in ready:
            ancestry[target] = frozenset().union(*(
                ancestry[parent]
                for parent in EXTENSION_PARENTS[target]
            ))
        remaining -= ready
    return {
        target: ancestry[target]
        for target in EXTENSION_DYNAMIC
    }


INTENDED_ANCESTRY = intended_extension_ancestry()


def enabled(records: RoleMap):
    return {
        target: FULL_RAW[signature]
        for target in c53.open_candidates(records)
        if (signature := c53.local_signature(records, target)) in FULL_RAW
    }


def local_endpoint_deletion(word: tuple[int, ...]):
    _sources, _outputs, initial, base_expected, _exits = base_parts(word)
    augmented_initial = merge_records(initial, SCAFFOLD)
    extension = extension_expected(word)
    failures = []
    attempts = 0
    for lane, (endpoint, stem) in enumerate(zip(ENDPOINTS, STEM_PATHS, strict=True)):
        target = stem[1]
        premise = {
            neighbour: augmented_initial[neighbour]
            for direction in c53.DIRECTIONS
            if (neighbour := add(target, direction)) in augmented_initial
        }
        premise[endpoint] = base_expected[endpoint]
        wanted = frozenset((extension[target],))
        baseline = FULL_RAW.get(c53.local_signature(premise, target))
        premise.pop(endpoint)
        after = FULL_RAW.get(c53.local_signature(premise, target))
        attempts += 1
        if baseline != wanted or after is not None:
            failures.append((lane, target, baseline, wanted, after))
    return attempts, tuple(failures)


def extension_closure(
    records: RoleMap,
    wanted: RoleMap,
    *,
    order: str,
):
    records = dict(records)
    formed = set()
    wrong = []
    maximum = 0
    actual = enabled(records)
    while True:
        live = {
            site: roles
            for site, roles in actual.items()
            if site not in records and site in EXTENSION_DYNAMIC
        }
        bad = {
            site: roles
            for site, roles in live.items()
            if wanted.get(site) != next(iter(roles))
        }
        if bad:
            wrong.append((len(formed), bad))
            break
        futures = tuple(site for site in live if site in wanted)
        maximum = max(maximum, len(futures))
        if not futures:
            break
        target = min(futures) if order == "min" else max(futures)
        records[target] = wanted[target]
        formed.add(target)
        c171.refresh_after_append(records, actual, target)
    return {
        "formed": frozenset(formed),
        "wrong": tuple(wrong),
        "maximum": maximum,
    }


def endpoint_absence_controls(word: tuple[int, ...]):
    _sources, _outputs, initial, base_expected, _exits = base_parts(word)
    complete = merge_records(initial, base_expected, SCAFFOLD)
    extension = extension_expected(word)
    failures = []
    attempts = 0
    for lane, endpoint in enumerate(ENDPOINTS):
        records = dict(complete)
        records.pop(endpoint)
        wanted_sites = frozenset(
            site
            for site, ancestry in INTENDED_ANCESTRY.items()
            if lane not in ancestry
        )
        wanted = {
            site: extension[site]
            for site in wanted_sites
        }
        minimum = extension_closure(records, wanted, order="min")
        maximum = extension_closure(records, wanted, order="max")
        attempts += 1
        if (
            minimum["wrong"]
            or maximum["wrong"]
            or minimum["formed"] != wanted_sites
            or maximum["formed"] != wanted_sites
            or JFINAL in minimum["formed"]
            or set(CONSUMER_SITES) & set(minimum["formed"])
        ):
            failures.append((lane, len(wanted_sites), minimum, maximum))
    return attempts, tuple(failures)


def transformed(records, rotation, shift: Coord):
    return c53.transform_records(records, rotation, shift)


def main() -> int:
    global PASS, FAIL
    PASS = FAIL = 0
    old_full_raw = c171.FULL_RAW
    c171.FULL_RAW = FULL_RAW
    try:
        print("AUTHORITY, RETAINED GRAMMAR, AND EXACT PRICE")
        check("Cycle-190 review note exists", NOTE.is_file())
        base_roles = {
            role
            for signature, outputs in c178.FULL_RAW.items()
            for _direction, role in signature
        } | {
            role
            for outputs in c178.FULL_RAW.values()
            for role in outputs
        }
        check(
            "the retained typed cable rows are reused literally",
            not (
                set(cable.CABLE_RAW)
                - set(c178.FULL_RAW)
            )
            and all(
                c178.FULL_RAW[signature] == values
                for signature, values in cable.CABLE_RAW.items()
            ),
            (
                len(cable.CABLE_RAW),
                len(set(cable.CABLE_RAW) - set(c178.FULL_RAW)),
            ),
        )
        check(
            "exactly two fresh roles are priced and MEMBER5 is never supplied",
            NEW_ROLES.isdisjoint(base_roles)
            and MEMBER5 not in SCAFFOLD.values()
            and EGRESS_CAP in SCAFFOLD.values(),
            (
                NEW_ROLES & base_roles,
                Counter(SCAFFOLD.values()),
            ),
        )
        check(
            "the compiled delta and merged local law are deterministic",
            not COMPILE_CONFLICTS
            and not NEW_RAW_CONFLICTS
            and not FULL_CONFLICTS
            and not BASE_OVERLAP
            and all(len(outputs) == 1 for outputs in FULL_RAW.values()),
            (
                len(COMPILED_TABLE),
                len(NEW_RAW),
                len(FULL_RAW),
                len(COMPILE_CONFLICTS),
                len(NEW_RAW_CONFLICTS),
                len(FULL_CONFLICTS),
                len(BASE_OVERLAP),
            ),
        )

        print("\nGEOMETRY AND VALUE-NEUTRAL BINDING")
        unintended = tuple(
            (left, right)
            for left in EXTENSION_DYNAMIC
            for direction in c53.DIRECTIONS
            if (right := add(left, direction)) in EXTENSION_DYNAMIC
            and left < right
            and left not in EXTENSION_PARENTS[right]
            and right not in EXTENSION_PARENTS[left]
        )
        check(
            "every extension edge is local with no unintended dynamic adjacency",
            all(
                all(manhattan(target, parent) == 1 for parent in parents)
                for target, parents in EXTENSION_PARENTS.items()
            )
            and not unintended,
            (
                len(EXTENSION_DYNAMIC),
                len(SCAFFOLD),
                unintended[:3],
            ),
        )
        first_cross = {
            site
            for site, ancestry in INTENDED_ANCESTRY.items()
            if len(ancestry) > 1
            and all(
                len(INTENDED_ANCESTRY.get(parent, frozenset())) <= 1
                for parent in EXTENSION_PARENTS[site]
            )
        }
        check(
            "first cross-bit ancestry occurs only at J01 and J23",
            first_cross == {J01, J23}
            and INTENDED_ANCESTRY[JFINAL] == frozenset(range(5))
            and all(
                INTENDED_ANCESTRY[site] == frozenset(range(5))
                for site in CONSUMER_SITES
            ),
            (
                first_cross,
                INTENDED_ANCESTRY[JFINAL],
            ),
        )
        probe_word = (1, 0, 1, 0, 1)
        probe_extension = extension_expected(probe_word)
        check(
            "the final patch is five ordered literals, never a 32-valued payload",
            tuple(
                probe_extension[site]
                for site in CONSUMER_SITES
            ) == tuple(c178.bit_role(bit) for bit in probe_word)
            and {
                probe_extension[site]
                for site in CUSTOM_DYNAMIC
                if NODE_KIND[site] == "status"
            } == {MEMBER5}
            and {
                probe_extension[site]
                for site in EXTENSION_DYNAMIC
            } <= {H0, H1, MEMBER5},
            (
                CONSUMER_SITES,
                tuple(probe_extension[site] for site in CONSUMER_SITES),
            ),
        )

        print("\nALL-32 EXACT FULL-HISTORY CLOSURE AND SCHEDULE CONFLUENCE")
        certificates = {}
        failures = {}
        shapes = Counter()
        ancestry_failures = []
        for word in WORDS:
            (
                initial,
                expected,
                exits,
                _source_lanes,
                output_lanes,
                _base_expected,
                _extension,
            ) = apparatus(word)
            certificate = c171.causal_certificate(initial, expected, exits)
            certificates[word] = certificate
            if not certificate["ok"]:
                failures[word] = certificate
                continue
            shapes[(
                certificate["minimum"]["states"],
                certificate["edge_checks"]["edges"],
                certificate["minimum"]["max_frontier"],
                certificate["maximum"]["max_frontier"],
                len(certificate["unordered"]),
                len(certificate["minimum"]["terminal"]),
            )] += 1
            ancestry = causal_ancestry(certificate, output_lanes)
            observed = {
                site: ancestry[site]
                for site in EXTENSION_DYNAMIC
            }
            if observed != INTENDED_ANCESTRY:
                ancestry_failures.append((
                    word,
                    tuple(
                        (site, observed.get(site), wanted)
                        for site, wanted in INTENDED_ANCESTRY.items()
                        if observed.get(site) != wanted
                    )[:3],
                ))
        check(
            "all 32 words have exact full-history closure under both schedules",
            not failures
            and len(certificates) == 32
            and all(
                certificate["minimum"]["ok"]
                and certificate["maximum"]["ok"]
                and not certificate["unordered"]
                and not certificate["edge_checks"]["signature_failures"]
                and not certificate["edge_checks"]["deletion_failures"]
                for certificate in certificates.values()
            ),
            (
                shapes,
                tuple(
                    (
                        word,
                        certificate.get("discovery", {}).get("error"),
                        certificate.get("minimum", {}).get("error"),
                        certificate.get("maximum", {}).get("error"),
                    )
                    for word, certificate in failures.items()
                )[:2],
            ),
        )
        check(
            "all 32 histories realize exactly the intended ancestry",
            not ancestry_failures,
            tuple(ancestry_failures)[:2],
        )

        print("\nALL-24 PROPER-CUBIC COVARIANCE OF THE NEW EGRESS")
        covariance_failures = []
        covariance_shapes = Counter()
        if probe_word in certificates and certificates[probe_word]["ok"]:
            (
                _source_lanes,
                _output_lanes,
                base_initial,
                base_expected,
                exits,
            ) = base_parts(probe_word)
            # Cycle-178 does not claim arbitrary rotated-schedule confluence.
            # Freeze its completed recurrent boundary so this all-24 gate asks
            # exactly whether the new egress/tree/consumer construction is
            # covariant, without silently inheriting a stronger predecessor
            # theorem.
            initial = merge_records(base_initial, base_expected, SCAFFOLD)
            expected = extension_expected(probe_word)
            for rotation_index, rotation in enumerate(c53.ROTATIONS):
                shift = (701 + rotation_index, -907, 1103)
                certificate = c171.causal_certificate(
                    transformed(initial, rotation, shift),
                    transformed(expected, rotation, shift),
                    transformed(exits, rotation, shift),
                )
                if not certificate["ok"]:
                    covariance_failures.append((rotation_index, certificate))
                    continue
                covariance_shapes[(
                    certificate["minimum"]["states"],
                    certificate["edge_checks"]["edges"],
                    certificate["minimum"]["max_frontier"],
                    certificate["maximum"]["max_frontier"],
                    len(certificate["unordered"]),
                )] += 1
        else:
            covariance_failures.append(("unrotated-probe-failed",))
        check(
            "the completed-boundary egress closes in all 24 proper-cubic orientations",
            not covariance_failures
            and sum(covariance_shapes.values()) == 24
            and {
                (states, edges, unordered)
                for (
                    states,
                    edges,
                    _minimum_frontier,
                    _maximum_frontier,
                    unordered,
                ) in covariance_shapes
            } == {(769, 772, 0)}
            and Counter(
                (
                    minimum_frontier,
                    maximum_frontier,
                )
                for (
                    _states,
                    _edges,
                    minimum_frontier,
                    maximum_frontier,
                    _unordered,
                ), count in covariance_shapes.items()
                for _ in range(count)
            ) == {
                (10, 6): 4,
                (6, 6): 16,
                (6, 10): 4,
            },
            (covariance_shapes, tuple(covariance_failures)[:1]),
        )

        # Disclose the exact inherited wall rather than mislabelling it as a
        # Cycle-190 failure or silently widening this cycle into a repair of
        # the retained recurrent carrier.
        inherited_profile = Counter()
        (
            _source_lanes,
            _output_lanes,
            inherited_initial,
            inherited_expected,
            inherited_exits,
        ) = base_parts(probe_word)
        c171.FULL_RAW = c178.FULL_RAW
        try:
            for rotation_index, rotation in enumerate(c53.ROTATIONS):
                shift = (1701 + rotation_index, -1907, 2103)
                certificate = c171.causal_certificate(
                    transformed(inherited_initial, rotation, shift),
                    transformed(inherited_expected, rotation, shift),
                    transformed(inherited_exits, rotation, shift),
                )
                if certificate["ok"]:
                    inherited_profile["pass"] += 1
                elif not certificate["discovery"]["ok"]:
                    inherited_profile["discovery-alias"] += 1
                else:
                    inherited_profile["replay-alias"] += 1
        finally:
            c171.FULL_RAW = FULL_RAW
        check(
            "whole-history rotated schedule sensitivity is exactly inherited from Cycle-178",
            inherited_profile == {
                "pass": 7,
                "discovery-alias": 9,
                "replay-alias": 8,
            },
            inherited_profile,
        )

        print("\n320 ENDPOINT DELETION / ABSENCE CONTROLS")
        deletion_attempts = 0
        absence_attempts = 0
        deletion_failures = []
        absence_failures = []
        for word in WORDS:
            attempts, failures_here = local_endpoint_deletion(word)
            deletion_attempts += attempts
            deletion_failures.extend((word, item) for item in failures_here)
            attempts, failures_here = endpoint_absence_controls(word)
            absence_attempts += attempts
            absence_failures.extend((word, item) for item in failures_here)
        check(
            "all 160 local endpoint-edge deletions are exact",
            deletion_attempts == 32 * 5
            and not deletion_failures,
            (deletion_attempts, tuple(deletion_failures)[:2]),
        )
        check(
            "all 160 complete-boundary endpoint absences are exact",
            absence_attempts == 32 * 5
            and not absence_failures,
            (absence_attempts, tuple(absence_failures)[:2]),
        )

        print("\nACCOUNTING")
        tag_counts = Counter(
            tag
            for tags in ROW_TAGS.values()
            for tag in tags
        )
        print("NEW_ROLES", tuple(sorted(NEW_ROLES)))
        print("SUPPLIED_RECORDS", len(SCAFFOLD), Counter(SCAFFOLD.values()))
        print("EXTENSION_DYNAMIC_RECORDS", len(EXTENSION_DYNAMIC))
        print("CABLE_DYNAMIC_RECORDS", len(CABLE_DYNAMIC))
        print("TERMINAL_BIT_RECORDS", len(TERMINAL_BITS))
        print("STATUS_DYNAMIC_RECORDS", sum(
            NODE_KIND[site] == "status" for site in CUSTOM_DYNAMIC
        ))
        print("CONSUMER_RECORDS", len(CONSUMER_SITES))
        print("COMPILED_CANONICAL_ROWS", len(COMPILED_TABLE), tag_counts)
        print("NEW_RAW_ROWS", len(NEW_RAW))
        print("FULL_RAW_ROWS", len(FULL_RAW))
        print("ALL32_SHAPES", shapes)
        print("COVARIANCE_SHAPES", covariance_shapes)
        print("J01", J01, "J23", J23, "J0123", J0123, "JFINAL", JFINAL)
        print("CONSUMER_SITES", CONSUMER_SITES)
        print("PASS", PASS, "FAIL", FAIL)
        print(
            "RESULT",
            "BARE_METAL_LITERAL_EGRESS_BIND"
            if FAIL == 0
            else "CYCLE190_OPEN",
        )
        return int(FAIL != 0)
    finally:
        c171.FULL_RAW = old_full_raw


if __name__ == "__main__":
    raise SystemExit(main())
