#!/usr/bin/env python3
"""Deterministic rebuild + verification of the 2026-08-05 unledgered science index.

Contract
--------
The shipped index `docs/repo/science_census_unledgered_index_2026-08-05.json`
carries its own inputs: a flat record list (`items`) in which every record
names its provenance (path, stratum, immutable ref, blob where applicable,
pull request number), plus fixed prose constants (authority, method, generated
date, coverage-gap texts, stratum descriptions) and three declared survey
constants that are NOT derivable from the records
(`docs_md_at_survey_tip`, `gated_docs_md_at_survey_tip`,
`ledger_rows_at_survey_tip` — point-in-time survey-walk observations).

This script rebuilds the index deterministically from those declared inputs:

1. re-verifies every record's existence against the git object store
   (`<ref>:<path>` must resolve to a blob; a record-level `blob` field, when
   present, must match exactly; refs marked UNRESOLVED are tallied, never
   silently passed);
2. re-derives every aggregate (per-stratum counts, item total, unique-path
   total, cross-stratum overlap count, stratum count) from the records alone;
3. re-emits the full index in canonical serialization (sorted keys, two-space
   indent, ASCII escapes, items sorted by (stratum, path), trailing newline);
4. requires the shipped file to match a PINNED whole-index sha256 (so any
   byte drift, including pass-through fields the rebuild copies verbatim,
   fails closed) and the regenerated bytes to match the shipped file
   byte-exactly;
5. writes a receipt JSON (inputs consumed, verification tallies, derived
   counts, sha256 of shipped and regenerated index) to
   `logs/runner-cache/census_index_rebuild_2026_08_05.json`.

Exit code 0 only if every record verifies and the rebuild is byte-exact.
Any verification failure or byte drift exits 1 (fail closed). The script is
read-only over `docs/`; its only write is the receipt in `logs/runner-cache/`.

Scope note: this reproduces and checks everything derivable from the index
itself. Survey-walk figures whose inputs were never shipped (the 2,914-ref
walk, tip-file splits, ledger-history statistics) are carried as declared
constants and listed as such in the receipt; this script does not re-run the
original walk.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / "docs" / "repo" / "science_census_unledgered_index_2026-08-05.json"

# Whole-index fail-closed pin: ANY byte drift in the shipped index -- including
# pass-through fields the rebuild copies verbatim (authority, method, prose,
# generated date, declared survey constants) -- fails this check. Updating the
# index deliberately requires updating this pin in the same commit.
EXPECTED_INDEX_SHA256 = "40f2878275e84ca53e905cfdf214ff5e44dfb8e9b144ac9a36743193b843e31b"
RECEIPT_PATH = REPO_ROOT / "logs" / "runner-cache" / "census_index_rebuild_2026_08_05.json"

# Survey-walk observations carried in totals but not derivable from the
# record list; every other total is recomputed below.
DECLARED_SURVEY_CONSTANTS = (
    "docs_md_at_survey_tip",
    "gated_docs_md_at_survey_tip",
    "ledger_rows_at_survey_tip",
)

HEX40 = set("0123456789abcdef")


def canonical_bytes(document: dict) -> bytes:
    """The one serialization the shipped index must equal, byte for byte."""
    return (json.dumps(document, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("utf-8")


def is_commitish(ref) -> bool:
    return isinstance(ref, str) and len(ref) == 40 and set(ref) <= HEX40


def batch_resolve(specs):
    """Resolve `<ref>:<path>` specs through one `git cat-file --batch-check`.

    Returns a list of (object_sha or None, object_type or None) per spec.
    """
    if not specs:
        return []
    proc = subprocess.run(
        ["git", "cat-file", "--batch-check"],
        input="\n".join(specs),
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
        check=False,
    )
    results = []
    for line in proc.stdout.strip("\n").split("\n"):
        parts = line.split()
        if len(parts) == 3 and parts[1] in ("blob", "tree", "commit", "tag"):
            results.append((parts[0], parts[1]))
        else:
            results.append((None, None))
    if len(results) != len(specs):
        raise RuntimeError(
            f"git cat-file --batch-check returned {len(results)} lines for {len(specs)} specs"
        )
    return results


def main() -> int:
    shipped_raw = INDEX_PATH.read_bytes()
    shipped_sha256 = hashlib.sha256(shipped_raw).hexdigest()
    if shipped_sha256 != EXPECTED_INDEX_SHA256:
        failures.append(
            "shipped index sha256 does not match the pinned EXPECTED_INDEX_SHA256 "
            f"(pinned {EXPECTED_INDEX_SHA256}, actual {shipped_sha256}); any byte "
            "drift, including pass-through fields, fails closed"
        )
    index = json.loads(shipped_raw)

    items = index["items"]
    failures = []

    # --- 1. Per-record existence verification against git -------------------
    resolvable = []  # (record, spec)
    unresolved_refs = 0
    null_refs = 0
    for record in items:
        ref = record.get("ref")
        if ref is None:
            null_refs += 1
            failures.append(f"record has null ref: {record.get('stratum')}:{record.get('path')}")
            continue
        if ref == "UNRESOLVED":
            unresolved_refs += 1
            if not record.get("unresolved_reason"):
                failures.append(
                    f"UNRESOLVED ref without unresolved_reason: {record.get('path')}"
                )
            continue
        if not is_commitish(ref):
            failures.append(f"malformed ref {ref!r} on {record.get('path')}")
            continue
        resolvable.append((record, f"{ref}:{record['path']}"))

    resolved = batch_resolve([spec for _, spec in resolvable])
    verified_blob_matches = 0
    verified_existence = 0
    for (record, spec), (obj_sha, obj_type) in zip(resolvable, resolved):
        if obj_sha is None or obj_type != "blob":
            failures.append(f"does not resolve to a blob: {spec}")
            continue
        verified_existence += 1
        declared_blob = record.get("blob")
        if declared_blob is not None:
            if declared_blob == obj_sha:
                verified_blob_matches += 1
            else:
                failures.append(
                    f"blob mismatch at {spec}: declared {declared_blob}, git has {obj_sha}"
                )

    # --- 2. Re-derive every aggregate from the records ----------------------
    stratum_counts = Counter(record["stratum"] for record in items)
    paths_by_name = defaultdict(set)
    for record in items:
        paths_by_name[record["path"]].add(record["stratum"])
    unique_paths = len(paths_by_name)
    overlap_paths = sum(1 for strata in paths_by_name.values() if len(strata) > 1)

    rebuilt = {
        "authority": index["authority"],
        "coverage_gaps": index["coverage_gaps"],
        "generated": index["generated"],
        "items": sorted(items, key=lambda r: (r["stratum"], r["path"])),
        "method": index["method"],
        "strata": [
            {**stratum_block, "count": stratum_counts[stratum_block["stratum"]]}
            for stratum_block in index["strata"]
        ],
        "totals": {
            **{k: index["totals"][k] for k in DECLARED_SURVEY_CONSTANTS},
            "cross_stratum_overlap_paths": overlap_paths,
            "items": len(items),
            "strata": len(index["strata"]),
            "unique_paths": unique_paths,
        },
    }

    declared_strata = {block["stratum"] for block in index["strata"]}
    for stratum in stratum_counts:
        if stratum not in declared_strata:
            failures.append(f"record stratum not declared in strata block: {stratum}")

    rebuilt_raw = canonical_bytes(rebuilt)
    rebuilt_sha256 = hashlib.sha256(rebuilt_raw).hexdigest()
    byte_exact = rebuilt_raw == shipped_raw
    if not byte_exact:
        failures.append(
            "regenerated index is not byte-identical to the shipped index "
            f"(shipped {shipped_sha256}, regenerated {rebuilt_sha256})"
        )

    # --- 3. Receipt ----------------------------------------------------------
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=REPO_ROOT, check=False
    ).stdout.strip() or None
    receipt = {
        "byte_exact_match": byte_exact,
        "declared_survey_constants": {
            k: index["totals"][k] for k in DECLARED_SURVEY_CONSTANTS
        },
        "derived_counts": {
            "cross_stratum_overlap_paths": overlap_paths,
            "items": len(items),
            "per_stratum": dict(sorted(stratum_counts.items())),
            "strata": len(index["strata"]),
            "unique_paths": unique_paths,
        },
        "failures": failures,
        "generator": "scripts/census_index_rebuild_2026_08_05.py",
        "inputs_consumed": {
            "git_head_at_run": head,
            "git_object_store": "resolved via git cat-file --batch-check",
            "index_path": str(INDEX_PATH.relative_to(REPO_ROOT)),
            "index_sha256": shipped_sha256,
        },
        "regenerated_index_sha256": rebuilt_sha256,
        "run_utc": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "verification": {
            "blob_fields_checked_and_matching": verified_blob_matches,
            "null_ref_records": null_refs,
            "records_resolving_to_git_blob": verified_existence,
            "records_total": len(items),
            "unresolved_ref_records": unresolved_refs,
        },
    }
    RECEIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    RECEIPT_PATH.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n")

    print(f"records: {len(items)}  unique_paths: {unique_paths}  overlaps: {overlap_paths}")
    print(f"resolved to git blobs: {verified_existence}  blob fields matching: {verified_blob_matches}")
    print(f"unresolved refs (disclosed): {unresolved_refs}  null refs: {null_refs}")
    print(f"shipped sha256:     {shipped_sha256}")
    print(f"regenerated sha256: {rebuilt_sha256}")
    print(f"byte-exact match:   {byte_exact}")
    print(f"receipt: {RECEIPT_PATH.relative_to(REPO_ROOT)}")
    if failures:
        print(f"FAIL ({len(failures)} problems):")
        for failure in failures[:50]:
            print(f"  - {failure}")
        return 1
    print("PASS: index verified and reproduced byte-exactly from its declared inputs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
