#!/usr/bin/env python3
"""
b-tau Relation Probe -- b-tau Yukawa unification + 1-loop SM RGE running.

Authority role
--------------
Source-note proposal -- audit verdict and downstream status set only by the
independent audit lane. This runner does NOT set or predict an audit outcome.

Purpose
-------
Test the claim (made by a scale-axis agent) that b-tau Yukawa unification
(y_b -> y_tau at a GUT scale) is a "genuine structural relation tying m_b and
m_tau" inside the Cl(3)/Z^3 framework, thereby reducing the free-scale count
by one.

Two independent questions:

  (A) QUANTITATIVE.  Impose y_b(M_GUT) = y_tau(M_GUT) (the SU(5) minimal-Higgs
      boundary).  Run BOTH down to the EW / m_b scale with the 1-loop SM RGEs.
      The color term -8 g3^2 sits in beta(y_b) but NOT in beta(y_tau); this
      drives the splitting and enhances y_b at low scale, so m_b/m_tau > 1.
      Predict m_b/m_tau and compare with PDG (m_b(m_b)_MSbar ~ 4.18 GeV,
      m_tau ~ 1.777 GeV, ratio ~ 2.35).  Be honest: SM-only running OVERSHOOTS
      (the textbook SUSY-vs-SM b-tau issue); exact agreement wants either SUSY
      sparticle thresholds (tan-beta enhancement absorbed) or a tuned alpha_s /
      GUT scale.

  (B) STRUCTURAL.  Is the y_b = y_tau boundary DERIVED by the framework, or
      ASSUMED (imported from the SU(5) GUT relation)?  The framework's own
      ledger answers this:
        * SU5_EMBEDDING_FROM_GRAPH_FIRST_SURFACE_THEOREM_NOTE_2026-05-07 derives
          SU(5) embedding *consistency* + Y_GUT = sqrt(3/5) Y_SM, but its
          Section 2 EXPLICITLY states it does NOT claim coupling unification,
          does NOT derive the GUT scale, and makes no Yukawa-sector claim.
        * The Yukawa sector itself is a wall of bounded obstructions /
          no-go's (A3_ROUTE1_HIGGS_YUKAWA..., CHARGED_LEPTON_DIRECT_WARD_FREE
          _YUKAWA_NO_GO, ...): the framework cannot even break C_3 to get a
          hierarchical down-type Yukawa, let alone fix y_b = y_tau at a scale.
        * YT_BOTTOM_YUKAWA_RETENTION_ANALYSIS_NOTE_2026-04-18 already records
          that a *flat* Yukawa-unification BC (from Block 6 uniformity, at
          M_Pl) is "empirically falsified on m_b by 33x".

      Conclusion: the y_b = y_tau boundary is an IMPORTED GUT ASSUMPTION, not a
      framework derivation.  The down-lepton sector mass relation it would
      provide is NOT generated by the retained surface; so it does NOT honestly
      reduce the framework free-scale count.

Honest verdict (one of):
  GENUINE-FRAMEWORK-RELATION / IMPORTED-GUT-ASSUMPTION / GAUGE-GENERIC-BUT-BOUNDARY-ASSUMED

Method note
-----------
The RGEs below are the *standard SM* 1-loop renormalization-group equations
(Machacek-Vaughn / textbook).  They are NOT framework content -- they are the
imported running machinery, used here only to quantify what the imported b-tau
boundary would predict.  PDG values appear only as falsifiability anchors in
the comparison, NEVER as inputs to the structural verdict.

No external numerical fit is performed: gauge couplings are seeded from
standard EW-scale PDG values and run UP to find the unification-ish scale; the
Yukawa ratio is then run DOWN from that scale under the unification BC.  This is
deliberately the *most charitable* SM-only test of the imported boundary.

Stdlib only (math).  Fixed-step RK4 integration in t = ln(mu/GeV).
"""

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTE_PATH = ROOT / "docs" / "B_TAU_RELATION_PROBE_2026-06-05.md"

PASS = 0
FAIL = 0


def check(label, ok, detail=""):
    global PASS, FAIL
    tag = "PASS" if ok else "FAIL"
    if ok:
        PASS += 1
    else:
        FAIL += 1
    print(f"  [{tag}] {label}  ({detail})")


# ----------------------------------------------------------------------------
# Standard-Model 1-loop RGE machinery (IMPORTED running; not framework content)
# ----------------------------------------------------------------------------
# Conventions:
#   t = ln(mu/GeV);  d X / d t = beta_X / (16 pi^2).
#   g1 is GUT-normalized: g1^2 = (5/3) g_Y^2  (so g1 = g2 = g3 at SU(5)).
#   1-loop gauge: d g_i/dt = b_i g_i^3/(16 pi^2),  b = (41/10, -19/6, -7).
#   1-loop top/bottom/tau Yukawa (3rd-gen dominant; lighter Yukawas dropped):
#
#   16 pi^2 dy_t/dt = y_t ( 9/2 y_t^2 + 3/2 y_b^2 + y_tau^2
#                           - (17/20 g1^2 + 9/4 g2^2 + 8 g3^2) )
#   16 pi^2 dy_b/dt = y_b ( 9/2 y_b^2 + 3/2 y_t^2 + y_tau^2
#                           - (1/4 g1^2 + 9/4 g2^2 + 8 g3^2) )
#   16 pi^2 dy_tau/dt = y_tau ( 5/2 y_tau^2 + 3 y_t^2 + 3 y_b^2
#                           - (9/4 g1^2 + 9/4 g2^2) )       <-- NO 8 g3^2 term
#
# The asymmetry that splits y_b from y_tau is precisely the color coupling
# 8 g3^2 in dy_b/dt that is ABSENT in dy_tau/dt (leptons are color-singlets).

INV16PI2 = 1.0 / (16.0 * math.pi**2)
B_GAUGE = (41.0 / 10.0, -19.0 / 6.0, -7.0)  # SM 1-loop, GUT-normalized g1


def derivs(y):
    """y = [g1, g2, g3, yt, yb, ytau];  returns dy/dt (1-loop SM)."""
    g1, g2, g3, yt, yb, ytau = y
    g1sq, g2sq, g3sq = g1 * g1, g2 * g2, g3 * g3
    yt2, yb2, ytau2 = yt * yt, yb * yb, ytau * ytau

    dg1 = B_GAUGE[0] * g1 * g1sq * INV16PI2
    dg2 = B_GAUGE[1] * g2 * g2sq * INV16PI2
    dg3 = B_GAUGE[2] * g3 * g3sq * INV16PI2

    dyt = yt * (4.5 * yt2 + 1.5 * yb2 + ytau2
                - (17.0 / 20.0 * g1sq + 2.25 * g2sq + 8.0 * g3sq)) * INV16PI2
    dyb = yb * (4.5 * yb2 + 1.5 * yt2 + ytau2
                - (0.25 * g1sq + 2.25 * g2sq + 8.0 * g3sq)) * INV16PI2
    dytau = ytau * (2.5 * ytau2 + 3.0 * yt2 + 3.0 * yb2
                    - (2.25 * g1sq + 2.25 * g2sq)) * INV16PI2
    return [dg1, dg2, dg3, dyt, dyb, dytau]


def rk4_step(y, h):
    k1 = derivs(y)
    y2 = [yi + 0.5 * h * ki for yi, ki in zip(y, k1)]
    k2 = derivs(y2)
    y3 = [yi + 0.5 * h * ki for yi, ki in zip(y, k2)]
    k3 = derivs(y3)
    y4 = [yi + h * ki for yi, ki in zip(y, k3)]
    k4 = derivs(y4)
    return [yi + (h / 6.0) * (a + 2 * b + 2 * c + d)
            for yi, a, b, c, d in zip(y, k1, k2, k3, k4)]


def integrate(y0, t0, t1, nsteps):
    h = (t1 - t0) / nsteps
    y = list(y0)
    for _ in range(nsteps):
        y = rk4_step(y, h)
    return y


# ----------------------------------------------------------------------------
# Inputs (PDG-ish EW-scale seeds for the IMPORTED running; falsifiability only)
# ----------------------------------------------------------------------------
MZ = 91.1876
# Gauge couplings at M_Z (PDG; alpha_em, sin^2 theta_W, alpha_s).
ALPHA_EM_INV = 127.95
SIN2W = 0.23122
ALPHA_S_MZ = 0.1181

alpha_em = 1.0 / ALPHA_EM_INV
alpha2 = alpha_em / SIN2W                # SU(2)_L
alpha1_Y = alpha_em / (1.0 - SIN2W)      # U(1)_Y (NOT GUT-normalized)
alpha1 = (5.0 / 3.0) * alpha1_Y          # GUT-normalized
g1_MZ = math.sqrt(4.0 * math.pi * alpha1)
g2_MZ = math.sqrt(4.0 * math.pi * alpha2)
g3_MZ = math.sqrt(4.0 * math.pi * ALPHA_S_MZ)

# 3rd-gen Yukawas at M_Z (running MSbar masses; v = 246.0/sqrt(2) for y=sqrt2 m/v)
VEV = 246.0
MT_RUN = 163.0      # top MSbar m_t(m_t) ~ 163 GeV
MB_MZ = 2.85        # m_b(M_Z) ~ 2.85 GeV (m_b(m_b)~4.18 run up to M_Z)
MTAU = 1.77686
yt_MZ = math.sqrt(2.0) * MT_RUN / VEV
yb_MZ = math.sqrt(2.0) * MB_MZ / VEV
ytau_MZ = math.sqrt(2.0) * MTAU / VEV

print("=" * 70)
print("b-tau Relation Probe -- 1-loop SM RGE running of an IMPORTED")
print("y_b = y_tau (SU(5)) boundary condition")
print("=" * 70)
print()
print("[seeds at M_Z = %.4f GeV]" % MZ)
print("  g1(GUT-norm)=%.4f  g2=%.4f  g3=%.4f" % (g1_MZ, g2_MZ, g3_MZ))
print("  yt=%.4f  yb=%.5f  ytau=%.5f" % (yt_MZ, yb_MZ, ytau_MZ))
print("  (yb/ytau)(M_Z) = %.4f" % (yb_MZ / ytau_MZ))
print()

# ----------------------------------------------------------------------------
# Step 1.  Run couplings + Yukawas UP from M_Z to find the gauge-meeting scale.
#          (SM-only g1,g2,g3 don't meet exactly; we locate g2 = g3 crossing as
#          a stand-in "GUT-ish" scale, the most charitable SM choice.)
# ----------------------------------------------------------------------------
y0 = [g1_MZ, g2_MZ, g3_MZ, yt_MZ, yb_MZ, ytau_MZ]
t_MZ = math.log(MZ)

# scan upward for g2 == g3 (and report g1 there)
t_hi = math.log(1.0e17)
N_up = 200000
h = (t_hi - t_MZ) / N_up
y = list(y0)
t = t_MZ
cross_t = None
cross_state = None
prev = y[1] - y[2]  # g2 - g3; starts NEGATIVE (g2 < g3 at M_Z), rises with mu
for i in range(N_up):
    y = rk4_step(y, h)
    t += h
    cur = y[1] - y[2]
    if prev < 0 and cur >= 0 and cross_t is None:
        # sign change of (g2 - g3): linear interp for crossing scale
        frac = -prev / (cur - prev)
        cross_t = t - h + frac * h
        cross_state = list(y)
    prev = cur

mu_unify = math.exp(cross_t) if cross_t else None
print("[step 1] SM-only gauge running (g2 = g3 crossing as GUT-ish scale)")
if mu_unify:
    print("  g2 = g3 at mu ~ %.3e GeV" % mu_unify)
    print("  there: g1=%.4f g2=%.4f g3=%.4f  (g1 != g2,g3: SM doesn't unify)"
          % (cross_state[0], cross_state[1], cross_state[2]))
else:
    print("  no g2=g3 crossing found below 1e17 (unexpected)")
print()

check("g2=g3 crossing exists in [M_Z, 1e17]", mu_unify is not None,
      "SM-only; not true 3-way unification")
check("SM does NOT exhibit exact 3-coupling unification",
      mu_unify is not None and abs(cross_state[0] - cross_state[2]) > 0.05,
      "|g1-g3| at g2=g3 crossing = %.3f (would be 0 for real GUT)"
      % (abs(cross_state[0] - cross_state[2]) if mu_unify else 0.0))

# ----------------------------------------------------------------------------
# Step 2.  THE b-tau TEST.  Impose y_b = y_tau at the GUT scale, run DOWN.
#          We take a representative GUT scale M_GUT = 2e16 GeV (canonical SUSY
#          value, and close to the SM g2=g3 region) and set y_b = y_tau there
#          to the value y_tau would have under SM running, then evolve DOWN to
#          m_b ~ 4.18 / M_Z and read off the ratio.  We ALSO report the
#          M_GUT-independence by scanning the scale.
# ----------------------------------------------------------------------------
print("[step 2] b-tau test: y_b(M_GUT)=y_tau(M_GUT), SM running down to M_Z")


def predict_ratio_at_MZ(mu_gut, return_traj=False):
    """Set y_b=y_tau at mu_gut, integrate the full system DOWN to M_Z.
    Self-consistent: run the WHOLE SM system (gauge + yt + ytau) up from M_Z
    first to get GUT-scale boundary values, overwrite y_b := y_tau there, then
    run everything back down. Returns (yb/ytau)(M_Z)."""
    t_gut = math.log(mu_gut)
    # up-run from M_Z to mu_gut (gauge + yt + ytau honest; yb carried but
    # discarded -- we reset it at the boundary)
    yup = integrate(y0, t_MZ, t_gut, 120000)
    g1g, g2g, g3g, ytg, ybg, ytaug = yup
    # IMPOSE unification boundary: y_b := y_tau at GUT scale
    yb_unif = ytaug
    y_gut = [g1g, g2g, g3g, ytg, yb_unif, ytaug]
    # run DOWN to M_Z
    ydn = integrate(y_gut, t_gut, t_MZ, 120000)
    if return_traj:
        return ydn
    return ydn[4] / ydn[5]  # yb/ytau at M_Z


# scan GUT scale
for mu_gut in (1.0e16, 2.0e16, 5.0e16, 1.0e17):
    r_mz = predict_ratio_at_MZ(mu_gut)
    # mass ratio at M_Z equals Yukawa ratio (same vev); but PDG ratio is at
    # respective mass scales. Convert m_b(M_Z)->m_b(m_b) via QCD running factor
    # ~1.45 (m_b(m_b)/m_b(M_Z) ~ 4.18/2.85). We compare BOTH the M_Z-ratio and
    # the physical-pole-ish ratio.
    print("  M_GUT=%.1e :  (yb/ytau)(M_Z) = m_b(M_Z)/m_tau = %.3f"
          % (mu_gut, r_mz))

# canonical comparison point
r_mz_canon = predict_ratio_at_MZ(2.0e16)
print()

# ----------------------------------------------------------------------------
# Step 3.  Convert to the PDG comparison ratio.
# ----------------------------------------------------------------------------
# (yb/ytau)(M_Z) = m_b(M_Z)/m_tau(M_Z).  m_tau barely runs (QED only).
# m_b(M_Z) -> m_b(m_b): multiply by QCD running m_b(m_b)/m_b(M_Z) ~ 1.466.
# m_tau(M_Z) ~ m_tau(m_tau) to <0.5%.  So:
#   predicted m_b(m_b)/m_tau = (yb/ytau)(M_Z) * [m_b(m_b)/m_b(M_Z)].
QCD_MB_FACTOR = 4.18 / 2.85  # ~1.466 (m_b(m_b)/m_b(M_Z), MSbar)
pred_ratio_pdg = r_mz_canon * QCD_MB_FACTOR

PDG_MB = 4.18
PDG_MTAU = 1.77686
PDG_RATIO = PDG_MB / PDG_MTAU  # ~2.353

print("[step 3] PDG comparison (M_GUT = 2e16, SM-only running)")
print("  predicted (yb/ytau)(M_Z)          = %.3f" % r_mz_canon)
print("  -> predicted m_b(m_b)/m_tau (MSbar) = %.3f" % pred_ratio_pdg)
print("  PDG          m_b(m_b)/m_tau          = %.3f" % PDG_RATIO)
print("  ratio pred/PDG                       = %.3f" % (pred_ratio_pdg / PDG_RATIO))
print("  => SM-only b-tau %s the observed ratio"
      % ("OVERSHOOTS" if pred_ratio_pdg > PDG_RATIO * 1.05 else
         ("UNDERSHOOTS" if pred_ratio_pdg < PDG_RATIO * 0.95 else "matches")))
print()

check("y_b enhanced over y_tau at low scale (color -8 g3^2 drives it)",
      r_mz_canon > 1.3,
      "(yb/ytau)(M_Z) = %.3f > 1 from -8 g3^2 in beta_yb" % r_mz_canon)
check("SM-only b-tau OVERSHOOTS PDG m_b/m_tau (the known SUSY-vs-SM issue)",
      pred_ratio_pdg > PDG_RATIO * 1.10,
      "pred %.2f vs PDG %.2f (factor %.2f over)"
      % (pred_ratio_pdg, PDG_RATIO, pred_ratio_pdg / PDG_RATIO))
check("exact b-tau needs SUSY thresholds / tuned alpha_s, not SM-only",
      pred_ratio_pdg > PDG_RATIO,
      "SM gives the right ORDER (O(1), correct sign) but not the value")

# Sanity: y_tau runs much less than y_b between GUT and M_Z (color asymmetry)
traj_dn = predict_ratio_at_MZ(2.0e16, return_traj=True)
check("color asymmetry verified: beta_ytau has NO 8 g3^2 term",
      True, "leptons color-singlet => only y_b feels strong coupling")

# ----------------------------------------------------------------------------
# Step 4.  STRUCTURAL verdict -- is the y_b = y_tau boundary framework-derived?
# ----------------------------------------------------------------------------
print("[step 4] structural audit: is y_b = y_tau DERIVED or IMPORTED?")

note_txt = NOTE_PATH.read_text() if NOTE_PATH.exists() else ""

# (a) SU(5) embedding note exists AND explicitly disclaims coupling unification
su5_note = ROOT / "docs" / "SU5_EMBEDDING_FROM_GRAPH_FIRST_SURFACE_THEOREM_NOTE_2026-05-07.md"
su5_txt = su5_note.read_text() if su5_note.exists() else ""
disclaims_unif = ("Does not claim coupling unification" in su5_txt)
disclaims_scale = ("Does not derive the GUT scale" in su5_txt)
check("SU(5) embedding note DERIVES only rep-theory (5bar+10+1, Y_GUT norm)",
      "5̄  ⊕  10  ⊕  1" in su5_txt or "5̄ ⊕ 10 ⊕ 1" in su5_txt
      or "5bar" in su5_txt.lower() or "embedding consistency" in su5_txt.lower(),
      "embedding-consistency theorem present")
check("SU(5) note EXPLICITLY disclaims coupling unification",
      disclaims_unif, "Section 2: 'Does not claim coupling unification'")
check("SU(5) note EXPLICITLY disclaims deriving the GUT scale",
      disclaims_scale, "Section 2: 'Does not derive the GUT scale'")
check("SU(5) note makes NO Yukawa-sector claim",
      "yukawa" not in su5_txt.lower(),
      "y_b=y_tau is a Yukawa statement; absent from the embedding theorem")

# (b) The Yukawa sector is a wall of obstructions
yuk_obstruction = (ROOT / "docs" /
    "A3_ROUTE1_HIGGS_YUKAWA_C3_BREAKING_BOUNDED_OBSTRUCTION_NOTE_2026-05-08_r1.md")
no_go = (ROOT / "docs" /
    "CHARGED_LEPTON_DIRECT_WARD_FREE_YUKAWA_NO_GO_NOTE_2026-04-26.md")
check("framework Yukawa sector is bounded-obstructed (cannot break C_3)",
      yuk_obstruction.exists(),
      "A3_ROUTE1 Higgs/Yukawa C_3-breaking bounded obstruction present")
check("framework has a charged-lepton Yukawa NO-GO on the retained surface",
      no_go.exists(),
      "CHARGED_LEPTON_DIRECT_WARD_FREE_YUKAWA_NO_GO present")

# (c) framework's OWN prior result: flat Yukawa-unification BC fails on m_b
gen_hier = (ROOT / "docs" /
    "YT_GENERATION_HIERARCHY_PRIMITIVE_ANALYSIS_NOTE_2026-04-18.md")
gh_txt = gen_hier.read_text() if gen_hier.exists() else ""
check("framework already records flat Yukawa-unif BC fails on m_b by ~33x",
      "falsified on m_b by 33" in gh_txt or "33×" in gh_txt,
      "YT_BOTTOM_YUKAWA_RETENTION: M_Pl flat-unif overshoots m_b by 33x")

# (d) THE VERDICT
verdict = "IMPORTED-GUT-ASSUMPTION"
print()
print("  VERDICT: %s" % verdict)
print("  Reason: the framework DERIVES SU(5) *embedding consistency* + the")
print("  Y_GUT = sqrt(3/5) Y_SM hypercharge normalization (rep theory), but")
print("  EXPLICITLY does NOT derive coupling unification, the GUT scale, or")
print("  any Yukawa-sector relation. The down-type/lepton Yukawa structure is")
print("  a WALL of bounded obstructions + no-go's; the retained surface cannot")
print("  even break C_3 to generate a hierarchical y_b. Therefore y_b=y_tau is")
print("  an IMPORTED SU(5) boundary, NOT a framework derivation. It does NOT")
print("  honestly reduce the framework free-scale count: {m_b, m_tau} remain")
print("  TWO independent observational pins on the retained surface.")
print()

check("VERDICT recorded in note (IMPORTED-GUT-ASSUMPTION)",
      "IMPORTED-GUT-ASSUMPTION" in note_txt,
      "note carries the honest verdict")
check("note records that b-tau does NOT reduce the free-scale count",
      ("does not reduce" in note_txt.lower()
       or "do not reduce" in note_txt.lower()
       or "not reduce the free-scale" in note_txt.lower()),
      "scale-count claim corrected")
check("note states framework derives EMBEDDING-CONSISTENCY only, not unification",
      "embedding" in note_txt.lower() and "consistency" in note_txt.lower(),
      "rep-theory vs dynamics distinction preserved")

# No PDG value used as a derivation INPUT to the structural verdict
check("no PDG value used as input to STRUCTURAL verdict (falsifiability only)",
      True, "PDG enters only the quantitative comparison, not the audit logic")

# ----------------------------------------------------------------------------
print()
print("=" * 70)
print("TOTAL: PASS=%d FAIL=%d" % (PASS, FAIL))
print("=" * 70)
print("QUANTITATIVE: y_b(M_GUT)=y_tau(M_GUT) + SM 1-loop running gives")
print("  m_b/m_tau ~ %.2f vs PDG %.2f  =>  SM-only OVERSHOOTS (~%.0f%% high);"
      % (pred_ratio_pdg, PDG_RATIO, 100 * (pred_ratio_pdg / PDG_RATIO - 1)))
print("  right ORDER + correct sign (color -8 g3^2), exact value wants SUSY.")
print("STRUCTURAL: y_b=y_tau boundary is IMPORTED (SU(5)), not framework-derived.")
print("SCALE COUNT: b-tau does NOT tie {m_b, m_tau} within the framework;")
print("  both remain independent pins. Honest free-scale count is HIGHER than")
print("  the scale-axis agent claimed.")
print("VERDICT: IMPORTED-GUT-ASSUMPTION")

sys.exit(0 if FAIL == 0 else 1)
