#!/usr/bin/env python3
"""Author checks for the companion compact-current and transfer note.

No scientific file inputs. Finite checks challenge the displayed proofs;
they do not establish a thermodynamic phase or independent review.
"""
AUDIT_TIMEOUT_SEC = 90

def check_current_sectors():
    from itertools import product, combinations
    from pathlib import Path
    import json, math
    import numpy as np
    from fractions import Fraction as F
    from sympy import Matrix, symbols, expand

    rows={}
    # Exact one-plaquette scalar determinant; real symmetric hopping is an
    # admissible member of the general nearest-neighbor matrix family.
    z,M=symbols('z M',nonzero=True)
    D=Matrix([[M,z,0,1],[1/z,M,1,0],[0,1,M,1],[1,0,1,M]])
    det=expand(D.det());c=M**4-4*M**2+2
    assert expand(det-(c-z-1/z))==0
    W=expand(det*det.subs(z,1/z))
    coeff={r:expand(W).coeff(z,r).subs(M,5) for r in range(-2,3)}
    assert coeff=={-2:1,-1:-1054,0:277731,1:-1054,2:1}
    assert expand(W-sum(expand(W).coeff(z,r)*z**r for r in range(-2,3)))==0
    assert coeff[0]+2*coeff[1]+2*coeff[2]>0
    rows['symbolic_scalar_determinant']={'determinant':str(det),'M':5,'paired_fourier_coefficients':{str(k):str(v) for k,v in coeff.items()},'negative_coefficients_despite_positive_weight':True}
    # The four-link current of each coefficient is r times the oriented boundary.
    C=np.array([[1,1,1,1]],dtype=int)
    G=np.zeros((4,4),dtype=int)
    for l in range(4):G[l,l]=-1;G[l,(l+1)%4]=1
    assert not np.any(C@G)
    for r in coeff:assert not np.any(G.T@(r*C[0]))
    # Direct normalized Villain real Gaussian vs Fourier character sum.
    def villain(theta,beta):
        n=np.arange(-30,31)
        return np.sqrt(2*np.pi*beta)*np.exp(-beta*(np.asarray(theta)[...,None]+2*np.pi*n)**2/2).sum(axis=-1)
    def weight(theta):return (527-2*np.cos(theta))**2
    partition=[]
    for beta in [.2,1.,5.,20.]:
        ks=np.arange(-100,101);gw=np.exp(-ks**2/(2*beta))
        grid=2*np.pi*np.arange(32768)/32768
        direct=float(np.mean(villain(grid,beta)*weight(grid)))
        dual=sum(float(v)*math.exp(-r*r/(2*beta)) for r,v in coeff.items())
        assert abs(direct/dual-1)<1e-12
        for N in [2,3,5,9,17]:
            th=2*np.pi*np.arange(N)/N
            dn=float(np.mean(villain(th,beta)*weight(th)))
            cn=sum(float(v)*gw[(ks+r)%N==0].sum() for r,v in coeff.items())
            assert abs(dn/cn-1)<1e-12
            # Actual positive pure-gauge q law on this one-plaquette complex.
            qr=np.arange(-30,31);probs=np.exp(-(N*qr)**2/(2*beta));probs/=probs.sum()
            moment=float(probs@(qr**2)) # ||q||^2 / 4 edges = r^2.
            b=N*N/(16*beta)
            theta=float(np.exp(-b*np.arange(-1000,1001)**2/2).sum())
            bound=2*math.log(theta)/b
            assert moment<=bound+1e-13
            partition.append({'beta':beta,'N':N,'direct_partition':dn,'dual_partition':float(cn),'relative_error':abs(dn/cn-1),'pure_q_second_moment_per_edge':moment,'theta_density_bound':bound})
    rows['direct_angles_vs_character_sums']=partition
    # Affine sectors for A=(1,1,0): k=(s-n,n,r), kernel lattice generated by
    # (-1,1,0),(0,0,1). Nonzero shifts occur for odd s and challenge the theta max.
    sector=[]
    for beta in [.15,.7,2.,8.]:
        v=np.arange(-100,101);n,r=np.meshgrid(v,v,indexing='ij')
        Z0=float(np.exp(-(2*n*n+r*r)/(2*beta)).sum())
        for s in range(-7,8):
            Z=float(np.exp(-((s-n)**2+n*n+r*r)/(2*beta)).sum())
            ratio=Z/Z0;lower=math.exp(-s*s/(2*beta));upper=math.exp(-s*s/(4*beta))
            assert lower*(1-1e-12)<=ratio<=upper*(1+1e-12)
            # Direct shifted lattice theta / Poisson dual; covol=sqrt(2).
            x=s/2
            direct_theta=float(np.exp(-(v+x)**2/beta).sum())
            poisson=math.sqrt(math.pi*beta)*float((np.exp(-math.pi**2*beta*v*v)*np.cos(2*math.pi*v*x)).sum())
            assert abs(direct_theta-poisson)<2e-14
            sector.append({'beta':beta,'s':s,'ratio':ratio,'integer_fill_lower':lower,'real_fill_upper':upper,'theta_poisson_error':abs(direct_theta-poisson)})
    rows['affine_integer_gaussian_comparison']=sector
    # Integer cochain homotopy and its transposed current filling, implemented
    # directly here so this exploratory check has no hidden local helper input.
    def box(d,L):
        cells=[[(p,S) for S in combinations(range(d),k) for p in product(*[range(L if i in S else L+1) for i in range(d)])] for k in range(d+1)]
        ix=[{v:i for i,v in enumerate(ck)} for ck in cells];Ds=[];Hs=[None]
        for k in range(d):
            a=np.zeros((len(cells[k+1]),len(cells[k])),dtype=np.int64)
            for row,(p,S) in enumerate(cells[k+1]):
                for j,axis in enumerate(S):
                    R=tuple(v for v in S if v!=axis);up=list(p);up[axis]+=1
                    a[row,ix[k][tuple(up),R]]+=(-1)**j;a[row,ix[k][p,R]]-=(-1)**j
            Ds.append(a)
        for k in range(1,d+1):
            h=np.zeros((len(cells[k-1]),len(cells[k])),dtype=np.int64)
            for row,(y,R) in enumerate(cells[k-1]):
                for axis in range(min(R) if R else d):
                    for t in range(y[axis]):
                        p=tuple(0 if j<axis else t if j==axis else y[j] for j in range(d))
                        h[row,ix[k][p,(axis,)+R]]+=1
            Hs.append(h)
        return cells,Ds,Hs
    rng=np.random.default_rng(71403);fills=[]
    for d,L in [(2,1),(2,3),(3,1),(3,2),(4,1)]:
        cells,Ds,Hs=box(d,L);G,C=Ds[:2]
        assert np.array_equal(G@Hs[1]+Hs[2]@C,np.eye(len(cells[1]),dtype=int))
        norm2=float(np.linalg.norm(C.astype(float),2)**2);assert norm2<=4*d+1e-12
        for _ in range(20):
            k=rng.integers(-3,4,size=len(cells[2]));s=C.T@k;fill=Hs[2].T@s
            assert not np.any(G.T@s)
            assert np.array_equal(C.T@fill,s)
        fills.append({'d':d,'L':L,'cells':[len(v) for v in cells],'curl_norm_squared':norm2,'integer_current_fill_checks':20})
    rows['current_homotopy_and_norm']=fills
    # Per-edge screening threshold and the distinct no-alias threshold.
    for m in [1,2,4]:
        for N in [2*m+1,4*m,4*m+1]:
            for q in range(-5,6):
                for j in range(-2*m,2*m+1):
                    assert abs(N*q-j)>=(N-2*m)*abs(q)
            residues=[j%N for j in range(-2*m,2*m+1)]
            assert (len(set(residues))==len(residues))==(N>4*m)
    rows['distinct_screening_and_injectivity_thresholds']=True
    # The canonical q weight can stay negative even after summing fermion
    # currents: one square, M=5>4, beta=1, N=7, q=one boundary.
    # x=exp(-1/2) is trapped by exact rational Taylor arithmetic.
    ehalf=sum(F(1,2)**n/math.factorial(n) for n in range(21))
    tail=F(1,2)**21/math.factorial(21)/(1-F(1,44))
    xlo=F(60653,100000);xhi=F(60654,100000)
    assert 1/(ehalf+tail)>xlo and 1/ehalf<xhi
    upper=1-1054*xlo**11+277731*xhi**24-1054*xlo**39+xhi**56
    assert upper<0
    rows['negative_marginalized_cyclic_q_weight']={'M':5,'beta':1,'N':7,'q_cycle':1,'scaled_weight_upper_exact':str(upper),'scaled_weight_upper_float':float(upper),'interval_for_exp_minus_half':[str(xlo),str(xhi)],'claim':'canonical Fourier alias weight after summing j is negative; original angle law remains positive'}
    # The physical-source identity is checked against the positive joint (theta,n)
    # integral, not only by differentiating the same character formula.
    source=[]
    for beta,N in [(1.,7),(5.,9),(.2,5)]:
        theta=2*np.pi*np.arange(N)/N;ns=np.arange(-30,31)
        field=theta[:,None]+2*np.pi*ns
        base=np.exp(-beta*field**2/2)*weight(theta)[:,None]
        norm=base.sum();mean=float((base*field).sum()/norm)
        var=float((base*field**2).sum()/norm-mean**2)
        ks=np.arange(-100,101);dual_weights=np.zeros(len(ks))
        for j,w in coeff.items():dual_weights+=float(w)*np.exp(-ks**2/(2*beta))*((ks+j)%N==0)
        dualnorm=dual_weights.sum();dualmean=dual_weights@ks/dualnorm
        signedvar=dual_weights@(ks**2)/dualnorm-dualmean**2
        assert abs(mean)<1e-12 and abs(var-(1/beta-signedvar/beta**2))<1e-12
        for h in [-.3,.1,.4]:
            direct=float((base*np.exp(h*field)).sum()/norm)
            predicted=math.exp(h*h/(2*beta))*np.sum(dual_weights*np.exp(-1j*ks*h/beta))/dualnorm
            assert abs(predicted.imag)<1e-13 and abs(direct-predicted.real)<1e-12
        source.append({'beta':beta,'N':N,'physical_variance':var,'signed_dual_variance':float(signedvar),'source_checks':[-.3,.1,.4]})
    rows['physical_source_identity']=source
    # Closed-chain extension, not a phase result.
    return rows

def check_transfer_scaling():
    from pathlib import Path
    from itertools import product
    import json, math
    import numpy as np
    import mpmath as mp
    from scipy.linalg import expm,eigh

    result={};rows=[]
    def theta(x):return 1+2*sum(x**(q*q) for q in range(1,30))
    def eigenQ(N,x):
        angle=2*np.pi*np.arange(N)/N
        return (1+2*sum(x**(q*q)*np.cos(q*angle) for q in range(1,30)))/theta(x)
    def spatial(phi,y):return (1+2*sum(y**(q*q)*np.cos(q*phi) for q in range(1,30)))/theta(y)
    for N in [2,3,5,9,17]:
        X=np.roll(np.eye(N),1,axis=0);H0=2*np.eye(N)-X-X.T
        for delta in [.1,.025,.00625,.0015625]:
            t=.7;x=delta*t;beta=N*N/(2*np.pi*np.pi)*math.log(1/x)
            # Direct periodized real Gaussian evaluated on each group element.
            ang=2*np.pi*np.arange(N)/N;n=np.arange(-20,21)
            prob=np.exp(-beta*(ang[:,None]+2*np.pi*n)**2/2).sum(axis=1);prob/=prob.sum()
            Q=sum(prob[r]*np.linalg.matrix_power(X,r) for r in range(N))
            lam=eigenQ(N,x);assert lam.min()>0
            assert np.max(abs(np.sort(np.linalg.eigvalsh(Q))-np.sort(lam)))<1e-13
            error=float(np.linalg.norm(Q-(np.eye(N)-x*H0),2))
            R=2*x**4/(1-x**5);bound=8*x*x+(4*x+2)*R
            assert error<=bound+1e-14
            generator=-np.log(lam)/delta
            target=2*t*(1-np.cos(ang));ge=float(np.max(abs(generator-target)))
            deficit=4*x+2*R;generator_bound=(bound+deficit**2/(2*(1-deficit)))/delta
            assert deficit<1 and ge<=generator_bound+1e-12
            rows.append({'N':N,'delta':delta,'temporal_beta':beta,'generator_error':ge,'transfer_linear_error':error,'proved_linear_error_bound':bound})
        last=[r['generator_error'] for r in rows if r['N']==N]
        assert all(b<a for a,b in zip(last,last[1:]))
    result['temporal_direct_kernel']=rows
    # Uniform spatial-potential check, with high-resolution angles used only to
    # challenge the analytic uniform bound (not to prove it).
    sp=[]
    for delta in [.1,.025,.00625,.0015625]:
        K=1.3;y=delta*K/2;phi=np.linspace(-np.pi,np.pi,2049)
        B=spatial(phi,y);assert B.min()>0 and B.max()<=1+1e-14
        error=float(np.max(abs(-np.log(B)/delta-K*(1-np.cos(phi)))))
        R=2*y**4/(1-y**5);linear=8*y*y+(4*y+2)*R;deficit=4*y+2*R
        bound=(linear+deficit**2/(2*(1-deficit)))/delta
        assert deficit<1 and error<=bound+1e-12
        sp.append({'delta':delta,'spatial_beta':1/(2*math.log(1/y)),'generator_sup_grid_error':error})
    assert all(b['generator_sup_grid_error']<a['generator_sup_grid_error'] for a,b in zip(sp,sp[1:]))
    result['spatial_villain_generator']=sp
    # Fixed one-plaquette physical Gauss sector. Electric labels have the same
    # oriented flux on all four edges, so Q restricted to the sector is lambda^4.
    pr=[]
    for N in [3,5,9]:
        ang=2*np.pi*np.arange(N)/N;F=np.exp(1j*np.outer(np.arange(N),ang))/np.sqrt(N)
        t=.7;K=1.3
        HB=F.conj().T@np.diag(K*(1-np.cos(ang)))@F
        HE=np.diag(8*t*(1-np.cos(ang)));H=HE+HB
        exact=expm(-.8*H)
        for delta in [.1,.025,.00625]:
            half=F.conj().T@np.diag(np.sqrt(spatial(ang,delta*K/2)))@F
            T=half@np.diag(eigenQ(N,delta*t)**4)@half
            eig,U=eigh(T);assert eig.min()>0 and eig.max()<=1+1e-12
            generator=(U*(-np.log(eig)/delta))@U.conj().T
            ge=float(np.linalg.norm(generator-H,2))
            steps=round(.8/delta);evolved=(U*(eig**steps))@U.conj().T
            error=float(np.linalg.norm(evolved-exact,2))
            pr.append({'N':N,'delta':delta,'generator_error':ge,'semigroup_time':.8,'semigroup_error':error,'minimum_transfer_eigenvalue':float(eig.min())})
        rr=[r for r in pr if r['N']==N]
        assert all(b['generator_error']<a['generator_error'] and b['semigroup_error']<a['semigroup_error'] for a,b in zip(rr,rr[1:]))
    result['gauss_sector_noncommuting_transfer']=pr
    # The wrong fixed-N rotor scaling: use log1p on an explicitly summed spectral
    # deficit, preserving exponentially small values that double precision loses.
    mp.mp.dps=90;freeze=[];N=5;b=mp.mpf(1)
    for delta in [mp.mpf('0.1'),mp.mpf('0.05'),mp.mpf('0.02'),mp.mpf('0.005'),mp.mpf('0.001')]:
        x=mp.exp(-2*mp.pi**2*b/(N*N*delta));den=1+2*sum(x**(q*q) for q in range(1,20))
        energies=[]
        for k in range(N):
            deficit=2*sum(x**(q*q)*(1-mp.cos(2*mp.pi*q*k/N)) for q in range(1,20))/den
            energies.append(-mp.log1p(-deficit)/delta)
        maxh=max(energies);assert maxh>0
        freeze.append({'delta':str(delta),'log10_generator_norm':str(mp.log10(maxh))})
    assert all(mp.mpf(v['log10_generator_norm'])<mp.mpf(u['log10_generator_norm']) for u,v in zip(freeze,freeze[1:]))
    result['fixed_N_rotor_scaling_freezes']=freeze
    # Distinct absolute path and operator bounds for anisotropic r=1 Wilson.
    sx=np.array([[0,1],[1,0]],complex);sy=np.array([[0,-1j],[1j,0]],complex);sz=np.diag([1,-1])
    gam=[np.kron(sx,s) for s in [sx,sy,sz]]+[np.kron(sy,np.eye(2))]
    vs=list(product(range(2),range(2),range(2),range(3)));ix={v:i for i,v in enumerate(vs)}
    rng=np.random.default_rng(8108);Us=[]
    for mu,L in enumerate([2,2,2,3]):
        U=np.zeros((len(vs),len(vs)),complex)
        for x in vs:
            y=list(x);y[mu]=(y[mu]+1)%L
            U[ix[x],ix[tuple(y)]]=np.exp(1j*rng.uniform(-np.pi,np.pi))
        assert np.linalg.norm(U.conj().T@U-np.eye(len(vs)))<1e-13;Us.append(U)
    wilson=[]
    for delta in [1.,.25,.0625]:
        weights=[1,1,1,1/delta];m0=.7;mass=m0+sum(weights);K=np.zeros((4*len(vs),4*len(vs)),complex)
        for w,g,U in zip(weights,gam,Us):
            axial=-w*(np.kron((np.eye(4)-g)/2,U)+np.kron((np.eye(4)+g)/2,U.conj().T))
            assert abs(np.linalg.norm(axial,2)-w)<1e-12;K+=axial
        D=mass*np.eye(len(K))+K
        coercive=(D+D.conj().T)/2
        assert np.linalg.eigvalsh(coercive).min()>=m0-1e-12
        assert np.linalg.svd(D,compute_uv=False).min()>=m0-1e-12
        actual=float(np.linalg.norm(K,2)/mass);improved=sum(weights)/mass;count=2*sum(weights)/mass
        assert actual<=improved+1e-12 and improved<1
        wilson.append({'delta':delta,'mass_diagonal':mass,'path_count_ratio':count,'operator_ratio_bound':improved,'actual_operator_ratio':actual,'minimum_singular_value':float(np.linalg.svd(D,compute_uv=False).min())})
    result['anisotropic_Wilson_bound_distinction']=wilson
    return result

def check_r1_fourier_sign():
    from fractions import Fraction as F
    from pathlib import Path
    from itertools import product
    import json,math
    import numpy as np
    import sympy as sp
    word=[-1,-4,3,-2,-3,1,2,3,4,-3]
    x=(1,1,0,1);visited=[x];edges=[]
    for a in word:
        y=list(x);y[abs(a)-1]+=1 if a>0 else -1;y=tuple(y)
        assert all(v in [0,1] for v in y)
        edges.append((x,y));visited.append(y);x=y
    assert visited[-1]==visited[0] and len(set(visited[:-1]))==10
    # Exhaust the subcurrent claim without using spin matrices.
    closed=[]
    for bits in product([0,1],repeat=10):
        div={v:0 for v in visited[:-1]}
        for b,(x,y) in zip(bits,edges):div[x]-=b;div[y]+=b
        if not any(div.values()):closed.append(bits)
    assert closed==[(0,)*10,(1,)*10]
    # Clifford e_A e_B multiplication by inversion parity, independent of matrices.
    def mul(A,B):
        out={}
        for a,ca in A.items():
            for b,cb in B.items():
                inversions=sum((b&((1<<i)-1)).bit_count() for i in range(4) if a&(1<<i))
                mask=a^b;out[mask]=out.get(mask,F(0))+ca*cb*((-1)**inversions)
        return {k:v for k,v in out.items() if v}
    poly={0:F(1)}
    for a in word:poly=mul(poly,{0:F(1,2),1<<(abs(a)-1):F(-1 if a>0 else 1,2)})
    trace=4*poly.get(0,F(0));assert trace==F(1,32)
    sx=sp.Matrix([[0,1],[1,0]]);sy=sp.Matrix([[0,-sp.I],[sp.I,0]]);sz=sp.diag(1,-1);I=sp.eye(4)
    gam=[sp.kronecker_product(sx,g) for g in [sx,sy,sz]]+[sp.kronecker_product(sy,sp.eye(2))]
    def projector(a):return (I-sp.sign(a)*gam[abs(a)-1])/2
    def spin_product(w):
        P=I
        for a in w:P=(P*projector(a)).applyfunc(sp.expand)
        return P
    P=spin_product(word);Prev=spin_product([-a for a in word[::-1]]);Pbar=spin_product([-a for a in word])
    assert sp.trace(P)==sp.Rational(trace.numerator,trace.denominator)
    assert sp.trace(Pbar)==sp.trace(P) and sp.trace(Prev)==sp.trace(P)
    l=sp.symbols('l');char=P.charpoly(l).as_expr()
    assert sp.expand(char-(l**4-l**3/32+l**2/1024))==0
    # Derive the isolated-cycle determinant's Laurent form from the two transfer
    # products, then compare whole 40x40 determinants at nontrivial phases.
    z,u=sp.symbols('z u',nonzero=True)
    forward=sp.expand((I-u**10*z*P).det())
    reverse=sp.expand((I-u**10/z*Prev).det());cycle=sp.expand(forward*reverse)
    paired=sp.expand(cycle*cycle)
    assert sp.expand(paired).coeff(z,1).coeff(u,10)==-sp.Rational(1,16)
    assert all(sp.expand(paired).coeff(z,1).coeff(u,r)==0 for r in range(10))
    checks=[]
    for mass in [2.5,5.,10.]:
        for angle in [0.,.317,1.1,math.pi]:
            D=np.eye(40,dtype=complex)
            for i,a in enumerate(word):
                j=(i+1)%10;phase=np.exp(1j*angle) if i==0 else 1
                Pf=np.array(projector(a),complex);Pb=np.array(projector(-a),complex)
                D[4*i:4*i+4,4*j:4*j+4]-=Pf*phase/mass
                D[4*j:4*j+4,4*i:4*i+4]-=Pb*phase.conjugate()/mass
            direct=np.linalg.det(D)
            predicted=complex(cycle.subs({u:1/mass,z:np.exp(1j*angle)}).evalf(30))
            err=abs(direct-predicted);assert err<3e-14
            checks.append({'mass':mass,'angle':angle,'direct_determinant_real':float(direct.real),'transfer_formula_error':err})
    # Full 16-site four-dimensional box: exact global polynomial tail, no
    # finite-angle approximation of its 32-dimensional Fourier coefficient.
    mass=2**100
    ratio=F(16*math.comb(128,11)*4**11,mass-39);assert ratio<1
    assert all(F(4*(128-r),r+1)<=39 for r in range(11,128))
    # Bound is derived from principal minors and the axial norm. Directly check
    # the actual full-box norm and gamma5-Hermiticity at independent phase fields.
    vs=list(product(range(2),repeat=4));ix={v:i for i,v in enumerate(vs)}
    g5=gam[0]*gam[1]*gam[2]*gam[3];G5=np.kron(np.eye(16),np.array(g5,complex))
    rng=np.random.default_rng(91410);full=[]
    for rep in range(3):
        K=np.zeros((64,64),complex)
        for x in vs:
            for mu in range(4):
                if x[mu]==1:continue
                y=list(x);y[mu]+=1;y=tuple(y);a=slice(4*ix[x],4*ix[x]+4);b=slice(4*ix[y],4*ix[y]+4)
                phase=np.exp(1j*rng.uniform(-math.pi,math.pi))
                K[a,b]=-np.array(projector(mu+1),complex)*phase
                K[b,a]=-np.array(projector(-mu-1),complex)*phase.conjugate()
        norm=float(np.linalg.norm(K,2));assert norm<=4+1e-12
        assert np.linalg.norm(K.conj().T-G5@K@G5)<1e-13
        full.append(norm)
    result={'word':word,'cycle_vertices':[list(v) for v in visited],'proper_nonempty_closed_subcurrents':0,'Clifford_trace_exact':str(trace),'explicit_matrix_charpoly':str(char),'adjoint_and_reverse_trace_equal':True,'leading_full_box_Fourier_coefficient':'-1/(16*M^10)','certificate_mass':str(mass),'remainder_to_leading_upper_exact':str(ratio),'remainder_to_leading_upper_float':float(ratio),'negative_real_Fourier_coefficient_certified':True,'isolated_cycle_determinant':str(cycle),'independent_cycle_determinant_checks':checks,'full_box_random_phase_operator_norms':full,'scope':'pointwise-positive standard r=1 Wilson paired determinant is not universally of positive Fourier type; no phase/no-go conclusion'}
    return result

def main():
    import json
    results=[]
    functions=[check_current_sectors,check_transfer_scaling,check_r1_fourier_sign]
    for fn in functions:
        try:
            data=fn()
            if fn is check_current_sectors:
                a=data.pop('affine_integer_gaussian_comparison')
                data['affine_integer_gaussian_summary']={
                    'cases':len(a),'betas':[.15,.7,2.,8.],'integer_sources':[-7,7],
                    'maximum_Poisson_error':max(r['theta_poisson_error'] for r in a),
                    'minimum_upper_minus_ratio':min(r['real_fill_upper']-r['ratio'] for r in a)}
                a=data.pop('direct_angles_vs_character_sums')
                data['character_sum_summary']={
                    'cases':len(a),'betas':[.2,1.,5.,20.],'N':[2,3,5,9,17],
                    'maximum_relative_error':max(r['relative_error'] for r in a),
                    'density_bound_checked_in_all_cases':True}
            print(json.dumps(data,sort_keys=True),flush=True)
            print('PASS:',fn.__name__,flush=True)
            results.append(fn.__name__)
        except Exception:
            print('FAIL:',fn.__name__,flush=True)
            print(f'TOTAL: PASS={len(results)} FAIL=1',flush=True)
            raise
    print('per_element: exact scalar coefficients, Clifford products and the full r=1 polynomial remainder challenge the sign claims')
    print('per_site: integer contraction and all proper cycle subcurrents are checked on explicitly named finite cell complexes')
    print('per_mode: direct Villain kernels, cyclic spectra and physical-source transforms check the original observable normalization')
    print('per_block: affine Gaussian sums, positive angle integrals and full cycle determinants use distinct mathematical representations')
    print('lattice_wide: general sector bounds are analytic; fixed-box transfer checks do not prove a uniform interacting infrared phase')
    print(f'TOTAL: PASS={len(results)} FAIL=0',flush=True)

if __name__=='__main__':
    main()
