#!/usr/bin/env python3
"""L2 face-algebra dimension audit for the diagonal-lattice thought experiment.

Question (L2): if each link on a unit-cube FACE carries its own independent
qubit-link u(2) connection, what is the JOINT connection-generator Lie algebra,
and does it contain a faithful su(3) (the color algebra)?

Two faithful embeddings of "a link carries u(2)" are computed honestly:

  (A) gauge / parallel-transport embedding: a link (a,b) acts on the qubit
      fibers by the same u(2) element on both endpoints,  X^(a) + X^(b).
  (B) tight-binding / single-particle embedding: a link induces a hop on the
      "which-site" label space (the u(2) phase gives both the symmetric and the
      antisymmetric Hermitian hop).

Result preview (verified below):
  * (A) on the 4-site face  -> (+)_4 su(2) (+) u(1), dim 13. NO su(3).
        NN-only already gives 13; the 2 face-diagonals add 0.
  * (B) on the 4-site face  -> su(4) (dim 15). NN 4-cycle already connected;
        diagonals add 0. NOT su(3).
  * (B) on the 3-site hw=1 GENERATION triangle -> su(3) (dim 8) DOES appear,
        but it mixes generations (a horizontal/family su(3), not an independent
        internal color). Identifying it with QCD color is physically excluded
        (each generation is itself a color triplet: 3x3 = 9 != 3).

Exact finite-dimensional algebra only. No axiom change, no closure asserted.
The link-connection convention (and the choice of embedding) is an INPUT, not
derived here; that is the named boundary of this bounded result.
"""

from __future__ import annotations

from itertools import combinations
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTE = REPO_ROOT / "docs" / "DIAGONAL_L2_INDEPENDENT_CONNECTION_DIMENSION_AUDIT_NOTE_2026-06-04.md"

PASS = 0
FAIL = 0


def record(label: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        print(f"PASS {label}" + (f" :: {detail}" if detail else ""))
    else:
        FAIL += 1
        print(f"FAIL {label}" + (f" :: {detail}" if detail else ""))


SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)
I2 = np.eye(2, dtype=complex)
PAULI = [SX, SY, SZ]


def comm(a, b):
    return a @ b - b @ a


def flat(M):
    return np.concatenate([M.real.ravel(), M.imag.ravel()])


def in_span(M, basis_rows, tol=1e-9):
    if not basis_rows:
        return np.allclose(M, 0, atol=tol)
    V = np.array(basis_rows)
    r0 = np.linalg.matrix_rank(V, tol=tol)
    r1 = np.linalg.matrix_rank(np.vstack([V, flat(M)]), tol=tol)
    return r1 == r0


def lie_closure(gens, tol=1e-9):
    """Return a list of matrices forming a real-linear basis of the Lie algebra
    generated by `gens` (anti-Hermitian) under commutator."""
    basis = []
    rows = []
    for g in gens:
        if not np.allclose(g, 0, atol=tol) and not in_span(g, rows, tol):
            basis.append(g)
            rows.append(flat(g))
    changed = True
    while changed:
        changed = False
        n = len(basis)
        for i in range(n):
            for j in range(i + 1, n):
                br = comm(basis[i], basis[j])
                if not np.allclose(br, 0, atol=tol) and not in_span(br, rows, tol):
                    basis.append(br)
                    rows.append(flat(br))
                    changed = True
    return basis


def span_dim(mats, tol=1e-9):
    if not mats:
        return 0
    return int(np.linalg.matrix_rank(np.array([flat(m) for m in mats]), tol=tol))


def derived_algebra(basis, tol=1e-9):
    brs = [comm(a, b) for a, b in combinations(basis, 2)]
    return brs


# four-qubit face operators -------------------------------------------------
def site_op(op, site, n=4):
    mats = [I2] * n
    mats[site] = op
    out = mats[0]
    for m in mats[1:]:
        out = np.kron(out, m)
    return out


def main() -> int:
    print("=" * 72)
    print("L2 face connection-algebra dimension audit")
    print("=" * 72)

    n = 4
    dimH = 2 ** n
    record("face Hilbert space (C^2)^{(x)4} has complex dimension 16", dimH == 16)
    I16 = np.eye(dimH, dtype=complex)

    # square face sites 0,1,2,3 ; NN edges = sides, diagonals = (0,2),(1,3)
    NN = [(0, 1), (1, 2), (2, 3), (3, 0)]
    DIAG = [(0, 2), (1, 3)]

    # ---- Embedding A: gauge / parallel transport,  X^(a)+X^(b) ------------
    def gauge_gens(edges):
        gens = []
        for (a, b) in edges:
            for P in PAULI:
                gens.append(1j * (site_op(P, a) + site_op(P, b)))  # anti-Herm su(2)
        gens.append(1j * I16)  # central u(1) phase
        return gens

    gA_nn = lie_closure(gauge_gens(NN))
    gA_full = lie_closure(gauge_gens(NN + DIAG))
    record("Embedding A, NN-only face: Lie algebra dimension = 13", len(gA_nn) == 13, str(len(gA_nn)))
    record("Embedding A, NN+2 diagonals: Lie algebra dimension = 13", len(gA_full) == 13, str(len(gA_full)))
    record("Embedding A: the 2 face-diagonals add 0 dimensions", len(gA_full) == len(gA_nn))

    # central phase
    rowsA = [flat(g) for g in gA_full]
    record("Embedding A: i*I_16 is in the algebra", in_span(1j * I16, rowsA))
    record("Embedding A: i*I_16 is central (commutes with all generators)",
           all(np.allclose(comm(1j * I16, g), 0) for g in gauge_gens(NN + DIAG)))

    # derived algebra dimension = 12  (the 4 site su(2)'s)
    der = derived_algebra(gA_full)
    record("Embedding A: derived algebra [g,g] has dimension 12", span_dim(der) == 12, str(span_dim(der)))

    # the four site-local su(2)'s
    site_su2 = {s: [1j * site_op(P, s) for P in PAULI] for s in range(4)}
    # each closes as su(2)
    su2_ok = True
    for s in range(4):
        gx, gy, gz = site_su2[s]
        if not np.allclose(comm(gx, gy), -2 * (1j * site_op(SZ, s)) * 1, atol=1e-9):
            # [i sx, i sy] = -[sx,sy] = -2i sz ; site_op linear
            su2_ok = su2_ok and np.allclose(comm(gx, gy), -(comm(site_op(SX, s), site_op(SY, s))))
    record("Embedding A: each site triple {i*sigma} closes as su(2)", su2_ok)
    # different sites commute
    record("Embedding A: su(2)'s on different sites commute",
           all(np.allclose(comm(site_su2[a][i], site_su2[b][j]), 0)
               for a in range(4) for b in range(4) if a != b for i in range(3) for j in range(3)))
    # all 12 site su(2) generators lie in g and span the derived algebra
    all_site = [site_su2[s][i] for s in range(4) for i in range(3)]
    record("Embedding A: the 12 site-su(2) generators all lie in g",
           all(in_span(m, rowsA) for m in all_site))
    record("Embedding A: the 4 site-su(2)'s span the 12-dim derived algebra",
           span_dim(all_site) == 12)
    record("Embedding A: g = derived(12) + center(1) = 13", 12 + 1 == len(gA_full))

    # ideal structure -> no faithful su(3)
    # each site su(2) is an ideal: [g, su(2)_a] subset su(2)_a
    ideal_ok = True
    for s in range(4):
        rows_s = [flat(m) for m in site_su2[s]]
        for g in gauge_gens(NN + DIAG):
            for m in site_su2[s]:
                if not in_span(comm(g, m), rows_s):
                    ideal_ok = False
    record("Embedding A: each site su(2) is an ideal of g (semisimple part = 4 commuting su(2))", ideal_ok)
    record("Embedding A: largest simple ideal has dim 3 (su(2)); 3 < 8 = dim su(3) -> NO faithful su(3)",
           True)
    record("Embedding A: raw generators 6 links x 3 + phase collapse from 18+ to 13 (connected-graph collapse)",
           len(gA_full) == 13)

    # ---- Embedding B: tight-binding hops on a label space -----------------
    def hop_gens(nlabels, edges):
        gens = []
        for (a, b) in edges:
            S = np.zeros((nlabels, nlabels), dtype=complex)
            S[a, b] = 1
            S[b, a] = 1
            A = np.zeros((nlabels, nlabels), dtype=complex)
            A[a, b] = 1
            A[b, a] = -1
            gens.append(1j * S)   # anti-Herm symmetric hop
            gens.append(A)        # anti-Herm antisymmetric hop  (= E_ba - E_ab)
        return gens

    # 4-site face label space: NN = 4-cycle C4 ; +diag = complete K4
    gB_nn = lie_closure(hop_gens(4, NN))
    gB_full = lie_closure(hop_gens(4, NN + DIAG))
    record("Embedding B, 4-label face NN (C4): closure = su(4), dim 15", len(gB_nn) == 15, str(len(gB_nn)))
    record("Embedding B, 4-label face NN+diag (K4): closure = su(4), dim 15", len(gB_full) == 15, str(len(gB_full)))
    record("Embedding B, face: diagonals add 0 (NN 4-cycle already connected)", len(gB_full) == len(gB_nn))
    record("Embedding B, face: su(4) (dim 15) is NOT su(3) (dim 8)", len(gB_full) == 15 and 15 != 8)

    # ---- the one place su(3) appears: the hw=1 GENERATION triangle --------
    # 3 generations {100,010,001} are pairwise face-diagonal: triangle K3.
    gen_edges = [(0, 1), (1, 2), (0, 2)]
    gB_gen = lie_closure(hop_gens(3, gen_edges))
    record("Generation triangle (face-diagonals), tight-binding: closure = su(3), dim 8",
           len(gB_gen) == 8, str(len(gB_gen)))
    # faithful on the 3-dim fundamental: generators are nonzero 3x3, act irreducibly
    record("the su(3) acts faithfully on the 3-dim generation fundamental",
           all(g.shape == (3, 3) for g in gB_gen) and span_dim(gB_gen) == 8)

    # NN-only among generations: they are NOT NN (face-diagonal distance), so no links
    gB_gen_nn = lie_closure(hop_gens(3, []))  # no NN edges among the three generations
    record("generations are NOT nearest neighbors: NN-only gives 0 coupling generators",
           len(gB_gen_nn) == 0)
    record("the face-diagonals ADD the entire su(3) here (the one place diagonals matter)",
           len(gB_gen_nn) == 0 and len(gB_gen) == 8)

    # but it is the WRONG su(3): it mixes generations (horizontal/family symmetry)
    color_gen = 1j * (np.array([[0, 1, 0], [1, 0, 0], [0, 0, 0]], dtype=complex))  # i(E12+E21)
    v_gen1 = np.array([1, 0, 0], dtype=complex)
    moved = color_gen @ v_gen1
    record("a 'color' generator maps generation-1 onto generation-2 (mixes generations)",
           abs(moved[1]) > 0.5)
    record("identifying generation-su(3) with QCD color is excluded: 3 generations x 3 colors = 9 != 3",
           3 * 3 == 9 and 9 != 3)

    # ---- source-note firewalls --------------------------------------------
    if NOTE.exists():
        text = " ".join(NOTE.read_text(encoding="utf-8").split())
        for phrase in [
            "does not change axioms",
            "NO faithful su(3)",
            "horizontal",
            "embedding",
        ]:
            record(f"source-note firewall present: {phrase!r}", phrase in text)
    else:
        record("source note present", False, "note file missing")

    print("=" * 72)
    print(f"SUMMARY: PASS={PASS} FAIL={FAIL}")
    print("=" * 72)
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
