#!/usr/bin/env python3
"""A soft vector constraint and slot fields generate the landed tensor field's curvature moves at twelfth order.

Open PR 9077 showed that the landed tensor field (slots E_ij on vertex and
face sites, the vector constraint (G E)_j = d_i E_ij on link sites) cannot be
moved by the two-site clause or by any single neighbourhood. Open PR 9066
showed the U(1) link field gets its ring at fourth order from a soft vertex
Gauss energy and record fields. This runner does the same for the tensor
field (supplied models, finite diagnostics, no physical reading):
H = U sum_rows (G v)_row^2 - h sum_slots (X_s + X_s^dag), where v is the
change of the slots from a constraint-satisfying configuration and X_s
shifts slot s by one. Each row is a one-neighbourhood term on its link site.

1. Leading moves: the smallest L1 norm of a nonzero integer change with
   G v = 0 is 12 (mixed-integer programs through a diagonal and a face slot,
   radius-2 box). A complete enumeration finds exactly 6 such moves through
   a diagonal slot and 4 through a face slot, all planar pieces of the
   landed scalar-gauge pattern (open PR 9077).
2. The path sum: the leading amplitude is g = A h^12 / U^11 with
   A = sum over the monotone paths of prod 1 / |G v_k|^2 over the 11
   intermediate partial moves, none of which satisfies the constraint.
   Exactly A = 111150053/31850496. The same sum for the U(1) plaquette ring
   gives 5/2, which is open PR 9066's 5/32 with fields h s^x = (h/2) sigma^x.
3. Exact diagonalization on the path box (2304 states, reflection symmetric)
   confirms it: the splitting over 2 A (h/U)^12 tends to 1 as h/U -> 0.
4. Two-level (qubit) slots allow only unit changes. The smallest unit moves
   have 20 slots (radius-2 box here; a radius-3 box gives the same), so they
   appear at order 20. Two shapes occur: a spatial one with path sum 0.926
   and a planar one, in one lattice plane, with path sum 510.6.
5. Diagonal energies: for unbounded (rotor) slots every constraint-satisfying
   configuration has the same excitation energies, since |G v|^2 depends
   only on the change v, so no diagonal term arises at any order. For qubit
   slots each slot flips one way only; on zero-charge surroundings (SAT
   samples on a 6^3 torus) the fourth-order diagonal energy changes across
   the planar 20-slot move by exactly (201/960) dN_A h^4/U^3 (unit step),
   where N_A counts rows whose two diagonal slots differ; dN_A = 0 occurs.
6. With a supplied one-site electric energy (J/2) E^2, the Gaussian spectrum
   of the generated curvature cosines has three branches with
   omega^2 = J g lambda(k), lambda ~ |k|^4 at small k (quadratic dispersion);
   one branch vanishes on the coordinate planes k_a = 0, since the planar
   pieces fix only the diagonal curvature components. On the landed scalar
   constraint surface S q = 0 two branches remain.
7. Modulo 2 (a parity constraint on qubit slots) the face slots and rows form
   the dual lattice's Z2 gauge structure: each row is a dual plaquette of four
   face slots, each face slot sits in four rows, and the face-slot moves are
   generated by the six-face cube moves plus windings; a planar piece modulo
   2 is an 8-slot move through diagonal slots.

Prints one line per check and `TOTAL: PASS=N FAIL=M`.
"""
import itertools
import sys
from fractions import Fraction

AUDIT_TIMEOUT_SEC = 600

import numpy as np
from scipy.optimize import Bounds, LinearConstraint, milp
from pysat.solvers import Glucose4
from scipy.sparse import csr_matrix

RESULTS = []


def check(label, ok, detail=""):
    RESULTS.append(bool(ok))
    tag = "PASS" if ok else "FAIL"
    print(f"[{tag}] {label}" + (f" :: {detail}" if detail else ""))


E3 = np.eye(3, dtype=int)
PAIRS = [(0, 1), (1, 2), (0, 2)]


def key(x, i, j):
    return (tuple(int(c) for c in x), (min(i, j), max(i, j)))


def row_terms(x, j):
    """The landed vector row (G p)_j(x) = p_jj(x + e_j) - p_jj(x) + sum_{i != j} [p_ij(x) - p_ij(x - e_i)]."""
    x = np.array(x)
    t = [(key(x + E3[j], j, j), 1), (key(x, j, j), -1)]
    for i in range(3):
        if i != j:
            t += [(key(x, i, j), 1), (key(x - E3[i], i, j), -1)]
    return t


def planar(x, n_):
    """The planar piece of the landed scalar-gauge pattern at x, in the plane normal to axis n_."""
    a, b = [c for c in range(3) if c != n_]
    x = np.array(x)
    v = {}
    for (j, i) in ((a, b), (b, a)):
        for s in (1, -1):
            v[key(x + s * E3[i], j, j)] = v.get(key(x + s * E3[i], j, j), 0) + 1
        v[key(x, j, j)] = v.get(key(x, j, j), 0) - 2
    i, j = min(a, b), max(a, b)
    for sh, c in [((0, 0, 0), -1), (tuple(-E3[i]), 1), (tuple(-E3[j]), 1), (tuple(-E3[i] - E3[j]), -1)]:
        k = key(x + np.array(sh), i, j)
        v[k] = v.get(k, 0) + c
    return {k: c for k, c in v.items() if c}


def box(R):
    cells = list(itertools.product(range(-R, R + 1), repeat=3))
    slots = [key(x, j, j) for x in cells for j in range(3)] + [key(x, i, j) for x in cells for (i, j) in PAIRS]
    sid = {k: n for n, k in enumerate(slots)}
    rows = []
    for x in itertools.product(range(-R - 1, R + 2), repeat=3):
        for j in range(3):
            v = {}
            for k, c in row_terms(x, j):
                if k in sid:
                    v[sid[k]] = v.get(sid[k], 0) + c
            if v:
                rows.append(v)
    G = np.zeros((len(rows), len(slots)))
    for r, v in enumerate(rows):
        for s, c in v.items():
            G[r, s] = c
    return slots, sid, G


# ------------------------------------------------ 1. the leading moves
slots2, sid2, G2 = box(2)
nS = len(slots2)
KS = [-2, -1, 1, 2]
Dm = np.zeros((nS, 4 * nS))
for s in range(nS):
    for a, k in enumerate(KS):
        Dm[s, 4 * s + a] = k
Gs = csr_matrix(G2) @ csr_matrix(Dm)
one = np.zeros((nS, 4 * nS))
for s in range(nS):
    one[s, 4 * s:4 * s + 4] = 1
l1 = np.array([abs(k) for _ in range(nS) for k in KS], dtype=float)


def min_l1(s0):
    """Smallest L1 norm of an integer move through slot s0 (|entries| <= 4, positive at s0)."""
    cost = np.ones(2 * nS)
    A = np.vstack([np.hstack([G2, -G2]), np.eye(1, 2 * nS, s0) - np.eye(1, 2 * nS, nS + s0)])
    sol = milp(cost, constraints=LinearConstraint(A, [0] * len(G2) + [1], [0] * len(G2) + [2]),
               integrality=np.ones(2 * nS), bounds=Bounds(0, 4), options={"time_limit": 300})
    return sol.status, int(round(sol.fun))


def enumerate_l1(s0, bound):
    cons = [LinearConstraint(Gs, 0, 0), LinearConstraint(csr_matrix(one), 0, 1),
            LinearConstraint(l1[None, :], 1, bound)]
    pos = np.zeros(4 * nS)
    pos[4 * s0 + 2] = pos[4 * s0 + 3] = 1
    cons.append(LinearConstraint(pos[None, :], 1, 1))
    found = []
    while len(found) < 30:
        sol = milp(l1, constraints=cons, integrality=np.ones(4 * nS), bounds=Bounds(0, 1), options={"time_limit": 300})
        if sol.status != 0:
            break
        b = np.round(sol.x).astype(int)
        d = Dm @ b
        found.append({slots2[s]: int(d[s]) for s in range(nS) if d[s]})
        cons.append(LinearConstraint(np.where(b == 1, -1.0, 1.0)[None, :], 1 - b.sum(), np.inf))
    return found


pieces = [planar(x, n_) for x in itertools.product(range(-1, 2), repeat=3) for n_ in range(3)]


def is_piece(mv):
    return any(mv == p or mv == {k: -c for k, c in p.items()} for p in pieces)


d0, f0 = sid2[key((0, 0, 0), 0, 0)], sid2[key((0, 0, 0), 0, 1)]
mins = [min_l1(d0), min_l1(f0)]
through_d, through_f = enumerate_l1(d0, 12), enumerate_l1(f0, 12)
check("the leading moves have L1 norm 12 and are exactly the planar pieces: 6 through a diagonal slot, 4 through a face slot",
      mins == [(0, 12), (0, 12)] and len(through_d) == 6 and len(through_f) == 4
      and all(is_piece(m) for m in through_d + through_f),
      f"smallest L1 through a diagonal and a face slot {[m[1] for m in mins]}; moves of L1 12 found {len(through_d)} and {len(through_f)}, all planar pieces")


# ------------------------------------------------ 2. the path sum
def local_rows(move):
    sl = list(move)
    si = {k: n for n, k in enumerate(sl)}
    rows = {}
    for x0 in {k[0] for k in sl}:
        for dd in itertools.product((-1, 0, 1), repeat=3):
            x = tuple(np.array(x0) + np.array(dd))
            for j in range(3):
                r = {}
                for k, c in row_terms(x, j):
                    if k in si:
                        r[si[k]] = r.get(si[k], 0) + c
                r = {a: b for a, b in r.items() if b}
                if r:
                    rows[(x, j)] = r
    G = np.zeros((len(rows), len(sl)), dtype=int)
    for n, r in enumerate(rows.values()):
        for a, b in r.items():
            G[n, a] = b
    return sl, G


def path_sum(G, d, exact=True):
    mags, sg = np.abs(d), np.sign(d)
    A, inter_zero = {}, 0
    for idx in sorted(itertools.product(*[range(m + 1) for m in mags]), key=sum):
        if sum(idx) == 0:
            A[idx] = Fraction(1) if exact else 1.0
            continue
        tot = sum((A[tuple(i - (k == s) for k, i in enumerate(idx))] for s in range(len(d)) if idx[s] > 0),
                  Fraction(0) if exact else 0.0)
        E = int(np.sum((G @ (sg * np.array(idx))) ** 2))
        if sum(idx) == mags.sum():
            A[idx] = tot
        else:
            inter_zero += E == 0
            A[idx] = tot / (Fraction(E) if exact else E)
    return A[tuple(mags)], inter_zero, len(A)


piece = planar((0, 0, 0), 2)
sl10, G10 = local_rows(piece)
d10 = np.array([piece[k] for k in sl10])
A10, z10, n10 = path_sum(G10, d10)
ring_G = np.array([[1, 0, 0, -1], [-1, 1, 0, 0], [0, -1, 1, 0], [0, 0, -1, 1]])
A_ring, _, _ = path_sum(ring_G, np.array([1, 1, 1, 1]))
check("the order-12 path sum is A = 111150053/31850496; the U(1) ring's is 5/2, matching open PR 9066's 5/32",
      A10 == Fraction(111150053, 31850496) and z10 == 0 and A_ring == Fraction(5, 2) and A_ring / 16 == Fraction(5, 32),
      f"A = {A10} = {float(A10):.6f} over {n10} partial moves, none constraint-satisfying; ring {A_ring}, (h/2)^4 form {A_ring / 16}")

# ------------------------------------------------ 3. exact diagonalization on the path box
mags, sg = np.abs(d10), np.sign(d10)
confs = list(itertools.product(*[range(m + 1) for m in mags]))
cid = {c: i for i, c in enumerate(confs)}
diag = np.array([np.sum((G10 @ (sg * np.array(c))) ** 2) for c in confs], dtype=float)
T = np.zeros((len(confs), len(confs)))
for c in confs:
    for s in range(len(c)):
        if c[s] < mags[s]:
            c2 = list(c)
            c2[s] += 1
            T[cid[c], cid[tuple(c2)]] = T[cid[tuple(c2)], cid[c]] = 1.0
ratios = []
for hU in (0.1, 0.15, 0.2):
    w = np.linalg.eigvalsh(np.diag(diag) - hU * T)
    ratios.append((w[1] - w[0]) / (2 * float(A10) * hU ** 12))
xs = np.array([0.1, 0.15, 0.2]) ** 2
fit = np.polyfit(xs, ratios, 2)
check("exact diagonalization on the 2304-state path box: the splitting over 2 A (h/U)^12 tends to 1",
      int(np.sum(diag == 0)) == 2 and abs(fit[-1] - 1) < 2e-3 and ratios[0] > ratios[1] > ratios[2],
      f"zero-energy configurations {int(np.sum(diag == 0))}; ratio at h/U = 0.1, 0.15, 0.2: "
      + ", ".join(f"{r:.4f}" for r in ratios) + f"; extrapolated to h = 0: {fit[-1]:.4f}")

# ------------------------------------------------ 4. qubit slots: unit moves
def min_unit_support(G, s0):
    n = G.shape[1]
    A = np.vstack([np.hstack([G, np.zeros((len(G), n))]), np.hstack([np.eye(n), -np.eye(n)]),
                   np.hstack([-np.eye(n), -np.eye(n)]), np.eye(1, 2 * n, s0)])
    lb = [0] * len(G) + [-np.inf] * (2 * n) + [1]
    ub = [0] * len(G) + [0] * (2 * n) + [1]
    sol = milp(np.concatenate([np.zeros(n), np.ones(n)]), constraints=LinearConstraint(A, lb, ub),
               integrality=np.ones(2 * n), bounds=Bounds(np.concatenate([-np.ones(n), np.zeros(n)]), np.ones(2 * n)),
               options={"time_limit": 300})
    d = np.round(sol.x[:n]).astype(int)
    return sol.status, {slots2[s]: int(d[s]) for s in range(n) if d[s]} if G is G2 else None


st_d, mv_d = min_unit_support(G2, d0)
st_f, mv_f = min_unit_support(G2, f0)


def unit_path_sum(move):
    sl, G = local_rows(move)
    d = np.array([move[k] for k in sl])
    n = len(d)
    masks = np.arange(1 << n, dtype=np.int64)
    bits = ((masks[:, None] >> np.arange(n)) & 1).astype(np.int64)
    E = np.sum(((bits * d[None, :]) @ G.T) ** 2, axis=1)
    pc = bits.sum(axis=1)
    A = np.zeros(1 << n)
    A[0] = 1.0
    for k in range(1, n + 1):
        layer = masks[pc == k]
        acc = np.zeros(len(layer))
        for s in range(n):
            acc += np.where((layer >> s) & 1, A[layer ^ (1 << s)], 0.0)
        A[layer] = acc if k == n else acc / E[layer]
    return A[-1], int(np.sum((E == 0) & (pc > 0) & (pc < n)))


ps_d, z_d = unit_path_sum(mv_d)
ps_f, z_f = unit_path_sum(mv_f)
# a planar 20-slot unit move (xy plane), found by the same program with another variable order
M_PLANAR = {((-2, -2, 0), (0, 1)): 1, ((-2, -1, 0), (1, 1)): -1, ((-2, 0, 0), (1, 1)): -1, ((-2, 0, 0), (0, 1)): -1,
            ((-1, -2, 0), (0, 0)): -1, ((-1, -1, 0), (0, 0)): 1, ((-1, -1, 0), (1, 1)): 1, ((-1, 0, 0), (0, 0)): 1,
            ((-1, 0, 0), (1, 1)): 1, ((-1, 1, 0), (0, 0)): -1, ((0, -2, 0), (0, 0)): -1, ((0, -2, 0), (0, 1)): -1,
            ((0, -1, 0), (0, 0)): 1, ((0, -1, 0), (1, 1)): 1, ((0, 0, 0), (0, 0)): 1, ((0, 0, 0), (1, 1)): 1,
            ((0, 0, 0), (0, 1)): 1, ((0, 1, 0), (0, 0)): -1, ((1, -1, 0), (1, 1)): -1, ((1, 0, 0), (1, 1)): -1}
slp, Gp = local_rows(M_PLANAR)
planar_ok = not np.any(Gp @ np.array([M_PLANAR[k] for k in slp])) and {k[0][2] for k in M_PLANAR} == {0}
ps_p, z_p = unit_path_sum(M_PLANAR)
spatial = [min(len({k[0][a] for k in mv}) for a in range(3)) > 1 for mv in (mv_d, mv_f)]
check("qubit slots allow only unit changes: the smallest unit moves have 20 slots, so they appear at order 20",
      st_d == 0 and st_f == 0 and len(mv_d) == 20 and len(mv_f) == 20 and z_d == z_f == z_p == 0 and planar_ok
      and len(M_PLANAR) == 20,
      f"unit-move supports through a diagonal and a face slot {len(mv_d)}, {len(mv_f)} (optimal, spatial {spatial}); "
      f"path sums {ps_d:.4g} and {ps_f:.4g}; a planar 20-slot unit move has path sum {ps_p:.4g}; "
      f"no constraint-satisfying partial move")


# ------------------------------------------------ 5. diagonal energies of qubit slots, on balanced surroundings
# A 6^3 torus holds the planar 20-slot move. Surroundings are sampled among zero-charge configurations (every row
# balanced) by a SAT solver with random phases; the move's slots start where the move can act.
Lq = 6


def qkey(x, i, j):
    return (tuple(int(c) % Lq for c in x), (min(i, j), max(i, j)))


qcells = list(itertools.product(range(Lq), repeat=3))
qslots = [qkey(x, j, j) for x in qcells for j in range(3)] + [qkey(x, i, j) for x in qcells for (i, j) in PAIRS]
qsid = {k: n for n, k in enumerate(qslots)}
qrows = [[(qkey(k[0], *k[1]), c) for k, c in row_terms(x, j)] for x in qcells for j in range(3)]
Gq = np.zeros((len(qrows), len(qslots)), dtype=int)
for r, terms in enumerate(qrows):
    for k, c in terms:
        Gq[r, qsid[k]] += c
clauses = []
for terms in qrows:
    lits = [(qsid[k] + 1, c) for k, c in terms]
    for assign in itertools.product((0, 1), repeat=6):
        if sum(c * a for (_, c), a in zip(lits, assign)):
            clauses.append([-v if a else v for (v, _), a in zip(lits, assign)])
qmove = {qkey(np.array(k[0]) + 3, *k[1]): c for k, c in M_PLANAR.items()}
dmove = np.array([qmove.get(k, 0) for k in qslots])
qsup = [qsid[k] for k in qmove]
qout = sorted({t for t in range(len(qslots)) for q in qsup if t not in qsup and np.any(Gq[:, q] * Gq[:, t])})
Eq = np.sum(Gq ** 2, axis=0).astype(float)
qpairs = [(q, t, float(Gq[:, q] @ Gq[:, t])) for q in qsup for t in qout if np.any(Gq[:, q] * Gq[:, t])]


def pair_e4(q, t, o, sq, st):
    Est = Eq[q] + Eq[t] + 2 * sq * st * o
    return -(1 / (Eq[q] * Est * Eq[t]) + 1 / (Eq[q] * Est * Eq[q]) + 1 / (Eq[t] * Est * Eq[q]) + 1 / (Eq[t] * Est * Eq[t]))


diag_pairs = [(qsid[terms[0][0]], qsid[terms[1][0]]) for terms in qrows]
solver = Glucose4(bootstrap_with=clauses)
rngq = np.random.default_rng(20260924)
formula_dev, dNA = 0.0, []
for trial in range(12):
    solver.set_phases([v if rngq.random() < 0.5 else -v for v in range(1, len(qslots) + 1)])
    assert solver.solve(assumptions=[-(qsid[k] + 1) if c == 1 else qsid[k] + 1 for k, c in qmove.items()])
    xq = np.array([1 if lit > 0 else 0 for lit in solver.get_model()[:len(qslots)]])
    sig = 1 - 2 * xq
    dE = sum(pair_e4(q, t, o, -sig[q], sig[t]) - pair_e4(q, t, o, sig[q], sig[t]) for q, t, o in qpairs)
    x2 = xq ^ (dmove != 0)
    NA = sum(xq[a] != xq[b] for a, b in diag_pairs)
    NA2 = sum(x2[a] != x2[b] for a, b in diag_pairs)
    formula_dev = max(formula_dev, abs(dE - 201 / 960 * (NA2 - NA)))
    dNA.append(int(NA2 - NA))
solver.delete()
check("qubit slots get fourth-order diagonal potentials across a move: exactly (201/960) dN_A h^4/U^3 on balanced surroundings",
      formula_dev < 1e-12 and len(set(dNA)) > 2 and not np.any(Gq @ dmove),
      f"{len(qpairs)} slot pairs across the planar move's edge; 12 SAT-sampled zero-charge surroundings: largest deviation from "
      f"(201/960) dN_A {formula_dev:.0e}, dN_A values {sorted(set(dNA))} (N_A counts rows whose two diagonal slots differ)")

# ------------------------------------------------ 6. with an electric energy: the Gaussian spectrum
# Add a one-site electric energy (J/2) sum_s E_s^2 (supplied) and expand the cosines: physical modes live on ker G(k),
# with omega^2 = J g * eig of sum_planes v_p(k) v_p(k)^dag restricted there (v_p the Fourier image of the planar piece).
FACE_IX = {(0, 1): 3, (1, 2): 4, (0, 2): 5}


def G_k(k):
    Gk = np.zeros((3, 6), dtype=complex)
    for j in range(3):
        Gk[j, j] = np.exp(1j * k[j]) - 1
        for i in range(3):
            if i != j:
                Gk[j, FACE_IX[tuple(sorted((i, j)))]] += 1 - np.exp(-1j * k[i])
    return Gk


def piece_k(k, n_):
    a, b = [c for c in range(3) if c != n_]
    v = np.zeros(6, dtype=complex)
    v[a] = 2 * np.cos(k[b]) - 2
    v[b] = 2 * np.cos(k[a]) - 2
    i, j = min(a, b), max(a, b)
    v[FACE_IX[(i, j)]] = -1 + np.exp(-1j * k[i]) + np.exp(-1j * k[j]) - np.exp(-1j * (k[i] + k[j]))
    return v


def branches(k, scalar=False):
    Gk = G_k(k)
    V = np.array([piece_k(k, n_) for n_ in range(3)])
    K = np.linalg.svd(Gk)[2][3:].conj().T
    if scalar:
        # the landed scalar constraint S q = 0 on the conjugate slots: the phase of the summed pieces vanishes
        w = V.sum(axis=0) @ K
        K = K @ np.linalg.svd(w[None, :])[2][1:].conj().T
    return np.linalg.eigvalsh(K.conj().T @ V.conj().T @ V @ K), np.linalg.norm(V @ Gk.conj().T)


rng6 = np.random.default_rng(6)
gauge, small, generic = 0.0, [], []
for _ in range(60):
    k = rng6.uniform(-np.pi, np.pi, 3)
    ev, gv = branches(k)
    gauge = max(gauge, gv)
    generic.append(ev.min() > 1e-8)
    ks = rng6.uniform(-1, 1, 3) * 0.04
    small.append(branches(ks)[0] / np.linalg.norm(ks) ** 4)
small = np.array(small)
on_plane = max(branches(np.array([0.3, 0.2, 0.0]))[0].min(), branches(np.array([0.0, 0.7, 0.4]))[0].min(),
               abs(branches(np.array([0.5, 0.0, 0.9]))[0].min()))
off_plane = branches(np.array([0.3, 0.2, 0.1]))[0].min()
sc_rank = min(int(np.sum(branches(rng6.uniform(-np.pi, np.pi, 3), scalar=True)[0] > 1e-8)) for _ in range(30))
check("with an electric energy the generated curvature cosines give three branches with omega^2 ~ k^4; one vanishes on the planes k_a = 0",
      gauge < 1e-12 and all(generic) and abs(on_plane) < 1e-12 and off_plane > 1e-6 and sc_rank == 2
      and small[:, 1].min() > 0.1 and small.max() < 1.2,
      f"pieces gauge invariant to {gauge:.0e}; all three branches nonzero at 60 random k; omega^2/(J g |k|^4) at small k: "
      f"{small[:, 0].min():.3f}-{small[:, 0].max():.3f}, {small[:, 1].min():.3f}-{small[:, 1].max():.3f}, "
      f"{small[:, 2].min():.3f}-{small[:, 2].max():.3f}; lowest branch {abs(on_plane):.0e} on the coordinate planes, "
      f"{off_plane:.1e} off them; on the scalar-constraint surface S q = 0 two branches remain")

# ------------------------------------------------ 7. modulo 2 the tensor rows are a Z2 gauge structure
def rank_mod2(M):
    M = M.copy() % 2
    r = 0
    for c in range(M.shape[1]):
        piv = [i for i in range(r, M.shape[0]) if M[i, c]]
        if not piv:
            continue
        M[[r, piv[0]]] = M[[piv[0], r]]
        for i in range(M.shape[0]):
            if i != r and M[i, c]:
                M[i] ^= M[r]
        r += 1
        if r == M.shape[0]:
            break
    return r


Lt = 3
tcells = list(itertools.product(range(Lt), repeat=3))


def tw(x):
    return tuple(int(c) % Lt for c in x)


tslots = [key(x, j, j) for x in tcells for j in range(3)] + [key(x, i, j) for x in tcells for (i, j) in PAIRS]
tsid = {k: n for n, k in enumerate(tslots)}
G2mod = np.zeros((3 * len(tcells), len(tslots)), dtype=int)
for r, (x, j) in enumerate((x, j) for x in tcells for j in range(3)):
    for k, c in row_terms(x, j):
        G2mod[r, tsid[(tw(k[0]), k[1])]] += c
G2mod %= 2
faces = [n for n, k in enumerate(tslots) if k[1][0] != k[1][1]]
Gf = G2mod[:, faces]


def cube_move(x):
    v = np.zeros(len(tslots), dtype=int)
    for (i, j) in PAIRS:
        for sh in (0, 1):
            v[tsid[(tw(np.array(x) + sh * E3[3 - i - j]), (i, j))]] ^= 1
    return v


cubes = np.array([cube_move(x)[faces] for x in tcells])
face_kernel = len(faces) - rank_mod2(Gf)
cube_rank = rank_mod2(cubes)
piece_mod2 = np.zeros(len(tslots), dtype=int)
for k, c in planar((1, 1, 1), 2).items():
    piece_mod2[tsid[(tw(k[0]), k[1])]] ^= c % 2
check("modulo 2 the face slots and rows form the dual lattice's Z2 gauge structure; the six-face cube move is its star",
      set(Gf.sum(axis=1)) == {4} and set(Gf.sum(axis=0)) == {4} and not np.any(G2mod @ cube_move((0, 0, 0)) % 2)
      and face_kernel == cube_rank + 3 and not np.any(G2mod @ piece_mod2 % 2) and int(piece_mod2.sum()) == 8,
      f"L = 3 torus: every row meets 4 face slots and every face slot 4 rows; face-slot moves {face_kernel} = "
      f"cube moves {cube_rank} + 3 windings; a planar piece modulo 2 is an 8-slot move through diagonal slots")

print(f"TOTAL: PASS={sum(RESULTS)} FAIL={len(RESULTS) - sum(RESULTS)}")
sys.exit(0 if all(RESULTS) else 1)
