#!/usr/bin/env python3
"""The flavor-carrier identification is structurally isolated as an open input: its delegation chain
terminates in NON-RETAINED notes, and its one candidate mechanism (Axiom 2 locality = the tensor-product
factorization carrier, the PHYSICAL_LATTICE_NECESSITY Part 9 narrative) is GENERATION-BLIND.

Traced 2026-05-31 from FLAVOR_CARRIER_NOT_DERIVED_TWO_INPUTS (PR #2453): the carrier sub-claim was
delegated to PHYSICAL_LATTICE_NECESSITY Parts 7/9. Reading that note + the ledger shows the delegation
DEAD-ENDS:
  - PHYSICAL_LATTICE_NECESSITY_NOTE load-bearing content = the two-invariant Wilson (beta,u_0) rigidity
    no-go (Parts 4/5), UNRELATED to flavor. Parts 7 (physical-species) and 9 (one-axiom substrate) are
    EXPLICITLY narrowed OUT (2026-05-02), surviving only as [LOGICAL] commentary, conditional on the
    sibling single-axiom notes being upgraded to retained-grade.
  - The whole would-be carrier chain is NON-RETAINED on origin/main:
      single_axiom_hilbert_note      = audited_renaming (assumes locality, does not derive it)
      single_axiom_information_note  = meta
      three_generation_chirality_boundary_note = unaudited
      continuum_identification_note  = unaudited
  - EVERY retained note in the neighborhood explicitly brackets the physical-species/flavor bridge as
    out-of-scope / admitted-context:
      three_generation_observable_theorem_note (l.19,151-153,285-288), _m3c_burnside (l.164,179-184),
      generation_axiom_boundary_note (retained_bounded; l.9-15,40-70 'physical-species bridge ... out of scope').

This runner verifies the SUBSTANTIVE structural reason the §9 mechanism cannot supply the carrier, on
the framework's OWN corner structure (Z_2)^3 (8 momentum points; the hw=1 corners ARE the 3 generations):
Axiom 2 locality factorizes the POSITION/site algebra, but the generation/flavor label is a NON-LOCAL
MOMENTUM-space structure -- so a local per-site observable is generation-blind, and the §9 'locality =
factorization carrier' (even if upgraded to retained) lands the observable on the position factor, NOT
the flavor factor. Hence the carrier identification is not reachable from A2/§9; it is a genuine open input.
"""
import itertools
import numpy as np


def check(name, cond, detail=""):
    print(f"[{'PASS' if cond else 'FAIL'}] {name}")
    if detail:
        print(f"       {detail}")
    return bool(cond)


def main():
    passed = []

    sites = list(itertools.product([0, 1], repeat=3))   # 8 position sites n in (Z_2)^3
    moms = list(itertools.product([0, 1], repeat=3))     # 8 momenta k (0<->0, 1<->pi)

    def char(k, n):                                       # character / momentum eigenstate amplitude
        sign = 1
        for ki, ni in zip(k, n):
            if (ki * ni) % 2:
                sign = -sign
        return sign / np.sqrt(8.0)

    psi = {k: np.array([char(k, n) for n in sites]) for k in moms}
    hw1 = [k for k in moms if sum(k) == 1]               # the 3 generations: (1,0,0),(0,1,0),(0,0,1)

    passed.append(check(
        "G1 the hw=1 BZ corners are exactly 3 (the generation triplet) on (Z_2)^3",
        len(hw1) == 3 and sorted(hw1) == [(0, 0, 1), (0, 1, 0), (1, 0, 0)],
        f"hw=1 corners = {sorted(hw1)}"))

    # (i) the generation states are UNIFORMLY DELOCALIZED -> no localization carries a generation label
    delocal = all(np.allclose(np.abs(psi[k]) ** 2, 1.0 / 8.0) for k in hw1)
    passed.append(check(
        "G2 each generation corner state is uniformly delocalized: |amplitude|^2 = 1/8 at EVERY site",
        delocal,
        "the flavor label lives in momentum space, not at any site"))

    # (iv) a LOCAL per-site observable is GENERATION-BLIND: identical expectation across all 3 generations
    P_site0 = np.zeros((8, 8)); P_site0[0, 0] = 1.0
    exps = [float(np.real(psi[k].conj() @ P_site0 @ psi[k])) for k in hw1]
    passed.append(check(
        "G3 a local per-site observable P_site0 has IDENTICAL expectation across the 3 generations (generation-blind)",
        np.allclose(exps, exps[0]) and abs(exps[0] - 1.0 / 8.0) < 1e-12,
        f"<gen_i|P_site0|gen_i> = {np.round(exps,6).tolist()} -> A2's position factorization carries NO generation label"))

    # the generation projectors are FULL position-support (non-local momentum-space objects)
    Pgen = [np.outer(psi[k], psi[k].conj()) for k in hw1]
    full_support = all(np.all(np.abs(P.diagonal()) > 1e-9) for P in Pgen)
    passed.append(check(
        "G4 the generation projectors are FULL position-support (non-local); not generated by any single-site subalgebra",
        full_support,
        "every site participates in each generation projector -> the carrier is a momentum (non-local) structure"))

    # (ii) C_3 axis-shift permutes the 3 corners cyclically (the generation C_3 is a momentum permutation)
    def R(k):
        return (k[2], k[0], k[1])
    perm = [hw1.index(R(k)) for k in hw1]
    passed.append(check(
        "G5 the C_3 axis-shift R permutes the 3 momentum corners cyclically (generation C_3 = momentum permutation)",
        sorted(perm) == [0, 1, 2] and perm != [0, 1, 2],
        f"R-permutation of hw=1 corners = {perm} (cyclic, fixed-point-free on the 3)"))

    # net structural conclusion
    passed.append(check(
        "C1 A2/§9 'locality = factorization carrier' gives the POSITION factor (generation-blind), NOT the flavor factor",
        delocal and np.allclose(exps, exps[0]) and full_support,
        "so the carrier identification is NOT reachable from A2/§9; it remains a genuine open input"))

    print(f"\nSCORECARD PASS={sum(passed)} FAIL={len(passed)-sum(passed)}")
    print("VERDICT: the flavor-carrier delegation chain (PHYSICAL_LATTICE_NECESSITY Parts 7/9) terminates in")
    print("NON-RETAINED notes (single_axiom_hilbert=audited_renaming, single_axiom_information=meta,")
    print("chirality_boundary/continuum_identification=unaudited); EVERY retained generation/lattice note")
    print("brackets the physical-species/flavor bridge out-of-scope. The one candidate mechanism (§9")
    print("locality=tensor-factorization carrier) is GENERATION-BLIND: the generation/flavor label is a")
    print("non-local MOMENTUM-space structure (corners uniformly delocalized; local per-site observable")
    print("identical across generations), so A2's POSITION factorization cannot carry the flavor observable")
    print("on the generation factor. The carrier is a structurally-isolated open input -- not reachable from")
    print("the current retained surface; the named upstream blocker is the non-retained single-axiom-Hilbert")
    print("tensor-factorization narrative (and even granted, it gives the position factor, not the flavor one).")
    print("Provenance verified vs origin/main 2026-05-31: open_gate lepton_brannen_bae_delta_two_ninths;")
    print("retained_no_go physical_lattice_necessity_note / koide_q_delta_residual_cohomology_obstruction;")
    print("retained generation_axiom_boundary_note(_bounded) + three_generation_observable_* (all bracket species);")
    print("audited_renaming single_axiom_hilbert_note; meta single_axiom_information_note; unaudited chirality/continuum.")
    return 0 if all(passed) else 1


if __name__ == "__main__":
    raise SystemExit(main())
