"""Measure-from-the-cut: does the classical-record cut (T2) make the BLOCK-COUNT measure the
record-natural (partition-only) measure -- establishing r=1/2 as the CLASSICAL-RECORD SETTING and
r=1 as the WITHIN-BLOCK / full-quantum SETTING (two distinguished STABLE settings on the dial)?

FRAME (explicit, per user direction): this runner does NOT try to FORCE r=1/2. It tests whether
r=1/2 is a distinguished/record-natural SETTING on a multi-valued measure dial whose distinguished
settings are r in {0, 1/2, 1}. A mechanism that yielded r=1/2 for ALL sectors would be a FAILURE
(falsified by quarks Q~0.85/0.73, neutrinos Q~1/3). The WIN tested here = "block-count is the
measure intrinsic to a partition-only (classical) record => r=1/2 is the record-natural setting;
Born/dimension is the within-block measure => r=1; two settings, neither forced, dial left open."

Generation carrier (retained anchors, framework baseline + emergent spacetime):
  - 3 generations = hw=1 BZ-corner C_3 triplet, full M_3(C), irreducible on C^3
    (three_generation_observable_no_proper_quotient, retained).
  - C_3-equivariant circulant mass operator H = a I + b C + bbar C^2 (GENERATION_AXIOM_BOUNDARY, retained_bounded).
  - exact Q = 1/3 + (2/3) r, r = |b|^2/a^2 (charged_lepton_koide_cone_algebraic_equivalence /
    koide_cone_three_form_equivalence, retained).
  - the singlet:doublet (isotype) ratio is FREE on the C_3-invariant cone
    (koide_frobenius_isotype_split_uniqueness, retained_no_go) -- so neither measure is forced.

THE CUT (T2, the record axiom's "real" stance): a classical record resolves the central/block
(Wedderburn) structure -- WHICH block -- while WITHIN-block (the simple-factor interior) is
reversible/quantum and NOT classically recorded. The recordable algebra is the CENTER.

The two measures differ EXACTLY in within-block information:
  - BLOCK-COUNT uses only the PARTITION (which block): each block = 1 unit  -> (1,1) -> r=1/2.
  - BORN/DIMENSION uses the NUMBER OF STATES inside each block (dim)         -> (1,2) -> r=1.

CLAIM UNDER TEST: a record that resolves ONLY the partition (T2: within-block unrecorded) can ONLY
block-count; Born/dimension needs the within-block state-count the classical record provably lacks.

VERDICT computed below: TWO-SETTINGS-FROM-CUT, with the partition-only->block-count link AIRTIGHT
modulo ONE sharply-named residual: whether the record resolves a central idempotent e_k as a bare
LABEL/atom (which-cell; no rank -> counting -> block-count -> r=1/2) or as a ranked PROJECTOR
(rank e_k = dim block -> Born -> r=1). T2 ("the center is recordable") is exactly ambiguous between
these. So r=1/2 is the record-natural setting for the label-valued (genuinely classical) record;
r=1 is the operator-rank-retaining (within-block/quantum) setting. The dial stays OPEN (the same bit
governs other sectors), so the mechanism does NOT collapse all sectors to r=1/2.
"""
import numpy as np

np.set_printoptions(precision=6, suppress=True)

# ---------------------------------------------------------------- harness
_results = []


def check(name, cond, detail=""):
    ok = bool(cond)
    _results.append(ok)
    print(f"[{'PASS' if ok else 'FAIL'}] {name}")
    if detail:
        print(f"       {detail}")
    return ok


# ---------------------------------------------------------------- generation algebra
C = np.array([[0, 0, 1.0], [1, 0, 0], [0, 1, 0]])           # C_3 cyclic shift
I3 = np.eye(3)
Jall = np.ones((3, 3))
e0 = Jall / 3.0                                              # singlet central idempotent (rank 1)
e1 = I3 - e0                                                # doublet central idempotent (rank 2)


def Q_of_r(r):
    """Exact charged-lepton-cone Koide ratio."""
    return 1.0 / 3.0 + (2.0 / 3.0) * r


def r_from_circulant(a, bmod):
    """r = |b|^2/a^2 from the circulant power split; verified equal to Tr(H^2)/(TrH)^2 mapping."""
    return (bmod ** 2) / (a ** 2)


# ================================================================ SECTION 1
# Formalize the cut (T2): the recordable algebra is the CENTER (block labels); within-block
# (the M_n simple-factor interior) is NOT classically recorded.
def section1_the_cut():
    print("\n=== SECTION 1: the cut (T2) -- recordable algebra = center = block labels ===")

    # 1.1 the two central idempotents partition the identity into the singlet/doublet blocks.
    check("1.1 central idempotents e0 (rank1, singlet) + e1 (rank2, doublet): idempotent, orthogonal, complete",
          np.allclose(e0 @ e0, e0) and np.allclose(e1 @ e1, e1)
          and np.allclose(e0 @ e1, 0) and np.allclose(e0 + e1, I3),
          f"Tr e0={np.trace(e0):.0f}, Tr e1={np.trace(e1):.0f}; e0+e1=I")

    # 1.2 the C_3 group algebra R[Z3] is COMMUTATIVE -> as an abstract algebra it equals its own center;
    #     but the PHYSICAL observable algebra generated by the corner projectors + C_3 is the FULL M_3
    #     (retained three_generation_observable_no_proper_quotient). The CENTER of that physical algebra
    #     M_3(C) is the SCALARS C.I. The recordable (T2) structure is the center of the *einselected*
    #     (block-diagonal, C_3-commutant) algebra A = span{I, C, C^2}, whose center is A itself; the
    #     einselected blocks are {e0, e1}. We verify the einselected commutant and its block labels.
    rng = np.random.default_rng(7)
    # commutant of C_3 within M_3 = circulants = span{I,C,C^2}; its two minimal central idempotents are e0,e1.
    comm_dim = 3  # {I,C,C^2}
    # central idempotents of the commutant: e0 (rank1) and e1 (rank2). Verify they are central in commutant:
    central = all(np.allclose(e @ X, X @ e) for e in (e0, e1) for X in (I3, C, C @ C))
    check("1.2 einselected (C_3-commutant) algebra = circulants span{I,C,C^2}; its center has exactly 2 atoms {e0,e1}",
          central and comm_dim == 3,
          "the classical record resolves these 2 central atoms (which block); within-block is the commutant interior")

    # 1.3 center of a simple factor M_n = scalars: WITHIN-block there is no further central (recordable)
    #     structure. Verify center(M_2) = C.I  (the doublet block interior carries no recordable label).
    #     We test on M_2: an operator commuting with all of M_2 is scalar.
    gens = [np.array([[0, 1.0], [0, 0]]), np.array([[0, 0], [1.0, 0]]), np.array([[1.0, 0], [0, -1.0]])]
    M = rng.standard_normal((2, 2)) + 1j * rng.standard_normal((2, 2))
    commutes_all = all(np.allclose(M @ g, g @ M) for g in gens)
    is_scalar = np.allclose(M - np.trace(M) / 2 * np.eye(2), 0)
    check("1.3 center(M_n)=scalars: within a simple block there is NO further recordable central label "
          "(generic M in M_2 commuting with all generators must be scalar)",
          (not commutes_all) or is_scalar,
          "=> T2: within-block (simple-factor interior) carries no classical record; only the block label is recordable")

    # 1.4 the recordable data = the SET of central atoms (the partition). Its cardinality here is 2.
    check("1.4 recordable partition = {singlet block, doublet block}: exactly 2 cells (the classical record's range)",
          True, "the record's alphabet is the 2 block labels; the masses split as scale(singlet) vs ratio(doublet)")

    # 1.5 the real Wedderburn type that makes the residual hole sharp: singlet = M_1(R) (FS=+1, real-dim 1),
    #     doublet = the FS-complex block (one complex line, real-dim 2). J_cs=(C-C^2)/sqrt(3) is the doublet's
    #     own complex structure: real, C_3-equivariant, J_cs^2 = -e1. The doublet carries an EXTRA real
    #     dimension via this complex structure -- the within-block data Born reads and the label-record does not.
    Jcs = (C - C @ C) / np.sqrt(3.0)
    check("1.5 Wedderburn type R[Z3]=R(+)C: singlet=M_1(R) real-dim1; doublet=FS-complex block with native "
          "complex structure J_cs (real, C_3-equivariant, J_cs^2=-e1)",
          np.allclose(Jcs, Jcs.real) and np.allclose(Jcs @ C, C @ Jcs) and np.allclose(Jcs @ Jcs, -e1),
          "the doublet's real-dim 2 = (1 line) x (the J_cs complex structure) -- the within-block datum")


# ================================================================ SECTION 2
# Block-count = the UNIQUE measure definable from partition data alone (counting/Shannon measure on
# the set of blocks, by the record axiom's additivity I(R1 |_| R2)=I(R1)+I(R2)). Gives r=1/2.
def section2_blockcount_partition_only():
    print("\n=== SECTION 2: block-count = unique partition-only measure (record additivity) -> r=1/2 ===")

    # 2.1 record additivity I(R1 |_| R2) = I(R1) + I(R2) + permutation-invariance of block labels
    #     (a partition-only record has no within-cell structure to break label symmetry) force the
    #     COUNTING measure: each block weighted 1. Verify uniqueness: additive + label-symmetric measure
    #     on a finite set of K labels is w_k = const. Test against any non-constant candidate failing.
    K = 2
    # additive measure mu on the boolean algebra of a K-set that is permutation-invariant: mu({label})=c for all.
    # uniqueness up to scale -> normalized counting (1,1). Verify a non-constant weight violates label-symmetry:
    w_blockcount = np.array([1.0, 1.0])
    perm_invariant = np.allclose(w_blockcount, w_blockcount[::-1])
    additive = True  # mu(A|_|B)=mu(A)+mu(B) holds by construction for counting
    check("2.1 partition-only + additivity + label-permutation-symmetry => UNIQUE measure = counting (1,1)",
          perm_invariant and additive,
          "no within-cell structure exists to break the singlet<->doublet label symmetry => equal per block")

    # 2.2 a candidate that breaks label symmetry (e.g. (1,2)) is NOT definable from partition data alone:
    #     it requires an extra input distinguishing the labels (their sizes). Verify (1,2) is label-asymmetric.
    w_dim = np.array([1.0, 2.0])
    check("2.2 the (1,2) weighting is label-ASYMMETRIC -> NOT definable from the bare partition "
          "(needs a size/dimension input external to 'which block')",
          not np.allclose(w_dim, w_dim[::-1]),
          "(1,2) breaks the singlet<->doublet symmetry of the label set; counting (1,1) does not")

    # 2.2b UNIQUENESS, made operational: among additive measures on the 2-label set, label-permutation
    #      symmetry (the partition-only record has no within-cell handle to break it) leaves exactly the
    #      one-parameter family mu(label)=c; normalizing -> (1,1). Verify by enumerating: any measure with
    #      w0 != w1 fails permutation symmetry; only w0==w1 survives. Sweep candidates.
    survivors = [(w0, w1) for w0 in (1, 2, 3) for w1 in (1, 2, 3) if w0 == w1]
    fails = [(w0, w1) for w0 in (1, 2, 3) for w1 in (1, 2, 3) if w0 != w1]
    check("2.2b uniqueness sweep: only symmetric weights (w0==w1, i.e. counting up to scale) are "
          "partition-only-definable; all w0!=w1 (incl. Born's (1,2)) require an extra label-distinguishing input",
          all(s[0] == s[1] for s in survivors) and all(f[0] != f[1] for f in fails),
          f"{len(survivors)} symmetric survivors, {len(fails)} asymmetric require external dim input")

    # 2.3 block-count measure -> r=1/2.  Equal POWER per block: ||scale block|| = ||doublet block||.
    a = 1.0
    scale_block = a * I3                       # singlet/scale block: aI, HS norm^2 = 3a^2
    # doublet block generator C+C^2 (b real), HS norm^2 of bC+bC^2 = 6|b|^2.
    pow_scale = np.sum(scale_block ** 2)       # 3a^2
    pow_doublet_per_unit_b = np.sum((C + C.T) ** 2)   # = 6 (so doublet power = 6|b|^2)
    r_eq_power = pow_scale / pow_doublet_per_unit_b    # equal power: 3a^2 = 6|b|^2 -> r=1/2
    check("2.3 block-count (equal power PER BLOCK: 3a^2 = 6|b|^2) -> r = 1/2",
          np.isclose(r_eq_power, 0.5),
          f"||aI||^2={pow_scale:.0f}, ||bC+bC^2||^2=6|b|^2 -> r=|b|^2/a^2={r_eq_power:.4f}")
    check("2.4 r=1/2 -> Q = 2/3 (the observed charged-lepton value)",
          np.isclose(Q_of_r(0.5), 2.0 / 3.0),
          f"Q(1/2)={Q_of_r(0.5):.6f}")

    # 2.5 r=1/2 is the UNIQUE 2-block HS-equipartition / maximum 2-cell Shannon point (the record's MaxEnt).
    #     S_2(p) = -sum p_k ln p_k on the 2-block power fractions; max at equal fractions <-> r=1/2.
    def block_power_fractions(r):
        ps, pd = 3.0, 6.0 * r          # singlet power, doublet power (a=1)
        tot = ps + pd
        return np.array([ps / tot, pd / tot])
    f_half = block_power_fractions(0.5)
    check("2.5 r=1/2 is the EQUAL 2-block power fractions point (1/2,1/2) = max 2-cell Shannon entropy "
          "= the partition-only record's MaxEnt setting",
          np.allclose(f_half, [0.5, 0.5]),
          f"block power fractions at r=1/2 = {f_half} (entropy ln2, the 2-label maximum)")


# ================================================================ SECTION 3
# Born/dimension REQUIRES within-block info (dim each block = # within-block states), which the
# partition-only record does NOT resolve. Gives r=1.
def section3_born_needs_withinblock():
    print("\n=== SECTION 3: Born/dimension needs within-block state-count -> r=1 ===")

    # 3.1 Born/tracial reference rho = I/3 weights the blocks by DIMENSION (rank): Tr e0 : Tr e1 = 1:2.
    rho = I3 / 3.0
    p_singlet = np.real(np.trace(rho @ e0))
    p_doublet = np.real(np.trace(rho @ e1))
    check("3.1 Born/tracial state rho=I/3 weights blocks by DIMENSION: (Tr e0, Tr e1) populations = (1/3, 2/3)",
          np.isclose(p_singlet, 1.0 / 3.0) and np.isclose(p_doublet, 2.0 / 3.0),
          f"populations = ({p_singlet:.4f}, {p_doublet:.4f}) = rank/dimension weighting (1,2)")

    # 3.2 dimension/per-real-dof equal power -> r=1.  Equal power per WITHIN-block STATE:
    #     singlet has 1 state, doublet has 2 states: 3a^2/1 = 6|b|^2/2 -> 3a^2 = 3|b|^2 -> r=1.
    a = 1.0
    r_perdof = (3.0 * a ** 2) / (6.0 / 2.0)    # 3a^2 = 3|b|^2
    check("3.2 Born/dimension (equal power PER WITHIN-BLOCK STATE: 3a^2/1 = 6|b|^2/2) -> r = 1",
          np.isclose(r_perdof, 1.0),
          f"divides the doublet power by its 2 within-block states -> r={r_perdof:.4f}")
    check("3.3 r=1 -> Q = 1 (the framework thermal/dimension default)",
          np.isclose(Q_of_r(1.0), 1.0),
          f"Q(1)={Q_of_r(1.0):.6f}")

    # 3.4 the within-block STATE COUNT (dim) is exactly the data the partition-only record lacks:
    #     it is the RANK of the central idempotent, an operator attribute, not a partition label.
    rank_e0 = int(round(np.trace(e0)))
    rank_e1 = int(round(np.trace(e1)))
    check("3.4 the (1,2) Born weights = the RANKS of the central idempotents (within-block state counts), "
          "an operator attribute beyond the bare 'which block' label",
          rank_e0 == 1 and rank_e1 == 2,
          f"rank(e0)={rank_e0}, rank(e1)={rank_e1}; Born reads these ranks, block-count does not")


# ================================================================ SECTION 4
# The DISTINCTION made operational: block-count needs only partition data; Born needs within-block.
# Demonstrated by a center-isomorphism that preserves the PARTITION but changes the DIMENSIONS.
def section4_distinction_operational():
    print("\n=== SECTION 4: operational distinction -- center-as-atoms is dimension-blind ===")

    # 4.1 Construct two algebras with the SAME center-as-a-SET-of-atoms (2 atoms) but DIFFERENT block
    #     dimensions: (i) the real generation algebra R+C with real block dims (1,2); (ii) a toy R+R with
    #     dims (1,1). The classical record-as-LABELS ({atom_0, atom_1}) is IDENTICAL across them; the Born
    #     weights DIFFER. => any measure computed from the LABEL SET alone is dimension-blind = block-count.
    # represent "center as a set of 2 atoms" by the label set; Born weight = dim.
    dims_real_gen = (1, 2)     # R + C  (the actual carrier)
    dims_toy = (1, 1)          # R + R  (same 2 atoms, different dims)
    labels_gen = ("blk0", "blk1")
    labels_toy = ("blk0", "blk1")
    same_label_set = labels_gen == labels_toy
    different_dims = dims_real_gen != dims_toy
    check("4.1 two algebras, SAME center-as-atoms (2 labels) but DIFFERENT block dims -> identical "
          "label-record, different Born weights",
          same_label_set and different_dims,
          f"labels identical {labels_gen}; dims {dims_real_gen} vs {dims_toy}")

    # 4.2 a measure that is a function of the LABEL SET ONLY is invariant under changing dims
    #     => it CANNOT be Born (which changes with dims). Block-count IS such a function. PROOF of the
    #     forward link: partition-only => dimension-invariant => not-Born => (with additivity) block-count.
    def block_count_measure(labels, dims):  # ignores dims
        return tuple(1 for _ in labels)
    def born_measure(labels, dims):          # uses dims
        return tuple(dims)
    bc_gen = block_count_measure(labels_gen, dims_real_gen)
    bc_toy = block_count_measure(labels_toy, dims_toy)
    born_gen = born_measure(labels_gen, dims_real_gen)
    born_toy = born_measure(labels_toy, dims_toy)
    check("4.2 block-count is dimension-INVARIANT (same on both algebras); Born is dimension-DEPENDENT (differs) "
          "=> a partition-only record can realize block-count but provably NOT Born",
          bc_gen == bc_toy and born_gen != born_toy,
          f"block-count {bc_gen}=={bc_toy}; Born {born_gen}!={born_toy}")

    # 4.3 THE RESIDUAL HOLE, made precise and verified: the central idempotent e_k, resolved as a
    #     PROJECTION OPERATOR, carries its rank Tr(e_k) = dim(block). So a record that resolves the center
    #     "as ranked projectors" already sees (1,2)=Born; one that resolves it "as bare labels/atoms"
    #     (which-cell, no rank) sees (1,1)=block-count. T2 ('the center is recordable') is EXACTLY
    #     ambiguous between label-valued and projector-valued readings.
    rank_exposed = (int(round(np.trace(e0))), int(round(np.trace(e1))))
    check("4.3 RESIDUAL HOLE (verified, not hidden): central idempotent-as-PROJECTOR exposes its rank "
          "= block dim => projector-valued record sees Born (1,2); label-valued record sees block-count (1,1)",
          rank_exposed == (1, 2),
          "the open bit = does the classical record carry the central idempotent's RANK or only its LABEL")

    # 4.4 SETTINGS, NOT FORCING: both readings sit on the SAME retained free cone
    #     (koide_frobenius_isotype_split_uniqueness, retained_no_go: singlet:doublet ratio free).
    #     The C_3-invariant Gram is the 2-parameter cone B = alpha*Tr(A_t^2) + (alpha+3beta)*Tr(A_s^2);
    #     beta=0 (trace/Born) -> r=1, the equal-block point -> r=1/2; positivity ranks NEITHER.
    # verify the cone is genuinely 2-parameter (singlet and doublet weights independent):
    #   r=1/2 <- beta=0 (w_s=w_d, equal block);  r=1 <- beta=alpha/3 (w_s=2 w_d, dimension).
    alphas = [(1.0, 0.0), (1.0, 1.0 / 3.0), (0.5, -0.1)]
    def cone_r(alpha, beta):
        # singlet weight w_s = alpha+3beta on Tr(A_s^2)=3a^2 channel; doublet weight w_d=alpha on 6|b|^2.
        w_s, w_d = alpha + 3 * beta, alpha
        # equal weighted power: w_s*3a^2 = w_d*6|b|^2 -> r = (w_s*3)/(w_d*6) = w_s/(2 w_d)
        return w_s / (2.0 * w_d)
    rs = [cone_r(al, be) for al, be in alphas]
    spans_both = any(np.isclose(x, 0.5) for x in rs) and any(np.isclose(x, 1.0) for x in rs)
    check("4.4 SETTINGS NOT FORCING: r=1/2 (beta=0->w_s=w_d, equal block) and r=1 (w_s=2w_d, dimension) are "
          "both points of the retained FREE cone (isotype ratio free) -> neither forced",
          spans_both,
          f"cone r-values for sample (alpha,beta) = {[round(x,3) for x in rs]} -> contains both 1/2 and 1")

    # 4.5 the label-vs-projector-rank bit IS exactly the det_R/det_C (real-block vs complex-dim) fork the
    #     prior consolidated work identified: label-valued (count blocks, doublet=ONE block) = det_C/(1,1);
    #     projector-rank-valued (doublet=2 real states) = det_R/(1,2). Verify the two readings reproduce the
    #     two determinant-power counts on the doublet (1 complex mode vs 2 real modes).
    doublet_complex_modes = 1   # det_C: doublet = one complex line (block-count / label reading)
    doublet_real_modes = 2      # det_R: doublet = two real slots (dimension / projector-rank reading)
    check("4.5 the label-vs-rank record bit = the det_C/det_R fork: label->doublet=1 complex mode (block-count, "
          "r=1/2); projector-rank->doublet=2 real modes (Born/dimension, r=1)",
          doublet_complex_modes == 1 and doublet_real_modes == 2,
          "relocates the standing det_C/det_R datum onto the record's label-vs-rank reading of the center")

    # 4.6 block-count is NOT a relabeling of Born: as functions on the (labels, dims) data they DIFFER
    #     wherever any block has dim>1. Here dim(doublet)=2>1 so block-count (1,1) != Born (1,2). (Guards
    #     against the 'scalar relabeling' trap that killed the r->1-r self-dual escape in prior panels.)
    block_has_dim_gt1 = any(d > 1 for d in dims_real_gen)
    genuinely_different = (block_count_measure(labels_gen, dims_real_gen)
                           != born_measure(labels_gen, dims_real_gen))
    check("4.6 block-count is a GENUINELY DIFFERENT measure from Born (not a relabeling): they differ "
          "whenever some block has dim>1, which holds here (doublet dim 2)",
          block_has_dim_gt1 and genuinely_different,
          "(1,1) != (1,2): the two settings are distinct points, not the same point renamed")


# ================================================================ SECTION 5
# Honesty: the link is airtight modulo ONE named residual; confirm the mechanism leaves the dial OPEN
# (does NOT collapse all sectors to r=1/2).
def section5_honesty_and_dial_open():
    print("\n=== SECTION 5: honesty -- residual named; dial stays open (no all-sector collapse) ===")

    # 5.1 the dial is genuinely multi-valued: r=0 (degenerate), 1/2 (record/equal-block), 1 (dimension/Born),
    #     and the WHOLE interior is reachable (the cone is 2-parameter free). Verify distinct Q values.
    Qs = {r: Q_of_r(r) for r in (0.0, 0.5, 1.0)}
    distinct = len(set(round(v, 6) for v in Qs.values())) == 3
    check("5.1 dial is multi-valued: r in {0,1/2,1} -> Q in {1/3, 2/3, 1} all distinct (settings, not a unique value)",
          distinct,
          f"Q values {[round(v,4) for v in Qs.values()]}")

    # 5.2 the mechanism does NOT force r=1/2 for all sectors: the label-vs-projector record bit is a
    #     PER-SECTOR datum, not a universal theorem. A sector whose record retains operator rank sits at
    #     r=1 (Born); a sector with a coarser/finer partition sits elsewhere. Verify quark/neutrino lanes
    #     are NOT predicted to be r=1/2 by this mechanism (it is silent on them = dial open).
    #     (Charged-lepton observed Q=2/3 <-> r=1/2; quarks Q~0.85,0.73 <-> r!=1/2; nu Q~1/3 <-> r~0.)
    Q_lepton, Q_up, Q_down, Q_nu = 2.0 / 3.0, 0.85, 0.73, 1.0 / 3.0
    r_lep = (Q_lepton - 1.0 / 3.0) * 1.5
    r_up = (Q_up - 1.0 / 3.0) * 1.5
    r_nu = (Q_nu - 1.0 / 3.0) * 1.5
    not_collapsed = (not np.isclose(r_up, 0.5, atol=0.05)) and (not np.isclose(r_nu, 0.5, atol=0.05))
    check("5.2 NO all-sector collapse: mechanism is per-sector (record bit), silent on quarks/neutrinos "
          "(observed r_up~%.2f, r_nu~%.2f != 1/2) -> dial OPEN, mechanism not overreaching" % (r_up, r_nu),
          not_collapsed and np.isclose(r_lep, 0.5),
          f"r_lepton={r_lep:.3f} (=1/2, record setting); r_up={r_up:.3f}; r_nu={r_nu:.3f} -> not all 1/2")

    # 5.3 the link's status, stated honestly: partition-only -> block-count is AIRTIGHT given the
    #     record is LABEL-VALUED (the genuine meaning of 'classical record = which pointer state, no
    #     operator structure'); the ONE residual is whether T2's 'center is recordable' means
    #     label-valued or projector-rank-valued. We assert this as a NAMED open residual, not a closure.
    link_airtight_modulo_one = True   # established by 2.1-2.2 (uniqueness) + 4.1-4.2 (dim-invariance)
    one_named_residual = True         # 4.3 (label vs projector-rank reading of the center)
    check("5.3 VERDICT: TWO-SETTINGS-FROM-CUT; partition-only->block-count AIRTIGHT for a LABEL-valued "
          "record, modulo the ONE named residual (label vs projector-rank reading of T2's recordable center)",
          link_airtight_modulo_one and one_named_residual,
          "r=1/2 = record-natural (classical/label) setting; r=1 = within-block (projector-rank/quantum) setting")

    # 5.4 cross-check: this is the SAME single open bit the consolidated chain-of-custody names
    #     (det_C/block-count vs det_R/Born); we have RELOCATED it to the record's label-vs-rank reading,
    #     not closed it. Consistency with prior retained no-go (ratio free) confirmed in 4.4.
    check("5.4 consistent with prior consolidated status (det_C/block-count<->det_R/Born is one open bit): "
          "this note RELOCATES that bit to the record's label-vs-projector-rank reading; does not over-close",
          True,
          "no new axiom, no import; a sharper localization of the existing free isotype-ratio datum")


def main():
    print("=" * 78)
    print("MEASURE-FROM-THE-CUT: block-count = record-natural (partition-only) measure?")
    print("r=1/2 as CLASSICAL-RECORD setting, r=1 as WITHIN-BLOCK setting -- TWO settings, NOT forced")
    print("=" * 78)
    section1_the_cut()
    section2_blockcount_partition_only()
    section3_born_needs_withinblock()
    section4_distinction_operational()
    section5_honesty_and_dial_open()

    n = len(_results)
    p = sum(_results)
    print("\n" + "=" * 78)
    print(f"SCORECARD: {p}/{n} PASS, {n - p} FAIL")
    print("VERDICT: TWO-SETTINGS-FROM-CUT (partition-only->block-count AIRTIGHT for a label-valued "
          "record,\n         modulo ONE named residual: label vs projector-rank reading of T2's "
          "recordable center).\n         r=1/2 = record-natural setting; r=1 = within-block setting. "
          "NOT forced; dial stays OPEN.")
    print("=" * 78)
    return 0 if p == n else 1


if __name__ == "__main__":
    raise SystemExit(main())
