#!/usr/bin/env python3
"""Runner: the generation weight dial's SHAPE is law-forced; the point on it is unfixed.

Supports docs/KOIDE_GENERATION_WEIGHT_DIAL_SHAPE_FORCED_VALUE_UNFIXED_QUALIFICATION_BOUNDED_THEOREM_NOTE_2026-07-11.md

What is verified (numbered, PASS/FAIL, final TOTAL line):

  T1 (dial shape forced): the invariant-state family of the supplied automorphism
  group on the canonical C3 generation readout carrier C^3 -- generated by the
  cyclic shift U (the supplied C3 action) together with the antiunitary standard-
  basis conjugation K (the supplied readout-context K/CPT exchange of the two
  doublet characters) -- equals exactly {diag(p_s, p_d/2, p_d/2)} in the character
  basis. C3-invariance alone leaves the two doublet weights free; the antiunitary
  exchange forces them equal. The singlet-vs-doublet split is NOT forced: a rank/
  dimension obstruction shows no group element (unitary or antiunitary) carries the
  rank-1 singlet cell onto the rank-2 doublet cell.

  T2 (value unfixed -- admission dichotomy): two lawful, fully invariant rules
  give different r under the ratified component dictionary p_s = a^2, p_d = 2|b|^2,
  r = p_d/(2 p_s): the dimension rule rho = I/3 gives r = 1; the cell-equipartition
  rule rho = diag(1/2,1/4,1/4) gives r = 1/2. Since both are lawful, r is a choice
  not fixed by the supplied structure.

  T3 (consistency corollary): recovers the file-4 facts -- C3 leaves r free; no
  unitary singlet/doublet swap (dims 1 != 2); r = |b|^2/a^2, Q = (1+2r)/3, and
  r = 1/2 iff equal channel energy E_+ = 3a^2 = E_perp = 6|b|^2.

Nothing is hard-coded on the derivation path: r values are computed from the state
weights and the ratified dictionary, not asserted.
"""

import numpy as np
from fractions import Fraction

TOL = 1e-10
PASS = 0
FAIL = 0
_n = 0


def check(cond, desc):
    global PASS, FAIL, _n
    _n += 1
    ok = bool(cond)
    if ok:
        PASS += 1
    else:
        FAIL += 1
    print(f"CHECK {_n:02d}: {'PASS' if ok else 'FAIL'} -- {desc}")
    return ok


# ---------------------------------------------------------------------------
# Supplied structure: C^3 with cyclic shift U, DFT (character) basis, antiunitary K.
# ---------------------------------------------------------------------------
w = np.exp(2j * np.pi / 3)          # primitive cube root of unity
wbar = np.conjugate(w)

# Cyclic shift on C^3:  (U psi)_i = psi_{i-1 mod 3}.
U = np.array([[0, 0, 1],
              [1, 0, 0],
              [0, 1, 0]], dtype=complex)

# DFT / character basis: columns v_k = (1, w^k, w^{2k})/sqrt(3).
F = np.array([[1, 1, 1],
              [1, w, w**2],
              [1, w**2, w**4]], dtype=complex) / np.sqrt(3)


def to_char(M):
    """Express operator M (standard basis) in the character basis."""
    return F.conj().T @ M @ F


def group_linear():
    """The 3 unitary group elements U^0, U^1, U^2 (standard basis)."""
    return [np.linalg.matrix_power(U, k) for k in range(3)]


def act(g_unitary, antilinear, rho):
    """Act on operator rho by group element g = (U^k) or (U^k . K).

    Linear element:      rho -> g rho g^dagger.
    Antilinear element:  rho -> g conj(rho) g^dagger   (K = std-basis conjugation).
    """
    core = np.conjugate(rho) if antilinear else rho
    return g_unitary @ core @ g_unitary.conj().T


def all_group_elements():
    """Full supplied automorphism group: {U^k} and {U^k K}, k=0,1,2 (6 elements)."""
    els = []
    for k in range(3):
        gk = np.linalg.matrix_power(U, k)
        els.append((gk, False))   # linear
        els.append((gk, True))    # antilinear (times K)
    return els


# ---------------------------------------------------------------------------
# CHECK 01 -- U is a unitary of order 3.
# ---------------------------------------------------------------------------
check(np.allclose(U @ U.conj().T, np.eye(3), atol=TOL)
      and np.allclose(np.linalg.matrix_power(U, 3), np.eye(3), atol=TOL)
      and not np.allclose(U, np.eye(3), atol=TOL),
      "U (cyclic shift) is unitary of order 3 (supplied C3 action)")

# ---------------------------------------------------------------------------
# CHECK 02 -- U has three distinct eigenvalues {1, w, wbar}: inequivalent characters.
# ---------------------------------------------------------------------------
ev = np.linalg.eigvals(U)
ev_sorted = sorted(ev, key=lambda z: np.angle(z))
target = sorted([1 + 0j, w, wbar], key=lambda z: np.angle(z))
distinct = min(abs(ev[i] - ev[j]) for i in range(3) for j in range(3) if i != j) > 1e-6
check(np.allclose(ev_sorted, target, atol=TOL) and distinct,
      "U eigenvalues are {1, w, wbar}, all distinct (three inequivalent C3 characters)")

# ---------------------------------------------------------------------------
# CHECK 03 -- F diagonalizes U (character basis exists).
# ---------------------------------------------------------------------------
Uc = to_char(U)
offdiag = Uc - np.diag(np.diag(Uc))
check(np.allclose(offdiag, 0, atol=TOL)
      and distinct,
      "F (DFT) diagonalizes U: U is diag in the character basis with distinct entries")
sing_idx = int(np.argmin(np.abs(np.diag(Uc) - 1.0)))   # singlet = eigenvalue-1 character
doub_idx = [i for i in range(3) if i != sing_idx]

# ---------------------------------------------------------------------------
# CHECK 04 -- Commutant of {I,U,U^2} = circulant algebra (diagonal in char basis).
# A matrix commutes with U iff it is diagonal in the character basis; dim_C = 3.
# ---------------------------------------------------------------------------
# Basis of the commutant: solve [U, X] = 0 for X in M_3(C) (18 real unknowns).
def commutant_dim(gens):
    # Real-linear system: for each generator g (unitary, linear), gX - Xg = 0.
    rows = []
    for g in gens:
        # vec(gX - Xg) = (I kron g - g^T kron I) vec(X)
        A = np.kron(np.eye(3), g) - np.kron(g.T, np.eye(3))
        rows.append(A)
    Amat = np.vstack(rows)
    # complex nullspace dimension
    _, s, _ = np.linalg.svd(Amat)
    rank = int(np.sum(s > 1e-9))
    return 9 - rank

cdim = commutant_dim(group_linear())
# Also: sample a commuting matrix and confirm it is diagonal in char basis.
X = np.diag([2.0, 3.0, 5.0]).astype(complex)      # arbitrary char-diagonal
X_std = F @ X @ F.conj().T
commutes = np.allclose(U @ X_std - X_std @ U, 0, atol=TOL)
check(cdim == 3 and commutes,
      "commutant of the C3 rep has complex dim 3 = circulant algebra (char-diagonal)")

# ---------------------------------------------------------------------------
# CHECK 05 -- C3-invariant Hermitian states are the 3-real-param circulant family;
# in the character basis the two doublet weights are FREE (can be unequal).
# rho = a I + b U + conj(b) U^2, a real, b complex.
# ---------------------------------------------------------------------------
def circulant_state(a, b):
    return a * np.eye(3) + b * U + np.conjugate(b) * (U @ U)

a0 = 1.0
b0 = 0.2 + 0.37j            # non-real b -> unequal doublet weights
rho_c = circulant_state(a0, b0)
c3_inv = np.allclose(U @ rho_c @ U.conj().T - rho_c, 0, atol=TOL)
rho_c_char = np.real(np.diag(to_char(rho_c)))
p1, p2 = rho_c_char[doub_idx[0]], rho_c_char[doub_idx[1]]
check(c3_inv and np.allclose(rho_c, rho_c.conj().T, atol=TOL)
      and abs(p1 - p2) > 1e-3,
      "C3-invariance ALONE leaves the two doublet weights free (p1 != p2 for non-real b)")

# ---------------------------------------------------------------------------
# CHECK 06 -- K (std-basis conjugation) is antiunitary, commutes with U, and
# maps the w-eigenspace to the wbar-eigenspace (doublet-character exchange),
# fixing the singlet eigenspace.
# ---------------------------------------------------------------------------
# Eigenvectors of U:
evals, evecs = np.linalg.eig(U)
def eigvec_for(val):
    i = int(np.argmin(np.abs(evals - val)))
    return evecs[:, i]
v_w = eigvec_for(w)
# K acts on a vector by complex conjugation (standard basis):
Kv_w = np.conjugate(v_w)
# U (K v_w) should be wbar * (K v_w):
maps_to_wbar = np.allclose(U @ Kv_w - wbar * Kv_w, 0, atol=TOL)
# K commutes with the (real) shift U as operators: K U = U K  <=>  conj(U)=U:
commutes_KU = np.allclose(np.conjugate(U), U, atol=TOL)
# Singlet eigenvector is real (fixed by K):
v_s = eigvec_for(1.0)
v_s = v_s / v_s[np.argmax(np.abs(v_s))]
singlet_fixed = np.allclose(np.conjugate(v_s), v_s, atol=TOL)
check(maps_to_wbar and commutes_KU and singlet_fixed,
      "antiunitary K: commutes with real U, swaps w<->wbar doublet eigenspaces, fixes singlet")

# ---------------------------------------------------------------------------
# CHECK 07 -- K-invariance forces b real, i.e., p1 = p2; joint-invariant Hermitian
# state space has real dimension 2 (the one-parameter dial diag(p_s, p_d/2, p_d/2)).
# ---------------------------------------------------------------------------
def project_joint(rho):
    # C3 average (linear projection):
    pc = sum(g @ rho @ g.conj().T for g in group_linear()) / 3.0
    # K average (rho + conj(rho))/2 = Re(rho):
    return (pc + np.conjugate(pc)) / 2.0

# Real dimension of joint-invariant Hermitian states via random sampling of the range.
rng = np.random.default_rng(20260711)
samples = []
for _ in range(60):
    A = rng.standard_normal((3, 3)) + 1j * rng.standard_normal((3, 3))
    H = A + A.conj().T
    samples.append(project_joint(H).reshape(-1))
Mreal = np.array([np.concatenate([s.real, s.imag]) for s in samples])
_, sv, _ = np.linalg.svd(Mreal)
joint_dim = int(np.sum(sv > 1e-8))
# And confirm every projected sample is char-diagonal with equal doublet weights.
allform = True
for s in samples:
    d = to_char(s.reshape(3, 3))
    off = d - np.diag(np.diag(d))
    dd = np.real(np.diag(d))
    if not (np.allclose(off, 0, atol=1e-9)
            and abs(dd[doub_idx[0]] - dd[doub_idx[1]]) < 1e-9):
        allform = False
        break
check(joint_dim == 2 and allform,
      "K-invariance forces p1 = p2: joint-invariant states = {diag(p_s, p_d/2, p_d/2)} (real dim 2)")

# ---------------------------------------------------------------------------
# CHECK 08 -- robustness: random Hermitian rho projected to joint invariants is
# always of the form diag(p, q, q) in the character basis.
# ---------------------------------------------------------------------------
ok08 = True
for _ in range(200):
    A = rng.standard_normal((3, 3)) + 1j * rng.standard_normal((3, 3))
    H = A + A.conj().T
    d = to_char(project_joint(H))
    off = d - np.diag(np.diag(d))
    dd = np.real(np.diag(d))
    if not (np.allclose(off, 0, atol=1e-9)
            and abs(dd[doub_idx[0]] - dd[doub_idx[1]]) < 1e-9):
        ok08 = False
        break
check(ok08, "robustness: 200 random Hermitian states project onto diag(p, q, q)")

# ---------------------------------------------------------------------------
# CHECK 09 -- cell rank obstruction: no group element maps the rank-1 singlet cell
# onto the rank-2 doublet cell (unitary or antiunitary).
# ---------------------------------------------------------------------------
# Cell projectors in the character basis, then transform to standard basis.
Ps_char = np.zeros((3, 3), dtype=complex); Ps_char[sing_idx, sing_idx] = 1.0
Pd_char = np.eye(3, dtype=complex) - Ps_char
Ps = F @ Ps_char @ F.conj().T
Pd = F @ Pd_char @ F.conj().T

def rank_of(P):
    return int(np.sum(np.linalg.svd(P)[1] > 1e-8))

rank_ok = (rank_of(Ps) == 1 and rank_of(Pd) == 2)
no_swap = True
for g, anti in all_group_elements():
    gPs = act(g, anti, Ps)
    if rank_of(gPs) != 1 or np.allclose(gPs, Pd, atol=1e-8):
        no_swap = False
        break
check(rank_ok and no_swap,
      "cell rank obstruction: singlet=rank1, doublet=rank2; no group element maps singlet->doublet")

# ---------------------------------------------------------------------------
# CHECK 10 -- cell orbit obstruction: the singlet cell is invariant under all 6
# group elements; doublet cell likewise; the singlet orbit never meets the doublet.
# ---------------------------------------------------------------------------
singlet_invariant = all(np.allclose(act(g, anti, Ps), Ps, atol=1e-8)
                        for g, anti in all_group_elements())
doublet_invariant = all(np.allclose(act(g, anti, Pd), Pd, atol=1e-8)
                        for g, anti in all_group_elements())
check(singlet_invariant and doublet_invariant,
      "cell orbit obstruction: both cells are group-invariant; split is a free invariant")

# ---------------------------------------------------------------------------
# Ratified component dictionary:  p_s = a^2, p_d = 2|b|^2, r = p_d/(2 p_s).
# For a state rho = diag(p_s, p_d/2, p_d/2) in char basis:
#   P_s = rho_singlet, P_d = sum of the two doublet-char weights, r = P_d/(2 P_s).
# ---------------------------------------------------------------------------
def r_of_state_char(diag_char, exact=False):
    Ps_w = diag_char[sing_idx]
    Pd_w = diag_char[doub_idx[0]] + diag_char[doub_idx[1]]
    if exact:
        return Fraction(Pd_w, 2 * Ps_w)
    return Pd_w / (2.0 * Ps_w)

def is_joint_invariant_state(rho_std):
    return np.allclose(project_joint(rho_std), rho_std, atol=1e-9)

# ---------------------------------------------------------------------------
# CHECK 11 -- T2 dimension rule rho = I/3 is joint-invariant and gives r = 1.
# ---------------------------------------------------------------------------
rho_dim = np.eye(3, dtype=complex) / 3.0
r_dim_num = r_of_state_char(np.real(np.diag(to_char(rho_dim))))
r_dim_exact = r_of_state_char([Fraction(1, 3)] * 3, exact=True)
check(is_joint_invariant_state(rho_dim)
      and abs(r_dim_num - 1.0) < TOL and r_dim_exact == Fraction(1, 1),
      "T2 dimension rule rho = I/3 is invariant and gives r = 1")

# ---------------------------------------------------------------------------
# CHECK 12 -- T2 cell-equipartition rule rho = diag(1/2,1/4,1/4) invariant, r = 1/2.
# Built in the character basis (singlet cell 1/2, each doublet char 1/4).
# ---------------------------------------------------------------------------
cell_char = np.zeros(3)
cell_char[sing_idx] = 0.5
cell_char[doub_idx[0]] = 0.25
cell_char[doub_idx[1]] = 0.25
rho_cell = F @ np.diag(cell_char).astype(complex) @ F.conj().T
r_cell_num = r_of_state_char(np.real(np.diag(to_char(rho_cell))))
exact_char = {sing_idx: Fraction(1, 2), doub_idx[0]: Fraction(1, 4), doub_idx[1]: Fraction(1, 4)}
r_cell_exact = r_of_state_char([exact_char[i] for i in range(3)], exact=True)
check(is_joint_invariant_state(rho_cell)
      and abs(r_cell_num - 0.5) < TOL and r_cell_exact == Fraction(1, 2),
      "T2 cell-equipartition rule rho = diag(1/2,1/4,1/4) is invariant and gives r = 1/2")

# ---------------------------------------------------------------------------
# CHECK 13 -- admission dichotomy witness: both rules lawful & invariant, r differs.
# ---------------------------------------------------------------------------
check(r_dim_exact != r_cell_exact and r_dim_exact == 1 and r_cell_exact == Fraction(1, 2),
      "admission dichotomy: two lawful invariant rules give r = 1 vs r = 1/2 (value not fixed)")

# ---------------------------------------------------------------------------
# CHECK 14 -- T3 dictionary consistency and equal-channel-energy identity.
# For circulant Yukawa Y = aI + bU + conj(b)U^2: E_+ = 3a^2, E_perp = 6|b|^2,
# r = |b|^2/a^2 = p_d/(2 p_s), Q = (1 + 2r)/3, and r = 1/2 iff E_+ = E_perp.
# ---------------------------------------------------------------------------
def energies(a, b):
    return 3 * a**2, 6 * abs(b)**2

ok14 = True
for (a, b) in [(1.0, 1/np.sqrt(2)), (1.0, 0.3), (2.0, 1.9)]:
    ps, pd = a**2, 2 * abs(b)**2
    r = pd / (2 * ps)
    r_direct = abs(b)**2 / a**2
    Ep, Eperp = energies(a, b)
    Q = (1 + 2 * r) / 3
    if not (abs(r - r_direct) < TOL and abs(Q - (1 + 2 * r) / 3) < TOL):
        ok14 = False
    # equal channel energy iff r = 1/2
    if (abs(Ep - Eperp) < TOL) != (abs(r - 0.5) < TOL):
        ok14 = False
# and the r=1/2 point: a^2 = 2|b|^2 gives equal energies exactly
ps_h, pd_h = 1.0, 1.0    # p_s=a^2=1, p_d=2|b|^2=1 => |b|^2=1/2
r_half = pd_h / (2 * ps_h)
check(ok14 and abs(r_half - 0.5) < TOL,
      "T3 dictionary: r = |b|^2/a^2 = p_d/(2 p_s), Q = (1+2r)/3, r=1/2 iff E_+ = E_perp")

# ---------------------------------------------------------------------------
# CHECK 15 -- T3 file-4 recovery: C3 alone leaves the doublet-split coordinate free
# (two C3-invariant states with different doublet weights), and no unitary in the
# supplied group swaps the rank-1 and rank-2 cells (dims 1 != 2).
# ---------------------------------------------------------------------------
# Two distinct C3-invariant states (before the antiunitary) with different splits:
s1 = np.real(np.diag(to_char(circulant_state(1.0, 0.10 + 0.30j))))
s2 = np.real(np.diag(to_char(circulant_state(1.0, 0.40 - 0.10j))))
split1 = s1[doub_idx[0]] - s1[doub_idx[1]]
split2 = s2[doub_idx[0]] - s2[doub_idx[1]]
c3_leaves_free = abs(split1 - split2) > 1e-3
# No unitary in the supplied group swaps cells (dimension obstruction 1 != 2):
no_unitary_swap = True
for g, anti in all_group_elements():
    if anti:
        continue
    gPs = act(g, anti, Ps)
    if rank_of(gPs) != 1:
        no_unitary_swap = False
check(c3_leaves_free and no_unitary_swap and rank_of(Ps) != rank_of(Pd),
      "T3 recovers file-4: C3 leaves the split free; no unitary singlet/doublet swap (1 != 2)")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print("-" * 68)
print("Runner: generation weight dial shape forced, value unfixed (Qualification)")
print("T1 dial shape forced; T2 value unfixed (admission dichotomy); T3 consistency")
print("Supplied elements: C3 shift U (context); antiunitary K/CPT exchange (context)")
print(f"TOTAL: PASS={PASS} FAIL={FAIL}")
