#!/usr/bin/env python3
"""
Finite D,U joint-algebra rank-one-selector no-go (Koide delta support route).

Theorem attempt:
  Test whether the unital *-algebra A_DU generated by the finite L=3
  Wilson-Dirac operator D and the spin lift U of the body-diagonal 120-degree
  lattice rotation contains a rank-one selector on their common zeta
  zero-mode sector.

Result:
  Negative for A_DU only.  At frozen L=3 and r=1.0, the relevant zero-mode
  spin-lift eigenspace has rank two.  The generator restrictions are
  D|M_zeta = 0 and U|M_zeta = zeta I_2, so every element of A_DU restricts to
  a scalar and none is a rank-one projector on M_zeta.

  This is not a no-go for the full Wilson/Clifford construction.  The displayed
  Clifford volume element Gamma=-i gamma_1 gamma_2 gamma_3 commutes with D and
  U and splits M_zeta.  The runner also makes no ambient eta-proxy or
  endpoint-lift claim.

No mass data, fitted Koide value, or selected endpoint target is used.
"""

from __future__ import annotations

import math
import sys

import numpy as np
import sympy as sp

from n5_resolution_certificate import emit_n5_resolution_certificate

AUDIT_INPUT_PATHS = ("scripts/n5_resolution_certificate.py",)


PASSES: list[tuple[str, bool, str]] = []


def record(name: str, ok: bool, detail: str = "") -> None:
    PASSES.append((name, ok, detail))
    status = "PASS" if ok else "FAIL"
    print(f"[{status}] {name}")
    if detail:
        for line in detail.splitlines():
            print(f"       {line}")


def section(title: str) -> None:
    print()
    print("=" * 88)
    print(title)
    print("=" * 88)


def clifford_generators() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
    sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
    sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)

    return (
        np.kron(sigma_y, sigma_x),
        np.kron(sigma_y, sigma_y),
        np.kron(sigma_y, sigma_z),
    )


def build_wilson_lattice(r: float = 1.0) -> tuple[np.ndarray, np.ndarray, list[tuple[int, int, int]]]:
    sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
    sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
    sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
    I2 = np.eye(2, dtype=complex)

    gamma_1, gamma_2, gamma_3 = clifford_generators()

    n_hat = np.array([1, 1, 1]) / math.sqrt(3)
    n_dot_sigma = n_hat[0] * sigma_x + n_hat[1] * sigma_y + n_hat[2] * sigma_z
    U_sigma = math.cos(math.pi / 3) * I2 - 1j * math.sin(math.pi / 3) * n_dot_sigma
    U_spin = np.kron(I2, U_sigma)

    L = 3
    N = L**3

    def idx(x: int, y: int, z: int) -> int:
        return (x % L) * L**2 + (y % L) * L + (z % L)

    translations = [np.zeros((N, N), dtype=complex) for _ in range(3)]
    for x in range(L):
        for y in range(L):
            for z in range(L):
                translations[0][idx(x + 1, y, z), idx(x, y, z)] = 1
                translations[1][idx(x, y + 1, z), idx(x, y, z)] = 1
                translations[2][idx(x, y, z + 1), idx(x, y, z)] = 1

    P_site = np.zeros((N, N), dtype=complex)
    fixed_sites: list[tuple[int, int, int]] = []
    for x in range(L):
        for y in range(L):
            for z in range(L):
                P_site[idx(z, x, y), idx(x, y, z)] = 1
                if x == y == z:
                    fixed_sites.append((x, y, z))

    U_full = np.kron(U_spin, P_site)
    D_kinetic = sum(
        np.kron(gamma, (T - T.conj().T) / (2j))
        for gamma, T in zip([gamma_1, gamma_2, gamma_3], translations)
    )
    wilson_op = sum((2 * np.eye(N) - T - T.conj().T) / 2 for T in translations)
    D = D_kinetic + r * np.kron(np.eye(4), wilson_op)
    return D, U_full, fixed_sites


def exact_k_zero_character_projector() -> tuple[sp.Matrix, sp.Matrix, sp.Expr]:
    """Independent exact check of the constant-site character multiplicity.

    At k=0 every translation is the identity, hence both the kinetic and
    Wilson terms vanish for every r.  The remaining spin lift is

        I_2 tensor [I_2 - i(sigma_x + sigma_y + sigma_z)] / 2.

    Its zeta=e^(i*pi/3) spectral projector has exact rank two.
    """

    sigma_x = sp.Matrix([[0, 1], [1, 0]])
    sigma_y = sp.Matrix([[0, -sp.I], [sp.I, 0]])
    sigma_z = sp.Matrix([[1, 0], [0, -1]])
    I2 = sp.eye(2)
    I4 = sp.eye(4)
    U_sigma = (I2 - sp.I * (sigma_x + sigma_y + sigma_z)) / 2
    U_spin = sp.kronecker_product(I2, U_sigma)
    zeta = (1 + sp.I * sp.sqrt(3)) / 2
    zeta_bar = sp.conjugate(zeta)
    projector = sp.simplify((U_spin - zeta_bar * I4) / (zeta - zeta_bar))
    return U_spin, projector, zeta


def exact_l3_r1_nonzero_mode_gaps() -> tuple[
    bool, list[tuple[int, sp.Expr, sp.Expr, sp.Expr]]
]:
    """Exact Fourier-block certificate that only k=0 can be a zero mode.

    For periodic L=3, each momentum component is 0 or +/-2*pi/3.  If m is
    the number of nonzero components, the r=1 Wilson scalar is W=3m/2 and
    the squared kinetic magnitude is s^2=3m/4.  The Clifford relations give
    block eigenvalues W +/- sqrt(s^2), each twice.  W^2-s^2>0 for m=1,2,3,
    so every nonconstant momentum block is invertible.
    """

    sigma_x = sp.Matrix([[0, 1], [1, 0]])
    sigma_y = sp.Matrix([[0, -sp.I], [sp.I, 0]])
    sigma_z = sp.Matrix([[1, 0], [0, -1]])
    gammas = [
        sp.kronecker_product(sigma_y, sigma)
        for sigma in (sigma_x, sigma_y, sigma_z)
    ]
    I4 = sp.eye(4)
    clifford_ok = all(
        sp.simplify(g_i * g_j + g_j * g_i - (2 if i == j else 0) * I4)
        == sp.zeros(4)
        for i, g_i in enumerate(gammas)
        for j, g_j in enumerate(gammas)
    )

    rows: list[tuple[int, sp.Expr, sp.Expr, sp.Expr]] = []
    for m in (1, 2, 3):
        wilson_scalar = sp.Rational(3 * m, 2)
        kinetic_sq = sp.Rational(3 * m, 4)
        squared_separation = sp.simplify(wilson_scalar**2 - kinetic_sq)
        rows.append((m, wilson_scalar, kinetic_sq, squared_separation))

    gaps_ok = all(
        bool(wilson_scalar > 0 and squared_separation > 0)
        for _, wilson_scalar, _, squared_separation in rows
    )
    return clifford_ok and gaps_ok, rows


def zero_character_lines(D: np.ndarray, U: np.ndarray) -> tuple[np.ndarray, np.ndarray, complex]:
    eigs, vecs = np.linalg.eigh(D)
    zero_indices = np.where(np.abs(eigs) < 1e-8)[0]
    zero_basis = vecs[:, zero_indices]
    U_zero = zero_basis.conj().T @ U @ zero_basis
    u_eigs, u_vecs = np.linalg.eig(U_zero)
    zeta = np.exp(1j * math.pi / 3)
    zeta_indices = [i for i, value in enumerate(u_eigs) if abs(value - zeta) < 1e-8]
    if len(zeta_indices) != 2:
        raise RuntimeError(f"expected two zeta zero modes, got {len(zeta_indices)}")
    line_0 = zero_basis @ u_vecs[:, zeta_indices[0]]
    line_1 = zero_basis @ u_vecs[:, zeta_indices[1]]
    line_0 = line_0 / np.linalg.norm(line_0)
    # Gram-Schmidt protects against numerical non-orthogonality in the U eigensolver.
    line_1 = line_1 - line_0 * np.vdot(line_0, line_1)
    line_1 = line_1 / np.linalg.norm(line_1)
    return line_0, line_1, zeta


def main() -> int:
    section("A. Finite Wilson-Dirac support model")

    r = 1.0
    D, U, fixed_sites = build_wilson_lattice(r)
    identity = np.eye(D.shape[0], dtype=complex)
    record(
        "A.1 finite D,U matrices have the stated Hermiticity and lifted-rotation relations",
        np.linalg.norm(D - D.conj().T) < 1e-10
        and np.linalg.norm(U @ U.conj().T - identity) < 1e-10
        and np.linalg.norm(U @ D @ U.conj().T - D) < 1e-10
        and np.linalg.norm(np.linalg.matrix_power(U, 3) + identity) < 1e-10,
        f"||D-D†||={np.linalg.norm(D - D.conj().T):.2e}; "
        f"||UU†-I||={np.linalg.norm(U @ U.conj().T - identity):.2e}; "
        f"||UDU†-D||={np.linalg.norm(U @ D @ U.conj().T - D):.2e}; "
        f"||U^3+I||={np.linalg.norm(np.linalg.matrix_power(U, 3) + identity):.2e}",
    )
    record(
        "A.2 body-diagonal action has three fixed sites",
        fixed_sites == [(0, 0, 0), (1, 1, 1), (2, 2, 2)],
        f"fixed_sites={fixed_sites}",
    )

    U_k0, P_zeta_k0, zeta_exact = exact_k_zero_character_projector()
    exact_k0_ok = (
        P_zeta_k0.rank() == 2
        and sp.simplify(P_zeta_k0 * P_zeta_k0 - P_zeta_k0) == sp.zeros(4)
        and sp.simplify(U_k0 * P_zeta_k0 - zeta_exact * P_zeta_k0) == sp.zeros(4)
    )
    record(
        "A.3 exact k=0 spin lift has a rank-two zeta eigenprojector",
        exact_k0_ok,
        "D(k=0)=0 for every r; rank(P_zeta)=2 and U_spin P_zeta=zeta P_zeta exactly.",
    )

    exact_momentum_ok, momentum_rows = exact_l3_r1_nonzero_mode_gaps()
    record(
        "A.4 exact L=3 momentum blocks exclude nonconstant zero modes at r=1",
        exact_momentum_ok,
        "\n".join(
            f"m={m}: W={wilson_scalar}, |s|^2={kinetic_sq}, W^2-|s|^2={squared_separation}>0"
            for m, wilson_scalar, kinetic_sq, squared_separation in momentum_rows
        ),
    )

    section("B. D,U-generated algebra on the common zero-mode eigenspace")

    eigs, vecs = np.linalg.eigh(D)
    zero_indices = np.where(np.abs(eigs) < 1e-8)[0]
    zero_basis = vecs[:, zero_indices]
    U_zero = zero_basis.conj().T @ U @ zero_basis
    u_eigs = np.linalg.eigvals(U_zero)
    zeta = np.exp(1j * math.pi / 3)
    zeta_bar = np.conjugate(zeta)
    zeta_count = sum(abs(value - zeta) < 1e-8 for value in u_eigs)
    zeta_bar_count = sum(abs(value - zeta_bar) < 1e-8 for value in u_eigs)
    record(
        "B.1 Wilson zero-mode space has dimension four",
        len(zero_indices) == 4,
        f"zero eigenvalues={len(zero_indices)}",
    )
    record(
        "B.2 each spin-lift eigenvalue over the body-diagonal rotation has multiplicity two in the zero-mode space",
        zeta_count == 2 and zeta_bar_count == 2,
        f"counts: exp(+i*pi/3)={zeta_count}, exp(-i*pi/3)={zeta_bar_count}",
    )

    line_0, line_1, character = zero_character_lines(D, U)
    line_checks = []
    selected_weights = []
    family_joint_ok = True
    for alpha in [0.0, math.pi / 6, math.pi / 4, math.pi / 3, math.pi / 2]:
        psi = math.cos(alpha) * line_0 + math.sin(alpha) * line_1
        psi = psi / np.linalg.norm(psi)
        d_err = np.linalg.norm(D @ psi)
        u_err = np.linalg.norm(U @ psi - character * psi)
        family_joint_ok = family_joint_ok and d_err < 1e-10 and u_err < 1e-10
        selected_weight = abs(np.vdot(line_0, psi)) ** 2
        selected_weights.append(round(float(selected_weight), 12))
        line_checks.append(
            f"alpha={alpha:.6f}: ||D psi||={d_err:.2e}, "
            f"||U psi-zeta psi||={u_err:.2e}, "
            f"selected_weight={selected_weight:.6f}"
        )
    record(
        "B.3 a sampled CP1 slice has the same D zero-mode and U eigenvalue data",
        len(set(selected_weights)) == 5 and family_joint_ok,
        "\n".join(line_checks),
    )

    character_basis = np.column_stack([line_0, line_1])
    D_restricted = character_basis.conj().T @ D @ character_basis
    U_restricted = character_basis.conj().T @ U @ character_basis
    joint_scalar_ok = (
        np.linalg.norm(D_restricted) < 1e-10
        and np.linalg.norm(U_restricted - character * np.eye(2)) < 1e-10
    )
    record(
        "B.4 the D,U-generated joint algebra is scalar on the rank-two zeta eigenspace",
        joint_scalar_ok,
        f"||D|M_zeta||={np.linalg.norm(D_restricted):.2e}; "
        f"||U|M_zeta-zeta I2||={np.linalg.norm(U_restricted-character*np.eye(2)):.2e}",
    )

    section("C. Basis-independence obstruction")

    beta = math.pi / 5
    basis_rotation = np.array(
        [[math.cos(beta), -math.sin(beta)], [math.sin(beta), math.cos(beta)]],
        dtype=complex,
    )
    rotated_basis = character_basis @ basis_rotation
    rotated_D = rotated_basis.conj().T @ D @ rotated_basis
    rotated_U = rotated_basis.conj().T @ U @ rotated_basis
    rotated_joint_ok = (
        np.linalg.norm(rotated_basis.conj().T @ rotated_basis - np.eye(2)) < 1e-10
        and np.linalg.norm(rotated_D) < 1e-10
        and np.linalg.norm(rotated_U - character * np.eye(2)) < 1e-10
    )
    full_rotation = (
        np.eye(D.shape[0], dtype=complex)
        + character_basis @ (basis_rotation - np.eye(2)) @ character_basis.conj().T
    )
    full_rotation_ok = (
        np.linalg.norm(full_rotation.conj().T @ full_rotation - np.eye(D.shape[0])) < 1e-10
        and np.linalg.norm(full_rotation @ D - D @ full_rotation) < 1e-10
        and np.linalg.norm(full_rotation @ U - U @ full_rotation) < 1e-10
    )
    record(
        "C.1 a nontrivial U(2) automorphism leaves the joint D,U data unchanged",
        rotated_joint_ok and full_rotation_ok,
        f"beta={beta:.12f}; ||D_rot||={np.linalg.norm(rotated_D):.2e}; "
        f"||U_rot-zeta I2||={np.linalg.norm(rotated_U-character*np.eye(2)):.2e}; "
        f"||[R,D]||={np.linalg.norm(full_rotation@D-D@full_rotation):.2e}; "
        f"||[R,U]||={np.linalg.norm(full_rotation@U-U@full_rotation):.2e}",
    )

    projector_0 = np.outer(line_0, np.conjugate(line_0))
    projector_1 = np.outer(line_1, np.conjugate(line_1))
    record(
        "C.2 distinct rank-one projectors have identical D and U eigen-data",
        np.linalg.norm(projector_0 - projector_1) > 1.0
        and np.linalg.norm(D @ projector_0) < 1e-10
        and np.linalg.norm(D @ projector_1) < 1e-10
        and np.linalg.norm(U @ projector_0 - character * projector_0) < 1e-10
        and np.linalg.norm(U @ projector_1 - character * projector_1) < 1e-10,
        f"||P0-P1||={np.linalg.norm(projector_0-projector_1):.12f}",
    )

    zero_projector = character_basis @ character_basis.conj().T
    generator_restrictions = [
        D_restricted,
        U_restricted,
        character_basis.conj().T @ U.conj().T @ character_basis,
        character_basis.conj().T @ zero_projector @ character_basis,
    ]
    generators_scalar = all(
        np.linalg.norm(matrix - np.trace(matrix) * np.eye(2) / 2) < 1e-10
        for matrix in generator_restrictions
    )
    rank_one_restriction = character_basis.conj().T @ projector_0 @ character_basis
    rank_one_is_extra = (
        np.linalg.norm(rank_one_restriction - np.trace(rank_one_restriction) * np.eye(2) / 2)
        > 0.5
    )
    record(
        "C.3 no element of the D,U-generated joint algebra restricts to a rank-one selector",
        generators_scalar and rank_one_is_extra,
        f"generator restrictions scalar={generators_scalar}; "
        f"rank-one nonscalar norm={np.linalg.norm(rank_one_restriction-np.eye(2)/2):.12f}",
    )

    section("D. Hostile-review objections")

    record(
        "D.1 eigensolver ordering cannot be used as a canonical selector",
        rotated_joint_ok and np.linalg.norm(rotated_basis[:, 0] - line_0) > 0.1,
        "A nontrivial basis rotation changes the first reported line while preserving D|M_zeta and U|M_zeta.",
    )

    gamma_1, gamma_2, gamma_3 = clifford_generators()
    gamma_chirality = -1j * gamma_1 @ gamma_2 @ gamma_3
    Gamma = np.kron(gamma_chirality, np.eye(27, dtype=complex))
    gamma_restricted = character_basis.conj().T @ Gamma @ character_basis
    gamma_eigenvalues = np.linalg.eigvalsh(gamma_restricted)
    gamma_split_ok = (
        np.linalg.norm(Gamma - Gamma.conj().T) < 1e-10
        and np.linalg.norm(Gamma @ Gamma - np.eye(D.shape[0])) < 1e-10
        and np.linalg.norm(Gamma @ D - D @ Gamma) < 1e-10
        and np.linalg.norm(Gamma @ U - U @ Gamma) < 1e-10
        and np.allclose(gamma_eigenvalues, [-1.0, 1.0], atol=1e-10)
    )
    record(
        "D.2 Clifford volume element is a counter-route outside the D,U-generated algebra",
        gamma_split_ok,
        f"||[Gamma,D]||={np.linalg.norm(Gamma@D-D@Gamma):.2e}; "
        f"||[Gamma,U]||={np.linalg.norm(Gamma@U-U@Gamma):.2e}; "
        f"eig(Gamma|M_zeta)={gamma_eigenvalues.tolist()}",
    )

    section("E. Verdict")

    no_go_core = (
        exact_k0_ok
        and exact_momentum_ok
        and joint_scalar_ok
        and rotated_joint_ok
        and full_rotation_ok
        and generators_scalar
        and rank_one_is_extra
    )
    record(
        "E.1 the D,U-generated unital star algebra contains no rank-one selector on M_zeta",
        no_go_core,
        (
            "The rank-two zeta zero-mode sector is not split by the D,U-generated algebra."
            if no_go_core
            else "No residual is certified because the core D,U joint-algebra checks failed."
        ),
    )
    record(
        "E.2 the full Wilson/Clifford construction is explicitly outside the no-go",
        no_go_core and gamma_split_ok,
        "The displayed Clifford volume element splits M_zeta; ambient eta proxies and endpoint lifts are not claimed.",
    )

    print()
    n_pass = sum(1 for _, ok, _ in PASSES if ok)
    n_total = len(PASSES)
    print("=" * 88)
    print("Summary")
    print("=" * 88)
    print(f"PASSED: {n_pass}/{n_total}")
    for name, ok, _ in PASSES:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")

    emit_n5_resolution_certificate(
        per_element=(
            np.linalg.norm(D - D.conj().T) < 1e-10
            and np.linalg.norm(U.conj().T @ U - np.eye(U.shape[0])) < 1e-10,
            "the executed finite Wilson Dirac element is Hermitian and the order-three translation element is unitary",
        ),
        per_site=(
            D.shape == (4 * 3**3, 4 * 3**3)
            and exact_k0_ok
            and exact_momentum_ok,
            "no per-site selector claim is made; the exact Fourier construction covers all 27 sites of the periodic L=3 cubical lattice",
        ),
        per_mode=(
            joint_scalar_ok and rotated_joint_ok,
            "both zeta-sector eigenline modes remain degenerate under D and U, including after a nontrivial basis rotation",
        ),
        per_block=(
            generators_scalar and rank_one_is_extra,
            "every D,U-generated block restricts to a scalar on the rank-two sector, while the displayed rank-one split is outside that algebra",
        ),
        lattice_wide=(
            no_go_core and gamma_split_ok,
            "the complete finite periodic L=3 lattice and its D,U algebra were executed; a Clifford-volume counter-route is explicitly outside the no-go scope",
        ),
    )

    print()
    if n_pass == n_total:
        print("VERDICT: the D,U-generated unital star algebra contains no rank-one selector on M_zeta.")
        print("KOIDE_DELTA_D_U_JOINT_ALGEBRA_RANK_ONE_SELECTOR_NO_GO=TRUE")
        print("D_U_JOINT_ALGEBRA_CONTAINS_RANK_ONE_SELECTOR=FALSE")
        print("D_U_JOINT_ALGEBRA_CLOSES_RANK_ONE_SELECTION=FALSE")
        print("DELTA_LATTICE_WILSON_SELECTED_EIGENLINE_CLOSES_DELTA=FALSE")
        print("RESIDUAL_EIGENLINE=rank_two_zeta_zero_mode_sector_not_split_by_D_U_generated_algebra")
        print("CLAIM_SCOPE=finite_periodic_L3_r1_unital_star_algebra_generated_by_D_and_U_only")
        print("FULL_WILSON_CLIFFORD_SELECTOR_NO_GO_CLAIMED=FALSE")
        print("AMBIENT_ETA_PROXY_USED=FALSE")
        print("ENDPOINT_LIFT_CLAIMED=FALSE")
        return 0

    print("VERDICT: D,U-generated unital-star-algebra check has FAILs.")
    print("KOIDE_DELTA_D_U_JOINT_ALGEBRA_RANK_ONE_SELECTOR_NO_GO=FALSE")
    print("D_U_JOINT_ALGEBRA_CONTAINS_RANK_ONE_SELECTOR=UNDETERMINED")
    print("D_U_JOINT_ALGEBRA_CLOSES_RANK_ONE_SELECTION=UNDETERMINED")
    print("DELTA_LATTICE_WILSON_SELECTED_EIGENLINE_CLOSES_DELTA=FALSE")
    print("RESIDUAL_EIGENLINE=undetermined_due_to_failed_runner_checks")
    print("CLAIM_SCOPE=finite_periodic_L3_r1_unital_star_algebra_generated_by_D_and_U_only")
    print("FULL_WILSON_CLIFFORD_SELECTOR_NO_GO_CLAIMED=FALSE")
    print("AMBIENT_ETA_PROXY_USED=FALSE")
    print("ENDPOINT_LIFT_CLAIMED=FALSE")
    return 1


if __name__ == "__main__":
    sys.exit(main())
