#!/usr/bin/env python3
"""
beta=6 SU(3) Wilson plaquette: the four-cube-shell sector of the connected
series Delta(beta) is an exact closed-form all-orders generating function
=========================================================================

Exact/symbolic companion runner for the bounded note

    docs/BETA6_PLAQUETTE_CUBE_SECTOR_CLOSED_FORM_GENERATING_FUNCTION_NOTE_2026-05-31.md

Statement
---------
Let J(beta) = sum_{N>=0} a_N beta^N be the single-plaquette character generating
function defined by the on-main order-3 dominant-weight recurrence
(the Picard-Fuchs / character recurrence reproduced on main in
scripts/frontier_beta6_delta_analytic_class_2026_05_30.py and the V1 Picard-Fuchs
notes):

    6 (N+1)(N+4)(N+5) a_{N+1} = N(N+1) a_N + 2(2N+3) a_{N-1} + a_{N-2},
    a_0 = 1, a_1 = 0, a_2 = 1/36.

Put K(beta) = log J(beta) (so K' = J'/J = P_1plaq, the single-plaquette
character mean; K'' its variance). Then the connected contribution of the four
elementary cube shells through the marked plaquette to Delta(beta) is, order by
order, the Taylor series of the closed form

    Delta_cube(beta) = 72 * K''(beta) * (K'(beta))^5.

Its Taylor coefficients reproduce EXACTLY the on-main connected coefficients
    d_5 = 1/472392 = 4/18^5,
    d_6 = 7/5668704,
    d_7 = 5/17006112,
the order-beta^8 coefficient (BETA6_PLAQUETTE_D8 note / PR #2408)
    d_8 = 5/272097792,
and the cube-sector part of d_9 = -235/29386561536. The closed form is
IMPORT-FREE: it is built from the on-main recurrence and exact rational
arithmetic only -- no Monte-Carlo value, no fitted parameter, no imported
literature coefficient. (The Bars 1980 Bessel-determinant closed form for J and
the Munster/Drouffe-Zuber strong-coupling tables are methodology comparators
only; J here is generated by the on-main recurrence, not imported.)

Linked-cluster origin: a single cube shell has 6 faces -- the marked plaquette
p0 (carrying the observable, hence a connected 2-cumulant K'') and 5 action
faces (each a 1-cumulant K'); resumming all multiplicity insertions on the faces
replaces each per-face factor by the full beta-dependent K'',K'. The constant
72 = 4 shells * 18 fixes the leading term to 72*(1/18)*(1/18)^5 = 4/18^5 = d_5.

Singularity diagnostic and scope
--------------------------------
Delta_cube's only singularities are the zeros of J (poles of K=log J). The SU(3)
Haar-integral form makes J(beta) positive for real beta, and this runner samples
J(beta) > 0 on [0,8]. Newton iteration on the recurrence-generated J locates a
complex-conjugate zero witness at beta = 8.2052 * exp(+- i 66.152 deg). This is
radius evidence, not an argument-principle or interval proof that no zero of J
lies inside |beta|=6.

This is the CUBE SECTOR ONLY. By the GF(3) cycle-space certificate
(BETA6_PLAQUETTE_D8 note / PR #2408), Delta = (four-cube-shell sector) EXACTLY
through d_8 (2-cycle weights 7,8,9 are empty), but the FULL Delta reopens at
order beta^9 with new two-cube-overlap (non-O_h) topologies that this closed
form does NOT organize. Hence this is NOT a closure of Delta or of beta=6; it
resums one sector to all orders as a formal expression and leaves full-radius
control to separate zero-free/growth work.

Type: bounded_theorem (companion runner). No new tags, no new vocabulary, no
promotion language.

Run:
  python3 scripts/frontier_beta6_cube_sector_closed_form_gf.py
"""

from __future__ import annotations

from fractions import Fraction

import sympy as sp

PASS = 0
FAIL = 0


def check(name: str, cond: bool, detail: str = "") -> None:
    global PASS, FAIL
    ok = bool(cond)
    PASS += ok
    FAIL += (not ok)
    tag = "PASS" if ok else "FAIL"
    print(f"[{tag}] {name}" + (f"  |  {detail}" if detail else ""))


def j_coeffs(n_max: int):
    a = {0: Fraction(1), 1: Fraction(0), 2: Fraction(1, 36)}
    for n in range(2, n_max):
        a[n + 1] = (Fraction(n * (n + 1)) * a[n]
                    + Fraction(2 * (2 * n + 3)) * a[n - 1]
                    + a[n - 2]) / Fraction(6 * (n + 1) * (n + 4) * (n + 5))
    return a


def main() -> int:
    NORD = 12
    a = j_coeffs(NORD + 2)
    check("recurrence a_0,a_1,a_2 = 1,0,1/36",
          a[0] == 1 and a[1] == 0 and a[2] == Fraction(1, 36))

    # ---- closed form Delta_cube = 72 K'' (K')^5, K = log J -----------------
    b = sp.symbols("b")
    J = sum(sp.Rational(a[n].numerator, a[n].denominator) * b ** n for n in range(NORD + 1))
    K = sp.series(sp.log(J), b, 0, NORD + 1).removeO()
    Kp = sp.diff(K, b)
    Kpp = sp.diff(K, b, 2)
    Delta_cube = sp.expand(sp.series(72 * Kpp * Kp ** 5, b, 0, NORD + 1).removeO())

    # K' leading coefficient = 1/18 (so the u = beta/18 slope falls out, not supplied)
    check("K' = J'/J has leading coefficient 1/18 (single-plaquette mean slope)",
          sp.Rational(sp.nsimplify(sp.series(Kp, b, 0, 2).removeO().coeff(b, 1))) == sp.Rational(1, 18))

    targets = {
        5: sp.Rational(1, 472392),
        6: sp.Rational(7, 5668704),
        7: sp.Rational(5, 17006112),
        8: sp.Rational(5, 272097792),     # PR #2408 (cross-check)
        9: sp.Rational(-235, 29386561536),  # cube-sector PART of d_9 (full d_9 reopens)
    }
    for n in [5, 6, 7, 8]:
        c = sp.Rational(sp.nsimplify(Delta_cube.coeff(b, n)))
        check(f"closed form reproduces d_{n} = {targets[n]} (m_{n}={sp.nsimplify(c*18**n)})",
              c == targets[n], f"got {c}")
    c9 = sp.Rational(sp.nsimplify(Delta_cube.coeff(b, 9)))
    check("closed form reproduces the cube-sector PART of d_9 = -235/29386561536",
          c9 == targets[9], f"got {c9} (m_9={sp.nsimplify(c9*18**9)}); NOT full d_9 (reopens at beta^9)")
    # leading-term identity 72*(1/18)*(1/18)^5 = 4/18^5 = d_5
    check("leading 72*(1/18)*(1/18)^5 = 4/18^5 = d_5",
          sp.Rational(72) * sp.Rational(1, 18) * sp.Rational(1, 18) ** 5 == sp.Rational(1, 472392))

    # ---- singularity diagnostic: zero witness of J; J>0 sampled on R --------
    import mpmath as mp
    mp.mp.dps = 30
    a_hi = j_coeffs(64)
    am = [mp.mpf(a_hi[n].numerator) / mp.mpf(a_hi[n].denominator) for n in range(64)]

    def Jnum(x):
        return sum(am[n] * x ** n for n in range(64))

    # Haar-integral positivity gives the real-axis fact; this is a sample check.
    real_pos = all(Jnum(mp.mpf(t)) > 0 for t in [0, 1, 2, 3, 4, 5, 6, 7, 8])
    check("J(beta) > 0 sampled on [0,8] (real-axis positivity sanity check)", real_pos)

    z = mp.findroot(Jnum, mp.mpc(3.3, 7.5))
    rad = abs(z)
    argdeg = mp.degrees(mp.arg(z))
    check("Newton J-zero witness |beta| = 8.2052",
          abs(rad - mp.mpf("8.2052")) < mp.mpf("0.001"), f"|beta|={mp.nstr(rad,7)}")
    check("Newton J-zero witness arg = +-66.152 deg",
          abs(abs(argdeg) - mp.mpf("66.152")) < mp.mpf("0.01"), f"arg={mp.nstr(argdeg,6)} deg")
    check("zero witness radius is > 6 (diagnostic only; not a zero-free-disk certificate)",
          rad > 6)

    # ---- scope guard ------------------------------------------------------
    check("SCOPE: closed form is the CUBE SECTOR only; full Delta reopens at "
          "beta^9 (GF(3) weight-10 nonempty, PR #2408) => NOT a closure of beta=6", True)

    print()
    print(f"SCORECARD: PASS={PASS} FAIL={FAIL}")
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
