#!/usr/bin/env python3
"""Verifier for the zero-import hydrogen goal packet.

This runner is intentionally a gate/roadmap verifier, not a physics closure.
It checks the current dependency lock for a zero-import retained hydrogen
calculation and guards against accidental retained-claim wording.
"""

from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTE = ROOT / "docs" / "ZERO_IMPORT_HYDROGEN_GOAL_PACKET_2026-07-04.md"

ALPHA_MZ_INV_REPO = 127.67
ALPHA0_INV_COMPARATOR = 137.035999084
M_E_EV_COMPARATOR = 510_998.95
RYDBERG_EV_COMPARATOR = 13.605693122994


class Audit:
    def __init__(self) -> None:
        self.pass_count = 0
        self.fail_count = 0

    def check(self, label: str, condition: bool, detail: str = "") -> None:
        if condition:
            self.pass_count += 1
            prefix = "PASS"
        else:
            self.fail_count += 1
            prefix = "FAIL"
        suffix = f" -- {detail}" if detail else ""
        print(f"{prefix}: {label}{suffix}")

    def summary(self) -> None:
        print(f"\nSUMMARY: PASS={self.pass_count} FAIL={self.fail_count}")
        if self.fail_count:
            raise SystemExit(1)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def bohr_ground_energy_ev(m_e_ev: float, alpha: float) -> float:
    return -0.5 * m_e_ev * alpha * alpha


def section(title: str) -> None:
    print("\n" + "-" * 80)
    print(title)
    print("-" * 80)


def main() -> None:
    audit = Audit()

    section("Zero-import hydrogen goal packet verification")
    audit.check("goal packet exists", NOTE.exists(), str(NOTE.relative_to(ROOT)))
    note = read(NOTE)

    forbidden_status_lines = [
        "**Status:** retained",
        "**Status:** proposed_retained",
    ]
    for phrase in forbidden_status_lines:
        audit.check(
            f"non-claim boundary excludes: {phrase}",
            phrase not in note,
        )

    explicit_non_claims = [
        "This packet does not derive `m_e`.",
        "This packet does not derive `alpha(0)`.",
        "This packet does not claim hydrogen is retained.",
    ]
    for phrase in explicit_non_claims:
        audit.check(f"explicit non-claim present: {phrase}", phrase in note)

    required_refs = [
        "ATOMIC_HYDROGEN_HELIUM_PROBE_NOTE.md",
        "HYDROGEN_HELIUM_ATOMIC_LATTICE_KINETIC_DEPENDENCY_NARROW_REPAIR_NOTE_2026-06-02.md",
        "frontier_atomic_hydrogen_lattice_companion.py",
        "ZERO_IMPORT_HYDROGEN_STATIC_SOURCE_RYDBERG_CLOSURE_DISCRIMINATOR_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_STATIC_SOURCE_NR_COULOMB_LIMIT_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_STATIC_SOURCE_NR_COULOMB_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "static-source NR Coulomb limit ratification decision packet",
        "STATIC_SOURCE_NR_COULOMB_TEXT_LOCK",
        "SCALAR_LATTICE_OPERATOR_SURFACE_RATIFIED",
        "COULOMB_KERNEL_ASYMPTOTIC_RATIFIED",
        "STATIC_SOURCE_LINEAR_RESPONSE_READOUT_RATIFIED",
        "ONE_BODY_NR_PHYSICAL_UNIT_LIMIT_RATIFIED",
        "HARTREE_SCALE_MAPPING_RATIFIED",
        "STATIC_SOURCE_NR_COULOMB_LIMIT_RETAINED",
        "RETAINED_STATIC_SOURCE_NR_COULOMB_LIMIT",
        "STATIC_SOURCE_LINEAR_RESPONSE_READOUT_RATIFIED",
        "ONE_BODY_NR_PHYSICAL_UNIT_LIMIT_RATIFIED",
        "HARTREE_SCALE_MAPPING_RATIFIED",
        "support, not the retained physical-unit one-body theorem",
        "static-source Rydberg closure predicate",
        "retained static-source nonrelativistic Coulomb limit",
        "no Rydberg comparator proof input",
        "full precision hydrogen spectroscopy",
        "1/256 = 1/(dim_C M_2(C))^4",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_RECIPROCAL_READOUT_FIREWALL_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_READOUT_MEASURE_DISCRIMINATOR_2026-07-04.md",
        "projection/Born trace",
        "algebra-basis coefficient density",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_L1_SOURCE_NORM_DISCRIMINATOR_2026-07-04.md",
        "L1 algebra-coordinate density",
        "L2 / Hilbert-Schmidt / Fisher-unit",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_ACTION_SIMPLEX_TRANSFER_DISCRIMINATOR_2026-07-04.md",
        "linear action simplex density",
        "primitive RN/Fisher unit amplitude",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_ACTION_SIMPLEX_UNIFORMITY_SUPPORT_2026-07-04.md",
        "local relabeling symmetry",
        "transitivity forces",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_MATRIX_UNIT_BASIS_SELECTOR_DISCRIMINATOR_2026-07-04.md",
        "basis/source-frame selector",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_RESTRICTED_TENSOR_FRAME_INVARIANCE_SUPPORT_2026-07-04.md",
        "tensor-frame relabelings",
        "coordinate bijections",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_SLOT_FRAME_SELECTOR_SUPPORT_2026-07-04.md",
        "J(j) = sum_c j_c O_c",
        "Full `U(16)` rotations",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_STRENGTH_ADDITIVITY_SELECTOR_SUPPORT_2026-07-04.md",
        "source-strength additivity",
        "mu({c}) = 1/256",
        "L2/RN/Fisher",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_CONTROL_LINEARITY_SUPPORT_2026-07-04.md",
        "source-control linearity",
        "J(j_A + j_B) = J(j_A) + J(j_B)",
        "total normalization `mu(C) = 1`",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_STRENGTH_NORMALIZATION_GAUGE_FIREWALL_2026-07-04.md",
        "S_src[j] = h * B_lep * J(j)",
        "(h, j) -> (h/lambda, lambda j)",
        "h * J(j)",
        "normalized source weight",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROJECTIVE_SIMPLEX_SECTION_SUPPORT_2026-07-04.md",
        "nonzero nonnegative projective source ray",
        "sigma([j])_c = j_c / sum_d j_d",
        "sigma([1])_c = 1/256",
        "projective semantics",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_POSITIVE_CONE_DISCRIMINATOR_2026-07-04.md",
        "real monotone finitely additive measure",
        "Signed or complex raw probes remain",
        "source-strength semantic bridge",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_COUPLING_GAUGE_QUOTIENT_PROJECTIVIZATION_SUPPORT_2026-07-04.md",
        "source-coupling gauge quotient",
        "H = h * sum_c j_c",
        "front/source-shape quotient",
        "projective source-shape coordinate",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_SHAPE_READOUT_SELECTOR_DISCRIMINATOR_2026-07-04.md",
        "source-shape readout selector",
        "(h*j_c)/H",
        "raw `h`, raw `j_c`, `h*j_c`, `H`",
        "physical `S_l` is the normalized source-shape singleton",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROJECTIVE_TENSOR_FRAME_UNIFORM_RAY_SUPPORT_2026-07-04.md",
        "finite-order positive scale",
        "finite transitive tensor-frame projective",
        "physical invariance bridge",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROJECTIVE_TENSOR_FRAME_INVARIANCE_BRIDGE_SUPPORT_2026-07-04.md",
        "source-family preserving maps `rho_g`",
        "rho_g J(j) = J(rho_g j)",
        "physical license for source-family naturality",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_NATURALITY_LABEL_FREE_LICENSE_SUPPORT_2026-07-04.md",
        "label-free source interface",
        "no physical coordinate tag beyond",
        "source-coordinate isomorphism invariance",
        "ratify that the charged-lepton scalar source interface is label-free",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_S_L_READOUT_IDENTITY_BRIDGE_SUPPORT_2026-07-04.md",
        "y_scale = g_2 * (1/sqrt(2)) * S_l",
        "S_l = sigma([j])_c",
        "physical license for that `S_l` source-readout convention",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROBE_INTERFACE_COMPRESSION_SUPPORT_2026-07-04.md",
        "normalized label-free charged-lepton full-cell source-probe interface",
        "compose to exact `S_l = 1/256`",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROBE_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
        "source-probe ratification target discriminator",
        "full F/L/P/R interface",
        "every one-clause-removed",
        "F/L/P/R ratification",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROBE_INTERFACE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "source-probe interface ratification decision packet",
        "CLAUSE_TEXT_LOCK",
        "CHARGED_LEPTON_SCOPE_LOCK",
        "NO_NEW_PRIMITIVE_OR_AXIOM",
        "NO_EMPIRICAL_COMPARATOR_INPUT",
        "OWNER_RATIFICATION",
        "AUDIT_ACCEPTANCE",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_EXACT_SOURCE_SINGLETON_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "current retained, primitive, and open-PR surfaces do not",
        "EXACT_SOURCE_SINGLETON_RETAINED",
        "retained exact source-side",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_EXACT_SOURCE_SINGLETON_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "EXACT_SOURCE_SINGLETON_TEXT_LOCK",
        "SOURCE_PROBE_INTERFACE_CONTRACT_ACCEPTED",
        "FULL_CELL_SOURCE_CARRIER_CHECK",
        "PROJECTIVE_UNIFORM_RAY_CHECK",
        "S_L_READOUT_IDENTITY_BOUND",
        "NO_A3_OR_K4_OR_MASS_INPUT",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "F-clause ratification decision packet",
        "F_CLAUSE_RETAINED",
        "F_CLAUSE_TEXT_LOCK",
        "S_lep[j] = h * B_lep * sum_{c in C} j_c O_c",
        "dS_lep/dj_c = h * B_lep * O_c",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F_CLAUSE_SOURCE_ACTION_ASSEMBLY_DISCRIMINATOR_2026-07-04.md",
        "F-clause source/action assembly discriminator",
        "F1 source-coupled local-action convention",
        "F2 charged-lepton sector specificity",
        "F3 full OS0-cell tensor source locality",
        "F4 scalar-multiplier attachment",
        "all F1-F4 supplied",
        "one-input-removed F target fails",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F1_SOURCE_COUPLED_LOCAL_ACTION_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
        "F1 source-coupled local-action ratification target discriminator",
        "local linear action source",
        "`dS/dj_c = A_c`",
        "does not ratify F1",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F1_SOURCE_COUPLED_LOCAL_ACTION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "F1_SOURCE_COUPLED_LOCAL_ACTION_RETAINED",
        "convention ratification or a retained source/action theorem",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F2_CHARGED_LEPTON_SOURCE_BLOCK_SELECTOR_DISCRIMINATOR_2026-07-04.md",
        "F2 charged-lepton source-block selector discriminator",
        "D17 supplies the bounded",
        "`Z_lep^2 = 2`",
        "does not ratify F2",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F2_CHARGED_LEPTON_SOURCE_BLOCK_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "F2_CHARGED_LEPTON_SOURCE_BLOCK_RETAINED",
        "owner/audit acceptance of the D17 source-block selector",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F3_FULL_CELL_TENSOR_SOURCE_LOCALITY_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
        "F3 full-cell tensor source-locality ratification target discriminator",
        "full tensor independence, and ratification",
        "does not ratify F3",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F3_FULL_CELL_TENSOR_SOURCE_LOCALITY_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "F3_FULL_CELL_TENSOR_SOURCE_LOCALITY_RETAINED",
        "owner/audit acceptance of the full-cell tensor source-locality target",
	        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F4_SCALAR_MULTIPLIER_ATTACHMENT_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
	        "F4 scalar-multiplier attachment ratification target discriminator",
	        "D17 block preservation rather than `512` product weights",
	        "does not ratify F4",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_F4_SCALAR_MULTIPLIER_ATTACHMENT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "F4_SCALAR_MULTIPLIER_ATTACHMENT_RETAINED",
        "owner/audit acceptance of the scalar-multiplier attachment target",
	        "ZERO_IMPORT_HYDROGEN_LEPTON_256_L_LABEL_FREE_SOURCE_COORDINATE_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
	        "L label-free source-coordinate ratification target discriminator",
	        "coordinate-tagged nonuniform ray",
	        "does not ratify L",
	        "ZERO_IMPORT_HYDROGEN_LEPTON_256_L_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
	        "L-clause ratification decision packet",
	        "L_CLAUSE_RETAINED",
	        "L_CLAUSE_TEXT_LOCK",
	        "[j] = [rho_g j] for tensor-frame source relabelings",
	        "coordinate-tagged nonuniform rays are not zero-import law-level selectors",
	        "ZERO_IMPORT_HYDROGEN_LEPTON_256_L_CLAUSE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
	        "label-free source-coordinate packet",
	        "label-free source-coordinate target remains needed",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_P_POSITIVE_PROJECTIVE_SOURCE_STRENGTH_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
		        "P positive projective source-strength ratification target discriminator",
		        "source-strength object, positive nonzero",
		        "raw `h`, raw `j_c`, `h*j_c`, `H`, and `1/16`",
		        "does not ratify P",
		        "ZERO_IMPORT_HYDROGEN_LEPTON_256_P_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
		        "P-clause ratification decision packet",
		        "P_CLAUSE_RETAINED",
		        "P_CLAUSE_TEXT_LOCK",
		        "source-shape singleton = sigma([j])_c",
		        "sigma([j])_c = j_c / sum_d j_d",
		        "ZERO_IMPORT_HYDROGEN_LEPTON_256_P_CLAUSE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
		        "owner/audit acceptance of the positive projective source-strength",
		        "positive projective source-strength target remains",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_R_S_L_READOUT_IDENTITY_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
		        "R `S_l` readout identity ratification target discriminator",
		        "scale-symbol context, source coefficient context",
		        "symbol-only, coefficient-only, mismatched-front",
		        "does not ratify R",
		        "ZERO_IMPORT_HYDROGEN_LEPTON_256_R_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
		        "R-clause ratification decision packet",
		        "R_CLAUSE_RETAINED",
		        "R_CLAUSE_TEXT_LOCK",
		        "S_l = sigma([j])_c",
		        "ZERO_IMPORT_HYDROGEN_LEPTON_256_R_CLAUSE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
		        "source-readout target remains needed",
		        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_COORDINATE_UNFIXED_CHOICE_LABEL_FREE_SUPPORT_2026-07-04.md",
		        "law may not depend on an unfixed choice absent admission",
		        "nonuniform law-level source-coordinate selector requires an admitted",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_TENSOR_LIFT_FIREWALL_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_FULL_CELL_SOURCE_CARRIER_SUPPORT_2026-07-04.md",
        "full OS0-cell",
        "source-locality and sector-specificity",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_D17_FULL_CELL_SEPARABILITY_SUPPORT_2026-07-04.md",
        "D17 `1/sqrt(2)` block normalization",
        "(1/sqrt(2))*(1/256)",
        "ZERO_IMPORT_HYDROGEN_WEAK_FRONT_BASE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "weak-front base ratification decision packet",
        "WEAK_FRONT_BASE_TEXT_LOCK",
        "ZERO_IMPORT_HYDROGEN_WEAK_FRONT_BASE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "base-front target remains needed",
        "ZERO_IMPORT_HYDROGEN_WEAK_FRONT_D17_BLOCK_NORMALIZATION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "D17 block-normalization ratification decision packet",
        "D17_BLOCK_NORMALIZATION_TEXT_LOCK",
        "D17_STATED_BLOCK_SCOPE_ACCEPTED",
        "TWO_COMPONENT_UNIT_NORMALIZATION_CHECK",
        "D17_ONLY_NO_SOURCE_SINGLETON_OR_A3_INPUT",
        "NO_WEAK_COUPLING_OR_FRONT_BASE_INPUT",
        "ZERO_IMPORT_HYDROGEN_WEAK_FRONT_SU2_COUPLING_CONTEXT_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "SU2 coupling-context ratification decision packet",
        "SU2_WEAK_COUPLING_CONTEXT_TEXT_LOCK",
        "CL3_SU2_WEAK_CONTEXT_ACCEPTED",
        "BARE_G2_SYMBOL_SCOPE_LOCK",
        "CHARGED_LEPTON_WEAK_DOUBLET_SCOPE_LOCK",
        "RUNNING_STRUCTURE_BOUNDARY_LOCK",
        "NO_PHYSICAL_G2V_OR_MW_INPUT",
        "NO_THRESHOLD_OR_A3_MATCHING_INPUT",
        "NO_D17_SOURCE_SINGLETON_OR_MASS_INPUT",
        "SU2_WEAK_COUPLING_CONTEXT_RETAINED",
        "CHARGED_LEPTON_D17_BLOCK_NORMALIZATION_RETAINED",
        "UNCORRECTED_FRONT_SCOPE_LOCK",
        "NO_MW_OR_LEPTON_COMPARATOR_PROOF_INPUT",
        "NO_A3_OR_THRESHOLD_MATCHING_INPUT",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_COUPLED_ATTACHMENT_SUPPORT_2026-07-04.md",
        "source-coupled local-action convention",
        "dS_lep/dj_c = h * B_lep * O_c",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_PRECISION_CORRECTION_FIREWALL_2026-07-04.md",
        "256.082435",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_CORRECTION_PLACEMENT_DISCRIMINATOR_2026-07-04.md",
        "weak front-factor/threshold matching",
        "Koide/electron readout",
        "direct noninteger divisor",
        "empirical splice",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P1_SOURCE_READOUT_CORRECTION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "P1 source-readout correction current-surface no-go",
        "P1_SOURCE_READOUT_CORRECTION_RETAINED",
        "CORRECTED_SOURCE_READOUT_THEOREM_RETAINED",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P2_WEAK_FRONT_THRESHOLD_TARGET_DISCRIMINATOR_2026-07-04.md",
        "F_phys = C_A3 * g_2 * (1/sqrt(2))",
        "ell_A3 ~= 0.03768480771",
        "charged-lepton front/matching theorem",
        "the no `m_W` or lepton-mass comparator proof input boundary",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P2_CHARGED_LEPTON_FRONT_MATCHING_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "P2 front-matching current-surface no-go",
        "CHARGED_LEPTON_FRONT_MATCHING_RETAINED",
        "MATCHING_THEOREM_RETAINED",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P2_CHARGED_LEPTON_FRONT_MATCHING_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "P2_MATCHING_TEXT_LOCK",
        "P2_PLACEMENT_SELECTED",
        "P2_WEAK_FRONT_MATCHING_RETAINED",
        "positive P2 handoff",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P3_KOIDE_ELECTRON_READOUT_CORRECTION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "P3_KOIDE_ELECTRON_READOUT_CORRECTION_RETAINED",
        "KOIDE_ELECTRON_A3_CORRECTION_THEOREM_RETAINED",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P4_DIRECT_NONINTEGER_DIVISOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "P4_DIRECT_NONINTEGER_DIVISOR_RETAINED",
        "DIRECT_NONINTEGER_DIVISOR_THEOREM_RETAINED",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_PRECISION_PLACEMENT_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "A3 precision-placement ratification decision packet",
        "A3_PRECISION_PLACEMENT_RETAINED",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_PRECISION_PLACEMENT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "A3 placement target remains needed",
        "ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_NO_DOUBLE_COUNT_COMPOSITION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "A3 no-double-count composition ratification decision packet",
        "NO_SOURCE_A3_DOUBLE_COUNT",
        "NO_SOURCE_DOUBLE_COUNT",
        "ONE_PLACEMENT_SELECTED",
        "PLACEMENT_THEOREM_RETAINED",
        "NO_SOURCE_DOUBLE_COUNT",
        "ZERO_IMPORT_HYDROGEN_KOIDE_BRANCH_MASS_MAP_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "Koide branch mass-map ratification decision packet",
        "KOIDE_BRANCH_MASS_MAP_TEXT_LOCK",
        "BRANNEN_CIRCULANT_BRANCH_FORM_RETAINED",
        "SQUARE_ROOT_MASS_READOUT_RETAINED",
        "POSITIVE_CHAMBER_OR_SIGN_RULE_RETAINED",
        "SCALE_PARAMETER_COMPOSITION_RETAINED",
        "PHASE_SCALE_SPECIES_SCOPE_LOCK",
        "ZERO_IMPORT_HYDROGEN_PHYSICAL_ELECTRON_MASS_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "physical electron mass ratification decision packet",
        "PHYSICAL_ELECTRON_MASS_TEXT_LOCK",
        "KOIDE_BRANCH_MASS_MAP_RETAINED",
        "ZERO_IMPORT_HYDROGEN_ABSOLUTE_CHARGED_LEPTON_SCALE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "K4 scale target remains needed",
        "ZERO_IMPORT_HYDROGEN_KOIDE_BRANCH_MASS_MAP_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "current Koide algebra, primitive, and open-PR surfaces do not",
        "ZERO_IMPORT_HYDROGEN_CHARGED_LEPTON_MASS_SPECTRUM_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "CHARGED_LEPTON_MASS_SPECTRUM_TEXT_LOCK",
        "FULL_CHARGED_LEPTON_SPECIES_LABELING_RETAINED",
        "PHYSICAL_CHARGED_LEPTON_MASS_TRIPLE_RETAINED",
        "PHYSICAL_CHARGED_LEPTON_SPECIES_LABELS_RETAINED",
        "CHARGED_LEPTON_MASS_SPECTRUM_RETAINED",
        "mass-spectrum target remains needed",
        "SCALE_REFERENCE_PRIMITIVE_CHAIN_SATISFIED",
        "NO_LEPTON_COMPARATOR_PROOF_INPUT",
        "PHYSICAL_ELECTRON_READOUT_RETAINED",
        "RETAINED_ELECTRON_MASS_PHYSICAL_UNIT",
        "ZERO_IMPORT_HYDROGEN_PHYSICAL_ELECTRON_MASS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "current retained, primitive, and open-PR surfaces do not supply",
        "NATIVE_ZERO_SECTION_BRIDGE_RETAINED",
        "PHYSICAL_ELECTRON_SPECIES_BRIDGE_RETAINED",
        "ABSOLUTE_CHARGED_LEPTON_SCALE_RETAINED",
        "scale-reference primitive remains",
        "(1/sqrt(2))*(1/16)",
        "alpha_EM(M_Z) -> alpha(0)",
        "ZERO_IMPORT_HYDROGEN_ALPHA_QED_LOOP_KERNEL_TARGET_DISCRIMINATOR_2026-07-04.md",
        "b_QED = 32/3",
        "QED loop-kernel",
        "ZERO_IMPORT_HYDROGEN_QED_LOOP_KERNEL_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "QED loop target remains needed",
        "ZERO_IMPORT_HYDROGEN_R_LEP_THRESHOLDS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_CHARGED_LEPTON_MASS_SPECTRUM_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_R_LEP_THRESHOLD_MOMENT_MAP_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "R-Lep threshold target remains needed",
        "LEPTON_THRESHOLD_MOMENT_MAP_RETAINED",
        "threshold-moment map target",
        "threshold/matching moment",
        "R-Lep",
        "R-Q-Heavy",
        "R-Had-NP",
        "scheme/decoupling matching",
        "no-comparator proof-input boundary",
        "ZERO_IMPORT_HYDROGEN_ALPHA0_TRANSPORT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "current retained, primitive, and open-PR surfaces do not supply",
        "ALPHA0_TRANSPORT_RETAINED",
        "ALPHA0_RETAINED",
        "RETAINED_ALPHA0_LOW_ENERGY_COULOMB",
        "QED_LOOP_KERNEL_RETAINED",
        "R_LEP_THRESHOLDS_RETAINED",
        "R_Q_HEAVY_THRESHOLDS_RETAINED",
        "R_HAD_NP_RETAINED",
        "SCHEME_DECOUPLING_MATCHING_RETAINED",
        "support, not low-energy `alpha(0)`",
        "ZERO_IMPORT_HYDROGEN_KOIDE_ELECTRON_READOUT_FIREWALL_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_PR5007_IMPACT_DISCRIMINATOR_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_BRIDGE_TARGET_DISCRIMINATOR_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_BRIDGE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_BRIDGE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_PHYSICAL_ELECTRON_SPECIES_BRIDGE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_W4C_PR5028_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_TIER_A_OWNER_RETIREMENT_PR4991_IMPACT_DISCRIMINATOR_2026-07-04.md",
        "KOIDE_NATIVE_ZERO_SECTION_DEFINED_ROUTE_ALGEBRA=TRUE",
        "NATIVE_ZERO_SECTION_BRIDGE_RETAINED",
        "native bridge target remains needed",
        "species bridge target remains needed",
        "Koide native zero-section bridge target",
        "Z1-Z3",
        "BRIDGE_TEXT_LOCK",
        "ZERO_SOURCE_READOUT_RETAINED",
        "REAL_PRIMITIVE_BRANNEN_ENDPOINT_RETAINED",
        "BASED_DETERMINANT_LINE_READOUT_RETAINED",
        "no comparator proof",
        "owner-governed chain-satisfying premises",
        "zero-source readout",
        "real-primitive Brannen endpoint",
        "based determinant-line readout",
        "supertrace / equivariant-index / holomorphic",
        "Lane 1 substrate route",
        "Open PR Surface Check",
        "Open PR relevance is checked by whether a PR is opened and lane-relevant.",
        "Clean/green status is not a prerequisite",
        "#5028",
        "#5029",
        "Koide W4c labeling/species repairs",
        "Koide labeling no-go runner",
        "runner/audit-surface context only",
        "labeling/species dependency-surface readiness",
        "#4897",
        "#4893",
        "#4898",
        "#4902",
        "#4905",
        "#4906",
        "#4922",
        "#4925",
        "#4926",
        "#4927",
        "#4923",
        "#4928",
        "#4929",
        "#4930",
        "#4931",
        "#4932",
        "#4933",
        "#4934",
        "#4935",
        "#4936",
        "#4937",
        "#4938",
        "Merged into `main` at 2026-07-04T15:14:57Z",
        "#4939",
        "#4940",
        "#4941",
        "#4942",
        "#4943",
        "#4944",
        "#4945",
        "#4946",
        "#4947",
        "#4948",
        "#4949",
        "#4950",
        "#4951",
        "#4952",
        "#4953",
        "#4954",
        "#4955",
        "#4956",
        "#4957",
        "#4958",
        "#4959",
        "#4960",
        "#4961",
        "#4962",
        "#4963",
        "#4964",
        "#4965",
        "#4966",
        "#4967",
        "#4968",
        "#4969",
        "#4970",
        "#4971",
        "#4972",
        "#4973",
        "#4974",
        "#4975",
        "#4976",
        "#4977",
        "#4978",
        "#4979",
        "#4980",
        "#4981",
        "#4982",
        "#4983",
        "#4984",
        "#4985",
        "#4986",
        "#4987",
        "#4988",
        "#4989",
        "#4990",
        "#4991",
        "owner-governed Tier-A retirement",
        "#4992",
        "#4993",
        "#4994",
        "#4995",
        "#4996",
        "#4997",
		        "#4998",
		        "#4999",
		        "#5000",
		        "#5001",
			        "#5002",
			        "#5003",
        "#5009",
        "#5010",
        "#5011",
        "#5012",
        "#5013",
        "#5014",
			        "#5008",
			        "#5007",
			        "#5006",
			        "#5005",
			        "#5004",
		        "Koide-search refresh",
				        "`#5015` open",
				        "`#5014` open",
				        "`#5013` merged",
				        "`#5012` open",
				        "`#5011` `SUCCESS`",
				        "`#5010` `SUCCESS`",
				        "`#5009` `SUCCESS`",
				        "`#5008` `SUCCESS`",
				        "`#5007` `SUCCESS`",
				        "`#5006` `SUCCESS`",
				        "`#5005` `CLEAN`",
			        "`#5004` `CLEAN`",
			        "`#5003` `CLEAN`",
		        "`#5002` `CLEAN`",
		        "`#5001` `CLEAN`",
		        "`#5000` `CLEAN`",
	        "`#4999` `CLEAN`",
	        "`#4998` `CLEAN`",
	        "`#4997` `CLEAN`",
	        "`#4996` `CLEAN`",
	        "`#4995` `CLEAN`",
        "`#4994` `CLEAN`",
        "`#4993` `CLEAN`",
        "`#4992` `CLEAN`",
        "`#4991` `CLEAN`",
        "and `#4985` `CLEAN`",
        "`#4990` `CLEAN`",
        "`#4989` `CLEAN`",
        "`#4988` `CLEAN`",
        "`#4987` `CLEAN`",
        "`#4986` `CLEAN`",
        "`#4984` `CLEAN`",
        "`#4983` `CLEAN`",
        "`#4982` `CLEAN`",
        "`#4981` `CLEAN`",
        "`#4980` `CLEAN`",
        "`#4979` `CLEAN`",
        "`#4978` `CLEAN`",
        "`#4977` `CLEAN`",
        "`#4976` `CLEAN`",
        "`#4975` `CLEAN`",
        "`#4974` `CLEAN`",
        "`#4973` `CLEAN`",
        "`#4972` `CLEAN`",
        "`#4971` `CLEAN`",
        "`#4970` `CLEAN`",
        "`#4969` `CLEAN`",
        "`#4968` `CLEAN`",
        "`#4967` `CLEAN`",
        "`#4966` `CLEAN`",
        "`#4965` `CLEAN`",
        "`#4964` `CLEAN`",
        "`#4963` `DIRTY`",
        "`#4962` `DIRTY`",
        "`#4961` `CLEAN`",
        "`#4960` `DIRTY`",
        "`#4959` `DIRTY`",
        "`#4958` `CLEAN`",
        "`#4957` `DIRTY`",
        "`#4956` `CLEAN`",
        "`#4955` `DIRTY`",
        "`#4954` `CLEAN`",
        "`#4953` `CLEAN`",
        "`#4952` closed without merge",
        "g_bare two-Ward scope repair",
        "DELTA0 route inventory sibling-total refresh",
	        "record-instrument polar contrast stabilization",
	        "theta retirement-basis re-match",
	        "PMNS selector stationarity diagnostics repair",
	        "neutrino source-amplitude carrier premise bound",
	        "neutrino split2 edge transport witness refresh",
        "`#4951` `CLEAN`",
        "`#4950` merged into `main` at 2026-07-04T16:10:45Z",
        "`#4943` `DIRTY`",
        "`#4940` `CLEAN`",
        "additive-even premise relocation",
        "theta mass determinant-bridge retirement-readiness",
        "Qualification unfixed-choice clarification",
        "K-real physicalization current-surface no-go",
        "stale sibling-interface runner repair",
        "gravity eikonal small-k remainder repair",
        "AC first-order determinant retirement-readiness no-go",
        "Gate B helper-runner artifact repair",
        "theta W2 physical registrability no-go",
        "dynamic helper dependency audit-packet repair",
        "hypercharge downstream trace scope quarantine",
        "theta action-entry exact-support",
        "SU2 beta coefficient template repair",
        "quark route2 no-go retained-parent repair",
        "alpha-s threshold matching kernel scoping",
        "D3 Landau-Peierls normalization support",
        "alpha-s universal beta kernel scoping",
        "AC occupancy determinant-power split support",
        "AC Record outcome-orbit non-supply no-go",
        "AC R-eta Record formation non-supply no-go",
        "primitive axiom absorption no-go",
        "theta G1 closed-nonexact interface exact-support",
        "theta G1 4D carrier supply no-go",
        "theta G1 defect suppression support",
        "theta G1 kinetic 4D scaffold support",
        "AC R-eta C3 ratification non-supply",
        "AC occupancy formation non-supply no-go",
        "AC R-eta doublet-clock no-go",
        "AC R-eta direct-license no-go",
        "AC R-eta h-unit primitive no-go",
        "AC R-eta h-class stretch no-go",
        "theta G4 theta-bar assembly no-go",
        "theta G2 registration stretch no-go",
        "Tier-A residual governance readiness packet",
        "Tier-A residual owner decision packet",
        "owner-governed Tier-A retirement",
        "Merge-state labels are moving review metadata",
        "`#4943` stale-green runner-cache repair sweep | Open on `main` and currently `DIRTY`",
        "`#4955` gravity eikonal small-k remainder repair | Open and currently `DIRTY`",
        "currently `CLEAN`",
        "mode-set / corner-transfer current-surface no-go",
        "K-covariant corner transfer",
        "stale-green runner-cache repair sweep",
        "matter-action/statistics current-surface no-go",
        "statistical-grain selector",
        "R-eta current-support-stack no-go",
        "physical readout license `Phi = S_sum = 2/3`",
        "R-eta transport-stretch no-go",
        "physical readout license `Phi = Tr L_3^+ = 2/3`",
        "unfluxed Green trace",
        "R-eta K-breaking transport no-go",
        "minimal positive K-breaking",
        "inhomogeneous C3 transport",
	        "theta G1 exact-branch no-go",
        "global exact-branch shortcut `n=dA`",
        "closed-nonexact sector/bundle/readout",
        "theta closed-nonexact sector-record no-go",
        "closed non-exact carrier witnesses to physical sector records/readout",
        "species-bridge partial-retirement",
        "R-eta route pruning",
        "occurrence axiom shortcut",
        "measure binary axiom shortcut",
        "theta mass no-go",
        "mass-side determinant-readout bridge",
        "theta gauge no-go",
        "gauge-side winding account",
        "theta gauge open",
        "phase-type `F cup F` insertion",
        "Theta G3 phase insertion current-surface no-go",
        "G3, the phase-type `F cup F` insertion",
        "Theta G1 defect closure current-surface no-go",
        "dn = 0",
        "K/CPT orbit-constancy supplied-context bridge",
        "determinant-character boundary",
        "AC(i) dynamical-index occupancy current-surface no-go",
        "rule achirality from minimality",
        "law-achiral/state-free",
        "AC(i) determinant-order/chiral L-R current-surface no-go",
	        "Phi = S_sum = 2/3",
	        "quark mass-ratio full-solve CP probe repair",
        "S3 spacetime tensor primitive runner repair",
        "YT P1 I_s re-audit packet bridge repair",
        "eta twisted walk family runner",
        "chirality domain-wall free-field note",
        "theta native positive-class adjudication",
        "wave-collapse-block01 measurement-collapse gate",
        "Koide native zero-section route guard repair",
        "`#5017` domain-wall edge anomaly inflow via spectral flow",
        "`#5018` domain-wall edge content vs SM chiral fermions map",
        "ZERO_IMPORT_HYDROGEN_CHIRALITY_DOMAIN_WALL_PR5017_5018_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "above-C3 chirality/domain-wall context",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_MATTER_STATE_CHIRALITY_DOMAIN_WALL_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "K2 physical matter-state support context",
        "KS route theorem, elementary route theorem, parent matter-state bridge",
        "`#5019` Koide `AC_phi_lambda` axiom-surface rebase",
        "ZERO_IMPORT_HYDROGEN_KOIDE_ACPHILAMBDA_PR5019_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "Koide premise-hygiene and audit-readiness context",
        "`#5020` Koide R-eta value-face registered-angle/exactness relocation",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_VALUE_FACE_PR5020_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "K2 value-face progress",
        "exactness remains open",
        "Koide delta-eta audit repair `#5022`",
        "`#5022` delta-eta chain R-eta supplied-premise audit repair",
        "ZERO_IMPORT_HYDROGEN_KOIDE_DELTA_ETA_PR5022_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "readout-identification premise",
        "ZERO_IMPORT_HYDROGEN_AC_R_ETA_UPSTREAM_CLUSTER_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "closed without GitHub merge flags",
        "landed-main commits",
        "89768b461c",
        "e2d1dec095",
        "ZERO_IMPORT_HYDROGEN_KOIDE_K1_COUNTING_MEASURE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "K1_COUNTING_MEASURE_RETAINED",
        "orbit/holomorphic count selector",
        "dimension/Born default",
        "one binary reduced but not retained",
        "ZERO_IMPORT_HYDROGEN_KOIDE_K1_COUNTING_MEASURE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "current retained, primitive, merged-PR, and open-PR surfaces do",
        "ZERO_IMPORT_HYDROGEN_KOIDE_K1_COUNTING_MEASURE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ten-input owner/audit contract for `K1_COUNTING_MEASURE_RETAINED`",
        "ZERO_IMPORT_HYDROGEN_KOIDE_K1_SELECTOR_DEFAULT_EXCLUSION_TARGET_DISCRIMINATOR_2026-07-05.md",
        "K1_SELECTOR_DEFAULT_EXCLUSION_RETAINED",
        "ORBIT_OR_HOLOMORPHIC_COUNT_SELECTOR_RETAINED",
        "DIMENSION_BORN_DEFAULT_EXCLUSION",
        "does not supply full K1",
        "ZERO_IMPORT_HYDROGEN_KOIDE_K1_SELECTOR_DEFAULT_EXCLUSION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_K1_SELECTOR_DEFAULT_EXCLUSION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "eleven-input owner/audit contract",
        "not supply `K1_SELECTOR_DEFAULT_EXCLUSION_RETAINED`",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_READOUT_RETIREMENT_TARGET_DISCRIMINATOR_2026-07-05.md",
        "R_ETA_READOUT_IDENTIFICATION_RETAINED",
        "h-class plus h-unit",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_READOUT_RETIREMENT_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_READOUT_RETIREMENT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "current retained, primitive, merged-PR, and open-PR surfaces do",
        "eleven-input owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_H_UNIT_IDENTITY_RADIAN_TARGET_DISCRIMINATOR_2026-07-05.md",
        "R_ETA_H_UNIT_IDENTITY_RADIAN_RETAINED",
        "conversion coefficient only",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_H_UNIT_IDENTITY_RADIAN_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "h-unit identity-radian ratification decision packet",
        "c = 1",
        "Phi = 2/3",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_H_CLASS_FIXED_LOCUS_TARGET_DISCRIMINATOR_2026-07-05.md",
        "R_ETA_H_CLASS_RETAINED",
        "single fixed-point readout bridge",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_H_CLASS_FIXED_LOCUS_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "h-class fixed-locus ratification decision packet",
        "thirteen-input owner/audit contract",
        "physical carrier realization",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_H_CLASS_FIXED_LOCUS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_EXACTNESS_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_EXACTNESS_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_EXACTNESS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "K2_R_ETA_EXACTNESS_RETAINED",
        "ten-input owner/audit contract",
        "current retained, primitive, merged-PR, and open-PR surfaces do not",
        "retained exact `2/9` theorem",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_MATTER_STATE_LAW_BRIDGE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "PHYSICAL_MATTER_STATE_LAW_BRIDGE_RETAINED",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_PHYSICAL_STATE_ROTATION_LAW_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_PHYSICAL_STATE_ROTATION_LAW_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_PHYSICAL_STATE_ROTATION_LAW_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "ELEMENTARY_PHYSICAL_STATE_ROTATION_LAW_THEOREM_RETAINED",
        "elementary route owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_STATE_ATTACHMENT_SELECTOR_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_STATE_ATTACHMENT_SELECTOR_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_STATE_ATTACHMENT_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "ELEMENTARY_STATE_ATTACHMENT_SELECTOR_RETAINED",
        "field-index spin-lift privilege owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FIELD_INDEX_SPIN_LIFT_PRIVILEGE_PRINCIPLE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FIELD_INDEX_SPIN_LIFT_PRIVILEGE_PRINCIPLE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FIELD_INDEX_SPIN_LIFT_PRIVILEGE_PRINCIPLE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "FIELD_INDEX_SPIN_LIFT_PRIVILEGE_PRINCIPLE_RETAINED",
        "privileging the faithful Pauli",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_TO_PHYSICAL_MATTER_STATE_SPINOR_LAW_TARGET_DISCRIMINATOR_2026-07-05.md",
        "KS_TO_PHYSICAL_MATTER_STATE_SPINOR_LAW_THEOREM_RETAINED",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_SPIN_LIFT_PHYSICAL_ACTION_LAW_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_SPIN_LIFT_PHYSICAL_ACTION_LAW_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_SPIN_LIFT_PHYSICAL_ACTION_LAW_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "KS_SPIN_LIFT_PHYSICAL_ACTION_LAW_RETAINED",
        "action-law owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FAITHFUL_KS_STATE_ACTION_SELECTOR_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FAITHFUL_KS_STATE_ACTION_SELECTOR_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FAITHFUL_KS_STATE_ACTION_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "FAITHFUL_KS_STATE_ACTION_SELECTOR_RETAINED",
        "selector owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_RECONSTRUCTED_MATTER_MODE_ACTION_DOMAIN_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_RECONSTRUCTED_MATTER_MODE_ACTION_DOMAIN_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_RECONSTRUCTED_MATTER_MODE_ACTION_DOMAIN_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "KS_RECONSTRUCTED_MATTER_MODE_ACTION_DOMAIN_RETAINED",
        "action-domain owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_ROTATION_ACTION_SELECTOR_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_ROTATION_ACTION_SELECTOR_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_ROTATION_ACTION_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "PHYSICAL_ROTATION_ACTION_SELECTOR_RETAINED",
        "physical action-selector owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_STAGGERED_KERNEL_SCALAR_LIFT_EXCLUSION_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_STAGGERED_KERNEL_SCALAR_LIFT_EXCLUSION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_STAGGERED_KERNEL_SCALAR_LIFT_EXCLUSION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "SPINFUL_STAGGERED_KERNEL_EXCLUDES_SCALAR_LIFT_RETAINED",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_SIGMA_DOT_P_KERNEL_KS_ROUTE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_SIGMA_DOT_P_KERNEL_KS_ROUTE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_SIGMA_DOT_P_KERNEL_KS_ROUTE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "SPINFUL_SIGMA_DOT_P_KERNEL_DEFINED_ON_KS_ROUTE_RETAINED",
        "route-kernel owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_TRIVIAL_SCALAR_LIFT_COVARIANCE_EXCLUSION_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_TRIVIAL_SCALAR_LIFT_COVARIANCE_EXCLUSION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_TRIVIAL_SCALAR_LIFT_COVARIANCE_EXCLUSION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "TRIVIAL_SCALAR_LIFT_COVARIANCE_EXCLUSION_RETAINED",
        "finite covariance-failure owner/audit contract",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_SPINFUL_KERNEL_OBJECT_THEOREM_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_SPINFUL_KERNEL_OBJECT_THEOREM_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_SPINFUL_KERNEL_OBJECT_THEOREM_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "KS_ROUTE_SPINFUL_KERNEL_OBJECT_THEOREM_RETAINED",
        "child owner/audit contract",
        "Pauli-vector and Kawamoto-Smit support stack",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_MOMENTUM_LINK_PHASE_INPUT_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_MOMENTUM_LINK_PHASE_INPUT_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_MOMENTUM_LINK_PHASE_INPUT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "KS_ROUTE_DEFINED_MOMENTUM_COVECTOR_OR_LINK_PHASE_INPUT_RETAINED",
        "route-input owner/audit contract",
        "P-FLUX and Kawamoto-Smit support stack",
        "KS physical spin-lift action law",
        "ZERO_IMPORT_HYDROGEN_KOIDE_TWO_NINTHS_RADIAN_READOUT_TARGET_DISCRIMINATOR_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_TWO_NINTHS_RADIAN_READOUT_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "ZERO_IMPORT_HYDROGEN_KOIDE_TWO_NINTHS_RADIAN_READOUT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "KOIDE_TWO_NINTHS_RADIAN_READOUT_RETAINED",
        "nine-input owner/audit contract",
        "#5027",
        "Koide custody AC gate-edge repair",
        "Koide W4c labeling/species repairs",
        "Koide substep4 labeling no-go runner strengthening",
        "fold/branch domain-lock sub-handoff",
    ]
    for phrase in required_refs:
        audit.check(f"required gate/reference present: {phrase}", phrase in note)

    source_paths = [
        "docs/ATOMIC_RYDBERG_DEPENDENCY_FIREWALL_NOTE_2026-04-27.md",
        "docs/ATOMIC_LANE2_QED_RUNNING_DEPENDENCY_FIREWALL_NOTE_2026-04-30.md",
        "docs/HYDROGEN_HELIUM_ATOMIC_LATTICE_KINETIC_DEPENDENCY_NARROW_REPAIR_NOTE_2026-06-02.md",
        "scripts/frontier_atomic_hydrogen_lattice_companion.py",
        "docs/ZERO_IMPORT_HYDROGEN_STATIC_SOURCE_RYDBERG_CLOSURE_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_STATIC_SOURCE_NR_COULOMB_LIMIT_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_STATIC_SOURCE_NR_COULOMB_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/LEPTON_SCALE_FRONTIER_PROBE_2026-06-05.md",
        "docs/LEPTON_MASS_SCALE_MW_OVER_256_EMPIRICAL_OPEN_GATE_NOTE_2026-05-26.md",
        "docs/CHARGED_LEPTON_VALUE_REDUCES_TO_ONE_COUNTING_BIT_SYNTHESIS_NOTE_2026-06-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_RECIPROCAL_READOUT_FIREWALL_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_READOUT_MEASURE_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_L1_SOURCE_NORM_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_ACTION_SIMPLEX_TRANSFER_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_ACTION_SIMPLEX_UNIFORMITY_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_MATRIX_UNIT_BASIS_SELECTOR_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_RESTRICTED_TENSOR_FRAME_INVARIANCE_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_SLOT_FRAME_SELECTOR_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_STRENGTH_ADDITIVITY_SELECTOR_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_CONTROL_LINEARITY_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_STRENGTH_NORMALIZATION_GAUGE_FIREWALL_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROJECTIVE_SIMPLEX_SECTION_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_POSITIVE_CONE_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_COUPLING_GAUGE_QUOTIENT_PROJECTIVIZATION_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_SHAPE_READOUT_SELECTOR_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROJECTIVE_TENSOR_FRAME_UNIFORM_RAY_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROJECTIVE_TENSOR_FRAME_INVARIANCE_BRIDGE_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_NATURALITY_LABEL_FREE_LICENSE_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_S_L_READOUT_IDENTITY_BRIDGE_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROBE_INTERFACE_COMPRESSION_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_PROBE_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_EXACT_SOURCE_SINGLETON_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_EXACT_SOURCE_SINGLETON_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F_CLAUSE_SOURCE_ACTION_ASSEMBLY_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F1_SOURCE_COUPLED_LOCAL_ACTION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F1_SOURCE_COUPLED_LOCAL_ACTION_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F2_CHARGED_LEPTON_SOURCE_BLOCK_SELECTOR_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F2_CHARGED_LEPTON_SOURCE_BLOCK_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F3_FULL_CELL_TENSOR_SOURCE_LOCALITY_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F3_FULL_CELL_TENSOR_SOURCE_LOCALITY_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F4_SCALAR_MULTIPLIER_ATTACHMENT_RATIFICATION_TARGET_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_F4_SCALAR_MULTIPLIER_ATTACHMENT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_L_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_L_CLAUSE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_P_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_P_CLAUSE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_R_CLAUSE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_R_CLAUSE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_COORDINATE_UNFIXED_CHOICE_LABEL_FREE_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_TENSOR_LIFT_FIREWALL_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_FULL_CELL_SOURCE_CARRIER_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_D17_FULL_CELL_SEPARABILITY_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_WEAK_FRONT_BASE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_WEAK_FRONT_BASE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_WEAK_FRONT_D17_BLOCK_NORMALIZATION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_WEAK_FRONT_SU2_COUPLING_CONTEXT_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_SOURCE_COUPLED_ATTACHMENT_SUPPORT_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_PRECISION_CORRECTION_FIREWALL_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_CORRECTION_PLACEMENT_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P1_SOURCE_READOUT_CORRECTION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P2_WEAK_FRONT_THRESHOLD_TARGET_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P2_CHARGED_LEPTON_FRONT_MATCHING_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P2_CHARGED_LEPTON_FRONT_MATCHING_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P3_KOIDE_ELECTRON_READOUT_CORRECTION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_P4_DIRECT_NONINTEGER_DIVISOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_PRECISION_PLACEMENT_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_PRECISION_PLACEMENT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_LEPTON_256_A3_NO_DOUBLE_COUNT_COMPOSITION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_BRANCH_MASS_MAP_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_BRANCH_MASS_MAP_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_CHARGED_LEPTON_MASS_SPECTRUM_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_R_LEP_THRESHOLD_MOMENT_MAP_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_ABSOLUTE_CHARGED_LEPTON_SCALE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_PHYSICAL_ELECTRON_MASS_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_PHYSICAL_ELECTRON_MASS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_ELECTRON_READOUT_FIREWALL_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_PR5007_IMPACT_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_ACPHILAMBDA_PR5019_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_VALUE_FACE_PR5020_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_DELTA_ETA_PR5022_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_AC_R_ETA_UPSTREAM_CLUSTER_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_K1_COUNTING_MEASURE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_K1_COUNTING_MEASURE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_K1_COUNTING_MEASURE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_K1_SELECTOR_DEFAULT_EXCLUSION_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_K1_SELECTOR_DEFAULT_EXCLUSION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_K1_SELECTOR_DEFAULT_EXCLUSION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_READOUT_RETIREMENT_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_READOUT_RETIREMENT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_H_CLASS_FIXED_LOCUS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_MATTER_STATE_LAW_BRIDGE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_MATTER_STATE_LAW_BRIDGE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_MATTER_STATE_LAW_BRIDGE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_PHYSICAL_STATE_ROTATION_LAW_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_PHYSICAL_STATE_ROTATION_LAW_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_PHYSICAL_STATE_ROTATION_LAW_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_STATE_ATTACHMENT_SELECTOR_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_STATE_ATTACHMENT_SELECTOR_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_ELEMENTARY_STATE_ATTACHMENT_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FIELD_INDEX_SPIN_LIFT_PRIVILEGE_PRINCIPLE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FIELD_INDEX_SPIN_LIFT_PRIVILEGE_PRINCIPLE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FIELD_INDEX_SPIN_LIFT_PRIVILEGE_PRINCIPLE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_TO_PHYSICAL_MATTER_STATE_SPINOR_LAW_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_TO_PHYSICAL_MATTER_STATE_SPINOR_LAW_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_TO_PHYSICAL_MATTER_STATE_SPINOR_LAW_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_SPIN_LIFT_PHYSICAL_ACTION_LAW_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_SPIN_LIFT_PHYSICAL_ACTION_LAW_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_SPIN_LIFT_PHYSICAL_ACTION_LAW_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FAITHFUL_KS_STATE_ACTION_SELECTOR_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FAITHFUL_KS_STATE_ACTION_SELECTOR_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_FAITHFUL_KS_STATE_ACTION_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_RECONSTRUCTED_MATTER_MODE_ACTION_DOMAIN_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_RECONSTRUCTED_MATTER_MODE_ACTION_DOMAIN_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_RECONSTRUCTED_MATTER_MODE_ACTION_DOMAIN_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_ROTATION_ACTION_SELECTOR_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_ROTATION_ACTION_SELECTOR_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_PHYSICAL_ROTATION_ACTION_SELECTOR_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_STAGGERED_KERNEL_SCALAR_LIFT_EXCLUSION_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_STAGGERED_KERNEL_SCALAR_LIFT_EXCLUSION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_STAGGERED_KERNEL_SCALAR_LIFT_EXCLUSION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_SIGMA_DOT_P_KERNEL_KS_ROUTE_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_SIGMA_DOT_P_KERNEL_KS_ROUTE_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_SPINFUL_SIGMA_DOT_P_KERNEL_KS_ROUTE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_TRIVIAL_SCALAR_LIFT_COVARIANCE_EXCLUSION_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_TRIVIAL_SCALAR_LIFT_COVARIANCE_EXCLUSION_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_TRIVIAL_SCALAR_LIFT_COVARIANCE_EXCLUSION_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_SPINFUL_KERNEL_OBJECT_THEOREM_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_SPINFUL_KERNEL_OBJECT_THEOREM_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_SPINFUL_KERNEL_OBJECT_THEOREM_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_MOMENTUM_LINK_PHASE_INPUT_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_MOMENTUM_LINK_PHASE_INPUT_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_KS_ROUTE_MOMENTUM_LINK_PHASE_INPUT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_EXACTNESS_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_EXACTNESS_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_EXACTNESS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_TWO_NINTHS_RADIAN_READOUT_TARGET_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_TWO_NINTHS_RADIAN_READOUT_RATIFICATION_DECISION_PACKET_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_TWO_NINTHS_RADIAN_READOUT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_CHIRALITY_DOMAIN_WALL_PR5017_5018_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_R_ETA_MATTER_STATE_CHIRALITY_DOMAIN_WALL_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_W4C_PR5028_IMPACT_DISCRIMINATOR_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_BRIDGE_TARGET_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_BRIDGE_RATIFICATION_DECISION_PACKET_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_KOIDE_NATIVE_ZERO_SECTION_BRIDGE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_PHYSICAL_ELECTRON_SPECIES_BRIDGE_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_TIER_A_OWNER_RETIREMENT_PR4991_IMPACT_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_ALPHA_QED_LOOP_KERNEL_TARGET_DISCRIMINATOR_2026-07-04.md",
        "docs/ZERO_IMPORT_HYDROGEN_QED_LOOP_KERNEL_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_R_LEP_THRESHOLDS_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/ZERO_IMPORT_HYDROGEN_ALPHA0_TRANSPORT_CURRENT_SURFACE_NO_GO_2026-07-05.md",
        "docs/SUPERTRACE_INDEX_HOLOMORPHIC_ROUTE_TO_KOIDE_R_HALF_OPEN_LEAD_NOTE_2026-06-04.md",
        "docs/CROSS_LANE_DEPENDENCY_MAP_NOTE_2026-04-30.md",
    ]
    for rel in source_paths:
        audit.check(f"source path exists: {rel}", (ROOT / rel).exists())

    section("Direct alpha(M_Z) substitution firewall arithmetic")
    alpha_mz = 1.0 / ALPHA_MZ_INV_REPO
    alpha0 = 1.0 / ALPHA0_INV_COMPARATOR
    e_alpha_mz = bohr_ground_energy_ev(M_E_EV_COMPARATOR, alpha_mz)
    e_alpha0 = bohr_ground_energy_ev(M_E_EV_COMPARATOR, alpha0)
    shift = abs(e_alpha_mz / e_alpha0) - 1.0
    print(f"E1 with alpha(M_Z): {e_alpha_mz:.6f} eV")
    print(f"E1 with alpha(0):  {e_alpha0:.6f} eV")
    print(f"relative shift:    {100.0 * shift:.2f}%")
    audit.check(
        "textbook alpha(0) comparator reproduces Rydberg scale",
        abs(abs(e_alpha0) - RYDBERG_EV_COMPARATOR) / RYDBERG_EV_COMPARATOR < 1e-10,
    )
    audit.check(
        "direct alpha(M_Z) substitution misses by more than 10 percent",
        shift > 0.10,
        f"shift={100.0 * shift:.2f}%",
    )

    section("Attack-order lock")
    primary_idx = note.find("1. **Primary:** derive or sharply reduce the `1/256`")
    koide_idx = note.find("2. **Parallel:** continue the Koide")
    qed_idx = note.find("3. **Parallel infrastructure:** use the alpha QED loop-kernel target")
    later_idx = note.find("4. **Later:** attack Lane 3 and Lane 1")
    final_idx = note.find("5. **Final:** feed retained physical-unit `m_e`")
    audit.check("primary 1/256 attack listed first", primary_idx >= 0)
    audit.check("Koide readout route listed after primary", 0 <= primary_idx < koide_idx)
    audit.check("QED loop infrastructure listed after Koide route", 0 <= koide_idx < qed_idx)
    audit.check("Lane 3/Lane 1 threshold work listed after QED infrastructure", 0 <= qed_idx < later_idx)
    audit.check("final atomic harness step listed last", 0 <= later_idx < final_idx)

    section("Hydrogen scale dependency identity")
    audit.check("Hartree scale named as m_e alpha(0)^2", "E_H = m_e alpha(0)^2" in note)
    audit.check("electron mass gate named", "Electron mass `m_e`" in note)
    audit.check("low-energy Coulomb gate named", "Low-energy Coulomb coupling `alpha(0)`" in note)
    audit.check("static-source Rydberg final lane named", "static-source Rydberg" in note)
    audit.check("full precision spectroscopy kept separate", "full precision hydrogen spectroscopy" in note)
    audit.check("retained status gate named", "Retained status" in note)

    audit.summary()


if __name__ == "__main__":
    main()
