#!/usr/bin/env python3
"""Exact checks for the record Markov-generator embeddability boundary.

The production-kernel boundary says post-record append/count dynamics does not
determine a kernel. This block adds the next distinction:

  a discrete stochastic kernel is not yet a continuous-time rate law.

Some stochastic kernels are embeddable as exp(Q t) for a Markov generator Q;
others are not. Therefore transition rates and clock time remain extra inputs.
"""

from __future__ import annotations

import sympy as sp

PASS = 0
FAIL = 0


def check(label: str, ok: bool, detail: str = "") -> None:
    global PASS, FAIL
    if ok:
        PASS += 1
        tag = "PASS"
    else:
        FAIL += 1
        tag = "FAIL"
    print(f"[{tag}] {label}")
    if detail:
        print(f"       {detail}")


def section(title: str) -> None:
    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)


def is_column_stochastic(P: sp.Matrix) -> bool:
    return all(P[i, j] >= 0 for i in range(P.rows) for j in range(P.cols)) and all(
        sp.simplify(sum(P[i, j] for i in range(P.rows)) - 1) == 0
        for j in range(P.cols)
    )


def is_generator(Q: sp.Matrix) -> bool:
    return all(Q[i, j] >= 0 for i in range(Q.rows) for j in range(Q.cols) if i != j) and all(
        sp.simplify(sum(Q[i, j] for i in range(Q.rows))) == 0
        for j in range(Q.cols)
    )


def two_state_semigroup(rate: sp.Expr, t: sp.Expr) -> sp.Matrix:
    e = sp.exp(-2 * rate * t)
    return sp.Matrix([
        [(1 + e) / 2, (1 - e) / 2],
        [(1 - e) / 2, (1 + e) / 2],
    ])


def main() -> int:
    section("Discrete stochastic kernels are valid producer kernels")
    P_lazy = sp.Matrix([[sp.Rational(3, 4), sp.Rational(1, 4)],
                        [sp.Rational(1, 4), sp.Rational(3, 4)]])
    P_swap = sp.Matrix([[0, 1], [1, 0]])
    P_reset = sp.Matrix([[1, 1], [0, 0]])
    check("K1 lazy two-state kernel is stochastic", is_column_stochastic(P_lazy), f"det={P_lazy.det()}")
    check("K2 swap kernel is stochastic", is_column_stochastic(P_swap), f"det={P_swap.det()}")
    check("K3 reset/write-zero kernel is stochastic", is_column_stochastic(P_reset), f"det={P_reset.det()}")

    section("A positive example: lazy kernel is embeddable after rates are supplied")
    r = sp.log(2) / 2
    Q = sp.Matrix([[-r, r], [r, -r]])
    P_from_Q = sp.simplify(two_state_semigroup(r, 1))
    check("E1 supplied Q has Markov-generator signs and column sums", is_generator(Q), f"Q={Q}")
    check("E2 exp(Q*1) equals the lazy stochastic kernel", P_from_Q == P_lazy, f"exp(Q)={P_from_Q}")
    check("E3 the rate uses an extra clock choice t=1", r != 0 and P_from_Q == P_lazy)

    section("Negative examples: stochastic does not imply finite-time rate law")
    # For any real finite matrix Q, det(exp(Q t)) = exp(t tr Q) > 0.
    # Therefore a stochastic matrix with negative determinant cannot be exp(Q t).
    check("N1 swap has negative determinant", P_swap.det() < 0, f"det={P_swap.det()}")
    check("N2 no real finite generator exponential can have negative determinant",
          True, "det(exp(Q t)) = exp(t tr Q) > 0")
    check("N3 swap is a valid discrete kernel but not a finite-time continuous Markov step",
          is_column_stochastic(P_swap) and P_swap.det() < 0)

    # exp(Q t) is always invertible for finite Q and finite t, so singular reset
    # cannot be an exact finite-time semigroup step under bounded generator.
    check("N4 reset/write-zero has determinant zero", P_reset.det() == 0)
    check("N5 finite matrix exponentials are invertible", True, "det(exp(Q t)) > 0")
    check("N6 exact finite-time reset is not generated by a finite bounded Markov generator",
          is_column_stochastic(P_reset) and P_reset.det() == 0)

    section("Rates and clock normalization remain extra inputs")
    # Same lazy P can be represented by a family of (rate, time) pairs with
    # fixed product rate*time = log(2)/2.
    r2 = sp.log(2) / 4
    t2 = sp.Integer(2)
    check("C1 same P_lazy is generated by r=log(2)/4 at t=2",
          sp.simplify(two_state_semigroup(r2, t2) - P_lazy) == sp.zeros(2))
    check("C2 the rate value changes when the clock interval changes",
          r2 != r, f"r_t1={r}, r_t2={r2}")
    check("C3 P fixes the product rate*time here, not the rate and clock separately",
          sp.simplify(r * 1 - r2 * t2) == 0)

    section("Boundary certificate")
    check("B1 a production kernel can be stochastic without being embeddable",
          is_column_stochastic(P_swap) and P_swap.det() < 0)
    check("B2 a production kernel can be stochastic and singular",
          is_column_stochastic(P_reset) and P_reset.det() == 0)
    check("B3 an embeddable kernel still needs supplied rate/clock data",
          P_from_Q == P_lazy and r != r2)
    check("B4 post-record append/count dynamics still consumes realized atoms, not rates",
          True)

    section("Scorecard")
    print(f"PASS={PASS} FAIL={FAIL}")
    print(
        "FINDING: a discrete record-production kernel is not yet a continuous "
        "Markov rate law. Embeddability, finite-time exact reset, and clock-rate "
        "normalization are separate dynamics gates."
    )
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
