#!/usr/bin/env python3
"""
PR #230 Block118 native Hamming-Dirichlet O_H axis selector.

Blocks 114-117 resolved that no finished strict source-Higgs, W/Z, neutral,
or Schur/scalar-LSZ closure artifact is present on the current PR230 head.
This block moves back into construction mode on the top source-Higgs root.

The current source/taste algebra generated by the three commuting taste
involutions is isomorphic to functions on the Boolean cube {+-1}^3.  The
canonical single-generator flip graph on that cube gives a finite
Hamming-Dirichlet form.  Restricted to the cyclic Z3-invariant trace-zero
neutral subspace, that form has a unique lowest nonzero mode:

    eps0 + eps1 + eps2  <=>  S0 + S1 + S2.

This retires the degree-one filter only as an axis selector.  It does not
derive the EW/Higgs action, canonical scalar LSZ metric, source-overlap
normalization, or physical C_ss/C_sH/C_HH pole rows.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    ROOT
    / "outputs"
    / "yt_pr230_block118_hamming_dirichlet_oh_axis_selector_2026-05-17.json"
)

PARENTS = {
    "degree_one_radial_tangent": "outputs/yt_pr230_degree_one_radial_tangent_oh_theorem_2026-05-07.json",
    "degree_one_action_premise": "outputs/yt_pr230_degree_one_higgs_action_premise_gate_2026-05-06.json",
    "fms_oh_candidate_action_packet": "outputs/yt_pr230_fms_oh_candidate_action_packet_2026-05-07.json",
    "fms_source_overlap_readout_gate": "outputs/yt_pr230_fms_source_overlap_readout_gate_2026-05-07.json",
    "source_higgs_direct_pole_contract": "outputs/yt_pr230_source_higgs_direct_pole_row_contract_2026-05-07.json",
    "source_higgs_pole_acceptance_contract": "outputs/yt_pr230_source_higgs_pole_row_acceptance_contract_2026-05-06.json",
    "block109_frontier_selector": "outputs/yt_pr230_block109_closure_root_frontier_selector_2026-05-17.json",
    "block110_action_descent_obstruction": "outputs/yt_pr230_block110_cl3_z3_action_descent_obstruction_2026-05-17.json",
    "block112_helmholtz_obstruction": "outputs/yt_pr230_block112_helmholtz_action_integrability_obstruction_2026-05-17.json",
    "block114_source_higgs_resolver": "outputs/yt_pr230_block114_source_higgs_strict_artifact_resolver_2026-05-17.json",
    "block115_wz_resolver": "outputs/yt_pr230_block115_wz_strict_artifact_resolver_2026-05-17.json",
    "block116_neutral_resolver": "outputs/yt_pr230_block116_neutral_h3h4_strict_artifact_resolver_2026-05-17.json",
    "block117_schur_scalar_lsz_resolver": "outputs/yt_pr230_block117_schur_scalar_lsz_strict_artifact_resolver_2026-05-17.json",
    "full_positive_assembly": "outputs/yt_pr230_full_positive_closure_assembly_gate_2026-05-04.json",
    "retained_route": "outputs/yt_retained_closure_route_certificate_2026-05-01.json",
    "campaign_status": "outputs/yt_pr230_campaign_status_certificate_2026-05-01.json",
    "completion_audit": "outputs/yt_pr230_positive_closure_completion_audit_2026-05-05.json",
}

STRICT_CLOSURE_PATHS = {
    "accepted_same_source_ew_higgs_action": "outputs/yt_pr230_same_source_ew_higgs_action_certificate_2026-05-06.json",
    "accepted_canonical_oh": "outputs/yt_pr230_canonical_oh_certificate_2026-05-07.json",
    "canonical_higgs_operator_certificate": "outputs/yt_canonical_higgs_operator_certificate_2026-05-03.json",
    "source_higgs_pole_rows": "outputs/yt_pr230_source_higgs_pole_rows_2026-05-06.json",
    "source_higgs_production_certificate": "outputs/yt_source_higgs_cross_correlator_production_certificate_2026-05-03.json",
    "same_source_w_response_rows": "outputs/yt_same_source_w_response_rows_2026-05-04.json",
    "neutral_h3h4_certificate": "outputs/yt_pr230_neutral_h3h4_certificate_2026-05-17.json",
    "strict_schur_feshbach_rows": "outputs/yt_pr230_strict_schur_feshbach_kprime_rows_2026-05-17.json",
}

FORBIDDEN_FIREWALL = {
    "used_hunit_matrix_element_readout": False,
    "used_yt_ward_identity": False,
    "used_y_t_bare": False,
    "used_observed_top_or_yukawa": False,
    "used_observed_wz_or_g2": False,
    "used_alpha_lm_plaquette_or_u0": False,
    "used_reduced_cold_pilots_as_production_evidence": False,
    "set_kappa_s_equal_one": False,
    "set_c2_equal_one": False,
    "set_z_match_equal_one": False,
    "set_g2_equal_one": False,
    "treated_axis_selector_as_ew_higgs_action": False,
    "treated_axis_selector_as_scalar_lsz_metric": False,
    "treated_axis_selector_as_source_overlap": False,
    "renamed_C_sx_C_xx_as_C_sH_C_HH": False,
    "claimed_retained_or_proposed_retained": False,
}

PASS_COUNT = 0
FAIL_COUNT = 0


def report(tag: str, ok: bool, msg: str) -> None:
    global PASS_COUNT, FAIL_COUNT
    if ok:
        PASS_COUNT += 1
        state = "PASS"
    else:
        FAIL_COUNT += 1
        state = "FAIL"
    print(f"  [{state}] {tag}: {msg}")


def load_json(rel: str) -> dict[str, Any]:
    path = ROOT / rel
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def status(cert: dict[str, Any]) -> str:
    return str(cert.get("actual_current_surface_status", ""))


def pauli_x() -> np.ndarray:
    return np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)


def taste_axes() -> list[np.ndarray]:
    i2 = np.eye(2, dtype=complex)
    sx = pauli_x()
    return [
        np.kron(sx, np.kron(i2, i2)),
        np.kron(i2, np.kron(sx, i2)),
        np.kron(i2, np.kron(i2, sx)),
    ]


def hs_inner(a: np.ndarray, b: np.ndarray) -> complex:
    return complex(np.trace(a.conj().T @ b))


def hs_norm(a: np.ndarray) -> float:
    return math.sqrt(max(float(hs_inner(a, a).real), 0.0))


def normalize(a: np.ndarray) -> np.ndarray:
    norm = hs_norm(a)
    if norm == 0.0:
        raise ValueError("cannot normalize zero operator")
    return a / norm


def max_abs(a: np.ndarray) -> float:
    return float(np.max(np.abs(a)))


def cube_vertices() -> list[tuple[int, int, int]]:
    return [
        (eps0, eps1, eps2)
        for eps0 in (-1, 1)
        for eps1 in (-1, 1)
        for eps2 in (-1, 1)
    ]


def flip(vertex: tuple[int, int, int], index: int) -> tuple[int, int, int]:
    values = list(vertex)
    values[index] *= -1
    return tuple(values)  # type: ignore[return-value]


def cycle(vertex: tuple[int, int, int]) -> tuple[int, int, int]:
    return (vertex[1], vertex[2], vertex[0])


def function_vector(kind: str, vertices: list[tuple[int, int, int]]) -> np.ndarray:
    rows: list[float] = []
    for eps0, eps1, eps2 in vertices:
        if kind == "constant":
            rows.append(1.0)
        elif kind == "E1":
            rows.append(float(eps0 + eps1 + eps2))
        elif kind == "E2":
            rows.append(float(eps0 * eps1 + eps1 * eps2 + eps2 * eps0))
        elif kind == "E3":
            rows.append(float(eps0 * eps1 * eps2))
        else:
            raise ValueError(kind)
    return np.array(rows, dtype=float)


def hamming_laplacian(vertices: list[tuple[int, int, int]]) -> np.ndarray:
    index = {vertex: row for row, vertex in enumerate(vertices)}
    laplacian = np.zeros((len(vertices), len(vertices)), dtype=float)
    for row, vertex in enumerate(vertices):
        for axis in range(3):
            col = index[flip(vertex, axis)]
            laplacian[row, row] += 1.0
            laplacian[row, col] -= 1.0
    return laplacian


def dirichlet_energy(vec: np.ndarray, laplacian: np.ndarray) -> float:
    return float(vec.T @ laplacian @ vec / vec.size)


def inner_average(left: np.ndarray, right: np.ndarray) -> float:
    return float(left.T @ right / left.size)


def eigen_report(laplacian: np.ndarray, vertices: list[tuple[int, int, int]]) -> dict[str, Any]:
    basis = {
        name: function_vector(name, vertices)
        for name in ("constant", "E1", "E2", "E3")
    }
    rows: dict[str, Any] = {}
    for name, vec in basis.items():
        norm = math.sqrt(inner_average(vec, vec))
        unit = vec / norm
        image = laplacian @ unit
        eigenvalue = inner_average(unit, image)
        residual = float(np.max(np.abs(image - eigenvalue * unit)))
        rows[name] = {
            "average_norm": norm,
            "laplacian_eigenvalue": eigenvalue,
            "eigen_residual_max_abs": residual,
            "dirichlet_energy_unit_norm": dirichlet_energy(unit, laplacian),
        }
    gram: dict[str, float] = {}
    names = list(basis)
    for i, left_name in enumerate(names):
        for right_name in names[i + 1 :]:
            left = basis[left_name] / math.sqrt(inner_average(basis[left_name], basis[left_name]))
            right = basis[right_name] / math.sqrt(inner_average(basis[right_name], basis[right_name]))
            gram[f"{left_name}:{right_name}"] = inner_average(left, right)
    return {"basis_rows": rows, "orthogonality_average_inner_products": gram}


def z3_commutes_with_laplacian(laplacian: np.ndarray, vertices: list[tuple[int, int, int]]) -> bool:
    index = {vertex: row for row, vertex in enumerate(vertices)}
    permutation = np.zeros_like(laplacian)
    for vertex, row in index.items():
        permutation[index[cycle(vertex)], row] = 1.0
    return max_abs(permutation @ laplacian - laplacian @ permutation) < 1.0e-12


def operator_axis_match() -> dict[str, Any]:
    axes = taste_axes()
    s0, s1, s2 = axes
    selected = normalize(s0 + s1 + s2)
    implemented = (s0 + s1 + s2) / math.sqrt(24.0)
    return {
        "selected_operator_hs_norm": hs_norm(selected),
        "implemented_taste_radial_hs_norm": hs_norm(implemented),
        "selected_minus_implemented_max_abs": max_abs(selected - implemented),
        "hs_inner_selected_implemented": float(hs_inner(selected, implemented).real),
    }


def main() -> int:
    print("PR #230 Block118 Hamming-Dirichlet O_H axis selector")
    print("=" * 72)

    certs = {name: load_json(path) for name, path in PARENTS.items()}
    statuses = {name: status(cert) for name, cert in certs.items()}
    missing = [name for name, cert in certs.items() if not cert]
    proposals = [name for name, cert in certs.items() if cert.get("proposal_allowed") is True]
    strict_presence = {name: (ROOT / rel).exists() for name, rel in STRICT_CLOSURE_PATHS.items()}

    vertices = cube_vertices()
    laplacian = hamming_laplacian(vertices)
    spectrum = eigen_report(laplacian, vertices)
    rows = spectrum["basis_rows"]
    z3_commutes = z3_commutes_with_laplacian(laplacian, vertices)
    axis = operator_axis_match()

    trace_zero_cyclic_modes = ["E1", "E2", "E3"]
    eigenvalues = {name: rows[name]["laplacian_eigenvalue"] for name in trace_zero_cyclic_modes}
    unique_lowest_name = min(eigenvalues, key=eigenvalues.get)
    sorted_gap = sorted(eigenvalues.values())[1] - sorted(eigenvalues.values())[0]
    unique_lowest_cyclic_trace_zero_mode = unique_lowest_name == "E1" and sorted_gap > 1.0
    e1_axis_matches_taste_radial = (
        axis["selected_minus_implemented_max_abs"] < 1.0e-12
        and abs(axis["hs_inner_selected_implemented"] - 1.0) < 1.0e-12
    )
    laplacian_is_native_hamming_cube = (
        laplacian.shape == (8, 8)
        and np.allclose(laplacian, laplacian.T)
        and np.allclose(laplacian @ np.ones(8), np.zeros(8))
        and z3_commutes
    )
    selector_exact_support = (
        not missing
        and not proposals
        and laplacian_is_native_hamming_cube
        and unique_lowest_cyclic_trace_zero_mode
        and e1_axis_matches_taste_radial
        and max(
            abs(value)
            for value in spectrum["orthogonality_average_inner_products"].values()
        )
        < 1.0e-12
        and max(row["eigen_residual_max_abs"] for row in rows.values()) < 1.0e-12
    )
    degree_one_filter_retired_for_axis_only = (
        selector_exact_support
        and "degree-one Higgs-action premise not derived"
        in statuses["degree_one_action_premise"]
    )
    action_lsz_and_rows_still_absent = (
        "does not derive accepted EW/Higgs action"
        in statuses["block110_action_descent_obstruction"]
        and certs["block114_source_higgs_resolver"].get("canonical_oh_certificate_absent")
        is True
        and certs["block114_source_higgs_resolver"].get("accepted_same_source_action_absent")
        is True
        and certs["block114_source_higgs_resolver"].get("strict_source_higgs_pole_rows_absent")
        is True
        and certs["fms_oh_candidate_action_packet"].get("accepted_current_surface") is False
        and certs["source_higgs_pole_acceptance_contract"].get("rows_present") is False
        and not any(strict_presence.values())
    )
    source_overlap_still_open = (
        certs["fms_source_overlap_readout_gate"].get("readout_executable_now") is False
        and certs["fms_source_overlap_readout_gate"].get("strict_rows_present") is False
        and certs["block112_helmholtz_obstruction"].get("canonical_source_higgs_overlap_fixed")
        is False
        and certs["block112_helmholtz_obstruction"].get("helmholtz_mixed_response_rows_present")
        is False
    )
    aggregate_gates_still_deny_closure = (
        certs["full_positive_assembly"].get("proposal_allowed") is False
        and certs["retained_route"].get("proposal_allowed") is False
        and certs["completion_audit"].get("proposal_allowed") is False
        and "retained closure not achieved"
        in statuses["completion_audit"]
    )
    firewall_clean = all(value is False for value in FORBIDDEN_FIREWALL.values())
    block118_passed = (
        selector_exact_support
        and degree_one_filter_retired_for_axis_only
        and action_lsz_and_rows_still_absent
        and source_overlap_still_open
        and aggregate_gates_still_deny_closure
        and firewall_clean
    )

    report("parent-certificates-present", not missing, f"missing={missing}")
    report("no-parent-authorizes-proposal", not proposals, f"proposal_allowed={proposals}")
    report("native-hamming-laplacian-z3-compatible", laplacian_is_native_hamming_cube, f"z3_commutes={z3_commutes}")
    report("cyclic-trace-zero-basis-diagonal", max(row["eigen_residual_max_abs"] for row in rows.values()) < 1.0e-12, str(rows))
    report("unique-lowest-cyclic-trace-zero-mode-is-e1", unique_lowest_cyclic_trace_zero_mode, f"eigenvalues={eigenvalues} gap={sorted_gap}")
    report("e1-axis-matches-implemented-taste-radial-source", e1_axis_matches_taste_radial, str(axis))
    report("degree-one-filter-retired-for-axis-selection-only", degree_one_filter_retired_for_axis_only, statuses["degree_one_action_premise"])
    report("action-lsz-and-pole-rows-still-absent", action_lsz_and_rows_still_absent, str(strict_presence))
    report("source-overlap-still-open", source_overlap_still_open, statuses["fms_source_overlap_readout_gate"])
    report("aggregate-gates-still-deny-closure", aggregate_gates_still_deny_closure, statuses["completion_audit"])
    report("forbidden-firewall-clean", firewall_clean, str(FORBIDDEN_FIREWALL))
    report("block118-hamming-dirichlet-oh-axis-selector-passed", block118_passed, "exact support only; no closure")

    result: dict[str, Any] = {
        "certificate_kind": "pr230_block118_hamming_dirichlet_oh_axis_selector",
        "actual_current_surface_status": (
            "exact support / Block118 native Hamming-Dirichlet selector fixes "
            "the PR230 taste-radial O_H axis as the unique lowest cyclic "
            "trace-zero finite Dirichlet mode; accepted EW/Higgs action, "
            "scalar LSZ metric, source-overlap normalization, and strict "
            "C_ss/C_sH/C_HH pole rows remain absent"
        ),
        "conditional_surface_status": (
            "source-Higgs support if a future accepted same-surface EW/Higgs "
            "action and scalar LSZ/canonical normalization adopt this selected "
            "axis as canonical O_H and production physical Euclidean "
            "C_ss/C_sH/C_HH(tau) pole rows pass Gram, threshold, FV/IR, "
            "contact, and covariance gates"
        ),
        "hypothetical_axiom_status": None,
        "admitted_observation_status": None,
        "proposal_allowed": False,
        "proposal_allowed_reason": (
            "The finite Hamming-Dirichlet selector is an exact axis-selection "
            "support artifact only. It does not supply a dynamic EW/Higgs "
            "action, canonical scalar LSZ metric, source-overlap rows, W/Z "
            "physical-response rows, or retained-route approval."
        ),
        "audit_required_before_effective_retained": True,
        "bare_retained_allowed": False,
        "parent_statuses": statuses,
        "strict_closure_path_presence": strict_presence,
        "forbidden_firewall": FORBIDDEN_FIREWALL,
        "cube_vertices": vertices,
        "hamming_laplacian": laplacian.tolist(),
        "spectrum": spectrum,
        "z3_commutes_with_laplacian": z3_commutes,
        "trace_zero_cyclic_mode_eigenvalues": eigenvalues,
        "unique_lowest_cyclic_trace_zero_mode": unique_lowest_name,
        "spectral_gap_to_next_cyclic_mode": sorted_gap,
        "operator_axis_match": axis,
        "selector_exact_support": selector_exact_support,
        "degree_one_filter_retired_for_axis_selection_only": degree_one_filter_retired_for_axis_only,
        "action_lsz_and_pole_rows_still_absent": action_lsz_and_rows_still_absent,
        "source_overlap_still_open": source_overlap_still_open,
        "aggregate_gates_still_deny_closure": aggregate_gates_still_deny_closure,
        "block118_hamming_dirichlet_oh_axis_selector_passed": block118_passed,
        "minimal_allowed_premises": [
            "the PR230 three-generator source/taste algebra and its primitive idempotent Boolean-cube realization",
            "the single-generator flip graph on that finite cube as a mathematical Hamming-Dirichlet selector",
            "the Z3 coordinate cycle acting on the three taste generators",
            "current PR230 aggregate firewalls that deny action/LSZ/pole-row closure",
        ],
        "open_imports_after_block118": [
            "accepted same-surface EW/Higgs action or canonical operator theorem",
            "canonical scalar LSZ/kinetic normalization for the selected axis",
            "production physical Euclidean C_ss/C_sH/C_HH(tau) pole rows",
            "Gram flatness, threshold, FV/IR, contact, and covariance authority",
            "source-overlap readout or physical W/Z/neutral bypass",
        ],
        "claim_boundary": (
            "Block118 may be used as the finite-axis selector for future "
            "O_H/action work. It must not be used to relabel existing "
            "C_sx/C_xx rows as C_sH/C_HH or to set kappa_s, c2, Z_match, or "
            "g2 to one."
        ),
        "pass_count": PASS_COUNT,
        "fail_count": FAIL_COUNT,
    }
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"\nWrote certificate: {OUTPUT.relative_to(ROOT)}")
    print(f"SUMMARY: PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    return 0 if FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
