#!/usr/bin/env python3
"""Exact gates for the Gleason qubit-lattice projection narrow theorem note."""

from itertools import combinations
from pathlib import Path
import re
import sys

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
NOTE = ROOT / "docs/GLEASON_ON_QUBIT_LATTICE_PROJECTION_LATTICE_NARROW_THEOREM_NOTE_2026-05-20.md"
SUBSTRATE = ROOT / "docs/QUBIT_LATTICE_JOINT_PRESENTATION_TENSOR_SUBSTRATE_BRIDGE_NOTE_2026-07-09.md"

PASS = 0
FAIL = 0


def check(label: str, condition: bool) -> None:
    """Record and print one discriminating gate."""
    global PASS, FAIL
    if condition:
        PASS += 1
        result = "PASS"
    else:
        FAIL += 1
        result = "FAIL"
    print(f"[{result}] {label}")


def projection(vector: sp.Matrix) -> sp.Matrix:
    """Return the exact rank-1 projection generated by a unit vector."""
    return (vector * vector.H).applyfunc(sp.simplify)


def hermitian_coordinates(matrix: sp.Matrix) -> sp.Matrix:
    """Embed a 4x4 Hermitian matrix in its 16-dimensional real coordinate space."""
    coordinates = [sp.re(matrix[i, i]) for i in range(4)]
    for i, j in combinations(range(4), 2):
        coordinates.append(sp.re(matrix[i, j]))
        coordinates.append(sp.im(matrix[i, j]))
    return sp.Matrix(coordinates).applyfunc(sp.simplify)


def is_projection(matrix: sp.Matrix) -> bool:
    return matrix.H == matrix and matrix * matrix == matrix


txt = NOTE.read_text(encoding="utf-8")
flat = " ".join(txt.split())

check("A1 raw trace-form needle", "m(P) = Tr" in txt)
check(
    "A1 physical Born/readout identification remains outside the claim",
    "does **not** identify the projections as physical measurement outcomes" in flat
    and "framework-generated physical probability" in flat,
)
check(
    "A2 finite-region Hilbert-space needle",
    "specific Hilbert space `H_Λ = ⊗_{x ∈ Λ} ℂ²` for finite `Λ ⊂ Z^3`" in flat,
)
check(
    "A3 unique trace-form representation needle",
    "Deriving the unique trace-form representation `m(P) = Tr(σ P)` for measures satisfying the stated mathematical hypotheses."
    in flat,
)
check("A4 live axiom-memo link present", "](MINIMAL_AXIOMS_2026-06-29.md)" in flat)
check("A4 historical axiom-memo link absent", "](MINIMAL_AXIOMS_2026-05-20.md)" not in flat)
check(
    "A5 joint-presentation tensor-substrate bridge link present",
    "](QUBIT_LATTICE_JOINT_PRESENTATION_TENSOR_SUBSTRATE_BRIDGE_NOTE_2026-07-09.md)"
    in flat,
)
substrate_text = SUBSTRATE.read_text(encoding="utf-8") if SUBSTRATE.exists() else ""
check(
    "A5 linked tensor-substrate dependency resolves with its bounded input surface",
    SUBSTRATE.exists()
    and "**Type:** bounded_theorem" in substrate_text
    and "supplied commuting joint presentation" in substrate_text.lower()
    and "minimality selection `m = 1`" in substrate_text,
)
forbidden_readout_vocabulary = ("log-scale response", "z W'", "zW'")
check(
    "A6 forbidden readout vocabulary absent",
    all(needle not in txt for needle in forbidden_readout_vocabulary),
)
check(
    "A7 independent-audit status present",
    "independent audit lane owns the verdict" in flat,
)
check("A7 retained status absent", "Status: retained" not in flat)

claim_restriction = re.search(
    r"## Claim Let `Λ ⊂ Z\^3` be a finite region with `\|Λ\| ≥ (\d+)`\.", flat
)
minimum_region_size = int(claim_restriction.group(1)) if claim_restriction else None
allowed_dimensions = all(2**n >= 4 >= 3 for n in range(2, 6))
singleton_is_outside_hypothesis = 2**1 < 3
check(
    "B1 dimension threshold and load-bearing region restriction",
    minimum_region_size == 2 and allowed_dimensions and singleton_is_outside_hypothesis,
)

sigma = sp.diag(
    sp.Rational(1, 10),
    sp.Rational(2, 10),
    sp.Rational(3, 10),
    sp.Rational(4, 10),
)
sigma_eigenvalues = sigma.eigenvals()
check(
    "B2 exact positive density matrix on C^4",
    all(entry.is_Rational is True for entry in sigma)
    and sigma.H == sigma
    and sp.trace(sigma) == 1
    and all(eigenvalue > 0 for eigenvalue in sigma_eigenvalues),
)

zero = sp.zeros(4)
identity = sp.eye(4)
basis = [sp.eye(4).col(i) for i in range(4)]
basis_projections = [projection(vector) for vector in basis]


def measure(matrix: sp.Matrix, projector: sp.Matrix) -> sp.Expr:
    return sp.simplify(sp.trace(matrix * projector))


check(
    "B2 measure normalization",
    measure(sigma, zero) == 0 and measure(sigma, identity) == 1,
)
orthogonal_resolution = (
    all(is_projection(projector) for projector in basis_projections)
    and all(
        basis_projections[i] * basis_projections[j] == zero
        for i, j in combinations(range(4), 2)
    )
    and sum(basis_projections, zero) == identity
)
check(
    "B2 exact orthogonal-resolution additivity",
    orthogonal_resolution
    and sum((measure(sigma, projector) for projector in basis_projections), sp.S.Zero)
    == 1,
)
check(
    "B2 pairwise projection additivity",
    all(
        measure(sigma, basis_projections[i] + basis_projections[j])
        == measure(sigma, basis_projections[i]) + measure(sigma, basis_projections[j])
        for i, j in combinations(range(4), 2)
    ),
)

spanning_projections = list(basis_projections)
for i, j in combinations(range(4), 2):
    real_vector = (basis[i] + basis[j]) / sp.sqrt(2)
    imaginary_vector = (basis[i] + sp.I * basis[j]) / sp.sqrt(2)
    spanning_projections.extend((projection(real_vector), projection(imaginary_vector)))

spanning_coordinates = sp.Matrix.hstack(
    *(hermitian_coordinates(projector) for projector in spanning_projections)
)
check(
    "B3 rank-1 projections span the full Hermitian space",
    len(spanning_projections) == 16
    and all(
        is_projection(projector)
        and sp.trace(projector) == 1
        and projector.rank() == 1
        for projector in spanning_projections
    )
    and all(coordinate.is_Rational is True for coordinate in spanning_coordinates)
    and spanning_coordinates.rank() == 16,
)

diagonal_projections = [
    sp.diag(*[sp.Integer((mask >> i) & 1) for i in range(4)])
    for mask in range(2**4)
]
diagonal_coordinates = sp.Matrix.hstack(
    *(hermitian_coordinates(projector) for projector in diagonal_projections)
)
diagonal_span_dimension = diagonal_coordinates.rank()
check(
    "B4 commuting-only span deficiency detected",
    all(is_projection(projector) for projector in diagonal_projections)
    and all(
        left * right == right * left
        for left, right in combinations(diagonal_projections, 2)
    )
    and diagonal_span_dimension == 4
    and diagonal_span_dimension < 16,
)

nonpositive_sigma = sp.diag(
    sp.Rational(-1, 2),
    sp.Rational(1, 2),
    sp.Rational(1, 2),
    sp.Rational(1, 2),
)
nonpositive_eigenvalues = nonpositive_sigma.eigenvals()
negative_eigenvalue_count = sum(
    multiplicity
    for eigenvalue, multiplicity in nonpositive_eigenvalues.items()
    if eigenvalue < 0
)
negative_projection = basis_projections[0]
check(
    "B5 non-positive trace-one matrix violates measure positivity",
    nonpositive_sigma.H == nonpositive_sigma
    and sp.trace(nonpositive_sigma) == 1
    and negative_eigenvalue_count == 1
    and is_projection(negative_projection)
    and measure(nonpositive_sigma, negative_projection) == sp.Rational(-1, 2)
    and measure(nonpositive_sigma, negative_projection) < 0,
)

print(f"TOTAL: PASS={PASS} FAIL={FAIL}")
print("VERDICT: PASS" if FAIL == 0 else "VERDICT: FAIL")
sys.exit(0 if FAIL == 0 else 1)
