"""S3/Route-2 endpoint-independent consumer inventory.

Question
--------
Which direct Route-2 theta-to-slice consumers are independent of the unresolved
E-row readout coefficient rho_E?

Result
------
After the two T-side entries are granted, the reduced readout family is

    P(rho_E) = [[1, 0, rho_E, 0],
                [0,-2, 0,     2]].

For a restricted carrier c=(u_E,u_T,delta_E,delta_T), rho_E appears only as
rho_E * delta_E in the E source component. Therefore the rho-independent
consumer subspace is exactly the hyperplane delta_E=0, spanned by E-shell,
T-shell, and T-center. The quotient is one-dimensional and generated by the
pure E-center-excess direction.
"""
from __future__ import annotations

from fractions import Fraction as F
from pathlib import Path

import sympy as sp

PASS = 0
FAIL = 0


def check(label: str, cond: bool, detail: str = "") -> bool:
    global PASS, FAIL
    ok = bool(cond)
    PASS += int(ok)
    FAIL += int(not ok)
    print(f"[{'PASS' if ok else 'FAIL'}] {label}")
    if detail:
        print(f"       {detail}")
    return ok


def P(rho: F) -> sp.Matrix:
    return sp.Matrix([[1, 0, sp.Rational(rho.numerator, rho.denominator), 0], [0, -2, 0, 2]])


E_SHELL = sp.Matrix([1, 0, 0, 0])
E_CENTER = sp.Matrix([1, 0, sp.Rational(1, 6), 0])
T_SHELL = sp.Matrix([0, 1, 0, 0])
T_CENTER = sp.Matrix([0, 1, 0, sp.Rational(1, 6)])
PURE_DELTA_E = E_CENTER - E_SHELL


def depends_on_rho(c: sp.Matrix) -> bool:
    rho0 = F(0, 1)
    rho1 = F(21, 4)
    return P(rho0) * c != P(rho1) * c


def main() -> int:
    print("S3/Route-2 endpoint-independent consumer inventory")
    print("=" * 88)

    rho0 = F(0, 1)
    rho1 = F(21, 4)
    dP = P(rho1) - P(rho0)
    check(
        "rho_E variation is rank one and acts only through the delta_E coordinate",
        dP.rank() == 1 and dP == sp.Matrix([[0, 0, sp.Rational(21, 4), 0], [0, 0, 0, 0]]),
        f"dP={dP}",
    )

    kernel = dP.nullspace()
    kernel_basis = [tuple(v) for v in kernel]
    expected_kernel = {
        tuple(E_SHELL),
        tuple(T_SHELL),
        tuple(T_CENTER * 6),
    }
    check(
        "rho-independent carrier subspace is exactly delta_E=0 with dimension 3",
        len(kernel) == 3
        and all(v[2, 0] == 0 for v in kernel)
        and {tuple(E_SHELL), tuple(T_SHELL), tuple(sp.Matrix([0, 0, 0, 1]))}.issubset(set(kernel_basis) | expected_kernel),
        f"kernel_basis={kernel}",
    )

    endpoint_columns = {
        "E-shell": E_SHELL,
        "E-center": E_CENTER,
        "T-shell": T_SHELL,
        "T-center": T_CENTER,
    }
    inventory = {name: depends_on_rho(col) for name, col in endpoint_columns.items()}
    check(
        "endpoint columns inventory: only E-center depends on rho_E",
        inventory == {"E-shell": False, "E-center": True, "T-shell": False, "T-center": False},
        f"inventory={inventory}",
    )

    images_at_target = {name: P(rho1) * col for name, col in endpoint_columns.items()}
    check(
        "target rho_E=21/4 changes E-center to q_E=15/8 and leaves the other endpoint images fixed",
        images_at_target["E-center"] == sp.Matrix([sp.Rational(15, 8), 0])
        and images_at_target["E-shell"] == sp.Matrix([1, 0])
        and images_at_target["T-shell"] == sp.Matrix([0, -2])
        and images_at_target["T-center"] == sp.Matrix([0, sp.Rational(-5, 3)]),
        f"images={images_at_target}",
    )

    a, b, de, dt = sp.symbols("a b de dt")
    c = sp.Matrix([a, b, de, dt])
    symbolic_delta = sp.simplify((P(rho1) - P(rho0)) * c)
    check(
        "generic carrier dependence is exactly (rho1-rho0)*delta_E in the E source component",
        symbolic_delta == sp.Matrix([sp.Rational(21, 4) * de, 0]),
        f"delta={symbolic_delta}",
    )

    quotient_rank = sp.Matrix.hstack(PURE_DELTA_E).rank()
    check(
        "rho-dependent quotient is one-dimensional, generated by the pure E-center-excess direction",
        quotient_rank == 1
        and depends_on_rho(PURE_DELTA_E)
        and not depends_on_rho(E_SHELL)
        and not depends_on_rho(T_SHELL)
        and not depends_on_rho(T_CENTER),
        f"pure_delta_E={PURE_DELTA_E.T}",
    )

    consumer_classes = {
        "slice_backbone_Lambda_R_T_R_V_R": "independent",
        "conditional_family_formula_Xi_P": "parametric",
        "carrier_delta_E_zero": "independent",
        "carrier_delta_E_nonzero": "inherits rho_E",
        "unique_theta_to_slice_theorem": "blocked",
    }
    check(
        "consumer class inventory separates independent, parametric, inherited, and blocked uses",
        consumer_classes["slice_backbone_Lambda_R_T_R_V_R"] == "independent"
        and consumer_classes["carrier_delta_E_zero"] == "independent"
        and consumer_classes["carrier_delta_E_nonzero"] == "inherits rho_E"
        and consumer_classes["unique_theta_to_slice_theorem"] == "blocked",
        f"classes={consumer_classes}",
    )

    note_paths = [
        Path("docs/QUARK_ROUTE2_EXACT_TIME_COUPLING_NOTE_2026-04-19.md"),
        Path("docs/S3_TIME_THETA_TO_SLICE_COUPLING_NOTE.md"),
        Path("docs/S3_TIME_PRIMITIVE_CHAIN_NOTE.md"),
    ]
    note_text = "\n".join(path.read_text() for path in note_paths)
    check(
        "source notes name the exact conditional family and inherited readout obstruction",
        "Xi_P(t ; c)" in note_text
        and "V_R(t)" in note_text
        and "beta_E / alpha_E = 21/4" in note_text
        and "unique" in note_text
        and "open" in note_text,
        "time-coupling, theta-to-slice, and primitive-chain notes contain the expected anchors",
    )

    print("\n" + "=" * 88)
    print(f"PASS={PASS} FAIL={FAIL}")
    print(
        "\nVERDICT: exact-support inventory. Any direct consumer whose restricted\n"
        "carrier has delta_E=0 is independent of the unresolved rho_E entry.\n"
        "The only direct rho_E carrier quotient is the pure E-center-excess\n"
        "direction; consumers with nonzero delta_E inherit the scalar readout\n"
        "ambiguity, and a unique theta-to-slice theorem remains blocked upstream."
    )
    return 1 if FAIL else 0


if __name__ == "__main__":
    raise SystemExit(main())
