#!/usr/bin/env python3
"""Minimal PR230 Y_T source-action support packet gate.

This runner intentionally replaces the earlier block/chunk history with one
self-contained check:

* the product RN source composes by source-field addition;
* its origin score is the primitive one-site signed record;
* the same family is generated by a source-coupled site-diagonal local action;
* retained/proposed-retained Y_T closure remains forbidden.
"""

from __future__ import annotations

import itertools
import json
import math
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "outputs" / "yt_pr230_consolidated_status_2026-05-22.json"
NOTE = ROOT / "docs" / "YT_PR230_CONSOLIDATED_STATUS_NOTE_2026-05-22.md"

PASS_COUNT = 0
FAIL_COUNT = 0


def report(tag: str, ok: bool, detail: Any) -> None:
    global PASS_COUNT, FAIL_COUNT
    if ok:
        PASS_COUNT += 1
        state = "PASS"
    else:
        FAIL_COUNT += 1
        state = "FAIL"
    print(f"{state}: {tag}: {detail}")


def states(n_sites: int) -> list[tuple[int, ...]]:
    return list(itertools.product((-1, 1), repeat=n_sites))


def rn_density(h: list[float], omega: list[tuple[int, ...]]) -> list[float]:
    weights = [math.exp(sum(hi * ei for hi, ei in zip(h, eps))) for eps in omega]
    z = sum(weights)
    return [w / z for w in weights]


def normalize(weights: list[float]) -> list[float]:
    z = sum(weights)
    return [w / z for w in weights]


def l1(a: list[float], b: list[float]) -> float:
    return sum(abs(x - y) for x, y in zip(a, b))


def max_abs(a: list[float], b: list[float]) -> float:
    return max(abs(x - y) for x, y in zip(a, b))


def main() -> int:
    print("PR230 minimal Y_T source-action support packet")
    print("=" * 72)

    omega = states(3)
    h = [0.17, -0.23, 0.31]
    k = [-0.11, 0.29, 0.07]
    rh = rn_density(h, omega)
    rk = rn_density(k, omega)
    rhk = rn_density([hi + ki for hi, ki in zip(h, k)], omega)
    composed = normalize([a * b for a, b in zip(rh, rk)])
    composition_l1_error = l1(composed, rhk)

    delta = 1.0e-6
    origin = [0.0, 0.0, 0.0]
    derivative_errors: list[float] = []
    for site in range(3):
        hp = origin.copy()
        hm = origin.copy()
        hp[site] = delta
        hm[site] = -delta
        rp = rn_density(hp, omega)
        rm = rn_density(hm, omega)
        score = [(math.log(a) - math.log(b)) / (2.0 * delta) for a, b in zip(rp, rm)]
        primitive = [float(eps[site]) for eps in omega]
        derivative_errors.append(max_abs(score, primitive))
    max_generator_error = max(derivative_errors)

    # For uniform S0, exp(-S_h) with S_h = S0 - h.epsilon gives exactly the
    # product RN density.  This is the source/action equivalence being reduced
    # to one open authority gate.
    action_weights = [math.exp(sum(hi * ei for hi, ei in zip(h, eps))) for eps in omega]
    action_density = normalize(action_weights)
    action_equivalence_l1_error = l1(action_density, rh)

    strict_source_higgs_rows = ROOT / "outputs" / "yt_pr230_block508_id_source_higgs_strict_rows_2026-05-22.json"
    strict_wz_packet = ROOT / "outputs" / "yt_pr230_strict_same_source_wz_physical_response_packet_2026-05-22.json"

    forbidden_imports = {
        "H_unit": False,
        "yt_ward_identity": False,
        "y_t_bare": False,
        "observed_top_or_yukawa_target": False,
        "alpha_LM_or_plaquette_u0": False,
        "package_v_as_closure": False,
        "Planck_or_alpha_s": False,
        "fitted_selector": False,
    }
    remaining_gates = [
        "accept or derive the equivalent source/action gate as current same-surface neutral EW/Higgs authority",
        "derive canonical O_H and scalar LSZ normalization on that accepted surface",
        "produce strict C_ss/C_sH/C_HH source-Higgs pole rows, or a strict same-source W/Z bypass",
        "only after physical input exists, run matching/running and retained-proposal gates",
    ]

    report("note-present", NOTE.exists(), NOTE.relative_to(ROOT).as_posix())
    report("product-rn-composes-by-source-addition", composition_l1_error < 1.0e-12, composition_l1_error)
    report("origin-score-is-primitive-one-site-record", max_generator_error < 1.0e-9, max_generator_error)
    report("site-diagonal-source-action-equivalent-to-product-rn", action_equivalence_l1_error < 1.0e-12, action_equivalence_l1_error)
    report("source-action-authority-still-open", True, "support result only")
    report("strict-source-higgs-rows-absent", not strict_source_higgs_rows.exists(), strict_source_higgs_rows.relative_to(ROOT).as_posix())
    report("strict-wz-bypass-absent", not strict_wz_packet.exists(), strict_wz_packet.relative_to(ROOT).as_posix())
    report("proposal-retained-forbidden", True, "not retained and not proposed_retained")
    report("forbidden-import-firewall-clean", not any(forbidden_imports.values()), forbidden_imports)
    report("remaining-gates-explicit", len(remaining_gates) == 4, remaining_gates)

    result = {
        "generated_at": "2026-05-22T00:00:00Z",
        "actual_current_surface_status": (
            "exact support / narrowed blocker: product RN source semantics and "
            "source-coupled site-diagonal local action are equivalent, but this "
            "gate is not accepted as current neutral EW/Higgs authority and "
            "positive Y_T closure is not achieved"
        ),
        "proposal_allowed": False,
        "proposal_allowed_reason": (
            "The packet contains support mathematics only.  It lacks accepted "
            "source/action authority, canonical O_H/scalar LSZ, strict physical "
            "pole rows or W/Z bypass, and matching/running closure."
        ),
        "bare_retained_allowed": False,
        "audit_required_before_effective_retained": True,
        "current_closure_satisfied": False,
        "consolidated_status_passed": PASS_COUNT == 10 and FAIL_COUNT == 0,
        "composition_l1_error": composition_l1_error,
        "max_generator_error": max_generator_error,
        "action_equivalence_l1_error": action_equivalence_l1_error,
        "source_action_gate_accepted": False,
        "canonical_oh_lsz_present": False,
        "strict_source_higgs_rows_present": strict_source_higgs_rows.exists(),
        "strict_wz_bypass_present": strict_wz_packet.exists(),
        "forbidden_imports": forbidden_imports,
        "remaining_gates": remaining_gates,
        "review_surface": [
            "docs/YT_PR230_CONSOLIDATED_STATUS_NOTE_2026-05-22.md",
            "scripts/frontier_yt_pr230_consolidated_status.py",
            "outputs/yt_pr230_consolidated_status_2026-05-22.json",
        ],
        "pass_count": PASS_COUNT,
        "fail_count": FAIL_COUNT,
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    print(f"SUMMARY: PASS={PASS_COUNT} FAIL={FAIL_COUNT}")
    return 0 if PASS_COUNT == 10 and FAIL_COUNT == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
