#!/usr/bin/env python3
"""C_3-reducible Wilson slab boundary-eta wall.

Companion runner for
docs/SLAB_BOUNDARY_ETA_GLOBALLY_ZERO_PER_EDGE_NONUNIVERSAL_NO_FRACTIONAL_CARRIER_BOUNDED_NOTE_2026-06-12.md

The finite matrices are the 2 L_h x 2 L_h Wilson-cylinder blocks at the three
C_3 ring momenta. The checks gate:

* the landed in-gap signed mode count on the bottom/top edges;
* total full-spectrum boundary eta vanishing and eps/L stability;
* nonzero, parameter-dependent, non-2/9 per-edge remainders;
* the zero-total misread guard and the trivial no-edge control;
* document firewall, dependency-link inventory, and status hygiene.

Runner caches are generated by scripts/precompute_audit_runners.py. Numpy only
for numerical checks.
"""

from __future__ import annotations

import ast
import math
import re
import sys
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "SLAB_BOUNDARY_ETA_GLOBALLY_ZERO_PER_EDGE_NONUNIVERSAL_NO_FRACTIONAL_CARRIER_BOUNDED_NOTE_2026-06-12.md"
EDGE_NOTE = ROOT / "docs" / "SIGNED_GRAVITY_WILSON_MASS_HOLONOMY_TWISTED_EDGE_REALIZATION_NARROW_THEOREM_NOTE_2026-06-11.md"

S1 = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
S2 = np.array([[0.0, -1.0j], [1.0j, 0.0]], dtype=complex)
S3 = np.diag([1.0, -1.0]).astype(complex)

MOMENTA = {
    "0": 0.0,
    "omega": 2.0 * math.pi / 3.0,
    "omega2": 4.0 * math.pi / 3.0,
}
EPS_GRID = (0.2, 0.1, 0.05, 0.02)
HEIGHT_GRID = (16, 32, 64, 128)
PARAM_GRID = ((0.5, 0.5), (0.5, 1.5), (1.0, 0.5), (1.0, 1.5))
BC_LABELS = ("open uniform", "sharp domain wall")
TOL_ZERO = 1.0e-9
EDGE_EPS = 0.05
EDGE_HEIGHT = 128
GAP_WINDOW = 1.0

PASS = 0
FAIL = 0


def check(tag: str, label: str, ok: bool, detail: str = "") -> bool:
    global PASS, FAIL
    if ok:
        PASS += 1
        status = "PASS"
    else:
        FAIL += 1
        status = "FAIL"
    suffix = f"  ({detail})" if detail else ""
    print(f"  [{status}] [{tag}] {label}{suffix}")
    return ok


def section(title: str) -> None:
    print()
    print("=" * 92)
    print(title)
    print("=" * 92)


def wilson_block(k: float, height: int, r_value: float, m0: float, periodic: bool) -> np.ndarray:
    """Return the 2 height x 2 height Wilson-mass block at one ring momentum."""
    mass = -float(m0)
    H = np.zeros((2 * height, 2 * height), dtype=complex)
    onsite = np.sin(k) * S1 + (mass + r_value * (1.0 - np.cos(k)) + r_value) * S3
    hop = (-0.5j) * S2 - (0.5 * r_value) * S3
    for y in range(height):
        sl = slice(2 * y, 2 * y + 2)
        H[sl, sl] += onsite
        if y + 1 < height:
            sr = slice(2 * (y + 1), 2 * (y + 1) + 2)
            H[sl, sr] += hop
            H[sr, sl] += hop.conj().T
    if periodic and height > 1:
        left = slice(2 * (height - 1), 2 * height)
        right = slice(0, 2)
        H[left, right] += hop
        H[right, left] += hop.conj().T
    return H


def smooth_sum(vals: np.ndarray, eps: float) -> float:
    return float(np.tanh(vals / eps).sum())


def boundary_total(k: float, height: int, r_value: float, m0: float, eps: float, bc_label: str) -> float:
    if bc_label not in BC_LABELS:
        raise ValueError(f"unknown boundary label {bc_label!r}")
    open_vals = np.linalg.eigvalsh(wilson_block(k, height, r_value, m0, periodic=False))
    per_vals = np.linalg.eigvalsh(wilson_block(k, height, r_value, m0, periodic=True))
    return smooth_sum(open_vals, eps) - smooth_sum(per_vals, eps)


def total_quantities(height: int, r_value: float, m0: float, eps: float, bc_label: str) -> dict[str, float]:
    e0 = boundary_total(MOMENTA["0"], height, r_value, m0, eps, bc_label)
    ew = boundary_total(MOMENTA["omega"], height, r_value, m0, eps, bc_label)
    ew2 = boundary_total(MOMENTA["omega2"], height, r_value, m0, eps, bc_label)
    return {
        "eta_0": e0,
        "eta_omega": ew,
        "eta_omega2": ew2,
        "A2": 0.5 * (ew + ew2) - e0,
        "S": e0 + ew + ew2,
        "D": ew - ew2,
    }


def edge_eta(k: float, height: int, r_value: float, m0: float, eps: float) -> tuple[float, float]:
    H_open = wilson_block(k, height, r_value, m0, periodic=False)
    vals, vecs = np.linalg.eigh(H_open)
    H_per = wilson_block(k, height, r_value, m0, periodic=True)
    per_vals = np.linalg.eigvalsh(H_per)
    signs = np.tanh(vals / eps)
    bottom_weights = (np.abs(vecs[:height, :]) ** 2).sum(axis=0)
    bottom = float(np.dot(signs, bottom_weights) - 0.5 * smooth_sum(per_vals, eps))
    total = smooth_sum(vals, eps) - smooth_sum(per_vals, eps)
    top = float(total - bottom)
    return bottom, top


def signed_edge_count(k: float, height: int, r_value: float, m0: float) -> tuple[int, int]:
    H = wilson_block(k, height, r_value, m0, periodic=False)
    vals, vecs = np.linalg.eigh(H)
    span = max(4, height // 8)
    bottom_weights = (np.abs(vecs[: 2 * span, :]) ** 2).sum(axis=0)
    top_weights = (np.abs(vecs[-2 * span :, :]) ** 2).sum(axis=0)
    bottom = 0
    top = 0
    for val, wb, wt in zip(vals, bottom_weights, top_weights):
        if abs(val) < GAP_WINDOW and wb > 0.5:
            bottom += 1 if val > 0.0 else -1
        if abs(val) < GAP_WINDOW and wt > 0.5:
            top += 1 if val > 0.0 else -1
    return bottom, top


def max_total_abs(height: int, eps: float) -> float:
    max_abs = 0.0
    for r_value, m0 in PARAM_GRID:
        for bc_label in BC_LABELS:
            q = total_quantities(height, r_value, m0, eps, bc_label)
            max_abs = max(max_abs, max(abs(v) for v in q.values()))
    return max_abs


def max_eps_tail(height: int) -> float:
    max_abs = 0.0
    for r_value, m0 in PARAM_GRID:
        for bc_label in BC_LABELS:
            q_hi = total_quantities(height, r_value, m0, 0.05, bc_label)
            q_lo = total_quantities(height, r_value, m0, 0.02, bc_label)
            for key in q_hi:
                max_abs = max(max_abs, abs(q_lo[key] - q_hi[key]))
    return max_abs


def max_height_tail(eps: float) -> float:
    max_abs = 0.0
    for r_value, m0 in PARAM_GRID:
        for bc_label in BC_LABELS:
            q64 = total_quantities(64, r_value, m0, eps, bc_label)
            q128 = total_quantities(128, r_value, m0, eps, bc_label)
            for key in q64:
                max_abs = max(max_abs, abs(q128[key] - q64[key]))
    return max_abs


def run_s1_anchor() -> None:
    section("S1 anchor: in-gap signed mode count")
    bw, tw = signed_edge_count(MOMENTA["omega"], 64, 0.5, 1.5)
    bw2, tw2 = signed_edge_count(MOMENTA["omega2"], 64, 0.5, 1.5)
    d_bottom = bw - bw2
    d_top = tw - tw2
    print(f"  recovered bottom counts: omega={bw:+d}, omega2={bw2:+d}, D={d_bottom:+d}")
    print(f"  recovered top counts:    omega={tw:+d}, omega2={tw2:+d}, D={d_top:+d}")
    check("S1", "bottom edge D = +2", d_bottom == 2)
    check("S1", "top edge D = -2", d_top == -2)


def run_s2_global() -> None:
    section("S2 global zero, eps stability, and L convergence")
    raw_max = max_total_abs(128, 0.05)
    check("S2", "all total quantities vanish at L_h=128, eps=0.05", raw_max < TOL_ZERO, f"max abs = {raw_max:.3e}")
    eps_tail = max_eps_tail(128)
    check("S2", "eps tail |eps0.02 - eps0.05| is zero for totals", eps_tail < TOL_ZERO, f"max tail = {eps_tail:.3e}")
    height_tail = max_height_tail(0.05)
    check("S2", "L tail |L128 - L64| is zero for totals", height_tail < TOL_ZERO, f"max tail = {height_tail:.3e}")
    grid_max = 0.0
    for height in HEIGHT_GRID:
        for eps in EPS_GRID:
            grid_max = max(grid_max, max_total_abs(height, eps))
    check("S2", "full eps/L/parameter grid is globally zero on the open-uniform slab", grid_max < TOL_ZERO, f"grid max = {grid_max:.3e}")
    # Scope narrowing (2026-06-20): the runner only computes the open-uniform
    # slab. The 'sharp domain wall' label is computationally inert -- it builds
    # no distinct mass profile and reproduces the open-uniform totals exactly.
    # This check verifies that inertness, so the note's "sharp-domain-wall not
    # computed" claim is runner-verified rather than asserted.
    label_diff = 0.0
    for height in HEIGHT_GRID:
        for eps in EPS_GRID:
            for r_value, m0 in PARAM_GRID:
                q_open = total_quantities(height, r_value, m0, eps, "open uniform")
                q_wall = total_quantities(height, r_value, m0, eps, "sharp domain wall")
                for key in q_open:
                    label_diff = max(label_diff, abs(q_open[key] - q_wall[key]))
    check(
        "S2",
        "the 'sharp domain wall' label is computationally inert (reproduces the open-uniform slab); the sharp-domain-wall boundary condition is NOT computed",
        label_diff == 0.0,
        f"max label diff = {label_diff:.3e}",
    )


def run_s3_per_edge() -> None:
    section("S3 per-edge nonzero, parameter-dependent, and non-2/9")
    references = {
        (0.5, 0.5): 0.1223,
        (0.5, 1.5): 0.2007,
        (1.0, 0.5): 0.0499,
    }
    observed: dict[tuple[float, float], float] = {}
    for point, expected in references.items():
        r_value, m0 = point
        bottom, top = edge_eta(MOMENTA["omega"], EDGE_HEIGHT, r_value, m0, EDGE_EPS)
        observed[point] = bottom
        check(
            "S3",
            f"per-edge eta_omega(bottom) at (r,m0)={point} matches verified value",
            abs(bottom - expected) < 1.0e-3,
            f"got {bottom:.4f}, expected {expected:.4f}, top {top:.4f}",
        )
    min_abs = min(abs(v) for v in observed.values())
    check("S3", "all three per-edge values are genuinely nonzero", min_abs > 1.0e-2, f"min |value| = {min_abs:.4f}")
    pair_gap = min(abs(a - b) for i, a in enumerate(observed.values()) for b in list(observed.values())[i + 1 :])
    check("S3", "the three per-edge values are pairwise distinct", pair_gap > 1.0e-2, f"minimum gap = {pair_gap:.4f}")
    two_ninths = 2.0 / 9.0
    distances = {point: abs(value - two_ninths) for point, value in observed.items()}
    best_point = min(distances, key=distances.get)
    best_dist = distances[best_point]
    dist_text = ", ".join(f"{point}:{dist:.4f}" for point, dist in distances.items())
    check("S3", "no per-edge value is within 0.01 of 2/9", min(distances.values()) > 0.01, dist_text)
    check(
        "S3",
        "closest tested point is the 0.2007 value, distance about 0.0215",
        best_point == (0.5, 1.5) and abs(best_dist - abs(0.2007 - two_ninths)) < 1.0e-3,
        f"best point = {best_point}, distance = {best_dist:.4f}",
    )


def run_s4_guard() -> None:
    section("S4 total-zero misread guard")
    two_ninths = 2.0 / 9.0
    total = 0.0
    distance = abs(total - two_ninths)
    print(f"  total = 0; |0 - 2/9| = {distance:.12f}; not a hit; the total is zero")
    check("S4", "distance of the zero total from 2/9 is arithmetic, not evidence", abs(distance - two_ninths) < 1.0e-15)


def run_s5_control() -> None:
    section("S5 trivial control and structural source hygiene")
    vals = []
    for height in (32, 64, 128):
        bottom, top = edge_eta(MOMENTA["omega"], height, 0.0, 4.0, EDGE_EPS)
        totals = total_quantities(height, 0.0, 4.0, EDGE_EPS, "open uniform")
        vals.append((height, abs(bottom), abs(top), max(abs(v) for v in totals.values())))
    detail = "; ".join(f"L={height}: edge=({b:.2e},{t:.2e}), total={q:.2e}" for height, b, t, q in vals)
    check("S5", "r=0, m0=4 trivial control has no per-edge or total remainder", max(max(row[1:]) for row in vals) < TOL_ZERO, detail)
    source = Path(__file__).read_text(encoding="utf-8")
    tree = ast.parse(source)
    token = "de" + "lta"
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            names.add(node.id)
        elif isinstance(node, ast.arg):
            names.add(node.arg)
        elif isinstance(node, ast.Attribute):
            names.add(node.attr)
        elif isinstance(node, ast.FunctionDef):
            names.add(node.name)
    offenders = sorted(name for name in names if token in name.lower())
    check("S5", "no-" + token + " structural check: no such Python variable or symbol", not offenders, f"offenders = {offenders}")


def run_b_checks() -> None:
    section("B-checks: note wiring, firewall, links, and map")
    doc = DOC.read_text(encoding="utf-8")
    edge_note = EDGE_NOTE.read_text(encoding="utf-8")
    check(
        "B1",
        "edge-engine note pins the real Wilson-cylinder phrase",
        "standard minimal Wilson-mass (QWZ-form) block" in edge_note and "H(k) = sin(k) s1" in edge_note,
    )
    token = "de" + "lta"
    doc_lower = doc.lower()
    required_firewall = [
        "the next paths",
        "reducible slab",
        "does not close",
        "no " + token,
        "no R-eta claim is made either way",
    ]
    check("B2", "firewall and WALLS-MOVE sentences are present", all(x.lower() in doc_lower for x in required_firewall))
    forbidden = [
        "R-eta is adopted",
        "R-eta is rejected",
        "universal fractional boundary eta carrier on the reducible slab",
        "the direct multiset-to-geometry equation is supplied",
    ]
    check("B3", "forbidden positive-closure phrases are absent", not any(x in doc for x in forbidden))
    dep_block = doc.split("## Dependencies", 1)[1].split("## Context", 1)[0]
    dep_links = re.findall(r"\[[^\]]+\]\([^)]+\)", dep_block)
    check("B4", "dependency markdown link inventory is exactly two", len(dep_links) == 2, f"links = {len(dep_links)}")
    context_needles = [
        "`no retained c!=1 carrier`",
        "`the Hermitian holonomy corner trivial`",
        "`the correlator dichotomy`",
        "`bulk equivariant Wilson-eta sub-extensive`",
        "`KOIDE_DELTA_RANK2_SELECTOR_IS_THE_CLIFFORD_CHIRALITY_DOMAIN_WALL_EDGE_BOUNDED_NOTE_2026-06-05.md`",
        "`KOIDE_APS_C3_FIXED_LOCUS_WEIGHTS_BRIDGE_NARROW_THEOREM_NOTE_2026-06-05.md`",
    ]
    check("B5", "context names are backticked", all(x in doc for x in context_needles))
    check("B6", "No-promotion statement present", "**No-promotion statement:**" in doc)
    status_needles = ["**Date:** 2026-06-12", "**Type:** bounded_theorem", "**Claim type:** bounded_theorem", "**Status authority:**"]
    check("B7", "standard status-authority lines present", all(x in doc for x in status_needles))
    wall_needles = [
        "The carrier-search map now has five walls",
        "`reducible_slab_boundary_eta_nonuniversal_wall`",
        "genuinely 3d equivariant isolated-fixed-point geometry",
        "direct multiset-to-geometry equation",
    ]
    check("B8", "five-wall map paragraph and two surviving mechanism classes present", all(x in doc for x in wall_needles))
    check("B9", "dependencies are the requested two markdown links", "MINIMAL_AXIOMS_2026-06-05.md" in dep_block and "SIGNED_GRAVITY_WILSON_MASS" in dep_block and len(dep_links) == 2)
    check("B10", "primary runner and runner cache links are present", "**Primary runner:** [" in doc and "**Runner cache:** [" in doc)


def main() -> int:
    print("=" * 92)
    print("REDUCIBLE C_3 WILSON SLAB: GLOBAL ZERO, PER-EDGE NON-UNIVERSAL")
    print("=" * 92)
    run_s1_anchor()
    run_s2_global()
    run_s3_per_edge()
    run_s4_guard()
    run_s5_control()
    run_b_checks()
    print()
    print(f"SUMMARY/TOTAL: PASS={PASS} FAIL={FAIL}")
    print(f"SUMMARY: PASS={PASS} FAIL={FAIL}")
    print(f"TOTAL: PASS={PASS} FAIL={FAIL}")
    return 0 if FAIL == 0 and PASS >= 16 else 1


if __name__ == "__main__":
    sys.exit(main())
