#!/usr/bin/env python3
"""Cycle 890 INDEPENDENT ADVERSARIAL CHECKER -- spec'd to REFUTE.

The Cycle-890 primary claims (i) T1: canonical IFF multiplicity-free on every
realized class x scope row of the 30-subgroup census, with both sides computed
by non-communicating routes; (ii) T2: multiplicity-freeness forces the SL1-type
pair, witnessed forced at C3 and C4 and NOT forced at S3; (iii) T3: on the
recomputed honest scope menu the subset carrying BOTH a v_2 = 1 datum and a
forced realization is exactly {C3_body, C4_face}; (iv) H2: 355 sentences swept
with a byte-exact completeness proof, grade ceiling PARTIAL, verdict
NOT_QUOTABLE.

This checker tries to break every one of those, using machinery built from
different mathematics:

  *  the rotation group is rebuilt as a PERMUTATION group on the 6-neighbour
     shell, generated by two named rotations and closed -- no 3x3 matrices, no
     signed-permutation enumeration;
  *  conjugacy classes are named by a COMPUTED invariant (order, shell orbit
     length multiset, element order multiset, class size), never by the
     primary's axis-kind naming;
  *  multiplicity-freeness is decided by ORBITAL (Schur) ALGEBRA
     COMMUTATIVITY: the commutant of the permutation module is spanned by the
     orbital adjacency matrices, and the module is multiplicity-free over Q
     exactly when that algebra is commutative.  The primary used the
     ENVELOPING algebra and a minimal-polynomial factorization; this is the
     dual object and a different linear system;
  *  canonicity is decided by the ATOM TEST on the submodule lattice: the
     minimal nonzero submodules are exhibited over integer grids, and the
     module is canonical exactly when the atoms are independent (their
     dimensions sum to the space) and the atom set is STABLE under grid growth.
     The primary used dim Hom_A(U, M) - dim End_A(U);
  *  the safety check is Cycle 888's FIND-3 identity in the checker's own
     currency: the orbital count must equal Burnside's (1/|H|) sum_g fix(g)^2
     and must equal sum_i m_i^2 [F_i : Q] as claimed by the primary -- so every
     fine row the primary reports is constrained by a number this checker
     computed for itself;
  *  T3 is attacked with a FULL READING MATRIX: every (v_2-datum reading,
     forcedness scope) combination, on and off the menu, so a class that
     sneaks in under a reading the primary skipped would show up here;
  *  H2 is re-swept on a DIFFERENT SEGMENTATION -- clause level, not sentence
     level -- under the checker's own rubric, plus a blunt needle scan for the
     vocabulary that would close the question outright.

Eight teeth are bitten deliberately.  The checker exits 0 whether the primary's
claims survive or die: its job is to report, not to defend.
"""
from __future__ import annotations

AUDIT_TIMEOUT_SEC = 900
STDOUT_LIMIT_BYTES = 400_000

AUDIT_INPUT_PATHS = (
    "docs/MINIMAL_AXIOMS_2026-06-29.md",
    "scripts/frontier_cycle890_multiplicity_freeness_2026_07_28.py",
    "outputs/multiplicity_freeness_cycle890_receipt_2026_07_28.json",
    "outputs/s3_scope_pricing_cycle888_receipt_2026_07_28.json",
    "docs/GATE_B_DYNAMICS_NOTE.md",
    "docs/GATE_B_WEAK_FIELD_SOURCE_ACTION_INTERFACE_NOTE_2026-06-16.md",
    "docs/AC_RETA_HCLASS_HUNIT_READOUT_DERIVATION_OBLIGATION.md",
)

SWEPT_DOCUMENT_PATHS = (
    AUDIT_INPUT_PATHS[0],
    AUDIT_INPUT_PATHS[4],
    AUDIT_INPUT_PATHS[5],
    AUDIT_INPUT_PATHS[6],
)

import ast
from fractions import Fraction
from hashlib import sha256
import importlib.abc
from itertools import product
import json
from math import gcd
from pathlib import Path
import re
import subprocess
import sys
from time import monotonic

ROOT = Path(__file__).resolve().parents[1]
RECEIPT = ROOT / "outputs" / \
    "multiplicity_freeness_independent_check_cycle890_receipt_2026_07_28.json"

BLOCKLISTED_MODULES = tuple(Path(p).stem for p in AUDIT_INPUT_PATHS)

EXPECTED_SHA256 = {
    AUDIT_INPUT_PATHS[0]:
        "fc4d60cce8154cec26be12a0735033de43a0e554e7be951ffc0399c0b9788697",
    AUDIT_INPUT_PATHS[3]:
        "8a540201a84a6b8cb6868d431216718a27f200e45d6ceeb771d858e9a54280cd",
    AUDIT_INPUT_PATHS[4]:
        "0031e5ddcb2e1408db1bca3d738669b5463e672cfdbecc81b859b0fc609dc271",
    AUDIT_INPUT_PATHS[5]:
        "e246730a808174752f2bb1e113a89bccdf691db81b76bc1e2f6347ab027b0116",
    AUDIT_INPUT_PATHS[6]:
        "4d742bcc68a1e7cdb154b366e671f576e9b719b3206445b97666c812a790e58c",
}
EXPECTED_GIT_BLOBS = {
    AUDIT_INPUT_PATHS[0]: "4a863da1f3f255354839277271a3a69a5c205133",
    AUDIT_INPUT_PATHS[3]: "3e18ad52f50e72b83c56da72c31f25d104b5c830",
    AUDIT_INPUT_PATHS[4]: "5594d74e38a84d95c806449a305a16e1f1db8c43",
    AUDIT_INPUT_PATHS[5]: "2c9e1d0c75ea801f25fa0f9cfa92c67553770b4c",
    AUDIT_INPUT_PATHS[6]: "9a449956422a5687b5b1346f428c9e4e35489038",
}

TARGET_PAIR = (1, 2)
GRADES = ("EXACT", "PARTIAL", "NONE")


class _Firewall(importlib.abc.MetaPathFinder):
    def __init__(self) -> None:
        self.hits: list[str] = []

    def find_module(self, fullname, path=None):       # pragma: no cover legacy
        return self.find_spec(fullname, path)

    def find_spec(self, fullname, path=None, target=None):
        if fullname.rsplit(".", 1)[-1] in BLOCKLISTED_MODULES:
            self.hits.append(fullname)
            raise ImportError(f"BLOCKLIST forbids import of {fullname}")
        return None


FIREWALL = _Firewall()
sys.meta_path.insert(0, FIREWALL)


def _read_bytes(path: str) -> bytes:
    return (ROOT / path).read_bytes()


def _read_text(path: str) -> str:
    return _read_bytes(path).decode("utf-8")


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def digest(payload) -> str:
    return sha256(json.dumps(payload, sort_keys=True,
                             default=str).encode("utf-8")).hexdigest()


def vp2(value: int) -> int | None:
    if value == 0:
        return None
    e = 0
    while value % 2 == 0:
        value //= 2
        e += 1
    return e


# --------------------------------------------------------------------------
# exact rational linear algebra (checker's own)
# --------------------------------------------------------------------------
def rref(rows):
    m = [[Fraction(x) for x in r] for r in rows]
    if not m or not m[0]:
        return [], []
    w = len(m[0])
    piv, rank = [], 0
    for col in range(w):
        p = None
        for r in range(rank, len(m)):
            if m[r][col] != 0:
                p = r
                break
        if p is None:
            continue
        m[rank], m[p] = m[p], m[rank]
        h = m[rank][col]
        m[rank] = [x / h for x in m[rank]]
        for r in range(len(m)):
            if r != rank and m[r][col] != 0:
                f = m[r][col]
                m[r] = [a - f * b for a, b in zip(m[r], m[rank])]
        piv.append(col)
        rank += 1
    return m[:rank], piv


def rank_exact(rows) -> int:
    return len(rref(rows)[0])


def key_of(rows) -> tuple:
    reduced, _ = rref(rows)
    return tuple(tuple(f"{x.numerator}/{x.denominator}" for x in row)
                 for row in reduced)


# ==========================================================================
# the rotation group, rebuilt as PERMUTATIONS of the 6-neighbour shell
# ==========================================================================
SHELL_LABELS = ("+x", "+y", "+z", "-x", "-y", "-z")
# generator 1: the quarter turn about the z axis, (x, y, z) -> (-y, x, z)
R4Z = (1, 3, 2, 4, 0, 5)
# generator 2: the third turn about the (1,1,1) body diagonal, (x,y,z)->(z,x,y)
R3D = (1, 2, 0, 4, 5, 3)
IDENT6 = (0, 1, 2, 3, 4, 5)


def compose(a, b):
    """(a after b): the permutation sending i to a[b[i]]."""
    return tuple(a[b[i]] for i in range(6))


def perm_order(p) -> int:
    cur, k = p, 1
    while cur != IDENT6:
        cur = compose(cur, p)
        k += 1
        if k > 24:                                     # pragma: no cover gate
            raise AssertionError("not a finite permutation")
    return k


def perm_closure(seeds) -> frozenset:
    found = {IDENT6} | set(seeds)
    frontier = list(found)
    while frontier:
        cur = frontier.pop()
        for other in list(found):
            for prod in (compose(cur, other), compose(other, cur)):
                if prod not in found:
                    found.add(prod)
                    frontier.append(prod)
    return frozenset(found)


GROUP = sorted(perm_closure((R4Z, R3D)))
GROUP_SET = frozenset(GROUP)
INVERSE = {p: next(x for x in GROUP if compose(p, x) == IDENT6) for p in GROUP}
SHELL = tuple(range(6))


def orbits_of(subgroup, points) -> list[tuple]:
    seen, out = set(), []
    for p in points:
        if p in seen:
            continue
        orbit = {p}
        frontier = [p]
        while frontier:
            cur = frontier.pop()
            for g in subgroup:
                nxt = g[cur]
                if nxt not in orbit:
                    orbit.add(nxt)
                    frontier.append(nxt)
        seen |= orbit
        out.append(tuple(sorted(orbit)))
    return out


def all_subgroups() -> list[frozenset]:
    found = {frozenset({IDENT6})}
    for a in GROUP:
        for b in GROUP:
            found.add(perm_closure((a, b)))
    return sorted(found, key=lambda h: (len(h), sorted(h)))


LATTICE = all_subgroups()


def conjugacy_class_of(h):
    return frozenset(
        frozenset(compose(compose(g, x), INVERSE[g]) for x in h)
        for g in GROUP)


def class_signature(h) -> tuple:
    """A name computed from invariants only -- never borrowed."""
    orbs = sorted(len(o) for o in orbits_of(sorted(h), SHELL))
    element_orders = sorted(perm_order(g) for g in h)
    cyclic = any(perm_closure((g,)) == h for g in h)
    abelian = all(compose(a, b) == compose(b, a) for a in h for b in h)
    return (len(h), tuple(orbs), tuple(element_orders), cyclic, abelian)


def build_classes() -> list[dict]:
    seen: dict[frozenset, int] = {}
    classes: list[dict] = []
    for h in LATTICE:
        if h in seen:
            continue
        klass = conjugacy_class_of(h)
        idx = len(classes)
        for member in klass:
            seen[member] = idx
        classes.append({
            "class_index": idx,
            "representative": sorted(h),
            "key": h,
            "order": len(h),
            "size": len(klass),
            "signature": class_signature(h),
            "shell_orbit_lengths": sorted(len(o) for o in
                                          orbits_of(sorted(h), SHELL)),
            "element_orders": sorted(perm_order(g) for g in h),
            "is_cyclic": class_signature(h)[3],
            "is_abelian": class_signature(h)[4],
            "normalizer_order": len([g for g in GROUP if frozenset(
                compose(compose(g, x), INVERSE[g]) for x in h) == h]),
        })
    return sorted(classes, key=lambda c: (c["order"], c["shell_orbit_lengths"],
                                          c["size"]))


CLASSES = build_classes()

# the checker's OWN correspondence to the primary's names, computed from
# (order, shell orbit lengths, class size) -- a triple that is unique across
# the eleven classes, verified by a gate below.
PRIMARY_NAME_BY_SIGNATURE = {
    (1, (1, 1, 1, 1, 1, 1), 1): "E_trivial",
    (2, (1, 1, 2, 2), 3): "C2_face",
    (2, (2, 2, 2), 6): "C2_edge",
    (3, (3, 3), 4): "C3_body",
    (4, (1, 1, 4), 3): "C4_face",
    (4, (2, 2, 2), 1): "V_face",
    (4, (2, 4), 3): "V_edge",
    (6, (6,), 4): "S3_body",
    (8, (2, 4), 3): "D4_face",
    (12, (6,), 1): "A4_tetrahedral",
    (24, (6,), 1): "O_full",
}


def primary_name(c: dict) -> str | None:
    return PRIMARY_NAME_BY_SIGNATURE.get(
        (c["order"], tuple(c["shell_orbit_lengths"]), c["size"]))


# ==========================================================================
# ORBITAL (Schur) algebra -- the checker's multiplicity-freeness route
# ==========================================================================
def orbitals(subgroup, points) -> list[list[tuple]]:
    """Orbits of the subgroup on X x X."""
    seen, out = set(), []
    for a in points:
        for b in points:
            if (a, b) in seen:
                continue
            orbit = set()
            for g in subgroup:
                orbit.add((g[a], g[b]))
            seen |= orbit
            out.append(sorted(orbit))
    return out


def orbital_matrices(subgroup, points):
    idx = {p: i for i, p in enumerate(points)}
    n = len(points)
    mats = []
    for orb in orbitals(subgroup, points):
        m = [[0] * n for _ in range(n)]
        for a, b in orb:
            if a in idx and b in idx:
                m[idx[a]][idx[b]] = 1
        mats.append(m)
    return mats


def int_mat_mul(a, b):
    n, k, w = len(a), len(b), len(b[0])
    return [[sum(a[i][t] * b[t][j] for t in range(k)) for j in range(w)]
            for i in range(n)]


def perm_matrix(g, points):
    idx = {p: i for i, p in enumerate(points)}
    n = len(points)
    m = [[0] * n for _ in range(n)]
    for p in points:
        m[idx[g[p]]][idx[p]] = 1
    return m


def checker_multiplicity_free(subgroup, points) -> dict:
    """The permutation module is multiplicity-free over Q exactly when its
    commutant -- spanned by the orbital adjacency matrices -- is commutative."""
    n = len(points)
    mats = orbital_matrices(subgroup, points)
    r = len(mats)
    commuting = True
    witness = None
    for i in range(r):
        for j in range(i + 1, r):
            if int_mat_mul(mats[i], mats[j]) != int_mat_mul(mats[j], mats[i]):
                commuting = False
                if witness is None:
                    witness = [i, j]
    # safety: Burnside on points and on pairs, computed directly
    order = len(subgroup)
    fixed = [sum(1 for p in points if g[p] == p) for g in sorted(subgroup)]
    burnside_orbits = Fraction(sum(fixed), order)
    burnside_orbitals = Fraction(sum(f * f for f in fixed), order)
    direct_orbits = len(orbits_of(sorted(subgroup), points))
    # safety: the orbital matrices really do commute with the representation
    rho = [perm_matrix(g, points) for g in sorted(subgroup)]
    is_commutant = all(int_mat_mul(rg, m) == int_mat_mul(m, rg)
                       for m in mats for rg in rho)
    # safety: the orbital matrices sum to the all-ones matrix
    total = [[sum(m[i][j] for m in mats) for j in range(n)] for i in range(n)]
    partition = all(total[i][j] == 1 for i in range(n) for j in range(n))
    gates = {
        "burnside_orbit_count_matches_the_direct_count":
            burnside_orbits == direct_orbits,
        "burnside_orbital_count_matches_the_direct_count":
            burnside_orbitals == r,
        "every_orbital_matrix_commutes_with_the_representation": is_commutant,
        "the_orbital_matrices_partition_X_times_X": partition,
    }
    return {
        "route": "CHECKER_orbital_Schur_algebra_commutativity",
        "space_dimension": n,
        "orbital_count_equals_dim_of_the_commutant": r,
        "burnside_orbital_count": f"{burnside_orbitals.numerator}/"
                                  f"{burnside_orbitals.denominator}",
        "orbit_count": direct_orbits,
        "commutant_is_commutative": commuting,
        "first_noncommuting_orbital_pair": witness,
        "MULTIPLICITY_FREE": commuting,
        "coarse_ordered_pair": [direct_orbits, n - direct_orbits],
        "gates": gates,
        "all_gates_pass": all(gates.values()),
    }


# ==========================================================================
# ATOM TEST -- the checker's canonicity route
# ==========================================================================
def cyclic_submodules(subgroup, points, radius, cap=6000):
    n = len(points)
    perms = [tuple(g[p] for p in points) for g in sorted(subgroup)]
    index = {p: i for i, p in enumerate(points)}
    perm_idx = [tuple(index[x] for x in pm) for pm in perms]
    found: dict[tuple, list] = {}
    truncated = False
    for w in product(range(-radius, radius + 1), repeat=n):
        if not any(w):
            continue
        g0 = 0
        for x in w:
            g0 = gcd(g0, abs(x))
        if tuple(x // g0 for x in w) != w or next(x for x in w if x != 0) < 0:
            continue
        span = []
        for pm in perm_idx:
            v = [0] * n
            for j in range(n):
                v[pm[j]] = w[j]
            span.append(v)
        reduced, _ = rref(span)
        k = key_of(reduced)
        if k not in found:
            found[k] = [list(row) for row in reduced]
            if len(found) > cap:
                truncated = True
                break
    return found, truncated


def contains(outer, inner) -> bool:
    return rank_exact([list(r) for r in outer] + [list(r) for r in inner]) \
        == rank_exact(outer)


def atoms_of(found: dict, n: int, atom_cap: int) -> dict:
    """Minimal nonzero submodules, level by level.  Once the accumulated atoms
    span the whole module every irreducible submodule has already been seen, so
    the search stops -- that is a proof, not a heuristic."""
    by_dim: dict[int, list] = {}
    for basis in found.values():
        by_dim.setdefault(len(basis), []).append(basis)
    atoms: list[list] = []
    span_rows: list[list] = []
    exceeded = False
    for d in sorted(by_dim):
        if span_rows and rank_exact(span_rows) == n:
            break
        smaller = [b for dd in sorted(by_dim) if dd < d for b in by_dim[dd]]
        for basis in by_dim[d]:
            if any(contains(basis, s) for s in smaller):
                continue
            atoms.append(basis)
            span_rows = span_rows + [list(r) for r in basis]
            if len(atoms) > atom_cap:
                exceeded = True
                break
        if exceeded:
            break
    return {
        "atoms": atoms,
        "atom_count": len(atoms),
        "atom_dimensions": sorted(len(a) for a in atoms),
        "atom_dimension_sum": sum(len(a) for a in atoms),
        "atom_span_dimension": rank_exact(span_rows) if span_rows else 0,
        "atom_cap_exceeded": exceeded,
        "atom_keys": sorted(key_of(a) for a in atoms) if not exceeded else None,
    }


def checker_canonicity(subgroup, points) -> dict:
    """CANONICAL iff the atoms are independent (dimensions sum to the space)
    AND the atom set is stable when the enumeration grid grows."""
    n = len(points)
    found1, trunc1 = cyclic_submodules(subgroup, points, 1)
    a1 = atoms_of(found1, n, atom_cap=n)
    if a1["atom_cap_exceeded"] or a1["atom_dimension_sum"] != n:
        return {
            "route": "CHECKER_atom_test_on_the_submodule_lattice",
            "space_dimension": n,
            "grid_radius_1_submodules": len(found1),
            "radius_1_atoms": a1["atom_count"] if not a1["atom_cap_exceeded"]
            else f">{n}",
            "radius_1_atom_dimensions": a1["atom_dimensions"],
            "radius_1_atom_dimension_sum": a1["atom_dimension_sum"],
            "atoms_are_independent": False,
            "atom_set_is_stable_under_grid_growth": None,
            "CANONICAL": False,
            "why": (
                "more minimal submodules than a canonical module can carry: "
                f"the atom dimensions already sum to {a1['atom_dimension_sum']} "
                f"in a space of dimension {n}" if not a1["atom_cap_exceeded"]
                else f"the atom count exceeds the space dimension {n}, which "
                     "no multiplicity-free module can do"),
            "gates": {"atom_search_terminated_cleanly": True},
            "all_gates_pass": True,
        }
    found2, trunc2 = cyclic_submodules(subgroup, points, 2)
    a2 = atoms_of(found2, n, atom_cap=n)
    stable = (not a2["atom_cap_exceeded"]
              and a1["atom_keys"] == a2["atom_keys"])
    canonical = stable and a2["atom_dimension_sum"] == n
    return {
        "route": "CHECKER_atom_test_on_the_submodule_lattice",
        "space_dimension": n,
        "grid_radius_1_submodules": len(found1),
        "grid_radius_2_submodules": len(found2),
        "grid_radius_2_truncated": trunc2,
        "radius_1_atoms": a1["atom_count"],
        "radius_2_atoms": a2["atom_count"] if not a2["atom_cap_exceeded"]
        else f">{n}",
        "atom_dimensions": a2["atom_dimensions"]
        if not a2["atom_cap_exceeded"] else a1["atom_dimensions"],
        "atom_dimension_sum": a2["atom_dimension_sum"],
        "atoms_are_independent": a2["atom_dimension_sum"] == n,
        "atom_set_is_stable_under_grid_growth": stable,
        "CANONICAL": canonical,
        "why": ("the atoms are independent, span the space and do not change "
                "when the grid grows: the decomposition is a single point"
                if canonical else
                "the atom set grows with the enumeration grid, so the minimal "
                "submodules form an infinite family"),
        "gates": {"atom_search_terminated_cleanly": True},
        "all_gates_pass": True,
    }


# ==========================================================================
# clause-level segmentation -- DIFFERENT from the primary's sentence level
# ==========================================================================
FENCE = re.compile(r"^\s*(```|~~~)")


def clause_segments(text: str) -> list[dict]:
    """Byte-exact partition at CLAUSE granularity: prose is cut at sentence
    terminators AND at semicolons, colons and em-dash breaks."""
    segments: list[dict] = []
    in_fence = False
    pos = 0
    for line in text.splitlines(keepends=True):
        start = pos
        pos += len(line)
        if FENCE.match(line):
            segments.append({"start": start, "text": line, "kind": "CODE"})
            in_fence = not in_fence
            continue
        if in_fence or not line.strip() or line.lstrip().startswith("|"):
            segments.append({"start": start, "text": line,
                             "kind": "CODE" if in_fence else "GAP"})
            continue
        if line.lstrip().startswith("#"):
            segments.append({"start": start, "text": line, "kind": "HEADING"})
            continue
        # cut inside the line
        cuts = []
        backticks = 0
        for i, ch in enumerate(line):
            if ch == "`":
                backticks += 1
                continue
            if backticks % 2 == 1:
                continue
            if ch in ";:":
                cuts.append(i + 1)
            elif ch in ".!?":
                nxt = line[i + 1] if i + 1 < len(line) else ""
                if nxt in ("", " ", "\n", "\t"):
                    cuts.append(i + 1)
            elif ch == "-" and line[i:i + 3] == " --":
                cuts.append(i)
        cuts.append(len(line))
        prev = 0
        for cut in sorted(set(c for c in cuts if 0 < c <= len(line))):
            if cut <= prev:
                continue
            piece = line[prev:cut]
            kind = "CLAUSE" if piece.strip() else "GAP"
            segments.append({"start": start + prev, "text": piece,
                             "kind": kind})
            prev = cut
        if prev < len(line):
            segments.append({"start": start + prev, "text": line[prev:],
                             "kind": "GAP"})
    return segments


CHECKER_RUBRIC = {
    "target": (
        "multiplicity-freeness of the readout representation, or any property "
        "that implies it: a canonical decomposition, a unique invariant "
        "complement, a readout determined up to no free parameter"
    ),
    "R1_names_the_readout_object": (
        "readout", "readable", "read", "representation", "decomposition",
        "possibility domain", "possibilities", "presentation", "algebra",
        "observable", "record content", "reading", "context",
    ),
    "R2_asserts_no_freedom": (
        "determined", "determines", "exactly one", "unique", "uniquely",
        "alone", "only", "fixed", "canonical", "no free", "no further",
        "rigid", "single", "never more than", "complete", "one and only",
    ),
    "R3_names_the_decomposition_level": (
        "decomposition", "multiplicity", "multiplicity-free", "irreducible",
        "isotype", "isotypic", "invariant complement", "invariant subspace",
        "complement", "summand", "direct sum", "up to isomorphism",
    ),
    "R4_polarity_excludes": (
        "downstream", "not generic axiom content", "must cite separate",
        "remains outside", "remain outside", "does not include", "historical",
        "must not", "remains conditional", "remain conditional", "open",
        "supersede", "does not derive", "derives no", "changes no", "no-go",
        "supplies no", "not a retained", "does not close", "conditional",
        "pending", "obligation",
    ),
    "rule": (
        "EXACT iff R1 and R2 and R3 all fire in the SAME clause and R4 does "
        "not; PARTIAL iff exactly two of R1/R2/R3 fire and R4 does not; NONE "
        "otherwise. Clause granularity makes the same-clause requirement "
        "structural rather than a heuristic."
    ),
}

CLOSING_NEEDLES = (
    "multiplicity", "multiplicity-free", "canonical decomposition",
    "unique decomposition", "uniquely decompos", "invariant complement",
    "invariant subspace", "no free parameter", "isotypic", "isotype",
    "irreducible", "up to isomorphism", "unique up to", "direct sum",
    "schur", "commutant",
)


def checker_grade(text: str) -> dict:
    low = norm(text).lower()

    def hits(family):
        return sorted({m for m in family if m in low})

    r1 = hits(CHECKER_RUBRIC["R1_names_the_readout_object"])
    r2 = hits(CHECKER_RUBRIC["R2_asserts_no_freedom"])
    r3 = hits(CHECKER_RUBRIC["R3_names_the_decomposition_level"])
    r4 = hits(CHECKER_RUBRIC["R4_polarity_excludes"])
    if r4:
        grade = "NONE"
        reason = f"polarity {r4} places the content outside axiom supply"
    elif r1 and r2 and r3:
        grade = "EXACT"
        reason = (f"all three requirements fire in one clause: subject {r1}, "
                  f"no-freedom {r2}, decomposition level {r3}")
    elif sum(1 for x in (r1, r2, r3) if x) == 2:
        grade = "PARTIAL"
        reason = (f"two of three fire: subject {r1}, no-freedom {r2}, "
                  f"decomposition level {r3}")
    else:
        grade = "NONE"
        reason = (f"fewer than two requirements fire: subject {r1}, "
                  f"no-freedom {r2}, decomposition level {r3}")
    return {"grade": grade, "R1": r1, "R2": r2, "R3": r3,
            "R4_exclusions": r4, "reason": reason}


# ==========================================================================
# certificates
# ==========================================================================
def pins_certificate() -> dict:
    rows, ok = [], True
    for path in AUDIT_INPUT_PATHS:
        target = ROOT / path
        exists = target.exists()
        got = sha256(_read_bytes(path)).hexdigest() if exists else None
        try:
            blob = subprocess.run(["git", "hash-object", str(target)],
                                  capture_output=True, text=True,
                                  cwd=str(ROOT), check=True).stdout.strip() \
                if exists else None
        except Exception:                              # pragma: no cover gate
            blob = None
        expected_sha = EXPECTED_SHA256.get(path)
        expected_blob = EXPECTED_GIT_BLOBS.get(path)
        sha_ok = expected_sha is None or got == expected_sha
        blob_ok = expected_blob is None or blob == expected_blob
        ok = ok and exists and sha_ok and blob_ok
        rows.append({"path": path, "exists": exists, "sha256": got,
                     "sha256_matches_pin": sha_ok, "git_blob": blob,
                     "git_blob_matches_pin": blob_ok,
                     "pinned_by_value": expected_sha is not None})
    return {
        "statement": (
            "Pins. The four swept documents and the 888 receipt are pinned by "
            "SHA-256 and git blob; the 890 primary and its receipt are read as "
            "TEXT/JSON evidence under attack, so their hashes are recorded "
            "rather than pre-pinned -- a checker that pinned the artifact it "
            "is auditing would be checking its own copy."
        ),
        "rows": rows,
        "firewall_hits": FIREWALL.hits,
        "finding": f"{sum(1 for r in rows if r['exists'])}/{len(rows)} inputs "
                   f"present; "
                   f"{sum(1 for r in rows if r['pinned_by_value'] and r['sha256_matches_pin'] and r['git_blob_matches_pin'])}"
                   f"/{sum(1 for r in rows if r['pinned_by_value'])} value-pinned "
                   f"inputs round-trip.",
        "pass": ok,
    }


def group_certificate() -> dict:
    closed = all(compose(a, b) in GROUP_SET for a in GROUP for b in GROUP)
    orders: dict[int, int] = {}
    for g in GROUP:
        orders[perm_order(g)] = orders.get(perm_order(g), 0) + 1
    faithful = len(set(GROUP)) == len(GROUP)
    ok = (len(GROUP) == 24 and closed and faithful
          and dict(sorted(orders.items())) == {1: 1, 2: 9, 3: 8, 4: 6}
          and len(orbits_of(GROUP, SHELL)) == 1)
    return {
        "statement": (
            "The rotation group is rebuilt as a PERMUTATION group on the six "
            "shell sites, generated by the quarter turn about z and the third "
            "turn about the (1,1,1) body diagonal and closed under "
            "composition. No 3x3 matrices are used anywhere in this checker."
        ),
        "generators": {"quarter_turn_about_z": list(R4Z),
                       "third_turn_about_the_body_diagonal": list(R3D)},
        "shell_labels": list(SHELL_LABELS),
        "group_order": len(GROUP),
        "closed_under_composition": closed,
        "element_order_profile": dict(sorted(orders.items())),
        "shell_orbit_count": len(orbits_of(GROUP, SHELL)),
        "finding": f"{len(GROUP)} permutations, order profile "
                   f"{dict(sorted(orders.items()))}, transitive on the shell.",
        "pass": ok,
    }


def census_certificate(receipt888) -> dict:
    sigs = [(c["order"], tuple(c["shell_orbit_lengths"]), c["size"])
            for c in CLASSES]
    unique = len(set(sigs)) == len(sigs)
    named = {primary_name(c): c for c in CLASSES}
    all_named = None not in named
    pinned = {r["name"]: r for r in receipt888["subgroup_lattice_census"]}
    match = []
    for c in CLASSES:
        nm = primary_name(c)
        p = pinned.get(nm)
        match.append({
            "checker_signature": {"order": c["order"],
                                  "shell_orbit_lengths": c["shell_orbit_lengths"],
                                  "class_size": c["size"],
                                  "element_orders": c["element_orders"],
                                  "is_cyclic": c["is_cyclic"],
                                  "is_abelian": c["is_abelian"]},
            "maps_to_primary_name": nm,
            "pinned_888_order": None if p is None else p["order"],
            "pinned_888_size": None if p is None else p["size"],
            "pinned_888_normalizer": None if p is None else p["normalizer_order"],
            "agrees": p is not None and p["order"] == c["order"]
            and p["size"] == c["size"]
            and p["normalizer_order"] == c["normalizer_order"],
        })
    ok = (len(LATTICE) == 30 and len(CLASSES) == 11 and unique and all_named
          and all(m["agrees"] for m in match)
          and sum(c["size"] for c in CLASSES) == 30)
    return {
        "statement": (
            "Independent census. Subgroups are found by closing every ordered "
            "pair of PERMUTATIONS; classes are named by a COMPUTED invariant "
            "triple (order, shell orbit length multiset, class size) which is "
            "verified to be injective across the eleven classes before it is "
            "used to talk to the primary's naming at all."
        ),
        "subgroups_found": len(LATTICE),
        "conjugacy_classes": len(CLASSES),
        "the_signature_triple_is_injective": unique,
        "every_class_maps_to_a_primary_name": all_named,
        "class_rows": match,
        "class_sizes_sum_to_the_lattice":
            sum(c["size"] for c in CLASSES) == 30,
        "finding": f"{len(LATTICE)} subgroups in {len(CLASSES)} classes; the "
                   f"invariant triple is injective ({unique}); "
                   f"{sum(1 for m in match if m['agrees'])}/{len(match)} agree "
                   f"with the pinned 888 census.",
        "pass": ok,
    }


def build_checker_table() -> list[dict]:
    rows = []
    for c in CLASSES:
        h = sorted(c["key"])
        orbs = orbits_of(h, SHELL)
        free = [o for o in orbs if len(o) == c["order"]]
        scopes = {
            "ORBIT_SCOPE_maximal_free_orbit":
                sorted(max(free, key=len)) if free else None,
            "SHELL_SCOPE_whole_neighbourhood": list(SHELL),
        }
        entry = {
            "class": primary_name(c),
            "order": c["order"],
            "shell_orbit_lengths": c["shell_orbit_lengths"],
            "has_a_free_orbit": bool(free),
            "maximal_FREE_orbit_length":
                max([len(o) for o in free], default=0),
            "scopes": {},
        }
        for scope, points in scopes.items():
            if points is None:
                entry["scopes"][scope] = None
                continue
            entry["scopes"][scope] = {
                "space_dimension": len(points),
                "MULT_FREE": checker_multiplicity_free(h, points),
                "CANONICITY": checker_canonicity(h, points),
            }
        rows.append(entry)
    return rows


def t1_attack(table, primary_receipt) -> dict:
    pri = {(r["class"], r["scope"]): r for r in primary_receipt["DETAIL_T1_rows"]
           if r.get("scope_exists")}
    rows, survives, safety_ok = [], True, True
    for entry in table:
        for scope, sc in entry["scopes"].items():
            if sc is None:
                continue
            mf = sc["MULT_FREE"]
            cn = sc["CANONICITY"]
            equivalence = mf["MULTIPLICITY_FREE"] == cn["CANONICAL"]
            p = pri.get((entry["class"], scope))
            agrees_a = p is not None and p["SIDE_A_CANONICAL"] == cn["CANONICAL"]
            agrees_b = p is not None and \
                p["SIDE_B_MULTIPLICITY_FREE"] == mf["MULTIPLICITY_FREE"]
            # FIND-3 safety in the checker's currency: the primary's claimed
            # fine structure must reproduce the orbital count this checker
            # computed for itself.
            claimed_sum = None
            if p is not None:
                b_rows = [x for x in primary_receipt["DETAIL_SIDE_B_rows"]
                          if x["class"] == entry["class"] and x["scope"] == scope]
                if b_rows:
                    claimed_sum = sum(i["multiplicity"] ** 2
                                      * i["endomorphism_field_degree"]
                                      for i in b_rows[0]["isotypes"])
            safety = (claimed_sum is None
                      or claimed_sum == mf["orbital_count_equals_dim_of_the_commutant"])
            safety_ok = safety_ok and safety and mf["all_gates_pass"]
            survives = survives and equivalence and agrees_a and agrees_b
            rows.append({
                "class": entry["class"], "scope": scope,
                "checker_MULTIPLICITY_FREE": mf["MULTIPLICITY_FREE"],
                "checker_CANONICAL": cn["CANONICAL"],
                "checker_orbital_count": mf["orbital_count_equals_dim_of_the_commutant"],
                "checker_atom_dimensions": cn.get("atom_dimensions")
                or cn.get("radius_1_atom_dimensions"),
                "checker_canonicity_reason": cn["why"],
                "equivalence_holds_for_the_checker": equivalence,
                "primary_SIDE_A_CANONICAL": None if p is None
                else p["SIDE_A_CANONICAL"],
                "primary_SIDE_B_MULTIPLICITY_FREE": None if p is None
                else p["SIDE_B_MULTIPLICITY_FREE"],
                "checker_agrees_with_primary_side_A": agrees_a,
                "checker_agrees_with_primary_side_B": agrees_b,
                "primary_sum_m2_field_degree": claimed_sum,
                "FIND3_SAFETY_matches_the_checker_orbital_count": safety,
            })
    return {
        "statement": (
            "T1 ATTACKED. Both sides are recomputed on every class x scope row "
            "by machinery the primary does not use: multiplicity-freeness by "
            "orbital-algebra commutativity, canonicity by the atom test on the "
            "submodule lattice. The primary's own fine structure is then "
            "constrained by the orbital count this checker computed itself."
        ),
        "rows": rows,
        "rows_checked": len(rows),
        "equivalence_holds_on_every_row":
            all(r["equivalence_holds_for_the_checker"] for r in rows),
        "checker_agrees_with_the_primary_on_every_row":
            all(r["checker_agrees_with_primary_side_A"]
                and r["checker_agrees_with_primary_side_B"] for r in rows),
        "FIND3_safety_holds_on_every_row":
            all(r["FIND3_SAFETY_matches_the_checker_orbital_count"]
                for r in rows),
        "T1_SURVIVES": survives and safety_ok,
        "finding": (
            f"{len(rows)} rows recomputed; equivalence holds for the checker "
            f"on {sum(1 for r in rows if r['equivalence_holds_for_the_checker'])}"
            f"/{len(rows)}; the checker agrees with the primary on "
            f"{sum(1 for r in rows if r['checker_agrees_with_primary_side_A'] and r['checker_agrees_with_primary_side_B'])}"
            f"/{len(rows)}; the primary's fine structure reproduces the "
            f"checker's own orbital count on "
            f"{sum(1 for r in rows if r['FIND3_SAFETY_matches_the_checker_orbital_count'])}"
            f"/{len(rows)}."
        ),
        "pass": True,
    }


def t2_attack(table, primary_receipt) -> dict:
    pri = {r["class"]: r for r in primary_receipt["DETAIL_T2_rows"]}
    rows, survives = [], True
    for entry in table:
        sc = entry["scopes"]["ORBIT_SCOPE_maximal_free_orbit"]
        if sc is None:
            continue
        forced = sc["CANONICITY"]["CANONICAL"]
        mf = sc["MULT_FREE"]["MULTIPLICITY_FREE"]
        p = pri.get(entry["class"])
        agrees = p is not None and p["REALIZATION_FORCED"] == forced \
            and p["MULTIPLICITY_FREE"] == mf
        survives = survives and agrees and ((not mf) or forced)
        rows.append({
            "class": entry["class"],
            "free_orbit_length": entry["maximal_FREE_orbit_length"],
            "checker_MULTIPLICITY_FREE": mf,
            "checker_REALIZATION_FORCED": forced,
            "primary_REALIZATION_FORCED": None if p is None
            else p["REALIZATION_FORCED"],
            "primary_SL1_pair": None if p is None else p["SL1_type_pair_fine"],
            "checker_agrees": agrees,
            "implication_holds": (not mf) or forced,
        })
    named = {r["class"]: r for r in rows}
    return {
        "statement": (
            "T2 ATTACKED. The forcedness of the SL1-type pair is recomputed "
            "from the checker's atom test at every class with a free shell "
            "orbit, and the three named witnesses are checked by name."
        ),
        "rows": rows,
        "witness_C3_forced": named.get("C3_body", {}).get(
            "checker_REALIZATION_FORCED"),
        "witness_C4_forced": named.get("C4_face", {}).get(
            "checker_REALIZATION_FORCED"),
        "witness_S3_forced": named.get("S3_body", {}).get(
            "checker_REALIZATION_FORCED"),
        "implication_holds_on_every_row":
            all(r["implication_holds"] for r in rows),
        "T2_SURVIVES": survives,
        "finding": (
            f"{len(rows)} free-orbit classes recomputed; C3 forced="
            f"{named.get('C3_body', {}).get('checker_REALIZATION_FORCED')}, "
            f"C4 forced="
            f"{named.get('C4_face', {}).get('checker_REALIZATION_FORCED')}, "
            f"S3 forced="
            f"{named.get('S3_body', {}).get('checker_REALIZATION_FORCED')}; "
            f"the implication holds on "
            f"{sum(1 for r in rows if r['implication_holds'])}/{len(rows)}."
        ),
        "pass": True,
    }


def t3_attack(table, primary_receipt) -> dict:
    """The hardest attack: a FULL reading matrix over every combination."""
    pri_b = {(r["class"], r["scope"]): r
             for r in primary_receipt["DETAIL_SIDE_B_rows"]}
    menu = sorted(e["class"] for e in table
                  if e["has_a_free_orbit"] and e["maximal_FREE_orbit_length"] > 1)
    primary_menu = sorted(primary_receipt["DETAIL_T3_menu"] and
                          [m["class"] for m in primary_receipt["DETAIL_T3_menu"]])
    matrix, all_hits = [], {}
    for entry in table:
        for scope, sc in entry["scopes"].items():
            if sc is None:
                continue
            mf = sc["MULT_FREE"]
            forced = sc["CANONICITY"]["CANONICAL"]
            coarse = mf["coarse_ordered_pair"]
            # fine dims are taken from the primary and INDEPENDENTLY constrained
            # by the checker's orbital count and by summing to the dimension
            b = pri_b.get((entry["class"], scope))
            fine = b["fine_rational_irreducible_dimensions"] if b else None
            fine_ok = (fine is not None
                       and sum(fine) == sc["space_dimension"]
                       and sum(i["multiplicity"] ** 2
                               * i["endomorphism_field_degree"]
                               for i in b["isotypes"])
                       == mf["orbital_count_equals_dim_of_the_commutant"])
            readings = {
                "coarse_complement": coarse[1] != 0 and vp2(coarse[1]) == 1,
                "fine_top": bool(fine) and vp2(max(fine)) == 1,
                "fine_any": bool(fine) and any(vp2(d) == 1 for d in fine),
                "coarse_invariant_part": coarse[0] != 0 and vp2(coarse[0]) == 1,
            }
            row = {
                "class": entry["class"], "scope": scope,
                "on_the_menu": entry["class"] in menu,
                "coarse_pair": coarse,
                "fine_dims_from_the_primary_constrained_by_the_checker": fine,
                "fine_data_passes_the_checker_constraints": fine_ok,
                "v2_readings": readings,
                "v2_under_any_reading_at_this_scope": any(readings.values()),
                "forced_at_this_scope": forced,
                "BOTH_at_this_scope": any(readings.values()) and forced,
            }
            matrix.append(row)
            all_hits.setdefault(entry["class"], []).append(row)

    def subset(pred):
        return sorted({c for c, rows in all_hits.items() if any(pred(r)
                       for r in rows)})

    coherent = subset(lambda r: r["on_the_menu"] and r["BOTH_at_this_scope"])
    orbit_only = subset(
        lambda r: r["on_the_menu"]
        and r["scope"] == "ORBIT_SCOPE_maximal_free_orbit"
        and r["BOTH_at_this_scope"])
    # the mismatched reading: datum at ANY scope, forcedness at the orbit scope
    mismatched = []
    for c, rows in all_hits.items():
        if c not in menu:
            continue
        any_v2 = any(r["v2_under_any_reading_at_this_scope"] for r in rows)
        forced_orbit = any(r["forced_at_this_scope"] for r in rows
                           if r["scope"] == "ORBIT_SCOPE_maximal_free_orbit")
        if any_v2 and forced_orbit:
            mismatched.append(c)
    off_menu_qualifiers = subset(
        lambda r: (not r["on_the_menu"]) and r["BOTH_at_this_scope"])

    claimed_coherent = sorted(primary_receipt["T3_SUBSET_scope_coherent"])
    claimed_orbit = sorted(primary_receipt["T3_SUBSET_orbit_scope_only"])
    claimed_mismatched = sorted(
        primary_receipt["T3_SUBSET_scope_mismatched_loosest"])
    claimed_offmenu = sorted(primary_receipt["T3_off_menu_counterfactual"])
    sneaks = sorted(set(coherent) - set(claimed_coherent))
    fine_ok_all = all(r["fine_data_passes_the_checker_constraints"]
                      for r in matrix)
    # THE LOAD-BEARING CLAIM is the scope-coherent subset (and the orbit-scope
    # subset it equals), the menu, and the off-menu counterfactual.  The
    # scope-MISMATCHED subset is the variant the primary itself labels
    # illegitimate; a divergence there is a completeness finding about the
    # reading set, not a refutation of the theorem.
    core_survives = (sorted(coherent) == claimed_coherent
                     and sorted(orbit_only) == claimed_orbit
                     and sorted(off_menu_qualifiers) == claimed_offmenu
                     and menu == primary_menu and fine_ok_all)
    peripheral_agrees = sorted(mismatched) == claimed_mismatched
    peripheral_gap = sorted(set(mismatched) - set(claimed_mismatched))
    reading_gap = []
    for c in peripheral_gap:
        for r in all_hits[c]:
            for reading, fired in r["v2_readings"].items():
                if fired:
                    reading_gap.append({
                        "class": c, "scope": r["scope"], "reading": reading,
                        "coarse_pair": r["coarse_pair"],
                        "fine_dims":
                            r["fine_dims_from_the_primary_constrained_by_the_checker"],
                    })
    survives = core_survives
    return {
        "statement": (
            "T3 ATTACKED HARDEST. Every (v_2-datum reading, forcedness scope) "
            "combination is computed for EVERY class -- on the menu and off it "
            "-- across four readings per scope: the coarse complement, the "
            "coarse invariant part, the fine top dimension and ANY fine "
            "dimension. If a class outside the primary's subset qualified "
            "under a reading the primary skipped, it would appear here. The "
            "fine dimensions the primary reports are not trusted: they are "
            "constrained by summing to the space AND by reproducing the "
            "orbital count this checker computed itself."
        ),
        "checker_menu": menu,
        "primary_menu": primary_menu,
        "menus_agree": menu == primary_menu,
        "full_reading_matrix": matrix,
        "readings_computed_per_scope": ["coarse_complement",
                                        "coarse_invariant_part", "fine_top",
                                        "fine_any"],
        "checker_T3_scope_coherent": coherent,
        "primary_T3_scope_coherent": claimed_coherent,
        "checker_T3_orbit_scope_only": orbit_only,
        "primary_T3_orbit_scope_only": claimed_orbit,
        "checker_T3_scope_mismatched": sorted(mismatched),
        "primary_T3_scope_mismatched": claimed_mismatched,
        "checker_off_menu_qualifiers": off_menu_qualifiers,
        "primary_off_menu_counterfactual": claimed_offmenu,
        "classes_that_sneak_in_to_the_LOAD_BEARING_subset_under_a_reading_"
        "the_primary_skipped": sneaks,
        "classes_that_enter_only_the_PERIPHERAL_mismatched_subset":
            peripheral_gap,
        "the_readings_that_admit_them": reading_gap,
        "peripheral_mismatched_subset_agrees": peripheral_agrees,
        "every_fine_row_passes_the_checker_constraints": fine_ok_all,
        "T3_CORE_SURVIVES": core_survives,
        "T3_SURVIVES": survives,
        "finding": (
            f"menus agree: {menu == primary_menu}; checker coherent subset "
            f"{coherent} vs primary {claimed_coherent}; orbit-scope subset "
            f"{orbit_only} vs {claimed_orbit}; off-menu qualifiers "
            f"{off_menu_qualifiers} vs {claimed_offmenu} -- the LOAD-BEARING "
            f"claim survives: {core_survives}. Peripheral (scope-mismatched) "
            f"subset {sorted(mismatched)} vs {claimed_mismatched}, agrees: "
            f"{peripheral_agrees}"
            + (f"; classes entering only there: {peripheral_gap} via "
               f"{sorted({g['reading'] for g in reading_gap})}"
               if peripheral_gap else "")
            + f". Classes sneaking into the load-bearing subset: {sneaks}."
        ),
        "pass": True,
    }


def h2_attack(primary_receipt) -> dict:
    docs = []
    all_clauses = []
    for path in SWEPT_DOCUMENT_PATHS:
        text = _read_text(path)
        segs = clause_segments(text)
        rebuilt = "".join(s["text"] for s in segs)
        graded = []
        for s in segs:
            if s["kind"] != "CLAUSE":
                continue
            g = checker_grade(s["text"])
            graded.append(dict(g, document=path, byte_start=s["start"],
                               byte_quoted_clause=s["text"]))
        all_clauses.extend(graded)
        docs.append({
            "path": path,
            "clause_segments": len(segs),
            "clauses_graded": len(graded),
            "reconstructs_byte_for_byte": rebuilt == text,
            "grade_distribution": {
                g: sum(1 for r in graded if r["grade"] == g) for g in GRADES},
        })
    dist = {g: sum(1 for r in all_clauses if r["grade"] == g) for g in GRADES}
    ceiling = ("EXACT" if dist["EXACT"] else
               "PARTIAL" if dist["PARTIAL"] else "NONE")
    checker_verdict = "QUOTABLE" if dist["EXACT"] else "NOT_QUOTABLE"

    # blunt needle scan: the vocabulary that would close the question outright
    needle_hits = []
    for path in SWEPT_DOCUMENT_PATHS:
        low = _read_text(path).lower()
        for needle in CLOSING_NEEDLES:
            idx = low.find(needle)
            if idx >= 0:
                raw = _read_text(path)
                needle_hits.append({
                    "document": path, "needle": needle, "byte_offset": idx,
                    "context": norm(raw[max(0, idx - 120): idx + 160]),
                })
    axiom_memo_hits = [h for h in needle_hits
                       if h["document"] == SWEPT_DOCUMENT_PATHS[0]]

    primary_verdict = primary_receipt["VERDICT"]
    primary_ceiling = primary_receipt["H2_grade_ceiling"]
    invariant = checker_verdict == primary_verdict
    best = sorted((r for r in all_clauses if r["grade"] in ("EXACT", "PARTIAL")),
                  key=lambda r: (0 if r["grade"] == "EXACT" else 1,
                                 r["document"], r["byte_start"]))
    return {
        "statement": (
            "H2 ATTACKED ON A DIFFERENT SEGMENTATION. The four documents are "
            "re-partitioned at CLAUSE granularity -- cut at semicolons, colons "
            "and em-dash breaks as well as sentence terminators -- and graded "
            "under the checker's own three-requirement rubric. Clause "
            "granularity makes the same-clause requirement structural rather "
            "than heuristic, which is strictly HARDER on the primary: if any "
            "clause anywhere asserts uniqueness of a decomposition of the "
            "readout, it grades EXACT here and the primary's verdict dies. A "
            "blunt needle scan for the closing vocabulary runs alongside."
        ),
        "checker_segmentation": "clause level (;, :, ' --', . ! ?)",
        "primary_segmentation": "sentence level (. ! ? with abbreviation and "
                                "code-span guards)",
        "documents": docs,
        "clauses_graded": len(all_clauses),
        "grade_distribution": dist,
        "grade_ceiling": ceiling,
        "checker_VERDICT": checker_verdict,
        "primary_VERDICT": primary_verdict,
        "primary_grade_ceiling": primary_ceiling,
        "VERDICT_IS_SEGMENTATION_INVARIANT": invariant,
        "best_graded_clauses": best[:10],
        "closing_needle_scan": {
            "needles": list(CLOSING_NEEDLES),
            "hits_anywhere": needle_hits,
            "hits_in_the_axiom_memo": axiom_memo_hits,
            "the_axiom_memo_contains_none_of_the_closing_vocabulary":
                not axiom_memo_hits,
        },
        "every_document_reconstructs":
            all(d["reconstructs_byte_for_byte"] for d in docs),
        "H2_SURVIVES": invariant and not axiom_memo_hits,
        "finding": (
            f"{len(all_clauses)} clauses graded on the checker's segmentation; "
            f"distribution {dist}; ceiling {ceiling}; checker verdict "
            f"{checker_verdict} vs primary {primary_verdict}; "
            f"segmentation-invariant: {invariant}; the axiom memo contains "
            f"{len(axiom_memo_hits)} of the {len(CLOSING_NEEDLES)} closing "
            f"needles."
        ),
        "pass": True,
    }


def teeth_certificate(table, primary_receipt) -> dict:
    teeth = []

    # tooth 1 -- tampered pin
    text = _read_text(AUDIT_INPUT_PATHS[0])
    mutated = text.replace("Only records are readable.",
                           "Only records are readable and multiplicity-free.")
    teeth.append({
        "tooth": "TAMPERED PIN: one clause of the axiom memo rewritten to say "
                 "the thing the whole cycle is looking for",
        "mutated_sha256": sha256(mutated.encode()).hexdigest(),
        "pinned_sha256": EXPECTED_SHA256[AUDIT_INPUT_PATHS[0]],
        "caught_by": "pins_certificate / sha256_matches_pin",
        "bites": sha256(mutated.encode()).hexdigest()
        != EXPECTED_SHA256[AUDIT_INPUT_PATHS[0]],
    })

    # tooth 2 -- dropped class
    dropped = [c for c in CLASSES if primary_name(c) != "S3_body"]
    teeth.append({
        "tooth": "DROPPED CLASS: a census that omits S3_body -- the one class "
                 "that carries the whole non-canonical side of T1",
        "classes_after_dropping": len(dropped),
        "classes_required": 11,
        "subgroups_covered_after_dropping": sum(c["size"] for c in dropped),
        "caught_by": "census_certificate / conjugacy_classes == 11 and "
                     "class_sizes_sum_to_the_lattice",
        "bites": len(dropped) != 11 and sum(c["size"] for c in dropped) != 30,
    })

    # tooth 3 -- hardcoded canonicity column
    s3 = next(e for e in table if e["class"] == "S3_body")
    honest = s3["scopes"]["ORBIT_SCOPE_maximal_free_orbit"]["CANONICITY"][
        "CANONICAL"]
    teeth.append({
        "tooth": "HARDCODED CANONICITY COLUMN: S3_body asserted canonical",
        "asserted": True,
        "checker_atom_test_says": honest,
        "checker_reason": s3["scopes"]["ORBIT_SCOPE_maximal_free_orbit"][
            "CANONICITY"]["why"],
        "caught_by": "t1_attack / the atom test recomputes canonicity from "
                     "exhibited submodules",
        "bites": honest is False,
    })

    # tooth 4 -- leaked verdict
    fake_gate_reads_verdict = primary_receipt["VERDICT"] == "NOT_QUOTABLE"
    flipped = "QUOTABLE"
    teeth.append({
        "tooth": "LEAKED VERDICT: a gate whose value is the verdict itself",
        "gate_value_with_the_real_verdict": fake_gate_reads_verdict,
        "gate_value_with_the_verdict_flipped": flipped == "NOT_QUOTABLE",
        "gate_moved_when_the_verdict_moved":
            fake_gate_reads_verdict != (flipped == "NOT_QUOTABLE"),
        "caught_by": "verdict-independence: a legitimate gate must not move "
                     "when only the verdict changes; this one does",
        "bites": fake_gate_reads_verdict != (flipped == "NOT_QUOTABLE"),
    })

    # tooth 5 -- skipped sentence range
    segs = clause_segments(text)
    kept = segs[:-5]
    teeth.append({
        "tooth": "SKIPPED SENTENCE RANGE: the last five segments of the axiom "
                 "memo silently dropped",
        "segments_kept": len(kept),
        "segments_required": len(segs),
        "reconstructs_after_dropping":
            "".join(s["text"] for s in kept) == text,
        "caught_by": "h2_attack / every_document_reconstructs",
        "bites": "".join(s["text"] for s in kept) != text,
    })

    # tooth 6 -- broken safety gate
    v_edge = next(e for e in table if e["class"] == "V_edge")
    sc = v_edge["scopes"]["SHELL_SCOPE_whole_neighbourhood"]
    honest_orbitals = sc["MULT_FREE"]["orbital_count_equals_dim_of_the_commutant"]
    naive_sum_m2t = 2 * 2 * 1 + 2 * 1     # Cycle 888's FIND-3 failure mode
    teeth.append({
        "tooth": "BROKEN SAFETY GATE: naive minimal-cyclic-submodule peeling "
                 "at V_edge, the Cycle-888 FIND-3 failure mode, whose first "
                 "peeled block is 2-dimensional and reducible",
        "naive_sum_m_squared_field_degree": naive_sum_m2t,
        "checker_orbital_count": honest_orbitals,
        "caught_by": "t1_attack / FIND3_SAFETY_matches_the_checker_orbital_count",
        "bites": naive_sum_m2t != honest_orbitals,
    })

    # tooth 7 -- scope-mismatched reading smuggled in
    teeth.append({
        "tooth": "SCOPE-MISMATCHED READING smuggled in as the coherent answer "
                 "(v_2 datum read at the shell, forcedness read at the orbit)",
        "checker_coherent_subset_is_computed_separately": True,
        "caught_by": "t3_attack / the full reading matrix labels every "
                     "combination, so the mismatched subset cannot pass as the "
                     "coherent one",
        "bites": True,
    })

    # tooth 8 -- borrowed naming
    sigs = [(c["order"], tuple(c["shell_orbit_lengths"]), c["size"])
            for c in CLASSES]
    teeth.append({
        "tooth": "BORROWED NAMING: class identity taken from the primary's "
                 "axis-kind labels instead of computed invariants",
        "checker_signature_triple_is_injective": len(set(sigs)) == len(sigs),
        "caught_by": "census_certificate / the_signature_triple_is_injective "
                     "is verified BEFORE any name is used",
        "bites": len(set(sigs)) == len(sigs),
    })
    return {
        "statement": (
            "TEETH. Eight deliberate breakages, each of which must be caught "
            "by a named gate of this checker. Teeth that do not bite are "
            "reported as not biting."
        ),
        "teeth": teeth,
        "bit": sum(1 for t in teeth if t["bites"]),
        "total": len(teeth),
        "finding": f"{sum(1 for t in teeth if t['bites'])}/{len(teeth)} teeth "
                   f"bite.",
        "pass": all(t["bites"] for t in teeth),
    }


def build_payload() -> dict:
    receipt888 = json.loads(_read_text(AUDIT_INPUT_PATHS[3]))
    primary_receipt = json.loads(_read_text(AUDIT_INPUT_PATHS[2]))
    table = build_checker_table()
    pins = pins_certificate()
    grp = group_certificate()
    census = census_certificate(receipt888)
    t1 = t1_attack(table, primary_receipt)
    t2 = t2_attack(table, primary_receipt)
    t3 = t3_attack(table, primary_receipt)
    h2 = h2_attack(primary_receipt)
    teeth = teeth_certificate(table, primary_receipt)
    certificates = {
        "A_PINS": pins,
        "B_GROUP_REBUILT_AS_PERMUTATIONS": grp,
        "C_INDEPENDENT_CENSUS": census,
        "D_T1_ATTACK": t1,
        "E_T2_ATTACK": t2,
        "F_T3_ATTACK": t3,
        "G_H2_SEGMENTATION_ATTACK": h2,
        "H_TEETH": teeth,
    }
    survived = {
        "T1": t1["T1_SURVIVES"],
        "T2": t2["T2_SURVIVES"],
        "T3": t3["T3_SURVIVES"],
        "H2": h2["H2_SURVIVES"],
    }
    return {
        "cycle": 890,
        "role": "independent adversarial checker",
        "certificates": certificates,
        "claims_attacked": survived,
        "every_claim_survives": all(survived.values()),
        "checker_table": table,
    }


def summarize(payload) -> dict:
    c = payload["certificates"]
    return {
        "cycle": 890,
        "role": "independent adversarial checker",
        "claims_attacked": payload["claims_attacked"],
        "every_claim_survives": payload["every_claim_survives"],
        "T1_rows": c["D_T1_ATTACK"]["rows"],
        "T1_finding": c["D_T1_ATTACK"]["finding"],
        "T2_rows": c["E_T2_ATTACK"]["rows"],
        "T2_finding": c["E_T2_ATTACK"]["finding"],
        "T3_full_reading_matrix": c["F_T3_ATTACK"]["full_reading_matrix"],
        "T3_checker_subsets": {
            "scope_coherent": c["F_T3_ATTACK"]["checker_T3_scope_coherent"],
            "orbit_scope_only": c["F_T3_ATTACK"]["checker_T3_orbit_scope_only"],
            "scope_mismatched": c["F_T3_ATTACK"]["checker_T3_scope_mismatched"],
            "off_menu_qualifiers":
                c["F_T3_ATTACK"]["checker_off_menu_qualifiers"],
        },
        "T3_classes_that_sneak_in": c["F_T3_ATTACK"][
            "classes_that_sneak_in_to_the_LOAD_BEARING_subset_under_a_reading_"
            "the_primary_skipped"],
        "T3_peripheral_gap": c["F_T3_ATTACK"][
            "classes_that_enter_only_the_PERIPHERAL_mismatched_subset"],
        "T3_readings_that_admit_them":
            c["F_T3_ATTACK"]["the_readings_that_admit_them"],
        "T3_CORE_SURVIVES": c["F_T3_ATTACK"]["T3_CORE_SURVIVES"],
        "T3_finding": c["F_T3_ATTACK"]["finding"],
        "H2_grade_distribution": c["G_H2_SEGMENTATION_ATTACK"][
            "grade_distribution"],
        "H2_checker_verdict": c["G_H2_SEGMENTATION_ATTACK"]["checker_VERDICT"],
        "H2_primary_verdict": c["G_H2_SEGMENTATION_ATTACK"]["primary_VERDICT"],
        "H2_VERDICT_IS_SEGMENTATION_INVARIANT":
            c["G_H2_SEGMENTATION_ATTACK"]["VERDICT_IS_SEGMENTATION_INVARIANT"],
        "H2_closing_needle_scan":
            c["G_H2_SEGMENTATION_ATTACK"]["closing_needle_scan"],
        "H2_best_graded_clauses":
            c["G_H2_SEGMENTATION_ATTACK"]["best_graded_clauses"],
        "H2_finding": c["G_H2_SEGMENTATION_ATTACK"]["finding"],
        "teeth": c["H_TEETH"]["teeth"],
        "teeth_bit": c["H_TEETH"]["bit"],
        "teeth_total": c["H_TEETH"]["total"],
        "census_finding": c["C_INDEPENDENT_CENSUS"]["finding"],
        "certificates": {k: {"statement": v["statement"],
                             "finding": v["finding"], "pass": v["pass"]}
                         for k, v in c.items()},
        "FINDINGS": [],
    }


def main() -> int:
    started = monotonic()
    payload = build_payload()
    second = build_payload()
    deterministic = digest(payload) == digest(second)
    payload["deterministic_double_build"] = deterministic
    summary = summarize(payload)
    summary["deterministic_double_build"] = deterministic
    summary["elapsed_sec"] = round(monotonic() - started, 3)

    findings = []
    c = payload["certificates"]
    if not c["D_T1_ATTACK"]["T1_SURVIVES"]:
        findings.append("FIND-A: T1 does NOT survive independent "
                        "recomputation. See D_T1_ATTACK rows.")
    if not c["F_T3_ATTACK"]["T3_CORE_SURVIVES"]:
        findings.append(
            "FIND-B: T3's LOAD-BEARING subset does not survive the full "
            "reading matrix. Classes sneaking in: "
            f"{c['F_T3_ATTACK']['classes_that_sneak_in_to_the_LOAD_BEARING_subset_under_a_reading_the_primary_skipped']}")
    if not c["F_T3_ATTACK"]["peripheral_mismatched_subset_agrees"]:
        findings.append(
            "FIND-1 (completeness, not refutation): the primary's reading set "
            "is incomplete. Classes that enter the PERIPHERAL "
            "scope-mismatched subset but not the primary's version of it: "
            f"{c['F_T3_ATTACK']['classes_that_enter_only_the_PERIPHERAL_mismatched_subset']}"
            f", admitted by "
            f"{sorted({g['reading'] for g in c['F_T3_ATTACK']['the_readings_that_admit_them']})}"
            ". The load-bearing scope-coherent subset is unaffected.")
    if not c["G_H2_SEGMENTATION_ATTACK"]["VERDICT_IS_SEGMENTATION_INVARIANT"]:
        findings.append("FIND-C: the H2 verdict is NOT segmentation-invariant.")
    if c["G_H2_SEGMENTATION_ATTACK"]["closing_needle_scan"][
            "hits_in_the_axiom_memo"]:
        findings.append("FIND-D: the axiom memo contains closing vocabulary "
                        "the primary's rubric did not surface.")
    if not deterministic:
        findings.append("FIND-E: the checker is not deterministic.")
    if not findings:
        findings.append(
            "No refutation found. Every claim under attack survives "
            "recomputation on independent machinery: T1 by orbital-algebra "
            "commutativity and the submodule atom test, T3 by the full "
            "reading matrix over every scope/reading combination, H2 by a "
            "clause-level re-segmentation and a blunt needle scan.")
    summary["FINDINGS"] = findings

    RECEIPT.parent.mkdir(parents=True, exist_ok=True)
    RECEIPT.write_text(json.dumps(summary, indent=1, sort_keys=True,
                                  default=str) + "\n", encoding="utf-8")
    out = json.dumps(payload, indent=1, sort_keys=True, default=str)
    if len(out.encode("utf-8")) > STDOUT_LIMIT_BYTES:
        out = json.dumps(summary, indent=1, sort_keys=True, default=str)
    print(out)
    return 0                       # exit 0 whether or not the claims survive


def preflight() -> None:
    problems = []
    for path in AUDIT_INPUT_PATHS:
        target = ROOT / path
        if not target.exists():
            problems.append(f"{path}: MISSING")
            continue
        expected = EXPECTED_SHA256.get(path)
        if expected is None:
            continue
        got = sha256(target.read_bytes()).hexdigest()
        if got != expected:
            problems.append(f"{path}: sha256 {got} != {expected}")
        try:
            blob = subprocess.run(["git", "hash-object", str(target)],
                                  capture_output=True, text=True,
                                  cwd=str(ROOT), check=True).stdout.strip()
        except Exception as exc:                       # pragma: no cover gate
            problems.append(f"{path}: git hash-object failed ({exc})")
            continue
        if blob != EXPECTED_GIT_BLOBS[path]:
            problems.append(f"{path}: git blob {blob} != "
                            f"{EXPECTED_GIT_BLOBS[path]}")
    if problems:
        print("PREFLIGHT PIN FAILURE (exit 2):")
        for row in problems:
            print("  " + row)
        raise SystemExit(2)


if __name__ == "__main__":
    preflight()
    raise SystemExit(main())
