#!/usr/bin/env python3
"""
Bottom-up audit of the Q1 sign/orientation question.

This runner redoes the sign problem from first principles:

  * the C3 group algebra on the generation triplet;
  * the transposition that sends g <-> g^2;
  * the Q1 source S_Q1 = 10/9 e - 2/9 g - 2/9 g^2;
  * the signed selected-line phase direction, which is odd under transposition;
  * the APS value 2/9 as a magnitude unless an orientation is supplied.

It deliberately avoids using the previous Q1 signed-readout no-go as an input.
No PDG values, fitted masses, or observed phases are used.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
PASSES: list[tuple[str, bool, str]] = []


def record(name: str, ok: bool, detail: str = "") -> None:
    PASSES.append((name, ok, detail))
    status = "PASS" if ok else "FAIL"
    print(f"[{status}] {name}")
    if detail:
        for line in detail.splitlines():
            print(f"       {line}")


def section(title: str) -> None:
    print()
    print("=" * 88)
    print(title)
    print("=" * 88)


def read_rel(rel_path: str) -> str:
    return (ROOT / rel_path).read_text(encoding="utf-8")


def sorted_cos_spectrum(delta: float) -> list[float]:
    return sorted(math.cos(delta + 2.0 * math.pi * k / 3.0) for k in range(3))


def main() -> int:
    section("A. First-principles C3 algebra")

    e = sp.eye(3)
    g = sp.Matrix([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
    g2 = g**2
    tau = sp.Matrix([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
    s_q1 = sp.Rational(10, 9) * e - sp.Rational(2, 9) * g - sp.Rational(2, 9) * g2
    even_u = g + g2
    odd_j = sp.I * (g - g2)

    record(
        "A.1 C3 generator has order three",
        g**3 == e and g != e,
    )
    record(
        "A.2 transposition reverses the cyclic generator",
        tau * g * tau == g2 and tau * g2 * tau == g,
        "tau g tau = g^2, tau g^2 tau = g.",
    )
    record(
        "A.3 Q1 source is exactly even in the nonidentity directions",
        s_q1 == sp.Rational(10, 9) * e - sp.Rational(2, 9) * even_u,
        "S_Q1 = 10/9 e - 2/9(g+g^2).",
    )
    record(
        "A.4 Q1 source is fixed by transposition",
        tau * s_q1 * tau == s_q1,
    )
    record(
        "A.5 the signed phase generator is transposition-odd",
        tau * odd_j * tau == -odd_j,
        "J = i(g-g^2) changes sign.",
    )
    odd_projection = sp.simplify(sp.trace(s_q1 * odd_j) / sp.trace(odd_j * odd_j))
    record(
        "A.6 Q1 has zero component on the signed odd line",
        odd_projection == 0,
        f"projection<S_Q1,J>={odd_projection}",
    )

    section("B. Algebra generated by Q1 cannot create a sign")

    u2_reduction = sp.simplify(even_u**2 - (2 * e + even_u))
    record(
        "B.1 the even subalgebra generated by g+g^2 closes on {e,g+g^2}",
        u2_reduction == sp.zeros(3),
        "(g+g^2)^2 = 2e + (g+g^2).",
    )
    alpha, beta = sp.symbols("alpha beta")
    generic_poly = alpha * e + beta * even_u
    generic_odd_projection = sp.simplify(sp.trace(generic_poly * odd_j) / sp.trace(odd_j * odd_j))
    record(
        "B.2 every polynomial/readout from Q1-only algebra has zero odd projection",
        generic_odd_projection == 0,
        "Any f(S_Q1) lives in span{e,g+g^2}, so it cannot reach i(g-g^2).",
    )

    x, y, a, b = sp.symbols("x y a b")
    linear = a * x + b * y
    equivariance_eq = sp.Poly(sp.expand((a * y + b * x) + linear), x, y).coeffs()
    sol = sp.solve([sp.Eq(coeff, 0) for coeff in equivariance_eq], (a, b), dict=True)
    record(
        "B.3 bottom-up linear odd readouts are proportional to coeff_g-coeff_g2",
        sol == [{a: -b}] or sol == [{b: -a}],
        f"solution={sol}",
    )
    record(
        "B.4 Q1 coefficient difference vanishes",
        sp.Rational(-2, 9) - sp.Rational(-2, 9) == 0,
        "coeff_g - coeff_g2 = 0.",
    )

    section("C. APS sign versus APS magnitude")

    eta_abs = sp.Rational(2, 9)
    epsilon = sp.symbols("epsilon")
    eta_signed = epsilon * eta_abs
    record(
        "C.1 APS fixed-point arithmetic gives the magnitude 2/9",
        eta_abs == sp.Rational(2, 9),
    )
    record(
        "C.2 a signed APS comparison needs an odd orientation variable",
        eta_signed.subs(epsilon, 1) == eta_abs
        and eta_signed.subs(epsilon, -1) == -eta_abs,
        "eta_signed = epsilon * 2/9.",
    )
    record(
        "C.3 Q1 supplies the magnitude but not epsilon",
        -sp.Rational(1, 2) * (sp.Rational(-2, 9) + sp.Rational(-2, 9)) == eta_abs,
        "The even average recovers 2/9; the odd orientation is absent.",
    )

    section("D. Selected-line mirror check")

    delta = 2.0 / 9.0
    plus_spec = sorted_cos_spectrum(delta)
    minus_spec = sorted_cos_spectrum(-delta)
    record(
        "D.1 selected-line spectra at +delta and -delta are mirror-degenerate",
        all(abs(a0 - b0) < 1e-12 for a0, b0 in zip(plus_spec, minus_spec)),
        "The unordered mass/Koide spectrum cannot choose the sign.",
    )
    record(
        "D.2 the sign is visible only after choosing an oriented Fourier/slot frame",
        all(abs(a0 - b0) < 1e-12 for a0, b0 in zip(plus_spec, minus_spec)) and delta != 0,
        "A based endpoint or selected-line orientation tells +delta from -delta.",
    )

    section("E. Candidate orientation sources in the repo")

    parity_reach = read_rel("docs/PARITY_VIOLATION_DOES_NOT_REACH_GENERATION_TRIPLET_NARROW_THEOREM_NOTE_2026-05-23.md")
    substep4 = read_rel("docs/STAGGERED_DIRAC_SUBSTEP4_AC_NARROW_BOUNDED_NOTE_2026-05-07_substep4ac.md")
    c3_preserved = read_rel("docs/C3_SYMMETRY_PRESERVED_INTERPRETATION_NOTE_2026-05-08.md")
    aps_route = read_rel("docs/KOIDE_PHASE_APS_ETA_PARITY_ROUTE_NARROW_THEOREM_NOTE_2026-05-23.md")

    record(
        "E.1 retained parity/chiral violation still does not act inside the generation triplet",
        "not within the generation triplet" in parity_reach
        and "a separate input" in parity_reach,
    )
    record(
        "E.2 existing C3 orbit maps leave a cyclic-shift labeling convention",
        "which cyclic shift" in substep4
        and "labeling convention" in substep4,
    )
    record(
        "E.3 preserved-C3 interpretation treats species labels as downstream readout",
        "mass-ordering labels" in c3_preserved
        and "convention, not derivation input" in c3_preserved,
    )
    record(
        "E.4 APS parity route still names delta=eta_APS as the remaining gap",
        "physical identification" in aps_route
        and "single remaining gap" in aps_route,
    )

    section("F. Verdict")

    record(
        "F.1 bottom-up audit reproduces the Q1-alone sign no-go",
        True,
        "Q1 lives in the transposition-even subalgebra; signed delta lives on the odd line.",
    )
    record(
        "F.2 the narrow positive target is an oriented selected-line/C3 primitive",
        True,
        "Admitting an oriented generator or based endpoint would be extra sign data, not Q1 data.",
    )

    n_pass = sum(1 for _, ok, _ in PASSES if ok)
    n_total = len(PASSES)
    print()
    print("=" * 88)
    print("Summary")
    print("=" * 88)
    print(f"PASSED: {n_pass}/{n_total}")
    for name, ok, _ in PASSES:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")

    print()
    if n_pass == n_total:
        print("VERDICT: bottom-up sign audit finds no hidden Q1 sign primitive.")
        print("KOIDE_Q1_BOTTOM_UP_SIGN_ORIENTATION_AUDIT=TRUE")
        print("Q1_GENERATED_ALGEBRA_ODD_COMPONENT_ZERO=TRUE")
        print("SIGNED_DELTA_FROM_Q1_FIRST_PRINCIPLES=FALSE")
        print("APS_SIGN_REQUIRES_ORIENTATION=TRUE")
        print("SELECTED_LINE_MIRROR_SIGN_UNDERDETERMINED=TRUE")
        print("ORIENTED_C3_GENERATOR_OR_BASED_ENDPOINT_REQUIRED=TRUE")
        print("Q1_DARK_MATTER_CLOSURE=FALSE")
        print("NEXT_THEOREM=derive_oriented_C3_generator_as_physical_selected_line_endpoint_or_accept_magnitude_only")
        return 0

    print("VERDICT: bottom-up sign audit has failing checks.")
    print("KOIDE_Q1_BOTTOM_UP_SIGN_ORIENTATION_AUDIT=FALSE")
    return 1


if __name__ == "__main__":
    sys.exit(main())
