#!/usr/bin/env python3
"""Cycle 816 independent adversarial check of the extinction census.

The Cycle-795, Cycle-814, and Cycle-816 primaries are SHA-pinned text/AST
references only.  The landed Cycle-719 controller core is the sole executable
science input.  This checker independently reconstructs the separator values,
rechecks both exact cycles, and audits whether Cycle 795 actually defined the
higher-k forecasts used by Cycle 816.
"""
from __future__ import annotations

AUDIT_TIMEOUT_SEC = 1200
STDOUT_LIMIT_BYTES = 150 * 1024
AUDIT_INPUT_PATHS = (
    "scripts/frontier_cycle719_two_rail_recurrent_controller_core_2026_07_26.py",
    "scripts/frontier_cycle795_discriminator_census_2026_07_28.py",
    "scripts/frontier_cycle814_deep_silence_probe_2026_07_28.py",
    "scripts/frontier_cycle816_first_forecast_test_2026_07_28.py",
)

import ast
from collections import Counter
from hashlib import sha1, sha256
import importlib.abc
from itertools import combinations
import json
from math import prod
from pathlib import Path
import sys
from time import monotonic
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

TEXT_AST_ONLY_PATHS = AUDIT_INPUT_PATHS[1:]
BLOCKLISTED_MODULES = tuple(Path(path).stem for path in TEXT_AST_ONLY_PATHS)
EXPECTED_SHA256 = {
    AUDIT_INPUT_PATHS[0]:
        "0c0417912f35c369113513823edd2221d446ecdcae7ff039c50fb7c322e791c4",
    AUDIT_INPUT_PATHS[1]:
        "6a52229e9ac3bf5ab45bd25a4088e354c759fc499b58462aa0c2401f89474e7f",
    AUDIT_INPUT_PATHS[2]:
        "f023d10784506e0c9ffbb39b17c3f120af78f377f27c5dab93de9a9aebaa98c0",
    AUDIT_INPUT_PATHS[3]:
        "7ebbb40377a24b52d27350000e37e60593a30286e40b5ce2f50ba917d8a75a71",
}
EXPECTED_GIT_BLOBS = {
    AUDIT_INPUT_PATHS[0]: "c123b8d681c3d76fce08ef13d7673622deac64ad",
    AUDIT_INPUT_PATHS[1]: "45afe5159562f28bb9edebf7340b582408ad4ba7",
    AUDIT_INPUT_PATHS[2]: "19ba617ad1f6be9f8fdc637b764dc7b38cae8d7b",
    AUDIT_INPUT_PATHS[3]: "c8cae9af2931865e8ae179f1cda1ca85e96d5f00",
}
REFERENCE_COMMITS = {
    "cycle719_core": "f7d78df6455d41cf50c143e41c81f204d3dec72e",
    "cycle795_primary": "6427de5c6bdd1e1f7939bac7855e1e188d28daef",
    "cycle814_primary": "d623bced35e9bf0963586e5a0d00ab11071c2a8b",
    "cycle816_primary": "66ae5d58682b3d7bd041310033c48fec322e2ad6",
}


class _PrimaryBlocklist(importlib.abc.MetaPathFinder):
    """Refuse execution of every primary under audit."""

    def __init__(self) -> None:
        self.hits: list[str] = []

    def find_spec(
        self,
        fullname: str,
        path: object = None,
        target: object = None,
    ) -> None:
        if fullname in BLOCKLISTED_MODULES:
            self.hits.append(fullname)
            raise ImportError(f"TEXT_AST_ONLY BLOCKLIST: {fullname}")
        return None


IMPORT_FIREWALL = _PrimaryBlocklist()
sys.meta_path.insert(0, IMPORT_FIREWALL)

import frontier_cycle719_two_rail_recurrent_controller_core_2026_07_26 as K


RING_STATIONS = 11
FIXTURE_BANKS = 2
LANDED_CONSTANTS = (130, 11, 2, 5, 12, 288, 6, 3)
RESOLVED_PERIOD = 4464
RESOLVED_KEYS = (
    (4, (0, 2, 4, 7), 1),
    (4, (0, 2, 4, 8), 1),
)
EXPECTED_TRANSIENT_KEYS = (
    (3, (0, 7)),
    (3, (1, 10)),
)
EXPECTED_CYCLE_KEYS = (
    (2, (0, 9)),
    (3, (0, 5)),
    (3, (0, 6)),
    (3, (1, 6)),
    (3, (1, 7)),
    (3, (2, 7)),
    (3, (2, 8)),
    (3, (3, 8)),
    (3, (3, 9)),
    (3, (4, 9)),
    (3, (4, 10)),
    (3, (5, 10)),
)
EXPECTED_PAIR_TABLE_SHA256 = (
    "266dd5f0c36cb79eb88a143c303e31ef1f79b068d6131545962ee38f8d24e705"
)
EXPECTED_CLEAN_NAMES_SHA256 = (
    "dc265dc602faef161bf1483f95810396fe3c4dfa75e7afb1cf9f871a396e6d91"
)
# Frozen after the first independent construction; this is not read from or
# generated by the Cycle-816 primary.
EXPECTED_INDEPENDENT_FORECAST_ROWS_SHA256 = (
    "a171a90fa3eeeed9908f5bcbf8b9167584ae2e5b96de6d626d07c4ce2b1febcc"
)
EXPECTED_CORRECT_ONE_IDENTITIES: tuple[
    tuple[int, tuple[str, ...], HigherKey], ...
] = (
    (
        1,
        ("direction_short_alignment", "epoch_sum_parity"),
        (4, (0, 2, 4, 8), 1),
    ),
    (
        3,
        ("direction_short_alignment", "parity_code"),
        (4, (0, 2, 4, 8), 1),
    ),
    (
        4,
        ("direction_short_alignment", "same_position_parity"),
        (4, (0, 2, 4, 8), 1),
    ),
    (
        5,
        ("short_orientation", "chord_midpoint_mod11"),
        (4, (0, 2, 4, 7), 1),
    ),
    (
        6,
        ("short_orientation", "epoch_sum_parity"),
        (4, (0, 2, 4, 8), 1),
    ),
    (
        10,
        ("direction_short_alignment", "chord_midpoint_mod11"),
        (4, (0, 2, 4, 7), 1),
    ),
    (
        11,
        ("short_orientation", "position_sum"),
        (4, (0, 2, 4, 8), 1),
    ),
    (
        15,
        ("direction_short_alignment", "position_sum"),
        (4, (0, 2, 4, 8), 1),
    ),
)

Coordinate = tuple[str, str, int]
Support = tuple[Coordinate, ...]
PairKey = tuple[int, tuple[int, int]]
HigherKey = tuple[int, tuple[int, ...], int]


def compact(value: object) -> str:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), default=str
    )


def digest(value: object) -> str:
    return sha256(compact(value).encode("utf-8")).hexdigest()


def git_blob_sha(payload: bytes) -> str:
    return sha1(f"blob {len(payload)}\0".encode("ascii") + payload).hexdigest()


def named_function(tree: ast.Module, name: str) -> ast.FunctionDef:
    rows = [
        node for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name == name
    ]
    if len(rows) != 1:
        raise AssertionError(("function", name, len(rows)))
    return rows[0]


def literal_assignment(tree: ast.Module, name: str) -> object:
    rows = [
        node.value
        for node in tree.body
        if isinstance(node, ast.Assign)
        and any(
            isinstance(target, ast.Name) and target.id == name
            for target in node.targets
        )
    ]
    if len(rows) != 1:
        raise AssertionError(("literal assignment", name, len(rows)))
    return ast.literal_eval(rows[0])


def literal_return(function: ast.FunctionDef) -> object:
    returns = [
        node.value for node in function.body
        if isinstance(node, ast.Return)
    ]
    if len(returns) != 1:
        raise AssertionError(("literal return", function.name, len(returns)))
    return ast.literal_eval(returns[0])


def feature_names() -> tuple[str, ...]:
    """Reimplementation of the Cycle-795 feature vocabulary."""

    fixed = (
        "epoch",
        "epoch_parity",
        "epoch_direction",
        "left",
        "right",
        "clockwise_gap",
        "counterclockwise_gap",
        "ring_separation",
        "ring_long_distance",
        "short_orientation",
        "direction_short_alignment",
        "position_sum",
        "position_product",
        "occupancy_mask",
        "chord_midpoint_mod11",
        "short_arc_start",
        "short_arc_end",
        "left_parity",
        "right_parity",
        "parity_code",
        "same_position_parity",
        "epoch_sum_parity",
        "initial_residual_weight",
        "initial_support_size",
        "support_signature_id",
        "support_kind_mask",
        "support_source_count",
        "support_bank_count",
        "support_link_count",
        "support_bank0_count",
        "support_bank1_count",
        "support_bank_imbalance",
        "support_coordinate_index_sum",
    )
    residues = tuple(
        f"{stem}_mod_{modulus}"
        for modulus in LANDED_CONSTANTS
        for stem in (
            "left",
            "right",
            "position_sum",
            "clockwise_gap",
            "ring_separation",
            "epoch",
        )
    )
    coincidences = tuple(
        f"same_position_residue_mod_{modulus}"
        for modulus in LANDED_CONSTANTS
    )
    return fixed + residues + coincidences


FEATURE_NAMES = feature_names()
PAIR_FEATURES = (
    "epoch",
    "epoch_parity",
    "epoch_direction",
    "left",
    "right",
    "clockwise_gap",
    "counterclockwise_gap",
    "ring_separation",
    "short_orientation",
    "direction_short_alignment",
    "position_sum",
    "position_product",
    "occupancy_mask",
    "chord_midpoint_mod11",
    "parity_code",
    "same_position_parity",
    "epoch_sum_parity",
    "initial_residual_weight",
    "support_signature_id",
    "support_kind_mask",
    "support_source_count",
    "support_bank_count",
    "support_link_count",
    "support_bank_imbalance",
)
FEATURE_INDEX = {
    name: index for index, name in enumerate(FEATURE_NAMES)
}


def watched_registers() -> tuple[tuple[str, int], ...]:
    rows = [
        ("POINTER", K.A.POINTER),
        ("U_TO_V", K.A.U_TO_V),
        ("V_TO_U", K.A.V_TO_U),
        ("DIRECTION_OK", K.A.DIRECTION_OK),
    ]
    rows.extend(
        (f"FRESH_{index}", wire)
        for index, wire in enumerate(K.A.FRESH)
    )
    rows.extend(
        (f"ZERO_WORK_{index}", wire)
        for index, wire in enumerate(K.A.ZERO_WORK)
    )
    rows.append(("TOKEN_OK", K.A.TOKEN_OK))
    return tuple(rows)


def residual_support(state: tuple[int, ...]) -> Support:
    banks, links = K.M.unpack_state(state, FIXTURE_BANKS)
    rows: list[Coordinate] = []
    if state[K.R3.X.SOURCE_POINTER]:
        rows.append(("source", "SOURCE_POINTER", 0))
    for bank_index, bank in enumerate(banks):
        rows.extend(
            ("bank", name, bank_index)
            for name, wire in watched_registers()
            if bank[wire]
        )
    for link_index, link in enumerate(links):
        rows.extend(
            ("link", f"WIRE_{wire}", link_index)
            for wire, bit in enumerate(link)
            if bit
        )
    return tuple(sorted(rows))


def allocator_fixtures() -> tuple[
    tuple[int, tuple[int, int], tuple[int, ...]], ...
]:
    banks, links = K.B.chain_genesis(FIXTURE_BANKS)
    state = K.M.pack_state(banks, links)
    rows = []
    for event in range(2 * FIXTURE_BANKS):
        direction = (1, 0) if event % 2 == 0 else (0, 1)
        before = K.M.prepare_endpoint(state, direction)
        rows.append((event, direction, before))
        state = K.A.apply_semantic(
            before, K.M.global_allocator_word(FIXTURE_BANKS)
        )
    return tuple(rows)


def separated_pairs() -> tuple[tuple[int, int], ...]:
    return tuple(
        (left, right)
        for left, right in combinations(range(RING_STATIONS), 2)
        if min(
            (right - left) % RING_STATIONS,
            (left - right) % RING_STATIONS,
        ) > 1
    )


def support_counts(support: Support) -> tuple[int, ...]:
    source = sum(row[0] == "source" for row in support)
    bank = sum(row[0] == "bank" for row in support)
    link = sum(row[0] == "link" for row in support)
    bank0 = sum(
        row[0] == "bank" and row[2] == 0 for row in support
    )
    bank1 = sum(
        row[0] == "bank" and row[2] == 1 for row in support
    )
    kind_mask = int(source > 0) + 2 * int(bank > 0) + 4 * int(link > 0)
    return (
        source,
        bank,
        link,
        bank0,
        bank1,
        kind_mask,
        sum(row[2] for row in support),
    )


def occupied_set_feature_vector(
    event: int,
    positions: tuple[int, ...],
    direction: tuple[int, int],
    support: Support,
    pair_support_ids: dict[Support, int],
) -> tuple[Any, ...]:
    """Compute the later Cycle-816 occupied-set extension independently."""

    left = min(positions)
    right = max(positions)
    clockwise = (right - left) % RING_STATIONS
    anticlockwise = (left - right) % RING_STATIONS
    separation = min(clockwise, anticlockwise)
    short_sign = 1 if clockwise < anticlockwise else -1
    direction_sign = 1 if direction == (1, 0) else -1
    position_sum = sum(positions)
    source, bank, link, bank0, bank1, kind_mask, index_sum = (
        support_counts(support)
    )
    support_id: int | str = pair_support_ids.get(
        support, "NEW_SUPPORT_" + digest(support)
    )

    values: list[Any] = [
        event,
        event & 1,
        direction_sign,
        left,
        right,
        clockwise,
        anticlockwise,
        separation,
        max(clockwise, anticlockwise),
        short_sign,
        direction_sign * short_sign,
        position_sum,
        prod(positions),
        sum(1 << position for position in positions),
        pow(len(positions), -1, RING_STATIONS)
        * position_sum % RING_STATIONS,
        left if short_sign == 1 else right,
        right if short_sign == 1 else left,
        left & 1,
        right & 1,
        2 * (left & 1) + (right & 1),
        int(len({position & 1 for position in positions}) == 1),
        (event + position_sum) & 1,
        len(support),
        len(support),
        support_id,
        kind_mask,
        source,
        bank,
        link,
        bank0,
        bank1,
        bank1 - bank0,
        index_sum,
    ]
    for modulus in LANDED_CONSTANTS:
        values.extend(
            (
                left % modulus,
                right % modulus,
                position_sum % modulus,
                clockwise % modulus,
                separation % modulus,
                event % modulus,
            )
        )
    values.extend(
        int(len({position % modulus for position in positions}) == 1)
        for modulus in LANDED_CONSTANTS
    )
    if len(values) != len(FEATURE_NAMES):
        raise AssertionError(("feature width", len(values)))
    return tuple(values)


def build_feature_data() -> dict[str, object]:
    program = K.interleaved_program(FIXTURE_BANKS)
    fixtures = allocator_fixtures()
    pair_supports: dict[PairKey, Support] = {}
    for event, _direction, before in fixtures:
        for positions in separated_pairs():
            after, rail_a, rail_b, _trace = K.run_orbit(
                before, program, token_positions=positions
            )
            expected_rail = tuple(
                int(station in positions)
                for station in range(RING_STATIONS)
            )
            if rail_a != expected_rail or any(rail_b):
                raise AssertionError(("pair rail", event, positions))
            pair_supports[(event, positions)] = residual_support(after)

    pair_support_ids = {
        support: index
        for index, support in enumerate(sorted(set(pair_supports.values())))
    }
    fixture_map = {
        event: (direction, before)
        for event, direction, before in fixtures
    }
    pair_vectors: dict[PairKey, tuple[Any, ...]] = {}
    pair_rows = []
    for key in sorted(pair_supports):
        event, positions = key
        vector = occupied_set_feature_vector(
            event,
            positions,
            fixture_map[event][0],
            pair_supports[key],
            pair_support_ids,
        )
        pair_vectors[key] = vector
        pair_rows.append((event, positions[0], positions[1], *vector))

    higher_vectors: dict[HigherKey, tuple[Any, ...]] = {}
    higher_initial_states: dict[HigherKey, tuple[int, ...]] = {}
    for key in RESOLVED_KEYS:
        k, positions, event = key
        direction, before = fixture_map[event]
        after, rail_a, rail_b, _trace = K.run_orbit(
            before, program, token_positions=positions
        )
        expected_rail = tuple(
            int(station in positions)
            for station in range(RING_STATIONS)
        )
        if len(positions) != k or rail_a != expected_rail or any(rail_b):
            raise AssertionError(("higher rail", key))
        higher_vectors[key] = occupied_set_feature_vector(
            event,
            positions,
            direction,
            residual_support(after),
            pair_support_ids,
        )
        higher_initial_states[key] = after

    return {
        "program": program,
        "fixtures": fixtures,
        "pair_vectors": pair_vectors,
        "pair_rows": tuple(pair_rows),
        "pair_support_ids": pair_support_ids,
        "higher_vectors": higher_vectors,
        "higher_initial_states": higher_initial_states,
    }


def select(vector: tuple[Any, ...], names: tuple[str, ...]) -> tuple[Any, ...]:
    return tuple(vector[FEATURE_INDEX[name]] for name in names)


def implication(
    value: tuple[Any, ...],
    transient_values: frozenset[tuple[Any, ...]],
    cycle_values: frozenset[tuple[Any, ...]],
) -> str:
    if value in transient_values and value not in cycle_values:
        return "TRANSIENT"
    if value in cycle_values and value not in transient_values:
        return "CYCLE"
    return "UNSEEN"


def independent_separator_analysis(
    feature_data: dict[str, object],
) -> dict[str, object]:
    pair_vectors = feature_data["pair_vectors"]
    higher_vectors = feature_data["higher_vectors"]
    transient_keys = tuple(sorted(EXPECTED_TRANSIENT_KEYS))
    cycle_keys = tuple(sorted(EXPECTED_CYCLE_KEYS))
    old_open_keys = tuple(
        sorted(
            set(pair_vectors)
            - set(transient_keys)
            - set(cycle_keys)
        )
    )
    candidates = (
        tuple((name,) for name in FEATURE_NAMES)
        + tuple(combinations(PAIR_FEATURES, 2))
    )
    hypotheses = []
    for names in candidates:
        transient_values = frozenset(
            select(pair_vectors[key], names) for key in transient_keys
        )
        cycle_values = frozenset(
            select(pair_vectors[key], names) for key in cycle_keys
        )
        if not transient_values.isdisjoint(cycle_values):
            continue
        old_forecast = tuple(
            implication(
                select(pair_vectors[key], names),
                transient_values,
                cycle_values,
            )
            for key in old_open_keys
        )
        margin = min(
            sum(abs(left - right) for left, right in zip(tvalue, cvalue))
            for tvalue in transient_values
            for cvalue in cycle_values
        )
        hypotheses.append(
            {
                "names": names,
                "transient_values": transient_values,
                "cycle_values": cycle_values,
                "old_forecast": old_forecast,
                "old_classified":
                    sum(label != "UNSEEN" for label in old_forecast),
                "margin": margin,
            }
        )
    hypotheses.sort(
        key=lambda row: (
            -row["old_classified"],
            len(row["names"]),
            -row["margin"],
            row["names"],
        )
    )

    rows = []
    census_lists = {
        "correct_on_both": [],
        "correct_on_one": [],
        "wrong_on_both": [],
    }
    for hypothesis_id, hypothesis in enumerate(hypotheses, start=1):
        key_tests = []
        correct = 0
        for key in RESOLVED_KEYS:
            value = select(higher_vectors[key], hypothesis["names"])
            side = implication(
                value,
                hypothesis["transient_values"],
                hypothesis["cycle_values"],
            )
            is_correct = side == "CYCLE"
            correct += int(is_correct)
            key_tests.append(
                {
                    "key": key,
                    "separator_value": value,
                    "forecast_side": side,
                    "resolved_side": "CYCLE",
                    "test_result": "CORRECT" if is_correct else "WRONG",
                }
            )
        census_name = {
            2: "correct_on_both",
            1: "correct_on_one",
            0: "wrong_on_both",
        }[correct]
        census_lists[census_name].append(hypothesis["names"])
        rows.append(
            {
                "hypothesis_id": hypothesis_id,
                "features": hypothesis["names"],
                "key_tests": tuple(key_tests),
                "census_bin": census_name,
                "killed_as_universal_separator": correct < 2,
            }
        )

    correct_one_rows = tuple(
        {
            "hypothesis_id": row["hypothesis_id"],
            "features": row["features"],
            "correct_key": next(
                test["key"]
                for test in row["key_tests"]
                if test["test_result"] == "CORRECT"
            ),
            "forecast_sides": tuple(
                test["forecast_side"] for test in row["key_tests"]
            ),
            "separator_values": tuple(
                test["separator_value"] for test in row["key_tests"]
            ),
        }
        for row in rows
        if row["census_bin"] == "correct_on_one"
    )
    counts = {
        name: len(values) for name, values in census_lists.items()
    }
    return {
        "candidate_count": len(candidates),
        "old_open_keys": old_open_keys,
        "hypotheses": tuple(hypotheses),
        "rows": tuple(rows),
        "rows_sha256": digest(rows),
        "clean_names_sha256":
            digest(tuple(row["names"] for row in hypotheses)),
        "old_forecast_vector_count":
            len({row["old_forecast"] for row in hypotheses}),
        "counts": counts,
        "lists": {
            name: tuple(values) for name, values in census_lists.items()
        },
        "correct_one_rows": correct_one_rows,
    }


def synchronous_configuration_word(
    program: tuple[object, ...],
    occupied: tuple[int, ...],
) -> tuple[object, ...]:
    """Direct scheduler composition, separate from Cycle 814's implementation."""

    current = frozenset(occupied)
    word = []
    for _tick in range(len(program)):
        for station, macro in enumerate(program):
            if station in current:
                word.extend(K.mapped_macro(macro))
        current = frozenset(
            (station + 1) % len(program) for station in current
        )
    return tuple(word)


def clean_postimage(state: tuple[int, ...]) -> bool:
    return not residual_support(state)


def verify_two_cycles(feature_data: dict[str, object]) -> tuple[
    dict[str, object], ...
]:
    program = feature_data["program"]
    initial_states = feature_data["higher_initial_states"]
    rows = []
    for key in RESOLVED_KEYS:
        _k, positions, _event = key
        word = synchronous_configuration_word(program, positions)
        initial = initial_states[key]
        state = initial
        clean_moments = []
        earlier_returns = []
        trajectory_hasher = sha256()
        for moment in range(RESOLVED_PERIOD):
            trajectory_hasher.update(
                str(sum(bit << index for index, bit in enumerate(state)))
                .encode("ascii")
            )
            trajectory_hasher.update(b"\n")
            if clean_postimage(state):
                clean_moments.append(moment)
            if moment and state == initial:
                earlier_returns.append(moment)
            state = K.A.apply_semantic(state, word)
        rows.append(
            {
                "key": key,
                "period": RESOLVED_PERIOD,
                "all_phases_nonclean": not clean_moments,
                "clean_moments": tuple(clean_moments),
                "no_earlier_return_to_T0": not earlier_returns,
                "earlier_return_moments": tuple(earlier_returns),
                "exact_full_state_return_to_T0": state == initial,
                "initial_state_sha256": sha256(
                    str(
                        sum(
                            bit << index
                            for index, bit in enumerate(initial)
                        )
                    ).encode("ascii")
                ).hexdigest(),
                "trajectory_sha256": trajectory_hasher.hexdigest(),
                "permanent_cycle_certified": (
                    not clean_moments
                    and not earlier_returns
                    and state == initial
                ),
            }
        )
    return tuple(rows)


def returned_dict_constant(
    function: ast.FunctionDef,
    key: str,
) -> object:
    returns = [
        node for node in function.body
        if isinstance(node, ast.Return) and isinstance(node.value, ast.Dict)
    ]
    if len(returns) != 1:
        raise AssertionError(("dict return", function.name, len(returns)))
    mapping = {
        ast.literal_eval(key_node): value_node
        for key_node, value_node in zip(
            returns[0].value.keys, returns[0].value.values
        )
        if key_node is not None
    }
    return ast.literal_eval(mapping[key])


def pair_key_annotation(tree: ast.Module) -> str | None:
    rows = [
        node.value
        for node in tree.body
        if isinstance(node, ast.Assign)
        and any(
            isinstance(target, ast.Name) and target.id == "Key"
            for target in node.targets
        )
    ]
    return ast.unparse(rows[0]) if len(rows) == 1 else None


def pair_unpack_present(function: ast.FunctionDef) -> bool:
    for node in ast.walk(function):
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if (
            isinstance(target, ast.Tuple)
            and len(target.elts) == 2
            and isinstance(target.elts[0], ast.Name)
            and target.elts[0].id == "epoch"
            and isinstance(target.elts[1], ast.Tuple)
            and tuple(
                item.id if isinstance(item, ast.Name) else None
                for item in target.elts[1].elts
            ) == ("left", "right")
            and isinstance(node.value, ast.Name)
            and node.value.id == "key"
        ):
            return True
    return False


def source_and_domain_controls() -> dict[str, object]:
    payloads = {
        path: (ROOT / path).read_bytes()
        for path in AUDIT_INPUT_PATHS
        if (ROOT / path).is_file()
    }
    trees = {
        path: ast.parse(payload, filename=path)
        for path, payload in payloads.items()
    }
    sha_rows = {
        path: sha256(payload).hexdigest()
        for path, payload in payloads.items()
    }
    blob_rows = {
        path: git_blob_sha(payload)
        for path, payload in payloads.items()
    }
    self_tree = ast.parse(
        Path(__file__).read_text(encoding="utf-8"),
        filename=Path(__file__).name,
    )
    literal_paths = literal_assignment(self_tree, "AUDIT_INPUT_PATHS")
    direct_frontier_imports = tuple(sorted(
        alias.name
        for node in self_tree.body
        if isinstance(node, ast.Import)
        for alias in node.names
        if alias.name.startswith("frontier_cycle")
    ))

    tree795 = trees[AUDIT_INPUT_PATHS[1]]
    tree814 = trees[AUDIT_INPUT_PATHS[2]]
    tree816 = trees[AUDIT_INPUT_PATHS[3]]
    boundaries = named_function(tree795, "boundaries")
    feature_table_795 = named_function(tree795, "feature_table")
    candidate_795 = named_function(tree795, "candidate_result")
    resolved_795 = named_function(tree795, "resolved_catalog")
    candidate_strings = {
        node.value for node in ast.walk(candidate_795)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    }
    resolved_catalog_labels = {
        value.value
        for node in ast.walk(resolved_795)
        if isinstance(node, ast.Dict)
        for key, value in zip(node.keys, node.values)
        if (
            isinstance(key, ast.Constant)
            and key.value == "v"
            and isinstance(value, ast.Constant)
            and value.value in {"TRANSIENT", "CYCLE"}
        )
    }
    open_key_loop = any(
        isinstance(node, ast.For)
        and isinstance(node.target, ast.Name)
        and node.target.id == "key"
        and isinstance(node.iter, ast.Name)
        and node.iter.id == "open_keys"
        for node in ast.walk(candidate_795)
    )
    key_annotation = pair_key_annotation(tree795)
    domain = {
        "definition_path": AUDIT_INPUT_PATHS[1],
        "Key_annotation": key_annotation,
        "feature_table_pair_unpack": pair_unpack_present(feature_table_795),
        "family_size": literal_assignment(tree795, "FAMILY_SIZE"),
        "open_size": literal_assignment(tree795, "OPEN_SIZE"),
        "scope": returned_dict_constant(boundaries, "scope"),
        "separator_status":
            returned_dict_constant(boundaries, "separator_status"),
        "forecast_status":
            returned_dict_constant(boundaries, "forecast_status"),
        "resolved_catalog_labels": tuple(sorted(resolved_catalog_labels)),
        "candidate_labels":
            tuple(sorted(
                candidate_strings & {"TRANSIENT", "CYCLE", "UNSEEN"}
            )),
        "candidate_forecasts_only_for_open_keys": open_key_loop,
        "higher_k_definition_present": any(
            isinstance(node, (ast.FunctionDef, ast.ClassDef))
            and "higher" in node.name.lower()
            for node in tree795.body
        ),
    }
    domain["pair_domain_exact"] = (
        key_annotation == "tuple[int, tuple[int, int]]"
        and domain["feature_table_pair_unpack"]
        and domain["family_size"] == 176
        and domain["open_size"] == 162
        and domain["scope"]
        == "FINITE_14_RESOLVED_KEY_DISCRIMINATION_CENSUS"
        and domain["forecast_status"]
        == "FEATURE_IMPLICATION_ONLY_NOT_A_CLAIM"
        and domain["resolved_catalog_labels"] == ("CYCLE", "TRANSIENT")
        and domain["candidate_labels"] == ("CYCLE", "TRANSIENT", "UNSEEN")
        and domain["candidate_forecasts_only_for_open_keys"]
        and not domain["higher_k_definition_present"]
    )

    named_features_816 = named_function(tree816, "named_features")
    extension_doc = ast.get_docstring(named_features_816) or ""
    primary816_basis = {
        "resolved_keys": literal_assignment(tree816, "RESOLVED_KEYS"),
        "resolved_period": literal_assignment(tree816, "RESOLVED_PERIOD"),
        "pair_table_sha256":
            literal_assignment(tree816, "EXPECTED_PRIMARY_TABLE_SHA256"),
        "clean_names_sha256":
            literal_assignment(tree816, "EXPECTED_CLEAN_NAMES_SHA256"),
        "occupied_set_extension_declared":
            "occupied set" in extension_doc
            and "Cycle-795 left/right" in extension_doc,
        "functions": tuple(sorted(
            node.name for node in tree816.body
            if isinstance(node, ast.FunctionDef)
            and node.name in {
                "named_features",
                "separator_reconstruction",
                "forecast_side",
                "prospective_test",
            }
        )),
    }
    strings814 = {
        node.value for node in ast.walk(tree814)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
    }
    cycle814_basis = {
        "has_exact_cycle_verifier":
            {
                "lane_equals_initial",
                "verify_trajectory",
                "verify_terminal_event",
            } <= {
                node.name for node in tree814.body
                if isinstance(node, ast.FunctionDef)
            },
        "landed_permanent_label":
            any(
                "CERTIFIED_FOREVER_NONCLEAN_CYCLE:" in value
                for value in strings814
            ),
        "return_to_T0_field": "return_to_T0_moments" in strings814,
    }

    blocked_attempts = []
    for module in BLOCKLISTED_MODULES:
        try:
            __import__(module)
        except ImportError as error:
            blocked_attempts.append(
                (module, str(error).startswith("TEXT_AST_ONLY BLOCKLIST:"))
            )
        else:
            blocked_attempts.append((module, False))

    result = {
        "AUDIT_INPUT_PATHS": AUDIT_INPUT_PATHS,
        "AUDIT_INPUT_PATHS_literal": literal_paths == AUDIT_INPUT_PATHS,
        "existing_worktree_relative": (
            len(payloads) == len(AUDIT_INPUT_PATHS)
            and all(
                not Path(path).is_absolute() and (ROOT / path).is_file()
                for path in AUDIT_INPUT_PATHS
            )
        ),
        "sha256": sha_rows,
        "expected_sha256": EXPECTED_SHA256,
        "git_blobs": blob_rows,
        "expected_git_blobs": EXPECTED_GIT_BLOBS,
        "reference_commits": REFERENCE_COMMITS,
        "text_AST_only_paths": TEXT_AST_ONLY_PATHS,
        "blocked_modules": BLOCKLISTED_MODULES,
        "blocked_import_attempts": tuple(blocked_attempts),
        "firewall_hits": tuple(IMPORT_FIREWALL.hits),
        "blocked_modules_loaded": tuple(
            module for module in BLOCKLISTED_MODULES
            if module in sys.modules
        ),
        "direct_frontier_imports": direct_frontier_imports,
        "cycle795_domain": domain,
        "cycle814_classification_basis": cycle814_basis,
        "cycle816_AST_basis": primary816_basis,
    }
    result["pass"] = (
        result["AUDIT_INPUT_PATHS_literal"]
        and result["existing_worktree_relative"]
        and sha_rows == EXPECTED_SHA256
        and blob_rows == EXPECTED_GIT_BLOBS
        and all(passed for _module, passed in blocked_attempts)
        and tuple(module for module, _passed in blocked_attempts)
        == BLOCKLISTED_MODULES
        and tuple(IMPORT_FIREWALL.hits) == BLOCKLISTED_MODULES
        and not result["blocked_modules_loaded"]
        and direct_frontier_imports
        == (
            "frontier_cycle719_two_rail_recurrent_controller_core_2026_07_26",
        )
        and domain["pair_domain_exact"]
        and cycle814_basis["has_exact_cycle_verifier"]
        and cycle814_basis["landed_permanent_label"]
        and cycle814_basis["return_to_T0_field"]
        and primary816_basis["resolved_keys"] == RESOLVED_KEYS
        and primary816_basis["resolved_period"] == RESOLVED_PERIOD
        and primary816_basis["pair_table_sha256"]
        == EXPECTED_PAIR_TABLE_SHA256
        and primary816_basis["clean_names_sha256"]
        == EXPECTED_CLEAN_NAMES_SHA256
        and primary816_basis["occupied_set_extension_declared"]
        and primary816_basis["functions"]
        == (
            "forecast_side",
            "named_features",
            "prospective_test",
            "separator_reconstruction",
        )
    )
    return result


def analysis_once() -> dict[str, object]:
    feature_data = build_feature_data()
    separators = independent_separator_analysis(feature_data)
    cycles = verify_two_cycles(feature_data)
    stable = {
        "pair_rows": feature_data["pair_rows"],
        "higher_vectors": tuple(
            (key, feature_data["higher_vectors"][key])
            for key in RESOLVED_KEYS
        ),
        "forecast_rows": separators["rows"],
        "cycles": cycles,
    }
    return {
        "features": feature_data,
        "separators": separators,
        "cycles": cycles,
        "stable_sha256": digest(stable),
    }


def render_output(
    checks: dict[str, bool],
    findings: dict[str, str],
    certificates: dict[str, object],
    report: dict[str, object],
) -> str:
    lines = [
        f"{'PASS' if passed else 'FAIL'} {label}"
        for label, passed in checks.items()
    ]
    lines.extend(
        f"FINDING {label} {finding}"
        for label, finding in findings.items()
    )
    lines.extend(
        f"CERTIFICATE {label} {compact(certificate)}"
        for label, certificate in certificates.items()
    )
    lines.append("SUMMARY_JSON " + compact(report))
    lines.append(str(report["terminal"]))
    return "\n".join(lines) + "\n"


def stable_output(
    checks: dict[str, bool],
    findings: dict[str, str],
    certificates: dict[str, object],
    report: dict[str, object],
) -> str:
    for _attempt in range(20):
        report["checks"] = dict(checks)
        report["pass"] = all(checks.values())
        report["terminal"] = (
            "CYCLE816_FORECAST_INDEPENDENT_CHECK_CONFIRMED"
            if report["pass"]
            else "CYCLE816_FORECAST_INDEPENDENT_CHECK_HONEST_FAIL"
        )
        output = render_output(checks, findings, certificates, report)
        size = len(output.encode("utf-8"))
        controls = certificates["CONTROLS"]
        if (
            report["stdout_bytes"] == size
            and controls["stdout_bytes"] == size
        ):
            return output
        report["stdout_bytes"] = size
        controls["stdout_bytes"] = size
    raise AssertionError("stdout byte fixed point did not converge")


def run() -> int:
    started = monotonic()
    sources = source_and_domain_controls()
    first = analysis_once()
    replay = analysis_once()
    features = first["features"]
    separators = first["separators"]
    cycles = first["cycles"]

    correct_one_identities = tuple(
        (
            row["hypothesis_id"],
            row["features"],
            row["correct_key"],
        )
        for row in separators["correct_one_rows"]
    )
    forecast_label_counts = Counter(
        test["forecast_side"]
        for row in separators["rows"]
        for test in row["key_tests"]
    )
    primary_extension_census = separators["counts"]
    adjusted_census = {
        "correct_on_both": 0,
        "correct_on_one": 0,
        "wrong_on_both": 0,
        "not_tested_domain_undefined": 103,
        "killed": 0,
        "not_refuted": 103,
    }
    undefined_hypotheses = tuple(
        row["names"] for row in separators["hypotheses"]
    )

    checks: dict[str, bool] = {}
    findings: dict[str, str] = {}
    certificates: dict[str, object] = {}

    checks["FORECAST RE-DERIVATION"] = (
        len(FEATURE_NAMES) == len(set(FEATURE_NAMES)) == 89
        and len(PAIR_FEATURES) == len(set(PAIR_FEATURES)) == 24
        and len(features["pair_vectors"]) == 176
        and len(features["pair_support_ids"]) == 25
        and digest(features["pair_rows"]) == EXPECTED_PAIR_TABLE_SHA256
        and separators["candidate_count"] == 365
        and len(separators["hypotheses"]) == 103
        and separators["clean_names_sha256"]
        == EXPECTED_CLEAN_NAMES_SHA256
        and len(separators["rows"]) == 103
        and separators["rows_sha256"]
        == EXPECTED_INDEPENDENT_FORECAST_ROWS_SHA256
        and tuple(
            row["hypothesis_id"] for row in separators["rows"]
        ) == tuple(range(1, 104))
        and all(len(row["key_tests"]) == 2 for row in separators["rows"])
        and sources["cycle816_AST_basis"]["resolved_keys"]
        == RESOLVED_KEYS
    )
    findings["FORECAST RE-DERIVATION"] = (
        "The independent occupied-set implementation reproduces all 103 "
        "Cycle-816 extension rows for both keys, with frozen row SHA256 "
        f"{separators['rows_sha256']}."
    )
    certificates["FORECAST RE-DERIVATION"] = {
        "method": (
            "Cycle-795 schema/candidate vocabulary reimplemented from text/AST; "
            "pair and k=4 postimages recomputed only through the Cycle-719 core; "
            "no audited primary imported or executed"
        ),
        "feature_count": len(FEATURE_NAMES),
        "pair_feature_count": len(PAIR_FEATURES),
        "candidate_count": separators["candidate_count"],
        "clean_hypothesis_count": len(separators["hypotheses"]),
        "tested_keys": RESOLVED_KEYS,
        "pair_table_sha256": digest(features["pair_rows"]),
        "clean_names_sha256": separators["clean_names_sha256"],
        "forecast_rows_sha256": separators["rows_sha256"],
        "extension_forecast_label_counts":
            dict(sorted(forecast_label_counts.items())),
    }

    checks["THE KILL RECOUNT"] = (
        primary_extension_census
        == {
            "correct_on_both": 0,
            "correct_on_one": 8,
            "wrong_on_both": 95,
        }
        and correct_one_identities == EXPECTED_CORRECT_ONE_IDENTITIES
        and separators["old_forecast_vector_count"] == 46
        and not separators["lists"]["correct_on_both"]
    )
    findings["THE KILL RECOUNT"] = (
        "Conditional on Cycle 816's added higher-k extension, the recount is "
        "0 correct-both, 8 correct-one, 95 wrong-both, and 46 -> 0; the eight "
        "correct-one identities match exactly."
    )
    certificates["THE KILL RECOUNT"] = {
        "scope": "CYCLE816_ADDED_OCCUPIED_SET_EXTENSION_ONLY",
        "counts": primary_extension_census,
        "correct_one_rows": separators["correct_one_rows"],
        "correct_one_identity_tuple": correct_one_identities,
        "surviving_universal_separators": (),
        "original_distinct_forecast_vectors":
            separators["old_forecast_vector_count"],
        "extension_surviving_distinct_forecast_vectors": 0,
        "extension_vector_collapse": "46 -> 0",
    }

    cycles_pass = (
        len(cycles) == 2
        and tuple(row["key"] for row in cycles) == RESOLVED_KEYS
        and all(
            row["period"] == RESOLVED_PERIOD
            and row["all_phases_nonclean"]
            and row["no_earlier_return_to_T0"]
            and row["exact_full_state_return_to_T0"]
            and row["permanent_cycle_certified"]
            for row in cycles
        )
    )
    checks["CLASSIFICATION FIDELITY"] = (
        cycles_pass
        and sources["cycle795_domain"]["resolved_catalog_labels"]
        == ("CYCLE", "TRANSIENT")
        and sources["cycle814_classification_basis"][
            "landed_permanent_label"
        ]
        and sources["cycle814_classification_basis"][
            "return_to_T0_field"
        ]
    )
    findings["CLASSIFICATION FIDELITY"] = (
        "Cycle 795 defines resolved recurrence rows as v=CYCLE and clean-event "
        "rows as v=TRANSIENT; both independently checked period-4464 full-state "
        "returns are forever nonclean, so their landed side is exactly CYCLE."
    )
    certificates["CLASSIFICATION FIDELITY"] = {
        "cycle795_definition_citation": {
            "path": sources["cycle795_domain"]["definition_path"],
            "resolved_catalog_labels":
                sources["cycle795_domain"]["resolved_catalog_labels"],
            "candidate_labels":
                sources["cycle795_domain"]["candidate_labels"],
            "forecast_status":
                sources["cycle795_domain"]["forecast_status"],
        },
        "cycle814_landed_basis":
            sources["cycle814_classification_basis"],
        "independent_exact_cycle_checks": cycles,
        "mapping": "EXACT_FULL_STATE_RECURRENCE_AND_NEVER_CLEAN => CYCLE",
    }

    escape_pass = (
        sources["cycle795_domain"]["pair_domain_exact"]
        and sources["cycle816_AST_basis"][
            "occupied_set_extension_declared"
        ]
        and all(key[0] == 4 and len(key[1]) == 4 for key in RESOLVED_KEYS)
        and len(undefined_hypotheses) == 103
        and adjusted_census["not_tested_domain_undefined"] == 103
        and adjusted_census["killed"] == 0
        and adjusted_census["not_refuted"] == 103
    )
    checks["THE ESCAPE ATTACK"] = escape_pass
    findings["THE ESCAPE ATTACK"] = (
        "CONFIRMED: Cycle 795 defines Key as an epoch plus exactly two "
        "positions and forecasts only its 162 pair-family open keys. The two "
        "k=4 keys are outside that domain; all 103 hypotheses are UNDEFINED "
        "there under the 795 definitions, hence not tested, none is killed, "
        "and the domain-faithful vector census remains 46 -> 46."
    )
    certificates["THE ESCAPE ATTACK"] = {
        "headline": "THE 795 HYPOTHESIS CLASS IS NOT SHOWN EXTINCT",
        "cycle795_declared_domain": sources["cycle795_domain"],
        "cycle816_later_extension": {
            "path": AUDIT_INPUT_PATHS[3],
            "occupied_set_extension_declared":
                sources["cycle816_AST_basis"][
                    "occupied_set_extension_declared"
                ],
            "status":
                "DEFENSIBLE_NEW_EXTENSION_BUT_NOT_PART_OF_CYCLE795_DOMAIN",
        },
        "important_distinction": (
            "UNSEEN is a total label for a value on a Cycle-795 pair-domain "
            "open key; UNDEFINED means the k=4 key has no feature/forecast "
            "value in the Cycle-795 definition at all"
        ),
        "undefined_row_count": len(undefined_hypotheses),
        "undefined_rows": undefined_hypotheses,
        "adjusted_census": adjusted_census,
        "adjusted_vector_collapse": "46 -> 46",
        "surviving_reading":
            "103/103 remain unrefuted on their declared Cycle-795 domain",
    }

    deterministic = first["stable_sha256"] == replay["stable_sha256"]
    elapsed = monotonic() - started
    controls_base = (
        sources["pass"]
        and deterministic
        and elapsed < AUDIT_TIMEOUT_SEC
        and tuple(IMPORT_FIREWALL.hits) == BLOCKLISTED_MODULES
        and not any(
            module in sys.modules for module in BLOCKLISTED_MODULES
        )
    )
    checks["CONTROLS"] = controls_base
    findings["CONTROLS"] = (
        "All four literal audit inputs exist and match pinned SHA256/blob "
        "identities; the 795/814/816 primaries were blocked from import, the "
        "full analysis replayed deterministically, and runtime/stdout stayed "
        "inside the requested bounds."
    )
    certificates["CONTROLS"] = {
        **sources,
        "deterministic": deterministic,
        "first_analysis_sha256": first["stable_sha256"],
        "replay_analysis_sha256": replay["stable_sha256"],
        "runtime_seconds": round(elapsed, 6),
        "runtime_limit_seconds": AUDIT_TIMEOUT_SEC,
        "stdout_bytes": 0,
        "stdout_limit_bytes": STDOUT_LIMIT_BYTES,
    }

    report = {
        "cycle": 816,
        "status": "PRIMARY_V2_DOMAIN_CORRECTION_CONFIRMED",
        "extension_recount": primary_extension_census,
        "domain_faithful_census": adjusted_census,
        "extension_vector_collapse": "46 -> 0",
        "domain_faithful_vector_collapse": "46 -> 46",
        "headline": "103/103 CYCLE795 HYPOTHESES NOT TESTED; NONE KILLED",
        "runtime_seconds": round(elapsed, 6),
        "runtime_limit_seconds": AUDIT_TIMEOUT_SEC,
        "stdout_bytes": 0,
        "stdout_limit_bytes": STDOUT_LIMIT_BYTES,
        "checks": {},
        "pass": False,
        "terminal": "CYCLE816_FORECAST_INDEPENDENT_CHECK_HONEST_FAIL",
    }
    output = stable_output(checks, findings, certificates, report)
    stdout_ok = len(output.encode("utf-8")) < STDOUT_LIMIT_BYTES
    checks["CONTROLS"] = controls_base and stdout_ok
    output = stable_output(checks, findings, certificates, report)
    if len(output.encode("utf-8")) >= STDOUT_LIMIT_BYTES:
        failure = {
            "pass": False,
            "terminal": "CYCLE816_FORECAST_INDEPENDENT_CHECK_HONEST_FAIL",
            "failure": "stdout bound exceeded",
            "stdout_bytes": len(output.encode("utf-8")),
            "stdout_limit_bytes": STDOUT_LIMIT_BYTES,
        }
        sys.stdout.write(compact(failure) + "\n")
        return 1
    sys.stdout.write(output)
    return 0 if report["pass"] else 1


def main() -> int:
    try:
        return run()
    except Exception as error:
        failure = {
            "pass": False,
            "terminal": "CYCLE816_FORECAST_INDEPENDENT_CHECK_HONEST_FAIL",
            "exception_type": type(error).__name__,
            "exception": str(error),
        }
        sys.stdout.write(compact(failure) + "\n")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
