#!/usr/bin/env python3
"""Species bridge minimum decomposition: derived support + two vacuities.

Companion runner for
    docs/SPECIES_BRIDGE_MINIMUM_DECOMPOSITION_BOUNDED_THEOREM_NOTE_2026-06-13.md

Treats AC_phi_lambda sub-admission (iii), the abstract-sector ->
physical-species bridge, the way the theta-bar structured admission
treated theta: decompose into derived support + provably-vacuous
convention choices + the one irreducible residual, then show the
residual carries no number, selector, or structural choice.

  A. Surface (interface to the gate note): the one-component staggered
     operator D on the 4^3 torus; dim ker D = 8; Hamming grading
     1+3+3+1; the lattice C_3[111] rotation U_R; the staggered
     chirality eps(x) = (-1)^(x1+x2+x3).

  B. Derived support (reproduced, the gate-note algebraic clause): the
     hw=1 triplet is three orthogonal, C_3-connected states in one
     Hilbert space; the algebra generated by (T_1,T_2,T_3, C_3)|_hw=1
     is M_3(C) (dim 9, scalar commutant => irreducible, no proper
     exact quotient).  The carrier STRUCTURE is derived, not admitted.

  C. Within-triplet naming vacuity (the landed labeling no-go,
     reproduced): the three hw=1 states form a SINGLE C_3 orbit, and a
     generic C_3-equivariant Hermitian equipartitions
     (diag(H) = Tr(H)/3), so no structure-derived functional separates
     the three corners.  Which corner is e/mu/tau is a vacuous
     convention.

  D. Carrier-triplet vacuity (NEW): the staggered chirality eps
     satisfies eps D eps = -D (preserves ker D), COMMUTES with the C_3
     rotation U_R, and maps the hw=1 triplet bijectively onto the hw=2
     triplet (the (pi,pi,pi) corner shift hw_k <-> hw_(3-k)).  Hence
     eps is a UNITARY C_3-INTERTWINER between the two candidate
     carriers: they are unitarily equivalent as C_3-representations
     (identical M_3(C), identical 3-cycle orientation).  The choice of
     which Hamming triplet is "the generations" therefore supplies no
     structural or numerical content -- it is naming-class, not
     input-class.

  E. The irreducible residual is contentless at the tested C_3 grade:
     after (B) derived and (C),(D) vacuous, the species bridge is
     exactly ONE interpretive identification (the derived 3-state
     irreducible C_3-structure IS what physics calls fermion generations
     at that grade).  Under the C_3 relabeling and eps carrier-swap
     symmetries tested here, it supplies no tested structural-selection
     bit: no number, no selector, no ordering, no weight.  It is the
     same C_3-grade identification class as the universal
     abstract->physical identification (abstract su(3) -> physical
     color) present in gauge theory.

PASS/FAIL per check; RESIDUAL (declared-open) lines at point of use.
Final line: TOTAL: PASS=<n> FAIL=<m>.
"""

import pathlib
import re

import numpy as np

L = 4
N = L ** 3
TOL = 1e-9

_pass = 0
_fail = 0


def check(num, desc, ok, detail=""):
    global _pass, _fail
    tag = "PASS" if ok else "FAIL"
    if ok:
        _pass += 1
    else:
        _fail += 1
    line = f"[{tag}] ({num:02d}) {desc}"
    if detail:
        line += f"  [{detail}]"
    print(line)


def residual(msg):
    print(f"RESIDUAL (declared-open): {msg}")


DOCS = pathlib.Path(__file__).resolve().parent.parent / "docs"


def doc_text(name):
    raw = (DOCS / name).read_text(encoding="utf-8")
    raw = re.sub(r"^\s*>\s?", "", raw, flags=re.M)
    return " ".join(raw.split())


def idx(x1, x2, x3):
    return (x1 % L) + L * ((x2 % L) + L * (x3 % L))


def sites():
    for x3 in range(L):
        for x2 in range(L):
            for x1 in range(L):
                yield (x1, x2, x3)


SITES = list(sites())
EMU = [(1, 0, 0), (0, 1, 0), (0, 0, 1)]


def eta_ks(x, mu):
    if mu == 0:
        return 1
    if mu == 1:
        return (-1) ** (x[0] % 2)
    return (-1) ** ((x[0] + x[1]) % 2)


print("=" * 72)
print("Species bridge minimum decomposition: derived support + two vacuities")
print("=" * 72)

# ===================== A. surface =====================================
print("\n--- A. gate-note surface reconstruction")

D = np.zeros((N, N))
for x in SITES:
    for mu, e in enumerate(EMU):
        xp = tuple(x[k] + e[k] for k in range(3))
        xm = tuple(x[k] - e[k] for k in range(3))
        D[idx(*x), idx(*xp)] += 0.5 * eta_ks(x, mu)
        D[idx(*x), idx(*xm)] -= 0.5 * eta_ks(x, mu)

sv = np.linalg.svd(D, compute_uv=False)
ker_dim = int(np.sum(sv < 1e-9))
corners = [(n1, n2, n3) for n1 in (0, 1) for n2 in (0, 1) for n3 in (0, 1)]
PHI = []
for (n1, n2, n3) in corners:
    phi = np.array([(-1.0) ** (n1 * x[0] + n2 * x[1] + n3 * x[2])
                    for x in SITES])
    PHI.append(phi / np.linalg.norm(phi))
PHI = np.column_stack(PHI)
hw = [sum(c) for c in corners]
ok = (np.allclose(D, -D.T) and ker_dim == 8
      and np.linalg.norm(D @ PHI) < TOL
      and [hw.count(k) for k in range(4)] == [1, 3, 3, 1])
check(1, "staggered surface: D real antisymmetric, dim ker D = 8, exact "
         "corner basis, Hamming grading 1+3+3+1", ok)

UR = np.zeros((N, N))
for x in SITES:
    xr = (x[1], x[2], x[0])
    UR[idx(*x), idx(*xr)] = 1.0
EPS = np.diag([(-1.0) ** (sum(x) % 2) for x in SITES])
Tmat = []
for mu, e in enumerate(EMU):
    T = np.zeros((N, N))
    for x in SITES:
        xp = tuple(x[k] + e[k] for k in range(3))
        T[idx(*x), idx(*xp)] = 1.0
    Tmat.append(T)
ok = (np.linalg.norm(D @ (UR @ PHI)) < TOL
      and np.allclose(UR @ UR @ UR, np.eye(N)))
check(2, "lattice C_3[111] rotation U_R (U_R^3 = I) preserves ker D; "
         "staggered chirality eps = diag((-1)^sum x) built", ok)

# ===================== B. derived support =============================
print("\n--- B. derived support: hw=1 carrier is M_3(C) (gate-note clause)")

V = PHI                                  # corner basis = ON kernel basis
trips = []
for j in range(8):
    v = V[:, j]
    trip = tuple(int(round(v.conj() @ (T @ v))) for T in Tmat)
    trips.append(trip)
hw1_cols = [j for j in range(8) if hw[j] == 1]
hw2_cols = [j for j in range(8) if hw[j] == 2]
# order hw=1 by which axis carries the -1 character
hw1 = [None, None, None]
for j in hw1_cols:
    hw1[trips[j].index(-1)] = V[:, j]
W1 = np.column_stack(hw1)
tmu1 = [W1.conj().T @ T @ W1 for T in Tmat]
c3_1 = W1.conj().T @ UR @ W1


def algebra_dim(gens):
    basis = [np.eye(3, dtype=complex)] + [g.astype(complex) for g in gens]
    dim = np.linalg.matrix_rank(np.array([m.flatten() for m in basis]),
                                tol=1e-9)
    while True:
        prods = [x @ y for x in basis for y in basis]
        stack = np.array([m.flatten() for m in basis + prods])
        _, s_, vt_ = np.linalg.svd(stack)
        nd = int(np.sum(s_ > 1e-9))
        if nd == dim:
            return dim
        basis = [vt_[i].reshape(3, 3) for i in range(nd)]
        dim = nd


def commutant_dim(gens):
    rows = []
    for g in gens:
        gc = g.astype(complex)
        rows.append(np.kron(gc, np.eye(3)) - np.kron(np.eye(3), gc.T))
    M = np.vstack(rows)
    return 9 - np.linalg.matrix_rank(M, tol=1e-9)


dim1 = algebra_dim(tmu1 + [c3_1])
comm1 = commutant_dim(tmu1 + [c3_1])
orth1 = np.allclose(W1.conj().T @ W1, np.eye(3))
ok = (dim1 == 9 and comm1 == 1 and orth1)
check(3, "derived support reproduced: the hw=1 triplet is 3 orthogonal "
         "C_3-connected states; algebra(T_1,T_2,T_3,C_3)|hw=1 = M_3(C) "
         "(dim 9, scalar commutant => irreducible, no proper exact "
         "quotient). The carrier STRUCTURE is derived, not admitted",
      ok, f"algebra dim = {dim1}, commutant dim = {comm1}")

# ===================== C. within-triplet naming vacuity ==============
print("\n--- C. within-triplet naming vacuity (landed labeling no-go)")

# single C_3 orbit: c3_1 is a 3-cycle on the corner basis
is_3cycle = (np.allclose(np.abs(c3_1) @ np.ones(3), np.ones(3))
             and np.allclose(np.abs(c3_1).sum(0), np.ones(3))
             and np.allclose(c3_1 @ c3_1 @ c3_1, np.eye(3)))
# generic C_3-equivariant Hermitian equipartitions: diag = Tr/3
rng = np.random.default_rng(17)
Hr = rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3))
Hr = Hr + Hr.conj().T
Heq = sum(np.linalg.matrix_power(c3_1, k) @ Hr
          @ np.linalg.matrix_power(c3_1.conj().T, k) for k in range(3)) / 3
equipart = np.allclose(np.diag(Heq), np.trace(Heq) / 3 * np.ones(3))
ok = is_3cycle and equipart
check(4, "within-triplet naming is vacuous: the hw=1 states form a "
         "SINGLE C_3 orbit (C_3 is a 3-cycle), and a generic "
         "C_3-equivariant Hermitian equipartitions (diag = Tr/3), so no "
         "structure-derived functional separates the corners -- which "
         "corner is e/mu/tau is convention (labeling no-go reproduced)",
      ok)

# ===================== D. carrier-triplet vacuity (NEW) ==============
print("\n--- D. carrier-triplet vacuity: eps is a unitary C_3-intertwiner")

eps_chir = np.allclose(EPS @ D @ EPS, -D)
eps_ker = np.linalg.norm(D @ (EPS @ PHI)) < 1e-9
eps_comm_UR = np.allclose(EPS @ UR, UR @ EPS)
check(5, "the staggered chirality eps satisfies eps D eps = -D "
         "(preserves ker D) and COMMUTES with the C_3 rotation U_R "
         "([eps, U_R] = 0)", eps_chir and eps_ker and eps_comm_UR)

# eps maps hw=1 corners to hw=2 corners (the (pi,pi,pi) shift)
maps_hw = True
for j in hw1_cols:
    w = EPS @ V[:, j]
    new = tuple(int(round(w.conj() @ (T @ w))) for T in Tmat)
    if sum(1 for t in new if t == -1) != 2:    # image is hw=2
        maps_hw = False
check(6, "eps maps the hw=1 triplet bijectively onto the hw=2 triplet "
         "(the (pi,pi,pi) corner shift hw_k <-> hw_(3-k))", maps_hw)

# both triplets: same C_3 structure, and eps is a unitary intertwiner
hw2 = [None, None, None]
for j in hw2_cols:
    # order hw=2 by which axis carries the +1 character (complement)
    hw2[trips[j].index(1)] = V[:, j]
W2 = np.column_stack(hw2)
c3_2 = W2.conj().T @ UR @ W2
dim2 = algebra_dim([W2.conj().T @ T @ W2 for T in Tmat] + [c3_2])
comm2 = commutant_dim([W2.conj().T @ T @ W2 for T in Tmat] + [c3_2])
# unitary intertwiner: eps maps span(hw1) onto span(hw2), and
# conjugating U_R by that map preserves the 3-cycle (same orientation)
EH = W2.conj().T @ EPS @ W1               # eps as a 3x3 map hw1 -> hw2
unit_inter = (np.allclose(EH @ EH.conj().T, np.eye(3))
              and np.allclose(EH @ c3_1, c3_2 @ EH))
ok = (dim2 == 9 and comm2 == 1 and unit_inter)
check(7, "the two candidate carriers are UNITARILY EQUIVALENT as "
         "C_3-representations: hw=2 is also M_3(C) (dim 9, scalar "
         "commutant), and eps restricts to a unitary intertwiner "
         "EH with EH C_3|hw1 = C_3|hw2 EH (same orientation) -- the "
         "carrier-triplet choice supplies NO structural or numerical "
         "content", ok, f"hw2 algebra dim = {dim2}, commutant = {comm2}")

# ===================== E. residual is C_3-grade contentless ===========
print("\n--- E. the irreducible residual carries no tested C_3-grade content")

# Contentlessness is CARRIED by check 4 (single C_3 orbit + equipartition)
# and check 7 (unitary eps-intertwiner). Here we make the
# "no orbit-separating functional" content PROBATIVE -- and honest about
# what forces it. A corner-distinguishing functional (the diagonal
# "weight on corner k") DOES separate the corners for a generic operator,
# but is forced EQUAL across corners once the operator is required to be
# C_3-equivariant (orbit-averaged): so the constancy is due to
# orbit-averaging, NOT to a trivial invariance.
Hgen = rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3))
Hgen = Hgen + Hgen.conj().T
diag_raw = np.real(np.diag(Hgen))                       # generic readout
Heq2 = sum(np.linalg.matrix_power(c3_1, k) @ Hgen
           @ np.linalg.matrix_power(c3_1.conj().T, k)
           for k in range(3)) / 3                        # C_3-equivariant
diag_eq = np.real(np.diag(Heq2))
sep_raw = (diag_raw.max() - diag_raw.min()) > 1e-3       # generic separates
forced_eq = np.allclose(diag_eq, diag_eq.mean())         # equivariant equal
# the eps carrier-swap, pulled back to hw1 via the intertwiner, is the
# IDENTITY: carrier-vacuity is from check 7, not from an automorphism test.
eps_auto = EH.conj().T @ EH
ok = (sep_raw and forced_eq and np.allclose(eps_auto, np.eye(3)))
check(8, "no C_3-EQUIVARIANT functional separates the corners: the "
         "corner-weight diagonal SEPARATES corners for a generic "
         "operator but is forced EQUAL once the operator is "
         "C_3-equivariant (orbit-averaged) -- the constancy is from "
         "orbit-averaging, not trivial invariance. The eps carrier-swap "
         "pulled back via the intertwiner is the IDENTITY (EH^dag EH = "
         "I), so carrier-vacuity is carried by check 7", ok,
      f"generic diag spread = {diag_raw.max() - diag_raw.min():.2f}, "
      f"equivariant spread = {diag_eq.max() - diag_eq.min():.1e}")

# the three tested C_3-grade input-types are each discharged by a COMPUTED witness (not by
# counting dict keys): number -> the carrier is the rigid regular C_3-rep
# (3 fixed integer character triples, no free modulus); selector ->
# unitary carrier-equivalence (7) + single orbit (4); ordering/weight ->
# equivariant equipartition (8).
char_triples = sorted(tuple(int(round(np.real(W1[:, j].conj()
                       @ (T @ W1[:, j])))) for T in Tmat)
                      for j in range(3))
number_absent = (char_triples == sorted([(-1, 1, 1), (1, -1, 1),
                                          (1, 1, -1)]))
selector_vacuous = unit_inter and is_3cycle
ordering_weight_vacuous = forced_eq and equipart
ok = (number_absent and selector_vacuous and ordering_weight_vacuous)
check(9, "each tested C_3-grade input-type is discharged by a computed witness: NUMBER -> "
         "the carrier is the rigid regular C_3-rep (3 fixed integer "
         "character triples (-1,1,1)/(1,-1,1)/(1,1,-1), no free "
         "modulus); SELECTOR -> unitary carrier-equivalence (7) + single "
         "orbit (4); ORDERING/WEIGHT -> equivariant equipartition (8). "
         "The bridge supplies none at this grade -- a pure interpretive identification "
         "of the same C_3-structural class as abstract-"
         "su(3) -> physical color", ok)

# ===================== F. interfaces + residuals =====================
print("\n--- F. interface pins and residuals")

labeling = doc_text("STAGGERED_DIRAC_SUBSTEP4_LABELING_NO_GO_NOTE"
                    "_2026-05-17.md")
gate = doc_text("STAGGERED_DIRAC_REALIZATION_GATE_NOTE_2026-05-03.md")
ok = ("orbit-equivariance" in labeling
      and ("M_3(C)" in gate or "M_3(C)" in gate.replace("C)", "C)")))
check(10, "interface pins: the labeling no-go's orbit-equivariance "
          "invariant (within-triplet naming) and the gate note's hw=1 "
          "M_3(C) algebraic clause (derived carrier structure) are "
          "present in the live notes", ok)
residual("the abstract-sector -> physical-species interpretive "
         "identification itself is the irreducible residual of "
         "AC_phi_lambda(iii): contentless at the tested C_3-structural "
         "grade (this note), but "
         "still an interpretive bridge of the same C_3-grade class as the "
         "universal abstract->physical identification -- NOT derived away, "
         "only shown to carry no tested number/selector/structural choice.")
residual("the carrier-triplet vacuity consumes the staggered surface at "
         "the gate-note grade (the hw structure and U_R/eps operators); "
         "across-fermion-type alignment (CKM/PMNS) is a SEPARATE "
         "residual, not addressed here.")
residual("inherited gate-note residuals remain at their declared grades "
         "(kinetic-class premise, spin-statistics support tier, "
         "boundary-holonomy convention).")

print()
print(f"TOTAL: PASS={_pass} FAIL={_fail}")
print("VERDICT: the species bridge AC_phi_lambda(iii) decomposes into "
      "derived support (the hw=1 carrier is M_3(C), irreducible, no "
      "proper quotient) + two vacuities (within-triplet naming: single "
      "C_3 orbit, equipartition; carrier-triplet choice: hw=1 and hw=2 "
      "unitarily equivalent via the chirality eps, a C_3-intertwiner) + "
      "one irreducible residual that is contentless at the tested "
      "C_3-structural grade (under the C_3 relabeling and eps "
      "carrier-swap symmetries tested here; supplies no tested "
      "number/selector/ordering/weight) -- the same C_3-grade class as "
      "the universal abstract->physical identification. The minimum form "
      "of AC_phi_lambda(iii) is a single C_3-grade contentless "
      "interpretive identification. Nothing retired; no audit status set.")
raise SystemExit(0 if _fail == 0 else 1)
