"""Current-bank no-go for deriving the Route-2 single-adjoint-line selector.

Block37 isolated a conditional primitive: if the source domain supplies one
typed adjoint line and the E-center readout uses its complement rank, then the
Route-2 E-side value follows exactly.  This runner checks whether the current
SU(3)-equivariant color/source bank can supply such a line.

It cannot: the adjoint representation has no invariant vector, its commutant
is scalar, and its invariant idempotent projectors have rank 0 or 8 only.  A
rank-1 line or rank-7 complement therefore requires a non-invariant typed
source datum not present in the current bank.
"""
from __future__ import annotations

from itertools import permutations
from pathlib import Path

import sympy as sp

PASS = 0
FAIL = 0

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
NOTE = DOCS / "QUARK_ROUTE2_SINGLE_ADJOINT_LINE_CURRENT_BANK_NO_GO_NOTE_2026-06-21.md"
SOURCE_BRIDGE = DOCS / "QUARK_ROUTE2_SOURCE_DOMAIN_BRIDGE_NO_GO_NOTE_2026-04-28.md"
RCONN = DOCS / "RCONN_DERIVED_NOTE.md"
KAPPA = DOCS / "RCONN_KAPPA_EW_REGISTER_NOT_READ_COLOR_TRACE_OPEN_GATE_NOTE_2026-06-08.md"
FIERZ = DOCS / "EW_CURRENT_FIERZ_CHANNEL_DECOMPOSITION_NOTE_2026-05-01.md"
COLOR_SINGLET = DOCS / "CL3_QUARK_ANTIQUARK_COLOR_SINGLET_THEOREM_NOTE_2026-05-02.md"


def check(name: str, cond: bool, detail: str = "") -> bool:
    global PASS, FAIL
    print(f"[{'PASS' if cond else 'FAIL'}] {name}")
    if detail:
        print(f"       {detail}")
    PASS += int(bool(cond))
    FAIL += int(not cond)
    return bool(cond)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def perm_sign(p: tuple[int, int, int]) -> int:
    inversions = 0
    for i in range(3):
        for j in range(i + 1, 3):
            if p[i] > p[j]:
                inversions += 1
    return -1 if inversions % 2 else 1


def su3_structure_constants() -> dict[tuple[int, int, int], sp.Expr]:
    sqrt3 = sp.sqrt(3)
    base = {
        (1, 2, 3): sp.Integer(1),
        (1, 4, 7): sp.Rational(1, 2),
        (1, 5, 6): -sp.Rational(1, 2),
        (2, 4, 6): sp.Rational(1, 2),
        (2, 5, 7): sp.Rational(1, 2),
        (3, 4, 5): sp.Rational(1, 2),
        (3, 6, 7): -sp.Rational(1, 2),
        (4, 5, 8): sqrt3 / 2,
        (6, 7, 8): sqrt3 / 2,
    }
    out: dict[tuple[int, int, int], sp.Expr] = {}
    for key, value in base.items():
        for p in permutations(key):
            out[p] = perm_sign(p) * value
    return out


def adjoint_matrices() -> list[sp.Matrix]:
    f = su3_structure_constants()
    mats: list[sp.Matrix] = []
    for a in range(1, 9):
        mat = sp.zeros(8, 8)
        for b in range(1, 9):
            for c in range(1, 9):
                mat[b - 1, c - 1] = f.get((a, c, b), sp.Integer(0))
        mats.append(mat)
    return mats


def main() -> int:
    print("ROUTE-2 SINGLE-ADJOINT-LINE SELECTOR: CURRENT-BANK NO-GO")
    print("=" * 78)

    for path in (NOTE, SOURCE_BRIDGE, RCONN, KAPPA, FIERZ, COLOR_SINGLET):
        check(f"{path.relative_to(ROOT)} exists", path.exists())

    note = read(NOTE)
    source_bridge = read(SOURCE_BRIDGE)
    rconn = read(RCONN)
    kappa = read(KAPPA)
    fierz = read(FIERZ)
    color_singlet = read(COLOR_SINGLET)

    print("\nA. Exact SU(3) adjoint representation checks")
    mats = adjoint_matrices()
    stacked = sp.Matrix.vstack(*mats)
    invariant_vector_dim = 8 - stacked.rank()
    check(
        "the adjoint representation has no invariant line vector",
        invariant_vector_dim == 0,
        f"stacked rank={stacked.rank()}, invariant-vector dimension={invariant_vector_dim}",
    )

    vars_ = sp.symbols("x0:64")
    X = sp.Matrix(8, 8, vars_)
    equations = []
    for mat in mats:
        equations.extend(list(mat * X - X * mat))
    coeffs, _ = sp.linear_eq_to_matrix(equations, vars_)
    commutant_dim = 64 - coeffs.rank()
    nullspace = coeffs.nullspace()
    basis_matrix = sp.Matrix(8, 8, nullspace[0])
    basis_is_identity = (
        len(nullspace) == 1
        and all(basis_matrix[i, j] == 0 for i in range(8) for j in range(8) if i != j)
        and len({basis_matrix[i, i] for i in range(8)}) == 1
        and basis_matrix[0, 0] != 0
    )
    check(
        "the adjoint commutant is one-dimensional and generated by identity",
        commutant_dim == 1 and basis_is_identity,
        f"linear-system rank={coeffs.rank()}, commutant_dim={commutant_dim}",
    )

    possible_invariant_projector_ranks = {0, 8}
    check(
        "SU(3)-equivariant idempotent projectors on the adjoint have only ranks 0 or 8",
        1 not in possible_invariant_projector_ranks and 7 not in possible_invariant_projector_ranks,
        f"possible ranks={sorted(possible_invariant_projector_ranks)}",
    )

    print("\nB. Route-2 selector consequence")
    check("a line selector would need rank 1 and complement rank 7", 8 - 1 == 7)
    check(
        "the current SU(3)-equivariant bank cannot supply that rank pattern",
        7 not in possible_invariant_projector_ranks,
        "rank-7 complement is non-invariant unless a typed source line is added",
    )

    print("\nC. Current source-bank text firewall")
    absent_terms = (
        "single-adjoint-line",
        "single adjoint line",
        "codimension-one adjoint complement",
        "rank-7 adjoint complement",
    )
    bank = "\n".join([source_bridge, rconn, kappa, fierz, color_singlet])
    check("current source bank does not name the single-adjoint-line primitive", not any(term in bank for term in absent_terms))
    check(
        "source-domain bridge note keeps Rconn-to-center-ratio bridge absent",
        "There is no current typed edge" in source_bridge
        and "R_conn = 8/9 -> c_TE" in source_bridge,
    )
    check(
        "Rconn note keeps 8/9 as F_adj support rather than a Route-2 line selector",
        "exact `8/9` support remains available as `F_adj`" in rconn
        and "gamma_E(center)" not in rconn,
    )
    check(
        "kappa note keeps color-trace readout/weighting selector open",
        "does not close the `κ_EW = 0`" in kappa
        and "physical weighting or observable-bridge rule" in " ".join(kappa.split()),
    )
    check(
        "Fierz note supplies singlet/adjoint channel algebra, not a line in the adjoint",
        "adjoint-channel" in fierz
        and "singlet-channel" in fierz
        and "N_c^2 − 1" in fierz
        and "single adjoint line" not in fierz,
    )
    check(
        "color-singlet note selects singlet/traceless split, not an adjoint line",
        "1 ⊕ 8" in color_singlet
        and "8-dimensional" in color_singlet
        and "single adjoint line" not in color_singlet,
    )

    print("\nD. Note/status firewall")
    forbidden = (
        "proposed_" + "retained",
        "proposed_" + "promoted",
        "would become " + "retained",
        "promoted to " + "retained",
        "retained on the actual " + "surface",
        "Nature-grade " + "closure",
    )
    check("note marks actual status as no-go", "**actual_current_surface_status:** no-go" in note)
    check("note states non-invariant future source line remains open", "non-invariant typed source line remains open" in note)
    check("note avoids retained/proposal overclaim phrases", not any(token in note for token in forbidden))

    print(f"\nTOTAL: PASS={PASS} FAIL={FAIL}")
    print(
        "VERDICT: current-bank no-go.  The SU(3)-equivariant adjoint source bank has no invariant "
        "line and no rank-7 invariant complement projector; its commutant is scalar.  Therefore the "
        "single-adjoint-line selector isolated as conditional support requires a new non-invariant "
        "typed source datum, not merely the current F_adj/Rconn/Fierz/color-singlet bank."
    )
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
