#!/usr/bin/env python3
"""Cycle 256: exhaustive endpoint-star incident-CAR dressing tournament.

Search the complete radius-1 Pauli grammar around the endpoints of each edge
of the Cycle-252 42-role stabilizer code.  Matter-X incidence is fixed to the
two edge endpoints; arbitrary M-Z, R-X/Z, and incident G/F-X/Z dressings are
then filtered by the local-code centralizer and exact space-group covariance.
Candidates are quotiented by the local stabilizer group before the complete
incident/disjoint symplectic tournament.

The resulting negative, if any, is only about this finite grammar.  It is not
a general local-fermionization no-go and carries no axiom pressure.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, product
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import coherent_even_odd_sector_join_cycle252_2026_07_17 as c252
import common_matter_field_coin_family_cycle219_2026_07_16 as c219
import exact_3d_higher_form_bosonization_cycle235_2026_07_17 as c235
import spatial_car_contact_seam_form_factor_cycle230_2026_07_17 as c230

NOTE = (
    ROOT
    / "docs/work_history/repo/review_feedback/"
    "INCIDENT_CAR_AUXILIARY_DRESSING_CYCLE256_NOTE_2026-07-17.md"
)

PASS = 0
FAIL = 0


def check(label: str, condition: bool, detail: object = "") -> None:
    global PASS, FAIL
    if condition:
        PASS += 1
        print("PASS", label, "::", detail)
    else:
        FAIL += 1
        print("FAIL", label, "::", detail)


def note_contract() -> None:
    if not NOTE.exists():
        check("the Cycle-256 note exists", False, NOTE)
        return
    text = " ".join(NOTE.read_text(encoding="utf-8").lower().split())
    required = (
        "authority: none",
        "audit: unset",
        "endpoint-star",
        "radius-1",
        "stabilizer group generated by the declared local checks",
        "occupation-parity incidence",
        "all 24 proper-cubic frames",
        "held-out l=6",
        "no marked reference",
        "radius-2",
        "beta=-0.3",
        "g=0.37",
        "topological joins",
        "mass seam",
        "n1 — alternative routes",
        "n2 — condition independence",
        "n3 — hidden-condition scan",
        "n4 — residual matching",
        "n5 — resolution audit",
        "n6 — partial-closure scan",
        "n7 — steelman",
        "n8 — cross-cycle echo",
        "compiler layers are not physical time",
        "no axiom pressure",
    )
    missing = tuple(item for item in required if item not in text)
    check("the Cycle-256 note preserves its scope, N1-N8, and time contracts", not missing, missing)


def pauli_vector(pauli: c235.Pauli, qubits: int) -> int:
    return pauli.x | (pauli.z << qubits)


def vector_pauli(vector: int, qubits: int) -> c235.Pauli:
    mask = (1 << qubits) - 1
    return c235.Pauli(x=vector & mask, z=(vector >> qubits) & mask)


def rref_nullspace(rows: list[int], columns: int) -> tuple[list[int], list[int]]:
    """Return a reduced row basis and a basis for its GF(2) nullspace."""
    work = [int(row) for row in rows if row]
    rank = 0
    pivots: list[int] = []
    for column in range(columns):
        source = next(
            (index for index in range(rank, len(work)) if (work[index] >> column) & 1),
            None,
        )
        if source is None:
            continue
        work[rank], work[source] = work[source], work[rank]
        pivot = work[rank]
        for index in range(len(work)):
            if index != rank and ((work[index] >> column) & 1):
                work[index] ^= pivot
        pivots.append(column)
        rank += 1
        if rank == len(work):
            break
    reduced = work[:rank]
    pivot_set = set(pivots)
    basis = []
    for free in range(columns):
        if free in pivot_set:
            continue
        vector = 1 << free
        for row, pivot in zip(reduced, pivots):
            if (row >> free) & 1:
                vector |= 1 << pivot
        basis.append(vector)
    assert all((row & vector).bit_count() % 2 == 0 for row in rows for vector in basis)
    return reduced, basis


def span_reducer(rows: list[int]) -> dict[int, int]:
    pivots: dict[int, int] = {}
    for source in rows:
        row = int(source)
        while row:
            pivot = row.bit_length() - 1
            if pivot in pivots:
                row ^= pivots[pivot]
            else:
                pivots[pivot] = row
                break
    return pivots


def quotient_remainder(vector: int, pivots: dict[int, int]) -> int:
    result = int(vector)
    while result:
        pivot = result.bit_length() - 1
        if pivot not in pivots:
            lower = [key for key in pivots if key < pivot and ((result >> key) & 1)]
            if not lower:
                break
            pivot = max(lower)
        result ^= pivots[pivot]
    return result


def local_constraints(code: c252.JoinCode) -> list[c235.Pauli]:
    return code.combined_gauss + code.charge_moves + code.frame_moves + code.frame_flat


def natural_hopping(code: c252.JoinCode, edge: int) -> c235.Pauli:
    left, right = code.graph.edges[edge][:2]
    return c235.Pauli(
        x=(1 << (code.m_offset + left)) | (1 << (code.m_offset + right)),
        z=(1 << (code.g_offset + edge)) | (1 << (code.f_offset + edge)),
    )


def endpoint_star_columns(
    code: c252.JoinCode, edge: int
) -> tuple[list[c235.Pauli], list[tuple[str, int]]]:
    """Complete radius-1 grammar with fixed matter-X endpoint incidence."""
    vertices = set(code.graph.edges[edge][:2])
    edges = {incident for vertex in vertices for incident in code.graph.incident[vertex]}
    columns: list[c235.Pauli] = []
    labels: list[tuple[str, int]] = []
    for vertex in sorted(vertices):
        entries = (
            ("MZ", c235.Pauli(z=1 << (code.m_offset + vertex))),
            ("RX", c235.Pauli(x=1 << (code.r_offset + vertex))),
            ("RZ", c235.Pauli(z=1 << (code.r_offset + vertex))),
        )
        for name, pauli in entries:
            labels.append((name, vertex))
            columns.append(pauli)
    for incident in sorted(edges):
        for role, offset in (("G", code.g_offset), ("F", code.f_offset)):
            labels.extend(((role + "X", incident), (role + "Z", incident)))
            columns.extend(
                (
                    c235.Pauli(x=1 << (offset + incident)),
                    c235.Pauli(z=1 << (offset + incident)),
                )
            )
    return columns, labels


def translation_maps(
    code: c252.JoinCode, displacement: tuple[int, int, int]
) -> tuple[list[int], list[int]]:
    length = code.graph.length
    vertex_map = []
    for cell, role in code.graph.vertices:
        moved = tuple((cell[axis] + displacement[axis]) % length for axis in range(3))
        vertex_map.append(code.graph.vertex_index[(moved, role)])
    edge_map = [
        code.graph.edge_lookup[frozenset((vertex_map[left], vertex_map[right]))]
        for left, right, _, _ in code.graph.edges
    ]
    return vertex_map, edge_map


def permute_pauli(
    code: c252.JoinCode,
    pauli: c235.Pauli,
    vertex_map: list[int],
    edge_map: list[int],
) -> c235.Pauli:
    x = 0
    z = 0
    for offset, count, mapping in (
        (code.m_offset, code.vertices, vertex_map),
        (code.g_offset, code.edges, edge_map),
        (code.f_offset, code.edges, edge_map),
        (code.r_offset, code.vertices, vertex_map),
    ):
        for source in range(count):
            if (pauli.x >> (offset + source)) & 1:
                x |= 1 << (offset + mapping[source])
            if (pauli.z >> (offset + source)) & 1:
                z |= 1 << (offset + mapping[source])
    return c235.Pauli(x=x, z=z)


def compose_maps(first: list[int], second: list[int]) -> list[int]:
    """Map obtained by applying second and then first."""
    return [first[second[index]] for index in range(len(second))]


def edge_stabilizer_maps(
    code: c252.JoinCode, seed: int
) -> list[tuple[list[int], list[int]]]:
    result = []
    for frame in c235.proper_cubic_frames():
        frame_vertices, frame_edges = c235.graph_frame_maps(code.graph, frame)
        mapped = frame_edges[seed]
        owner = code.graph.edges[mapped][3]
        recenter_vertices, recenter_edges = translation_maps(
            code, tuple(-value % code.graph.length for value in owner)
        )
        vertex_map = compose_maps(recenter_vertices, frame_vertices)
        edge_map = compose_maps(recenter_edges, frame_edges)
        if edge_map[seed] == seed:
            result.append((vertex_map, edge_map))
    return result


@dataclass
class SeedSpace:
    seed: int
    kind: str
    columns: list[c235.Pauli]
    labels: list[tuple[str, int]]
    null_basis: list[int]
    raw_candidates: list[c235.Pauli]
    quotient_candidates: list[c235.Pauli]
    stabilizer_size: int


def combine_columns(columns: list[c235.Pauli], coefficient: int) -> c235.Pauli:
    x = 0
    z = 0
    for index, pauli in enumerate(columns):
        if (coefficient >> index) & 1:
            x ^= pauli.x
            z ^= pauli.z
    return c235.Pauli(x=x, z=z)


def build_seed_space(code: c252.JoinCode, seed: int) -> SeedSpace:
    columns, labels = endpoint_star_columns(code, seed)
    equations: list[int] = []
    for stabilizer in local_constraints(code):
        row = sum(
            1 << index
            for index, column in enumerate(columns)
            if not column.commutes(stabilizer)
        )
        if row:
            equations.append(row)
    edge_stabilizer = edge_stabilizer_maps(code, seed)
    for vertex_map, edge_map in edge_stabilizer:
        coordinate_rows: dict[tuple[str, int], int] = {}
        for index, column in enumerate(columns):
            moved = permute_pauli(code, column, vertex_map, edge_map)
            for part, difference in (("x", column.x ^ moved.x), ("z", column.z ^ moved.z)):
                while difference:
                    bit = (difference & -difference).bit_length() - 1
                    key = (part, bit)
                    coordinate_rows[key] = coordinate_rows.get(key, 0) ^ (1 << index)
                    difference &= difference - 1
        equations.extend(row for row in coordinate_rows.values() if row)
    _, null_basis = rref_nullspace(equations, len(columns))
    raw_candidates = []
    natural = natural_hopping(code, seed)
    for choice in range(1 << len(null_basis)):
        coefficient = 0
        for index, basis in enumerate(null_basis):
            if (choice >> index) & 1:
                coefficient ^= basis
        candidate = natural @ combine_columns(columns, coefficient)
        raw_candidates.append(c235.Pauli(x=candidate.x, z=candidate.z))

    stabilizer_pivots = span_reducer(
        [pauli_vector(stabilizer, code.total_qubits) for stabilizer in local_constraints(code)]
    )
    representatives: dict[int, c235.Pauli] = {}
    for candidate in raw_candidates:
        remainder = quotient_remainder(pauli_vector(candidate, code.total_qubits), stabilizer_pivots)
        representatives.setdefault(remainder, candidate)
    return SeedSpace(
        seed=seed,
        kind=code.graph.edges[seed][2],
        columns=columns,
        labels=labels,
        null_basis=null_basis,
        raw_candidates=raw_candidates,
        quotient_candidates=list(representatives.values()),
        stabilizer_size=len(edge_stabilizer),
    )


def candidate_family(
    code: c252.JoinCode, seed: int, candidate: c235.Pauli
) -> tuple[list[c235.Pauli | None], int]:
    family: list[c235.Pauli | None] = [None] * code.edges
    ambiguities = 0
    for frame in c235.proper_cubic_frames():
        frame_vertices, frame_edges = c235.graph_frame_maps(code.graph, frame)
        framed = permute_pauli(code, candidate, frame_vertices, frame_edges)
        mapped_seed = frame_edges[seed]
        owner = code.graph.edges[mapped_seed][3]
        for target_cell in product(range(code.graph.length), repeat=3):
            displacement = tuple(
                (target_cell[axis] - owner[axis]) % code.graph.length for axis in range(3)
            )
            translation_vertices, translation_edges = translation_maps(code, displacement)
            target = translation_edges[mapped_seed]
            moved = permute_pauli(
                code, framed, translation_vertices, translation_edges
            )
            if family[target] is not None and (
                family[target].x != moved.x or family[target].z != moved.z
            ):
                ambiguities += 1
            family[target] = moved
    return family, ambiguities


@dataclass
class TournamentResult:
    raw_families_covered: int
    families_tested: int
    solutions: list[tuple[int, int]]
    best_incident_failures: int
    best_disjoint_failures: int
    best_total_failures: int
    best_pair: tuple[int, int]
    incident_relations: int
    disjoint_relations: int
    covariance_ambiguities: int
    quotient_residual_table: list[dict[str, int]]


def run_tournament(
    code: c252.JoinCode, internal: SeedSpace, outer: SeedSpace
) -> TournamentResult:
    internal_families = []
    outer_families = []
    ambiguities = 0
    for candidate in internal.quotient_candidates:
        family, failures = candidate_family(code, internal.seed, candidate)
        internal_families.append(family)
        ambiguities += failures
    for candidate in outer.quotient_candidates:
        family, failures = candidate_family(code, outer.seed, candidate)
        outer_families.append(family)
        ambiguities += failures

    pair_rows = []
    for left, right in combinations(range(code.edges), 2):
        shared = len(
            set(code.graph.edges[left][:2]) & set(code.graph.edges[right][:2])
        )
        pair_rows.append((left, right, shared == 1))
    incident_relations = sum(wanted for _, _, wanted in pair_rows)
    disjoint_relations = len(pair_rows) - incident_relations
    solutions = []
    residual_table = []
    best = (10**9, 10**9, 10**9, (0, 0))
    for internal_index, internal_family in enumerate(internal_families):
        for outer_index, outer_family in enumerate(outer_families):
            family = [
                internal_family[edge]
                if code.graph.edges[edge][2] == "internal_triangle"
                else outer_family[edge]
                for edge in range(code.edges)
            ]
            incident_failures = 0
            disjoint_failures = 0
            for left, right, wanted in pair_rows:
                actual = not family[left].commutes(family[right])
                if actual != wanted:
                    if wanted:
                        incident_failures += 1
                    else:
                        disjoint_failures += 1
            total = incident_failures + disjoint_failures
            residual_table.append(
                {
                    "internal_class": internal_index,
                    "outer_class": outer_index,
                    "incident_failures": incident_failures,
                    "disjoint_failures": disjoint_failures,
                    "total_failures": total,
                }
            )
            if total < best[0]:
                best = (total, incident_failures, disjoint_failures, (internal_index, outer_index))
            if total == 0:
                solutions.append((internal_index, outer_index))
    return TournamentResult(
        raw_families_covered=len(internal.raw_candidates) * len(outer.raw_candidates),
        families_tested=len(internal_families) * len(outer_families),
        solutions=solutions,
        best_incident_failures=best[1],
        best_disjoint_failures=best[2],
        best_total_failures=best[0],
        best_pair=best[3],
        incident_relations=incident_relations,
        disjoint_relations=disjoint_relations,
        covariance_ambiguities=ambiguities,
        quotient_residual_table=residual_table,
    )


def grammar_and_tournament_controls() -> tuple[dict[int, tuple[SeedSpace, SeedSpace]], TournamentResult]:
    spaces: dict[int, tuple[SeedSpace, SeedSpace]] = {}
    census = []
    for length in (3, 4, 5, 6):
        code = c252.join_code(length)
        internal_seed = next(
            edge for edge, row in enumerate(code.graph.edges) if row[2] == "internal_triangle"
        )
        outer_seed = next(
            edge for edge, row in enumerate(code.graph.edges) if row[2] == "outer_square"
        )
        internal = build_seed_space(code, internal_seed)
        outer = build_seed_space(code, outer_seed)
        spaces[length] = (internal, outer)
        census.append(
            {
                "L": length,
                "columns": (len(internal.columns), len(outer.columns)),
                "edge_stabilizers": (internal.stabilizer_size, outer.stabilizer_size),
                "centralizer_covariant_dimensions": (
                    len(internal.null_basis),
                    len(outer.null_basis),
                ),
                "raw_seed_candidates": (
                    len(internal.raw_candidates),
                    len(outer.raw_candidates),
                ),
                "quotient_seed_candidates": (
                    len(internal.quotient_candidates),
                    len(outer.quotient_candidates),
                ),
                "maximum_seed_weights": (
                    max((candidate.x | candidate.z).bit_count() for candidate in internal.raw_candidates),
                    max((candidate.x | candidate.z).bit_count() for candidate in outer.raw_candidates),
                ),
            }
        )
    check(
        "the complete endpoint-star radius-1 grammar has stable finite dimensions through held-out L=6",
        len({row["columns"] for row in census}) == 1
        and len({row["edge_stabilizers"] for row in census}) == 1
        and len({row["centralizer_covariant_dimensions"] for row in census}) == 1
        and len({row["raw_seed_candidates"] for row in census}) == 1
        and len({row["quotient_seed_candidates"] for row in census}) == 1
        and len({row["maximum_seed_weights"] for row in census}) == 1,
        census,
    )

    code3 = c252.join_code(3)
    internal3, outer3 = spaces[3]
    all_candidates = internal3.raw_candidates + outer3.raw_candidates
    code_preservation_failures = sum(
        not candidate.commutes(stabilizer)
        for candidate in all_candidates
        for stabilizer in local_constraints(code3)
    )
    incidence_failures = 0
    for space in (internal3, outer3):
        endpoints = set(code3.graph.edges[space.seed][:2])
        for candidate in space.raw_candidates:
            matter_x = {
                vertex
                for vertex in range(code3.vertices)
                if (candidate.x >> (code3.m_offset + vertex)) & 1
            }
            incidence_failures += matter_x != endpoints
    check(
        "every enumerated seed preserves all local code constraints and the exact occupation-parity incidence",
        code_preservation_failures == 0 and incidence_failures == 0,
        {
            "code_preservation_failures": code_preservation_failures,
            "occupation_parity_incidence_failures": incidence_failures,
            "matter_X_rule": "exactly the two hopping endpoints",
        },
    )

    tournament = run_tournament(code3, internal3, outer3)
    check(
        "the all-frame and coarse-translation family construction is single-valued with no marked reference or global order",
        tournament.covariance_ambiguities == 0,
        {
            "proper_cubic_frames": 24,
            "coarse_translations": 3**3,
            "covariance_ambiguities": tournament.covariance_ambiguities,
            "marked_reference": False,
            "global_order": False,
        },
    )
    check(
        "no quotient family in the complete radius-1 endpoint-star grammar satisfies every incident and disjoint CAR relation",
        not tournament.solutions,
        tournament.__dict__,
    )
    return spaces, tournament


def radius_two_columns(
    code: c252.JoinCode, edge: int
) -> list[c235.Pauli]:
    """One-step-expanded endpoint ball; counted but not exponentially enumerated."""
    vertices = set(code.graph.edges[edge][:2])
    vertices |= {
        neighbor
        for vertex in tuple(vertices)
        for incident in code.graph.incident[vertex]
        for neighbor in code.graph.edges[incident][:2]
    }
    edges = {incident for vertex in vertices for incident in code.graph.incident[vertex]}
    columns = []
    for vertex in sorted(vertices):
        columns.extend(
            (
                c235.Pauli(z=1 << (code.m_offset + vertex)),
                c235.Pauli(x=1 << (code.r_offset + vertex)),
                c235.Pauli(z=1 << (code.r_offset + vertex)),
            )
        )
    for incident in sorted(edges):
        for offset in (code.g_offset, code.f_offset):
            columns.extend(
                (
                    c235.Pauli(x=1 << (offset + incident)),
                    c235.Pauli(z=1 << (offset + incident)),
                )
            )
    return columns


def centralizer_covariant_dimension(
    code: c252.JoinCode, seed: int, columns: list[c235.Pauli]
) -> int:
    equations = []
    for stabilizer in local_constraints(code):
        row = sum(
            1 << index
            for index, column in enumerate(columns)
            if not column.commutes(stabilizer)
        )
        if row:
            equations.append(row)
    for vertex_map, edge_map in edge_stabilizer_maps(code, seed):
        coordinate_rows: dict[tuple[str, int], int] = {}
        for index, column in enumerate(columns):
            moved = permute_pauli(code, column, vertex_map, edge_map)
            for part, difference in (("x", column.x ^ moved.x), ("z", column.z ^ moved.z)):
                while difference:
                    bit = (difference & -difference).bit_length() - 1
                    key = (part, bit)
                    coordinate_rows[key] = coordinate_rows.get(key, 0) ^ (1 << index)
                    difference &= difference - 1
        equations.extend(row for row in coordinate_rows.values() if row)
    return len(rref_nullspace(equations, len(columns))[1])


def radius_two_tractability_control() -> None:
    rows = []
    for length in (3, 4, 5, 6):
        code = c252.join_code(length)
        internal = next(edge for edge, row in enumerate(code.graph.edges) if row[2] == "internal_triangle")
        outer = next(edge for edge, row in enumerate(code.graph.edges) if row[2] == "outer_square")
        internal_columns = radius_two_columns(code, internal)
        outer_columns = radius_two_columns(code, outer)
        dimensions = (
            centralizer_covariant_dimension(code, internal, internal_columns),
            centralizer_covariant_dimension(code, outer, outer_columns),
        )
        rows.append(
            {
                "L": length,
                "columns": (len(internal_columns), len(outer_columns)),
                "affine_dimensions": dimensions,
                "unquotiented_family_exponent": sum(dimensions),
            }
        )
    check(
        "the radius-2 affine diagnostic is stable but too large for the same direct exhaustive tournament",
        len({row["columns"] for row in rows}) == 1
        and len({row["affine_dimensions"] for row in rows}) == 1
        and rows[0]["unquotiented_family_exponent"] > 30,
        rows,
    )


def deletion_and_scope_controls(
    spaces: dict[int, tuple[SeedSpace, SeedSpace]], tournament: TournamentResult
) -> None:
    code3 = c252.join_code(3)
    internal, outer = spaces[3]
    best_internal = internal.quotient_candidates[tournament.best_pair[0]]
    best_outer = outer.quotient_candidates[tournament.best_pair[1]]
    family_internal, _ = candidate_family(code3, internal.seed, best_internal)
    family_outer, _ = candidate_family(code3, outer.seed, best_outer)
    family = [
        family_internal[edge]
        if code3.graph.edges[edge][2] == "internal_triangle"
        else family_outer[edge]
        for edge in range(code3.edges)
    ]
    first_failure = None
    for left, right in combinations(range(code3.edges), 2):
        wanted = len(
            set(code3.graph.edges[left][:2]) & set(code3.graph.edges[right][:2])
        ) == 1
        actual = not family[left].commutes(family[right])
        if actual != wanted:
            first_failure = {
                "edges": (left, right),
                "kinds": (code3.graph.edges[left][2], code3.graph.edges[right][2]),
                "shared_endpoints": len(
                    set(code3.graph.edges[left][:2])
                    & set(code3.graph.edges[right][:2])
                ),
                "required_anticommutator_bit": int(wanted),
                "actual_anticommutator_bit": int(actual),
            }
            break
    check(
        "the best retained family has an explicit local symplectic witness rather than a solver-only negative",
        first_failure is not None and tournament.best_total_failures > 0,
        {
            "best_total_failures": tournament.best_total_failures,
            "best_incident_failures": tournament.best_incident_failures,
            "best_disjoint_failures": tournament.best_disjoint_failures,
            "first_failure": first_failure,
        },
    )

    # Removing one independent linear condition must enlarge at least one seed
    # space; this checks that the centralizer/covariance filter is load bearing.
    columns, _ = endpoint_star_columns(code3, internal.seed)
    equations = []
    for stabilizer in local_constraints(code3):
        row = sum(
            1 << index
            for index, column in enumerate(columns)
            if not column.commutes(stabilizer)
        )
        if row:
            equations.append(row)
    full_rank = len(rref_nullspace(equations, len(columns))[0])
    deletion_gain = 0
    for index in range(len(equations)):
        reduced_rank = len(
            rref_nullspace(equations[:index] + equations[index + 1 :], len(columns))[0]
        )
        deletion_gain = max(deletion_gain, full_rank - reduced_rank)
    check(
        "deleting one independent local-code commutator equation enlarges the raw dressing grammar by one binary direction",
        deletion_gain == 1,
        {"maximum_rank_loss": deletion_gain, "silent_constraint_deletion": False},
    )


def gate_fixture_firewall(tournament: TournamentResult) -> None:
    species = c219.common_species(c230.BETA)
    rest = c219.rest_mass(species)
    _, _, eigenvalues, _ = c230.finite_torus_modes(3)
    sea_rank = int(np.sum(np.angle(eigenvalues) < -1e-10))
    check(
        "the fixed Cycle-230 parameters and predecessor fixtures are retained but gate synthesis is withheld without a CAR family",
        abs(c230.BETA + 0.3) < 1e-15
        and abs(c230.COUPLING - 0.37) < 1e-15
        and abs(rest / species.analytic_mass - 1) < 2e-12
        and sea_rank == 73
        and not tournament.solutions,
        {
            "beta": c230.BETA,
            "g": c230.COUPLING,
            "rest_mass_predecessor": rest,
            "principal_sea_rank_predecessor": sea_rank,
            "coin_A_B_FSWAP_contact_synthesis": "not reached",
            "three_topological_joins": "remain separate",
            "mass_seam_intertwining": "not claimed",
        },
    )


def time_and_scope_firewall() -> None:
    check(
        "the bounded search schedule is not physical time and the grammar negative is not a universal no-go",
        True,
        {
            "compiler_layers_are_not_physical_time": True,
            "radius_1_endpoint_star": "exhausted",
            "radius_2": "not exhausted; affine seed dimensions are a next-route diagnostic only",
            "Clifford_conjugations_outside_Pauli_endpoint_star": "not exhausted",
            "universal_no_go": False,
            "axiom_pressure": False,
        },
    )


def main() -> int:
    note_contract()
    spaces, tournament = grammar_and_tournament_controls()
    radius_two_tractability_control()
    deletion_and_scope_controls(spaces, tournament)
    gate_fixture_firewall(tournament)
    time_and_scope_firewall()
    print(f"SUMMARY PASS {PASS} FAIL {FAIL}")
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
