#!/usr/bin/env python3
"""KCPT Unit 18 -- the even lattice-Dirac word algebra <D2, J_full>^H equals C[M] and
reaches four of the six commutant dimensions; the two missing charges are character-level.

Self-contained (no import of any other runner). Rebuilds from the bare L=4, N=64
staggered-lattice site construction the antisymmetric integer adjacency D2, the
corner-wave kernel frame, the ambient-invariant total complex structure
J_full = J_ker + J_bulk (J_full^2 = -I), the mass square M = D2^2 with strata
lambda_m = -4m (m=0,1,2,3), the chiral parity S_eps = diag((-1)^{x1+x2+x3}), the order-768
ambient group G_amb, its order-1536 extension H = <G_amb, S_eps>, and the SIX Unit-14
constituents C^64 = 8 (+) 8 (+) 12 (+) 12 (+) 12^+ (+) 12^-.

End_H(C^64) = C^6 is six-dimensional (the six constituents are multiplicity-free), so every
H-invariant operator is block-scalar (Schur). This unit certifies:

  T1  dim End_H(C^64) = 6: the six-character Gram is the identity I_6, so all six
      constituents are irreducible and pairwise inequivalent.               [G-T1-CHARORTHO]
  T2  the H-invariant (even-degree) part of the lattice-Dirac word algebra generated by
      {D2, J_full} equals C[M] = span{I, M, M^2, M^3}, dim 4: every even-length word in
      {D2, J_full} is G_amb-invariant AND S_eps-even, hence H-invariant and block-scalar,
      and the block-scalar span of all 85 even words up to degree 6 is exactly the 4-dim
      C[M]. The all-degree statement follows from J_full^2=-I, [D2,J_full]=0, and
      P := D2 J_full = -sqrt(-M) in C[M], all re-derived self-contained here.
                                                                         [G-T2-*, G-REJ-*]
  T3  the reach gap dim End_H - dim C[M] = 6 - 4 = 2 equals the number of intra-shell
      degeneracies: the CP-split pair {12^+, 12^-} both sit at M-shell -4 (m=1) and the
      two induced-12 both sit at M-shell -8 (m=2); C[M] is constant on each M-shell, so it
      cannot separate either degenerate pair.                                    [G-T3-*]
  T4  the two missing commutant dimensions are supplied by CHARACTER-LEVEL isotypic
      (Frobenius) projectors P_i = (d_i/|H|) Sum_h conj(chi_i(h)) rho(h): each equals its
      constituent projector, adjoining the CP isotypic projector raises the reach 4 -> 5
      and the induced-12 isotypic projector raises it 5 -> 6 = dim End_H, and each
      separates its M-degenerate pair (block-scalar 1 on one constituent, 0 on its
      partner). No polynomial in {D2, J_full} does this.                          [G-T4-*]
  T5  the structural reason the CP-charge is character-level: M is CP-even and takes the
      same scalar on the split pair, so every f(M) is blind to their chi_sgn twist, while
      the paired characters obey chi_{12^-}(h) = chi_sgn(h) * chi_{12^+}(h). The resulting
      isotypic projector is central/H-invariant, not chi_sgn-odd as an operator.          [G-T5-*]

ANTI-FABRICATION DISCIPLINE. J_full, M, S_eps, and G_amb are rebuilt only from the
shell/kernel/lattice machinery, never a parity/sign proxy. The commutant dimension is
decided by the REAL six-character orthonormality Gram (mult-free => dim = 6), never
assumed. The Dirac-even reach is the REAL numeric rank of the block-scalar coordinate
vectors of C[M] together with all 85 even words up to degree 6, backed by the exact
all-degree word reduction; the parity grading
carries live rejectors (D2 and J_full each ANTICOMMUTE with S_eps, their product COMMUTES),
so an odd word cannot masquerade as H-invariant. The radius identity P^2 = -M and the
symmetry P^T = P are REAL max-abs norms, re-derived here from the construction (not
imported). The character-projector separations are REAL block-scalar coordinates (1 vs 0),
and the chi_sgn twist is a REAL per-element character comparison over all 1536 h. No
irrational value is gated; every claim is a rank, an exact spectrum multiplicity, a
character identity, or an explicit wrong-value/parity rejector.
"""
import itertools
import os
import re
import numpy as np

# Every note this runner reads, repo-relative: the two parents (Unit 14 six-constituent
# decomposition, Unit 16 symplectic leg) plus this unit's own note. Plain literal tuple,
# statically ast-parseable by the runner-cache input fingerprint, matching the Unit-14
# runner's declaration mechanism.
AUDIT_INPUT_PATHS = (
    "docs/KCPT_CP_COMPLETION_UNDER_EXTENDED_GROUP_BOUNDED_THEOREM_NOTE_2026-07-20.md",                 # U14
    "docs/KCPT_SYMPLECTIC_LEG_CHISGN_COVARIANCE_OMEGA_PAIRING_BOUNDED_THEOREM_NOTE_2026-07-20.md",     # U16
    "docs/KCPT_DIRAC_EVEN_ALGEBRA_REACH_CHARACTER_CP_CHARGE_BOUNDED_THEOREM_NOTE_2026-07-21.md",       # self-note
)

L, N = 4, 64
TOL0 = 1e-12      # exact rational-zero level
TOL_F = 1e-9      # [FLOAT] identity level
TOL_EIG = 1e-8    # eigen / rank / restriction selection
TOLREJ = 1e-6     # rejector / residual floor
TOL_COMM = 1e-6   # commutant singular-value null threshold

DOCS = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs"))
U14_NOTE = "KCPT_CP_COMPLETION_UNDER_EXTENDED_GROUP_BOUNDED_THEOREM_NOTE_2026-07-20.md"
U16_NOTE = "KCPT_SYMPLECTIC_LEG_CHISGN_COVARIANCE_OMEGA_PAIRING_BOUNDED_THEOREM_NOTE_2026-07-20.md"
U17_NOTE = "KCPT_DIRAC_RADIUS_GRADING_OF_END_H_BOUNDED_THEOREM_NOTE_2026-07-20.md"
SELF_NOTE = "KCPT_DIRAC_EVEN_ALGEBRA_REACH_CHARACTER_CP_CHARGE_BOUNDED_THEOREM_NOTE_2026-07-21.md"

# PRESERVE VERBATIM source-pin substrings (grepped from the on-disk parent notes):
PIN_U14 = "C^64 = 8 + 8 + 12 + 12 + 12⁺ + 12⁻"
PIN_U16 = "hᵀ ω h = χ_sgn(h) · ω"

PASS = FAIL = 0


def gate(tag, cond, desc):
    global PASS, FAIL
    ok = bool(cond)
    PASS, FAIL = PASS + (1 if ok else 0), FAIL + (0 if ok else 1)
    print(f"{'PASS' if ok else 'FAIL'} {tag} - {desc}")
    return ok


def note_text(basename):
    try:
        with open(os.path.join(DOCS, basename), encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def nrm(X):
    return float(np.max(np.abs(X)))


def eqm(a, b):
    return np.array_equal(a, b)


# ---------------- construction (self-contained; verbatim Unit-14 backbone) --------------
def idx(a, b, c):
    return (a * L + b) * L + c


coords = np.zeros((N, 3), dtype=np.int64)
for a in range(L):
    for b in range(L):
        for c in range(L):
            coords[idx(a, b, c)] = (a, b, c)


def eta_mu(mu, x):
    if mu == 0:
        return 1
    if mu == 1:
        return (-1) ** int(x[0])
    return (-1) ** int(x[0] + x[1])


e = [np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1])]
D2 = np.zeros((N, N), dtype=np.int64)
for i in range(N):
    x = coords[i]
    for mu in range(3):
        D2[i, idx(*((x + e[mu]) % L))] += eta_mu(mu, x)
        D2[i, idx(*((x - e[mu]) % L))] -= eta_mu(mu, x)

SUBSETS = [(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]
sidx = {frozenset(S): k for k, S in enumerate(SUBSETS)}
V8 = np.zeros((N, 8), dtype=np.int64)
for i in range(N):
    x = coords[i]
    for k, S in enumerate(SUBSETS):
        V8[i, k] = (-1) ** int(sum(x[j] for j in S))


def sgn_subset(S):
    Sset = frozenset(S)
    return ((-1) ** len(Sset & frozenset({0, 2}))) * (1 if 1 in Sset else -1)


J64 = np.zeros((8, 8), dtype=np.int64)
for k, S in enumerate(SUBSETS):
    T = frozenset(S) ^ frozenset({1})
    J64[sidx[T], k] = 64 * sgn_subset(S)
Jker_int = V8 @ J64 @ V8.T                       # == 64^2 * J_ker

M = D2 @ D2
lam = [0, -4, -8, -12]
Fac = [M - lam[m] * np.eye(N, dtype=np.int64) for m in range(4)]
Q = []
for m in range(4):
    P = np.eye(N, dtype=np.int64)
    for mp in range(4):
        if mp != m:
            P = P @ Fac[mp]
    Q.append(P)
Nm = []
for m in range(4):
    v = 1
    for mp in range(4):
        if mp != m:
            v *= (lam[m] - lam[mp])
    Nm.append(v)                                 # (384, -128, 128, -384)

# total complex structure from the shell/kernel machinery (NO parity/sign proxy)
D2f = D2.astype(float)
Pf = [Q[m].astype(float) / Nm[m] for m in range(4)]
Jkerf = Jker_int.astype(float) / (64.0 ** 2)
Jbulk = sum(D2f @ Pf[m] / (2.0 * np.sqrt(m)) for m in (1, 2, 3))
Jfull = Jkerf + Jbulk

# chiral parity S_eps (the Unit-9 involution); integer form for exact identities
eps = np.array([(-1) ** int(coords[i][0] + coords[i][1] + coords[i][2]) for i in range(N)], dtype=np.int64)
Seps_int = np.diag(eps)
Seps = Seps_int.astype(float)
I64i = np.eye(N, dtype=np.int64)


# ---------------- G_amb reconstruction (dressed-symmetry scan + closure) ----------------
def perm(fmap):
    P = np.zeros((N, N), dtype=np.int64)
    for i in range(N):
        y = np.array(fmap(coords[i])) % L
        P[i, idx(int(y[0]), int(y[1]), int(y[2]))] = 1
    return P


UR = perm(lambda x: (x[1], x[2], x[0]))
U2m = perm(lambda x: (-x[1], -x[0], -x[2]))
STAB = np.eye(N, dtype=np.int64)
TR = {t: perm(lambda x, t=t: (x[0] - t[0], x[1] - t[1], x[2] - t[2]))
      for t in itertools.product(range(L), repeat=3)}


def signfield(bits):
    a1, a2, a3, b12, b13, b23 = bits
    d = np.zeros(N, dtype=np.int64)
    for i in range(N):
        x1, x2, x3 = coords[i]
        expo = a1 * x1 + a2 * x2 + a3 * x3 + b12 * x1 * x2 + b13 * x1 * x3 + b23 * x2 * x3
        d[i] = (-1) ** int(expo)
    return d


ALLBITS = list(itertools.product([0, 1], repeat=6))
SF = {bits: signfield(bits) for bits in ALLBITS}
BASES = {"stab": STAB, "U2": U2m, "UR": UR}


def closure_grp(gs):
    gs = [g0.copy() for g0 in gs]
    elts = {g0.tobytes(): g0 for g0 in gs}
    frontier = list(elts.values())
    while frontier:
        nf = []
        for xg in frontier:
            for g0 in gs:
                p = xg @ g0
                key = p.tobytes()
                if key not in elts:
                    elts[key] = p
                    nf.append(p)
        frontier = nf
    return list(elts.values())


commuting = []
for name, base in BASES.items():
    for bits in ALLBITS:
        dd = np.diag(SF[bits])
        for t in itertools.product(range(L), repeat=3):
            U = dd @ base @ TR[t]
            if eqm(U @ D2, D2 @ U):
                commuting.append(U.copy())
Gamb = closure_grp(commuting)

# small deterministic greedy generating set of G_amb (commutant of a generating set ==
# commutant of the group); closure certified == 768, so kron stacks use these, not 768.
Gsorted = sorted(Gamb, key=lambda U: U.tobytes())
gens_G = []
seenG = {I64i.tobytes()}
gen_closure_G = 0
for U in Gsorted:
    if eqm(U, I64i) or U.tobytes() in seenG:
        continue
    gens_G.append(U)
    cl = closure_grp(gens_G)
    seenG = {x.tobytes() for x in cl}
    gen_closure_G = len(cl)
    if gen_closure_G == 768:
        break

# ---------------- extend by S_eps: H = <G_amb, S_eps>, order 1536 -----------------------
gens_H = gens_G + [Seps_int]
coset = [Seps_int @ g for g in Gamb]             # the nontrivial coset S_eps * G_amb
Gamb_keys = {g.tobytes() for g in Gamb}
coset_keys = {c.tobytes() for c in coset}
gamb_complete = len(Gamb) == 768 and len(Gamb_keys) == 768
extension_complete = (
    gamb_complete
    and len(coset) == 768
    and len(coset_keys) == 768
    and Gamb_keys.isdisjoint(coset_keys)
    and all((Seps_int @ g @ Seps_int).tobytes() in Gamb_keys for g in Gamb)
)

# ---------------- holomorphic / anti-holomorphic frames --------------------------------
evals, evecs = np.linalg.eig(Jfull)
selp = np.where(np.abs(evals - 1j) < TOL_EIG)[0]
selm = np.where(np.abs(evals + 1j) < TOL_EIG)[0]
Bh, _ = np.linalg.qr(evecs[:, selp])       # holo W, 64 x 32
Bm, _ = np.linalg.qr(evecs[:, selm])       # anti-holo H_-, 64 x 32
PiW = Bh @ Bh.conj().T
PiHm = Bm @ Bm.conj().T


# ---------------- commutant helpers (memory-safe: kron stacks over GENERATORS only) -----
def commutant_dim(mats, r):
    Ir = np.eye(r, dtype=complex)
    A = np.vstack([np.kron(m.T, Ir) - np.kron(Ir, m) for m in mats])
    s = np.linalg.svd(A, compute_uv=False)
    return int(np.sum(s < TOL_COMM))


def commutant_basis(mats, r, d):
    Ir = np.eye(r, dtype=complex)
    A = np.vstack([np.kron(m.T, Ir) - np.kron(Ir, m) for m in mats])
    Uc, s, Vh = np.linalg.svd(A, full_matrices=False)   # full_matrices=False: no huge U -> OOM-safe
    del Uc, A
    return [np.conj(Vh[-(i + 1)]).reshape(r, r, order="F") for i in range(d)]


def split_block(Z, basis_mats, r, d):
    """Split the r-dim block with orthobasis columns Z (64 x r) into d H-irreps via a
    GENERIC self-adjoint commutant element.  A seed is accepted ONLY on clean d-cluster
    eigenvalue separation (inter-cluster gap > 1e6 * intra), NEVER by any target rank.
    Returns (sub-bases in 64-space, per-cluster ranks, seed) or (None, None, -1)."""
    for seed in range(128):
        rng = np.random.default_rng(seed)
        cc = rng.standard_normal(len(basis_mats)) + 1j * rng.standard_normal(len(basis_mats))
        Y = sum(cc[i] * basis_mats[i] for i in range(len(basis_mats)))
        Hs = Y + Y.conj().T
        ww, VV = np.linalg.eigh(Hs)
        spread = float(ww[-1] - ww[0])
        if spread <= 0:
            continue
        thr = 1e-4 * spread
        grp = [[0]]
        for j in range(1, r):
            if ww[j] - ww[j - 1] > thr:
                grp.append([j])
            else:
                grp[-1].append(j)
        intra = max((ww[g[-1]] - ww[g[0]]) for g in grp)
        inter = min((ww[grp[t + 1][0]] - ww[grp[t][-1]]) for t in range(len(grp) - 1)) \
            if len(grp) > 1 else 0.0
        if len(grp) == d and inter > 1e6 * max(intra, 1e-18):
            return [Z @ VV[:, g] for g in grp], [len(g) for g in grp], seed
    return None, None, -1


# ---------------- 5 holomorphic G_amb-idempotents on W (Unit-12 census) -----------------
Cgens = [Bh.conj().T @ g.astype(complex) @ Bh for g in gens_G]   # 32x32 restrictions
dimcW = commutant_dim(Cgens, 32)                                  # expect 5
BsW = commutant_basis(Cgens, 32, dimcW)
subZW, ranksW, seedW = split_block(Bh, BsW, 32, dimcW)
if subZW is not None:
    order = list(np.argsort(ranksW))
    subZW = [subZW[i] for i in order]
    ranksW = [ranksW[i] for i in order]
    PW = [z @ z.conj().T for z in subZW]                          # 64x64, in W; ranks 4,4,6,6,12
    PHm = [Seps.astype(complex) @ p @ Seps.astype(complex) for p in PW]   # S_eps-images in H_-
else:
    PW = PHm = []

# ============ split the reducible rank-12 CP-completed 24-block into 12^+ / 12^- ========
gensHc = [g.astype(complex) for g in gens_H]
k12 = int(np.argmax(ranksW)) if ranksW else 0    # the rank-12 W-block (ranksW sorted -> idx 4)
block12 = PW[k12] + PHm[k12]
r24 = int(round(np.trace(block12).real))         # 24
_w24, V24 = np.linalg.eigh((block12 + block12.conj().T) / 2.0)
Z24 = V24[:, -r24:]                              # 64 x 24 orthobasis of the CP-completed block
matsH24 = [Z24.conj().T @ g @ Z24 for g in gensHc]
dH24 = commutant_dim(matsH24, r24)               # expect 2 (two inequivalent H-irreps)
if dH24 == 2:
    BsB24 = commutant_basis(matsH24, r24, dH24)
    subZ24, subr24, _seed24 = split_block(Z24, BsB24, r24, dH24)
else:
    subZ24, subr24 = None, None
if subZ24 is not None:
    ordb = list(np.argsort(subr24))
    ZhalfW = [subZ24[i] for i in ordb]           # two 64 x 12 half-bases (12^+, 12^-)
else:
    ZhalfW = [np.zeros((N, 12), dtype=complex), np.zeros((N, 12), dtype=complex)]

# ==================== SIX Unit-14 constituents + the symmetric-form contrast anchor =====
# four CP-doubled blocks (8,8,12,12) + the two halves of the split real 12 (12^+, 12^-)
P6 = [PW[0] + PHm[0], PW[1] + PHm[1], PW[2] + PHm[2], PW[3] + PHm[3],
      ZhalfW[0] @ ZhalfW[0].conj().T,
      ZhalfW[1] @ ZhalfW[1].conj().T]
ranks6 = [int(np.linalg.matrix_rank(P, tol=TOL_EIG)) for P in P6]

# ==================================== gates (Unit 18: Dirac-even algebra reach vs the six-dim commutant)

print("\n=== KCPT Unit 18: even lattice-Dirac algebra <D2,J_full>^H = C[M] reaches 4 of the 6 commutant dims; the CP-charge is character-level ===")

Mf = M.astype(float)
Mf2 = Mf @ Mf
I64 = np.eye(N)
n6 = 6
Hgrp = Gamb + coset                       # order-1536 extended group H = <G_amb, S_eps> (list)


def orthobasis_c(P):
    """64 x rank(P) matrix whose columns are an orthonormal basis of range(P)."""
    Pc = np.asarray(P, dtype=complex)
    w, V = np.linalg.eigh((Pc + Pc.conj().T) / 2.0)
    r = int(round(float(np.trace(Pc).real)))          # rank = trace of the Hermitian idempotent
    order = np.argsort(w.real)[::-1]
    return V[:, order[:r]]


Z6 = [orthobasis_c(P6[i]) for i in range(n6)]
d6 = [Z6[i].shape[1] for i in range(n6)]
P6c = [np.asarray(P6[i], dtype=complex) for i in range(n6)]


def vscalar(T):
    """H-block-scalar coordinate 6-vector of T (Schur: End_H is block-scalar)."""
    Tc = np.asarray(T, dtype=complex)
    return np.array([np.trace(P6c[k] @ Tc) / d6[k] for k in range(n6)])


def mat_rank(vecs, tol=TOL_EIG):
    A = np.array(vecs)
    if A.size == 0:
        return 0
    return int(np.linalg.matrix_rank(A, tol=tol))


gamb_bytes = set(np.asarray(g).astype(np.int64).tobytes() for g in Gamb)


def chi_sgn(h):
    """+1 on G_amb, -1 on the S_eps coset (membership by exact integer bytes)."""
    return 1.0 if np.asarray(h).astype(np.int64).tobytes() in gamb_bytes else -1.0


def isotypic(i):
    """Character-level isotypic (Frobenius) projector onto constituent i."""
    di = d6[i]
    acc = np.zeros((N, N), dtype=complex)
    for j, h in enumerate(Hgrp):
        hc = np.asarray(h, dtype=complex)
        acc += np.conj(chars[i, j]) * hc
    return (di / len(Hgrp)) * acc


# M-shell block-scalar per constituent (=-4m, exact by Schur). The first four P6 entries
# are the induced 8,8,12,12 blocks and the final two are the split 12+,12- halves, by the
# verbatim Unit-16 construction above; the shell gates must verify those named roles.
svals = vscalar(Mf).real
shell = [int(round(v)) for v in svals]
cp_idx = [4, 5]
ind12_idx = [2, 3]
ind8_idx = [0, 1]
cp0, cp1 = cp_idx
ia, ib = ind12_idx
e0, e1 = ind8_idx

# C[M] block-vectors and the even/odd lattice-Dirac words up to degree 6
Mpows = [I64, Mf, Mf2, Mf2 @ Mf]
vM = [vscalar(X) for X in Mpows]
gens = [D2f, Jfull]
words = [(0, I64)]
frontier = [(0, I64)]
for _ in range(6):
    newf = [(L + 1, X @ G) for (L, X) in frontier for G in gens]
    words += newf
    frontier = newf
even_mats = [X for (L, X) in words if L % 2 == 0]      # G_amb-invariant AND S_eps-even => H-invariant
even_vecs = [vscalar(X) for X in even_mats]

# ---- Construction sanity (4) ----
gate("G-CONSTRUCT-J2", nrm(Jfull @ Jfull + I64) < TOL_F,
     "J_full^2 = -I_64 (total complex structure)")
uev, cnts = np.unique(np.rint(np.linalg.eigvalsh(Mf)).astype(int), return_counts=True)
gate("G-CONSTRUCT-M", dict(zip(uev.tolist(), cnts.tolist())) == {-12: 8, -8: 24, -4: 24, 0: 8},
     "M = D2^2 spectrum multiplicities {0:8, -4:24, -8:24, -12:8}")
decomp_orth = max(nrm(P6c[i] @ P6c[j]) for i in range(n6) for j in range(n6) if i != j)
decomp_hinv = max(nrm(g @ P - P @ g) for g in gensHc for P in P6c)
sixP_ok = (ranks6 == [8, 8, 12, 12, 12, 12]
           and nrm(sum(P6c) - I64) < TOL_F
           and all(nrm(P6c[k] @ P6c[k] - P6c[k]) < TOL_F for k in range(n6))
           and all(nrm(P6c[k] - P6c[k].conj().T) < TOL_F for k in range(n6))
           and decomp_orth < TOL_F and decomp_hinv < TOL_F)
gate("G-CONSTRUCT-SIX", sixP_ok,
     "six H-invariant constituents ranks [8,8,12,12,12,12], orthogonal Hermitian idempotents summing to I")
gate("G-GROUP", gamb_complete and extension_complete and gen_closure_G == 768
     and len(Gamb_keys | coset_keys) == 1536,
     "|G_amb| = 768 and H = G_amb disjoint-union S_eps G_amb has 1536 unique elements (index 2)")

# ---- T1: dim End_H = 6 via character orthonormality (1) ----
chars = np.zeros((n6, len(Hgrp)), dtype=complex)
for j, h in enumerate(Hgrp):
    hc = np.asarray(h, dtype=complex)
    for i in range(n6):
        chars[i, j] = np.trace(Z6[i].conj().T @ hc @ Z6[i])
Gram = chars @ chars.conj().T / len(Hgrp)
gram_dev = nrm(Gram - np.eye(n6))
gate("G-T1-CHARORTHO", gram_dev < TOL_F,
     "computed six-character Gram = I_6 (max residual %.2e) => dim End_H(C^64) = 6" % gram_dev)

# ---- T2: even Dirac algebra <D2,J_full>^H = C[M], dim 4 (4) ----
gate("G-T2-CMRANK", mat_rank(vM) == 4,
     "rank{v(I), v(M), v(M^2), v(M^3)} = 4 = dim C[M] (M has four distinct shells)")
Prad = D2f @ Jfull
comm_dev = nrm(D2f @ Jfull - Jfull @ D2f)
janti_dev = nrm(Jfull + Jfull.T)
root_from_shells = sum((-2.0 * np.sqrt(m)) * Pf[m] for m in (1, 2, 3))
root_dev = nrm(Prad - root_from_shells)
gate("G-T2-EVENREACH", len(even_mats) == 85 and mat_rank(vM + even_vecs) == 4
     and comm_dev < TOL_F and root_dev < TOL_F,
     "85 even words deg<=6 add no rank to C[M]; [D2,J_full]=0 and D2 J_full in C[M] reduce every even word")
maxblk = 0.0
for X in even_mats:
    v = vscalar(X)
    maxblk = max(maxblk, nrm(np.asarray(X, dtype=complex) - sum(v[k] * P6c[k] for k in range(n6))))
gate("G-T2-EVENBLOCK", maxblk < TOL_F,
     "every even word equals its block-scalar reconstruction (H-invariant); max residual %.2e" % maxblk)
gate("G-T2-PROOT", janti_dev < TOL_F and comm_dev < TOL_F
     and nrm(Prad - Prad.T) < TOL_F and nrm(Prad @ Prad + Mf) < TOL_F and root_dev < TOL_F,
     "P := D2 J_full = -sqrt(-M) from the rebuilt shell projectors (root residual %.2e); P symmetric, P^2=-M" % root_dev)

# ---- Parity grading: odd generators anticommute with S_eps, their product commutes (3) ----
d2_odd_dev = nrm(Seps @ D2f @ Seps + D2f)
j_odd_dev = nrm(Seps @ Jfull @ Seps + Jfull)
d2_cp_off = nrm(Z6[cp0].conj().T @ D2f @ Z6[cp1])
j_cp_off = nrm(Z6[cp0].conj().T @ Jfull @ Z6[cp1])
gamb_d2_dev = max(nrm(g @ D2f - D2f @ g) for g in gens_G)
gamb_j_dev = max(nrm(g @ Jfull - Jfull @ g) for g in gens_G)
prad_h_dev = max(nrm(g @ Prad - Prad @ g) for g in gens_H)
gate("G-REJ-D2ODD", d2_odd_dev < TOL_F and gamb_d2_dev < TOL_F and d2_cp_off > TOLREJ,
     "D2 is G_amb-invariant but S_eps-odd and has nonzero 12+/12- off-block %.3f => not H-invariant" % d2_cp_off)
gate("G-REJ-JODD", j_odd_dev < TOL_F and gamb_j_dev < TOL_F and j_cp_off > TOLREJ,
     "J_full is G_amb-invariant but S_eps-odd and has nonzero 12+/12- off-block %.3f => not H-invariant" % j_cp_off)
gate("G-REJ-PEVEN", nrm(Seps @ Prad @ Seps - Prad) < TOL_F
     and prad_h_dev < TOL_F and nrm(Prad) > TOLREJ,
     "nonzero D2 J_full is S_eps-even and H-invariant (generator commutator residual %.2e)" % prad_h_dev)

# ---- T3: reach gap 6-4 = 2 = the two intra-shell degeneracies (3) ----
gate("G-T3-MSHELLS", sorted(shell) == [-12, -8, -8, -4, -4, 0],
     "constituent M-shells (multiset) = {0, -4, -4, -8, -8, -12}")
gate("G-T3-DEGENPAIRS",
     [shell[k] for k in cp_idx] == [-4, -4]
     and [shell[k] for k in ind12_idx] == [-8, -8]
     and sorted(shell[k] for k in ind8_idx) == [-12, 0],
     "CP-pair share M-shell -4; two induced-12 share M-shell -8; two induced-8 M-distinct (0 vs -12)")
gate("G-GAP",
     6 - mat_rank(vM + even_vecs) == 2 and len(shell) - len(set(shell)) == 2,
     "dim End_H - dim C[M] = 2 = number of intra-shell (M-degenerate) constituent pairs")

# ---- T4: the two missing charges are character-level isotypic projectors (5) ----
iso_all = [isotypic(i) for i in range(n6)]
iso_dev = max(nrm(iso_all[i] - P6c[i]) for i in range(n6))
iso_cp = iso_all[cp0]
iso_ind = iso_all[ia]
gate("G-T4-ISOEQ", iso_dev < TOL_F,
     "all six character projectors (d/|H|) sum_h conj(chi) rho(h) reconstruct their constituent projectors; max residual %.2e" % iso_dev)
gate("G-T4-RANK5", mat_rank(vM + even_vecs + [vscalar(iso_cp)]) == 5,
     "adjoining the CP isotypic projector raises reach 4 -> 5")
gate("G-T4-RANK6", mat_rank(vM + even_vecs + [vscalar(iso_cp), vscalar(iso_ind)]) == 6,
     "adjoining the induced-12 isotypic projector raises reach 5 -> 6 = dim End_H")
vc = vscalar(iso_cp).real
gate("G-T4-SEPSPLIT",
     abs(vc[cp0] - 1) < TOL_F and abs(vc[cp1]) < TOL_F and abs(vc[cp0] - vc[cp1]) > 1 - TOL_F,
     "CP isotypic charge separates {12+,12-}: block-scalar 1 on one, 0 on its chi_sgn-twin")
vi = vscalar(iso_ind).real
gate("G-T4-SEPIND",
     abs(vi[ia] - 1) < TOL_F and abs(vi[ib]) < TOL_F and abs(vi[ia] - vi[ib]) > 1 - TOL_F,
     "induced-12 isotypic charge separates the two M-shell(-8) constituents: 1 vs 0")

# ---- T5: structural reason -- M is CP-even and 12- = 12+ (x) chi_sgn (2) ----
m_even_dev = nrm(Seps @ Mf @ Seps - Mf)
gate("G-T5-MCPEVEN", m_even_dev < TOL_F,
     "S_eps M S_eps = M (computed residual %.2e); f(M) is constant on the twist-pair's common shell" % m_even_dev)
twist = 0.0
for h in Hgrp:
    hc = np.asarray(h, dtype=complex)
    ca = np.trace(Z6[cp0].conj().T @ hc @ Z6[cp0])
    cb = np.trace(Z6[cp1].conj().T @ hc @ Z6[cp1])
    twist = max(twist, abs(ca - chi_sgn(h) * cb))
gate("G-T5-TWIST", twist < TOLREJ,
     "max_h |chi_12+(h)-chi_sgn(h)chi_12-(h)| = %.2e; the central projector is character-sensitive, not chi_sgn-odd" % twist)

# ---- Source pins (3) ----
gate("G-PIN-U14", PIN_U14 in note_text(U14_NOTE),
     "U14 six-constituent decomposition sentence present in the U14 note")
gate("G-PIN-U16", PIN_U16 in note_text(U16_NOTE),
     "U16 chi_sgn-covariance sentence present in the U16 note")
_t = note_text(SELF_NOTE)
_linked_kcpt = re.findall(r"\]\((KCPT_[^)]+\.md)\)", _t)
gate("G-PIN-SELF", _linked_kcpt == [U14_NOTE, U16_NOTE]
     and f"`{U17_NOTE}`" in _t and U17_NOTE not in _linked_kcpt,
     "self-note dependency inventory: exactly U14 + U16 linked (2 edges), U17 backticked (0)")

print(f"\nTOTAL: PASS={PASS} FAIL={FAIL}")
raise SystemExit(1 if FAIL else 0)
