"""KCPT L = 6 ind8-separator reach census (surface comparison with the landed L = 4 census).

Self-contained (stdlib + numpy only). Ports the KCPT structure map to L = 6
(N = 216, 6^3 torus, staggered lattice) and measures, over every H-conjugation
orbit of the D2-commuting signed-permutation group G_amb, the reach observable

    omega(g) = || Pi_{C_g}(sep6) ||_F^2 / || sep6 ||_F^2 ,

where C_g = <D2, J_full, S_eps, U_g> is the complex-linear matrix *-algebra
generated by those real matrices and one census element U_g, Pi is Frobenius orthogonal
projection, and sep6 = P8a - P8b is the ind-8 separator (difference of the two
multiplicity-1 rank-8 isotypic projectors on the top staggered shell). The reach
into the full 9-dimensional separator complement of C[M] inside A' is recorded as
d(g); the shell-projector character difference Dchi(g) = Re(tr(P8a U_g) - tr(P8b U_g))
is recorded alongside.

The construction section (build_lattice, signed-permutation helpers, build_group,
A_nat, per-shell H-averaged commutant, isotypic blocks, A', sep6, the 9-direction
complement) mirrors the landed L = 6 surface-change lane. Everything is built from
scratch; no external data files are loaded. Runs single-threaded.

Gate contract: prints per-gate PASS lines and a final `TOTAL: PASS=N FAIL=0`,
exits 0 on success.
"""

import itertools
import time
import gc
import resource
import sys
from collections import Counter, defaultdict
from fractions import Fraction
import numpy as np

# ----------------------------------------------------------------------------
# gate harness
# ----------------------------------------------------------------------------
_P = [0]
_F = [0]


def gate(name, cond, msg=""):
    ok = bool(cond)
    tag = "PASS" if ok else "FAIL"
    line = f"[GATE {name}] {tag}"
    if msg:
        line += f" -- {msg}"
    print(line, flush=True)
    if ok:
        _P[0] += 1
    else:
        _F[0] += 1
    return ok


def rss_gb():
    r = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    # macOS reports bytes, Linux reports kB
    return r / 1e9 if r > 1e7 else r / 1e6


# ----------------------------------------------------------------------------
# lattice construction (staggered D2, shell projectors, complex structure J)
# ----------------------------------------------------------------------------
SUBSETS = [(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]


def build_lattice(L):
    N = L ** 3
    e = np.eye(3, dtype=int)

    def idx(a, b, c):
        return ((a % L) * L + (b % L)) * L + (c % L)

    coords = np.array([[a, b, c] for a in range(L) for b in range(L) for c in range(L)],
                      dtype=int)

    def eta_mu(mu, x):
        if mu == 0:
            return 1
        if mu == 1:
            return (-1) ** x[0]
        return (-1) ** (x[0] + x[1])

    D2 = np.zeros((N, N), dtype=np.int64)
    for i in range(N):
        x = coords[i]
        for mu in range(3):
            xp = (x + e[mu]) % L
            xm = (x - e[mu]) % L
            D2[i, idx(*xp)] += eta_mu(mu, x)
            D2[i, idx(*xm)] -= eta_mu(mu, x)

    M = D2 @ D2
    evM = np.linalg.eigvalsh(M.astype(float))
    rounded = np.round(evM).astype(int)
    distinct = sorted(set(rounded.tolist()), reverse=True)
    lam = distinct
    K = len(lam)

    Mf = M.astype(float)
    Pf = []
    mults = []
    Iden = np.eye(N)
    for m in range(K):
        Q = np.eye(N)
        Nm = 1.0
        for mp in range(K):
            if mp == m:
                continue
            Q = Q @ (Mf - lam[mp] * Iden)
            Nm *= (lam[m] - lam[mp])
        P = Q / Nm
        Pf.append(P)
        mults.append(int(round(np.trace(P))))

    V8 = np.zeros((N, 8), dtype=float)
    for k, S in enumerate(SUBSETS):
        for i in range(N):
            x = coords[i]
            V8[i, k] = (-1) ** sum(x[j] for j in S)

    sidx = {frozenset(S): k for k, S in enumerate(SUBSETS)}

    def sgn_subset(S):
        s = set(S)
        a = (-1) ** len(s & {0, 2})
        b = 1 if 1 in s else -1
        return a * b

    JN = np.zeros((8, 8), dtype=float)
    for k, S in enumerate(SUBSETS):
        target = frozenset(S) ^ frozenset({1})
        JN[sidx[target], k] = N * sgn_subset(S)
    Jker_int = V8 @ JN @ V8.T
    Jkerf = Jker_int / (float(N) ** 2)

    D2f = D2.astype(float)
    Jbulk = np.zeros((N, N), dtype=float)
    for m in range(K):
        if lam[m] == 0:
            continue
        Jbulk += (D2f @ Pf[m]) / np.sqrt(abs(lam[m]))
    Jfull = Jkerf + Jbulk

    eps = np.array([(-1) ** (coords[i, 0] + coords[i, 1] + coords[i, 2]) for i in range(N)],
                   dtype=float)
    Seps = np.diag(eps)

    return {
        "L": L, "N": N, "coords": coords, "idx": idx,
        "D2": D2, "D2f": D2f, "M": M, "lam": lam, "K": K,
        "Pf": Pf, "mults": mults, "V8": V8,
        "Jfull": Jfull, "eps": eps, "Seps": Seps,
    }


# ----------------------------------------------------------------------------
# signed-permutation group G_amb and H = <G_amb, S_eps>
# ----------------------------------------------------------------------------
def sp_from_fmap(fmap, signfn, coords, idx, N):
    p = np.zeros(N, dtype=np.int64)
    s = np.zeros(N, dtype=np.int64)
    for i in range(N):
        x = coords[i]
        xn = fmap(x)
        j = idx(*[int(v) for v in xn])
        p[i] = j
        s[i] = signfn(x)
    return p, s


def sp_diag(signfn, coords, N):
    p = np.arange(N, dtype=np.int64)
    s = np.array([signfn(coords[i]) for i in range(N)], dtype=np.int64)
    return p, s


def compose(a, b):
    """Matrix product U_a @ U_b; on column vectors b acts first, then a."""
    pa, sa = a
    pb, sb = b
    return (pb[pa], sa * sb[pa])


def sp_inv(a):
    p, s = a
    pinv = np.empty_like(p)
    pinv[p] = np.arange(len(p))
    return (pinv, s[pinv])


def key(g):
    return g[0].tobytes() + (g[1].astype(np.int8)).tobytes()


def commutes_with_D2(g, D2):
    p, s = g
    A = (s[:, None] * s[None, :]) * D2[np.ix_(p, p)]
    return np.array_equal(A, D2)


def closure(gens):
    seen = {}
    idg = (np.arange(len(gens[0][0]), dtype=np.int64),
           np.ones(len(gens[0][0]), dtype=np.int64))
    stack = [idg]
    seen[key(idg)] = idg
    while stack:
        g = stack.pop()
        for gg in gens:
            h = compose(g, gg)
            k = key(h)
            if k not in seen:
                seen[k] = h
                stack.append(h)
    return seen


def build_group(lat):
    L, N = lat["L"], lat["N"]
    coords, idx, D2 = lat["coords"], lat["idx"], lat["D2"]

    def f_stab(x):
        return (x[0], x[1], x[2])

    def f_U2(x):
        return (-x[1], -x[0], -x[2])

    def f_UR(x):
        return (x[1], x[2], x[0])

    bases = [f_stab, f_U2, f_UR]

    trans = []
    for t in coords:
        tt = t.copy()
        trans.append(sp_from_fmap(lambda x, tt=tt: (x[0] + tt[0], x[1] + tt[1], x[2] + tt[2]),
                                  lambda x: 1, coords, idx, N))

    def make_signfn(bits):
        a1, a2, a3, b12, b13, b23 = bits

        def fn(x):
            e = (a1 * x[0] + a2 * x[1] + a3 * x[2]
                 + b12 * x[0] * x[1] + b13 * x[0] * x[2] + b23 * x[1] * x[2])
            return (-1) ** e
        return fn

    allbits = list(itertools.product([0, 1], repeat=6))

    # enumerate candidate signed perms U_base @ U_sign @ U_translation,
    # keeping those that commute with D2
    commuting = {}
    for base in bases:
        base_sp = sp_from_fmap(base, lambda x: 1, coords, idx, N)
        for bits in allbits:
            sf = sp_diag(make_signfn(bits), coords, N)
            g0 = compose(base_sp, sf)  # U_base @ U_sign
            for t in trans:
                g = compose(g0, t)
                if commutes_with_D2(g, D2):
                    commuting[key(g)] = g

    gens_all = list(commuting.values())
    Gamb = closure(gens_all)
    nG = len(Gamb)

    ident0 = np.arange(N)
    gens_G = []
    cur_size = 1
    for g in gens_all:
        if np.array_equal(g[0], ident0) and np.all(g[1] == 1):
            continue
        trial = closure(gens_G + [g])
        if len(trial) > cur_size:
            gens_G.append(g)
            cur_size = len(trial)
            if cur_size == nG:
                break

    Seps_sp = sp_diag(lambda x: (-1) ** (x[0] + x[1] + x[2]), coords, N)
    gens_H = gens_G + [Seps_sp]
    Hclos = closure(gens_H)
    nH = len(Hclos)

    HP = np.array([g[0] for g in Hclos.values()], dtype=np.int64)
    HS = np.array([g[1] for g in Hclos.values()], dtype=np.int8)
    Gkeys = set(Gamb.keys())

    return {
        "Gamb": Gamb, "H": Hclos, "nG": nG, "nH": nH,
        "HP": HP, "HS": HS, "Gkeys": Gkeys,
        "gens_G": gens_G, "gens_H": gens_H, "Seps_sp": Seps_sp,
    }


def conj_partition(elements, conj_gens):
    remaining = dict(elements)
    sizes = []
    while remaining:
        k0, g0 = next(iter(remaining.items()))
        orbit = {k0: g0}
        stack = [g0]
        while stack:
            g = stack.pop()
            for c in conj_gens:
                h = compose(compose(c, g), sp_inv(c))
                kh = key(h)
                if kh not in orbit:
                    orbit[kh] = h
                    stack.append(h)
        for k in orbit:
            remaining.pop(k, None)
        sizes.append(len(orbit))
    return sizes


def conj_partition_reps(elements, conj_gens):
    """Same partition as conj_partition, returning one representative + size per orbit."""
    remaining = dict(elements)
    out = []
    while remaining:
        k0, g0 = next(iter(remaining.items()))
        orbit = {k0: g0}
        stack = [g0]
        while stack:
            g = stack.pop()
            for c in conj_gens:
                h = compose(compose(c, g), sp_inv(c))
                kh = key(h)
                if kh not in orbit:
                    orbit[kh] = h
                    stack.append(h)
        for k in orbit:
            remaining.pop(k, None)
        out.append((g0, len(orbit)))
    return out


def orbit_size(g, conj_gens):
    orbit = {key(g): g}
    stack = [g]
    while stack:
        h = stack.pop()
        for c in conj_gens:
            hh = compose(compose(c, h), sp_inv(c))
            kh = key(hh)
            if kh not in orbit:
                orbit[kh] = hh
                stack.append(hh)
    return len(orbit)


# ----------------------------------------------------------------------------
# Frobenius helpers, word algebras, overlaps
# ----------------------------------------------------------------------------
def vec(A):
    return np.asarray(A, dtype=complex).reshape(-1)


def orth_add(B, A, tol=1e-9):
    v = vec(A)
    nv = np.linalg.norm(v)
    if nv < tol:
        return B, False
    v = v / nv
    for _ in range(2):
        if B.shape[0]:
            v = v - B.T @ (B.conj() @ v)
    r = np.linalg.norm(v)
    if r < tol:
        return B, False
    return np.vstack([B, v / r]), True


def word_algebra(gens, N, cap=400, tol=1e-9):
    gens = [np.asarray(g, dtype=complex) for g in gens]
    B = np.zeros((0, N * N), dtype=complex)
    B, _ = orth_add(B, np.eye(N))
    frontier = [np.eye(N, dtype=complex)]
    while frontier and B.shape[0] < cap:
        newf = []
        for w in frontier:
            for g in gens:
                p = g @ w
                B2, added = orth_add(B, p, tol)
                if added:
                    B = B2
                    newf.append(p)
        frontier = newf
    return B, len(frontier) == 0


def word_algebra_real(gens, N, cap, tol=1e-9):
    """Real-valued word basis for the complex-linear matrix *-algebra <I, gens>.

    All generators and words are real, so a real Frobenius-orthonormal basis of
    their real span is also a complex basis of the complex-linear span. Returns
    (B, dim, closed): B is (dim, N*N) float64 rows, dim is the complex
    dimension, and closed is True iff the frontier emptied below cap. Stored as
    one growing (cap, N*N) array; one such array is live at a time.
    """
    gens = [np.asarray(g, dtype=np.float64) for g in gens]
    NN = N * N
    B = np.empty((cap, NN), dtype=np.float64)
    v = np.eye(N).reshape(-1).astype(np.float64)
    v /= np.linalg.norm(v)
    B[0] = v
    cnt = 1
    frontier = [np.eye(N, dtype=np.float64)]
    while frontier and cnt < cap:
        newf = []
        for w in frontier:
            for g in gens:
                p = g @ w
                v = p.reshape(-1).copy()
                nv = np.linalg.norm(v)
                if nv < tol:
                    continue
                v /= nv
                for _ in range(2):
                    if cnt:
                        v = v - B[:cnt].T @ (B[:cnt] @ v)
                r = np.linalg.norm(v)
                if r < tol:
                    continue
                B[cnt] = v / r
                cnt += 1
                newf.append(p)
                if cnt >= cap:
                    break
            if cnt >= cap:
                break
        frontier = newf
    closed = (len(frontier) == 0)
    return B[:cnt], cnt, closed


def overlap2(B, X):
    if B.shape[0] == 0:
        return 0.0
    v = vec(X)
    v = v / np.linalg.norm(v)
    return float(np.linalg.norm(B.conj() @ v) ** 2)


def center_of(Blist, gens, tol=1e-10):
    d = len(Blist)
    Gm = np.zeros((d, d), dtype=complex)
    for gg in gens:
        gg = np.asarray(gg, dtype=complex)
        Cg = np.stack([(gg @ Xk - Xk @ gg).ravel() for Xk in Blist], axis=1)
        Gm += Cg.conj().T @ Cg
    w, V = np.linalg.eigh(Gm)
    thr = tol * max(w[-1].real, 1e-30)
    nidx = np.where(w < thr)[0]
    Z = [sum(V[k, j] * Blist[k] for k in range(d)) for j in nidx]
    return Z, len(nidx)


# ----------------------------------------------------------------------------
# rigorous per-shell isotypic decomposition (H-averaged commutant)
# ----------------------------------------------------------------------------
def shell_commutant(Pm, HP, HS, nR=14, build_seed=98765, chunk=512):
    N = Pm.shape[0]
    w, V = np.linalg.eigh(Pm)
    d = int(round(np.trace(Pm).real))
    Z = V[:, N - d:].astype(complex)
    nH = HP.shape[0]
    HSf = HS.astype(float)
    rng = np.random.default_rng(build_seed)
    Rs = []
    for _ in range(nR):
        A = rng.standard_normal((d, d)) + 1j * rng.standard_normal((d, d))
        Rs.append(A + A.conj().T)
    acc = [np.zeros((d, d), dtype=complex) for _ in range(nR)]
    for c0 in range(0, nH, chunk):
        c1 = min(c0 + chunk, nH)
        W = np.stack([Z.conj().T @ (HSf[h][:, None] * Z[HP[h], :]) for h in range(c0, c1)])
        for j, R in enumerate(Rs):
            T = W @ R
            acc[j] += np.einsum('hij,hkj->ik', T, W.conj())
        del W
    B = []
    for a in acc:
        M0 = a / nH
        for Q in B:
            M0 = M0 - np.vdot(Q, M0) * Q
        nrm = np.sqrt(abs(np.vdot(M0, M0)))
        if nrm > 1e-8:
            B.append(M0 / nrm)
    return Z, B


def isotypic_blocks(Z, Bc, cluster_seed):
    cm = len(Bc)
    d = Z.shape[1]
    Gc = np.zeros((cm, cm), dtype=complex)
    for Xk in Bc:
        Cg = np.stack([(Xk @ Xj - Xj @ Xk).ravel() for Xj in Bc], axis=1)
        Gc += Cg.conj().T @ Cg
    wc, Vc = np.linalg.eigh(Gc)
    thr = 1e-8 * max(wc[-1].real, 1e-30)
    nidx = np.where(wc < thr)[0]
    rC = len(nidx)
    Zc = [sum(Vc[k, j] * Bc[k] for k in range(cm)) for j in nidx]
    rng = np.random.default_rng(cluster_seed)
    C = sum(rng.standard_normal() * Zb for Zb in Zc)
    Hc = (C + C.conj().T) / 2
    ev, U = np.linalg.eigh(Hc)
    if rC <= 1:
        groups = [np.arange(len(ev))]
    else:
        gaps = np.diff(ev)
        cut = np.sort(np.argsort(gaps)[-(rC - 1):])
        groups = []
        start = 0
        for c in cut:
            groups.append(np.arange(start, c + 1))
            start = c + 1
        groups.append(np.arange(start, len(ev)))
    blocks = []
    for gr in groups:
        cols = U[:, gr]
        Pdd = cols @ cols.conj().T
        rank = int(round(np.trace(Pdd).real))
        pm = []
        for Xk in Bc:
            Y = Pdd @ Xk @ Pdd
            for Q in pm:
                Y = Y - np.vdot(Q, Y) * Q
            nrm = np.sqrt(abs(np.vdot(Y, Y)))
            if nrm > 1e-6:
                pm.append(Y / nrm)
        mult = int(round(np.sqrt(len(pm))))
        dim = rank // mult if mult else 0
        Pshell = Z @ Pdd @ Z.conj().T
        blocks.append((dim, mult, rank, Pshell))
    return rC, blocks


def build_aprime(shell_ZB, D2f, Jfull, N):
    XH = []
    for Z, Bc in shell_ZB:
        for B in Bc:
            XH.append(Z @ B @ Z.conj().T)
    dH = len(XH)
    Gm = np.zeros((dH, dH), dtype=complex)
    for gg in (D2f.astype(complex), np.asarray(Jfull, dtype=complex)):
        Cg = np.stack([(gg @ Xk - Xk @ gg).ravel() for Xk in XH], axis=1)
        Gm += Cg.conj().T @ Cg
    w, V = np.linalg.eigh(Gm)
    thr = 1e-10 * max(w[-1].real, 1e-30)
    nidx = np.where(w < thr)[0]
    q = len(nidx)
    Aprime = [sum(V[k, j] * XH[k] for k in range(dH)) for j in nidx]
    return XH, Aprime, q, w


def dense_from_sp(p, s, N):
    U = np.zeros((N, N), dtype=float)
    U[np.arange(N), p] = s
    return U


# ----------------------------------------------------------------------------
# rational pinning helper
# ----------------------------------------------------------------------------
def q_le_candidates(maxq):
    vals = set()
    for q in range(1, maxq + 1):
        for p in range(0, q + 1):
            vals.add(Fraction(p, q))
    return sorted(vals)


def nearest_two(x, cands):
    ds = sorted(((abs(float(c) - x), c) for c in cands), key=lambda t: t[0])
    return ds[0], ds[1]


# ============================================================================
# MAIN
# ============================================================================
def main():
    t_start = time.time()
    np.set_printoptions(suppress=True)

    lat = build_lattice(6)
    N = lat["N"]
    D2 = lat["D2"]
    D2f = lat["D2f"]
    Jfull = lat["Jfull"]
    Pf = lat["Pf"]
    Seps = lat["Seps"]
    lam = lat["lam"]
    mults = lat["mults"]
    coords = lat["coords"]
    idx = lat["idx"]
    print(f"[info] L=6 built: N={N}, M spectrum {lam}, shell mults {mults} "
          f"({time.time()-t_start:.0f}s)", flush=True)

    # -------------------- groups and orbit partition --------------------
    t0 = time.time()
    grp = build_group(lat)
    nG, nH = grp["nG"], grp["nH"]
    HP, HS = grp["HP"], grp["HS"]
    Gkeys = grp["Gkeys"]
    conj_gens = grp["gens_H"] + [sp_inv(g) for g in grp["gens_H"]]
    print(f"[info] groups built: |G_amb|={nG}, |H|={nH} ({time.time()-t0:.0f}s)", flush=True)

    # ===== SECTION S: structure recap (cheap re-derivations) =====
    seps_in_G = key(grp["Seps_sp"]) in Gkeys
    gate("S1", nG == 2592 and nH == 5184 and (nH // nG) == 2 and not seps_in_G,
         f"|G_amb|={nG}=6^3*12, |H|={nH}, [H:G]={nH//nG}, S_eps in G_amb: {seps_in_G}")

    hclass_sizes = conj_partition(grp["H"], conj_gens)
    hc = dict(Counter(hclass_sizes))
    exp_hc = {1: 2, 2: 5, 3: 4, 4: 3, 6: 24, 12: 57, 54: 6, 72: 6, 108: 21, 144: 9}
    reps = conj_partition_reps(grp["Gamb"], conj_gens)
    go = dict(Counter(sz for _, sz in reps))
    exp_go = {1: 2, 2: 3, 3: 4, 4: 1, 6: 14, 12: 27, 54: 6, 72: 6, 108: 9, 144: 3}
    gate("S2",
         len(hclass_sizes) == 137 and hc == exp_hc
         and len(reps) == 75 and go == exp_go and sum(sz for _, sz in reps) == 2592,
         f"{len(hclass_sizes)} H-classes {dict(sorted(hc.items()))}; "
         f"{len(reps)} G-orbits {dict(sorted(go.items()))} sum {sum(sz for _, sz in reps)}")

    # ===== natural Dirac core A_nat = <D2, J, S_eps> =====
    Bnat, closed_nat = word_algebra([D2f, Jfull, Seps], N, cap=400, tol=1e-9)
    Xnat = [Bnat[k].reshape(N, N) for k in range(Bnat.shape[0])]
    Znat, zdim_nat = center_of(Xnat, [D2f, Jfull, Seps], tol=1e-10)
    BZc = np.zeros((0, N * N), dtype=complex)
    for z in Znat:
        BZc, _ = orth_add(BZc, z)
    ov_center = [overlap2(BZc, Pf[m]) for m in range(4)]

    # Wedderburn type of A_nat: 4 blocks each M_2(C), block ranks = shell mults
    def wedderburn_anat(seed):
        rngw = np.random.default_rng(seed)
        C = sum(rngw.standard_normal() * z for z in Znat)
        Hc = (C + C.conj().T) / 2
        ev, U = np.linalg.eigh(Hc)
        gaps = np.diff(ev)
        cut = np.sort(np.argsort(gaps)[-(zdim_nat - 1):]) if zdim_nat > 1 else []
        groups = []
        start = 0
        for c in cut:
            groups.append(np.arange(start, c + 1))
            start = c + 1
        groups.append(np.arange(start, len(ev)))
        res = []
        for gr in groups:
            cols = U[:, gr]
            P = cols @ cols.conj().T
            rank = int(round(np.trace(P).real))
            bb = []
            for Xk in Xnat:
                Y = P @ Xk @ P
                for Q in bb:
                    Y = Y - np.vdot(Q, Y) * Q
                nrm = np.sqrt(abs(np.vdot(Y, Y)))
                if nrm > 1e-8:
                    bb.append(Y / nrm)
            _, bc = center_of(bb, bb, tol=1e-9) if bb else (None, 0)
            res.append((rank, len(bb), bc))
        return sorted(res)

    wA = [wedderburn_anat(s) for s in (7, 1234)]
    ranks_ok = all(sorted(r[0] for r in w) == [8, 48, 64, 96] for w in wA)
    m2_ok = all(all(r[1] == 4 and r[2] == 1 for r in w) for w in wA)
    seed_agree = wA[0] == wA[1]
    gate("S3",
         Bnat.shape[0] == 16 and closed_nat and zdim_nat == 4
         and all(o >= 1 - 1e-10 for o in ov_center)
         and ranks_ok and m2_ok and seed_agree,
         f"dim A_nat={Bnat.shape[0]}, dim Z={zdim_nat} (=C[M], min overlap "
         f"{min(ov_center):.10f}); 4 blocks ranks [8,48,64,96], each M_2(C), two-seed agree {seed_agree}")

    # ===== per-shell commutant, A', sep6, 9-direction complement =====
    t0 = time.time()
    shell_ZB = [shell_commutant(Pf[m], HP, HS) for m in range(4)]
    XH, Aprime, qA, wgram = build_aprime(shell_ZB, D2f, Jfull, N)
    comm_max = 0.0
    for i in range(len(Aprime)):
        for j in range(i + 1, len(Aprime)):
            c = np.linalg.norm(Aprime[i] @ Aprime[j] - Aprime[j] @ Aprime[i])
            comm_max = max(comm_max, c)

    _, blocks_m3 = isotypic_blocks(*shell_ZB[3], 7)
    rank8 = [P for (d, mu, r, P) in blocks_m3 if mu == 1 and d == 8]
    P8a, P8b = rank8[0], rank8[1]
    sep6 = P8a - P8b
    rank_sum = int(round((np.trace(P8a) + np.trace(P8b)).real))
    sep6_norm = float(np.linalg.norm(sep6))
    sep_re = np.real(sep6).reshape(-1)
    sep_im = np.imag(sep6).reshape(-1)
    sep_norm2 = float(sep6_norm ** 2)
    P8a_r = np.real(P8a)
    P8b_r = np.real(P8b)

    cD = float(np.linalg.norm(sep6 @ D2f - D2f @ sep6))
    cJ = float(np.linalg.norm(sep6 @ Jfull - Jfull @ sep6))
    rng2 = np.random.default_rng(424242)
    cH_max = 0.0
    for _ in range(400):
        h = int(rng2.integers(nH))
        U = dense_from_sp(HP[h], HS[h].astype(float), N)
        cH_max = max(cH_max, float(np.linalg.norm(sep6 @ U - U @ sep6)))
    ov_anat_sep6 = overlap2(Bnat, sep6)
    gate("S4",
         rank_sum == 16 and abs(sep6_norm - 4.0) <= 1e-10
         and cD <= 1e-10 and cJ <= 1e-10 and cH_max <= 1e-10 and ov_anat_sep6 <= 1e-10,
         f"sep6 rank sum {rank_sum}, ||sep6||_F {sep6_norm:.12f}, [sep6,D2] {cD:.1e}, "
         f"[sep6,J] {cJ:.1e}, max[sep6,rho(h)] {cH_max:.1e}, overlap^2(A_nat,sep6) {ov_anat_sep6:.2e}")

    BZ = np.zeros((0, N * N), dtype=complex)
    for m in range(4):
        BZ, _ = orth_add(BZ, Pf[m])
    n_cm = BZ.shape[0]
    extras = []
    for A in Aprime:
        BZ2, added = orth_add(BZ, A)
        if added:
            extras.append(BZ2[-1].reshape(N, N))
            BZ = BZ2
    ex_re = [np.real(e).reshape(-1) for e in extras]
    ex_im = [np.imag(e).reshape(-1) for e in extras]
    ov_extras = [overlap2(Bnat, E) for E in extras]
    gate("S5",
         qA == 13 and comm_max <= 1e-10 and n_cm == 4 and len(extras) == 9
         and max(ov_extras) <= 1e-10,
         f"dim A'={qA} abelian (max||[A,B]|| {comm_max:.1e}); C[M] dim {n_cm}, "
         f"separator complement dim {len(extras)}, blind to A_nat (max overlap^2 {max(ov_extras):.1e})")

    # ===== LICENSING L1-NAT: H normalizes A_nat over generators and inverses =====
    nat_norm_max = 0.0
    for gsp in conj_gens:
        p, s = gsp
        sf = s.astype(float)
        for X in (D2f, Jfull, Seps):
            Xh = (sf[:, None] * sf[None, :]) * X[np.ix_(p, p)]
            v = vec(Xh)
            v = v / np.linalg.norm(v)
            proj = Bnat.T @ (Bnat.conj() @ v)
            nat_norm_max = max(nat_norm_max, float(np.linalg.norm(v - proj)))
    gate("L1-NAT", nat_norm_max < 1e-10,
         f"H normalizes A_nat: max normalized projection residual over "
         f"gens_H+inverses and X in {{D2,J_full,S_eps}} = {nat_norm_max:.1e}")

    # ===== LICENSING L1: sep6 H-invariance over generators and inverses =====
    l1_max = 0.0
    for gsp in conj_gens:
        Uh = dense_from_sp(gsp[0], gsp[1].astype(float), N)
        l1_max = max(l1_max, float(np.linalg.norm(Uh @ sep6 @ Uh.T - sep6)))
    gate("L1", l1_max < 1e-10,
         f"sep6 H-invariance: max ||U sep6 U^T - sep6||_F over gens_H+inverses = {l1_max:.1e}")
    print(f"[info] structure done ({time.time()-t0:.0f}s)", flush=True)

    # ================= CENSUS over the 75 G-orbits =================
    t0 = time.time()
    print("\n==== L=6 REACH CENSUS (75 H-orbits of G_amb) ====", flush=True)
    print("ci size dim closed omega(15) d(g) Dchi", flush=True)
    rows = []
    unresolved = []
    for ci, (g, size) in enumerate(reps):
        p, s = g
        Ug = dense_from_sp(p, s.astype(float), N)
        B, dim, closed = word_algebra_real([D2f, Jfull, Seps, Ug], N, cap=600)
        closed_at_600 = closed
        if not closed_at_600:
            del B
            gc.collect()
            B, dim, closed = word_algebra_real([D2f, Jfull, Seps, Ug], N, cap=4300)
        w = (np.linalg.norm(B @ sep_re) ** 2 + np.linalg.norm(B @ sep_im) ** 2) / sep_norm2
        reach = [float(np.linalg.norm(B @ ex_re[i]) ** 2 + np.linalg.norm(B @ ex_im[i]) ** 2)
                 for i in range(len(extras))]
        dg = sum(1 for rr in reach if rr > 1e-6)
        dchi = float(np.real(np.trace(P8a_r @ Ug) - np.trace(P8b_r @ Ug)))
        if not closed:
            unresolved.append(ci)
        rows.append((ci, size, dim, closed, w, dg, dchi, closed_at_600))
        print(f"C {ci:3d} sz {size:3d} dim {dim:4d} closed {int(closed)} "
              f"omega {w:.15f} dg {dg} dchi {dchi:+.10f}", flush=True)
        del B
        if ci % 8 == 0:
            gc.collect()
    print(f"[info] census done ({time.time()-t0:.0f}s), peak RSS {rss_gb():.2f} GB", flush=True)

    if unresolved:
        gate("CENSUS_RESOLVED", False, f"UNRESOLVED closures at cap 4300: {unresolved} -- STOP")
        print(f"TOTAL: PASS={_P[0]} FAIL={_F[0]}", flush=True)
        sys.exit(1)
    n_cap600_misses = sum(1 for r in rows if not r[7])
    gate("CN0", all(r[3] for r in rows) and n_cap600_misses == 0 and len(rows) == 75
         and sum(r[1] for r in rows) == 2592,
         f"all 75 closures closed at cap 600 (cap-600 misses {n_cap600_misses}), "
         f"elements sum {sum(r[1] for r in rows)}=2592, 0 UNRESOLVED")

    # cluster omega values
    def cluster(vals, tol=1e-6):
        cs = []
        for v in sorted(vals):
            placed = False
            for c in cs:
                if abs(v - c[0]) < tol:
                    c[1].append(v)
                    c[0] = np.mean(c[1])
                    placed = True
                    break
            if not placed:
                cs.append([v, [v]])
        return [c[0] for c in cs]

    omegas = [r[4] for r in rows]
    centers = cluster(omegas)
    q12 = q_le_candidates(12)
    q15 = q_le_candidates(15)

    print("\n==== OMEGA VALUE SET ====", flush=True)
    total_el = 0
    value_summary = []
    for cval in centers:
        members = [r for r in rows if abs(r[4] - cval) < 1e-6]
        ncls = len(members)
        nel = sum(r[1] for r in members)
        total_el += nel
        (d1, c1), (d2, c2) = nearest_two(cval, q12)
        value_summary.append((cval, ncls, nel, c1, d1, c2, d2))
        print(f"omega={cval:.15f} classes={ncls} elements={nel} "
              f"nearest q<=12 {c1}(err {d1:.1e}) second {c2}(err {d2:.1e})", flush=True)
    gate("CN_total", total_el == 2592 and len(centers) == 6,
         f"{len(centers)} distinct omega values, element total {total_el}=2592")

    # per-value quantization gates with wrong-value rejectors
    # expected: 0(61/1818), 1/4(2/14), 4/15(1/144, denom>12), 1/3(5/300), 1/2(3/24), 1(3/292)
    exp_counts = {
        Fraction(0): (61, 1818),
        Fraction(1, 4): (2, 14),
        Fraction(1, 3): (5, 300),
        Fraction(1, 2): (3, 24),
        Fraction(1): (3, 292),
    }
    pinned = {}
    for (cval, ncls, nel, c1, d1, c2, d2) in value_summary:
        if d1 < 1e-9:
            # quantized at q<=12: pin c1, reject next-nearest q<=12 by >=1e-6
            name = f"CN_q[{c1}]"
            exp = exp_counts.get(c1, None)
            ok = (exp is not None and (ncls, nel) == exp and d2 >= 1e-6)
            pinned[c1] = (ncls, nel)
            gate(name, ok,
                 f"omega={c1} (err {d1:.1e}) classes={ncls} elements={nel}; "
                 f"rejector: next q<=12 {c2} off by {d2:.1e}(>=1e-6)")
        else:
            # no q<=12 rational within 1e-9 -> report decimal + exact denominator honestly
            fr15 = min(q15, key=lambda c: abs(float(c) - cval))
            d15 = abs(float(fr15) - cval)
            name = "CN_nonq"
            ok = (ncls == 1 and nel == 144 and d1 >= 1e-3
                  and fr15 == Fraction(4, 15) and d15 < 1e-12)
            gate(name, ok,
                 f"omega={cval:.15f} matches no q<=12 rational (nearest {c1} err {d1:.1e}); "
                 f"equals {fr15} (denominator 15>12, err {d15:.1e}) classes={ncls} elements={nel}")

    # count-consistency across all pinned quantized strata
    gate("CN_counts",
         pinned.get(Fraction(0)) == (61, 1818)
         and pinned.get(Fraction(1, 4)) == (2, 14)
         and pinned.get(Fraction(1, 3)) == (5, 300)
         and pinned.get(Fraction(1, 2)) == (3, 24)
         and pinned.get(Fraction(1)) == (3, 292),
         "class/element counts: 0->(61,1818) 1/4->(2,14) 1/3->(5,300) 1/2->(3,24) 1->(3,292)")

    # d(g) is binary {0,9}; every reaching class (omega>0) has d(g)=9; split pinned
    dvals = set(r[5] for r in rows)
    n_d0 = sum(1 for r in rows if r[5] == 0)
    n_d9 = sum(1 for r in rows if r[5] == 9)
    reach_ok = all(r[5] == 9 for r in rows if r[4] > 1e-9)
    gate("CN_dg", dvals <= {0, 9} and reach_ok and n_d0 == 14 and n_d9 == 61,
         f"d(g) values {sorted(dvals)} (subset of {{0,9}}), counts d=0:{n_d0} d=9:{n_d9}; "
         f"omega>0 => d(g)=9: {reach_ok}")

    # ===== LICENSING L2: direct cross-check of the proved H-class-function relation =====
    # six sampled orbits, one per measured omega stratum; 3 random same-class
    # conjugates h g h^-1 must reproduce dim exactly and omega to 1e-10
    rng3 = np.random.default_rng(20260725)
    l2_ok = True
    l2_report = []
    for cval in centers:
        members = [r for r in rows if abs(r[4] - cval) < 1e-6]
        sel = max(members, key=lambda r: (r[1], r[2]))
        ci = sel[0]
        g = reps[ci][0]
        for _ in range(3):
            hI = int(rng3.integers(nH))
            hsp = (HP[hI], HS[hI])
            gc_sp = compose(compose(hsp, g), sp_inv(hsp))
            Uc = dense_from_sp(gc_sp[0], gc_sp[1].astype(float), N)
            Bc, dc, cc = word_algebra_real([D2f, Jfull, Seps, Uc], N, cap=600)
            wc = (np.linalg.norm(Bc @ sep_re) ** 2 + np.linalg.norm(Bc @ sep_im) ** 2) / sep_norm2
            del Bc
            gc.collect()
            if not (cc and dc == sel[2] and abs(wc - sel[4]) < 1e-10):
                l2_ok = False
            l2_report.append((ci, dc, wc))
    gate("L2", l2_ok and len(l2_report) == 18,
         f"class-function check: 6 orbits (one per omega stratum) x 3 random conjugates; "
         f"all reproduce (dim, omega): {l2_ok}")

    # ===== COMPARISON with landed L=4 census =====
    # L=4 (cited): value set {0, 1/9, 1/3, 1}. L=6 measured: {0,1/4,4/15,1/3,1/2,1}.
    measured = set()
    for cval in centers:
        measured.add(cval)
    min_to_ninth = min(abs(cval - 1.0 / 9.0) for cval in centers)
    present_14 = any(abs(cval - 0.25) < 1e-9 for cval in centers)
    present_415 = any(abs(cval - 4.0 / 15.0) < 1e-9 for cval in centers)
    present_12 = any(abs(cval - 0.5) < 1e-9 for cval in centers)
    gate("CMP1",
         min_to_ninth > 1e-6 and present_14 and present_415 and present_12,
         f"L=4 value 1/9 absent at L=6 (min|omega-1/9| {min_to_ninth:.3f}); "
         f"L=6 gains 1/4 {present_14}, 4/15 {present_415}, 1/2 {present_12} (not in L=4 set)")

    # ===== CHARACTER: Dchi value set and the U22 inversion =====
    dchi_centers = cluster([r[6] for r in rows], tol=1e-6)
    dchi_set = sorted(round(c) for c in dchi_centers)
    nz = set(r[0] for r in rows if abs(r[6]) > 1e-6)
    nz_el = sum(r[1] for r in rows if r[0] in nz)
    plus6 = [r for r in rows if abs(r[6] - 6.0) < 1e-6]
    minus6 = [r for r in rows if abs(r[6] + 6.0) < 1e-6]
    nz_rows = [r for r in rows if r[0] in nz]
    gate("CHR1",
         dchi_set == [-6, 0, 6]
         and len(plus6) == 2 and sum(r[1] for r in plus6) == 144
         and len(minus6) == 2 and sum(r[1] for r in minus6) == 144
         and len(nz) == 4 and nz_el == 288
         and all(r[1] == 72 and r[2] == 108 for r in nz_rows),
         f"Dchi set {dchi_set}; +6 on 2 classes/144 el, -6 on 2 classes/144 el; "
         f"|Dchi!=0|={len(nz)} classes/{nz_el} el, each size 72 dim 108")

    third = set(r[0] for r in rows if abs(r[4] - 1.0 / 3.0) < 1e-6)
    subset = nz <= third
    proper = nz < third
    counterex = sorted(third - nz)
    ce_rows = [r for r in rows if r[0] in counterex]
    gate("CHR2",
         subset and proper and len(counterex) == 1
         and all(abs(r[6]) <= 1e-9 and abs(r[4] - 1.0 / 3.0) < 1e-6
                 and r[1] == 12 and r[2] == 68 for r in ce_rows),
         f"{{Dchi!=0}} (n={len(nz)}) is a PROPER subset of {{omega=1/3}} (n={len(third)}); "
         f"counterexample class size {ce_rows[0][1]} dim {ce_rows[0][2]} has omega=1/3, "
         f"Dchi={ce_rows[0][6]:+.1e} (L=4 equality does not survive)")

    # ===== UNLOCK: minimal reaching stratum and the g1 core =====
    wmax = max(r[4] for r in rows)
    maxrows = [r for r in rows if abs(r[4] - wmax) < 1e-6]
    minsize = min(r[1] for r in maxrows)
    gate("UNL1",
         abs(wmax - 1.0) < 1e-9 and len(maxrows) == 3
         and sorted(r[1] for r in maxrows) == [4, 144, 144] and minsize == 4,
         f"max omega {wmax:.12f} on 3 classes sizes {sorted(r[1] for r in maxrows)}; "
         f"minimal reaching class size {minsize}")

    # g1 = diag((-1)^x1) . T(1,1,1), linear part identity
    def sfn_x1(x):
        return (-1) ** (int(x[1]) % 2)

    def fmap_g1(x):
        return (int(x[0]) + 1, int(x[1]) + 1, int(x[2]) + 1)

    g1 = sp_from_fmap(fmap_g1, sfn_x1, coords, idx, N)
    g1_inG = key(g1) in Gkeys
    g1_comm = commutes_with_D2(g1, D2)
    g1_orbit = orbit_size(g1, conj_gens)
    Ug1 = dense_from_sp(g1[0], g1[1].astype(float), N)
    Bg1, dim_g1, closed_g1 = word_algebra_real([D2f, Jfull, Seps, Ug1], N, cap=600)
    w_g1 = (np.linalg.norm(Bg1 @ sep_re) ** 2 + np.linalg.norm(Bg1 @ sep_im) ** 2) / sep_norm2
    del Bg1
    gc.collect()
    gate("UNL2",
         g1_inG and g1_comm and g1_orbit == 4 and dim_g1 == 68
         and closed_g1 and abs(w_g1 - 1.0) < 1e-9,
         f"g1=diag((-1)^x1).T(1,1,1): in G_amb {g1_inG}, [g1,D2]=0 {g1_comm}, class size "
         f"{g1_orbit}, dim<A_nat,g1>={dim_g1}, omega={w_g1:.12f}")

    # Wedderburn of <A_nat, g1>: sep6 as a difference of two minimal central idempotents.
    # RNG-free extraction: use the spectral projectors of sep6 itself (eigenvalues +/-1),
    # then count how many minimal central idempotents each covers via the center of the
    # orthonormalized compressed corner algebra (a true block count).
    Bg1w, closed_g1w = word_algebra([D2f, Jfull, Seps, Ug1], N, cap=200)
    Xg1 = [row.reshape(N, N) for row in Bg1w]
    Zg1, zdim_g1 = center_of(Xg1, [D2f, Jfull, Seps, Ug1], tol=1e-9)

    def ortho_mats(mats):
        Vf = np.stack([m.reshape(-1) for m in mats])
        _, s, Vh = np.linalg.svd(Vf, full_matrices=False)
        r = int(np.sum(s > 1e-8 * s[0]))
        return [Vh[i].reshape(mats[0].shape) for i in range(r)]

    def corner_center_dim(P):
        ev, V = np.linalg.eigh((P + P.conj().T) / 2)
        cols = V[:, ev > 0.5]
        Xc = ortho_mats([cols.conj().T @ x @ cols for x in Xg1])
        _, zc = center_of(Xc, Xc, tol=1e-9)
        return zc, cols.shape[1]

    def spectral_projector(H, target, tol=1e-6):
        ev, V = np.linalg.eigh((H + H.conj().T) / 2)
        cols = V[:, np.abs(ev - target) < tol]
        return cols @ cols.conj().T

    Pplus = spectral_projector(sep6, +1.0)
    Pminus = spectral_projector(sep6, -1.0)
    rank_plus = int(round(np.trace(Pplus).real))
    rank_minus = int(round(np.trace(Pminus).real))
    plus_central = max(float(np.linalg.norm(Pplus @ x - x @ Pplus)) for x in Xg1)
    minus_central = max(float(np.linalg.norm(Pminus @ x - x @ Pminus)) for x in Xg1)
    recon_resid = float(np.linalg.norm((Pplus - Pminus) - sep6))
    zc_plus, _ = corner_center_dim(Pplus)
    zc_minus, _ = corner_center_dim(Pminus)
    zc_comb, _ = corner_center_dim(Pplus + Pminus)   # rank-16 rejector: must resolve 2 blocks
    gate("UNL3",
         zdim_g1 == 17 and closed_g1w
         and rank_plus == 8 and rank_minus == 8
         and plus_central < 1e-6 and minus_central < 1e-6
         and recon_resid < 1e-6
         and zc_plus == 1 and zc_minus == 1 and zc_comb == 2,
         f"dim Z(<A_nat,g1>)={zdim_g1}; sep6 = e_a - e_b (resid {recon_resid:.1e}), e_a,e_b central "
         f"(max comm {max(plus_central, minus_central):.1e}), each a single minimal central "
         f"idempotent of rank {rank_plus}={rank_minus}; corner-center counts e_a->{zc_plus}, "
         f"e_b->{zc_minus}, (e_a+e_b, rank 16)->{zc_comb} (rejector resolves 2 blocks)")

    # ===== DIAL: fix sign field (-1)^x1 and linear part I, vary translation =====
    dial_targets = [((1, 1, 1), 1.0), ((1, 1, 3), 0.5), ((1, 1, 5), 1.0 / 3.0),
                    ((3, 3, 3), 0.25), ((1, 1, 0), 0.0)]
    dial_ok = True
    dial_report = []
    for tvec, wexp in dial_targets:
        def fmap_t(x, tvec=tvec):
            return (int(x[0]) + tvec[0], int(x[1]) + tvec[1], int(x[2]) + tvec[2])
        gt = sp_from_fmap(fmap_t, sfn_x1, coords, idx, N)
        inG = key(gt) in Gkeys
        comm = commutes_with_D2(gt, D2)
        Ut = dense_from_sp(gt[0], gt[1].astype(float), N)
        Bt, dt, ct = word_algebra_real([D2f, Jfull, Seps, Ut], N, cap=600)
        wt = (np.linalg.norm(Bt @ sep_re) ** 2 + np.linalg.norm(Bt @ sep_im) ** 2) / sep_norm2
        del Bt
        gc.collect()
        dial_report.append((tvec, dt, wt))
        if not (inG and comm and abs(wt - wexp) < 1e-6):
            dial_ok = False
    dial_omegas = sorted(set(round(r[2], 6) for r in dial_report))
    gate("DIAL1", dial_ok and dial_omegas == [0.0, 0.25, round(1.0 / 3.0, 6), 0.5, 1.0],
         f"fixed sign (-1)^x1, linear part I: translation alone sweeps omega "
         f"{[(t, round(w,6)) for (t,_,w) in dial_report]}")

    # ===== PERTURBATION: wrong separator P8a (rank-8, not a difference) =====
    P8a_c = P8a
    P8a_re = np.real(P8a_c).reshape(-1)
    P8a_im = np.imag(P8a_c).reshape(-1)
    P8a_n2 = float(np.linalg.norm(P8a_c) ** 2)
    ov_anat_p8a = overlap2(Bnat, P8a_c)
    # identity class (trivial G element): omega must read 0 for sep6, non-0 for P8a
    Uid = np.eye(N)
    Bid, _, _ = word_algebra_real([D2f, Jfull, Seps, Uid], N, cap=600)
    w_id_sep6 = (np.linalg.norm(Bid @ sep_re) ** 2 + np.linalg.norm(Bid @ sep_im) ** 2) / sep_norm2
    w_id_p8a = (np.linalg.norm(Bid @ P8a_re) ** 2 + np.linalg.norm(Bid @ P8a_im) ** 2) / P8a_n2
    del Bid
    gc.collect()
    flips = []
    if ov_anat_sep6 <= 1e-10 < ov_anat_p8a:
        flips.append("S4-blindness (overlap^2 A_nat: sep6 %.1e -> P8a %.4f)"
                     % (ov_anat_sep6, ov_anat_p8a))
    if w_id_sep6 <= 1e-9 < w_id_p8a:
        flips.append("CN[omega=0] identity class (sep6 %.1e -> P8a %.4f)"
                     % (w_id_sep6, w_id_p8a))
    print(f"\n[PERT] wrong separator P8a flips: {flips}", flush=True)
    gate("PERT1",
         ov_anat_p8a > 1e-2 and abs(w_id_p8a - 0.125) < 1e-6
         and w_id_sep6 <= 1e-9 and len(flips) == 2,
         f"P8a not blind (overlap^2 {ov_anat_p8a:.4f}); identity class omega: sep6 "
         f"{w_id_sep6:.1e} vs P8a {w_id_p8a:.4f}; {len(flips)} gates flip -> runner discriminates")

    # -------------------- summary --------------------
    dt = time.time() - t_start
    print(f"\n[info] wall-clock {dt:.1f}s, peak RSS {rss_gb():.2f} GB", flush=True)
    print(f"TOTAL: PASS={_P[0]} FAIL={_F[0]}", flush=True)
    sys.exit(0 if _F[0] == 0 else 1)


if __name__ == "__main__":
    main()
