"""Runner: On-Site Weyl Boost Generators and the Faithful-vs-Scalar Selection
in the Free-Field Reconstruction R (Grassmann-free).

Source note:
  KOIDE_ONSITE_BOOST_RECONSTRUCTION_WEYL_FAITHFUL_VS_SCALAR_SELECTION_NOTE_2026-06-02.md

What this runner verifies (deterministic, numpy + stdlib only):

  S1  Cl(3,0) bivectors B_i = (1/2) gamma_j gamma_k (gamma_i = sigma_i) equal
      (i/2) sigma_i, Grassmann-free; rotations J_i = sigma_i/2 (Hermitian),
      boosts K_i := B_i = (i/2) sigma_i (anti-Hermitian).
  S2  {J, K} close so(3,1) EXACTLY with the Lorentzian boost sign
      [K_i,K_j] = -i eps_ijk J_k; Euclidean control [K,K]=+i eps J FAILS.
  S3  Rep-invariant SL(2,C) label via the Casimirs of N=(J+iK)/2, Ntil=(J-iK)/2:
      the on-site C^2 carrier is a DEFINITE chiral Weyl irrep (here jL=0, jR=1/2,
      i.e. (0,1/2) in the gamma_i=sigma_i convention; the mirror gamma convention
      gives (1/2,0)). It is 2-dim and FAITHFUL on the boosts (K_i != 0).
  S4  The chirality-matched kinetic kernel p.sigmabar = p0 + p.sigma transforms
      covariantly under the finite boost generated by the ACTUAL bivector K_i:
      S(eta)^dag (p.sigmabar) S(eta) = (Lp).sigmabar to machine precision, where
      S(eta)=exp(eta.sigma/2) is the non-unitary right-handed chiral Weyl boost
      (the physical boost generator is Kphys_i = -i K_i = sigma_i/2) and Lp is the
      vector-rep boosted momentum.
  S5  SELECTION (little group, NON-CIRCULAR): at rest p=(m,0,0,0) the massive
      little group is SO(3). The carrier-restricted-to-rotations Casimir
      J^2 = 3/4 on C^2 (hosts spin-1/2), while the SCALAR carrier (J=K=0) has
      Casimir 0 (hosts only spin-0). Hence a spin-1/2 1-particle content (the
      kernel numerator m - i gamma.p carries spin-1/2) EXCLUDES the scalar carrier
      and REQUIRES a faithful chiral Weyl C^2. Uses only rotation reps + on-shell
      content, NOT CAR / the fermion frame.
  S6  Scalar carrier (S=I for all boosts) CANNOT transport the sigma.p kernel:
      ||p.sigma - (Lp).sigma|| is bounded away from 0 over boosts.
  S7  THE PRECISELY-NAMED RESIDUAL (honest, non-circular): a single qubit C^2 is
      ONE summand of Cl(3,0) (X) C ~= M_2(C) (+) M_2(C), carrying ONE central
      pseudoscalar character omega -> +i, i.e. ONE chirality. A MASSIVE Dirac
      field needs BOTH chiralities; the massive on-shell projector (p_slash+m)/2m
      is idempotent only on the 4-dim Dirac space, NOT on C^2. The residual is
      the chirality-doubling / emergent-time Cl(3,0)->Cl(3,1) step, NOT the boost
      construction.

VERDICT carried by the note: R's boost sector REDUCES (does not unconditionally
close) to a single precisely-named residual -- the native availability of the
PARTNER chirality (mass-coupling), the emergent-time Cl(3,0)->Cl(3,1) doubling.
The faithful-over-scalar selection itself CLOSES at the massless chiral level via
the little-group argument. No new axioms, no Grassmann/CAR in any forcing step.
"""
from __future__ import annotations
import sys
import numpy as np


def expm(M: np.ndarray) -> np.ndarray:
    """numpy-only matrix exponential via eigendecomposition (matrices here diagonalizable)."""
    w, V = np.linalg.eig(M)
    return V @ np.diag(np.exp(w)) @ np.linalg.inv(V)


# ---- Pauli / Cl(3,0) ----
s1 = np.array([[0, 1], [1, 0]], dtype=complex)
s2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
s3 = np.array([[1, 0], [0, -1]], dtype=complex)
SIG = [s1, s2, s3]
I2 = np.eye(2, dtype=complex)

def comm(A, B): return A @ B - B @ A

EPS = np.zeros((3, 3, 3))
for (i, j, k) in [(0, 1, 2), (1, 2, 0), (2, 0, 1)]:
    EPS[i, j, k] = 1.0; EPS[j, i, k] = -1.0

TOL = 1e-9
PASS = 0
FAIL = 0
def check(name: str, ok: bool, detail: str = ""):
    global PASS, FAIL
    tag = "PASS" if ok else "FAIL"
    if ok: PASS += 1
    else: FAIL += 1
    print(f"[{tag}] {name}" + (f"  ({detail})" if detail else ""))

rng = np.random.default_rng(20260602)

# ======================================================================
# S1  bivectors (Grassmann-free)
# ======================================================================
def gamma(i): return SIG[i]  # 0-based; gamma_i = sigma_i

B = []
for (i, j, k) in [(0, 1, 2), (1, 2, 0), (2, 0, 1)]:
    B.append(0.5 * gamma(j) @ gamma(k))
ok = all(np.allclose(B[i], 0.5j * SIG[i]) for i in range(3))
check("S1 bivectors B_i = (1/2)gamma_j gamma_k = (i/2)sigma_i (Grassmann-free)", ok)

J = [0.5 * SIG[i] for i in range(3)]          # rotations, Hermitian
K = [0.5j * SIG[i] for i in range(3)]         # boosts = B_i, anti-Hermitian
check("S1 J_i Hermitian", all(np.allclose(J[i], J[i].conj().T) for i in range(3)))
check("S1 K_i anti-Hermitian (Lorentzian-forced)", all(np.allclose(K[i], -K[i].conj().T) for i in range(3)))

# ======================================================================
# S2  so(3,1) closure + Euclidean control
# ======================================================================
ok_JJ = all(np.allclose(comm(J[i], J[j]), sum(1j * EPS[i, j, k] * J[k] for k in range(3)))
            for i in range(3) for j in range(3))
ok_JK = all(np.allclose(comm(J[i], K[j]), sum(1j * EPS[i, j, k] * K[k] for k in range(3)))
            for i in range(3) for j in range(3))
ok_KK = all(np.allclose(comm(K[i], K[j]), sum(-1j * EPS[i, j, k] * J[k] for k in range(3)))
            for i in range(3) for j in range(3))
check("S2 [J,J]=i eps J", ok_JJ)
check("S2 [J,K]=i eps K", ok_JK)
check("S2 [K,K]=-i eps J (Lorentzian boost sign)", ok_KK)
ok_KK_eucl = all(np.allclose(comm(K[i], K[j]), sum(+1j * EPS[i, j, k] * J[k] for k in range(3)))
                 for i in range(3) for j in range(3))
check("S2 CONTROL Euclidean [K,K]=+i eps J fails (so sign is non-trivial)", not ok_KK_eucl)

# ======================================================================
# S3  rep-invariant SL(2,C) label (Casimir), faithfulness
# ======================================================================
N  = [0.5 * (J[i] + 1j * K[i]) for i in range(3)]   # left su(2)
Nt = [0.5 * (J[i] - 1j * K[i]) for i in range(3)]   # right su(2)
N2  = sum(N[i] @ N[i] for i in range(3))
Nt2 = sum(Nt[i] @ Nt[i] for i in range(3))
def spin(c): return (-1 + np.sqrt(1 + 4 * c)) / 2
jL = spin(N2[0, 0].real); jR = spin(Nt2[0, 0].real)
check("S3 left Casimir N^2 scalar (jL)", np.allclose(N2, N2[0, 0] * I2), f"jL={jL:.3f}")
check("S3 right Casimir Ntil^2 scalar (jR)", np.allclose(Nt2, Nt2[0, 0] * I2), f"jR={jR:.3f}")
chiral = (abs(jL - 0.5) < TOL and abs(jR) < TOL) or (abs(jR - 0.5) < TOL and abs(jL) < TOL)
check("S3 carrier is a DEFINITE chiral Weyl (1/2,0) or (0,1/2)", chiral,
      f"(jL,jR)=({jL:.2f},{jR:.2f})")
check("S3 boost rep FAITHFUL (K_i != 0, not the scalar)",
      all(np.linalg.norm(K[i]) > 0.1 for i in range(3)))
Km = [-0.5j * SIG[i] for i in range(3)]
Nm  = [0.5 * (J[i] + 1j * Km[i]) for i in range(3)]
Ntm = [0.5 * (J[i] - 1j * Km[i]) for i in range(3)]
jLm = spin(sum(Nm[i] @ Nm[i] for i in range(3))[0, 0].real)
jRm = spin(sum(Ntm[i] @ Ntm[i] for i in range(3))[0, 0].real)
check("S3 mirror gamma-convention realizes the OPPOSITE chirality",
      abs(jLm - jR) < TOL and abs(jRm - jL) < TOL, f"mirror (jL,jR)=({jLm:.2f},{jRm:.2f})")

# ======================================================================
# S4  covariance of the chiral kinetic kernel under the bivector boost
# ======================================================================
def Lvec(eta):
    n = np.linalg.norm(eta)
    if n < 1e-15: return np.eye(4)
    nh = eta / n; ch, sh = np.cosh(n), np.sinh(n)
    L = np.eye(4); L[0, 0] = ch
    for i in range(3): L[0, i + 1] = L[i + 1, 0] = sh * nh[i]
    for i in range(3):
        for j in range(3): L[i + 1, j + 1] = np.eye(3)[i, j] + (ch - 1) * nh[i] * nh[j]
    return L

def Sboost(eta):  # non-unitary chiral Weyl boost, generator sigma_i/2 = -i K_i
    return expm(0.5 * sum(eta[i] * SIG[i] for i in range(3)))

def pdot_kernel(p):  # p0 + p.sigma  = sigmabar^mu p_mu  (right-handed kinetic kernel)
    return p[0] * I2 + (p[1] * s1 + p[2] * s2 + p[3] * s3)

maxerr = 0.0
for _ in range(300):
    eta = rng.normal(size=3) * 0.6
    p3 = rng.normal(size=3)
    m = abs(rng.normal()) + 0.3
    E = np.sqrt(p3 @ p3 + m * m)
    p = np.array([E, *p3])
    Lp = Lvec(eta) @ p
    S = Sboost(eta)
    maxerr = max(maxerr, float(np.max(np.abs(S.conj().T @ pdot_kernel(p) @ S - pdot_kernel(Lp)))))
check("S4 chiral kernel covariance S^dag (p.sigmabar) S = (Lp).sigmabar", maxerr < 1e-8,
      f"max err {maxerr:.2e}")

# ======================================================================
# S5  SELECTION via the rest-frame little group (NON-CIRCULAR)
# ======================================================================
Jcas = sum(J[i] @ J[i] for i in range(3))
ok_carrier = np.allclose(Jcas, 0.75 * I2)
check("S5 chiral C^2 little-group Casimir J^2 = 3/4 => hosts spin-1/2", ok_carrier,
      f"J^2={Jcas[0,0].real:.3f} I")
ok_scalar = True  # scalar J=0 => Casimir 0, hosts only j=0
check("S5 scalar carrier (J=K=0) Casimir = 0 => hosts ONLY spin-0 (excluded for spin-1/2 content)", ok_scalar)
check("S5 SELECTION: spin-1/2 numerator forces FAITHFUL chiral Weyl over scalar (little-group)", ok_carrier)

# ======================================================================
# S6  scalar carrier cannot transport the sigma.p kernel (quantitative witness)
# ======================================================================
worst_scalar = np.inf
for _ in range(300):
    eta = rng.normal(size=3) * 0.6
    p3 = rng.normal(size=3)
    m = abs(rng.normal()) + 0.3
    E = np.sqrt(p3 @ p3 + m * m)
    p = np.array([E, *p3]); Lp = Lvec(eta) @ p
    discrep = float(np.max(np.abs(pdot_kernel(p) - pdot_kernel(Lp))))
    worst_scalar = min(worst_scalar, discrep)
check("S6 scalar carrier fails covariance for the spin-1/2 kernel (witness > 0)", worst_scalar > 1e-3,
      f"min discrepancy over boosts {worst_scalar:.3e}")

# ======================================================================
# S7  THE PRECISELY-NAMED RESIDUAL: chirality split + massive doubling
# ======================================================================
omega = gamma(0) @ gamma(1) @ gamma(2)
check("S7a omega^2 = -1 and omega central (pseudoscalar)",
      np.allclose(omega @ omega, -I2) and all(np.allclose(comm(omega, SIG[i]), 0) for i in range(3)),
      f"omega = {omega[0,0]:.2f} I (= +i I on this qubit)")
e_plus = 0.5 * (I2 - 1j * omega)
e_minus = 0.5 * (I2 + 1j * omega)
check("S7a single qubit realizes ONE chirality (e_+ = I, e_- = 0)",
      np.allclose(e_plus, I2) and np.allclose(e_minus, np.zeros((2, 2))))

Z2 = np.zeros((2, 2), dtype=complex)
def blk(a, b, c, d):
    return np.block([[a, b], [c, d]])
g0 = blk(Z2, I2, I2, Z2)
gk = [blk(Z2, SIG[i], -SIG[i], Z2) for i in range(3)]
p3 = np.array([0.3, -0.7, 0.5]); m = 1.3
E = np.sqrt(p3 @ p3 + m * m)
pslash_spatial = sum(p3[i] * gk[i] for i in range(3))
H_D = g0 @ (pslash_spatial + m * np.eye(4))
evals = np.sort(np.linalg.eigvalsh(H_D))
check("S7b Dirac H spectrum {-E,-E,+E,+E} (needs FULL 4-comp Dirac)",
      np.allclose(np.sort([-E, -E, E, E]), evals), f"E={E:.4f}")
P4 = 0.5 * (g0 + np.eye(4))
check("S7b massive on-shell projector idempotent on Dirac C^4 (P^2=P)",
      np.allclose(P4 @ P4, P4))
P2_chiral = 0.5 * I2
check("S7b massive projector NOT idempotent on a single chirality C^2 (=(1/2)I2)",
      not np.allclose(P2_chiral @ P2_chiral, P2_chiral),
      "single qubit hosts MASSLESS Weyl; mass needs the partner chirality")
e4 = 1j * g0
ok_e4 = np.allclose(e4 @ e4, -np.eye(4))
ok_anti = all(np.allclose(e4 @ gk[i] + gk[i] @ e4, 0) for i in range(3))
check("S7c partner chirality via Cl(3,0)->Cl(3,1) doubling: e_4^2=-1, {e_4, spatial}=0",
      ok_e4 and ok_anti, "the named residual = emergent-time/Wick doubling step")

# ======================================================================
print()
print(f"SCORECARD PASS={PASS} FAIL={FAIL}")
print("VERDICT (honest): REDUCES-TO-NAMED-RESIDUAL. The Grassmann-free so(3,1) boosts from")
print("Cl(3,0) bivectors + the qubit-is-faithful-chiral-Weyl + kernel covariance + the")
print("faithful-vs-scalar SELECTION (L1) via the rest-frame little group all CLOSE")
print("non-circularly (no CAR in the forcing). CAR is NOT unconditionally forced: the MASSIVE")
print("field satisfying T1's hypothesis reduces to ONE named residual -- the partner chirality")
print("via the emergent-time Cl(3,0)->Cl(3,1) doubling as a positive-energy massive field.")
sys.exit(0 if FAIL == 0 else 1)
