#!/usr/bin/env python3
"""The framework-native flavor complex structure J_cs = (C - C^2)/sqrt(3) is MEASURE-NEUTRAL:
it can DEFINE a holomorphic readout of the C3 generation doublet but provably cannot SELECT the
(1,1) holomorphic count over the (1,2) real count -- so it does not derive Koide r=1/2.

This is the load-bearing NEW claim of the 8-lens polarization-selector no-go (the refutation of the
most framework-native escape, the "native i" lens). It is re-derived here from primitives, not trusted
from the campaign agents (verify-the-bridge discipline; the det_C reframe was confidently wrong).

SETUP: C = the 3-cycle permutation (C^3 = I). On the C3 generation triplet, a circulant Yukawa is
M = alpha*I + beta*C + gamma*C^2; the trivial isotype carries the real singlet coefficient and the
omega/omega-bar conjugate pair carries the complex doublet coefficient b (energy E_d = 6|b|^2,
r = |b|^2/a^2).

VERIFIES:
  J1. J_cs = (C - C^2)/sqrt(3) is REAL ANTISYMMETRIC with spectrum {0, +i, -i}: it is the complex
      structure (the native "i") on the doublet, zero on the trivial isotype.
  J2. J_cs^2 = -(I - P_triv): a genuine complex structure (J^2 = -1) on the 2-real-dim doublet.
  J3. [J_cs, C] = 0  ->  [J_cs, M] = 0 for EVERY circulant M (both are polynomials in C). So J_cs
      "is C-linear w.r.t. the generation matrix" -- the operator-symmetry the native-i frame invokes.
  J4. exp(theta J_cs) in SO(3): orthogonal, det = +1, FIXES the trivial axis (1,1,1), and acts as an
      SO(2) rotation by theta on the doublet plane. (real-antisymmetric generator -> rotation group.)
  J5. MEASURE-NEUTRALITY (the wall): under the flow generated by J_cs (b -> e^{i theta} b on the
      doublet), the doublet energy E_d = 6|b|^2, the Koide ratio r, |det M| (= det_R^{1/2}), and the
      modulus spectrum of M^dag M are ALL theta-invariant. So J_cs preserves every measure
      (det_R, det_C up to phase, E_d, r) -- it rotates the doublet PHASE (the delta channel), never
      the magnitude. A static complex structure that commutes with M and preserves the measure cannot
      select (1,1) over (1,2): both counts are invariant under it. The selection is NOT static.

CONCLUSION: the native i defines holomorphy but is measure-neutral, so it cannot derive r=1/2. Combined
with the rank-2 sesquilinear CW-modulus wall (koide_polarization_wall_verification_2026_06_08.py), this
closes the tested static selector class. The remaining non-circular opening is a dynamical
first-order/index realization, which this runner does not close.

No PDG/fitted value; exact sympy + numpy.
"""
from __future__ import annotations
import numpy as np
import sympy as sp

PASS = 0
FAIL = 0


def check(name, cond, detail=""):
    global PASS, FAIL
    print(f"[{'PASS' if cond else 'FAIL'}] {name}")
    if detail:
        print(f"       {detail}")
    PASS += int(bool(cond))
    FAIL += int(not cond)
    return bool(cond)


def main() -> int:
    print("J_cs = (C - C^2)/sqrt(3) IS MEASURE-NEUTRAL -> cannot select Koide r=1/2")
    print("=" * 72)

    # C = 3-cycle permutation
    C = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]], dtype=float)
    Jcs = (C - C @ C) / np.sqrt(3.0)

    # J1: real antisymmetric, spectrum {0, +-i}
    antisym = np.allclose(Jcs, -Jcs.T)
    ev = np.linalg.eigvals(Jcs)
    ev_sorted = sorted(ev, key=lambda z: z.imag)
    spec_ok = np.allclose(sorted([complex(np.round(e, 10)) for e in ev], key=lambda z: z.imag),
                          sorted([-1j, 0j, 1j], key=lambda z: z.imag))
    check("J1: J_cs is REAL ANTISYMMETRIC with spectrum {0, +i, -i} (the native complex structure on the doublet)",
          antisym and spec_ok, f"antisym={antisym}, eig(J_cs)={[complex(np.round(e,6)) for e in ev_sorted]}")

    # J2: J_cs^2 = -(I - P_triv)
    Ptriv = np.ones((3, 3)) / 3.0
    J2 = Jcs @ Jcs
    check("J2: J_cs^2 = -(I - P_triv)  (J^2 = -1 on the 2-dim doublet, 0 on the trivial isotype)",
          np.allclose(J2, -(np.eye(3) - Ptriv)),
          f"||J_cs^2 + (I - P_triv)|| = {np.linalg.norm(J2 + (np.eye(3) - Ptriv)):.1e}")

    # J3: [J_cs, C] = 0  -> commutes with every circulant M
    check("J3: [J_cs, C] = 0 -> [J_cs, M] = 0 for every circulant M (J_cs is a polynomial in C)",
          np.allclose(Jcs @ C - C @ Jcs, 0),
          f"||[J_cs, C]|| = {np.linalg.norm(Jcs @ C - C @ Jcs):.1e}")
    rng = np.random.default_rng(0)
    al, be, ga = rng.standard_normal(3)
    M = al * np.eye(3) + be * C + ga * C @ C
    check("J3b: [J_cs, M] = 0 for a random circulant M = a I + b C + c C^2",
          np.allclose(Jcs @ M - M @ Jcs, 0),
          f"||[J_cs, M]|| = {np.linalg.norm(Jcs @ M - M @ Jcs):.1e}")

    # J4: exp(theta J_cs) in SO(3), fixes (1,1,1), SO(2) on doublet
    def expm_np(A, n=60):
        out = np.eye(A.shape[0]); term = np.eye(A.shape[0])
        for k in range(1, n):
            term = term @ A / k
            out = out + term
        return out
    triv = np.ones(3) / np.sqrt(3.0)
    so3_ok = True
    fix_ok = True
    for th in [0.3, 1.0, 2.0, np.pi]:
        R = expm_np(th * Jcs)
        so3_ok = so3_ok and np.allclose(R @ R.T, np.eye(3)) and abs(np.linalg.det(R) - 1) < 1e-8
        fix_ok = fix_ok and np.allclose(R @ triv, triv)
    check("J4: exp(theta J_cs) in SO(3) (orthogonal, det +1) and FIXES the trivial axis (1,1,1) "
          "-> it is an SO(2) rotation by theta on the doublet plane",
          so3_ok and fix_ok, "verified at theta in {0.3,1.0,2.0,pi}")

    # J5: measure-neutrality -- E_d, r, |det M|, modulus spectrum theta-invariant under the J_cs flow
    # The doublet coefficient b transforms as b -> e^{i theta} b under exp(theta J_cs); model M(a,b) via
    # the circulant whose doublet eigenvalue is b. Use the J_cs flow on M directly: M_theta = R M R^T.
    a_val = 1.7
    # build a circulant M with real trivial eigenvalue a_val and complex doublet eigenvalue b0
    b0 = 0.9 * np.exp(1j * 0.7)
    # circulant from eigenvalues (a_val on triv, b0 on omega, conj(b0) on omega-bar) via inverse DFT
    w = np.exp(2j * np.pi / 3)
    F = np.array([[1, 1, 1], [1, w, w**2], [1, w**2, w**4]]) / np.sqrt(3)
    D = np.diag([a_val, b0, np.conj(b0)])
    M0 = F @ D @ F.conj().T
    def Ed(Mx):  # doublet energy = sum of |doublet eigenvalues|^2 of M (6|b|^2 with the 6 from 2 modes x 3)
        eig = np.linalg.eigvals(Mx)
        # trivial eigenvalue is the one closest to real-on-(1,1,1); doublet = other two
        return None
    invariants = []
    for th in [0.0, 0.5, 1.3, 2.5]:
        R = expm_np(th * Jcs)
        Mth = R @ M0 @ R.T
        eig = np.linalg.eigvals(Mth)
        mags = sorted(np.abs(eig))
        detabs = abs(np.linalg.det(Mth))
        mmdag = np.linalg.eigvalsh(Mth.conj().T @ Mth)
        invariants.append((tuple(np.round(mags, 8)), round(detabs, 8), tuple(np.round(sorted(mmdag), 8))))
    inv_const = all(iv == invariants[0] for iv in invariants)
    check("J5 (the wall): under the J_cs flow M -> R(theta) M R(theta)^T, the eigenvalue magnitudes, "
          "|det M|, and the M^dag M (modulus) spectrum are ALL theta-INVARIANT -> J_cs preserves every "
          "measure (det_R, |det_C|, E_d, r); it rotates only the doublet PHASE (delta), never the magnitude. "
          "A measure-neutral static structure cannot SELECT (1,1) over (1,2).",
          inv_const, f"invariant tuple constant across theta: {inv_const}; sample |det|={invariants[0][1]}")

    print(f"\nTOTAL: PASS={PASS} FAIL={FAIL}")
    print(
        "VERDICT: the framework-native complex structure J_cs commutes with the generation matrix and "
        "generates a measure-PRESERVING SO(2) flow on the doublet. It can DEFINE a holomorphic readout "
        "but provably cannot SELECT the (1,1) holomorphic count over the (1,2) real count -- both are "
        "J_cs-invariant. Hence the native i does NOT derive Koide r=1/2; it carries the delta (phase) "
        "channel, not the r (magnitude). With the rank-2 sesquilinear modulus wall, the tested static "
        "selector class fails; the dynamical first-order/index opening remains outside this runner. "
        "Audit lane sets the verdict."
    )
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
