"""Two-step lattice translation sector conservation check.

This runner verifies the repaired scope of
LATTICE_TOTAL_MOMENTUM_CONSERVATION_THEOREM_NOTE_2026-05-02.md.

It intentionally does not test or claim a canonical momentum density
P_x, a local divergence identity, full one-step momentum quantization,
or an H_phys reconstruction bridge.  The retained claim is only the
finite two-step translation-sector statement supplied by the repaired
lattice Noether surface.
"""
from __future__ import annotations

import numpy as np


TOL = 1e-10


def shift_matrix(length: int, step: int) -> np.ndarray:
    """Return the unitary cyclic shift |x> -> |x + step>."""
    mat = np.zeros((length, length), dtype=complex)
    for x in range(length):
        mat[(x + step) % length, x] = 1.0
    return mat


def hermitian_two_step_invariant_hamiltonian(length: int, seed: int = 20260525) -> np.ndarray:
    """Build a nontrivial Hermitian operator invariant under T_2 only."""
    rng = np.random.default_rng(seed)
    raw = rng.standard_normal((length, length)) + 1j * rng.standard_normal((length, length))
    hermitian = (raw + raw.conj().T) / 2

    t2 = shift_matrix(length, 2)
    order = length // np.gcd(length, 2)
    averaged = np.zeros_like(hermitian)
    power = np.eye(length, dtype=complex)
    for _ in range(order):
        averaged += power @ hermitian @ power.conj().T
        power = t2 @ power
    averaged /= order
    return (averaged + averaged.conj().T) / 2


def cyclic_projectors(generator: np.ndarray, order: int) -> list[np.ndarray]:
    """Projectors for the cyclic group generated by generator."""
    powers = [np.eye(generator.shape[0], dtype=complex)]
    for _ in range(1, order):
        powers.append(generator @ powers[-1])

    projectors = []
    for k in range(order):
        proj = np.zeros_like(generator, dtype=complex)
        for m, power in enumerate(powers):
            phase = np.exp(-2j * np.pi * k * m / order)
            proj += phase * power
        projectors.append(proj / order)
    return projectors


def unitary_from_hermitian(hamiltonian: np.ndarray, time: float) -> np.ndarray:
    vals, vecs = np.linalg.eigh(hamiltonian)
    phases = np.exp(-1j * time * vals)
    return vecs @ np.diag(phases) @ vecs.conj().T


def max_norm(mats) -> float:
    return max(float(np.linalg.norm(mat)) for mat in mats)


def main() -> None:
    print("=" * 72)
    print("TWO-STEP LATTICE TRANSLATION SECTOR CHECK")
    print("=" * 72)
    print()

    length = 8
    order = length // np.gcd(length, 2)
    t1 = shift_matrix(length, 1)
    t2 = shift_matrix(length, 2)
    hamiltonian = hermitian_two_step_invariant_hamiltonian(length)

    print(f"finite ring length L_s = {length}")
    print(f"two-step cyclic order N_2 = {order}")
    print()

    print("-" * 72)
    print("TEST 1: finite two-step translation group and projectors")
    print("-" * 72)
    projectors = cyclic_projectors(t2, order)
    closure_resid = float(np.linalg.norm(np.linalg.matrix_power(t2, order) - np.eye(length)))
    idempotent_resid = max_norm([p @ p - p for p in projectors])
    orthogonal_resid = max_norm(
        [projectors[i] @ projectors[j] for i in range(order) for j in range(order) if i != j]
    )
    resolution_resid = float(np.linalg.norm(sum(projectors) - np.eye(length)))
    eigen_resid = max_norm(
        [
            t2 @ projectors[k] - np.exp(2j * np.pi * k / order) * projectors[k]
            for k in range(order)
        ]
    )
    t1_ok = max(closure_resid, idempotent_resid, orthogonal_resid, resolution_resid, eigen_resid) < TOL
    print(f"  ||T_2^N2 - I||                 = {closure_resid:.3e}")
    print(f"  max ||Pi_k^2 - Pi_k||          = {idempotent_resid:.3e}")
    print(f"  max ||Pi_k Pi_l||, k != l      = {orthogonal_resid:.3e}")
    print(f"  ||sum_k Pi_k - I||             = {resolution_resid:.3e}")
    print(f"  max ||T_2 Pi_k - phase Pi_k||  = {eigen_resid:.3e}")
    print(f"  STATUS: {'PASS' if t1_ok else 'FAIL'}")
    print()

    print("-" * 72)
    print("TEST 2: H respects T_2 but not generic one-step T_1")
    print("-" * 72)
    comm_t2 = float(np.linalg.norm(hamiltonian @ t2 - t2 @ hamiltonian))
    comm_t1 = float(np.linalg.norm(hamiltonian @ t1 - t1 @ hamiltonian))
    t2_ok = comm_t2 < TOL and comm_t1 > 1e-3
    print(f"  ||[H, T_2]||_F = {comm_t2:.3e}")
    print(f"  ||[H, T_1]||_F = {comm_t1:.3e}")
    print("  boundary: two-step symmetry is exact; one-step symmetry is not assumed")
    print(f"  STATUS: {'PASS' if t2_ok else 'FAIL'}")
    print()

    print("-" * 72)
    print("TEST 3: sector projectors commute with H")
    print("-" * 72)
    projector_comm_resid = max_norm([hamiltonian @ p - p @ hamiltonian for p in projectors])
    t3_ok = projector_comm_resid < TOL
    print(f"  max ||[H, Pi_k]||_F = {projector_comm_resid:.3e}")
    print(f"  STATUS: {'PASS' if t3_ok else 'FAIL'}")
    print()

    print("-" * 72)
    print("TEST 4: sector weights are conserved under exp(-i t H)")
    print("-" * 72)
    rng = np.random.default_rng(20260526)
    psi0 = rng.standard_normal(length) + 1j * rng.standard_normal(length)
    psi0 /= np.linalg.norm(psi0)
    initial = np.array([np.vdot(p @ psi0, p @ psi0).real for p in projectors])
    max_weight_drift = 0.0
    for time in [0.2, 0.7, 1.5, 3.0]:
        psi_t = unitary_from_hermitian(hamiltonian, time) @ psi0
        weights = np.array([np.vdot(p @ psi_t, p @ psi_t).real for p in projectors])
        max_weight_drift = max(max_weight_drift, float(np.max(np.abs(weights - initial))))
    t4_ok = max_weight_drift < TOL
    print(f"  max sector-weight drift = {max_weight_drift:.3e}")
    print(f"  STATUS: {'PASS' if t4_ok else 'FAIL'}")
    print()

    print("-" * 72)
    print("TEST 5: two-step character count and one-step ambiguity")
    print("-" * 72)
    one_step_phases = np.array([np.exp(2j * np.pi * n / length) for n in range(length)])
    two_step_phases = one_step_phases**2
    distinct_two_step = len({complex(round(z.real, 12), round(z.imag, 12)) for z in two_step_phases})
    paired_resid = max(
        abs(two_step_phases[n] - two_step_phases[(n + length // 2) % length])
        for n in range(length // 2)
    )
    t5_ok = distinct_two_step == order and paired_resid < TOL
    print(f"  distinct T_2 phases = {distinct_two_step} = L_s/2")
    print(f"  max |phase(n) - phase(n+L_s/2)| = {paired_resid:.3e}")
    print("  boundary: T_2 sectors identify one-step momenta modulo pi")
    print(f"  STATUS: {'PASS' if t5_ok else 'FAIL'}")
    print()

    print("=" * 72)
    print("SUMMARY")
    print("=" * 72)
    checks = [
        ("T1 (cyclic projectors)", t1_ok),
        ("T2 (two-step not one-step symmetry)", t2_ok),
        ("T3 ([H, Pi_k]=0)", t3_ok),
        ("T4 (sector weights conserved)", t4_ok),
        ("T5 (two-step character boundary)", t5_ok),
    ]
    for label, ok in checks:
        print(f"  {label:<42} {'PASS' if ok else 'FAIL'}")
    print()
    all_ok = all(ok for _, ok in checks)
    print(f"  OVERALL: {'PASS' if all_ok else 'FAIL'}")
    print()
    print("  verdict: bounded two-step translation-sector conservation exhibited;")
    print("           no canonical P_x divergence, full one-site momentum, or")
    print("           H_phys reconstruction bridge is claimed.")
    if not all_ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
