#!/usr/bin/env python3
"""Matter graded composition: the axiom-update boundary, checked exactly.

Class-A finite-dimensional runner for the composition gap: the same one-site
datum M_2(C) admits two inequivalent cross-site compositions, and nothing in
the one-site data selects between them.

Declared objects (all exact; sympy only, no floats, no sampling):

  * Pauli matrices s1, s2, s3, the unit one = eye(2), and the matrix units
    E00, E01 = |0><1|, E10, E11 of M_2(C);
  * three sites 0, 1, 2 on a line, nearest-neighbour pairs (0,1) and (1,2),
    with (0,2) non-adjacent; kron = iterated Kronecker product on C^8;
  * iota(x, M): the ungraded site embedding (identity on the other factors);
  * a Jordan-Wigner family c_x for a chosen total order, with Z = s3, plus
    cd_x = c_x^dagger, n_x = cd_x c_x and total parity P = s3 (x) s3 (x) s3;
  * kappa(x, M): the graded site embedding, the unital *-homomorphism with
    E01 -> c_x, E10 -> cd_x, E11 -> cd_x c_x, E00 -> c_x cd_x;
  * the proper cubic rotation group generated by Rz and Rx with SU(2) lifts
    Uz = (1 - i s3)/sqrt(2), Ux = (1 - i s1)/sqrt(2);
  * the real 8-dimensional basis {1, i, s_k, i s_k} of M_2(C);
  * six Majoranas g_1..g_6 on C^8 built from three Jordan-Wigner modes, with
    g_1,g_2,g_3 assigned to one site and g_4,g_5,g_6 to the other.

Check groups:

  A  two compositions of the same one-site data: both iota and kappa are
     injective unital *-homomorphisms generating all of M_8(C), they agree on
     the even one-site content, and they differ in their cross-site relations;
  B  the ungraded product forbids a site-local graded family;
  C  every complex Z_2-grading of the site algebra is an axis, different
     axes give different odd parts, and the *-compatible axes are real;
  D  proper cubic rotations: no invariant axis, the vector representation is
     irreducible, and the only rotation-equivariant unital real automorphisms
     of M_2(C) are the identity and the antilinear Clifford involution alpha;
  E  the graded composition with the mode's own parity: exact CAR, order
     independence up to an even intertwiner, the ladder's own parity axis,
     parity superselection, and readable one-site content;
  F  the rotation-covariant real alternative: six Majoranas on two sites give
     a real algebra of real dimension 64 against 32 for M_2(C) (x) M_2(C), the
     site generators anticommute across sites, and the smallest even Hermitian
     non-scalar elements are cross-site bond bilinears;
  G  the graded clause selects no dynamics and no state;
  H  coexistence: the two local structures share the parity-even and
     parity-odd subspaces exactly, at most 7 of the 12 nearest-neighbour
     bonds of a 2x2x2 cube are string-free under any total order, and the
     three-Majorana bilinears form a commuting spin-1/2 lattice inside the
     even sector of the real graded product.

Output: one PASS/FAIL line per check and a final `TOTAL: PASS=N FAIL=M`.
Exit code 0 iff FAIL = 0.
"""

import itertools
import sys

import sympy as sp
from sympy import I, Matrix, eye, zeros, symbols, sqrt

PASS = 0
FAIL = 0


def check(label, cond):
    """Record and print one exact check."""
    global PASS, FAIL
    ok = bool(cond)
    if ok:
        PASS += 1
    else:
        FAIL += 1
    print(("PASS " if ok else "FAIL ") + label)


# ---------------------------------------------------------------- notation

s1 = Matrix([[0, 1], [1, 0]])
s2 = Matrix([[0, -I], [I, 0]])
s3 = Matrix([[1, 0], [0, -1]])
one = eye(2)
SIG = [s1, s2, s3]

E00 = Matrix([[1, 0], [0, 0]])
E01 = Matrix([[0, 1], [0, 0]])
E10 = Matrix([[0, 0], [1, 0]])
E11 = Matrix([[0, 0], [0, 1]])
UNITS = [E00, E01, E10, E11]

I8 = eye(8)
Z8 = zeros(8, 8)
Z2 = zeros(2, 2)
NSITE = 3
NN_PAIRS = [(0, 1), (1, 2)]


def kron(*ms):
    out = ms[0]
    for m in ms[1:]:
        out = sp.kronecker_product(out, m)
    return Matrix(out)


def zero(M):
    return all(sp.expand(e) == 0 for e in M)


def eq(A, B):
    return zero(A - B)


def rows_of(mats):
    return Matrix([[e for e in M] for M in mats])


def iota(x, M):
    fac = [one, one, one]
    fac[x] = M
    return kron(*fac)


def jw_family(order):
    """c_x for the total order given by rank list `order` (order[y] = rank of y)."""
    out = []
    for x in range(NSITE):
        fac = []
        for y in range(NSITE):
            if y == x:
                fac.append(E01)
            elif order[y] < order[x]:
                fac.append(s3)
            else:
                fac.append(one)
        out.append(kron(*fac))
    return out


c = jw_family([0, 1, 2])
cd = [m.H for m in c]
n = [cd[x] * c[x] for x in range(NSITE)]
P = kron(s3, s3, s3)


def kappa(x, M):
    return sp.expand(
        M[0, 0] * (c[x] * cd[x])
        + M[0, 1] * c[x]
        + M[1, 0] * cd[x]
        + M[1, 1] * (cd[x] * c[x])
    )


# ---------------------------------- A: two compositions of the same datum

def embedding_report(emb):
    ok = True
    for x in range(NSITE):
        for i in range(2):
            for j in range(2):
                for k in range(2):
                    for l in range(2):
                        lhs = emb(x, UNITS[2 * i + j]) * emb(x, UNITS[2 * k + l])
                        rhs = emb(x, UNITS[2 * i + l]) if j == k else Z8
                        ok = ok and eq(lhs, rhs)
        for U in UNITS:
            ok = ok and eq(emb(x, U.H), emb(x, U).H)
        ok = ok and eq(emb(x, E00) + emb(x, E11), I8)
        ok = ok and rows_of([emb(x, U) for U in UNITS]).rank() == 4
    return ok


check("A1 iota unital *-hom on the matrix units, adjoint-compatible, injective, 3 sites",
      embedding_report(iota))
check("A2 kappa unital *-hom on the matrix units, adjoint-compatible, injective, 3 sites",
      embedding_report(kappa))

pauli_strings = [kron(a, b, d) for a in [one] + SIG for b in [one] + SIG for d in [one] + SIG]
check("A3a the 64 Pauli strings built from iota images span M_8(C) (rank 64)",
      len(pauli_strings) == 64 and rows_of(pauli_strings).rank() == 64)

monomials = []
for aexp in itertools.product([0, 1], repeat=NSITE):
    for bexp in itertools.product([0, 1], repeat=NSITE):
        M = I8
        for x in range(NSITE):
            if aexp[x]:
                M = M * cd[x]
            if bexp[x]:
                M = M * c[x]
        monomials.append(M)
check("A3b the 64 normal-ordered monomials prod cd_x^a c_x^b span M_8(C) (rank 64)",
      len(monomials) == 64 and rows_of(monomials).rank() == 64)

u0, u1 = iota(0, E01), iota(1, E01)
check("A4 ungraded pair: [iota(0,E01),iota(1,E01)]=0 and the anticommutator is 2*product != 0",
      eq(u0 * u1 - u1 * u0, Z8)
      and eq(u0 * u1 + u1 * u0, 2 * u0 * u1)
      and not zero(u0 * u1))

graded_pair_ok = True
for (x, y) in [(0, 1), (0, 2)]:
    graded_pair_ok = (graded_pair_ok
                      and eq(c[x] * c[y] + c[y] * c[x], Z8)
                      and eq(c[x] * cd[y] + cd[y] * c[x], Z8)
                      and eq(c[x] * c[y] - c[y] * c[x], 2 * c[x] * c[y])
                      and not zero(c[x] * c[y]))
check("A5 graded pair relations hold for (0,1) and for the non-adjacent (0,2) alike",
      graded_pair_ok)

even_agree = all(eq(kappa(x, E11), iota(x, E11)) and eq(kappa(x, E00), iota(x, E00))
                 for x in range(NSITE))
check("A6 the two compositions share the even one-site content; the odd content differs at site 1",
      even_agree and not eq(kappa(1, E01), iota(1, E01)))

# ------------------------------- B: no site-local graded family, ungraded

asym = symbols("a0:4")
bsym = symbols("b0:4")
A = Matrix(2, 2, asym)
B = Matrix(2, 2, bsym)
A1 = kron(A, one)
B1 = kron(one, B)
check("B1 symbolic A,B: {A(x)1, 1(x)B} = 2*(A(x)B) identically on M_4(C)",
      eq(A1 * B1 + B1 * A1, 2 * kron(A, B)))

AB = kron(A, B)
block_ok = all(eq(AB[2 * i:2 * i + 2, 2 * j:2 * j + 2], A[i, j] * B)
               for i in range(2) for j in range(2))
check("B2 block identity (A(x)B)[2i:2i+2,2j:2j+2] = A[i,j]*B, so A(x)B=0 forces A=0 or B=0",
      block_ok)

check("B3 c_1 is outside the span of iota(1,.) (rank 5) and fails to commute with iota(0,s1)",
      rows_of([iota(1, U) for U in UNITS] + [c[1]]).rank() == 5
      and not zero(c[1] * iota(0, s1) - iota(0, s1) * c[1]))

# ------------------------------------------- C: every complex grading is an axis

va, vb1, vb2, vb3 = symbols("va vb1 vb2 vb3")
V = va * one + vb1 * s1 + vb2 * s2 + vb3 * s3
sq_target = ((va**2 + vb1**2 + vb2**2 + vb3**2) * one
             + 2 * va * (vb1 * s1 + vb2 * s2 + vb3 * s3))
square_ok = eq(V * V, sq_target)
offdiag = [sp.expand(2 * va * vb1), sp.expand(2 * va * vb2), sp.expand(2 * va * vb3)]
branch_a = all(sp.expand(e.subs({va: 0})) == 0 for e in offdiag)
branch_b = all(sp.expand(e.subs({vb1: 0, vb2: 0, vb3: 0})) == 0 for e in offdiag)
anz = sp.Symbol("anz", nonzero=True)
forced = sp.solve([e.subs({va: anz}) for e in offdiag], [vb1, vb2, vb3], dict=True)
complete = forced == [{vb1: 0, vb2: 0, vb3: 0}]
comps = sp.nonlinsolve(offdiag, [va, vb1, vb2, vb3])
inside = all(t[0] == 0 or list(t[1:]) == [0, 0, 0] for t in comps)
both_branches = (sp.Tuple(0, vb1, vb2, vb3) in comps) and (sp.Tuple(va, 0, 0, 0) in comps)
check("C1 V^2 = (a^2+b.b)1 + 2a(b.s); V^2 proportional to 1 exactly when a=0 or b=0",
      square_ok and branch_a and branch_b and complete and inside and both_branches)


def ad_matrix(Vm):
    cols = []
    for Bm in UNITS:
        W = Vm * Bm * Vm
        cols.append([W[0, 0], W[0, 1], W[1, 0], W[1, 1]])
    return Matrix(cols).T


def flat2(M):
    return [M[0, 0], M[0, 1], M[1, 0], M[1, 1]]


T3 = ad_matrix(s3)
odd3 = T3.eigenvects()
odd3_basis = [v for (val, mult, vecs) in odd3 if val == -1 for v in vecs]
even3_basis = [v for (val, mult, vecs) in odd3 if val == 1 for v in vecs]
plus = Matrix([1, 1]) / sqrt(2)
minus = Matrix([1, -1]) / sqrt(2)
pm = plus * minus.H
mp = minus * plus.H
T1 = ad_matrix(s1)
odd1 = [v for (val, mult, vecs) in T1.eigenvects() if val == -1 for v in vecs]
c2_ok = (
    len(odd3_basis) == 2
    and len(even3_basis) == 2
    and Matrix([list(v.T) for v in odd3_basis] + [flat2(E01), flat2(E10)]).rank() == 2
    and Matrix([list(v.T) for v in even3_basis] + [flat2(E00), flat2(E11)]).rank() == 2
    and len(odd1) == 2
    and Matrix([list(v.T) for v in odd1] + [flat2(pm), flat2(mp)]).rank() == 2
    and Matrix([flat2(pm), flat2(mp), flat2(E01), flat2(E10)]).rank() > 2
    and Matrix([flat2(E01), flat2(E10), flat2(pm)]).rank() == 3
)
check("C2 the grading axis is the ladder axis; different axes give different odd parts", c2_ok)

wb1, wb2, wb3 = symbols("wb1 wb2 wb3")
wb = [wb1, wb2, wb3]
cwb = [sp.conjugate(w) for w in wb]
Vb = wb1 * s1 + wb2 * s2 + wb3 * s3
dot_bb = sum(wb[k] * cwb[k] for k in range(3))
cross_bb = [wb[1] * cwb[2] - wb[2] * cwb[1],
            wb[2] * cwb[0] - wb[0] * cwb[2],
            wb[0] * cwb[1] - wb[1] * cwb[0]]
vv_target = dot_bb * one + I * (cross_bb[0] * s1 + cross_bb[1] * s2 + cross_bb[2] * s3)
th = sp.Symbol("th", real=True)
rn = symbols("rn1 rn2 rn3", real=True)
phase_real = {wb1: sp.exp(I * th) * rn[0], wb2: sp.exp(I * th) * rn[1], wb3: sp.exp(I * th) * rn[2]}
cross_phase_real = [sp.simplify(e.subs(phase_real)) for e in cross_bb]
cross_witness = [sp.expand(e.subs({wb1: 1, wb2: I, wb3: 0})) for e in cross_bb]
c3_ok = (eq(Vb * Vb.H, vv_target)
         and all(e == 0 for e in cross_phase_real)
         and any(e != 0 for e in cross_witness))
check("C3 V=b.s: V V^dag = (b.conj b)1 + i(b x conj b).s; scalar for b = phase*real, not for (1,i,0)",
      c3_ok)

# ------------------------------------------------------- D: rotations

Rz = Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 1]])
Rx = Matrix([[1, 0, 0], [0, 0, -1], [0, 1, 0]])
group = {sp.ImmutableMatrix(eye(3))}
frontier = list(group)
while frontier:
    nxt = []
    for g in frontier:
        for h in (Rz, Rx):
            p = sp.ImmutableMatrix(Matrix(g) * h)
            if p not in group:
                group.add(p)
                nxt.append(p)
    frontier = nxt
check("D1 closure of Rz,Rx is the proper cubic rotation group: order 24, integer, det +1",
      len(group) == 24
      and all(e.is_Integer for g in group for e in Matrix(g))
      and all(Matrix(g).det() == 1 for g in group))

Uz = (one - I * s3) / sqrt(2)
Ux = (one - I * s1) / sqrt(2)
lift_ok = True
for (U, R) in ((Uz, Rz), (Ux, Rx)):
    lift_ok = lift_ok and eq(U * U.H, one)
    for k in range(3):
        rhs = R[0, k] * s1 + R[1, k] * s2 + R[2, k] * s3
        lift_ok = lift_ok and eq(U * SIG[k] * U.H, rhs)
check("D2 SU(2) lifts: U s_k U^dag = sum_j R_jk s_j exactly for both generators", lift_ok)

n1, n2, n3 = symbols("n1 n2 n3", real=True)
nvec = Matrix([n1, n2, n3])
axis_ok = True
for sz in (1, -1):
    for sx in (1, -1):
        sol = sp.solve(list(Rz * nvec - sz * nvec) + list(Rx * nvec - sx * nvec),
                       [n1, n2, n3], dict=True)
        axis_ok = axis_ok and sol == [{n1: 0, n2: 0, n3: 0}]
check("D3 no invariant axis: Rz n = +-n and Rx n = +-n force n = 0 in all four sign cases",
      axis_ok)

msym = symbols("m0:9", real=True)
Mgen = Matrix(3, 3, msym)
comm_sol = sp.solve(list(Mgen * Rz - Rz * Mgen) + list(Mgen * Rx - Rx * Mgen),
                    list(msym), dict=True)
Mcom = Mgen.subs(comm_sol[0])
free_com = sorted(Mcom.free_symbols, key=sp.default_sort_key)
check("D4 the real commutant of {Rz,Rx} in M_3(R) is R*1: the vector rep is R-irreducible",
      len(comm_sol) == 1 and len(free_com) == 1 and Mcom == free_com[0] * eye(3))

RB = [one, I * one, s1, s2, s3, I * s1, I * s2, I * s3]
RBNAME = ["1", "i", "s1", "s2", "s3", "is1", "is2", "is3"]


def coords(M):
    a = sp.re(M.trace() / 2)
    b = sp.im(M.trace() / 2)
    cs = [(M * s).trace() / 2 for s in SIG]
    return [a, b] + [sp.re(x) for x in cs] + [sp.im(x) for x in cs]


A11, A12, A21, A22, B11, B12, B21, B22 = symbols(
    "A11 A12 A21 A22 B11 B12 B21 B22", real=True)
UNK = [A11, A12, A21, A22, B11, B12, B21, B22]


def phi(M):
    v = coords(M)
    out = (A11 * v[0] + A12 * v[1]) * one + (A21 * v[0] + A22 * v[1]) * (I * one)
    for k in range(3):
        out = (out + (B11 * v[2 + k] + B12 * v[5 + k]) * SIG[k]
               + (B21 * v[2 + k] + B22 * v[5 + k]) * (I * SIG[k]))
    return out


eqs = []
for X in RB:
    for Y in RB:
        for e in sp.expand(phi(X * Y) - phi(X) * phi(Y)):
            eqs += [sp.expand(sp.re(e)), sp.expand(sp.im(e))]
for e in sp.expand(phi(one) - one):
    eqs += [sp.expand(sp.re(e)), sp.expand(sp.im(e))]
eqs = sorted({e for e in eqs if e != 0}, key=sp.default_sort_key)
d5_sols = sp.solve(eqs, UNK, dict=True)
IDENT = {A11: 1, A12: 0, A21: 0, A22: 1, B11: 1, B12: 0, B21: 0, B22: 1}
ALPHA = {A11: 1, A12: 0, A21: 0, A22: -1, B11: -1, B12: 0, B21: 0, B22: 1}
check("D5 exactly two rotation-equivariant unital real automorphisms of M_2(C): id and alpha",
      len(d5_sols) == 2 and IDENT in d5_sols and ALPHA in d5_sols)


def alpha(M):
    v = coords(M)
    out = v[0] * one - v[1] * (I * one)
    for k in range(3):
        out = out - v[2 + k] * SIG[k] + v[5 + k] * (I * SIG[k])
    return sp.expand(out)


def conj_form(M):
    return sp.expand(s2 * M.conjugate() * s2)


d6a = (all(eq(alpha(alpha(X)), X) for X in RB)
       and all(eq(alpha(I * X), -I * alpha(X)) for X in RB)
       and eq(alpha(I * one), -I * alpha(one))
       and all(eq(alpha(X), conj_form(X)) for X in RB))
check("D6a alpha is an involution, is antilinear, and equals M -> s2 conj(M) s2 on the basis",
      d6a)

odd_part = [s1, s2, s3, I * one]
even_part = [one, I * s1, I * s2, I * s3]
d6b = (all(eq(alpha(X), -X) for X in odd_part)
       and all(eq(alpha(X), X) for X in even_part)
       and Matrix([flat2(X) for X in odd_part]).rank() == 4
       and Matrix([flat2(X) for X in even_part]).rank() == 4
       and all(Matrix([flat2(X * Y)] + [flat2(W) for W in even_part]).rank() == 4
               for X in even_part for Y in even_part)
       and eq((I * s1) * (I * s2), -(I * s3))
       and eq((I * s2) * (I * s3), -(I * s1))
       and eq((I * s3) * (I * s1), -(I * s2))
       and all(eq(X * X, -one) for X in (I * s1, I * s2, I * s3)))
check("D6b alpha: odd part span_R{s1,s2,s3,i1}; even part span_R{1,is1,is2,is3} is quaternionic",
      d6b)

# ------------------------------------- E: the graded composition

car_ok = True
for x in range(NSITE):
    for y in range(NSITE):
        car_ok = car_ok and eq(c[x] * c[y] + c[y] * c[x], Z8)
        car_ok = car_ok and eq(c[x] * cd[y] + cd[y] * c[x], I8 if x == y else Z8)
check("E1 exact CAR for the family {c_x}: {c_x,c_y}=0 and {c_x,cd_y}=delta_xy on all 9 pairs",
      car_ok)

e2 = all(eq(P * c[x] * P, -c[x]) and eq(P * n[x] * P, n[x]) for x in range(NSITE))
e2 = (e2
      and eq(n[0] * c[1] - c[1] * n[0], Z8)
      and eq(n[0] * cd[1] - cd[1] * n[0], Z8)
      and eq(n[0] * c[2] - c[2] * n[0], Z8)
      and eq((c[0] * cd[0]) * c[1] - c[1] * (c[0] * cd[0]), Z8))
check("E2 P c_x P = -c_x and P n_x P = n_x; even one-site elements commute across sites", e2)

c_alt = jw_family([2, 0, 1])
cd_alt = [m.H for m in c_alt]
alt_car = True
for x in range(NSITE):
    for y in range(NSITE):
        alt_car = alt_car and eq(c_alt[x] * c_alt[y] + c_alt[y] * c_alt[x], Z8)
        alt_car = alt_car and eq(c_alt[x] * cd_alt[y] + cd_alt[y] * c_alt[x],
                                 I8 if x == y else Z8)
wsym = symbols("w0:64")
Wgen = Matrix(8, 8, wsym)
lin = []
for x in range(NSITE):
    lin += list(Wgen * c[x] - c_alt[x] * Wgen)
    lin += list(Wgen * cd[x] - cd_alt[x] * Wgen)
wsol = sp.solve(lin, list(wsym), dict=True)
Wint = Wgen.subs(wsol[0])
wfree = sorted(Wint.free_symbols, key=sp.default_sort_key)
check("E3a the order [2,0,1] family also satisfies CAR; the intertwiner space is 1-dimensional",
      alt_car and len(wsol) == 1 and len(wfree) == 1)

W0 = Wint.subs({wfree[0]: 1})
WW = sp.expand(W0 * W0.H)
lam = sp.expand(WW[0, 0])
check("E3b the intertwiner is even ([W,P]=0), nonzero, and W W^dag is a multiple of 1",
      not zero(W0) and eq(W0 * P - P * W0, Z8) and eq(WW, lam * I8) and lam != 0)

q1, q2, q3 = symbols("q1 q2 q3", real=True)
nsig = q1 * s1 + q2 * s2 + q3 * s3
e4_sols = sp.solve(list(nsig * E01 * nsig + E01) + [q1**2 + q2**2 + q3**2 - 1],
                   [q1, q2, q3], dict=True)
e4_want = [{q1: 0, q2: 0, q3: 1}, {q1: 0, q2: 0, q3: -1}]
check("E4 the ladder fixes its axis: (n.s)E01(n.s) = -E01 with real unit n exactly at n = +-e3",
      len(e4_sols) == 2 and all(s in e4_sols for s in e4_want))

Pp = (I8 + P) / 2
Pm = (I8 - P) / 2
Xs = Matrix(8, 8, symbols("x0:64"))
Ys = Matrix(8, 8, symbols("y0:64"))
rho = sp.expand(Pp * Xs * Pp + Pm * Ys * Pm)
odd_strings = []
for idx in itertools.product(range(4), repeat=NSITE):
    if sum(1 for u in idx if u in (1, 2)) % 2 == 1:
        odd_strings.append(kron(*[[one, s1, s2, s3][u] for u in idx]))
e5 = len(odd_strings) == 32
for O in odd_strings:
    tr = sp.expand(sum(rho[i, j] * O[j, i] for i in range(8) for j in range(8)))
    e5 = e5 and tr == 0
check("E5 every parity-diagonal state annihilates every odd element (all 32 odd strings)", e5)

e6 = True
for x in range(NSITE):
    ev = [kappa(x, E00), kappa(x, E11)]
    od = [kappa(x, E01), kappa(x, E10)]
    e6 = (e6
          and all(eq(P * M * P, M) for M in ev)
          and all(eq(P * M * P, -M) for M in od)
          and rows_of(ev + [I8, n[x]]).rank() == 2
          and eq(ev[0] * ev[1] - ev[1] * ev[0], Z8)
          and eq(n[x] * n[x], n[x])
          and set(n[x].eigenvals().keys()) == {0, 1}
          and rows_of(od + [c[x], cd[x]]).rank() == 2)
check("E6 kappa even part span{1,n_x} commutes, n_x^2=n_x, spectrum {0,1}; odd part {c_x,cd_x}",
      e6)

fA = iota(0, A)
fB = iota(1, B)
check("E7 commuting ladders break the graded relation; site-local {f_0,f_1}=0 forces f_0 f_1 = 0",
      not zero(u0 * u1 + u1 * u0)
      and eq(c[0] * c[1] + c[1] * c[0], Z8)
      and eq(fA * fB + fB * fA, 2 * fA * fB))

# ------------------------- F: the rotation-covariant real alternative

g = []
for m in range(NSITE):
    g.append(sp.expand(c[m] + cd[m]))
    g.append(sp.expand(I * (c[m] - cd[m])))
f1 = all(eq(G, G.H) for G in g)
for i in range(6):
    for j in range(6):
        f1 = f1 and eq(g[i] * g[j] + g[j] * g[i], 2 * I8 if i == j else Z8)
check("F1 six Majoranas on C^8 are Hermitian with {g_a,g_b} = 2 delta_ab", f1)

gS = []
for r in range(7):
    for S in itertools.combinations(range(6), r):
        M = I8
        for a in S:
            M = M * g[a]
        gS.append(M)
real_rows = []
for M in gS:
    row = []
    for e in M:
        e = sp.expand(e)
        row.append(sp.re(e))
        row.append(sp.im(e))
    real_rows.append(row)
check("F2 the 64 products g_S are R-independent: real dimension 64 against 32 for M_4(C)",
      len(gS) == 64 and Matrix(real_rows).rank() == 64)

check("F3 the Hermitian site generators anticommute across the two sites: {g_j, g_k} = 0",
      all(eq(g[j] * g[k] + g[k] * g[j], Z8) for j in (0, 1, 2) for k in (3, 4, 5)))

t0, t1, t2, t3 = symbols("t0 t1 t2 t3", real=True)
Mev = (t0 * I8 + t1 * (g[0] * g[1]) + t2 * (g[1] * g[2]) + t3 * (g[2] * g[0]))
herm_sol = sp.solve(list(sp.expand(Mev - Mev.H)), [t0, t1, t2, t3], dict=True)
check("F4 one-site even Hermitian elements are scalars: the bivector coefficients vanish",
      herm_sol == [{t1: 0, t2: 0, t3: 0}])

Gpar = I8
for a in range(6):
    Gpar = Gpar * g[a]
Gpar = sp.expand((-I)**3 * Gpar)
f5 = eq(Gpar, Gpar.H) and eq(Gpar * Gpar, I8)
for j in (0, 1, 2):
    for k in (3, 4, 5):
        Bnd = sp.expand(I * g[j] * g[k])
        f5 = (f5 and eq(Bnd, Bnd.H) and not zero(Bnd)
              and eq(Bnd * Gpar - Gpar * Bnd, Z8))
check("F5 i g_j g_k across sites is Hermitian, nonzero, even for G = (-i)^3 g1..g6, G^2 = 1",
      f5)

# ------------------------------- G: no dynamics and no state are selected

Hhop = Z8
for (x, y) in NN_PAIRS:
    Hhop = Hhop + cd[x] * c[y] + cd[y] * c[x]
Hhop = sp.expand(Hhop)
H0 = Z8
vac = zeros(8, 1)
vac[0] = 1


def expval(psi, H):
    return sp.expand((psi.H * H * psi)[0, 0])


psi_a = cd[0] * vac
psi_b = sp.expand((cd[0] * vac + cd[1] * vac) / sqrt(2))
ev_a = expval(psi_a, Hhop)
ev_b = expval(psi_b, Hhop)
g1_ok = (eq(Hhop * P - P * Hhop, Z8) and eq(H0 * P - P * H0, Z8)
         and not zero(Hhop - H0)
         and expval(vac, Hhop) == 0 and expval(cd[1] * vac, Hhop) == 0
         and sp.expand((psi_a.H * psi_a)[0, 0]) == 1
         and sp.expand((psi_b.H * psi_b)[0, 0]) == 1
         and eq(P * psi_a + psi_a, zeros(8, 1)) and eq(P * psi_b + psi_b, zeros(8, 1))
         and ev_a == 0 and ev_b == 1)
check("G1 H_hop and H=0 are both even and distinct; expectations 0 and 1 on two parity states",
      g1_ok)

# ------------------------------- H: coexistence of the two local structures

even_spin = [S for S in pauli_strings if eq(S * P, P * S)]
odd_spin = [S for S in pauli_strings if eq(S * P, -P * S)]
even_car = []
odd_car = []
for aexp in itertools.product([0, 1], repeat=NSITE):
    for bexp in itertools.product([0, 1], repeat=NSITE):
        M = I8
        for x in range(NSITE):
            if aexp[x]:
                M = M * cd[x]
            if bexp[x]:
                M = M * c[x]
        (even_car if (sum(aexp) + sum(bexp)) % 2 == 0 else odd_car).append(M)
h1 = (len(even_spin) == 32 and len(odd_spin) == 32
      and len(even_car) == 32 and len(odd_car) == 32
      and rows_of(even_spin).rank() == 32 and rows_of(even_car).rank() == 32
      and rows_of(even_spin + even_car).rank() == 32
      and rows_of(odd_spin).rank() == 32 and rows_of(odd_car).rank() == 32
      and rows_of(odd_spin + odd_car).rank() == 32)
check("H1 both local structures share the same 32-dim even and 32-dim odd subspaces of M_8(C)",
      h1)

cube = list(itertools.product([0, 1], repeat=3))
bonds = {frozenset((a, b)) for a in cube for b in cube
         if sum(abs(a[i] - b[i]) for i in range(3)) == 1}
best = 0
for perm in itertools.permutations(cube):
    k = sum(1 for i in range(7) if frozenset((perm[i], perm[i + 1])) in bonds)
    if k > best:
        best = k
check("H2 2x2x2 cube: 12 nearest-neighbour bonds, at most 7 order-adjacent under any total order",
      len(bonds) == 12 and best == 7)


def majorana_spin(site):
    G = g[3 * site:3 * site + 3]
    S = []
    for a in range(3):
        b, cc = (a + 1) % 3, (a + 2) % 3
        S.append(sp.expand(-I * G[b] * G[cc] / 2))
    return S


S0 = majorana_spin(0)
S1 = majorana_spin(1)
h3 = True
for S in (S0, S1):
    for a in range(3):
        b, cc = (a + 1) % 3, (a + 2) % 3
        h3 = h3 and eq(S[a] * S[b] - S[b] * S[a], I * S[cc])
    h3 = h3 and all(eq(x, x.H) for x in S)
    h3 = h3 and eq(sp.expand(S[0] * S[0] + S[1] * S[1] + S[2] * S[2]),
                   sp.Rational(3, 4) * I8)
    h3 = h3 and all(eq(x * Gpar - Gpar * x, Z8) for x in S)
h3 = h3 and all(eq(x * y - y * x, Z8) for x in S0 for y in S1)
check("H3 three-Majorana bilinears: su(2) per site, Hermitian, S^2=3/4, even, commuting across sites",
      h3)

print("SUMMARY: same one-site data, two compositions; the graded product is order-free, "
      "its parity axis is the ladder's own, the covariant grading is antilinear.")
print(f"TOTAL: PASS={PASS} FAIL={FAIL}")
sys.exit(0 if FAIL == 0 else 1)
