#!/usr/bin/env python3
"""Exact checks for the note that prices menu-independence as independent and insufficient.

T1 and T2 are exact rational or exact symbolic finite algebra: an explicit covariant
nearest-neighbour witness law on Z^3 with a seven-symbol record alphabet, its full
7^6 x 24 covariance sweep, its four odds rules, and exact rational rank certificates
for the polynomial grading sector at degree five.  T3 rebuilds the emergent 2x2x2 cube
(12 edge qubits, superfast encoding, Kawamoto-Smit staggered pi-flux Hamiltonian,
half-filled sea) from scratch inside this file and reads its conditional record odds;
that stage inherits float64 eigenvectors and its conclusions depend only on the odds
being distinct.  No dense object above 4096 x 4096 is formed.  No seeds are used: every
sampled configuration is generated by a stated deterministic formula.  The
dimension-three frame-function theorem is named as context and is not recomputed.
"""

import itertools
import math
import time
from fractions import Fraction as F
from pathlib import Path

import numpy as np
import sympy as sp


AUDIT_TIMEOUT_SEC = 300

ROOT = Path(__file__).resolve().parents[1]
NOTE_PATH = ROOT / "docs" / "MENU_INDEPENDENCE_IS_INDEPENDENT_OF_THE_AXIOMS_AND_INSUFFICIENT_WITH_THEM_THE_BORN_FORM_NEEDS_MENU_ABUNDANCE_BOUNDED_THEOREM_NOTE_2026-09-03.md"
PARENT_NOTE = ROOT / "docs" / "BORN_FORM_FROM_BINARY_TERNARY_SCALED_PROJECTOR_FRAME_LIFT_BOUNDED_THEOREM_NOTE_2026-08-09.md"
AXIOM_PATH = ROOT / "docs" / "MINIMAL_AXIOMS_2026-06-29.md"

AUDIT_INPUT_PATHS = (
    "docs/MENU_INDEPENDENCE_IS_INDEPENDENT_OF_THE_AXIOMS_AND_INSUFFICIENT_WITH_THEM_THE_BORN_FORM_NEEDS_MENU_ABUNDANCE_BOUNDED_THEOREM_NOTE_2026-09-03.md",
    "docs/BORN_FORM_FROM_BINARY_TERNARY_SCALED_PROJECTOR_FRAME_LIFT_BOUNDED_THEOREM_NOTE_2026-08-09.md",
    "docs/MINIMAL_AXIOMS_2026-06-29.md",
)

TOL = 1e-9


def normalize(text):
    return " ".join(text.split())


class Checks:
    def __init__(self):
        self.passed = 0
        self.failed = 0

    def check(self, label, statement, condition):
        result = bool(condition)
        if result:
            self.passed += 1
        else:
            self.failed += 1
        print(f"{'PASS' if result else 'FAIL'}: {label} {statement}")

    def finish(self):
        print(f"TOTAL: PASS={self.passed} FAIL={self.failed}")
        return self.failed


# ==================================================================== T1: the witness law
DIRS = ((1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1))
SYMVEC = np.array(((0, 0, 0),) + DIRS, dtype=np.int8)   # symbol 0 = blank, 1..6 = DIRS


def proper_cubic_rotations():
    out = []
    for perm in itertools.permutations(range(3)):
        for signs in itertools.product((1, -1), repeat=3):
            m = [[0, 0, 0] for _ in range(3)]
            for row in range(3):
                m[row][perm[row]] = signs[row]
            mat = np.array(m, dtype=np.int64)
            if round(np.linalg.det(mat)) == 1:
                out.append(mat)
    return out


ROTS = proper_cubic_rotations()


def symbol_map(rot):
    """sigma[s] for s in 0..6, and the induced slot permutation on the six directions."""
    sigma = [0] * 7
    for s in range(1, 7):
        image = tuple(int(x) for x in rot @ np.array(DIRS[s - 1], dtype=np.int64))
        sigma[s] = DIRS.index(image) + 1
    return np.array(sigma, dtype=np.int8), [sigma[j + 1] - 1 for j in range(6)]


def primitive(vec):
    g = math.gcd(math.gcd(abs(vec[0]), abs(vec[1])), abs(vec[2]))
    return tuple(int(x) // g for x in vec)


def unsigned_primitive(vec):
    p = primitive(vec)
    return max(p, tuple(-x for x in p))


def menu_of(vsum, k):
    """L_MENU: the menu as an exact family of possibilities, keyed on (V, k)."""
    if k == 0:
        return (("I", F(1)),)
    if vsum == (0, 0, 0):
        return (("I", F(1, 3)), ("I", F(2, 3)))
    u = primitive(vsum)
    if k % 2 == 1:
        return (("R", F(1), u), ("R", F(1), tuple(-x for x in u)))
    return (("R", F(2, 3), u), ("R", F(2, 3), tuple(-x for x in u)), ("I", F(1, 3)))


def family_of(menu):
    if len(menu) == 1:
        return "SINGLETON"
    if all(m[0] == "I" for m in menu):
        return "BINARY_COIN"
    return "BINARY_RANKONE" if len(menu) == 2 else "TERNARY_MIXED"


def trace_of(item):
    """tr(E) for E = cI (2c) or E = cP(u) (c)."""
    return 2 * item[1] if item[0] == "I" else item[1]


def rule_values(menu, rule):
    traces = [trace_of(m) for m in menu]
    if rule == "BORN":
        return [t / 2 for t in traces]
    if rule == "UNIFORM":
        return [F(1, len(menu))] * len(menu)
    q = int(rule.split("=")[1])
    powers = [t ** q for t in traces]
    total = sum(powers)
    return [p / total for p in powers]


RULES = ("BORN", "UNIFORM", "POWER q=2", "POWER q=3")


def rotate_possibility(item, rot):
    if item[0] == "I":
        return item
    image = tuple(int(x) for x in rot @ np.array(item[2], dtype=np.int64))
    return ("R", item[1], image)


def t1(checks):
    n_pat = 7 ** 6
    idx = np.arange(n_pat, dtype=np.int64)
    sym = np.empty((n_pat, 6), dtype=np.int8)
    rest = idx.copy()
    for j in range(6):
        sym[:, j] = (rest % 7).astype(np.int8)
        rest //= 7
    vsum = SYMVEC[sym].sum(axis=1).astype(np.int64)
    kcount = (sym != 0).sum(axis=1).astype(np.int64)

    mismatch = 0
    total_checks = 0
    for rot in ROTS:
        sigma, pi = symbol_map(rot)
        rotated = np.empty_like(sym)
        for j in range(6):
            rotated[:, pi[j]] = sigma[sym[:, j]]
        v_rot = SYMVEC[rotated].sum(axis=1).astype(np.int64)
        k_rot = (rotated != 0).sum(axis=1).astype(np.int64)
        expected = vsum @ rot.T
        mismatch += int(np.count_nonzero(np.any(v_rot != expected, axis=1) | (k_rot != kcount)))
        total_checks += n_pat
    checks.check(
        "T1-covariance-sweep",
        f"the menu key (V, k) is cubic covariant over all 7^6 x 24 = {total_checks} pairs",
        total_checks == 2823576 and mismatch == 0,
    )

    # the menu as an exact object, on a deterministic spread of patterns
    sample = [int((i * 4801 + 17) % n_pat) for i in range(2000)]
    obj_mismatch = 0
    obj_checks = 0
    for rot in ROTS:
        sigma, pi = symbol_map(rot)
        for p in sample:
            digits = [(p // 7 ** j) % 7 for j in range(6)]
            rotated = [0] * 6
            for j in range(6):
                rotated[pi[j]] = int(sigma[digits[j]])
            v0 = tuple(int(x) for x in sum(np.array(SYMVEC[d], dtype=np.int64) for d in digits))
            v1 = tuple(int(x) for x in sum(np.array(SYMVEC[d], dtype=np.int64) for d in rotated))
            k0 = sum(1 for d in digits if d)
            m0 = set(rotate_possibility(item, rot) for item in menu_of(v0, k0))
            m1 = set(menu_of(v1, sum(1 for d in rotated if d)))
            obj_checks += 1
            if m0 != m1:
                obj_mismatch += 1
    checks.check(
        "T1-covariance-menu-object",
        f"M(g.n) = g.M(n) as an exact family on {obj_checks} deterministic pairs",
        obj_checks == 48000 and obj_mismatch == 0,
    )

    # the realised menu family
    odd_dirs, even_dirs = set(), set()
    has_zero_v, has_blank = False, False
    for i in range(n_pat):
        k = int(kcount[i])
        v = (int(vsum[i, 0]), int(vsum[i, 1]), int(vsum[i, 2]))
        if k == 0:
            has_blank = True
        elif v == (0, 0, 0):
            has_zero_v = True
        elif k % 2 == 1:
            odd_dirs.add(unsigned_primitive(v))
        else:
            even_dirs.add(unsigned_primitive(v))
    n_menus = 2 + len(odd_dirs) + len(even_dirs)
    menus = [(("I", F(1)),), (("I", F(1, 3)), ("I", F(2, 3)))]
    for d in sorted(odd_dirs):
        menus.append((("R", F(1), d), ("R", F(1), tuple(-x for x in d))))
    for d in sorted(even_dirs):
        menus.append((("R", F(2, 3), d), ("R", F(2, 3), tuple(-x for x in d)), ("I", F(1, 3))))
    checks.check(
        "T1-realised-family",
        f"the finite alphabet realises exactly {n_menus} menus, all four families",
        has_blank and has_zero_v and len(menus) == n_menus
        and {family_of(m) for m in menus} == {"SINGLETON", "BINARY_COIN", "BINARY_RANKONE", "TERNARY_MIXED"},
    )
    checks.check(
        "T1-resolutions-exact",
        "every realised menu resolves the identity exactly",
        all(
            sum(trace_of(m) for m in menu) == 2
            and all(
                sum(m[1] * F(m[2][a], 1) for m in menu if m[0] == "R") == 0
                for a in range(3)
            )
            for menu in menus
        ),
    )

    # four odds rules on the same law
    normalised = {r: all(sum(rule_values(menu, r)) == 1 for menu in menus) for r in RULES}
    checks.check(
        "T1-four-rules-normalised",
        f"Born, uniform and power q = 2, 3 are all normalised on all {n_menus} menus",
        all(normalised[r] for r in RULES),
    )
    cov_bad = 0
    for menu in menus:
        for rot in ROTS:
            rotated = tuple(rotate_possibility(item, rot) for item in menu)
            for r in RULES:
                a = dict(zip([rotate_possibility(i, rot) for i in menu], rule_values(menu, r)))
                b = dict(zip(rotated, rule_values(rotated, r)))
                if a != b:
                    cov_bad += 1
    checks.check(
        "T1-four-rules-covariant",
        "all four rules satisfy p_(g.n)(g.v) = p_n(v) on every menu and rotation",
        cov_bad == 0,
    )

    # the menu-independence witness
    where = {}
    for mi, menu in enumerate(menus):
        for item in menu:
            where.setdefault(item, []).append(mi)
    shared = sorted(v for v, ms in where.items() if len(ms) > 1)
    checks.check(
        "T1-single-shared-possibility",
        f"of {len(where)} possibilities exactly one, (1/3)I, sits in more than one menu",
        len(shared) == 1 and shared[0] == ("I", F(1, 3)),
    )
    n1 = (5, 5, 0, 0, 0, 0)
    n2 = (5, 6, 0, 0, 0, 0)

    def cond_menu(pattern):
        v = tuple(int(x) for x in sum(np.array(SYMVEC[s], dtype=np.int64) for s in pattern))
        return menu_of(v, sum(1 for s in pattern if s))

    m1, m2 = cond_menu(n1), cond_menu(n2)
    got = {}
    for r in RULES:
        v1 = dict(zip(m1, rule_values(m1, r)))[("I", F(1, 3))]
        v2 = dict(zip(m2, rule_values(m2, r)))[("I", F(1, 3))]
        got[r] = (v1, v2)
    checks.check(
        "T1-witness-menus",
        "two aligned records give the mixed ternary, two opposed the coin menu",
        family_of(m1) == "TERNARY_MIXED" and family_of(m2) == "BINARY_COIN",
    )
    checks.check(
        "T1-independence-witness",
        "(1/3)I gets 1/3 vs 1/3 (Born), 1/3 vs 1/2 (uniform), 1/3 vs 1/5 and 1/9 (power)",
        got["BORN"] == (F(1, 3), F(1, 3))
        and got["UNIFORM"] == (F(1, 3), F(1, 2))
        and got["POWER q=2"] == (F(1, 3), F(1, 5))
        and got["POWER q=3"] == (F(1, 3), F(1, 9)),
    )
    checks.check(
        "T1-non-implication",
        "one law carries both, so menu-independence is independent of the four axioms",
        got["BORN"][0] == got["BORN"][1] and got["UNIFORM"][0] != got["UNIFORM"][1],
    )
    return menus


def t1_torus(checks):
    """Deterministic 3^3 torus: translation and rotation covariance of the menu key."""
    L = 3
    sites = [(x, y, z) for x in range(L) for y in range(L) for z in range(L)]
    index = {s: i for i, s in enumerate(sites)}
    nbr = np.array([[index[tuple((s[a] + DIRS[j][a]) % L for a in range(3))] for j in range(6)]
                    for s in sites], dtype=np.int64)
    ncfg = 400
    conf = np.array([[(11 * c + 5 * s + 3 * c * s + 1) % 7 for s in range(27)] for c in range(ncfg)],
                    dtype=np.int8)

    def keys(cfg):
        picked = cfg[:, nbr]                      # (ncfg, 27, 6)
        return SYMVEC[picked].sum(axis=2).astype(np.int64), (picked != 0).sum(axis=2).astype(np.int64)

    v0, k0 = keys(conf)
    tmis = 0
    tchecks = 0
    for t in sites:
        perm = np.array([index[tuple((s[a] - t[a]) % L for a in range(3))] for s in sites])
        shifted = conf[:, perm]
        v1, k1 = keys(shifted)
        target = np.array([index[tuple((s[a] + t[a]) % L for a in range(3))] for s in sites])
        tmis += int(np.count_nonzero(np.any(v1[:, target] != v0, axis=2) | (k1[:, target] != k0)))
        tchecks += ncfg * len(sites)
    checks.check(
        "T1-torus-translation",
        f"on a 3^3 torus the menu key is translation covariant over {tchecks} checks",
        tchecks == 291600 and tmis == 0,
    )
    rmis = 0
    rchecks = 0
    for rot in ROTS:
        sigma, _ = symbol_map(rot)
        inv = np.linalg.inv(rot).round().astype(np.int64)
        src = np.array([index[tuple(int(v) % L for v in inv @ np.array(s, dtype=np.int64))] for s in sites])
        tgt = np.array([index[tuple(int(v) % L for v in rot @ np.array(s, dtype=np.int64))] for s in sites])
        rotated = sigma[conf[:, src]]
        v1, k1 = keys(rotated)
        expect = v0 @ rot.T
        rmis += int(np.count_nonzero(np.any(v1[:, tgt] != expect, axis=2) | (k1[:, tgt] != k0)))
        rchecks += ncfg * len(sites)
    checks.check(
        "T1-torus-rotation",
        f"the menu key is rotation covariant about the origin over {rchecks} checks",
        rchecks == 259200 and rmis == 0,
    )


# ==================================================================== T2: abundance
A_ODD = [(i, d - i) for d in (1, 3, 5) for i in range(d, -1, -1)]
B_EVEN = [(i, d - i) for d in (0, 2, 4) for i in range(d, -1, -1)]
A_ALL = [(i, d - i) for d in range(6) for i in range(d, -1, -1)]
B_ALL = [(i, d - i) for d in range(5) for i in range(d, -1, -1)]

TER_A = ((F(3, 4), (F(1), F(0), F(0))),
         (F(5, 8), (F(-3, 5), F(4, 5), F(0))),
         (F(5, 8), (F(-3, 5), F(-4, 5), F(0))))
ROT_Q = ((F(1, 3), F(-2, 3), F(2, 3)),
         (F(2, 3), F(2, 3), F(1, 3)),
         (F(-2, 3), F(1, 3), F(2, 3)))


def apply_rot(rot, n):
    return tuple(sum(rot[a][b] * n[b] for b in range(3)) for a in range(3))


TER_A2 = tuple((c, apply_rot(ROT_Q, n)) for c, n in TER_A)


def quaternion_rotation(a, b, c, d):
    s = a * a + b * b + c * c + d * d
    return ((F(a * a + b * b - c * c - d * d, s), F(2 * (b * c - a * d), s), F(2 * (b * d + a * c), s)),
            (F(2 * (b * c + a * d), s), F(a * a - b * b + c * c - d * d, s), F(2 * (c * d - a * b), s)),
            (F(2 * (b * d - a * c), s), F(2 * (c * d + a * b), s), F(a * a - b * b - c * c + d * d, s)))


def rational_rotations(limit):
    out, seen = [], set()
    for a in range(4):
        for b in range(4):
            for c in range(4):
                for d in range(4):
                    if a + b + c + d == 0:
                        continue
                    rot = quaternion_rotation(a, b, c, d)
                    if rot in seen:
                        continue
                    seen.add(rot)
                    out.append(rot)
                    if len(out) == limit:
                        return out
    return out


def menu_row(menu, a_mons, b_mons):
    row = [F(0)] * (len(a_mons) + len(b_mons))
    for coefficient, n in menu:
        x, y, z = n
        vals = [x ** i * y ** j for i, j in a_mons] + [z * x ** i * y ** j for i, j in b_mons]
        row = [row[t] + coefficient * vals[t] for t in range(len(row))]
    return row


def exact_rank(rows, columns):
    matrix = [row[:] for row in rows]
    pivot = 0
    for column in range(columns):
        idx = next((i for i in range(pivot, len(matrix)) if matrix[i][column] != 0), None)
        if idx is None:
            continue
        matrix[pivot], matrix[idx] = matrix[idx], matrix[pivot]
        inv = F(1) / matrix[pivot][column]
        matrix[pivot] = [v * inv for v in matrix[pivot]]
        for i in range(len(matrix)):
            if i != pivot and matrix[i][column] != 0:
                factor = matrix[i][column]
                matrix[i] = [matrix[i][t] - factor * matrix[pivot][t] for t in range(columns)]
        pivot += 1
        if pivot == len(matrix):
            break
    return pivot


def linear_modes_in_kernel(rows, a_mons, b_mons):
    names = [("A", i, j) for i, j in a_mons] + [("B", i, j) for i, j in b_mons]
    modes = (("A", 1, 0), ("A", 0, 1), ("B", 0, 0))
    return all(all(row[names.index(m)] == 0 for row in rows) for m in modes)


def t2(checks, menus):
    # (a) one cubic orbit of a genuine rank-one ternary leaves a fifteen-parameter family
    orbit = []
    for rot in ROTS:
        rr = tuple(tuple(F(int(rot[a][b])) for b in range(3)) for a in range(3))
        orbit.append(tuple((c, apply_rot(rr, n)) for c, n in TER_A))
    orbit_rows = [menu_row(m, A_ODD, B_EVEN) for m in orbit]
    orbit_rank = exact_rank(orbit_rows, 21)
    checks.check(
        "T2-finite-orbit-nullity",
        "24 cubic images of one rank-one ternary: 21 columns, rank 6, nullity 15",
        len(orbit_rows) == 24 and orbit_rank == 6 and 21 - orbit_rank == 15,
    )
    rogue = [F(0)] * (len(A_ODD) + len(B_EVEN))
    rogue[A_ODD.index((0, 3))] = F(-34, 59)
    rogue[A_ODD.index((0, 5))] = F(25, 59)
    residuals = [sum(row[t] * rogue[t] for t in range(len(rogue))) for row in orbit_rows]
    checks.check(
        "T2-explicit-rogue",
        "f = -34/59 y^3 + 25/59 y^5 has residual exactly zero on all 24 of those menus",
        all(r == 0 for r in residuals),
    )
    checks.check(
        "T2-rogue-in-range",
        "its coefficients have absolute sum one, so |f| <= 1 and w has range in [0, 1]",
        sum(abs(v) for v in rogue) == 1 and rogue[A_ODD.index((0, 3))] != 0,
    )

    # (b) the mixed ternary imposes exactly the binary condition
    c_sym, t_sym = sp.symbols("c t", real=True)
    f_sym = sp.Function("f")
    mixed = c_sym * (1 + f_sym(t_sym)) / 2 + c_sym * (1 + f_sym(-t_sym)) / 2 + (1 - c_sym) - 1
    checks.check(
        "T2-mixed-ternary-reduces",
        "{cP(u), cP(-u), (1-c)I} normalises to (c/2)(f(u) + f(-u)), the binary condition",
        sp.simplify(mixed - c_sym * (f_sym(t_sym) + f_sym(-t_sym)) / 2) == 0,
    )
    mixed_menus = []
    for rot in ROTS:
        rr = tuple(tuple(F(int(rot[a][b])) for b in range(3)) for a in range(3))
        for c in (F(2, 3), F(1, 2), F(4, 5)):
            u = apply_rot(rr, (F(3, 5), F(4, 5), F(0)))
            mixed_menus.append(((c, u), (c, tuple(-v for v in u))))
    mixed_rows = [menu_row(m, A_ODD, B_EVEN) for m in mixed_menus]
    checks.check(
        "T2-mixed-ternary-nullity",
        "all 72 mixed ternary rows vanish identically on that ansatz: nullity 21, not 3",
        len(mixed_rows) == 72 and all(all(v == 0 for v in row) for row in mixed_rows)
        and 21 - exact_rank(mixed_rows, 21) == 21,
    )

    # (c) the full family: two base ternaries under ninety-six exact rational rotations
    rots96 = rational_rotations(48)
    full = []
    for rot in rots96:
        full.append(tuple((c, apply_rot(rot, n)) for c, n in TER_A))
        full.append(tuple((c, apply_rot(rot, n)) for c, n in TER_A2))
    odd_rows = [menu_row(m, A_ODD, B_EVEN) for m in full]
    odd_rank = exact_rank(odd_rows, 21)
    checks.check(
        "T2-full-family-odd",
        "96 rational rotations of two rank-one ternaries: 21 columns, rank 18, nullity 3",
        len(odd_rows) == 96 and odd_rank == 18 and 21 - odd_rank == 3
        and linear_modes_in_kernel(odd_rows, A_ODD, B_EVEN),
    )
    all_rows = [menu_row(m, A_ALL, B_ALL) for m in full]
    all_rank = exact_rank(all_rows, 36)
    checks.check(
        "T2-full-family-unrestricted",
        "the same 96 rows without the oddness restriction: 36 columns, rank 33, nullity 3",
        len(all_rows) == 96 and all_rank == 33 and 36 - all_rank == 3
        and linear_modes_in_kernel(all_rows, A_ALL, B_ALL),
    )

    # (d) singleton-only supports: no trace form
    rx, ry, rz = sp.symbols("rx ry rz", real=True)
    sq = rx ** 2 + ry ** 2 + rz ** 2
    gap_z = sp.simplify((rx ** 2 + ry ** 2 + (rz - 1) ** 2 - (sq - 1)).subs(rz, 1))
    gap_x = sp.simplify(((rx - 1) ** 2 + ry ** 2 + rz ** 2 - (sq - 1)).subs(rx, 1))
    checks.check(
        "T2-singleton-only",
        "singletons force w = 1; r.n = 1 forces r = n, and e_z with e_x is infeasible",
        gap_z == 0 and gap_x == 0 and (0, 0, 1) != (1, 0, 0),
    )

    # (e) binary-only supports: an exact non-Born survivor
    ux, uy, uz = sp.symbols("ux uy uz", real=True)
    cubic_f = uz ** 3
    checks.check(
        "T2-binary-only",
        "f(u) = u_z^3 is odd, passes every binary menu, and f(3/5,0,4/5) = 64/125 not 4/5",
        sp.simplify(cubic_f + cubic_f.subs(uz, -uz)) == 0
        and sp.Rational(4, 5) ** 3 == sp.Rational(64, 125)
        and sp.Rational(64, 125) != sp.Rational(4, 5),
    )

    # (f) the witness law's own realised family cannot supply abundance
    rank_one_ternaries = [m for m in menus if len(m) == 3 and all(i[0] == "R" for i in m)]
    checks.check(
        "T2-law-has-no-rank-one-ternary",
        f"none of the {len(menus)} menus L_MENU realises is a rank-one ternary resolution",
        rank_one_ternaries == [],
    )
    bin_id = sp.simplify((1 + t_sym ** 3) / 2 + (1 + (-t_sym) ** 3) / 2 - 1) == 0
    ter_id = sp.simplify(sp.Rational(2, 3) * (1 + t_sym ** 3) / 2
                         + sp.Rational(2, 3) * (1 + (-t_sym) ** 3) / 2
                         + sp.Rational(1, 3) - 1) == 0
    coin_ok = all(sum(m[1] for m in menu) == 1 for menu in menus if family_of(menu) == "BINARY_COIN")
    fams = {family_of(menu) for menu in menus}
    survivor_ok = bin_id and ter_id and coin_ok and fams <= {
        "SINGLETON", "BINARY_COIN", "BINARY_RANKONE", "TERNARY_MIXED"}
    checks.check(
        "T2-survivor-on-the-law",
        "f(u) = u_z^3 is exactly normalised on every menu the witness law realises",
        survivor_ok,
    )

    # (g) the family abundance demands is infinite; a finite alphabet realises at most a^6 menus
    family = []
    m = 2
    while len(family) < 200:
        for n in range(1, m):
            if math.gcd(m, n) != 1 or (m - n) % 2 == 0:
                continue
            p = F(-(m * m - n * n), m * m + n * n)
            q = F(2 * m * n, m * m + n * n)
            c2 = F(1) / (1 - p)
            c1 = -2 * p / (1 - p)
            family.append(((c1, (F(1), F(0), F(0))), (c2, (p, q, F(0))), (c2, (p, -q, F(0)))))
            if len(family) == 200:
                break
        m += 1
    resolves = all(
        sum(c for c, _ in menu) == 2 and all(sum(c * n[a] for c, n in menu) == 0 for a in range(3))
        for menu in family
    )
    noncollinear = all(menu[1][1][1] != 0 for menu in family)
    distinct = len({tuple(sorted(menu)) for menu in family}) == 200
    checks.check(
        "T2-abundance-family-infinite",
        "200 distinct exact rational non-collinear rank-one ternary resolutions exhibited",
        resolves and noncollinear and distinct,
    )
    checks.check(
        "T2-finite-alphabet-bound",
        f"a seven-symbol alphabet gives at most 7^6 conditions and here {len(menus)} menus",
        len(menus) <= 7 ** 6 and len(menus) < 200,
    )
    return {"law_nullity": 21 - exact_rank(mixed_rows, 21), "rogue_survives": all(r == 0 for r in residuals)}


# ==================================================================== T3: the emergent cube
def popcount(n):
    return bin(n).count("1")


class Pauli:
    """i^k prod_q X_q^{x_q} Z_q^{z_q}, X before Z on every qubit."""

    __slots__ = ("k", "x", "z")

    def __init__(self, k, x, z):
        self.k = k % 4
        self.x = x
        self.z = z

    def __mul__(self, other):
        return Pauli(self.k + other.k + 2 * popcount(self.z & other.x), self.x ^ other.x, self.z ^ other.z)

    def neg(self):
        return Pauli(self.k + 2, self.x, self.z)

    def __eq__(self, other):
        return self.k == other.k and self.x == other.x and self.z == other.z

    def __hash__(self):
        return hash((self.k, self.x, self.z))


PHASE = (1 + 0j, 1j, -1 + 0j, -1j)


def act(p, b):
    return b ^ p.x, PHASE[p.k] * ((-1) ** (popcount(p.z & b) % 2))


class Cube:
    """The 2x2x2 cube with 12 edge qubits in the superfast encoding, route-B convention."""

    def __init__(self):
        self.V = 8
        self.EDGES = sorted((min(s, s ^ bit), max(s, s ^ bit))
                            for s in range(8) for bit in (4, 2, 1) if s ^ bit > s)
        self.NQ = len(self.EDGES)
        self.DIM = 1 << self.NQ
        self.EIDX = {}
        for q, (i, j) in enumerate(self.EDGES):
            self.EIDX[(i, j)] = q
            self.EIDX[(j, i)] = q
        self.NBR = {i: sorted(j for (a, b) in self.EDGES for j in ((b,) if a == i else ((a,) if b == i else ())))
                    for i in range(self.V)}
        self.STARMASK = {i: sum(1 << self.EIDX[(i, k)] for k in self.NBR[i]) for i in range(self.V)}
        self.FACES = []
        for ax in range(3):
            bits = [4, 2, 1]
            fb = bits[ax]
            ob = [b for b in bits if b != fb]
            for val in (0, fb):
                self.FACES.append((val, val | ob[1], val | ob[0] | ob[1], val | ob[0]))

    def A_unsigned(self, i, j):
        x = 1 << self.EIDX[(i, j)]
        z = 0
        for k in self.NBR[i]:
            if k != j and k < j:
                z ^= 1 << self.EIDX[(i, k)]
        for l in self.NBR[j]:
            if l != i and l < i:
                z ^= 1 << self.EIDX[(j, l)]
        return Pauli(popcount(x & z) % 2, x, z)

    def A(self, i, j):
        p = self.A_unsigned(i, j)
        return p if i < j else p.neg()

    def B(self, i):
        return Pauli(0, 0, self.STARMASK[i])

    def loop(self, cyc):
        out = Pauli(0, 0, 0)
        for a in range(len(cyc)):
            out = out * self.A(cyc[a], cyc[(a + 1) % len(cyc)])
        return out

    def record(self, z):
        return tuple(popcount(z & self.STARMASK[i]) % 2 for i in range(self.V))

    def hop_pauli(self, i, j):
        a = self.A(i, j)
        return a * self.B(i), a * self.B(j)

    def hop_amp(self, p1, p2, y):
        b1, a1 = act(p1, y)
        b2, a2 = act(p2, y)
        assert b1 == b2
        v = 0.5j * (a1 - a2)
        return b1, complex(round(v.real), round(v.imag))


def build_cube():
    cube = Cube()
    stab = [cube.loop(f) for f in cube.FACES]
    gens, basis = [], []
    for s in stab:
        v = s.x
        for b in basis:
            v = min(v, v ^ b)
        if v:
            basis.append(v)
            basis.sort(reverse=True)
            gens.append(s)
    group = []
    for m in range(1 << len(gens)):
        p = Pauli(0, 0, 0)
        for t in range(len(gens)):
            if (m >> t) & 1:
                p = p * gens[t]
        group.append(p)
    dim = cube.DIM
    cid = -np.ones(dim, dtype=np.int64)
    phi = np.zeros(dim, dtype=complex)
    reps = []
    for z0 in range(dim):
        if cid[z0] >= 0:
            continue
        c = len(reps)
        reps.append(z0)
        for g in group:
            b, a = act(g, z0)
            cid[b] = c
            phi[b] = a

    def corner_xyz(s):
        return ((s >> 2) & 1, (s >> 1) & 1, s & 1)

    def eta_ks(v, a):
        if a == 0:
            return 1
        if a == 1:
            return -1 if (v[0] & 1) else 1
        return -1 if ((v[0] + v[1]) & 1) else 1

    eta = np.zeros(cube.NQ, dtype=np.int64)
    for q, (i, j) in enumerate(cube.EDGES):
        lo, hi = min(i, j), max(i, j)
        eta[q] = eta_ks(corner_xyz(lo), {4: 0, 2: 1, 1: 2}[lo ^ hi])
    flux = []
    for cyc in cube.FACES:
        f = 1
        for t in range(4):
            f *= int(eta[cube.EIDX[(cyc[t], cyc[(t + 1) % 4])]])
        flux.append(f)

    hamp = np.zeros((cube.NQ, dim), dtype=np.complex128)
    for q, e in enumerate(cube.EDGES):
        p1, p2 = cube.hop_pauli(*e)
        for z in range(dim):
            zz, amp = cube.hop_amp(p1, p2, z)
            if amp == 0:
                continue
            assert zz == z ^ (1 << q)
            hamp[q, z] = -1.0 * eta[q] * amp
    nval = np.array([sum(cube.record(z)) for z in range(dim)], dtype=np.int64)

    ncoset = len(reps)
    w = np.zeros((dim, ncoset), dtype=np.complex128)
    w[np.arange(dim), cid] = phi / np.sqrt(float(len(group)))
    hw = np.zeros((dim, ncoset), dtype=np.complex128)
    for c in range(ncoset):
        psi = w[:, c]
        out = np.zeros(dim, dtype=np.complex128)
        for q in range(cube.NQ):
            out[np.arange(dim) ^ (1 << q)] += hamp[q] * psi
        hw[:, c] = out
    hc = w.conj().T @ hw
    evals, evecs = np.linalg.eigh(hc)
    sea = w @ evecs[:, 0]
    return cube, hamp, nval, np.abs(sea) ** 2, float(evals[0]), float(evals[1] - evals[0]), \
        int(np.sum(evals < evals[0] + 1e-9)), flux, ncoset


def block_ground_diag(cube, hamp, nval, rmask, wval):
    """Ground-space diagonal of H restricted to a record block, split by the conserved N."""
    dim = cube.DIM
    idx = np.flatnonzero((np.arange(dim) & rmask) == wval)
    free = [q for q in range(cube.NQ) if not (rmask >> q) & 1]
    loc = -np.ones(dim, dtype=np.int64)
    blocks = []
    for n in np.unique(nval[idx]):
        sub = idx[nval[idx] == n]
        d = len(sub)
        loc[sub] = np.arange(d)
        hb = np.zeros((d, d), dtype=np.complex128)
        cols = np.arange(d)
        for q in free:
            a = hamp[q][sub]
            mask = a != 0
            if not mask.any():
                continue
            hb[loc[sub[mask] ^ (1 << q)], cols[mask]] += a[mask]
        loc[sub] = -1
        ev, vc = np.linalg.eigh(hb)
        blocks.append((sub, ev, vc))
    e0 = min(float(b[1][0]) for b in blocks)
    diag = np.zeros(dim)
    deg = 0
    for sub, ev, vc in blocks:
        sel = np.flatnonzero(ev < e0 + TOL)
        if len(sel) == 0:
            continue
        deg += len(sel)
        diag[sub] += np.sum(np.abs(vc[:, sel]) ** 2, axis=1)
    return e0, deg, diag / deg


def conditional_odds(prob, nq, max_k):
    """For every record set R with |R| <= max_k and every free edge q, the odds p(Z_q = 0)."""
    tensor = prob.reshape((2,) * nq)
    by_k = {k: {"values": set(), "menus": set(), "singletons": 0, "witness": None} for k in range(max_k + 1)}
    blocks = {k: 0 for k in range(max_k + 1)}
    for m in range(0, max_k + 2):
        for subset in itertools.combinations(range(nq), m):
            keep = sorted(nq - 1 - q for q in subset)
            drop = tuple(a for a in range(nq) if a not in set(keep))
            marg = tensor.sum(axis=drop) if drop else tensor
            qs = sorted(subset, reverse=True)
            if m <= max_k:
                blocks[m] += int(np.count_nonzero(marg > TOL))
            if m == 0:
                continue
            k = m - 1
            if k > max_k:
                continue
            for pos, q in enumerate(qs):
                flat = np.moveaxis(marg, pos, -1).reshape(-1, 2)
                tot = flat.sum(axis=1)
                good = tot > TOL
                p0 = flat[good, 0] / tot[good]
                rec = by_k[k]
                for v in np.unique(np.round(p0, 9)):
                    rec["values"].add(float(v))
                menu0 = p0 > 1e-12
                menu1 = (1.0 - p0) > 1e-12
                if np.any(menu0 & menu1):
                    rec["menus"].add((0, 1))
                if np.any(~menu0):
                    rec["menus"].add((1,))
                if np.any(~menu1):
                    rec["menus"].add((0,))
                single = int(np.count_nonzero(~menu0 | ~menu1))
                rec["singletons"] += single
                if single and rec["witness"] is None:
                    rows = np.flatnonzero(good)[np.flatnonzero(~menu0 | ~menu1)]
                    others = [x for x in qs if x != q]
                    row = int(rows[0])
                    bits = {}
                    for pos2, q2 in enumerate(others):
                        bits[q2] = (row >> (len(others) - 1 - pos2)) & 1
                    rec["witness"] = (tuple(sorted(bits)), tuple(bits[b] for b in sorted(bits)), q,
                                      float(p0[np.flatnonzero(~menu0 | ~menu1)][0]))
    return by_k, blocks


def t3(checks):
    cube, hamp, nval, p_sea, e_sea, gap, deg, flux, ncoset = build_cube()
    checks.check(
        "T3-cube-setup",
        "12 qubits, six minus-one fluxes, code dim 128, sea -4 sqrt(3), gap 2 sqrt(3)",
        cube.DIM == 4096 and cube.NQ == 12 and flux == [-1] * 6 and ncoset == 128
        and abs(e_sea + 4 * math.sqrt(3)) < 1e-9 and abs(gap - 2 * math.sqrt(3)) < 1e-6 and deg == 1,
    )
    checks.check(
        "T3-selection-rule-zeros",
        "the sea has exactly 2112 zeros of 4096 and edge 9 is the corner pair (4, 6)",
        int(np.count_nonzero(p_sea < 1e-14)) == 2112 and cube.EDGES[9] == (4, 6),
    )
    by_k, blocks = conditional_odds(p_sea, cube.NQ, 8)
    flat = all(by_k[k]["values"] == {0.5} for k in (0, 1, 2))
    checks.check(
        "T3-flat-only-to-two",
        "odds are exactly one half at k = 0, 1, 2 over 1, 24 and 264 record blocks",
        flat and blocks[0] == 1 and blocks[1] == 24 and blocks[2] == 264,
    )
    want = sorted(float(x) for x in (F(5, 18), F(1, 3), F(1, 2), F(2, 3), F(13, 18)))
    got = sorted(by_k[3]["values"])
    checks.check(
        "T3-five-values-at-three",
        "at k = 3 the odds take five values 5/18, 1/3, 1/2, 2/3, 13/18 over 1760 blocks",
        len(got) == 5 and all(abs(a - b) < 1e-9 for a, b in zip(got, want)) and blocks[3] == 1760,
    )
    checks.check(
        "T3-same-menu-five-odds",
        "every one of those blocks carries the same binary menu",
        by_k[3]["menus"] == {(0, 1)} and len(by_k[3]["values"]) == 5,
    )
    checks.check(
        "T3-no-forcing-below-eight",
        "complete over every record subset and value: no singleton menu at k = 4, 5, 6, 7",
        all(by_k[k]["singletons"] == 0 for k in (4, 5, 6, 7)),
    )
    named = (0, 1, 2, 3, 4, 5, 6, 8)
    rmask = sum(1 << e for e in named)
    sel = (np.arange(cube.DIM) & rmask) == 0
    tot = p_sea[sel].sum()
    p1_named = p_sea[sel & (((np.arange(cube.DIM) >> 9) & 1) == 1)].sum() / tot
    p1_empty = p_sea[((np.arange(cube.DIM) >> 9) & 1) == 1].sum()
    checks.check(
        "T3-forcing-at-eight",
        "forcing first at k = 8: zero records on edges 0-6 and 8 lock edge 9 to one",
        by_k[8]["singletons"] > 0 and abs(p1_named - 1.0) < 1e-9,
    )
    checks.check(
        "T3-menu-independence-refuted",
        "that same possibility has odds one half in the empty neighbourhood",
        abs(p1_empty - 0.5) < 1e-9 and abs(p1_named - 1.0) < 1e-9,
    )

    # the relaxation tick against the sea, on the same neighbourhoods
    sets = (((0,), (0,)), ((0,), (1,)), ((1,), (0,)), ((0, 1), (0, 0)), ((0, 1), (0, 1)),
            ((0, 5), (0, 0)), ((0, 1, 2), (0, 0, 0)), ((0, 1, 2), (1, 0, 1)),
            ((0, 1, 2, 3), (0, 0, 0, 0)), ((0, 1, 2, 3, 4), (0, 0, 0, 0, 0)))
    rows = []
    for rec, vals in sets:
        rmask = sum(1 << e for e in rec)
        wval = sum(b << e for b, e in zip(vals, rec))
        _, _, diag = block_ground_diag(cube, hamp, nval, rmask, wval)
        sel = (np.arange(cube.DIM) & rmask) == wval
        for q in range(cube.NQ):
            if (rmask >> q) & 1:
                continue
            out = []
            for p in (diag, p_sea):
                tot = p[sel].sum()
                if tot < TOL:
                    out.append(None)
                    continue
                p1 = p[sel & (((np.arange(cube.DIM) >> q) & 1) == 1)].sum() / tot
                out.append((1.0 - p1, p1))
            rows.append((rec, vals, q, out[0], out[1]))
    menus_mr = {tuple(b for b in (0, 1) if r[3][b] > 1e-12) for r in rows}
    menus_sea = {tuple(b for b in (0, 1) if r[4][b] > 1e-12) for r in rows if r[4]}
    checks.check(
        "T3-one-menu-shape",
        "tick and sea both carry the same binary menu on every sampled neighbourhood",
        menus_mr == {(0, 1)} and menus_sea == {(0, 1)},
    )
    hit = [r for r in rows if r[0] == (0, 1, 2, 3) and r[2] == 4]
    checks.check(
        "T3-no-discriminator",
        "at records (0,1,2,3) = 0, edge 4: tick 1/5, sea 1/3, uniform 1/2",
        len(hit) == 1 and abs(hit[0][3][0] - 0.2) < 1e-9 and abs(hit[0][4][0] - 1 / 3) < 1e-9,
    )
    nonflat_mr = [r for r in rows if abs(r[3][0] - 0.5) > 1e-9]
    nonflat_sea = [r for r in rows if r[4] and abs(r[4][0] - 0.5) > 1e-9]
    checks.check(
        "T3-tick-and-sea-fail-alike",
        "tick and sea depart from one half at exactly the same neighbourhood",
        len(nonflat_mr) == 1 and len(nonflat_sea) == 1
        and nonflat_mr[0][:3] == nonflat_sea[0][:3],
    )
    return {"odds_at_three": len(by_k[3]["values"]), "one_shape": menus_mr == {(0, 1)} and menus_sea == {(0, 1)}}


# ==================================================================== T4 and source gates
def t4(checks, menus, t2_facts, t3_facts, parent):
    """The vacuity lemma, and the two usable candidate sentences."""
    n1 = (("R", F(2, 3), (0, 0, 1)), ("R", F(2, 3), (0, 0, -1)), ("I", F(1, 3)))
    n2 = (("I", F(1, 3)), ("I", F(2, 3)))
    functional = True
    for menu in (n1, n2):
        vals = dict(zip(menu, rule_values(menu, "UNIFORM")))
        functional = functional and len(vals) == len(menu)
    checks.check(
        "T4-vacuity-lemma",
        "the menu is a function of the condition, so the candidate sentence holds verbatim",
        functional,
    )
    u1 = dict(zip(n1, rule_values(n1, "UNIFORM")))[("I", F(1, 3))]
    u2 = dict(zip(n2, rule_values(n2, "UNIFORM")))[("I", F(1, 3))]
    checks.check(
        "T4-candidate-is-vacuous",
        "that same law is menu-dependent at 1/3 against 1/2, so the sentence has no force",
        u1 != u2,
    )
    fibred_needed = t3_facts["odds_at_three"] > 1
    abundance_needed = t2_facts["law_nullity"] == 21 and t2_facts["rogue_survives"]
    import_named = "standard dimension-three frame-function theorem" in normalize(parent) \
        or "dimension-three frame theorem" in normalize(parent)
    checks.check(
        "T4-price-is-three",
        "three items, three witnesses: fibred grading, abundance, the named frame import",
        fibred_needed and abundance_needed and import_named and len(menus) < 200,
    )


def main():
    started = time.time()
    checks = Checks()
    note = NOTE_PATH.read_text(encoding="utf-8")
    parent = PARENT_NOTE.read_text(encoding="utf-8")
    axiom = AXIOM_PATH.read_text(encoding="utf-8")

    print("external_scientific_inputs: the canonical axiom file and the 2026-08-09 parent note are read only for source gates")
    print("package_local_integrity_reads: the source note is read for claim-surface consistency; the cache envelope binds the declared inputs")
    print("standard_theorem_boundary: the dimension-three frame-function theorem is named, not recomputed")
    print("arithmetic_boundary: T1 and T2 are exact; T3 inherits float64 and rests only on the odds being distinct")

    menus = t1(checks)
    t1_torus(checks)
    t2_facts = t2(checks, menus)
    t3_facts = t3(checks)
    t4(checks, menus, t2_facts, t3_facts, parent)

    checks.check(
        "source-admissibility",
        "the local distribution is nearest-neighbor determined and varying",
        "the probability distribution over the possibilities is determined by, and varies with, the nearest-neighbor conditions" in normalize(axiom),
    )
    checks.check(
        "source-admissibility-support",
        "reading note (3): available and admissible denote that support",
        '"available"/"admissible" denotes its support' in normalize(axiom),
    )
    checks.check(
        "source-record",
        "a record locks exactly one admissible possibility and only records are readable",
        "When present, a record locks exactly one admissible local possibility" in normalize(axiom)
        and "Only records are readable" in normalize(axiom),
    )
    checks.check(
        "source-parent-clauses",
        "the parent states its two clauses as independent conditional clauses",
        "its value depends on the effect, not on a menu containing it" in normalize(parent)
        and "two independent conditional clauses" in normalize(parent),
    )
    checks.check(
        "surface-status",
        "the note keeps its conditional surface and independent audit explicit",
        all(s in normalize(note) for s in ("actual_current_surface_status: conditional-support",
                                "audit_required_before_effective_retained: true",
                                "no canonical axiom edit",
                                "Independent audit remains required")),
    )

    print("per_element: every menu, possibility, odds value, rank row and record block is checked as a declared element")
    print("per_site: one M_2(C) site under a Z^3 law and one twelve-qubit cube; no wider carrier is asserted")
    print("per_mode: odd and unrestricted sphere-polynomial sections through degree five by exact rational rank")
    print("per_block: the witness law, the abundance certificates, the record blocks and the candidates together")
    print("lattice_wide: executed on the 7^6 alphabet and a 3^3 torus for covariance only; no lattice-wide Born claim")
    print(f"runtime_seconds: {time.time() - started:.1f}")
    return checks.finish()


if __name__ == "__main__":
    raise SystemExit(main())
