"""Multi-site Pauli group P_N on a stipulated N-qubit tensor product has order 4^{N+1};
its minimal generating set has 2N+1 elements (the global phase is shared).

This runner verifies the finite algebraic theorem on
H_N = (C²)^{⊗ N}. It does not verify, import, or require a physical
framework Fock-space identification H_x ≅ C². The retained per-site Cl(3)
note is compatible algebraic context for the local Pauli realization, but
the load-bearing checks below are direct matrix/group computations.

The multi-site Pauli group P_N is generated by the sitewise σ_i,x acting at
each site x ∈ {1, ..., N}:

    P_N  =  ⟨σ_{i, x} : i ∈ {1, 2, 3}, x ∈ {1, ..., N}⟩

By the per-site Pauli group result (R8 Block 03), each site contributes a
factor of P_1 / Z(P_1) ≅ Z_2 × Z_2 (4 cosets), and the central scalar
phases ±1, ±i are global (4 phase elements).

Total order:  |P_N|  =  4 · 4^N  =  4^{N+1}.

(4 from the central Z_4 scalar phase ⊗ 4^N from per-site (Z_2 × Z_2)
matrix choices.)

For N = 1: |P_1| = 4 · 4 = 16 ✓ (matches R8 Block 03)
For N = 2: |P_2| = 4 · 16 = 64
For N = 3: |P_3| = 4 · 64 = 256

MINIMAL GENERATOR COUNT (corrected 2026-05-29).
The center Z_4 = {±I, ±i I} is a SINGLE global subgroup shared across the
whole register, NOT a per-site factor. So the minimal generating set is:
  - site 1 supplies X_1, Z_1, and ONE phase generator (e.g. the Y_1 that
    carries the global i, or i·I directly) — 3 generators;
  - each additional site supplies only X_j, Z_j — 2 generators each.
Total minimal = 3 + 2(N-1) = 2N + 1, NOT 3N.

The reason 2N+1 (not 3N): once one site supplies the global phase i, the
third Pauli at every site is recovered for free, because
σ_3,x = -i σ_1,x σ_2,x and the i is already in the group. Concretely
Z_x = -i X_x · (i·I) · ... — more directly Y_x = i X_x Z_x is obtained from
the shared i·I and the site-x pair (X_x, Z_x). So per additional site only
two anticommuting Paulis are needed.

Lower bound (2N generators are NOT enough): the 2N site-Paulis
{X_i, Z_i : i=1..N} generate a proper subgroup of order 2·4^N (the
phaseless / real-sign Pauli group {±1}×(Z_2×Z_2)^N). This subgroup does
NOT contain i·I, so it cannot equal P_N (order 4^{N+1} = 4·4^N). Adding any
ONE phase generator (i·I, or one Y on a single site) closes the gap to the
full P_N. Hence 2N+1 is both necessary and sufficient.

Tests:
  (T1) For N = 1, group has order 16 (recover R8 Block 03)
  (T2) For N = 2, group has order 64
  (T3) For N = 3, group has order 256
  (T4) Order formula |P_N| = 4^{N+1} matches numerical enumeration
  (T5) Center Z(P_N) = {±I_total, ±i I_total} of order 4 (scalar phases)
  (T6) Quotient P_N / Z(P_N) ≅ (Z_2 × Z_2)^N has order 4^N
  (T7) The 2N site-Paulis ⟨X_i, Z_i⟩ generate the phaseless group of order
       2·4^N and do NOT contain i·I — so 2N generators are insufficient.
  (T8) Adding ONE phase generator (i·I) to the 2N site-Paulis yields the
       full P_N of order 4^{N+1}; total minimal generating set = 2N+1.
  (T9) Equivalently, {X_i, Z_i : i=1..N} ∪ {Y_1} (one Y on a single site)
       — a different 2N+1 set — also generates the full P_N.
  (T10) Minimality lower bound (subset search): NO set of 2N site-Paulis
        reaches the full group. Checked exhaustively for N=1,2 over all
        2N-subsets of the per-site Pauli generator pool (which already
        includes the i-phase carriers Y_i), confirming 2N is impossible.
  (T11) Minimality lower bound (abelianization, generator-type-independent):
        [P_N, P_N] = {±I} has order 2, and every g ∈ P_N satisfies g² ∈
        {±I}, so the abelianization P_N/[P_N,P_N] is an elementary-abelian
        2-group of order 2^{2N+1}, i.e. rank 2N+1. Any generating set of
        P_N must surject onto a generating set of this quotient, so it has
        ≥ 2N+1 elements — for ANY choice of generators, not only Paulis.
        Combined with T8/T9 (a 2N+1 set that works), the minimal generating
        set size is EXACTLY 2N+1.
"""
from __future__ import annotations

from itertools import combinations

import numpy as np


def kron_chain(matrices: list[np.ndarray]) -> np.ndarray:
    result = matrices[0]
    for M in matrices[1:]:
        result = np.kron(result, M)
    return result


def at_site(local_op: np.ndarray, x: int, N: int) -> np.ndarray:
    I2 = np.eye(2, dtype=complex)
    factors = [local_op if i == x else I2 for i in range(N)]
    return kron_chain(factors)


def matrix_in_set(M: np.ndarray, set_: list[np.ndarray]) -> bool:
    for E in set_:
        if np.linalg.norm(M - E) < 1e-10:
            return True
    return False


def generate_group(generators: list[np.ndarray], dim: int, max_iter: int = 200):
    """BFS-generate the multiplicative group, return (order, elements)."""
    Iden = np.eye(dim, dtype=complex)
    elements = [Iden.copy()]
    new = True
    iter_count = 0
    while new and iter_count < max_iter:
        new = False
        for E in elements[:]:
            for g in generators:
                product = E @ g
                if not matrix_in_set(product, elements):
                    elements.append(product)
                    new = True
        iter_count += 1
    return len(elements), elements


# Single-qubit Pauli matrices.
S1 = np.array([[0, 1], [1, 0]], dtype=complex)       # X
S2 = np.array([[0, -1j], [1j, 0]], dtype=complex)    # Y
S3 = np.array([[1, 0], [0, -1]], dtype=complex)      # Z


def full_generators(N: int) -> list[np.ndarray]:
    """All 3N site-Paulis σ_{i,x} (X, Y, Z at each site)."""
    gens = []
    for x in range(N):
        for sigma in (S1, S2, S3):
            gens.append(at_site(sigma, x, N))
    return gens


def xz_generators(N: int) -> list[np.ndarray]:
    """The 2N site-Paulis {X_x, Z_x : x=0..N-1} (no Y, no explicit phase)."""
    gens = []
    for x in range(N):
        gens.append(at_site(S1, x, N))  # X_x
        gens.append(at_site(S3, x, N))  # Z_x
    return gens


def main() -> None:
    print("=" * 72)
    print("MULTI-SITE PAULI GROUP P_N: ORDER 4^{N+1}, MINIMAL GENERATORS 2N+1")
    print("=" * 72)
    print()

    results = {}

    for N in (1, 2, 3):
        dim = 2 ** N
        print(f"  Generating P_{N} on {N}-site Hilbert (dim = {dim})...")
        order, _ = generate_group(full_generators(N), dim)
        results[N] = order
        expected = 4 ** (N + 1)
        print(f"    P_{N}: observed order = {order}, expected 4^{N+1} = {expected}")
        print()

    # ----- Test 1: N=1 (recover R8 Block 03) -----
    print("-" * 72)
    print("TEST 1: |P_1| = 16  (recovers R8 Block 03 for N = 1)")
    print("-" * 72)
    print(f"  observed: {results[1]}, expected: 16")
    t1_ok = results[1] == 16
    print(f"  STATUS: {'PASS' if t1_ok else 'FAIL'}")
    print()

    # ----- Test 2: N=2 -----
    print("-" * 72)
    print("TEST 2: |P_2| = 64")
    print("-" * 72)
    print(f"  observed: {results[2]}, expected: 64")
    t2_ok = results[2] == 64
    print(f"  STATUS: {'PASS' if t2_ok else 'FAIL'}")
    print()

    # ----- Test 3: N=3 -----
    print("-" * 72)
    print("TEST 3: |P_3| = 256")
    print("-" * 72)
    print(f"  observed: {results[3]}, expected: 256")
    t3_ok = results[3] == 256
    print(f"  STATUS: {'PASS' if t3_ok else 'FAIL'}")
    print()

    # ----- Test 4: General formula |P_N| = 4^{N+1} -----
    print("-" * 72)
    print("TEST 4: Formula |P_N| = 4^{N+1} matches all observed orders")
    print("-" * 72)
    all_match = all(results[N] == 4 ** (N + 1) for N in (1, 2, 3))
    print(f"  N = 1: {results[1]} = 4^2 = {4**2}")
    print(f"  N = 2: {results[2]} = 4^3 = {4**3}")
    print(f"  N = 3: {results[3]} = 4^4 = {4**4}")
    t4_ok = all_match
    print(f"  STATUS: {'PASS' if t4_ok else 'FAIL'}")
    print()

    # ----- Test 5: Center for N = 2 -----
    print("-" * 72)
    print("TEST 5: Center Z(P_2) = {±I, ±iI} of order 4 (scalar phases only)")
    print("-" * 72)
    N = 2
    dim = 4
    gens2 = full_generators(N)
    _, elements = generate_group(gens2, dim)
    Iden = np.eye(dim, dtype=complex)
    center = []
    for E in elements:
        is_central = all(np.linalg.norm(E @ g - g @ E) < 1e-10 for g in gens2)
        if is_central:
            center.append(E)
    print(f"  |Z(P_2)| = {len(center)}")
    expected_center = [Iden, -Iden, 1j * Iden, -1j * Iden]
    center_match = all(matrix_in_set(C, expected_center) for C in center)
    print(f"  Center = {{±I, ±iI}}: {center_match}")
    t5_ok = len(center) == 4 and center_match
    print(f"  STATUS: {'PASS' if t5_ok else 'FAIL'}")
    print()

    # ----- Test 6: Quotient P_N / Z(P_N) has order 4^N -----
    print("-" * 72)
    print("TEST 6: P_N / Z(P_N) has order 4^N (the (Z_2 × Z_2)^N coset structure)")
    print("-" * 72)
    quotient_orders = {N: results[N] // 4 for N in (1, 2, 3)}
    expected_quotient = {N: 4 ** N for N in (1, 2, 3)}
    print(f"  N = 1: |P_1 / Z| = {quotient_orders[1]} = 4^1 = {expected_quotient[1]}")
    print(f"  N = 2: |P_2 / Z| = {quotient_orders[2]} = 4^2 = {expected_quotient[2]}")
    print(f"  N = 3: |P_3 / Z| = {quotient_orders[3]} = 4^3 = {expected_quotient[3]}")
    t6_ok = all(quotient_orders[N] == expected_quotient[N] for N in (1, 2, 3))
    print(f"  STATUS: {'PASS' if t6_ok else 'FAIL'}")
    print()

    # ===================================================================
    # CORRECTED MINIMAL-GENERATOR-COUNT TESTS (2026-05-29).
    # The center Z_4 is a single GLOBAL subgroup, not a per-site factor.
    # Minimal generating set = 2N + 1, not 3N.
    # ===================================================================

    # ----- Test 7: 2N site-Paulis are INSUFFICIENT (no i·I) -----
    print("-" * 72)
    print("TEST 7: 2N site-Paulis ⟨X_i, Z_i⟩ generate phaseless group of")
    print("        order 2·4^N and do NOT contain i·I (insufficient for P_N)")
    print("-" * 72)
    t7_subresults = {}
    t7_ok = True
    for N in (1, 2, 3):
        dim = 2 ** N
        order_xz, elts_xz = generate_group(xz_generators(N), dim)
        expected_phaseless = 2 * 4 ** N
        iI = 1j * np.eye(dim, dtype=complex)
        has_iI = matrix_in_set(iI, elts_xz)
        full_order = 4 ** (N + 1)
        ok = (
            order_xz == expected_phaseless
            and not has_iI
            and order_xz < full_order
        )
        t7_subresults[N] = (order_xz, has_iI)
        print(
            f"  N = {N}: |⟨X_i,Z_i⟩| = {order_xz} "
            f"(expected phaseless 2·4^{N} = {expected_phaseless}); "
            f"contains i·I? {has_iI}; full |P_{N}| = {full_order}"
        )
        t7_ok = t7_ok and ok
    print(f"  STATUS: {'PASS' if t7_ok else 'FAIL'}")
    print()

    # ----- Test 8: 2N+1 generators (site-Paulis + i·I) are SUFFICIENT -----
    print("-" * 72)
    print("TEST 8: 2N site-Paulis + ONE phase generator (i·I) = full P_N;")
    print("        minimal generating set size = 2N+1")
    print("-" * 72)
    t8_ok = True
    for N in (1, 2, 3):
        dim = 2 ** N
        gens = xz_generators(N) + [1j * np.eye(dim, dtype=complex)]
        n_gens = len(gens)
        order_plus, _ = generate_group(gens, dim)
        full_order = 4 ** (N + 1)
        ok = order_plus == full_order and n_gens == 2 * N + 1
        print(
            f"  N = {N}: {n_gens} generators (= 2N+1 = {2*N+1}); "
            f"|⟨...⟩| = {order_plus}, expected full {full_order}"
        )
        t8_ok = t8_ok and ok
    print(f"  STATUS: {'PASS' if t8_ok else 'FAIL'}")
    print()

    # ----- Test 9: alternative 2N+1 set (site-Paulis + one Y) -----
    print("-" * 72)
    print("TEST 9: alternative minimal set {X_i, Z_i} ∪ {Y_0} (one Y on a")
    print("        single site) — also 2N+1 generators — generates full P_N")
    print("-" * 72)
    t9_ok = True
    for N in (1, 2, 3):
        dim = 2 ** N
        gens = xz_generators(N) + [at_site(S2, 0, N)]  # add Y at site 0
        n_gens = len(gens)
        order_alt, _ = generate_group(gens, dim)
        full_order = 4 ** (N + 1)
        ok = order_alt == full_order and n_gens == 2 * N + 1
        print(
            f"  N = {N}: {n_gens} generators (= 2N+1 = {2*N+1}); "
            f"|⟨X_i,Z_i,Y_0⟩| = {order_alt}, expected full {full_order}"
        )
        t9_ok = t9_ok and ok
    print(f"  STATUS: {'PASS' if t9_ok else 'FAIL'}")
    print()

    # ----- Test 10: lower bound — NO 2N site-Paulis reach the full group -----
    print("-" * 72)
    print("TEST 10: minimality lower bound — exhaustively, NO size-2N subset")
    print("         of the 3N site-Pauli pool generates the full P_N")
    print("         (so 2N is impossible; minimal is 2N+1). N = 1, 2.")
    print("-" * 72)
    t10_ok = True
    for N in (1, 2):
        dim = 2 ** N
        pool = full_generators(N)  # all 3N site-Paulis (incl. the Y i-carriers)
        full_order = 4 ** (N + 1)
        k = 2 * N
        any_reaches_full = False
        n_subsets = 0
        max_subset_order = 0
        for subset in combinations(pool, k):
            n_subsets += 1
            order_sub, _ = generate_group(list(subset), dim)
            max_subset_order = max(max_subset_order, order_sub)
            if order_sub == full_order:
                any_reaches_full = True
                break
        ok = not any_reaches_full
        print(
            f"  N = {N}: checked all {n_subsets} size-{k} subsets of "
            f"{len(pool)} site-Paulis; max order reached = {max_subset_order}, "
            f"full = {full_order}; any reaches full? {any_reaches_full}"
        )
        t10_ok = t10_ok and ok
    print(f"  STATUS: {'PASS' if t10_ok else 'FAIL'}")
    print()

    # ----- Test 11: abelianization rank lower bound (any generator type) ---
    print("-" * 72)
    print("TEST 11: abelianization P_N/[P_N,P_N] is elementary-abelian of")
    print("         rank 2N+1, so ANY generating set needs ≥ 2N+1 elements")
    print("         (generator-type-independent lower bound). N = 1, 2.")
    print("-" * 72)
    t11_ok = True
    for N in (1, 2):
        dim = 2 ** N
        _, els = generate_group(full_generators(N), dim)
        # Commutator subgroup [P_N, P_N].
        comms: list[np.ndarray] = []
        for a in els:
            ainv = np.linalg.inv(a)
            for b in els:
                c = a @ b @ ainv @ np.linalg.inv(b)
                if not matrix_in_set(c, comms):
                    comms.append(c)
        abel_order = len(els) // len(comms)
        rank = abel_order.bit_length() - 1  # log2(abel_order)
        # Elementary-abelian iff every g^2 lands in the commutator subgroup.
        elem_ab = all(matrix_in_set(a @ a, comms) for a in els)
        expected_rank = 2 * N + 1
        ok = (
            len(comms) == 2
            and 2 ** rank == abel_order
            and elem_ab
            and rank == expected_rank
        )
        print(
            f"  N = {N}: |[P_N,P_N]| = {len(comms)}, "
            f"|abelianization| = {abel_order} = 2^{rank}, "
            f"elementary-abelian? {elem_ab}; rank = {rank} "
            f"(= 2N+1 = {expected_rank}) ⇒ min generators ≥ {expected_rank}"
        )
        t11_ok = t11_ok and ok
    print(f"  STATUS: {'PASS' if t11_ok else 'FAIL'}")
    print()

    # ----- Scorecard -----
    print("=" * 72)
    print("  SCORECARD")
    print("=" * 72)
    print(f"  Test 1  (|P_1| = 16):                              {'PASS' if t1_ok else 'FAIL'}")
    print(f"  Test 2  (|P_2| = 64):                              {'PASS' if t2_ok else 'FAIL'}")
    print(f"  Test 3  (|P_3| = 256):                             {'PASS' if t3_ok else 'FAIL'}")
    print(f"  Test 4  (formula |P_N| = 4^{{N+1}}):                {'PASS' if t4_ok else 'FAIL'}")
    print(f"  Test 5  (Z(P_N) = scalar phases, order 4):         {'PASS' if t5_ok else 'FAIL'}")
    print(f"  Test 6  (quotient order = 4^N):                    {'PASS' if t6_ok else 'FAIL'}")
    print(f"  Test 7  (2N site-Paulis insufficient, no i·I):     {'PASS' if t7_ok else 'FAIL'}")
    print(f"  Test 8  (2N+1 = site-Paulis + i·I sufficient):     {'PASS' if t8_ok else 'FAIL'}")
    print(f"  Test 9  (alt 2N+1 = site-Paulis + one Y):          {'PASS' if t9_ok else 'FAIL'}")
    print(f"  Test 10 (no 2N subset reaches full):               {'PASS' if t10_ok else 'FAIL'}")
    print(f"  Test 11 (abelianization rank 2N+1 lower bound):    {'PASS' if t11_ok else 'FAIL'}")
    all_ok = all([t1_ok, t2_ok, t3_ok, t4_ok, t5_ok, t6_ok, t7_ok, t8_ok, t9_ok, t10_ok, t11_ok])
    print(f"  OVERALL: {'PASS' if all_ok else 'FAIL'}")
    if not all_ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
