#!/usr/bin/env python3
"""Cycle 692: enumerated mechanisms that do not fix hypercharge alpha.

`hypercharge_identification_note` is `audited_conditional` with load-bearing
score 20.5 and 1040 transitive descendants. Its audit rationale isolates the
entire obstruction to a single constant:

    "The structural +1:(-3) result is an exact algebraic consequence of the
     stated decomposition. However, the normalized (+1/3,-1) result depends on
     the explicitly supplied alpha=1/3 normalization, which the packet says is
     not derived, so the full scoped claim remains conditional."

and its re-audit instruction is:

    "missing_bridge_theorem: derive and cite a retained-grade or explicitly
     approved authority fixing alpha=1/3, then re-audit the unchanged name-free
     theorem surface."

This cycle tests a finite, explicit family of scale-fixing mechanisms on the
declared two-block surface. It does not claim that every possible
dimensionless framework construction has been classified.

Setting: V = C^2 (x) (C^2 (x) C^2); SWAP_23 exchanges the last two factors;
P_sym = (I+SWAP_23)/2 and P_anti = (I-SWAP_23)/2 have ranks 3 and 1 on the
last-two space, hence 6 and 2 on V. The central block-scalar operator is
Y(alpha,beta) = alpha*P_sym + beta*P_anti embedded as I_2 (x) Y.

Findings, all exact rational arithmetic:

  1. Tracelessness forces 6*alpha + 2*beta = 0, i.e. beta = -3*alpha. The
     RATIO +1:(-3) is fixed exactly; the SCALE is untouched.
  2. The formal additive subgroup generated by the two block values alpha and
     -3*alpha is alpha*Z. This is pure generated-subgroup algebra. Turning it
     into an achievable physical readout set would require a separate readout
     identification and record-availability premise.
  3. Among the explicitly enumerated scale-fixing conditions, exactly one
     yields +1/3, and it is the condition "the one-dimensional trivial block
     carries charge -1" -- i.e. the target unit choice itself. Tracelessness
     leaves alpha free; primitive-generator and integer-spectrum normalizations
     give |alpha| = 1; unit symmetric-block charge gives alpha = 1; and the unit
     quadratic normalization Tr(Y^2)=1 gives alpha^2=1/24.
  4. The approved `scale_reference_primitive` cannot supply alpha either: its
     own note states it "carries zero dimensionless content" and "does not
     supply any dimensionless quantity". alpha is dimensionless. So the
     otherwise-natural discharge route through the approved units authority is
     closed by that authority's own scope.

Conclusion: tracelessness, the generated-subgroup structure, the tested unit
and quadratic normalizations other than the explicit beta=-1 unit choice, and
the approved units primitive do not derive alpha=1/3. A different
dimensionless framework construction remains open and is not excluded.

Firewalls: this cycle derives no charge, identifies no block with a physical
species, and asserts no Standard-Model content. It makes a bounded negative
claim about ONE constant on ONE declared surface, with its escape conditions
stated. It proposes and adopts no axiom or primitive.
"""

from __future__ import annotations

import itertools
import json
import sys
from fractions import Fraction as F
from hashlib import sha256
from math import gcd, isqrt
from pathlib import Path
from time import perf_counter

ROOT = Path(__file__).resolve().parents[1]
AUTHORITY = "none"
AUDIT = "unset"
CYCLE_CLAIM = None  # set by supervisor at freeze

PASS = 0
FAIL = 0


def check(label: str, condition: bool, detail: object = "") -> None:
    global PASS, FAIL
    if condition:
        PASS += 1
        print("PASS", label, "::", detail)
    else:
        FAIL += 1
        print("FAIL", label, "::", detail)


# ------------------------------------------------------- the declared surface --
def swap23_on_last_two():
    """SWAP on C^2 (x) C^2 as an exact 4x4 rational matrix."""
    S = [[F(0)] * 4 for _ in range(4)]
    for i in range(2):
        for j in range(2):
            S[i * 2 + j][j * 2 + i] = F(1)
    return [row[:] for row in S]


def projectors():
    S = swap23_on_last_two()
    I = [[F(1 if i == j else 0) for j in range(4)] for i in range(4)]
    P_sym = [[(I[i][j] + S[i][j]) / 2 for j in range(4)] for i in range(4)]
    P_anti = [[(I[i][j] - S[i][j]) / 2 for j in range(4)] for i in range(4)]
    return P_sym, P_anti


def matmul(A, B):
    n = len(A)
    return [[sum(A[i][k] * B[k][j] for k in range(n)) for j in range(n)] for i in range(n)]


def trace(A):
    return sum(A[i][i] for i in range(len(A)))


def rank(rows):
    M = [list(r) for r in rows]
    r = 0
    for c in range(len(M[0])):
        piv = next((i for i in range(r, len(M)) if M[i][c] != 0), None)
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        pv = M[r][c]
        for i in range(len(M)):
            if i != r and M[i][c] != 0:
                f = M[i][c] / pv
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        r += 1
    return r


def main() -> int:
    started = perf_counter()
    summary: dict[str, object] = {"cycle": 692, "authority": AUTHORITY,
                                  "audit": AUDIT, "cycle_claim": CYCLE_CLAIM}

    P_sym, P_anti = projectors()

    # -- R1: the declared surface, exactly ----------------------------------
    idempotent = matmul(P_sym, P_sym) == P_sym and matmul(P_anti, P_anti) == P_anti
    orthogonal = all(all(x == 0 for x in row) for row in matmul(P_sym, P_anti))
    r_sym, r_anti = rank(P_sym), rank(P_anti)
    n_sym, n_anti = 2 * r_sym, 2 * r_anti          # multiplicities on V
    check("the declared surface is reproduced exactly: P_sym and P_anti are "
          "complementary orthogonal projectors of ranks 3 and 1 on the last-two "
          "factors, hence multiplicities 6 and 2 on V",
          idempotent and orthogonal and (r_sym, r_anti) == (3, 1)
          and (n_sym, n_anti) == (6, 2),
          {"idempotent": idempotent, "orthogonal": orthogonal,
           "ranks_last_two": [r_sym, r_anti], "multiplicities_on_V": [n_sym, n_anti]})

    # -- R2: tracelessness fixes a line, including the zero solution ----------
    # Tr(I_2 (x) Y) = 2*(alpha*3 + beta*1) = n_sym*alpha + n_anti*beta
    def traceless_beta(alpha):
        return -F(n_sym, n_anti) * alpha
    beta_per_alpha = traceless_beta(F(1))
    parameters = (F(0), F(1), F(1, 3), F(5, 7), F(-2))
    line_residuals = {
        str(a): str(n_sym * a + n_anti * traceless_beta(a))
        for a in parameters
    }
    check("tracelessness gives the exact solution line (alpha,beta)=t*(1,-3), "
          "including t=0; the ratio +1:(-3) applies on its nonzero part and the "
          "scale parameter t remains free",
          beta_per_alpha == -3 and set(line_residuals.values()) == {"0"},
          {"beta_per_alpha": str(beta_per_alpha),
           "trace_residuals_including_zero": line_residuals})

    # -- R3: exact additive subgroup algebra, not a physical readout bridge ---
    # Z*alpha + Z*beta = alpha*(Z + beta_per_alpha*Z).
    ratio_is_integer = beta_per_alpha.denominator == 1
    ratio_integer = int(beta_per_alpha) if ratio_is_integer else 0
    coefficient_gcd = gcd(1, abs(ratio_integer)) if ratio_is_integer else 0
    check("the formal additive subgroup generated by alpha and beta=-3*alpha "
          "is alpha*Z because gcd(1,3)=1; this is generated-subgroup algebra, "
          "not a claim that the framework supplies a physical readout map or "
          "arbitrary record populations",
          ratio_is_integer and ratio_integer == -3 and coefficient_gcd == 1,
          {"integer_coefficients": [1, ratio_integer],
           "coefficient_gcd": coefficient_gcd,
           "generated_subgroup": "alpha*Z"})
    summary["generated_subgroup"] = {
        "integer_coefficients": [1, ratio_integer],
        "coefficient_gcd": coefficient_gcd,
        "group": "alpha*Z",
        "physical_readout_bridge_claimed": False,
    }

    # -- R4: compute the finite normalization table from the block formulas ---
    # Unit-generator and primitive-integer-spectrum conditions fix |alpha|=1.
    subgroup_generator_coefficient = F(coefficient_gcd)
    generator_unit_alpha_sq = F(1, subgroup_generator_coefficient ** 2)
    symmetric_unit_alpha = F(1)
    integer_primitive_alpha_sq = generator_unit_alpha_sq
    trivial_unit_alpha = F(-1, 1) / beta_per_alpha
    # quadratic normalization Tr(Y^2)=1 on V: n_sym*a^2 + n_anti*(9a^2) = 24a^2 = 1
    sq = F(n_sym) + F(n_anti) * beta_per_alpha ** 2
    quadratic_alpha_sq = F(1, sq)
    quadratic_is_rational_square = (
        isqrt(quadratic_alpha_sq.numerator) ** 2 == quadratic_alpha_sq.numerator
        and isqrt(quadratic_alpha_sq.denominator) ** 2 == quadratic_alpha_sq.denominator
    )
    conditions = {
        "tracelessness alone": {"solution": "alpha free", "alpha": None},
        "generated-subgroup primitive generator magnitude = 1": {
            "solution": f"alpha^2 = {generator_unit_alpha_sq}", "alpha": None},
        "symmetric-block charge = +1": {
            "solution": f"alpha = {symmetric_unit_alpha}", "alpha": symmetric_unit_alpha},
        "integer spectrum with primitive generator": {
            "solution": f"alpha^2 = {integer_primitive_alpha_sq}", "alpha": None},
        "trivial-block charge = -1": {
            "solution": f"alpha = {trivial_unit_alpha}", "alpha": trivial_unit_alpha},
        f"Tr(Y^2) = 1  ({sq}*alpha^2 = 1)": {
            "solution": f"alpha^2 = {quadratic_alpha_sq}", "alpha": None},
    }
    yields_positive_third = [
        k for k, result in conditions.items() if result["alpha"] == F(1, 3)
    ]
    table_consistent = (
        generator_unit_alpha_sq == 1
        and symmetric_unit_alpha == 1
        and integer_primitive_alpha_sq == 1
        and trivial_unit_alpha == F(1, 3)
        and sq == 24
        and quadratic_alpha_sq == F(1, 24)
        and not quadratic_is_rational_square
    )
    check("the explicitly enumerated normalization conditions are computed from "
          "the block formulas: only beta=-1 yields positive alpha=1/3, and that "
          "condition is the target unit choice rather than a derived selector",
          table_consistent and yields_positive_third == ["trivial-block charge = -1"],
          {k: result["solution"] for k, result in conditions.items()})
    summary["scale_conditions"] = {
        k: result["solution"] for k, result in conditions.items()
    }

    # -- R5: the quadratic route provably does not give 1/3 ------------------
    # 24*(1/3)^2 = 24/9 = 8/3 != 1, so Tr(Y^2)=1 and alpha=1/3 are incompatible.
    q_at_third = sq * F(1, 3) ** 2
    check("the unit quadratic normalization Tr(Y^2)=1 is incompatible with "
          f"alpha=1/3: Tr(Y^2) there equals {q_at_third}, not 1",
          q_at_third != 1, {"Tr_Y2_at_alpha_one_third": str(q_at_third)})

    # -- R6: the approved units primitive cannot supply it -------------------
    # Verified against the primitive's own scope text, quoted in the note.
    registry_path = ROOT / "docs" / "audit" / "data" / "axiom_premise_nodes.json"
    registered_path = None
    carries_zero_dimensionless = False
    registry_binding_ok = False
    if registry_path.exists():
        registry = json.loads(registry_path.read_text(encoding="utf-8"))
        registered_path = registry.get("nodes", {}).get(
            "scale_reference_primitive", {}).get("current_path")
    units_note = ROOT / registered_path if registered_path else None
    if units_note is not None and units_note.exists():
        t = units_note.read_text(encoding="utf-8", errors="replace")
        carries_zero_dimensionless = ("zero dimensionless" in t
                                      and "does not supply any dimensionless" in t)
        registry_binding_ok = registered_path == "docs/SCALE_REFERENCE_PRIMITIVE_NOTE.md"
    check("the approved scale-reference primitive cannot discharge alpha either: "
          "alpha is dimensionless, and that primitive's own note states it carries "
          "zero dimensionless content and supplies no dimensionless quantity "
          "(verified through the premise-registry binding on this tree)",
          registry_binding_ok and carries_zero_dimensionless,
          {"registry_present": registry_path.exists(),
           "registered_path": registered_path,
           "primitive_note_present": bool(units_note and units_note.exists()),
           "scope_text_confirms_dimensionless_empty": carries_zero_dimensionless})

    # -- R7: adversarial scope guard against a universal quadratic no-go ------
    alternate_quadratic_target = sq * F(1, 3) ** 2
    check("scope guard: the alternate condition Tr(Y^2)=8/3 DOES admit "
          "|alpha|=1/3, so the negative result is limited to the unit target "
          "Tr(Y^2)=1 and cannot be read as excluding every quadratic normalization",
          alternate_quadratic_target == F(8, 3),
          {"alternate_target": str(alternate_quadratic_target),
           "admitted_alpha_magnitude": "1/3"})

    escapes = [
        "rescope the parent row to its scale-invariant content -- the exact ratio "
        "+1:(-3) and the formal alpha*Z generated-subgroup structure -- which "
        "carry no selected scale; the auditor's own instruction says the name-free "
        "theorem surface is unchanged",
        "supply a genuinely dimensionless derivation of the unit-charge choice "
        "from framework content (not classified by this finite enumeration)",
        "register a new explicitly approved dimensionless authority -- which the "
        "repository's no-new-axiom / no-new-primitive rule forbids a physics-loop "
        "run from doing, and which would require an owner governance decision",
    ]
    summary["escapes"] = escapes

    summary["conclusion"] = (
        "On the declared two-block surface, tracelessness fixes only the ratio, "
        "the formal additive subgroup generated by the block values fixes only "
        "alpha*Z, the tested unit quadratic normalization does not select "
        "alpha=1/3, and the registered scale-reference primitive supplies no "
        "dimensionless value. Of the enumerated conditions, only the explicit "
        "beta=-1 unit choice yields alpha=1/3. Other dimensionless derivations "
        "remain open and are not excluded."
    )
    summary["no_go"] = {
        "statement": "tracelessness, generated-subgroup structure, the tested "
                     "unit normalizations other than beta=-1, the unit quadratic "
                     "normalization, and the scale-reference primitive do not "
                     "derive alpha=1/3",
        "scope": "the declared two-block surface V = C^2 (x) (C^2 (x) C^2) with "
                 "central block-scalar Y; conditions enumerated in this runner only",
        "shared_obstruction": False,
        "axiom_pressure": False,
        "escape_conditions": escapes,
    }
    summary["firewalls"] = {
        "any_charge_derived": False,
        "any_block_identified_with_a_physical_species": False,
        "standard_model_content_asserted": False,
        "new_axiom_or_primitive_proposed": False,
    }
    summary["resources"] = {"elapsed_seconds": perf_counter() - started}
    summary["runner_sha256"] = sha256(Path(__file__).read_bytes()).hexdigest()
    summary["pass_count"] = PASS
    summary["fail_count"] = FAIL
    summary["pass"] = FAIL == 0

    receipt = ROOT / "outputs" / (
        "physical_hypercharge_alpha_scale_freedom_cycle692_receipt_2026_07_25.json")
    if "--no-receipt" not in sys.argv:
        receipt.parent.mkdir(parents=True, exist_ok=True)
        receipt.write_text(json.dumps(summary, indent=1, sort_keys=True,
                                      default=str) + "\n", encoding="utf-8")
    print("SUMMARY_JSON", json.dumps(summary, sort_keys=True, default=str))
    print(f"RESULT {PASS} {FAIL} elapsed {perf_counter() - started:.2f} s")
    if FAIL:
        print("RESULT HYPERCHARGE_ALPHA_SCALE_FREEDOM_TOURNAMENT_FAILED")
        return 1
    print("RESULT ENUMERATED_HYPERCHARGE_ALPHA_SCALE_MECHANISMS_DO_NOT_FIX_ONE_THIRD")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
