#!/usr/bin/env python3
"""Cycle 704: record-register symplectic dilation of the executed Cycle-700
readout channel.

The Cycle-700 harness executes an open readout: an affine-linear symplectic
leapfrog on (phi, pi) over a Z^3 box, driven by a supplied frozen source, whose
kept output is the hold-window time average at four detector sites. Everything
not kept is discarded, and that discard is the open-system step.

This harness adjoins a record register pair (A, B) of size k = 4 and one exact
symplectic shear per hold step, generated by the coupling Hamiltonian
H_c = B . (P phi) with (phi, A) as positions and (pi, B) as momenta. It then
gates, against the landed Cycle-700 anchors: bit-for-bit non-disturbance on the
physical slice B = 0; that A carries the executed readout; per-factor exact
symplecticity with an explicit factor-wise inverse; exact conservation of B
under active coupling; the measured rank and kernel of the readout map; and the
Cycle-700 mutation family carried through the dilation.

The harness is import-safe: it imports the landed sibling runners and executes
their machinery, and emits a bounded transcript only when invoked.
"""

from __future__ import annotations

from hashlib import sha256
import importlib.util
import json
from pathlib import Path
import sys
from time import perf_counter

import numpy as np
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import splu


SEED = 20260801
L_DYN = 9
L_STRUCT = 3
T_STRUCT = 1.0
STRUCT_SITES = ((1, 1, 1), (2, 1, 1))
CHECKPOINT_HOLD_STEP = 500
ACTIVE_B = (1e-3, 0.0, 0.0, 0.0)

# Landed Cycle-700 anchors, at the precision they were landed at.
HOLD_PINS = (
    -4.209568736178572,
    -4.150939492487698,
    -4.121308954024253,
    -4.1145788661621125,
)
R_STATIC19 = -3.9169789686578382
R_PRED_SPLIT = -3.9132331854898643
STATIC_RESIDUAL = 0.003745783167973915
R_MUT = -4.0411929130059585
RANGE_SEP = 0.12421394434812028
RANGE_RATIO = 33.161007665936864

_OUT: list[str] = []
_PASS = 0
_FAIL = 0


def emit(line: str) -> None:
    _OUT.append(line)


def sig6(x) -> float:
    """Display rounding for machine-round-off diagnostics.

    Applied uniformly to every dimensionless defect, residual, and round-trip
    error reported below, and never to a physical magnitude, a landed anchor,
    or a singular value. Six significant digits far exceeds the meaningful
    content of a quantity whose size is set by double-precision round-off. The
    gates themselves always compare the unrounded value; only the transcript
    and the summary carry the rounded one.
    """
    return float(format(float(x), ".6e"))


def check(label: str, ok: bool, detail: object = "") -> bool:
    global _PASS, _FAIL
    if len(label) > 34 or not all(c.islower() or c.isdigit() or c == "_" for c in label):
        raise ValueError("invalid check label: " + label)
    if ok:
        _PASS += 1
        emit("PASS " + label)
    else:
        _FAIL += 1
        emit("FAIL " + label + " :: " + str(detail))
    return ok


def load_module(root: Path, alias: str, relative: str):
    spec = importlib.util.spec_from_file_location(alias, root / relative)
    if spec is None or spec.loader is None:
        raise ImportError(relative)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ROOT = Path(__file__).resolve().parents[1]
c700 = load_module(
    ROOT, "cycle704_c700",
    "scripts/physical_operational_source_response_readout_chain_cycle700_2026_07_25.py",
)
c696 = load_module(
    ROOT, "cycle704_c696",
    "scripts/physical_open_coframe_k_endpoint_compiler_cycle696_2026_07_25.py",
)

DT = c700.DT
Q_COUPLING = c700.Q_COUPLING
N_HOLD = int(round(c700.HOLD_T / DT))


def flat_index(x, L: int) -> int:
    """Flat index convention of the Cycle-700 detector readout."""
    return (x[0] * L + x[1]) * L + x[2]


def aug_run_dynamics(lap, rho, T, L, sites=None, phi0=None, pi0=None, B0=None,
                     checkpoint_hold_step=None):
    """Augmented leapfrog on (phi, A; pi, B).

    Lines 1-3 of the step body are the Cycle-700 `run_dynamics` step verbatim.
    Line 4 adds one record-coupling shear per hold step: the time-1 flow of
    H_c = B . (P phi), whose two legs are

        pi[det] -= B      (dpi/dt = -dH_c/dphi = -P^T B, back-reaction)
        A       += phi    (dA/dt  =  dH_c/dB   =  P phi, record)

    with dphi/dt = dH_c/dpi = 0 and dB/dt = -dH_c/dA = 0. Because phi and B are
    both constant along that flow, the time-1 map is exactly the two lines
    above; they read and write disjoint variables, so their order is immaterial
    and the composition is one exact symplectic shear. On the physical slice
    B = 0 the back-reaction leg subtracts +0.0 and preserves every float bit.
    """
    n_ramp = int(round(T / DT))
    n_hold = N_HOLD
    n_total = n_ramp + n_hold
    sites = c700.detector_sites(L) if sites is None else sites
    det = [flat_index(s, L) for s in sites]
    k = len(det)
    phi = np.zeros_like(rho) if phi0 is None else phi0.copy()
    pi = np.zeros_like(rho) if pi0 is None else pi0.copy()
    A = np.zeros(k)
    A2 = np.zeros(k)
    A_ck = None
    B = np.zeros(k) if B0 is None else np.asarray(B0, dtype=float).copy()
    history = []
    hold = []
    hold_seen = 0

    def g(step):
        u = min(1.0, max(0.0, step / n_ramp))
        return 4.0 * u ** 3 - 3.0 * u ** 4

    for step in range(n_total):
        g0, g1 = g(step), g(step + 1)
        pi -= 0.5 * DT * (lap @ phi + Q_COUPLING * g0 * rho)
        phi += DT * pi
        pi -= 0.5 * DT * (lap @ phi + Q_COUPLING * g1 * rho)
        history.append((g0, g1))
        if step + 1 > n_ramp:
            hold.append(phi.copy())
            pi[det] -= B
            A += phi[det]
            hold_seen += 1
            if checkpoint_hold_step is not None:
                if hold_seen == checkpoint_hold_step:
                    A_ck = A.copy()
                elif hold_seen > checkpoint_hold_step:
                    A2 += phi[det]
    phibar = np.mean(hold, axis=0) if hold else np.zeros_like(phi)
    return phi, pi, phibar, history, A, B, A_ck, A2


def aug_inverse_dynamics(lap, rho, L, phi, pi, A, B, history, sites=None):
    """Explicit algebraic inverse of `aug_run_dynamics`, factor by factor.

    Not the Cycle-700 momentum-flip reversal: every shear of the augmented map
    is un-applied in reverse order by its own algebraic inverse.
    """
    sites = c700.detector_sites(L) if sites is None else sites
    det = [flat_index(s, L) for s in sites]
    phi = phi.copy()
    pi = pi.copy()
    A = A.copy()
    B = B.copy()
    n_total = len(history)
    n_ramp = n_total - N_HOLD
    for step in range(n_total - 1, -1, -1):
        g0, g1 = history[step]
        if step + 1 > n_ramp:
            A -= phi[det]
            pi[det] += B
        pi += 0.5 * DT * (lap @ phi + Q_COUPLING * g1 * rho)
        phi -= DT * pi
        pi += 0.5 * DT * (lap @ phi + Q_COUPLING * g0 * rho)
    return phi, pi, A, B


def adjoint_readout_row(Km, det, j, n_ramp, n_total, drop_last=False):
    """Row j of the linear readout map R for the source-free channel.

    With rho = 0 the step map F is the constant linear map F = K2 D K1, where
    the kick K sends (q, p) -> (q, p - Km q) and the drift D sends
    (q, p) -> (q + DT p, p). Km is symmetric, so

        K^T : (q, p) -> (q - Km p, p),      D^T : (q, p) -> (q, p + DT q),

    and F^T = K1^T D^T K2^T is applied in that order. The register satisfies
    A_j = sum_t chi(t) c_j^T F^t x0 with chi(t) = 1 exactly on the hold window
    t > n_ramp and c_j = (P^T e_j, 0), so row j of R is the Horner recursion
    v <- F^T (v + chi(t) c_j) run from t = n_total down to t = 1.
    """
    n = Km.shape[0]
    vq = np.zeros(n)
    vp = np.zeros(n)
    for t in range(n_total, 0, -1):
        held = t > n_ramp and not (drop_last and t == n_total)
        if held:
            vq[det[j]] += 1.0
        vq -= Km @ vp
        vp += DT * vq
        vq -= Km @ vp
    return np.concatenate([vq, vp])


def build_struct_factors(lap3, det3, N3, k3):
    """Explicit dense shear factors of the augmented flow at L = L_STRUCT.

    Coordinates are ordered z = (q, p) with q = (phi, A) and p = (pi, B), so
    J = [[0, I], [-I, 0]] on R^(2m), m = N3 + k3. Each factor is the time-1
    flow of a quadratic Hamiltonian (1/2) z^T H z with (J H)^2 = 0, hence
    S = I + J H exactly; and S^T J S - J = (J H)^T J + J (J H) + (J H)^T J (J H)
    = H^T - H + H J H vanishes identically once H is symmetric and J H is
    nilpotent. Both are gated exactly below, so a wrong transpose in any leg
    is detected rather than absorbed.
    """
    m = N3 + k3
    dim = 2 * m
    J = np.zeros((dim, dim))
    J[:m, m:] = np.eye(m)
    J[m:, :m] = -np.eye(m)
    P = np.zeros((k3, N3))
    for j, i in enumerate(det3):
        P[j, i] = 1.0
    Km = 0.5 * DT * lap3.toarray()

    H_kick = np.zeros((dim, dim))
    H_kick[:N3, :N3] = Km
    H_drift = np.zeros((dim, dim))
    H_drift[m:m + N3, m:m + N3] = DT * np.eye(N3)
    H_rec = np.zeros((dim, dim))
    H_rec[:N3, m + N3:] = P.T
    H_rec[m + N3:, :N3] = P
    return J, Km, {"kick": H_kick, "drift": H_drift, "rec": H_rec}, dim, m


def main() -> int:
    global _PASS, _FAIL
    _OUT.clear()
    _PASS = 0
    _FAIL = 0
    started = perf_counter()

    lap9, _ = c700.build_laplacian(L_DYN)
    q9 = c700.frozen_source(L_DYN, c696.SRC_SCALE)
    zeros9 = np.zeros_like(q9)
    N = L_DYN ** 3
    sites9 = c700.detector_sites(L_DYN)
    det9 = [flat_index(s, L_DYN) for s in sites9]
    k = len(det9)

    # ============================================================ A: anchors
    emit("== A LANDED ANCHORS ==")
    plain = {}
    for T, pin in zip(c700.T_LADDER, HOLD_PINS):
        plain[T] = c700.run_dynamics(lap9, q9, T)
        got = c700.detector_ratio(plain[T][2], L_DYN)
        check("a1_hold_t" + str(int(T)), abs(got - pin) <= c700.MACHINE_TOL,
              (got, pin))
    emit("REPORT a1_hold=" + ",".join(repr(c700.detector_ratio(plain[T][2], L_DYN))
                                      for T in c700.T_LADDER))
    fphi, fpi, _, hist160 = plain[c700.T_LADDER[-1]]
    rphi, rpi = c700.reverse_dynamics(lap9, q9, fphi, fpi, hist160)
    rev_err = max(float(np.max(np.abs(rphi))), float(np.max(np.abs(rpi))))
    check("a2_c700_exact_reversal", rev_err < c700.REVERSIBILITY_TOL, rev_err)
    emit("REPORT a2_reversal=" + repr(sig6(rev_err)))

    lap19, face19 = c700.build_laplacian(19, face_mutation=True)
    q19 = c700.frozen_source(19, c696.SRC_SCALE)
    r_static19 = c700.detector_ratio(splu(lap19).solve(q19), 19)
    mut19 = lap19 + c700.FACE_MUTATION_WEIGHT * face19
    r_mut = c700.detector_ratio(splu(csc_matrix(mut19)).solve(q19), 19)
    staticerr = abs(r_static19 - R_PRED_SPLIT)
    range_sep = abs(r_mut - r_static19)
    range_ratio = range_sep / staticerr
    check("a3_static19_pin", abs(r_static19 - R_STATIC19) <= 1e-12, r_static19)
    check("a3_static_residual_pin", abs(staticerr - STATIC_RESIDUAL) <= 1e-12,
          staticerr)
    check("a3_mutated_ratio_pin", abs(r_mut - R_MUT) <= 1e-9, r_mut)
    check("a3_range_separation_pin", abs(range_sep - RANGE_SEP) <= 1e-9, range_sep)
    check("a3_range_ratio_pin",
          abs(range_ratio - RANGE_RATIO) <= 1e-6 * RANGE_RATIO, range_ratio)
    emit("REPORT a3_static=" + repr(r_static19) + " res=" + repr(staticerr))
    emit("REPORT a3_mut=" + repr(r_mut) + " sep=" + repr(range_sep))
    emit("REPORT a3_range_ratio=" + repr(range_ratio))

    # ================================================ B: the channel carried
    emit("== B DILATION CARRIES THE CHANNEL ==")
    aug160 = aug_run_dynamics(lap9, q9, c700.T_LADDER[-1], L_DYN,
                              checkpoint_hold_step=CHECKPOINT_HOLD_STEP)
    check("b1_phi_bit_identity", np.array_equal(aug160[0], fphi))
    check("b2_pi_bit_identity", np.array_equal(aug160[1], fpi))
    check("b3_phibar_bit_identity",
          np.array_equal(aug160[2], plain[c700.T_LADDER[-1]][2]))
    A_pos = aug160[4]
    hold_mean = aug160[2][det9]
    b4 = float(np.max(np.abs(A_pos / N_HOLD - hold_mean) / np.abs(hold_mean)))
    check("b4_register_carries_holdmean", b4 <= 1e-12, b4)
    ratio_A = float((A_pos[0] - A_pos[1]) / (A_pos[2] - A_pos[3]))
    ratio_bar = c700.detector_ratio(aug160[2], L_DYN)
    b4b = abs(ratio_A - ratio_bar) / abs(ratio_bar)
    check("b4b_register_ratio_matches", b4b <= 1e-11, b4b)
    b4c = abs(ratio_A - HOLD_PINS[-1])
    check("b4b_register_ratio_landed", b4c <= 1e-9, b4c)
    emit("REPORT b4_relerr=" + repr(sig6(b4)) + " ratio=" + repr(ratio_A))
    emit("REPORT b4b_rel=" + repr(sig6(b4b)) + " abs=" + repr(sig6(b4c)))

    augB = aug_run_dynamics(lap9, q9, c700.T_LADDER[0], L_DYN, B0=ACTIVE_B)
    b5 = float(np.max(np.abs(augB[5] - np.asarray(ACTIVE_B))))
    check("b5_conserved_active_coupling", b5 == 0.0, b5)
    b6 = float(np.max(np.abs((aug160[6] + aug160[7]) - A_pos))
               / np.max(np.abs(A_pos)))
    check("b6_window_additivity", b6 <= 1e-12, b6)
    emit("REPORT b5_bdrift=" + repr(sig6(b5)) + " b6_add=" + repr(sig6(b6)))

    # ========================================= C: inverse and symplecticity
    emit("== C INVERSE AND SYMPLECTICITY ==")
    iphi, ipi, iA, iB = aug_inverse_dynamics(lap9, q9, L_DYN, aug160[0],
                                             aug160[1], A_pos, aug160[5],
                                             aug160[3])
    c1 = max(float(np.max(np.abs(iphi))), float(np.max(np.abs(ipi))))
    check("c1_augmented_inverse", c1 < c700.REVERSIBILITY_TOL, c1)
    c2 = float(np.max(np.abs(iA)))
    check("c2_unregistration", c2 <= 1e-9, c2)
    check("c2b_back_momentum_zero",
          float(np.max(np.abs(iB))) == 0.0 and float(np.max(np.abs(aug160[5]))) == 0.0)
    emit("REPORT c1_back=" + repr(sig6(c1)) + " c2_aback=" + repr(sig6(c2)))

    lap3, _ = c700.build_laplacian(L_STRUCT)
    rho3 = c700.dipole_source(L_STRUCT)
    N3 = L_STRUCT ** 3
    k3 = len(STRUCT_SITES)
    det3 = [flat_index(s, L_STRUCT) for s in STRUCT_SITES]
    J, Km3, Hs, dim, m = build_struct_factors(lap3, det3, N3, k3)
    check("c3a_kick_matrix_symmetry", float(np.max(np.abs(Km3 - Km3.T))) == 0.0)
    S = {}
    Sinv = {}
    sym_def, nil_def, num_def, inv_def = 0.0, 0.0, 0.0, 0.0
    for name, H in Hs.items():
        JH = J @ H
        sym_def = max(sym_def, float(np.max(np.abs(H - H.T))))
        nil_def = max(nil_def, float(np.max(np.abs(JH @ JH))))
        S[name] = np.eye(dim) + JH
        Sinv[name] = np.eye(dim) - JH
        num_def = max(num_def, float(np.max(np.abs(S[name].T @ J @ S[name] - J))))
        inv_def = max(inv_def,
                      float(np.max(np.abs(S[name] @ Sinv[name] - np.eye(dim)))))
    check("c3b_factor_generator_symmetry", sym_def == 0.0, sym_def)
    check("c3c_factor_generator_nilpotent", nil_def == 0.0, nil_def)
    check("c3d_factor_numeric_defect", num_def <= 1e-13, num_def)
    check("c3e_factor_inverse_exact", inv_def == 0.0, inv_def)
    emit("REPORT c3_sym=" + repr(sig6(sym_def)) + " nil=" + repr(sig6(nil_def))
         + " num=" + repr(sig6(num_def)) + " inv=" + repr(sig6(inv_def)))

    n_ramp3 = int(round(T_STRUCT / DT))
    n_total3 = n_ramp3 + N_HOLD

    def g3(step):
        u = min(1.0, max(0.0, step / n_ramp3))
        return 4.0 * u ** 3 - 3.0 * u ** 4

    S_total = np.eye(dim)
    c_total = np.zeros(dim)
    S_total_inv = np.eye(dim)
    for step in range(n_total3):
        for leg, gv in (("kick", g3(step)), ("drift", None),
                        ("kick", g3(step + 1))):
            S_total = S[leg] @ S_total
            c_total = S[leg] @ c_total
            if gv is not None:
                c_total[m:m + N3] -= 0.5 * DT * Q_COUPLING * gv * rho3
            S_total_inv = S_total_inv @ Sinv[leg]
        if step + 1 > n_ramp3:
            S_total = S["rec"] @ S_total
            c_total = S["rec"] @ c_total
            S_total_inv = S_total_inv @ Sinv["rec"]

    defect_raw = float(np.max(np.abs(S_total.T @ J @ S_total - J)))
    prodnorm = 1.0 + float(np.linalg.norm(S_total, 1)) * float(
        np.linalg.norm(S_total, np.inf))
    defect_rel = defect_raw / prodnorm
    check("c4a_composed_defect_norm", defect_rel <= 1e-12, defect_rel)
    check("c4a_composed_defect_raw", defect_raw <= 1e-9, defect_raw)
    sign, logdet = np.linalg.slogdet(S_total)
    check("c4b_unit_determinant", sign == 1.0 and abs(logdet) <= 1e-8,
          (sign, logdet))
    emit("REPORT c4_defect_raw=" + repr(sig6(defect_raw))
         + " prodnorm=" + format(prodnorm, ".6e"))
    emit("REPORT c4_logdet=" + repr(sig6(logdet)) + " sign=" + repr(float(sign)))

    rng = np.random.default_rng(SEED)
    phi3 = rng.standard_normal(N3)
    pi3 = rng.standard_normal(N3)
    B3 = rng.standard_normal(k3)
    x3 = np.concatenate([phi3, np.zeros(k3), pi3, B3])
    out3 = aug_run_dynamics(lap3, rho3, T_STRUCT, L_STRUCT, sites=STRUCT_SITES,
                            phi0=phi3, pi0=pi3, B0=B3)
    x3_end = np.concatenate([out3[0], out3[4], out3[1], out3[5]])
    c4c = float(np.linalg.norm(S_total @ x3 + c_total - x3_end)
                / np.linalg.norm(x3_end))
    check("c4c_matrix_matches_integrator", c4c <= 1e-12, c4c)
    emit("REPORT c4c_relerr=" + repr(sig6(c4c)))

    inv_raw = float(np.max(np.abs(S_total @ S_total_inv - np.eye(dim))))
    inv_rel = inv_raw / prodnorm
    check("c5a_factorwise_inverse", inv_rel <= 1e-11, inv_rel)
    xr = rng.standard_normal(dim)
    yr = S_total @ xr + c_total
    c5b = float(np.linalg.norm(S_total_inv @ (yr - c_total) - xr)
                / np.linalg.norm(xr))
    check("c5b_affine_round_trip", c5b <= 1e-12, c5b)
    emit("REPORT c5_inv_raw=" + repr(sig6(inv_raw)) + " trip=" + repr(sig6(c5b)))

    # ================================================== D: openness measured
    emit("== D OPENNESS MEASURED ==")
    T_OPEN = c700.T_LADDER[0]
    n_ramp_open = int(round(T_OPEN / DT))
    n_total_open = n_ramp_open + N_HOLD
    Km9 = (0.5 * DT) * lap9
    R = np.array([adjoint_readout_row(Km9, det9, j, n_ramp_open, n_total_open)
                  for j in range(k)])
    rng = np.random.default_rng(SEED)
    d1 = 0.0
    for _ in range(3):
        p0 = rng.standard_normal(N)
        v0 = rng.standard_normal(N)
        got = aug_run_dynamics(lap9, zeros9, T_OPEN, L_DYN, phi0=p0, pi0=v0)[4]
        want = R @ np.concatenate([p0, v0])
        d1 = max(d1, float(np.max(np.abs(got - want) / np.abs(want))))
    check("d1_adjoint_matches_forward", d1 <= 1e-10, d1)

    p0 = rng.standard_normal(N)
    v0 = rng.standard_normal(N)
    A_src_x = aug_run_dynamics(lap9, q9, T_OPEN, L_DYN, phi0=p0, pi0=v0)[4]
    aug_src20 = aug_run_dynamics(lap9, q9, T_OPEN, L_DYN)
    A_src_0 = aug_src20[4]
    want = R @ np.concatenate([p0, v0])
    d2 = float(np.max(np.abs((A_src_x - A_src_0) - want) / np.abs(want)))
    check("d2_affine_readout_map", d2 <= 1e-10, d2)
    emit("REPORT d1_rel=" + repr(sig6(d1)) + " d2_rel=" + repr(sig6(d2)))

    sv = np.linalg.svd(R, compute_uv=False)
    s_max, s_min = float(sv[0]), float(sv[-1])
    check("d3_readout_rank_four", s_min >= 1e-8 * s_max, (s_min, s_max))
    emit("REPORT d3_sv=" + ",".join(repr(float(v)) for v in sv))
    emit("REPORT d3_kernel_dim=" + str(2 * N - k))

    xrand = rng.standard_normal(2 * N)
    coef, _r, _rk, _s = np.linalg.lstsq(R.T, xrand, rcond=None)
    x_ker = xrand - R.T @ coef
    x_ker = x_ker / np.linalg.norm(x_ker)
    ker_run = aug_run_dynamics(lap9, zeros9, T_OPEN, L_DYN,
                               phi0=x_ker[:N], pi0=x_ker[N:])
    ratio_silent = float(np.linalg.norm(ker_run[4]) / N_HOLD
                         / (s_max * np.linalg.norm(x_ker)))
    check("d4_kernel_silence", ratio_silent <= 1e-10, ratio_silent)
    env_ker = float(np.linalg.norm(np.concatenate([ker_run[0], ker_run[1]])))
    check("d4b_environment_survives",
          env_ker >= 1e-2 * float(np.linalg.norm(x_ker)), env_ker)

    yv = rng.standard_normal(k)
    x_row = R.T @ yv
    x_row = x_row / np.linalg.norm(x_row)
    row_run = aug_run_dynamics(lap9, zeros9, T_OPEN, L_DYN,
                               phi0=x_row[:N], pi0=x_row[N:])
    ratio_loud = float(np.linalg.norm(row_run[4]) / N_HOLD
                       / (s_max * np.linalg.norm(x_row)))
    check("d5_row_space_loudness", ratio_loud / ratio_silent >= 1e4,
          (ratio_loud, ratio_silent))
    emit("REPORT d4_silent=" + repr(sig6(ratio_silent)) + " env=" + repr(env_ker))
    emit("REPORT d5_loud=" + repr(ratio_loud)
         + " contrast=" + format(ratio_loud / ratio_silent, ".6e"))

    x_a = rng.standard_normal(2 * N)
    scale_ab = float(np.linalg.norm(x_a) / np.linalg.norm(x_ker))
    x_b = x_a + scale_ab * x_ker
    run_a = aug_run_dynamics(lap9, zeros9, T_OPEN, L_DYN,
                             phi0=x_a[:N], pi0=x_a[N:])
    run_b = aug_run_dynamics(lap9, zeros9, T_OPEN, L_DYN,
                             phi0=x_b[:N], pi0=x_b[N:])
    d6 = float(np.linalg.norm(run_a[4] - run_b[4])
               / (N_HOLD * s_max * np.linalg.norm(x_a)))
    check("d6_same_record_witness", d6 <= 1e-10, d6)
    env_gap = float(np.linalg.norm(np.concatenate([run_a[0] - run_b[0],
                                                   run_a[1] - run_b[1]]))
                    / np.linalg.norm(x_a))
    check("d6b_environments_differ", env_gap >= 1e-2, env_gap)
    emit("REPORT d6_record=" + repr(sig6(d6)) + " env_gap=" + repr(env_gap))

    # ============================================ E: mutations through the dilation
    emit("== E MUTATIONS THROUGH THE DILATION ==")
    aug_del = aug_run_dynamics(lap9, zeros9, c700.T_LADDER[-1], L_DYN)
    check("e1_deletion_exact_zero",
          np.array_equal(aug_del[2], np.zeros(N))
          and np.array_equal(aug_del[4], np.zeros(k)))
    del_ratio = float(np.linalg.norm(aug_del[2])
                      / max(np.linalg.norm(aug160[2]), 1e-300))
    check("e1b_deletion_null_ratio", del_ratio < c700.SIGNAL_NULL, del_ratio)

    aug_sign = aug_run_dynamics(lap9, -q9, c700.T_LADDER[-1], L_DYN)
    A_neg = aug_sign[4]
    check("e2_sign_bit_exact_oddness", np.array_equal(A_neg, -A_pos))
    ratio_neg = float((A_neg[0] - A_neg[1]) / (A_neg[2] - A_neg[3]))
    check("e2b_sign_ratio_blind", abs(ratio_neg - ratio_A) <= 1e-12,
          (ratio_neg, ratio_A))
    d_sum = abs((A_pos[0] - A_pos[1]) + (A_neg[0] - A_neg[1]))
    check("e2c_sign_difference_registers",
          d_sum <= 1e-12 * abs(A_pos[0] - A_pos[1]), d_sum)
    emit("REPORT e1_delratio=" + repr(sig6(del_ratio)) + " e2_dsum=" + repr(sig6(d_sum)))

    A_1x = aug_src20[4]
    A_2x = aug_run_dynamics(lap9, 2.0 * q9, T_OPEN, L_DYN)[4]
    A_hx = aug_run_dynamics(lap9, 0.5 * q9, T_OPEN, L_DYN)[4]
    check("e3_scale_double_exact", np.array_equal(A_2x, 2.0 * A_1x))
    check("e3b_scale_half_exact", np.array_equal(A_hx, 0.5 * A_1x))
    e4 = abs(float((A_pos[2] - A_pos[3]) / (A_pos[0] - A_pos[1])) - 1.0 / ratio_A)
    check("e4_register_swap_inverse", e4 <= 1e-12, e4)
    emit("REPORT e4_swap=" + repr(sig6(e4)))

    # ============================================= F: wrong-value rejectors
    emit("== F REJECTORS ==")
    aug_plain20 = aug_src20
    shift1 = augB[2] - aug_plain20[2]
    f1 = float(np.max(np.abs(shift1)))
    check("f1_back_reaction_detected", f1 >= 1e-6, f1)
    aug2B = aug_run_dynamics(lap9, q9, T_OPEN, L_DYN,
                             B0=tuple(2.0 * v for v in ACTIVE_B))
    shift2 = aug2B[2] - aug_plain20[2]
    f2 = float(np.linalg.norm(shift2 - 2.0 * shift1) / np.linalg.norm(shift1))
    check("f2_back_reaction_linear", f2 <= 1e-9, f2)
    check("f3_bit_identity_discriminates",
          not np.array_equal(augB[0], aug_plain20[0]))
    R_trunc = np.array([adjoint_readout_row(Km9, det9, j, n_ramp_open,
                                            n_total_open, drop_last=True)
                        for j in range(k)])
    f4 = float(np.max(np.abs(R_trunc - R)) / np.max(np.abs(R)))
    check("f4_adjoint_window_rejector", f4 >= 1e-4, f4)
    emit("REPORT f1_shift=" + repr(f1) + " f2_lin=" + repr(sig6(f2)))
    emit("REPORT f4_window=" + repr(f4))

    # ============================================================ G: receipt
    emit("== G RECEIPT ==")
    runner_sha = sha256(Path(__file__).read_bytes()).hexdigest()
    summary = {
        "cycle": 704,
        "pass": None,
        "fail": None,
        "A": {"hold": [c700.detector_ratio(plain[T][2], L_DYN)
                       for T in c700.T_LADDER],
              "reversal": sig6(rev_err), "R_static19": r_static19, "R_mut": r_mut,
              "staticerr": staticerr, "range_sep": range_sep,
              "range_ratio": range_ratio},
        "B": {"bit_phi": True, "bit_pi": True, "bit_phibar": True,
              "b4": sig6(b4), "ratio_A": ratio_A, "b5": sig6(b5), "b6": sig6(b6)},
        "C": {"c1": sig6(c1), "c2": sig6(c2), "defect_raw": sig6(defect_raw),
              "logdet": sig6(logdet), "c4c": sig6(c4c),
              "inv_raw": sig6(inv_raw), "trip": sig6(c5b), "dim": dim},
        "D": {"d1": sig6(d1), "d2": sig6(d2), "sv": [float(v) for v in sv],
              "kernel_dim": 2 * N - k, "silent": sig6(ratio_silent),
              "loud": ratio_loud, "d6": sig6(d6), "env_gap": env_gap},
        "E": {"del": sig6(del_ratio), "swap": sig6(e4)},
        "F": {"f1": f1, "f2": sig6(f2), "f4": f4},
    }
    check("g1_receipt_fields",
          len(runner_sha) == 64 and all(ch in "0123456789abcdef" for ch in runner_sha))

    prospective = _PASS + 1
    summary["pass"] = prospective
    summary["fail"] = _FAIL
    summary_line = "SUMMARY_JSON " + json.dumps(summary, sort_keys=True,
                                                separators=(",", ":"))
    total_line = "TOTAL: PASS=" + str(prospective) + " FAIL=" + str(_FAIL)
    reserved = (len("PASS stdout_under_6000") + 1 + len(summary_line) + 1
                + len(total_line) + 1)
    n_stdout = sum(len(s) + 1 for s in _OUT) + reserved
    check("stdout_under_6000", n_stdout < 6000, n_stdout)
    summary["pass"] = _PASS
    summary["fail"] = _FAIL
    summary_line = "SUMMARY_JSON " + json.dumps(summary, sort_keys=True,
                                                separators=(",", ":"))
    total_line = "TOTAL: PASS=" + str(_PASS) + " FAIL=" + str(_FAIL)
    _OUT.append(summary_line)
    _OUT.append(total_line)
    sys.stdout.write("\n".join(_OUT) + "\n")

    # Cold-run receipt, written after stdout so it cannot disturb the byte
    # budget above, and suppressed by --no-receipt exactly as the Cycle-700
    # sibling does. Elapsed time is carried here only, so stdout stays
    # deterministic across runs.
    receipt_body = dict(summary)
    receipt_body["resources"] = {"elapsed_seconds": perf_counter() - started}
    receipt_body["runner_sha256"] = runner_sha
    receipt_body["pass_count"] = _PASS
    receipt_body["fail_count"] = _FAIL
    receipt_body["pass"] = _FAIL == 0
    if "--no-receipt" not in sys.argv:
        receipt = ROOT / "outputs" / (
            "physical_record_register_symplectic_dilation_cycle704"
            "_receipt_2026-08-01.json"
        )
        receipt.parent.mkdir(parents=True, exist_ok=True)
        receipt.write_text(
            json.dumps(receipt_body, indent=1, sort_keys=True, default=str) + "\n",
            encoding="utf-8",
        )
    return 0 if _FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
