#!/usr/bin/env python3
"""D4 per-direction algebra-dimension pattern dichotomy on the two-flux-class surface.

Deterministic (seeded), numpy only, no network, no cache writes.

This runner upgrades the D4 leg of
scripts/realized_kinetic_branch_discriminators_2026_07_02.py from a
representative-level dimension read to a class-level pattern statement: for
Hermitian nearest-neighbor symbols on the one-site C^2 carrier that are
covariant under the proper cubic rotations, the per-direction unital
star-algebra dimension is CONSTANT across the three directions, and on the
surface's one-coefficient-per-direction representatives it lies in {1, 2},
realizing exactly the patterns [1,1,1] (K0 class) and [2,2,2] (K1 class).
Two hypotheses are shown load-bearing: off-surface Hermitian symbols reach
dimension 4, and non-covariant symbols realize direction-mixed patterns.

The K1 coefficient family is COMPUTED from the parent construction
(translation-cell blocking of the eta0 phase system) exactly as the
discriminator runner extracts it -- never hard-coded Paulis.

Exit code 0 iff FAIL == 0.
"""

from __future__ import annotations

import itertools
import math
import sys

import numpy as np


PASS = 0
FAIL = 0
COUNT = 0

RNG = np.random.default_rng(20260703)


def check(tag: str, desc: str, ok: bool, extra: str = "") -> bool:
    global PASS, FAIL, COUNT
    COUNT += 1
    ok = bool(ok)
    if ok:
        PASS += 1
    else:
        FAIL += 1
    line = f"[{'PASS' if ok else 'FAIL'}] [{tag}] {COUNT:2d}. {desc}"
    if extra:
        line += f"  |  {extra}"
    print(line)
    return ok


I2 = np.eye(2, dtype=complex)
S1 = np.array([[0, 1], [1, 0]], dtype=complex)
S2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
S3 = np.array([[1, 0], [0, -1]], dtype=complex)
SIG = [S1, S2, S3]
E_UNIT = [np.array(v, dtype=int) for v in ((1, 0, 0), (0, 1, 0), (0, 0, 1))]
CELL = list(itertools.product((0, 1), repeat=3))
CELL_INDEX = {r: i for i, r in enumerate(CELL)}


# --------------------------------------------------------------------------
# Core machinery: unital *-algebra dimension by span-closure + SVD rank.
# No scalar/nonscalar if/else shortcut anywhere.
# --------------------------------------------------------------------------

def vectorize(M):
    return np.asarray(M, dtype=complex).reshape(-1, order="F")


def rank_complex(A, tol=1e-10):
    if A.size == 0:
        return 0
    s = np.linalg.svd(A, compute_uv=False)
    return int(np.sum(s > tol))


def alg_dim(gens, tol=1e-10):
    """Dimension of the unital *-subalgebra of M_n(C) generated by gens.

    Start from [I] + gens + adjoints, close under pairwise products to a
    fixed point (dimension can only grow, capped at n*n), take numerical
    rank of the flattened span via SVD at tol.  Real machinery: the rank is
    computed from actual singular values, never from an if/else on whether a
    generator is scalar.
    """
    n = gens[0].shape[0]
    basis = [np.eye(n, dtype=complex)]
    candidates = list(gens) + [G.conj().T for G in gens]

    def current_rank(items):
        return rank_complex(np.column_stack([vectorize(B) for B in items]), tol)

    changed = True
    while changed:
        changed = False
        for C in list(candidates):
            trial = basis + [C]
            if current_rank(trial) > current_rank(basis):
                basis.append(C)
                changed = True
        products = []
        for A in basis:
            for B in basis:
                products.append(A @ B)
        candidates = products + [P.conj().T for P in products]
    return current_rank(basis)


def rand_hermitian(rng):
    A = rng.standard_normal((2, 2)) + 1j * rng.standard_normal((2, 2))
    return (A + A.conj().T) / 2.0


def rand_unitary(rng):
    A = rng.standard_normal((2, 2)) + 1j * rng.standard_normal((2, 2))
    Q, R = np.linalg.qr(A)
    ph = np.diag(R) / np.abs(np.diag(R))
    return Q * ph.conj()


# --------------------------------------------------------------------------
# Parent construction: eta0 phases, absorbing frame, K1 Gamma extraction.
# Mirrors scripts/realized_kinetic_branch_discriminators_2026_07_02.py.
# --------------------------------------------------------------------------

def eta0(x, mu):
    """Kawamoto-Smit signs, matching the parent kinetic-class runner."""
    if mu == 0:
        return 1.0
    if mu == 1:
        return (-1.0) ** (x[0] % 2)
    return (-1.0) ** ((x[0] + x[1]) % 2)


def Tmat(x):
    out = I2.copy()
    for mu, power in enumerate(x):
        if power % 2:
            out = out @ SIG[mu]
    return out


def absorbed_k1_edge_coefficients(tfun=eta0):
    """Direction matrices from eta and the parent absorbing frame.

    The identity T(x)^dag sigma_mu T(x+mu) = eta_mu(x) I implies
    sigma_mu = eta_mu(x) T(x) T(x+mu)^dag.  Average only after computing
    these edge matrices from the phase system.
    """
    coeffs = []
    spreads = []
    for mu in range(3):
        mats = []
        for x in CELL:
            y = tuple(np.array(x) + E_UNIT[mu])
            mats.append(complex(tfun(x, mu)) * Tmat(x) @ Tmat(y).conj().T)
        avg = sum(mats) / len(mats)
        coeffs.append(avg)
        spreads.append(max(np.linalg.norm(M - avg) for M in mats))
    return coeffs, spreads


def k1_raw_extraction_symbol(p, edge_coeffs):
    M = np.zeros((2, 2), dtype=complex)
    for mu in range(3):
        M += 1j * edge_coeffs[mu] * math.sin(float(p[mu]))
    return M


def extract_k1_gammas(edge_coeffs):
    gammas = []
    q = math.pi / 2.0
    for mu in range(3):
        p_plus = np.zeros(3)
        p_minus = np.zeros(3)
        p_plus[mu] = q
        p_minus[mu] = -q
        raw_plus = k1_raw_extraction_symbol(p_plus, edge_coeffs)
        raw_minus = k1_raw_extraction_symbol(p_minus, edge_coeffs)
        gammas.append((raw_plus - raw_minus) / (2j))
    return gammas


def blocked_symbol_8(p, phases):
    """Translation-cell (2^3) blocked nearest-neighbor symbol from per-link
    phases, mirroring the discriminator runner's T8 pipeline."""
    M = np.zeros((8, 8), dtype=complex)
    for r in CELL:
        for mu in range(3):
            y = list(r)
            y[mu] += 1
            block_shift = np.zeros(3)
            if y[mu] >= 2:
                y[mu] -= 2
                block_shift[mu] = 1.0
            y = tuple(y)
            phase = complex(phases[(r, mu)])
            z = np.exp(1j * float(np.dot(p, block_shift)))
            i = CELL_INDEX[y]
            j = CELL_INDEX[r]
            M[i, j] += phase * z
            M[j, i] += np.conj(phase) * np.conj(z)
    return M


def blocked_derivative_gammas_8(phases):
    """First-order (sin) coefficient family of the blocked symbol, extracted by
    a momentum derivative at p0 = pi*(1,1,1), as the discriminator runner does."""
    p0 = math.pi * np.ones(3)
    dq = 1e-5
    out = []
    for mu in range(3):
        e = np.zeros(3)
        e[mu] = dq
        out.append(
            (blocked_symbol_8(p0 + e, phases) - blocked_symbol_8(p0 - e, phases))
            / (2.0 * dq)
        )
    return out


def eta0_cell_phases():
    return {(r, mu): eta0(r, mu) for r in CELL for mu in range(3)}


def perturbed_cell_phases():
    """Flip one eta0 link sign (as the discriminator runner's T8 does)."""
    phases = eta0_cell_phases()
    phases[((1, 0, 0), 0)] *= -1.0
    return phases


# --------------------------------------------------------------------------
# Hermitian nearest-neighbor symbol machinery for the covariance legs.
# K(p) = C + sum_mu (A_mu cos p_mu + B_mu sin p_mu).
# --------------------------------------------------------------------------

def nn_symbol(p, C, As, Bs):
    M = np.array(C, dtype=complex)
    for mu in range(3):
        M = M + As[mu] * math.cos(float(p[mu])) + Bs[mu] * math.sin(float(p[mu]))
    return M


def rot_z12(p):
    """Proper C4z rotation of momentum: (p0,p1,p2) -> (p1,-p0,p2)."""
    return np.array([p[1], -p[0], p[2]], dtype=float)


def grid_points(N):
    vals = np.linspace(-math.pi, math.pi, N, endpoint=False)
    return list(itertools.product(vals, repeat=3))


# --------------------------------------------------------------------------
def main():
    print("=" * 78)
    print("realized kinetic branch D4 pattern dichotomy (2026-07-03)")
    print("=" * 78)

    edge_coeffs, spreads = absorbed_k1_edge_coefficients()
    gammas = extract_k1_gammas(edge_coeffs)
    # K0 one-coefficient-per-direction representative: scalar cos coefficient.
    k0_dir_coeffs = [I2.copy() for _ in range(3)]

    # ----- T1  Single-Hermitian-generator dichotomy + Cayley-Hamilton -----
    t1_ok = True
    ch_max = 0.0
    n_scalar = 0
    n_nonscalar = 0
    for _ in range(50):
        B = rand_hermitian(RNG)
        d = alg_dim([B])
        scalar = np.linalg.norm(B - (np.trace(B) / 2.0) * I2) < 1e-12
        if scalar:
            n_scalar += 1
            if d != 1:
                t1_ok = False
        else:
            n_nonscalar += 1
            if d != 2:
                t1_ok = False
        ch = np.linalg.norm(B @ B - (np.trace(B) * B - np.linalg.det(B) * I2))
        ch_max = max(ch_max, ch)
        if ch > 1e-12:
            t1_ok = False
    # Explicit scalars must give dim 1.
    for c in (0.0, 1.0, -2.5, 3.7):
        if alg_dim([c * I2]) != 1:
            t1_ok = False
    n_scalar += 4
    check(
        "T1",
        "single Hermitian generator gives dim 1 iff scalar else 2; Cayley-Hamilton holds",
        t1_ok,
        f"nonscalar->2 count={n_nonscalar}, scalar->1 count={n_scalar}, max CH residual={ch_max:.2e}",
    )

    # ----- T2  Dim-4 off-surface rejector -----
    d_s1s3 = alg_dim([S1, S3])
    pair4 = 0
    for _ in range(20):
        B1 = rand_hermitian(RNG)
        B2 = rand_hermitian(RNG)
        if alg_dim([B1, B2]) == 4:
            pair4 += 1
    check(
        "T2",
        "off-surface: two Hermitian generators reach dim 4 (sigma_1,sigma_3 and generic pairs)",
        d_s1s3 == 4 and pair4 >= 18,
        f"alg_dim([S1,S3])={d_s1s3}, generic dim-4 pairs={pair4}/20",
    )

    # ----- T3  Machinery rejector: non-Hermitian nilpotent -> dim 4 -----
    Anil = np.array([[0, 1], [0, 0]], dtype=complex)
    d_nil = alg_dim([Anil])
    check(
        "T3",
        "machinery gate: adjoint closure of nilpotent [[0,1],[0,0]] generates all of M_2(C)",
        d_nil == 4,
        f"alg_dim([A_nilpotent])={d_nil} (a scalarness branch would wrongly give 2)",
    )

    # ----- T4  K1 coefficients COMPUTED from parent; K0 scalar -----
    herm = all(np.linalg.norm(G - G.conj().T) < 1e-12 for G in gammas)
    unit = all(np.linalg.norm(G @ G - I2) < 1e-12 for G in gammas)
    anti = max(
        np.linalg.norm(gammas[i] @ gammas[j] + gammas[j] @ gammas[i])
        for i in range(3)
        for j in range(i + 1, 3)
    )
    k1_dims = [alg_dim([G]) for G in gammas]
    k0_dims = [alg_dim([A]) for A in k0_dir_coeffs]
    k0_scalar = max(
        np.linalg.norm(A - (np.trace(A) / 2.0) * I2) for A in k0_dir_coeffs
    )
    check(
        "T4",
        "computed K1 Gamma family is Hermitian/unitary/anticommuting with per-dir dims [2,2,2]; K0 scalar dims [1,1,1]",
        herm and unit and anti < 1e-12 and k1_dims == [2, 2, 2]
        and k0_dims == [1, 1, 1] and max(spreads) < 1e-12 and k0_scalar < 1e-12,
        f"K1 dims={k1_dims}, K0 dims={k0_dims}, max anticommutator={anti:.2e}, edge spread={max(spreads):.2e}",
    )

    # ----- T5  Rotation transport on the COMPUTED Gamma family -----
    # U_z = exp(-i pi/4 sigma_3); U_111 = exp(-i (2pi/3) n.sigma/2), n=(1,1,1)/sqrt3.
    Uz = _expm_2x2(-1j * (math.pi / 4.0) * S3)
    nsig = (S1 + S2 + S3) / math.sqrt(3.0)
    U111 = _expm_2x2(-1j * (2.0 * math.pi / 3.0) * nsig / 2.0)

    # U_z: sigma_1 -> ? sigma_2, sigma_2 -> ? sigma_1.  Determine the exact signs.
    cz1 = Uz @ gammas[0] @ Uz.conj().T
    cz2 = Uz @ gammas[1] @ Uz.conj().T
    sgn_z1 = _proportional_sign(cz1, gammas[1])
    sgn_z2 = _proportional_sign(cz2, gammas[0])
    z_ok = (
        sgn_z1 is not None and sgn_z2 is not None
        and np.linalg.norm(cz1 - sgn_z1 * gammas[1]) < 1e-12
        and np.linalg.norm(cz2 - sgn_z2 * gammas[0]) < 1e-12
        and alg_dim([cz1]) == alg_dim([gammas[0]])
    )
    # U_111: cyclic permutation (Gamma_1,Gamma_2,Gamma_3) up to sign.
    perm = [U111 @ G @ U111.conj().T for G in gammas]
    target = [gammas[1], gammas[2], gammas[0]]
    perm_signs = [_proportional_sign(perm[i], target[i]) for i in range(3)]
    cyc_ok = all(s is not None for s in perm_signs) and all(
        np.linalg.norm(perm[i] - perm_signs[i] * target[i]) < 1e-12 for i in range(3)
    )
    dim_preserved = all(alg_dim([perm[i]]) == alg_dim([gammas[i]]) for i in range(3))
    check(
        "T5",
        "spinor-rep rotations transport the computed Gamma family (U_z: 1<->2, U_111: 3-cycle) up to sign, dims preserved",
        z_ok and cyc_ok and dim_preserved,
        f"U_z signs=({sgn_z1},{sgn_z2}), U_111 cycle signs={perm_signs}",
    )

    # ----- T6  Direction-constancy forcing under U(2) conjugation + pattern filter -----
    conj_preserves = True
    conj_max_dev = 0
    for _ in range(20):
        U = rand_unitary(RNG)
        for M in (gammas[0], k0_dir_coeffs[0]):
            d0 = alg_dim([M])
            d1 = alg_dim([U @ M @ U.conj().T])
            conj_max_dev = max(conj_max_dev, abs(d1 - d0))
            if d1 != d0:
                conj_preserves = False
    all_patterns = list(itertools.product((1, 2), repeat=3))
    constant_patterns = [p for p in all_patterns if len(set(p)) == 1]
    no_filter = all_patterns
    filter_ok = (
        sorted(constant_patterns) == [(1, 1, 1), (2, 2, 2)]
        and len(no_filter) == 8
    )
    check(
        "T6",
        "alg_dim invariant under 20 Haar U(2) conjugations; constancy filter leaves exactly {[1,1,1],[2,2,2]}, no filter leaves all 8",
        conj_preserves and filter_ok,
        f"constant patterns={constant_patterns} (count {len(constant_patterns)}), unfiltered count={len(no_filter)}, max dim deviation={conj_max_dev}",
    )

    # ----- T7  Non-covariant mixed pattern realizability + covariance refutation -----
    Cmat = np.zeros((2, 2), dtype=complex)
    As_mixed = [I2.copy(), I2.copy(), I2.copy()]
    Bs_mixed = [S3.copy(), np.zeros((2, 2), dtype=complex), np.zeros((2, 2), dtype=complex)]
    # Per-direction algebra dimension of each direction's generator set, via alg_dim.
    mixed_dims = []
    for mu in range(3):
        gen = Bs_mixed[mu]
        if np.linalg.norm(gen) < 1e-12:
            # zero sin coefficient: the direction generator is the (scalar) A_mu = I only
            mixed_dims.append(alg_dim([As_mixed[mu]]))
        else:
            mixed_dims.append(alg_dim([gen]))
    grid = grid_points(6)
    best_defect = float("inf")
    for _ in range(200):
        U = rand_unitary(RNG)
        defect = 0.0
        for p in grid:
            p = np.array(p, dtype=float)
            lhs = U @ nn_symbol(p, Cmat, As_mixed, Bs_mixed) @ U.conj().T
            rhs = nn_symbol(rot_z12(p), Cmat, As_mixed, Bs_mixed)
            defect = max(defect, np.linalg.norm(lhs - rhs))
        best_defect = min(best_defect, defect)
    check(
        "T7",
        "non-covariant symbol B_1=sigma_3,B_2=B_3=0 has dims [2,1,1]; no unitary implements C4z covariance (floor > 0.5)",
        mixed_dims == [2, 1, 1] and best_defect > 0.5,
        f"mixed dims={mixed_dims}, min covariance defect over 200 unitaries={best_defect:.3f}",
    )

    # ----- T8  Fourier-Hermiticity extraction + non-Hermitian rejector -----
    # Build a Hermitian NN symbol from Hermitian coefficients, extract by
    # discrete Fourier orthogonality on an 8^3 grid, confirm every coefficient
    # Hermitian; then corrupt one coefficient and confirm K(p) != K(p)^dag.
    C_true = rand_hermitian(RNG)
    A_true = [rand_hermitian(RNG) for _ in range(3)]
    B_true = [rand_hermitian(RNG) for _ in range(3)]
    C_ext, A_ext, B_ext = fourier_extract(C_true, A_true, B_true)
    herm_defect = max(
        [np.linalg.norm(C_ext - C_ext.conj().T)]
        + [np.linalg.norm(A_ext[mu] - A_ext[mu].conj().T) for mu in range(3)]
        + [np.linalg.norm(B_ext[mu] - B_ext[mu].conj().T) for mu in range(3)]
    )
    recon_defect = max(
        np.linalg.norm(C_ext - C_true),
        max(np.linalg.norm(A_ext[mu] - A_true[mu]) for mu in range(3)),
        max(np.linalg.norm(B_ext[mu] - B_true[mu]) for mu in range(3)),
    )
    # Rejector: insert one non-Hermitian coefficient.
    A_bad = [a.copy() for a in A_true]
    A_bad[0] = np.array([[0, 1], [0, 0]], dtype=complex)  # non-Hermitian
    sym_defect = 0.0
    for p in grid_points(8):
        p = np.array(p, dtype=float)
        M = nn_symbol(p, C_true, A_bad, B_true)
        sym_defect = max(sym_defect, np.linalg.norm(M - M.conj().T))
    check(
        "T8",
        "Fourier orthogonality extracts Hermitian coefficients (reconstruction exact); a non-Hermitian coefficient breaks K(p)=K(p)^dag",
        herm_defect < 1e-12 and recon_defect < 1e-12 and sym_defect > 0.1,
        f"max coeff Herm defect={herm_defect:.2e}, reconstruction defect={recon_defect:.2e}, non-Herm symbol defect={sym_defect:.3f}",
    )

    # ----- T9  Guard: flip one eta0 link sign, blocked family loses anticommutation -----
    # Mirror the discriminator runner's T8: extract the blocked (2^3) first-order
    # coefficient family by momentum derivative, on clean and perturbed phases.
    clean_bg = blocked_derivative_gammas_8(eta0_cell_phases())
    pert_bg = blocked_derivative_gammas_8(perturbed_cell_phases())
    clean_anti = max(
        np.linalg.norm(clean_bg[i] @ clean_bg[j] + clean_bg[j] @ clean_bg[i])
        for i in range(3)
        for j in range(i + 1, 3)
    )
    pert_anti = max(
        np.linalg.norm(pert_bg[i] @ pert_bg[j] + pert_bg[j] @ pert_bg[i])
        for i in range(3)
        for j in range(i + 1, 3)
    )
    check(
        "T9",
        "guard: flipping one eta0 link sign breaks the clean anticommutation of the blocked family",
        pert_anti > 0.1 and clean_anti < 1e-12,
        f"perturbed anticommutation norm={pert_anti:.3f}, clean anticommutation norm={clean_anti:.2e}",
    )

    print()
    print(f"TOTAL: PASS={PASS} FAIL={FAIL}")
    print()
    print(
        "SUMMARY: On the parent two-flux-class kinetic surface, the D4 "
        "per-direction algebra-dimension"
    )
    print(
        "         discriminator is a BINARY CLASS INVARIANT on the covariant "
        "surface: for Hermitian"
    )
    print(
        "         nearest-neighbor symbols on the one-site C^2 carrier "
        "covariant under the proper cubic"
    )
    print(
        "         rotations the per-direction unital star-algebra dimension is "
        "CONSTANT across the three"
    )
    print(
        "         directions, and on the one-coefficient-per-direction "
        "representatives it lies in {1,2},"
    )
    print(
        "         realizing exactly [1,1,1] (K0 class) and [2,2,2] (K1 class). "
        "Off-surface Hermitian"
    )
    print(
        "         symbols realize dim 4 and non-covariant symbols realize "
        "direction-mixed patterns, so"
    )
    print(
        "         both hypotheses are load-bearing. The selector bit is not "
        "decided here, and the"
    )
    print("         Admissibility reading is not decided here.")
    return 0 if FAIL == 0 else 1


def _expm_2x2(M):
    """Matrix exponential for a 2x2 complex matrix via eigendecomposition."""
    w, V = np.linalg.eig(M)
    return V @ np.diag(np.exp(w)) @ np.linalg.inv(V)


def _proportional_sign(A, B, tol=1e-9):
    """Return s in {+1,-1} if A ~= s*B, else None (B must be nonzero)."""
    nb = np.linalg.norm(B)
    if nb < tol:
        return None
    for s in (1.0, -1.0):
        if np.linalg.norm(A - s * B) < 1e-9:
            return s
    return None


def fourier_extract(C_true, A_true, B_true):
    """Extract C, A_mu, B_mu from the Hermitian NN symbol by discrete Fourier
    orthogonality on an 8^3 momentum grid.

    K(p) = C + sum_mu (A_mu cos p_mu + B_mu sin p_mu).  On the uniform grid,
    <1,1>=1, <1,cos p_mu>=<1,sin p_mu>=0, <cos p_mu,cos p_nu>=(1/2)delta,
    <sin p_mu,sin p_nu>=(1/2)delta, <cos,sin>=0, so the coefficients are the
    grid averages of K weighted by 1, 2 cos p_mu, 2 sin p_mu respectively.
    """
    N = 8
    vals = np.linspace(-math.pi, math.pi, N, endpoint=False)
    pts = list(itertools.product(vals, repeat=3))
    npts = len(pts)
    C_acc = np.zeros((2, 2), dtype=complex)
    A_acc = [np.zeros((2, 2), dtype=complex) for _ in range(3)]
    B_acc = [np.zeros((2, 2), dtype=complex) for _ in range(3)]
    for p in pts:
        p = np.array(p, dtype=float)
        K = nn_symbol(p, C_true, A_true, B_true)
        C_acc += K
        for mu in range(3):
            A_acc[mu] += 2.0 * math.cos(float(p[mu])) * K
            B_acc[mu] += 2.0 * math.sin(float(p[mu])) * K
    C_ext = C_acc / npts
    A_ext = [A_acc[mu] / npts for mu in range(3)]
    B_ext = [B_acc[mu] / npts for mu in range(3)]
    return C_ext, A_ext, B_ext


if __name__ == "__main__":
    sys.exit(main())
