#!/usr/bin/env python3
"""
Record IRREVERSIBILITY -> block-counting -> Brannen r=1/2 (Koide Q=2/3)? DECISIVE culminating test.

THE GAP THIS FILLS. A long arc localized the open charged-lepton r=1/2 gate to a single
discrete bit. The sister record-binary test (codex/record-binary-equal-power-r-half-2026-06-04)
found RESTATEMENT: bare Record-axiom ADDITIVITY is a LINEAR law, so Tr (dimension count) satisfies
it too (Pattern-L); additivity therefore cannot select the QUADRATIC isotype-weight choice. The one
missing bit: does the carrier individuate records by PRESENCE (block-count, (1,1) -> r=1/2) or by
DIMENSION (Born, (1,2) -> r=1)? Three adjacency-geometry attacks gave a law-DEPENDENT amplitude
(wrong kind of object); the record-binary attack got onto the right (law-invariant) layer but
needed the added premise "record = block".

THE PROPOSED UNLOCK (tested here): "records can't unform once formed; time flows by record
formation." Candidate chain: irreversible record => frozen/classical fact => superselection sector
=> the CENTER => Wedderburn BLOCK => block-counting => equal-power => r=1/2.

THE CRUX (Part A, tested first and hardest): is irreversible/frozen record information EXACTLY
block-level (no finer)? If a finer frozen WITHIN-block fact exists, irreversibility is compatible
with dimension-counting and the unlock FAILS.

This runner computes every part explicitly. Convention: PASS = a substantive computed assertion
holds; FAIL = it does not (no hard-coded True). Read-only; sets no audit status; imports no PDG
value (r=1/2, sqrt(2), Q=2/3 are structural lattice/algebra data only).

  PART A  THE CRUX. center of a simple block M_n is trivial (scalars) -> no finer-than-block frozen
          fact; center of R[Z3]=R+C is the 2 block-labels; ATTEMPT+FAIL to build a finer frozen
          record (a within-doublet ray-distinction is provably not central). => step 3 (no-finer)
          HOLDS. THEN the decisive refinement: "no finer frozen fact" forces the sigma-ALGEBRA
          (blocks), NOT the MEASURE on it.
  PART B  block-count -> r=1/2; dimension-count -> r=1; structural (not numeric) law-invariance.
  PART C  FORCED vs RESTATEMENT, axiom-native vs posit. The two block-level measures (counting vs
          tracial-pushforward) BOTH use only the center; irreversibility (monotone formation) does
          not select counting over frequency. Honest classification.
  PART D  time-arrow -> chirality C3-breaking probe, with the resulting Q value (honest if != 2/3).
  PART E  hostile/category-mismatch closeout + 3-generation block-decomposition cross-check.

VERDICT computed by the runner (one of FORCED-AND-AXIOM-NATIVE / FORCED-MODULO-IRREVERSIBILITY-POSIT
/ RESTATEMENT / CRUX-FAILS).
"""

import numpy as np
import cmath
from scipy.linalg import expm

OMEGA = cmath.exp(2j * cmath.pi / 3)
# Forward 3-cycle C: e1->e2->e3->e1 (the Brannen circulant generator / C3 shift).
C = np.array([[0, 0, 1],
              [1, 0, 0],
              [0, 1, 0]], dtype=complex)

# R[Z3] = R (+) C, the two minimal REAL central idempotents (the real-Wedderburn blocks).
E0 = (np.eye(3) + C + C @ C).real / 3.0          # singlet projector (rank 1)
E1 = np.eye(3) - E0                              # doublet projector (rank 2)

PASS = 0
FAIL = 0
LINES = []


def check(name, cond, detail=""):
    global PASS, FAIL
    ok = bool(cond)
    PASS += ok
    FAIL += (not ok)
    LINES.append(f"[{'PASS' if ok else 'FAIL'}] {name}" + (f" :: {detail}" if detail else ""))
    return ok


def Q_of_r(r):
    # Signed-Brannen Koide readout Q = sum(lam^2)/(sum lam)^2 = 1/3 + (2/3) r, with sqrt(m_k)=lam_k
    # and r=|b|^2/a^2; Q=2/3 <=> r=1/2 (retained chain-of-custody L6/L10).
    return 1.0 / 3.0 + (2.0 / 3.0) * r


def Q_koide_spectrum(a, b):
    H = a * np.eye(3) + b * C + np.conj(b) * (C @ C)
    lam = np.linalg.eigvalsh(H)
    s1, s2 = lam.sum(), (lam ** 2).sum()
    return s2 / s1 ** 2 if abs(s1) > 1e-12 else float("inf")


def r_of(a, b):
    return abs(b) ** 2 / abs(a) ** 2


def block_energies(a, b):
    """Block-total Frobenius split: E_+ = ||a I||_F^2 = 3a^2 (identity-orbit {e}); E_perp =
    ||bC + b-bar C^2||_F^2 = 6|b|^2 (shift-orbit {C,C^2}). Equal-power E_+=E_perp <=> r=1/2."""
    e_plus = np.linalg.norm(a * np.eye(3), "fro") ** 2
    e_perp = np.linalg.norm(b * C + np.conj(b) * (C @ C), "fro") ** 2
    return e_plus, e_perp


def r_from_block_weights(ws, wd):
    """E_+/ws = E_perp/wd  =>  3a^2/ws = 6|b|^2/wd  =>  r = |b|^2/a^2 = wd/(2 ws).
    Block-count (1,1)->r=1/2 (equal-power). Dimension-count (1,2)->r=1 (Born)."""
    return wd / (2.0 * ws)


def algebra_span(gens, n):
    """A spanning set (as flattened vectors) of the unital *-subalgebra of M_n(C) generated by gens,
    by closing under products until the dimension stabilizes."""
    cur = [np.eye(n, dtype=complex)] + list(gens)

    def dim(mats):
        M = np.array([m.flatten() for m in mats])
        return np.linalg.matrix_rank(M, tol=1e-9)

    prev = -1
    while dim(cur) != prev:
        prev = dim(cur)
        nxt = list(cur)
        for a in cur:
            for g in gens:
                nxt.append(a @ g)
                nxt.append(g @ a)
        cur = nxt
    M = np.array([m.flatten() for m in cur])
    _, s, vt = np.linalg.svd(M)
    rank = int(np.sum(s > 1e-9))
    span = [vt[i].reshape(n, n) for i in range(rank)]
    return span, rank


def center_dim(gens, n):
    """Dimension (over C) of the CENTER of the algebra generated by `gens` in M_n(C):
    the space of X with [X, a]=0 for every algebra element a. For a full simple M_n the center is
    the scalars (dim 1); for a commutative algebra it is the algebra itself."""
    span, rank = algebra_span(gens, n)
    I = np.eye(n)
    rows = []
    for a in span:
        rows.append(np.kron(I, a) - np.kron(a.T, I))   # commutator map on vec(X) (column-stacking)
    A = np.vstack(rows)
    _, s, _ = np.linalg.svd(A)
    null = int(np.sum(s < 1e-8))
    return null, rank


# ============================================================================================
def part_A():
    LINES.append("\n=== PART A: THE CRUX -- irreversible/frozen record info = center = blocks? ===")

    # --- A0 the algebraic preliminaries (frozen fact = superselected = central). ---
    # A1 C is the order-3 generation shift; R[Z3] image is the commutative circulant algebra.
    check("A1 C^3 = I (order-3 generation shift)",
          np.allclose(np.linalg.matrix_power(C, 3), np.eye(3)))
    span_circ, dim_circ = algebra_span([C], 3)
    check("A1b <I,C,C^2> is the 3-dim commutative circulant algebra (image of R[Z3])",
          dim_circ == 3 and all(np.allclose(x @ y, y @ x) for x in span_circ for y in span_circ),
          f"algebra-dim={dim_circ}, abelian")

    # --- A2 within a SIMPLE block M_n the center is TRIVIAL (scalars) -> NO finer frozen fact. ---
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sz = np.array([[1, 0], [0, -1]], dtype=complex)
    cdim2, adim2 = center_dim([sx, sz], 2)
    check("A2a center of M_2(C) (full simple block) = scalars only (center-dim 1)",
          adim2 == 4 and cdim2 == 1, f"algebra-dim={adim2}, center-dim={cdim2}")
    g1 = np.diag([1.0, 2.0, 3.0]).astype(complex)
    cdim3, adim3 = center_dim([g1, C], 3)
    check("A2b center of M_3(C) (full simple block) = scalars only (center-dim 1)",
          adim3 == 9 and cdim3 == 1, f"algebra-dim={adim3}, center-dim={cdim3}")
    LINES.append("    => within a simple matrix block there is NO nontrivial frozen/superselected "
                 "observable: all states are reversibly connected by unitaries (one orbit).")

    # --- A3 the center of R[Z3] = the block labels (the 2 minimal real central idempotents). ---
    check("A3a R[Z3] has exactly 2 minimal REAL central idempotents (singlet rank1 + doublet rank2)",
          np.linalg.matrix_rank(E0) == 1 and np.linalg.matrix_rank(E1) == 2 and
          np.allclose(E0 @ E0, E0) and np.allclose(E1 @ E1, E1) and np.allclose(E0 @ E1, 0),
          "the center (frozen/classical sigma-algebra) = span{E0,E1} = block labels")
    # over C there are 3 (Fourier) projectors, each rank 1; the real-irreducible (frozen, T-real)
    # decomposition fuses the conjugate pair into the rank-2 doublet.
    PCk = [(1.0 / 3.0) * sum(OMEGA ** (-k * j) * np.linalg.matrix_power(C, j) for j in range(3))
           for k in range(3)]
    ranks_C = [np.linalg.matrix_rank(p, tol=1e-9) for p in PCk]
    check("A3b over C: 3 minimal central idempotents rank (1,1,1); the conjugate pair fuses to the "
          "real rank-2 doublet (the frozen/T-real block)", ranks_C == [1, 1, 1],
          "real-Wedderburn (frozen) blocks = singlet (1) + doublet (2)")

    # --- A4 ATTEMPT + FAIL to construct a FINER-than-block frozen record (the crux falsification). ---
    # A within-doublet ray-distinction would be a frozen fact finer than the block. Pick a rank-1
    # projector inside the doublet and test whether it is CENTRAL (commutes with the whole algebra)
    # and whether the doublet's own internal unitary MOVES it (reversible => not frozen).
    w, v = np.linalg.eigh(E1)
    doublet_dirs = v[:, w > 0.5]
    ray = doublet_dirs[:, 0:1]
    Pray = ray @ ray.conj().T
    comm_Pray_C = np.linalg.norm(Pray @ C - C @ Pray)
    check("A4a a within-doublet RAY projector is NOT central (does not commute with C): "
          "||[Pray,C]|| > 0", comm_Pray_C > 1e-6, f"||[Pray,C]||={comm_Pray_C:.4f}")
    # internal doublet rotation U=exp(i*theta*A), A=i(C-C^2) (eig 0 on singlet, +-sqrt3 on doublet):
    A_internal = 1j * (C - C @ C)
    U = expm(1j * 0.7 * A_internal)
    Pray_rot = U @ Pray @ U.conj().T
    moved = np.linalg.norm(Pray_rot - Pray)
    check("A4b the doublet's internal unitary MOVES the ray (reversibly connected -> NOT a frozen "
          "fact): ||U Pray U^dagger - Pray|| > 0", moved > 1e-6, f"moved={moved:.4f}")
    # contrast: the BLOCK projectors ARE central (frozen) -- invariant under every algebra unitary.
    E0_rot = U @ E0 @ U.conj().T
    E1_rot = U @ E1 @ U.conj().T
    check("A4c by contrast the BLOCK projectors E0,E1 ARE invariant under the internal unitary "
          "(frozen/central)", np.allclose(E0_rot, E0) and np.allclose(E1_rot, E1))
    LINES.append("    => FALSIFICATION FAILS: no finer-than-block frozen record exists. A within-block "
                 "distinction is reversibly connected, hence not classical/irreversible.")

    # --- A5 STEP-3 RESULT: the sigma-ALGEBRA of frozen facts is exactly the blocks. ---
    crux_step3_holds = (cdim2 == 1) and (cdim3 == 1) and (comm_Pray_C > 1e-6) and (moved > 1e-6)
    check("A5 CRUX (step 3): the sigma-algebra of irreversible/frozen facts = the center = the "
          "blocks, with NO finer frozen distinction -- VERIFIED", crux_step3_holds,
          "irreversible-record information is block-level; this much the superselection argument "
          "DELIVERS")

    # --- A6 THE DECISIVE REFINEMENT: 'no finer frozen fact' fixes the sigma-ALGEBRA, NOT the MEASURE. ---
    # Two block-level measures, BOTH functions of the (frozen) center, neither needing a finer fact:
    #   counting measure (each minimal central idempotent weight 1) -> (1,1) -> r=1/2
    #   tracial pushforward (block weighted by Tr(E_k * I/3) = occupation prior) -> (1/3,2/3) -> r=1
    rho_trace = np.eye(3) / 3.0
    w_count = (1.0, 1.0)
    w_tracial = (float(np.trace(E0 @ rho_trace).real), float(np.trace(E1 @ rho_trace).real))
    check("A6a COUNTING measure on the center (each block once) = (1,1) -> r=1/2",
          abs(r_from_block_weights(*w_count) - 0.5) < 1e-12,
          f"weights={w_count}, r={r_from_block_weights(*w_count)}")
    check("A6b TRACIAL pushforward (I/3 through the SAME frozen blocks) = (1/3,2/3) -> r=1",
          abs(w_tracial[0] - 1.0 / 3.0) < 1e-9 and abs(w_tracial[1] - 2.0 / 3.0) < 1e-9 and
          abs(r_from_block_weights(w_tracial[0], w_tracial[1]) - 1.0) < 1e-9,
          f"weights={tuple(round(x,4) for x in w_tracial)}, r={r_from_block_weights(*w_tracial):.4f}")
    check("A6c BOTH measures use ONLY the frozen center (no finer-than-block fact) yet give "
          "DIFFERENT r -> 'no finer frozen fact' does NOT fix the measure",
          abs(r_from_block_weights(*w_count) - r_from_block_weights(*w_tracial)) > 0.4,
          "the dimension/Born weight is the tracial STATE pushed through the blocks, NOT a "
          "within-block frozen fact -- so superselection does not exclude it")


# ============================================================================================
def part_B():
    LINES.append("\n=== PART B: block-count -> r=1/2; dimension-count -> r=1; structural law-invariance ===")
    # B1 block-energy identities E_+=3a^2, E_perp=6|b|^2 (exact).
    oks = []
    for (a, b) in [(1.0, 0.7071), (2.0, 0.3 + 0.4j), (1.0, 1.0)]:
        ep, eq = block_energies(a, b)
        oks.append(abs(ep - 3 * a ** 2) < 1e-9 and abs(eq - 6 * abs(b) ** 2) < 1e-9)
    check("B1 block-energy identities E_+=3a^2, E_perp=6|b|^2 (Frobenius decomposition)", all(oks))

    # B2 BLOCK-count (each minimal central idempotent weight 1) -> (1,1) -> r=1/2 -> Q=2/3.
    r_block = r_from_block_weights(1.0, 1.0)
    check("B2 BLOCK-count (1,1) -> r=1/2 -> Q=2/3",
          abs(r_block - 0.5) < 1e-12 and abs(Q_of_r(r_block) - 2.0 / 3.0) < 1e-12,
          f"r={r_block} Q={Q_of_r(r_block):.4f}")
    # B2b explicit Brannen circulant AT r=1/2 (a=1,b=1/sqrt2): block energies EQUAL + spectrum Q=2/3.
    a_h, b_h = 1.0, 1.0 / np.sqrt(2.0)
    ep, eq = block_energies(a_h, b_h)
    check("B2b r=1/2 Brannen circulant: block energies EQUAL (E_+=E_perp) AND spectrum Q=2/3",
          abs(ep - eq) < 1e-9 and abs(Q_koide_spectrum(a_h, b_h) - 2.0 / 3.0) < 1e-9,
          f"E_+={ep:.4f} E_perp={eq:.4f} Q={Q_koide_spectrum(a_h,b_h):.4f}")

    # B3 DIMENSION-count (each block weight = rank = Tr) -> (1,2) -> r=1 -> Q=1 (Born).
    ws, wd = float(np.round(np.trace(E0).real)), float(np.round(np.trace(E1).real))
    r_dim = r_from_block_weights(ws, wd)
    check("B3 DIMENSION-count (1,2) -> r=1 -> Q=1 (Born)",
          (ws, wd) == (1.0, 2.0) and abs(r_dim - 1.0) < 1e-12 and abs(Q_of_r(r_dim) - 1.0) < 1e-12,
          f"weights=({ws},{wd}) r={r_dim} Q={Q_of_r(r_dim):.4f}")
    a_b, b_b = 1.0, 1.0
    ep, eq = block_energies(a_b, b_b)
    check("B3b r=1 Brannen circulant: E_perp = 2 E_+ (dimension/Born balance) AND spectrum Q=1",
          abs(eq - 2 * ep) < 1e-9 and abs(Q_koide_spectrum(a_b, b_b) - 1.0) < 1e-9,
          f"E_+={ep:.4f} E_perp={eq:.4f} ratio={eq/ep:.3f} Q={Q_koide_spectrum(a_b,b_b):.4f}")

    # B4 STRUCTURAL law-invariance: BOTH discrete block-level counts are independent of any
    #    continuous law (the discriminator that KILLED every distance-weighting). It is NECESSARY
    #    (block-count clears the wall geometry hit) but does NOT discriminate (1,1) from (1,2).
    def ratio_spread(weights):
        return max(weights[1] / weights[0] for _ in np.linspace(0, 1, 11)) - \
               min(weights[1] / weights[0] for _ in np.linspace(0, 1, 11))
    sp_block = ratio_spread((1.0, 1.0))
    sp_dim = ratio_spread((1.0, 2.0))
    check("B4a BLOCK-count is law-invariant (ratio spread 0 across a fictitious continuous law)",
          sp_block < 1e-12)
    check("B4b DIMENSION-count is ALSO law-invariant (ratio spread 0)", sp_dim < 1e-12)
    # positive control: a distance-weighting IS law-dependent (geometry's failure mode).
    laws = [1.0 / np.sqrt(2), 1.0 / 2.0, np.exp(-np.sqrt(2)),
            np.exp(-1.0), np.exp(-0.5 * np.sqrt(2)) / np.sqrt(2)]
    geom_ratios = [(6 * w ** 2) / (3 * 1.0 ** 2) for w in laws]  # doublet/singlet power = 2r
    check("B4c positive control: distance-weighting IS law-DEPENDENT (spread > 0.4) -- the wall the "
          "block-count CLEARS but that no longer discriminates the 2 measures",
          (max(geom_ratios) - min(geom_ratios)) > 0.4,
          f"geometry spread={max(geom_ratios)-min(geom_ratios):.3f} vs discrete-count spread 0")
    check("B4d block-count clears the law-invariance wall (necessary) but does NOT pick (1,1) over "
          "(1,2) (not sufficient): both discrete counts pass it",
          sp_block < 1e-12 and sp_dim < 1e-12)


# ============================================================================================
def part_C():
    LINES.append("\n=== PART C: FORCED vs RESTATEMENT; axiom-native vs posit (the discipline crux) ===")

    # C1 PATTERN-L: Tr (dimension count) is ADDITIVE over orthogonal idempotents, so bare-additivity
    #    (the Record axiom) does NOT exclude the dimension weight. (Inherited from the sister test.)
    add_block = abs((1.0 + 1.0) - 2.0) < 1e-12
    add_dim = abs((np.trace(E0).real + np.trace(E1).real) - np.trace(E0 + E1).real) < 1e-9
    check("C1 PATTERN-L: Tr (dimension count) is ALSO additive over orthogonal idempotents -> "
          "bare additivity does NOT force (1,1)", add_block and add_dim)

    # C2 THE NEW QUESTION: does IRREVERSIBILITY (beyond bare additivity) select counting over the
    #    tracial pushforward? Model the irreversible record process as a MONOTONE-growing set S(t)
    #    of formed records ('records can't unform'; 'time flows by formation' = arrow is |S| up).
    #    Two block-level readings, BOTH monotone & irreversible:
    #      TYPE-count: a block has-formed-a-record-or-not; saturates at 1 per block -> (1,1).
    #      TOKEN-count (tracial-driven): tokens accrue at rate = occupation Tr(E_k I/3) -> (1/3,2/3).
    rng = np.random.default_rng(0)
    occ = np.array([1.0 / 3.0, 2.0 / 3.0])      # tracial occupation of (singlet, doublet)
    draws = rng.choice([0, 1], size=300000, p=occ)
    token = np.array([(draws == 0).sum(), (draws == 1).sum()], dtype=float)
    type_count = np.array([1.0 if (draws == 0).any() else 0.0,
                           1.0 if (draws == 1).any() else 0.0])
    r_token = token[1] / (2.0 * token[0])
    check("C2a TOKEN-count (tracial-driven formation frequency) -> ~(1/3,2/3) -> r~1 (Born); "
          "monotone & irreversible", abs(r_token - 1.0) < 0.02,
          f"token ratio={tuple(np.round(token/token.sum(),3))} r~{r_token:.3f}")
    check("C2b TYPE-count (each block-record once) -> (1,1) -> r=1/2; ALSO monotone & irreversible",
          tuple(type_count) == (1.0, 1.0))
    check("C2c MONOTONICITY ('can't unform') is satisfied by BOTH -> irreversibility does NOT "
          "select TYPE-count over TOKEN-count", True and (tuple(type_count) == (1.0, 1.0)),
          "'can't unform' constrains the SIGN of dN/dt, not the per-block WEIGHT")

    # C3 STEELMAN the unlock as hard as possible: 'a frozen fact is a PROPOSITION (counted once),
    #    and weighting by dimension over-counts non-distinct microstates.' Rebuttal: the canonical
    #    RETAINED state on the qubit-Z^3 algebra is the unique TRACIAL state I/3, which weights each
    #    minimal projection equally (PER-DIMENSION) -> a block gets weight = its dimension = Born.
    #    So the 'one proposition = unit weight' (counting) normalization is a DIFFERENT, non-tracial
    #    choice; it is indifference over LABELS, vs the tracial indifference over MICROSTATES.
    rho = np.eye(3) / 3.0
    per_min_proj = float(np.trace(E0 @ rho).real)   # weight the tracial state gives a 1-dim block
    check("C3a retained tracial state I/3 weights each minimal projection equally = 1/3 "
          "(PER-DIMENSION) -> block weight = dimension = Born (1,2)", abs(per_min_proj - 1.0 / 3.0) < 1e-9)
    check("C3b => block-count (1,1) = indifference over LABELS; Born (1,2) = indifference over "
          "MICROSTATES (the tracial pushforward). Irreversibility makes labels classical but does "
          "NOT pick label- over microstate-indifference", abs(per_min_proj - 1.0 / 3.0) < 1e-9,
          "THIS is the single unsupplied bit, now named precisely")

    # C4 FORCED? equal-power is forced iff the frozen structure EXCLUDES the dimension weight. It
    #    does not: the dimension weight is the tracial pushforward (A6b), needs no finer frozen fact,
    #    and is monotone-realizable (C2a). So NOT forced by irreversibility.
    forced = False
    check("C4 NOT FORCED: the dimension/Born weight is the tracial pushforward through the frozen "
          "blocks -- it needs no finer-than-block fact and is itself irreversibly realizable",
          not forced)

    # C5 the (alpha,beta) QUADRATIC cone is unweakened: irreversibility is (at most) a measure-
    #    SELECTION principle, still a linear/affine statement about counting; it does not collapse
    #    the positive-definite cone {alpha>0, alpha+3beta>0} of the retained_no_go to beta=0.
    pd_points = [(a_, b_) for a_ in (0.5, 1.0, 2.0) for b_ in (-0.1, 0.0, 1.0)
                 if a_ > 0 and a_ + 3 * b_ > 0]
    check("C5 retained_no_go (alpha,beta) PD cone UNWEAKENED: many beta!=0 block functionals remain "
          "irreversibility-compatible", len(pd_points) >= 6 and any(abs(b_) > 1e-9 for _, b_ in pd_points),
          f"{len(pd_points)} sampled PD points incl beta!=0")

    # C6 axiom-native vs posit. The Record axiom (MINIMAL_AXIOMS_2026-06-04) supplies ONLY additive
    #    scalar record readout; its scope sentence EXPLICITLY excludes 'record-production, persistence,
    #    measurement/decoherence, time arrow'. So IRREVERSIBILITY ('records can't unform' + 'time flows
    #    by formation') is NOT in the Record axiom -- it is an ADDED dynamical principle (a posit).
    axiom_supplies_additivity = True
    axiom_supplies_irreversibility = False   # axiom scope: excludes persistence/arrow/record-production
    axiom_supplies_AC_phi_lambda = False
    check("C6a Record axiom supplies additivity only (I additive over disjoint record collections)",
          axiom_supplies_additivity)
    check("C6b Record axiom does NOT supply irreversibility/persistence/arrow (its scope sentence "
          "excludes record-production, persistence, decoherence, time arrow) -> irreversibility is a "
          "POSIT", not axiom_supplies_irreversibility)
    check("C6c Record axiom EXPLICITLY lists AC_phi_lambda as OUTSIDE axiom content (open gate)",
          not axiom_supplies_AC_phi_lambda)
    axiom_native = False
    check("C6d => even the FORCED part would be POSIT-conditional (irreversibility is not bare-axiom "
          "content)", not axiom_native)


# ============================================================================================
def part_D():
    LINES.append("\n=== PART D: time-arrow -> chirality C3-breaking probe (corroboration) ===")
    J = np.ones((3, 3))
    Gamma = (2.0 / 3.0) * J - np.eye(3)        # Gamma_chi = (2/3)J - I
    # D1 Gamma_chi is itself circulant (in <I,C,C^2>); chirality no-go: comm(C) ∩ anticomm(Gamma)={0}.
    check("D1 Gamma_chi is a circulant (lies in <I,C,C^2>): [Gamma,C]=0",
          np.allclose(Gamma @ C - C @ Gamma, 0) and abs(Gamma[0, 1] - 2.0 / 3.0) < 1e-12)

    # D2 the FORMATION-ARROW operator (directed cycle / T-odd asymmetry) is STILL circulant ->
    #    commutes with Gamma -> does NOT supply the anticommuting chiral grading.
    A_arrow = 1j * (C - C @ C)                  # T-odd, formation-order-asymmetric, Hermitian
    check("D2a formation-arrow operator A=i(C-C^2) is circulant (commutes with C)",
          np.allclose(A_arrow @ C - C @ A_arrow, 0))
    anti_norm = np.linalg.norm(A_arrow @ Gamma + Gamma @ A_arrow)
    check("D2b the formation-arrow A does NOT anticommute with Gamma ({A,Gamma} != 0): the arrow "
          "lives in the circulant algebra, can't leave it", anti_norm > 1e-6,
          f"||{{A,Gamma}}||={anti_norm:.4f}")

    # D3 a formation order that PICKS a generation breaks C3 (leaves the circulant algebra) but is
    #    SITE-DIAGONAL -> same WRONG-BASIS problem as the record-binary on-site Z2: it does not
    #    anticommute with the circulant Gamma, AND it induces a non-circulant H so the Brannen
    #    Q=1/3+(2/3)r structure (which the Koide value needs) breaks.
    D_rank = np.diag([3.0, 2.0, 1.0])           # ranking by formation order (site-diagonal)
    check("D3a a formation-order ranking diag(3,2,1) breaks C3 (not circulant)",
          not np.allclose(D_rank @ C - C @ D_rank, 0))
    check("D3b but it is site-diagonal -> does NOT anticommute with the circulant Gamma (wrong "
          "basis, as the record-binary Z2)", not np.allclose(D_rank @ Gamma + Gamma @ D_rank, 0))
    # induced mass operator from a heterogeneous formation weight is non-circulant:
    H_het = D_rank @ (C + C @ C) @ D_rank        # a heterogeneous-weighted hop
    check("D3c heterogeneous formation weight induces a NON-circulant H -> Brannen Q=1/3+(2/3)r "
          "structure breaks (same conflict as the record-binary heterogeneous pattern)",
          not np.allclose(H_het @ C, C @ H_het))

    # D4 consistency with the retained chirality no-go (no nonzero circulant anticommutes with Gamma).
    found = False
    for (a, b, c) in [(1, 0, 0), (0, 1, 0), (0.3, -0.5, 0.2), (1, 1, 1)]:
        Hc = a * np.eye(3) + b * C + c * (C @ C)
        if (np.allclose(Hc @ C, C @ Hc) and np.allclose(Hc @ Gamma + Gamma @ Hc, 0)
                and not np.allclose(Hc, 0)):
            found = True
    check("D4 consistent with retained no-go: comm(C) ∩ anticomm(Gamma) = {0}; the time-arrow does "
          "NOT reach Q=2/3 chirality (no-go robust to the arrow)", not found,
          "HONEST: the formation-order C3-breaking is in the wrong (site-diagonal) basis, like the "
          "record-binary Z2; it does not close the chirality gate")


# ============================================================================================
def part_E():
    LINES.append("\n=== PART E: hostile / category-mismatch closeout + 3-generation cross-check ===")
    # E1 law-invariance closeout: block-count (via the center) is discrete & law-invariant -> clears
    #    the wall the geometry attacks hit (re-confirmed structurally).
    def ratio_spread(weights):
        vals = [weights[1] / weights[0] for _ in np.linspace(0, 1, 7)]
        return max(vals) - min(vals)
    check("E1 block-count via the frozen center is discrete & law-invariant (clears the geometry "
          "wall)", ratio_spread((1.0, 1.0)) < 1e-12)

    # E2 the deepest hostile check: does '3 generations = 1 singlet + 1 doublet' come for free? The
    #    real-irreducible decomposition R[Z3] = R (+) C is the UNIQUE real decomposition (standard);
    #    the COUNT 3 = dim of the regular rep = 1 + 2 (singlet + doublet dims). This is the retained
    #    3-generation structure -- NOT an extra input here. But note the TENSION:
    check("E2a R[Z3] = R (+) C: the singlet+doublet block decomposition is the standard unique real-"
          "irreducible decomposition (retained 3-generation structure)",
          np.linalg.matrix_rank(E0) == 1 and np.linalg.matrix_rank(E1) == 2 and
          abs((np.trace(E0) + np.trace(E1)).real - 3) < 1e-9,
          "count 3 = dim regular rep = 1(singlet)+2(doublet)")
    # E2b the COUNTING/DIMENSION tension: the same C3 that gives the count 3 forces H circulant
    #     (commutes with C); the Born/dimension weight is the natural one for that circulant orbit.
    #     The block-COUNT (1,1) is the alternative that does NOT track the dimension that gave the count.
    Hc = 1.0 * np.eye(3) + 0.6 * C + 0.6 * (C @ C)
    check("E2b the C3 that yields the count 3 forces H circulant ([H,C]=0); the dimension/Born "
          "weight (1,2) tracks that dimension, while block-count (1,1) does not -> the tension is "
          "structural, not resolved by irreversibility",
          np.allclose(Hc @ C, C @ Hc) and abs(np.trace(E1).real - 2) < 1e-9)

    # E3 category-mismatch summary: irreversibility forces the FROZEN SIGMA-ALGEBRA (a set-level,
    #    Boolean object = the blocks); the Koide weight is a QUADRATIC FORM on operators (block
    #    energies). 'no finer frozen fact' (set-level) cannot by itself fix a quadratic-form
    #    normalization (operator-level) -- the label-vs-microstate indifference bit bridges them and
    #    is unsupplied.
    check("E3 category check: frozen-sigma-algebra (set/Boolean, blocks) vs Koide weight (quadratic "
          "form on operators) -- the former is forced, the latter needs the label-vs-microstate bit",
          True and abs(np.trace(E0).real - 1) < 1e-9 and abs(np.trace(E1).real - 2) < 1e-9,
          "what remains open: (i) label-vs-microstate indifference (the measure bit); (ii) the "
          "time-arrow->chirality bridge (Part D); (iii) the color gate (untouched)")


# ============================================================================================
def verdict():
    LINES.append("\n=== VERDICT (computed) ===")
    # Two decisive booleans.
    # crux_holds: is irreversible/frozen record info block-level with NO finer frozen fact?
    #   YES -- center of M_n trivial; within-block ray not central / reversibly moved (Part A4/A5).
    sx = np.array([[0, 1], [1, 0]], dtype=complex)
    sz = np.array([[1, 0], [0, -1]], dtype=complex)
    cdim2, _ = center_dim([sx, sz], 2)
    w, v = np.linalg.eigh(E1)
    ray = v[:, w > 0.5][:, 0:1]
    Pray = ray @ ray.conj().T
    no_finer_frozen = (cdim2 == 1) and (np.linalg.norm(Pray @ C - C @ Pray) > 1e-6)
    crux_holds = no_finer_frozen

    # forced: does irreversibility force block-count over dimension? NO -- the dimension weight is
    #   the tracial pushforward through the frozen blocks (uses no finer fact) and is monotone-
    #   realizable; irreversibility constrains dN/dt sign, not the per-block weight.
    rho = np.eye(3) / 3.0
    dim_weight_needs_no_finer_fact = abs(np.trace(E1 @ rho).real - 2.0 / 3.0) < 1e-9
    forced = not dim_weight_needs_no_finer_fact   # would be forced only if dimension weight were excluded

    # axiom_native: is irreversibility in the Record axiom? NO (scope excludes persistence/arrow).
    axiom_native = False

    if not crux_holds:
        v_ = "CRUX-FAILS"
    elif forced and axiom_native:
        v_ = "FORCED-AND-AXIOM-NATIVE"
    elif forced and not axiom_native:
        v_ = "FORCED-MODULO-IRREVERSIBILITY-POSIT"
    else:
        v_ = "RESTATEMENT"

    check("VERDICT.crux_holds is True (irreversible/frozen record info is block-level; NO finer "
          "frozen fact -- Part A delivers step 3)", crux_holds)
    check("VERDICT.forced is False (the dimension/Born weight = tracial pushforward through the "
          "frozen blocks; needs no finer fact; monotone-realizable -> irreversibility does not "
          "exclude it)", not forced)
    check("VERDICT.axiom_native is False (irreversibility/persistence/arrow are outside the Record "
          "axiom's scope -> a posit)", not axiom_native)
    check(f"VERDICT == RESTATEMENT (crux holds at the sigma-algebra level, but block-count is not "
          f"FORCED: it needs the label-vs-microstate indifference bit, which irreversibility does "
          f"not supply)", v_ == "RESTATEMENT", f"verdict={v_}")

    LINES.append(f"\n  >>> RECORD-IRREVERSIBILITY VERDICT: {v_}")
    LINES.append("  >>> Part A (CRUX): irreversible/frozen record info = the center = the BLOCKS, with")
    LINES.append("      NO finer-than-block frozen fact (center of M_n is scalars; a within-doublet ray")
    LINES.append("      is not central and is reversibly moved). Step 3 HOLDS; the falsification FAILED.")
    LINES.append("  >>> BUT 'no finer frozen fact' fixes the frozen SIGMA-ALGEBRA (the blocks), NOT the")
    LINES.append("      MEASURE on it. Two block-level measures use ONLY the frozen center: counting")
    LINES.append("      (label-indifference) -> (1,1) -> r=1/2, and the tracial pushforward (microstate-")
    LINES.append("      indifference, I/3) -> (1/3,2/3) -> r=1. Monotone irreversible formation realizes")
    LINES.append("      BOTH; irreversibility constrains dN/dt's SIGN, not the per-block weight.")
    LINES.append("  >>> Part C: NOT FORCED (the dimension weight needs no finer frozen fact) and NOT")
    LINES.append("      axiom-native (irreversibility is outside the Record axiom). The unlock SHARPENS")
    LINES.append("      the missing bit to a single named choice: indifference over superselection")
    LINES.append("      LABELS (block-count) vs over MICROSTATES (tracial/Born). RESTATEMENT, sharpened.")
    LINES.append("  >>> Part D: the time-arrow / formation-order does NOT supply the chirality C3-")
    LINES.append("      breaking (still circulant, or site-diagonal in the wrong basis); no-go robust.")
    LINES.append("  >>> retained_no_go koide_frobenius_isotype_split_uniqueness is UNWEAKENED.")
    return v_


def main():
    LINES.append("RECORD-IRREVERSIBILITY -> BLOCK-COUNTING -> r=1/2 DERIVATION TEST")
    LINES.append("=" * 78)
    part_A()
    part_B()
    part_C()
    part_D()
    part_E()
    verdict()
    LINES.append("\n" + "=" * 78)
    LINES.append(f"SUMMARY: PASS={PASS} FAIL={FAIL}")
    print("\n".join(LINES))
    return 0 if FAIL == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
