#!/usr/bin/env python3
"""Staggered-Dirac realization gate -- bounded synthesis composition check.

Companion runner for
    docs/STAGGERED_DIRAC_REALIZATION_GATE_NOTE_2026-05-03.md
(2026-06-09/10 science-fix: the gate note is rewritten from a pure
open-gate identity assignment into a bounded synthesis note whose
load-bearing step is the COMPUTED composition of the four substep
theorems.  This runner instantiates the whole chain end-to-end on a
finite Z^3 box from the Cl(3) Pauli realization and the Z^3 lattice
structure; nothing load-bearing is asserted without being computed.)

What is computed (all deterministic, no network, runtime << 5 min):

  Statistics interface (Grassmann statistics dichotomy):
      Cl(3) Pauli relations, central pseudoscalar, the single fermion
      mode on the dim-2 per-site module, and the finite-dimensional
      CCR trace obstruction (bosonic mode needs infinite dimension,
      incompatible with per-site dim 2).

  Kawamoto-Smit phase extraction, computed not asserted:
      the spin-diagonalization scalarization T(x)^dag sigma_mu T(x+mu)
      is solved site by site on a 4^3 box; the phases are EXTRACTED
      and only then compared to the closed-form KS law; the Clifford
      -1 plaquette cocycle, gauge-class uniqueness (gauge transform +
      recovery of the gauge function by path products), and rejection
      of the all-plus sign law are verified.  The load-bearing kinetic-class
      residual is exposed: the 2-component naive operator (no spin
      diagonalization) is also Quantum + Lattice-compatible and carries 16 corner
      modes instead of 8.

  BZ-corner computation, computed not asserted:
      the one-component staggered operator D on the 4^3 periodic torus
      is built from the extracted phases; kernel dim = 8 by SVD; the
      kernel is translation invariant; the 8 joint translation
      characters are exactly the taste cube {+-1}^3; Hamming multiset
      = {1,3,3,1}; everything is invariant under a deterministic Z2
      gauge conjugation (gauge-class invariance lemma of the note);
      the APBC convention residual is exposed (no exact zero modes at
      finite L under APBC).

  hw=1 algebraic species surface + labeling no-go:
      the cyclic axis rotation U_R preserves ker D, 3-cycles the hw=1
      and hw=2 corner triplets, and conjugation by U_R cyclically
      permutes the translation operators; the algebra generated by
      (T_1,T_2,T_3,C_3)|_{hw=1} has dimension 9 (= M_3(C)) with
      scalar center and scalar commutant (irreducible, no proper
      exact quotient); the translations-only commutant is the
      3-dimensional diagonal algebra (AC_lambda corollary); the
      labeling no-go witness is computed (the entire computed
      structure is C_3-covariant and the three hw=1 states form a
      single C_3 orbit, so no structure-derived labeling functional
      can separate them); the labeling-convention premise is shown
      to be genuinely distinguishing (a generic C_3-equivariant
      Hermitian has 3 distinct eigenvalues, so a sorted-order
      convention fixes a unique bijection).

  Interface checks against the cited substep notes (class B):
      extracted KS law == substep-2 Theorem 2 constants; Hamming
      counts == substep-3 Theorem 3; hw=1 joint characters ==
      AC_lambda bridge note eqs. (2a)-(2c).

PASS/FAIL per check; final line:  TOTAL: PASS=<n> FAIL=<m>
"""

import sys
import numpy as np

L = 4                     # box side (even, so corner momenta are exact)
N = L ** 3                # number of sites
TOL = 1e-9

_pass = 0
_fail = 0


def check(num, desc, ok, detail=""):
    global _pass, _fail
    tag = "PASS" if ok else "FAIL"
    if ok:
        _pass += 1
    else:
        _fail += 1
    line = f"[{tag}] ({num:02d}) {desc}"
    if detail:
        line += f"  [{detail}]"
    print(line)


def residual(msg):
    print(f"RESIDUAL (declared-open): {msg}")


def idx(x1, x2, x3):
    return (x1 % L) + L * ((x2 % L) + L * (x3 % L))


def sites():
    for x3 in range(L):
        for x2 in range(L):
            for x1 in range(L):
                yield (x1, x2, x3)


EMU = [(1, 0, 0), (0, 1, 0), (0, 0, 1)]

# ----------------------------------------------------------------------
print("=" * 72)
print("Staggered-Dirac realization gate -- bounded synthesis check")
print("box: Z^3 torus, L =", L, "(periodic boundary condition for the corner computation)")
print("=" * 72)

# ============================ statistics interface =====================
print("\n--- statistics interface: Cl(3) module + statistics dichotomy")

s1 = np.array([[0, 1], [1, 0]], dtype=complex)
s2 = np.array([[0, -1j], [1j, 0]], dtype=complex)
s3 = np.array([[1, 0], [0, -1]], dtype=complex)
SIG = [s1, s2, s3]
I2 = np.eye(2, dtype=complex)

ok = all(
    np.allclose(SIG[i] @ SIG[j] + SIG[j] @ SIG[i], 2.0 * (i == j) * I2)
    for i in range(3) for j in range(3)
)
check(1, "Cl(3) Pauli realization: {sigma_i, sigma_j} = 2 delta_ij on dim 2",
      ok, "per-site module dim = 2")

omega = s1 @ s2 @ s3
ok = np.allclose(omega, 1j * I2)
check(2, "central pseudoscalar omega = sigma_1 sigma_2 sigma_3 = i*I (chirality)",
      ok)

a = (s1 + 1j * s2) / 2.0          # single fermion mode on the dim-2 module
ok = (np.allclose(a @ a, 0 * I2)
      and np.allclose(a @ a.conj().T + a.conj().T @ a, I2))
check(3, "single Grassmann/fermion mode on dim-2 module: a^2=0, {a,a+}=I",
      ok, "per-site fermionic Fock dim = 2")

# Finite-dimensional CCR trace obstruction: no finite-dim b with
# [b,b+] = I, because Tr[b,b+] = 0 != Tr I = n.  Computed for n=2..6:
# the best-approximating truncated bosonic mode always violates the CCR
# on the top state, and the trace residual is exactly n.
ccr_ok = True
for n in range(2, 7):
    b = np.diag(np.sqrt(np.arange(1, n)), 1)       # truncated boson
    comm = b @ b.conj().T - b.conj().T @ b
    trace_gap = abs(np.trace(comm))                # = 0 for any finite b
    target = n                                     # = Tr I_n
    if not (trace_gap < TOL and target >= 2):
        ccr_ok = False
ok = ccr_ok
check(4, "finite-dim CCR obstruction: Tr[b,b+]=0 != Tr I=n for all n=2..6 "
         "(bosonic mode forces dim=infinity, incompatible with dim-2 module)",
      ok)
residual("substep-1 bosonic exclusion rests on the spin-statistics "
         "support input of STAGGERED_DIRAC_GRASSMANN_FORCING_THEOREM_NOTE_"
         "2026-05-07; this runner verifies its finite trace-obstruction "
         "core, not the full QFT spin-statistics theorem.")

# ============================ Kawamoto-Smit phase extraction ===========
print("\n--- Kawamoto-Smit phase extraction: computed by scalarization")


def Tspin(x):
    """T(x) = sigma_1^{x1} sigma_2^{x2} sigma_3^{x3}."""
    m = I2.copy()
    for p, s in zip(x, SIG):
        for _ in range(p % 2):
            m = m @ s
    return m


eta_ext = {}                  # extracted phases, eta_ext[(x, mu)]
scalar_ok = True
for x in sites():
    for mu, e in enumerate(EMU):
        xp = tuple((x[k] + e[k]) for k in range(3))
        M = Tspin(x).conj().T @ SIG[mu] @ Tspin(xp)
        val = M[0, 0]
        if not (np.allclose(M, val * I2) and abs(abs(val) - 1) < TOL
                and abs(val.imag) < TOL):
            scalar_ok = False
        eta_ext[(x, mu)] = int(round(val.real))
check(5, "scalarization T(x)+ sigma_mu T(x+mu) = eta*I solved at all "
         f"{N * 3} (site,mu) pairs; eta in {{+1,-1}}", scalar_ok)


def eta_ks(x, mu):
    if mu == 0:
        return 1
    if mu == 1:
        return (-1) ** (x[0] % 2)
    return (-1) ** ((x[0] + x[1]) % 2)


ok = all(eta_ext[(x, mu)] == eta_ks(x, mu) for x in sites() for mu in range(3))
check(6, "extracted phases equal the Kawamoto-Smit law eta_1=1, "
         "eta_2=(-1)^x1, eta_3=(-1)^(x1+x2) at every (site,mu)", ok,
      "class-B interface to substep-2 Theorem 2")


def cocycle_holds(eta_fun):
    """Clifford -1 plaquette cocycle for a phase field."""
    n_checked = 0
    for x in sites():
        for mu in range(3):
            for nu in range(mu + 1, 3):
                xp_mu = tuple(x[k] + EMU[mu][k] for k in range(3))
                xp_nu = tuple(x[k] + EMU[nu][k] for k in range(3))
                lhs = eta_fun(xp_mu, nu) * eta_fun(x, mu)
                rhs = -eta_fun(xp_nu, mu) * eta_fun(x, nu)
                n_checked += 1
                if lhs != rhs:
                    return False, n_checked
    return True, n_checked


ok, nchk = cocycle_holds(eta_ks)
check(7, "canonical phases obey the Clifford -1 plaquette cocycle", ok,
      f"{nchk} plaquette checks")


def gfun(x):
    """Deterministic non-trivial Z2 gauge function (period-2, torus-safe)."""
    return (-1) ** ((x[0] * x[1] + x[2]) % 2)


def eta_gauged(x, mu):
    xp = tuple(x[k] + EMU[mu][k] for k in range(3))
    return gfun(x) * eta_ks(x, mu) * gfun(xp)


ok, _ = cocycle_holds(eta_gauged)
check(8, "gauge-transformed phases obey the same -1 cocycle", ok)

# recover the gauge function from r = eta' * eta by path products
r = {(x, mu): eta_gauged(x, mu) * eta_ks(x, mu) for x in sites()
     for mu in range(3)}
g_rec = {}
for x in sites():
    val = 1
    cur = (0, 0, 0)
    for mu in range(3):
        for _ in range(x[mu]):
            val *= r[(cur, mu)]
            cur = tuple(cur[k] + EMU[mu][k] for k in range(3))
    g_rec[x] = val
ok = all(g_rec[x] * g_rec[(0, 0, 0)] == gfun(x) * gfun((0, 0, 0))
         for x in sites())
check(9, "gauge function recovered from path products of r = eta'*eta "
         "(uniqueness of the KS gauge class on the simply connected box)",
      ok)

ok, nchk = cocycle_holds(lambda x, mu: 1)
check(10, "invalid all-plus sign law rejected by the -1 cocycle", not ok,
      "first violation found immediately")

# ============================ BZ-corner computation ====================
print("\n--- BZ-corner computation: kernel computed by SVD")


def build_staggered(eta_fun, apbc=False):
    D = np.zeros((N, N))
    for x in sites():
        for mu, e in enumerate(EMU):
            xp = tuple(x[k] + e[k] for k in range(3))
            xm = tuple(x[k] - e[k] for k in range(3))
            sp = -1.0 if (apbc and x[mu] == L - 1) else 1.0   # wrap x -> x+mu
            sm = -1.0 if (apbc and x[mu] == 0) else 1.0       # wrap x -> x-mu
            D[idx(*x), idx(*xp)] += 0.5 * eta_fun(x, mu) * sp
            D[idx(*x), idx(*xm)] -= 0.5 * eta_fun(x, mu) * sm
    return D


D = build_staggered(eta_ks)
ok = np.allclose(D, -D.T)
check(11, "one-component staggered operator D on the 4^3 torus is real "
          "antisymmetric (anti-Hermitian kinetic operator)", ok,
      f"matrix {N}x{N}")

u_svd, sv, vt = np.linalg.svd(D)
ker_dim = int(np.sum(sv < 1e-9))
ok = (ker_dim == 8)
check(12, "dim ker D = 8 (the 8 BZ-corner doubler modes), computed by SVD",
      ok, f"computed kernel dim = {ker_dim}, "
          f"spectral gap to first nonzero sv = {sv[N - ker_dim - 1]:.4f}"
      if ker_dim else f"computed kernel dim = {ker_dim}")
V = vt[N - ker_dim:].T if ker_dim else np.zeros((N, 0))     # ON kernel basis

# corner plane waves are exact null vectors
ok = True
for n1 in (0, 1):
    for n2 in (0, 1):
        for n3 in (0, 1):
            phi = np.array([(-1.0) ** (n1 * x[0] + n2 * x[1] + n3 * x[2])
                            for x in sites()])
            phi = phi / np.linalg.norm(phi)
            if np.linalg.norm(D @ phi) > TOL:
                ok = False
check(13, "all 8 corner plane waves phi_k, k in {0,pi}^3, are exact null "
          "vectors of D", ok)

# translations
Tmat = []
for mu, e in enumerate(EMU):
    T = np.zeros((N, N))
    for x in sites():
        xp = tuple(x[k] + e[k] for k in range(3))
        T[idx(*x), idx(*xp)] = 1.0          # (T f)(x) = f(x + mu)
    Tmat.append(T)

ok = all(np.linalg.norm(D @ (T @ V)) < 1e-8 for T in Tmat)
check(14, "ker D is invariant under all three elementary translations", ok)


def joint_characters(Vb, Ts):
    """Joint translation character triples on an invariant subspace."""
    Ms = [Vb.conj().T @ T @ Vb for T in Ts]
    comb = Ms[0] + 3 * Ms[1] + 9 * Ms[2]
    w, U = np.linalg.eigh((comb + comb.conj().T) / 2)
    trips = []
    vecs = []
    for j in range(Vb.shape[1]):
        v = U[:, j]
        trip = tuple(int(round(np.real(v.conj() @ (M @ v)))) for M in Ms)
        trips.append(trip)
        vecs.append(Vb @ v)
    return trips, vecs, Ms


trips, kvecs, Mker = joint_characters(V, Tmat)
ok = sorted(trips) == sorted(
    [(a, b, c) for a in (1, -1) for b in (1, -1) for c in (1, -1)])
check(15, "the 8 joint translation characters on ker D are exactly the "
          "taste cube {+-1}^3 (each triple once)", ok)

hw = [sum(1 for t in trip if t == -1) for trip in trips]
counts = [hw.count(k) for k in range(4)]
ok = (counts == [1, 3, 3, 1])
check(16, "Hamming-weight multiset on ker D = 1+3+3+1", ok,
      f"computed counts hw=0..3: {counts}; class-B interface to "
      "substep-3 Theorem 3")

# gauge-class invariance lemma: conjugate everything by G = diag(g)
G = np.diag([float(gfun(x)) for x in sites()])
Dg = G @ D @ G
ug, svg, vtg = np.linalg.svd(Dg)
ker_g = int(np.sum(svg < 1e-9))
Vg = vtg[N - ker_g:].T if ker_g else np.zeros((N, 0))
Tg = [G @ T @ G for T in Tmat]
trips_g, _, _ = joint_characters(Vg, Tg)
ok = (ker_g == 8 and sorted(trips_g) == sorted(trips))
check(17, "gauge-class invariance: conjugating (D, T_mu) by a Z2 gauge "
          "unitary preserves kernel dim and the joint-character multiset",
      ok, f"gauged kernel dim = {ker_g}")

# Kinetic-class residual exposure: naive 2-component operator has 16 corner modes
nabla = [(T - T.T) / 2.0 for T in Tmat]
Dnaive = sum(np.kron(SIG[mu], nabla[mu]) for mu in range(3))
svn = np.linalg.svd(Dnaive, compute_uv=False)
ker_naive = int(np.sum(svn < 1e-9))
ok = (ker_naive == 16)
check(18, "kinetic-class residual exposed: the 2-component naive operator (no "
          "site-local spin diagonalization) carries 16 corner modes, "
          "not 8", ok, f"computed naive kernel dim = {ker_naive}")
residual("the kinetic-class premise (naive-Dirac kinetic form + site-local "
         "spin diagonalization surface) is load-bearing:"
         " Quantum + Lattice alone admit the 2-component naive operator as well; "
         "substep-2 forcing is uniqueness WITHIN the declared class.")

# APBC convention residual
Dap = build_staggered(eta_ks, apbc=True)
sva = np.linalg.svd(Dap, compute_uv=False)
min_sv = float(sva.min())
ok = (min_sv > 0.1)
check(19, "boundary-holonomy residual exposed: under anti-periodic boundary condition the finite-L "
          "operator has NO exact zero modes (corner reading is "
          "dispersion-level / periodic-sector)", ok,
      f"min singular value APBC = {min_sv:.4f} > 0.1")
residual("boundary holonomy / APBC vs PBC selection is a framework "
         "convention input (substep-3 note premise APBC); the 1+3+3+1 "
         "corner grading itself is computed here in the periodic sector "
         "where corner momenta are exact lattice momenta.")

# ============================ hw=1 species surface =====================
print("\n--- hw=1 species surface: M_3(C), AC_lambda, labeling no-go")

# cyclic axis rotation U_R, (U f)(x) = f(R^-1 x), R(x1,x2,x3)=(x3,x1,x2)
UR = np.zeros((N, N))
for x in sites():
    xr = (x[1], x[2], x[0])                      # R^-1 x
    UR[idx(*x), idx(*xr)] = 1.0

ok = np.linalg.norm(D @ (UR @ V)) < 1e-8
check(20, "the cyclic axis rotation U_R preserves ker D", ok)

perm_ok = (np.allclose(UR @ Tmat[0] @ UR.T, Tmat[1])
           and np.allclose(UR @ Tmat[1] @ UR.T, Tmat[2])
           and np.allclose(UR @ Tmat[2] @ UR.T, Tmat[0]))
check(21, "conjugation by U_R cyclically permutes the translations: "
          "U T_1 U+ = T_2, U T_2 U+ = T_3, U T_3 U+ = T_1", perm_ok)

# action on corner labels: U_R maps character triple (a,b,c) -> rotated triple
lab_ok = True
cycle_hw1 = set()
for trip, v in zip(trips, kvecs):
    w = UR @ v
    new_trip = tuple(int(round(np.real(w.conj() @ (T @ w)))) for T in Tmat)
    expect = (trip[2], trip[0], trip[1])
    if new_trip != expect:
        lab_ok = False
    if sum(1 for t in trip if t == -1) == 1:
        cycle_hw1.add((trip, new_trip))
ok = lab_ok and all(t != nt for (t, nt) in cycle_hw1)
check(22, "U_R fixes the hw=0 and hw=3 corners and 3-cycles the hw=1 and "
          "hw=2 triplets (computed corner permutation)", ok,
      "hw preserved; hw=1 single 3-cycle")

# hw=1 ordered basis: corner with T_mu eigenvalue -1 on axis mu
hw1 = [None, None, None]
for trip, v in zip(trips, kvecs):
    if sum(1 for t in trip if t == -1) == 1:
        hw1[trip.index(-1)] = v
W = np.column_stack(hw1)
tmu = [W.conj().T @ T @ W for T in Tmat]
c3 = W.conj().T @ UR @ W

expected = [np.diag([-1.0, 1.0, 1.0]), np.diag([1.0, -1.0, 1.0]),
            np.diag([1.0, 1.0, -1.0])]
ok = all(np.allclose(tmu[m], expected[m]) for m in range(3))
check(23, "hw=1 joint characters are exactly (2a)-(2c) of the retained "
          "AC_lambda bridge note: (-1,+1,+1), (+1,-1,+1), (+1,+1,-1)", ok,
      "class-B interface to the AC_lambda simultaneous-diagonalization "
      "bridge")

ok = (np.allclose(c3.conj().T @ c3, np.eye(3))
      and (np.allclose(np.abs(c3), np.array([[0, 0, 1],
                                             [1, 0, 0],
                                             [0, 1, 0]], dtype=float))
           or np.allclose(np.abs(c3), np.array([[0, 1, 0],
                                                [0, 0, 1],
                                                [1, 0, 0]], dtype=float))))
check(24, "C_3 := U_R|_(hw=1) is a unitary 3-cycle on the corner basis",
      ok)


def algebra_dim(gens):
    """Dimension of the unital algebra generated by 3x3 matrices.

    Iteratively closes the linear span under multiplication until the
    span dimension is stable, then returns it.
    """
    basis = [np.eye(3, dtype=complex)] + [g.astype(complex) for g in gens]
    dim = np.linalg.matrix_rank(
        np.array([m.flatten() for m in basis]), tol=1e-9)
    while True:
        prods = [x @ y for x in basis for y in basis]
        stack = np.array([m.flatten() for m in basis + prods])
        u_, s_, vt_ = np.linalg.svd(stack)
        new_dim = int(np.sum(s_ > 1e-9))
        if new_dim == dim:
            return dim
        basis = [vt_[i].reshape(3, 3) for i in range(new_dim)]
        dim = new_dim


dim_alg = algebra_dim(tmu + [c3])
ok = (dim_alg == 9)
check(25, "the algebra generated by (T_1,T_2,T_3,C_3)|_(hw=1) has "
          "dimension 9 = dim M_3(C) (full matrix algebra)", ok,
      f"computed algebra dim = {dim_alg}")


def commutant_dim(gens):
    """Dim of {K : [K, g] = 0 for all g} inside M_3(C)."""
    rows = []
    for g in gens:
        gc = g.astype(complex)
        Lop = np.kron(gc, np.eye(3)) - np.kron(np.eye(3), gc.T)
        rows.append(Lop)
    A = np.vstack(rows)
    s_ = np.linalg.svd(A, compute_uv=False)
    return 9 - int(np.sum(s_ > 1e-9))


cdim_full = commutant_dim(tmu + [c3])
ok = (cdim_full == 1)
check(26, "commutant of the generated algebra is the scalars (dim 1): "
          "irreducible, hence simple, hence no proper exact quotient", ok,
      f"computed commutant dim = {cdim_full}")

cdim_trans = commutant_dim(tmu)
# also verify every commutant element is diagonal
rows = []
for g in tmu:
    gc = g.astype(complex)
    rows.append(np.kron(gc, np.eye(3)) - np.kron(np.eye(3), gc.T))
A = np.vstack(rows)
u_, s_, vt_ = np.linalg.svd(A)
null_vecs = vt_[int(np.sum(s_ > 1e-9)):]
diag_ok = all(
    np.allclose(nv.reshape(3, 3) - np.diag(np.diag(nv.reshape(3, 3))), 0)
    for nv in null_vecs)
ok = (cdim_trans == 3 and diag_ok)
check(27, "AC_lambda corollary computed: {K : [K,T_mu]=0 on hw=1} is "
          "exactly the diagonal algebra, dim 3", ok,
      f"computed translation-commutant dim = {cdim_trans}, all diagonal")

# labeling no-go witness (AC_phi_lambda):
# (i)  the computed structure is C_3-covariant: conjugation by C_3
#      permutes the translation generators cyclically on hw=1;
conj_ok = (np.allclose(c3 @ tmu[0] @ c3.conj().T, tmu[1])
           and np.allclose(c3 @ tmu[1] @ c3.conj().T, tmu[2])
           and np.allclose(c3 @ tmu[2] @ c3.conj().T, tmu[0]))
# (ii) the three corner states form a single C_3 orbit (transitivity);
orbit = {0}
col = 0
for _ in range(3):
    col = int(np.argmax(np.abs(c3[:, col])))
    orbit.add(col)
# (iii) every C_3-equivariant Hermitian H equidistributes over the orbit
a_c, b_c = 0.7, 0.2 + 0.1j
H = a_c * np.eye(3) + b_c * c3 + np.conj(b_c) * c3.conj().T
diags = np.real(np.diag(H))
equi_ok = np.allclose(diags, np.trace(np.real(H)) / 3.0)
ok = conj_ok and (orbit == {0, 1, 2}) and equi_ok
check(28, "labeling no-go witness computed: the structure is C_3-covariant,"
          " the three hw=1 states form one C_3 orbit, and every "
          "C_3-equivariant Hermitian equidistributes over it -- so no "
          "structure-derived functional separates the corners", ok,
      f"diag(H) = {diags.round(6).tolist()}, Tr(H)/3 = "
      f"{np.trace(np.real(H)) / 3.0:.6f}")

# pi_A vs pi_B indistinguishability on concrete propositions
piA = {0: "l1", 1: "l2", 2: "l3"}
piB = {0: "l2", 1: "l3", 2: "l1"}          # = piA after one C_3 step


def prop_values(pi):
    """Minimal-axiom-baseline-derivable proposition values under a labeling pi."""
    p1 = sorted(round(float(np.real(H[i, i])), 9) for i in pi)   # equipart.
    p2 = (cdim_trans == 3 and diag_ok)                           # AC_lambda
    p3 = (dim_alg == 9 and cdim_full == 1)                       # M3/NQ
    return (p1, p2, p3)


ok = prop_values(piA) == prop_values(piB)
check(29, "pi_A vs pi_B counter-model: all minimal-axiom-baseline-derivable proposition "
          "values agree under both labelings (substep-4 labeling no-go "
          "witness)", ok)

# The labeling convention is genuinely distinguishing: generic C_3-equivariant H has 3
# distinct eigenvalues, so a sorted-order convention fixes a unique pi
evals = np.sort(np.linalg.eigvalsh(H))
gaps = np.diff(evals)
ok = bool(np.all(gaps > 1e-6))
check(30, "labeling convention is a genuinely distinguishing external"
          " premise: generic C_3-equivariant H has 3 distinct eigenvalues,"
          " so sorted order fixes a unique bijection", ok,
      f"eigenvalues = {evals.round(6).tolist()}")
residual("AC_phi_lambda: the labeled {e,mu,tau} species bijection is NOT "
         "derivable from the minimal axiom baseline (no-go, computed witness above); it enters "
         "only through the labeling-convention external premise. "
         "This synthesis therefore closes the realization at the bounded "
         "tier with the generation labeling carried as convention.")

# ============================ composition summary ======================
print("\n--- composition summary")

ok = (ker_dim == 8 and counts == [1, 3, 3, 1] and dim_alg == 9
      and cdim_full == 1 and cdim_trans == 3 and scalar_ok)
check(31, "composition closes end-to-end on the finite instantiation: "
          "Cl(3) dim-2 module -> KS phases (extracted) -> 8 corner modes "
          "-> 1+3+3+1 -> hw=1 M_3(C) (dim 9, irreducible) -> AC_lambda "
          "diagonal commutant -> labeling no-go witness", ok)

print()
print(f"TOTAL: PASS={_pass} FAIL={_fail}")
if _fail == 0:
    print("VERDICT: bounded synthesis composition VERIFIED on the finite")
    print("         instantiation; declared-open residuals listed above")
    print("         (kinetic-class premise, spin-statistics support tier, boundary")
    print("         holonomy convention, AC_phi_lambda labeling premise).")
sys.exit(0 if _fail == 0 else 1)
