#!/usr/bin/env python3
"""Cartan-valued cross-plane pairing and the Weyl-frame theorems: the
rank-2 flux pairing is diagonal-Weyl-invariant joint-orbit data, provably
underdetermined by per-plane-independent Weyl orbits; its values are
(1/3)Z with the fractional part a function of triality classes alone, and
integer with odd support on root-valued fluxes.

Paired note:
docs/THETA_CARTAN_VALUED_CROSS_PLANE_PAIRING_DIAGONAL_WEYL_FRAME_THEOREMS_AND_TRIALITY_FRACTIONAL_VALUES_BOUNDED_THEOREM_NOTE_2026-07-02.md

Class-A finite checks only: exact rational linear algebra on the su(3)
weight lattice (Gram form, Weyl group), exact integer cochain algebra on the
cubical complex of T^4_2 (boundary maps, cubical cup products), and finite
sector-sum arithmetic. Deterministic pseudo-random integer draws from a
fixed seed test exact identities. No fits, no external comparators, no
measured values.

Sections:
  A. Weight-lattice ground: Gram form G (|alpha|^2 = 2 normalization),
     Cartan integers <alpha_i, omega_j> = delta_ij, Weyl group of order 6
     generated by the two simple reflections, G-invariance of W, zero
     W-fixed subspace, dominant representatives biject with regular-orbit
     points.
  B. Cartan-valued cochain pairing on T^4_2: Q_G(n) = (1/2) sum_ab G_ab
     n^(a) u n^(b) on rank-2 closed integer 2-cochains: componentwise class
     invariance, cross-plane structure, reduction to the Gram-intersection
     of flux classes, reflection-oddness.
  C. Value structure: Q_G in (1/3)Z on weight-valued fluxes; root-lattice
     shifts change Q_G by integers, so Q_G mod 1 is a function of the
     triality classes alone (3 x 3 table verified over multiple
     representatives); Q_G in Z on root-valued fluxes with an ODD witness
     Q_G = -1 at (alpha_1, alpha_2) complementary unit fluxes.
  D. Frame theorems: Q_G is invariant under the DIAGONAL Weyl action on all
     flux components; per-plane-INDEPENDENT Weyl action changes Q_G
     (explicit witnesses) — per-plane orbit data underdetermine the
     pairing; the orbit-invariant content of a single flux cannot resolve
     it (both members of a breaking pair are in the same per-plane orbits).
  E. Two-dimensional joint-frame witness: on the glued 2D dual the sector
     label is a dominant weight, i.e. exactly one W-orbit representative —
     the glued label IS frame-free orbit data (block-2/4 mechanism).
  F. Interface arithmetic on the integer (root-valued) subsector: positive
     weight family gives Z_Q > 0 paired with odd support; at theta = pi the
     odd sectors carry negative weight; fractional sectors reported as
     arithmetic only.

Expected close: TOTAL: PASS=21 FAIL=0
"""
from __future__ import annotations

from fractions import Fraction
from itertools import combinations, permutations

import numpy as np

PASS = 0
FAIL = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS, FAIL
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS += 1
    else:
        FAIL += 1
    print(f"  [{status}] {name}")
    if detail:
        print(f"         {detail}")


RNG = np.random.default_rng(23)

# ---------------------------------------------------------------------------
# Section A: weight-lattice ground (exact rationals)
# ---------------------------------------------------------------------------
print("Section A: su(3) weight lattice, Gram form, Weyl group")

G = [[Fraction(2, 3), Fraction(1, 3)], [Fraction(1, 3), Fraction(2, 3)]]
A1 = (2, -1)   # alpha_1 in fundamental-weight coordinates
A2 = (-1, 2)   # alpha_2
W1 = (1, 0)    # omega_1
W2 = (0, 1)    # omega_2


def pair(x, y) -> Fraction:
    return sum(G[i][j] * x[i] * y[j] for i in range(2) for j in range(2))


check("A1 normalization: |alpha_1|^2 = |alpha_2|^2 = 2, <alpha_1,alpha_2> = -1",
      pair(A1, A1) == 2 and pair(A2, A2) == 2 and pair(A1, A2) == -1)
check("A2 Cartan integers: <alpha_i, omega_j> = delta_ij",
      pair(A1, W1) == 1 and pair(A1, W2) == 0
      and pair(A2, W1) == 0 and pair(A2, W2) == 1)
check("A3 weight-weight pairings are thirds: <w1,w1> = 2/3, <w1,w2> = 1/3",
      pair(W1, W1) == Fraction(2, 3) and pair(W1, W2) == Fraction(1, 3))


def s1(v):
    # s_alpha(v) = v - <v, alpha> alpha  (simply-laced, alpha-check = alpha)
    c = pair(v, A1)
    return (v[0] - c * A1[0], v[1] - c * A1[1])


def s2(v):
    c = pair(v, A2)
    return (v[0] - c * A2[0], v[1] - c * A2[1])


def close_group(gens):
    elems = [lambda v: v]
    reprs = {((1, 0), (0, 1))}
    frontier = [lambda v: v]
    while frontier:
        new = []
        for f in frontier:
            for g in gens:
                h = (lambda f=f, g=g: (lambda v: g(f(v))))()
                key = (h((1, 0)), h((0, 1)))
                if key not in reprs:
                    reprs.add(key)
                    elems.append(h)
                    new.append(h)
        frontier = new
    return elems


W_ELEMS = close_group([s1, s2])
check("A4 the group generated by the two simple reflections has order 6",
      len(W_ELEMS) == 6)

ok_inv = True
for w in W_ELEMS:
    for v in [A1, A2, W1, W2, (3, -2), (1, 4)]:
        for u in [W1, (2, 1), (-1, 3)]:
            ok_inv = ok_inv and pair(w(v), w(u)) == pair(v, u)
check("A5 the Gram form is W-invariant: <wv, wu> = <v, u> for all six w",
      ok_inv)

avg = [[Fraction(0)] * 2 for _ in range(2)]
for w in W_ELEMS:
    e1 = w((1, 0))
    e2 = w((0, 1))
    for i in range(2):
        avg[i][0] += Fraction(e1[i], 6)
        avg[i][1] += Fraction(e2[i], 6)
check("A6 the W-average is exactly the zero map (no fixed direction)",
      all(avg[i][j] == 0 for i in range(2) for j in range(2)))

dom_ok = True
for a in range(-4, 5):
    for b in range(-4, 5):
        v = (a, b)
        if pair(v, A1) == 0 or pair(v, A2) == 0 or pair(v, (1, 1)) == 0:
            continue  # non-regular (some Weyl wall) — skip
        orbit = {w(v) for w in W_ELEMS}
        doms = [u for u in orbit if u[0] > 0 and u[1] > 0]
        dom_ok = dom_ok and len(doms) == 1
check("A7 every regular orbit in the window contains exactly one dominant"
      " representative (dominant labels = W-orbits)", dom_ok)

# ---------------------------------------------------------------------------
# Section B: Cartan-valued cochain pairing on T^4_2
# ---------------------------------------------------------------------------
print("Section B: Cartan-valued cup pairing on T^4")

D = 4
L = 2


def cells(k):
    out = []
    sites = [tuple(s) for s in np.ndindex(*(L,) * D)]
    for S in combinations(range(D), k):
        for x in sites:
            out.append((x, S))
    return out


CI = {k: (cells(k), {c: i for i, c in enumerate(cells(k))})
      for k in range(0, D + 1)}


def shift(x, mu):
    y = list(x)
    y[mu] = (y[mu] + 1) % L
    return tuple(y)


def d_matrix(k):
    _, ik = CI[k]
    _, ik1 = CI[k + 1]
    M = np.zeros((len(ik1), len(ik)), dtype=np.int64)
    for (x, S), r in ik1.items():
        for j, mu in enumerate(S):
            Srem = tuple(m for m in S if m != mu)
            sgn = (-1) ** j
            M[r, ik[(shift(x, mu), Srem)]] += sgn
            M[r, ik[(x, Srem)]] -= sgn
    return M


DM = {k: d_matrix(k) for k in range(0, D)}


def cup22(a, b):
    _, ik4 = CI[4]
    _, ik2 = CI[2]
    out = np.zeros(len(ik4), dtype=np.int64)
    for (x, S), r in ik4.items():
        tot = 0
        for S1 in combinations(S, 2):
            S2 = tuple(m for m in S if m not in S1)
            perm = list(S1) + list(S2)
            inv = sum(1 for i in range(4) for j in range(i + 1, 4)
                      if perm[i] > perm[j])
            y = x
            for mu in S1:
                y = shift(y, mu)
            tot += ((-1) ** inv) * int(a[ik2[(x, S1)]]) * int(b[ik2[(y, S2)]])
        out[r] = tot
    return out


PLANES = list(combinations(range(D), 2))


def flux_rep(mu, nu):
    v = np.zeros(len(CI[2][0]), dtype=np.int64)
    for (x, S), i in CI[2][1].items():
        if S == (mu, nu) and x[mu] == 0 and x[nu] == 0:
            v[i] = 1
    return v


REPS = {pl: flux_rep(*pl) for pl in PLANES}


def qg(n1, n2):
    """Q_G for the rank-2 cochain with weight-coordinate components n1, n2:
    (1/2) sum_ab G_ab n^a u n^b, exact rational."""
    c11 = int(np.sum(cup22(n1, n1)))
    c12 = int(np.sum(cup22(n1, n2)))
    c21 = int(np.sum(cup22(n2, n1)))
    c22 = int(np.sum(cup22(n2, n2)))
    return (G[0][0] * c11 + G[0][1] * (c12 + c21) + G[1][1] * c22) / 2


def flux_cochain(assign):
    """assign: plane -> weight-coordinate pair (a, b). Returns (n1, n2)."""
    n1 = np.zeros(len(CI[2][0]), dtype=np.int64)
    n2 = np.zeros(len(CI[2][0]), dtype=np.int64)
    for pl, (a, b) in assign.items():
        n1 = n1 + a * REPS[pl]
        n2 = n2 + b * REPS[pl]
    return n1, n2


def q_flux(assign):
    """Gram-intersection of the flux classes directly:
    Q = sum over complementary pairs, with block-3 signs."""
    comp = {(0, 1): (2, 3), (0, 2): (1, 3), (0, 3): (1, 2)}
    sgn = {(0, 1): 1, (0, 2): -1, (0, 3): 1}
    tot = Fraction(0)
    zero = (0, 0)
    for p, pc in comp.items():
        tot += sgn[p] * pair(assign.get(p, zero), assign.get(pc, zero))
    return tot


ok_red = True
for _ in range(6):
    assign = {pl: (int(RNG.integers(-2, 3)), int(RNG.integers(-2, 3)))
              for pl in PLANES}
    n1, n2 = flux_cochain(assign)
    ok_red = ok_red and (qg(n1, n2) == q_flux(assign))
check("B1 cochain pairing reduces to the Gram-intersection of flux classes"
      " (random rank-2 flux assignments)", ok_red)

ok_cls = True
for _ in range(4):
    assign = {pl: (int(RNG.integers(-2, 3)), int(RNG.integers(-2, 3)))
              for pl in PLANES}
    n1, n2 = flux_cochain(assign)
    lam1 = RNG.integers(-1, 2, size=len(CI[1][0]))
    lam2 = RNG.integers(-1, 2, size=len(CI[1][0]))
    ok_cls = ok_cls and (qg(n1 + DM[1] @ lam1, n2 + DM[1] @ lam2)
                         == qg(n1, n2))
check("B2 componentwise class invariance: Q_G(n + d lambda) = Q_G(n) for"
      " independent shifts of both weight components", ok_cls)

ok_cross = all(qg(*flux_cochain({pl: (a, b)})) == 0
               for pl in PLANES for (a, b) in [(1, 0), (2, -1), (1, 3)])
check("B3 cross-plane structure: every single-plane rank-2 flux has Q_G = 0",
      ok_cross)


def reflect2(v, axis=0):
    out = np.zeros_like(v)
    for (x, S), i in CI[2][1].items():
        y = list(x)
        y[axis] = (-y[axis]) % L
        sgn = 1
        if axis in S:
            y[axis] = (y[axis] - 1) % L
            sgn = -1
        out[i] = sgn * v[CI[2][1][(tuple(y), S)]]
    return out


assign0 = {(0, 1): (2, -1), (2, 3): (-1, 2), (0, 2): (1, 0), (1, 3): (0, 1)}
n1a, n2a = flux_cochain(assign0)
check("B4 coordinate reflection flips Q_G (pairing mechanism intact at"
      " rank 2)",
      qg(reflect2(n1a), reflect2(n2a)) == -qg(n1a, n2a),
      f"Q = {qg(n1a, n2a)}, reflected = {qg(reflect2(n1a), reflect2(n2a))}")

# ---------------------------------------------------------------------------
# Section C: value structure
# ---------------------------------------------------------------------------
print("Section C: value structure — thirds, triality, integer odd support")

q_ww = q_flux({(0, 1): W1, (2, 3): W1})
q_ww2 = q_flux({(0, 1): W1, (2, 3): W2})
check("C1 weight-valued fluxes give thirds: Q(w1,w1 pair) = 2/3,"
      " Q(w1,w2 pair) = 1/3",
      q_ww == Fraction(2, 3) and q_ww2 == Fraction(1, 3))

def triality(v):
    return (v[0] - v[1]) % 3


ok_root_shift = True
ok_tri_table = True
table = {}
for _ in range(60):
    va = (int(RNG.integers(-3, 4)), int(RNG.integers(-3, 4)))
    vb = (int(RNG.integers(-3, 4)), int(RNG.integers(-3, 4)))
    q0 = q_flux({(0, 1): va, (2, 3): vb})
    # shift va by a random root-lattice vector
    m, n = int(RNG.integers(-2, 3)), int(RNG.integers(-2, 3))
    gamma = (2 * m - n, -m + 2 * n)
    q1 = q_flux({(0, 1): (va[0] + gamma[0], va[1] + gamma[1]), (2, 3): vb})
    ok_root_shift = ok_root_shift and (q1 - q0).denominator == 1
    key = (triality(va), triality(vb))
    frac = q0 % 1
    if key in table:
        ok_tri_table = ok_tri_table and table[key] == frac
    else:
        table[key] = frac
check("C2 root-lattice shifts change Q by integers: Q mod 1 is a function"
      " of the triality classes alone", ok_root_shift and ok_tri_table,
      "table (t,t') -> Q mod 1: " + ", ".join(
          f"{k}:{v}" for k, v in sorted(table.items())))

check("C3 the fractional table is the mod-3 center pairing: Q mod 1 ="
      " (-t t'/3) mod 1 equivalently (2 t t'/3) mod 1",
      all(v == Fraction(2 * k[0] * k[1] % 3, 3) for k, v in table.items()))

q_roots = q_flux({(0, 1): A1, (2, 3): A2})
ok_int_root = True
for _ in range(20):
    m, n = int(RNG.integers(-2, 3)), int(RNG.integers(-2, 3))
    m2, n2 = int(RNG.integers(-2, 3)), int(RNG.integers(-2, 3))
    ra = (2 * m - n, -m + 2 * n)
    rb = (2 * m2 - n2, -m2 + 2 * n2)
    qv = q_flux({(0, 1): ra, (2, 3): rb})
    ok_int_root = ok_int_root and qv.denominator == 1
check("C4 root-valued fluxes give integer Q; the (alpha_1, alpha_2) pair is"
      " an ODD witness: Q = -1",
      ok_int_root and q_roots == -1)

# ---------------------------------------------------------------------------
# Section D: frame theorems
# ---------------------------------------------------------------------------
print("Section D: diagonal vs independent Weyl frames")

ok_diag = True
for _ in range(6):
    assign = {pl: (int(RNG.integers(-2, 3)), int(RNG.integers(-2, 3)))
              for pl in PLANES}
    q0 = q_flux(assign)
    for w in W_ELEMS:
        wa = {pl: w(v) for pl, v in assign.items()}
        ok_diag = ok_diag and q_flux(wa) == q0
check("D1 DIAGONAL Weyl action (one frame for all planes) leaves Q"
      " invariant: the pairing is joint-orbit data", ok_diag)

base = {(0, 1): A1, (2, 3): A2}
q_base = q_flux(base)
breaks = []
for w in W_ELEMS:
    alt = {(0, 1): w(A1), (2, 3): A2}
    if q_flux(alt) != q_base:
        breaks.append((w(A1), q_flux(alt)))
check("D2 INDEPENDENT per-plane Weyl action changes Q (explicit witnesses):"
      " per-plane orbit data underdetermine the pairing",
      len(breaks) >= 2,
      f"base Q = {q_base}; e.g. rotated-first-slot values "
      + ", ".join(f"{v}->{q}" for v, q in breaks[:3]))

orbit_a1 = {w(A1) for w in W_ELEMS}
vals_within_orbit = {q_flux({(0, 1): v, (2, 3): A2}) for v in orbit_a1}
check("D3 the breaking pair lives inside ONE per-plane orbit: the same"
      " single-flux orbit yields multiple Q values",
      len(vals_within_orbit) >= 3,
      f"Q values over the alpha_1 orbit (second slot fixed): "
      f"{sorted(str(v) for v in vals_within_orbit)}")

# ---------------------------------------------------------------------------
# Section E: 2D joint-frame witness
# ---------------------------------------------------------------------------
print("Section E: 2D glued dual label is frame-free orbit data")

check("E1 dominant labels biject with regular W-orbits (A7) and the glued"
      " 2D sector label is a dominant weight: the matched label IS the"
      " orbit invariant — no frame choice enters the 2D sector data",
      dom_ok)

# ---------------------------------------------------------------------------
# Section F: interface arithmetic on the integer subsector
# ---------------------------------------------------------------------------
print("Section F: interface arithmetic (root-valued integer subsector)")

roots_window = []
for m in range(-1, 2):
    for n in range(-1, 2):
        roots_window.append((2 * m - n, -m + 2 * n))
ZQ = {}
for ra in roots_window:
    for rb in roots_window:
        q = q_flux({(0, 1): ra, (2, 3): rb})
        assert q.denominator == 1
        wgt = float(np.exp(-1.0 * (pair(ra, ra) + pair(rb, rb))))
        ZQ[int(q)] = ZQ.get(int(q), 0.0) + wgt
tot = sum(ZQ.values())
ZQ = {k: v / tot for k, v in ZQ.items()}
odd_ok = any(k % 2 == 1 and ZQ[k] > 0 for k in ZQ)
paired_ok = all(abs(ZQ[k] - ZQ.get(-k, 0.0)) < 1e-14 for k in ZQ)
neg_odd = all((1 if k % 2 == 0 else -1) * ZQ[k] < 0 for k in ZQ if k % 2 == 1)
check("F1 positive weight family on root-valued fluxes: Z_Q > 0 with odd-Q"
      " support and pairing Z_Q = Z_-Q",
      odd_ok and paired_ok and all(v > 0 for v in ZQ.values()),
      f"Q populated: {sorted(ZQ)}")
check("F2 at theta = pi every odd-Q sector carries negative weight; at"
      " theta = 0 all weights nonnegative", neg_odd)

print(f"TOTAL: PASS={PASS} FAIL={FAIL}")
