#!/usr/bin/env python3
"""The gluing flow does not source the theta-parity pair term: link
integration of real class-weight seeds produces plane-blind pair couplings,
and plane-blind couplings vanish identically under the epsilon assembly —
while phased seeds are transported (orientation-sensitively), never created.
The theta admission's gauge-side content localizes at the SEED class.

Paired note:
docs/THETA_GLUING_FLOW_NONSOURCING_PAIR_LEVEL_SEED_LOCALIZATION_BOUNDED_THEOREM_NOTE_2026-07-02.md

Class-A finite checks only: exact invariant-projector evaluation (joint null
space of the Lie-algebra action; no group integration), exact epsilon
combinatorics, and discriminating contrasts (every inheritance gate is paired
with a phased-seed case that breaks it, so an insensitive gate cannot pass).
Deterministic (fixed seed); no fits, no external comparators, no measured
values, no Monte Carlo.

Sections:
  A. Symmetry inheritance with discriminating contrast: the real-seed star
     is invariant under simultaneous dagger and bar (the internal images of
     orientation reversal), while the SAME gates FAIL for phased seeds
     (alpha -> -alpha), so the checks discriminate.
  B. Plane-blindness and the epsilon cancellation: the glued pair object
     equals its universal channel form (plane labels never enter); the
     epsilon-assembled sum of plane-uniform (flow-generated) pair couplings
     is EXACTLY zero, while the epsilon-carrying (orientation-anisotropic)
     assembly of the same values is nonzero — the theta-parity pair term
     cannot be generated by a plane-blind mechanism.
  C. Seed transport: real seeds give real effective couplings (reality
     propagates); phased seeds transport orientation-sensitively — the
     same-orientation channel compounds the phase (e^{2 i alpha}) while the
     opposed-orientation channel cancels it — the flow moves seed oddness,
     it does not create it.

Expected close: TOTAL: PASS=9 FAIL=0
"""
from __future__ import annotations

from itertools import product

import numpy as np

PASS = 0
FAIL = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global PASS, FAIL
    status = "PASS" if condition else "FAIL"
    if condition:
        PASS += 1
    else:
        FAIL += 1
    print(f"  [{status}] {name}")
    if detail:
        print(f"         {detail}")


RNG = np.random.default_rng(7)


def rand_su3(n: int = 1):
    out = []
    for _ in range(n):
        z = (RNG.normal(size=(3, 3)) + 1j * RNG.normal(size=(3, 3))) / np.sqrt(2)
        q, r = np.linalg.qr(z)
        q = q @ np.diag(np.diag(r) / np.abs(np.diag(r)))
        q = q / np.linalg.det(q) ** (1 / 3)
        out.append(q)
    return out


LAM = np.zeros((8, 3, 3), dtype=complex)
LAM[0][0, 1] = LAM[0][1, 0] = 1
LAM[1][0, 1] = -1j
LAM[1][1, 0] = 1j
LAM[2][0, 0] = 1
LAM[2][1, 1] = -1
LAM[3][0, 2] = LAM[3][2, 0] = 1
LAM[4][0, 2] = -1j
LAM[4][2, 0] = 1j
LAM[5][1, 2] = LAM[5][2, 1] = 1
LAM[6][1, 2] = -1j
LAM[6][2, 1] = 1j
LAM[7][0, 0] = LAM[7][1, 1] = 1 / np.sqrt(3)
LAM[7][2, 2] = -2 / np.sqrt(3)
GM = [LAM[i] for i in range(8)]


def dim_of(r: str) -> int:
    return 1 if r == "1" else 3


def rep_mat(r: str, g: np.ndarray) -> np.ndarray:
    if r == "1":
        return np.ones((1, 1), dtype=complex)
    return g if r == "F" else np.conj(g)


def rep_gen(r: str, X: np.ndarray) -> np.ndarray:
    if r == "1":
        return np.zeros((1, 1), dtype=complex)
    return X if r == "F" else -np.conj(X)


def kron3(a, b, c) -> np.ndarray:
    return np.kron(np.kron(a, b), c)


def invariant_projector(R: str, S: str, T: str) -> np.ndarray:
    dR, dS, dT = dim_of(R), dim_of(S), dim_of(T)
    rows = []
    for X in GM:
        g3 = -np.conj(rep_gen(T, X))
        rows.append(kron3(rep_gen(R, X), np.eye(dS), np.eye(dT))
                    + kron3(np.eye(dR), rep_gen(S, X), np.eye(dT))
                    + kron3(np.eye(dR), np.eye(dS), g3))
    A = np.vstack(rows)
    _, s, vh = np.linalg.svd(A)
    null = vh[int(np.sum(s > 1e-9)):].conj().T
    return null @ null.conj().T


def I_RST(R: str, S: str, T: str, S1, S2, S3) -> complex:
    Pi = invariant_projector(R, S, T)
    M = kron3(rep_mat(R, S1), rep_mat(S, S2), rep_mat(T, S3).T)
    return complex(np.trace(Pi @ M))


REPS3 = ["1", "F", "Fb"]
CBASE = 0.35


def cw(r: str, alpha: float) -> complex:
    if r == "1":
        return 1.0
    return CBASE * np.exp(1j * alpha) if r == "F" else CBASE * np.exp(-1j * alpha)


def star(S1, S2, S3, alpha: float) -> complex:
    tot = 0.0 + 0j
    for (R, S, T) in product(REPS3, repeat=3):
        tot += cw(R, alpha) * cw(S, alpha) * cw(T, alpha) \
            * I_RST(R, S, T, S1, S2, S3)
    return complex(tot)


def chi_F(M: np.ndarray) -> complex:
    return complex(np.trace(M))


def pair_glued(S1, S2, alpha: float, same_orientation: bool) -> complex:
    """Exact glued pair via channel identities:
    same-orientation: Int dV w(V S1) w(V S2)
      = sum_R c_R(a) c_Rbar(a) chi_R(S2^dag S1)/d_R
    opposed:          Int dV w(V S1) w(V^dag S2)
      = sum_R c_R(a) c_R(a) chi_R(S2 S1)/d_R."""
    comp = (S2.conj().T @ S1) if same_orientation else (S2 @ S1)
    tot = 1.0 + 0j  # trivial channel: c_1 * c_1
    for R in ["F", "Fb"]:
        Rb = "Fb" if R == "F" else "F"
        cA = cw(R, alpha)
        cB = cw(Rb, alpha) if same_orientation else cw(R, alpha)
        ch = chi_F(comp) if R == "F" else np.conj(chi_F(comp))
        tot += cA * cB * ch / 3.0
    return complex(tot)


# ---------------------------------------------------------------------------
# Section A: symmetry inheritance with discriminating contrast
# ---------------------------------------------------------------------------
print("Section A: inheritance under the flow (with phased-seed contrast)")

S1, S2, S3 = rand_su3(3)

G_real = star(S1, S2, S3, 0.0)
G_real_dag = star(S1.conj().T, S2.conj().T, S3.conj().T, 0.0)
G_ph = star(S1, S2, S3, 0.7)
G_ph_dag = star(S1.conj().T, S2.conj().T, S3.conj().T, 0.7)
check("A1 real seeds: the glued star is invariant under simultaneous dagger"
      " (the internal image of orientation reversal); the SAME gate FAILS"
      " for phased seeds (discriminating contrast)",
      abs(G_real_dag - G_real) < 1e-12 and abs(G_ph_dag - G_ph) > 1e-3,
      f"real diff = {abs(G_real_dag - G_real):.2e},"
      f" phased diff = {abs(G_ph_dag - G_ph):.4f}")

G_real_bar = star(S1.conj(), S2.conj(), S3.conj(), 0.0)
G_ph_bar = star(S1.conj(), S2.conj(), S3.conj(), 0.7)
check("A2 real seeds: invariant under simultaneous bar; phased seeds break"
      " it (contrast)",
      abs(G_real_bar - G_real) < 1e-12 and abs(G_ph_bar - G_ph) > 1e-3)

check("A3 the phased-seed images equal the seed with alpha -> -alpha"
      " (the flow maps the flip onto the SEED parameter, not onto new"
      " structure)",
      abs(G_ph_dag - star(S1, S2, S3, -0.7)) < 1e-12
      and abs(G_ph_bar - star(S1, S2, S3, -0.7)) < 1e-12)

# ---------------------------------------------------------------------------
# Section B: plane-blindness and the epsilon cancellation
# ---------------------------------------------------------------------------
print("Section B: plane-blind couplings die under the epsilon assembly")

Pi_pair = invariant_projector("F", "Fb", "1")
g_proj = complex(np.trace(Pi_pair @ kron3(rep_mat("F", S1),
                                          rep_mat("Fb", S2),
                                          np.ones((1, 1), dtype=complex))))
# the (F,Fb,1) channel of the star at alpha=0 is c^2 * chi_F(...)-structure;
# verify the glued pair closed form against the projector channel sum:
g_channel = pair_glued(S1, S2, 0.0, same_orientation=True)
g_full = complex(sum(cw(R, 0.0) * cw(S, 0.0)
                     * I_RST(R, S, "1", S1, S2, np.eye(3))
                     for (R, S) in product(REPS3, repeat=2)))
check("B1 the glued pair equals its universal channel form (plane labels"
      " never enter the functional): projector sum vs closed form",
      abs(g_full - g_channel) < 1e-12,
      f"glued pair = {g_channel.real:.8f}")


def eps4(a: int, b: int, c: int, d: int) -> int:
    p = [a, b, c, d]
    if len(set(p)) < 4:
        return 0
    sign = 1
    for i in range(4):
        for j in range(i + 1, 4):
            if p[i] > p[j]:
                sign = -sign
    return sign


ok_sum = all(sum(eps4(mu, nu, r, s) for r in range(4) for s in range(4)) == 0
             for mu in range(4) for nu in range(4) if nu != mu)
check("B2 sum over (rho,sigma) of eps_{mu nu rho sigma} = 0 for every plane"
      " (re-earned)", ok_sum)

K_uniform = g_channel.real  # the flow-generated coupling: SAME for all pairs
T_flow = sum(eps4(m, n, r, s) * K_uniform
             for m in range(4) for n in range(4)
             for r in range(4) for s in range(4)
             if n != m and s != r)
# contrast: orientation-anisotropic (epsilon-carrying) couplings do NOT die
T_aniso = sum(eps4(m, n, r, s) * (eps4(m, n, r, s) * K_uniform)
              for m in range(4) for n in range(4)
              for r in range(4) for s in range(4)
              if n != m and s != r)
check("B3 the epsilon-assembled sum of plane-uniform (flow-generated) pair"
      " couplings is EXACTLY zero, while the same values with"
      " epsilon-carrying (orientation-anisotropic) couplings survive:"
      " a plane-blind mechanism cannot generate the theta-parity pair term",
      T_flow == 0 and abs(T_aniso) > 1.0,
      f"flow assembly = {T_flow}, anisotropic contrast = {T_aniso:.4f}")

# ---------------------------------------------------------------------------
# Section C: seed transport
# ---------------------------------------------------------------------------
print("Section C: reality propagates; phases transport, are not created")

ok_real_prop = True
for (R, S) in product(REPS3, repeat=2):
    c_eff = cw(R, 0.0) * cw(S, 0.0)
    ok_real_prop = ok_real_prop and abs(complex(c_eff).imag) < 1e-15
g_vals = [pair_glued(*rand_su3(2), 0.0, so) for so in (True, False)]
check("C1 real seeds give real effective couplings and real glued pair"
      " values (reality propagates through the flow)",
      ok_real_prop and all(abs(v.imag) < 1e-12 for v in g_vals))

al = 0.7
gA = pair_glued(S1, S2, al, same_orientation=True)
gA0 = pair_glued(S1, S2, 0.0, same_orientation=True)
check("C2 same-orientation channel: the seed phases CANCEL"
      " (c e^{ia} pairs with c e^{-ia}): glued object equals the alpha = 0"
      " value — no oddness deposited in this channel",
      abs(gA - gA0) < 1e-12)

gB = pair_glued(S1, S2, al, same_orientation=False)
comp = S2 @ S1
pred = 1.0 + CBASE ** 2 * (np.exp(2j * al) * chi_F(comp)
                           + np.exp(-2j * al) * np.conj(chi_F(comp))) / 3.0
check("C3 opposed-orientation channel: the seed phase COMPOUNDS"
      " (e^{2 i alpha} on the composite character): the flow transports"
      " seed oddness orientation-sensitively — it moves theta content, it"
      " does not create it",
      abs(gB - pred) < 1e-12 and abs(gB - pair_glued(S1, S2, 0.0, False)) > 1e-3,
      f"|alpha-shift of the opposed channel| ="
      f" {abs(gB - pair_glued(S1, S2, 0.0, False)):.4f}")

print(f"TOTAL: PASS={PASS} FAIL={FAIL}")
