from pathlib import Path
import subprocess,json,hashlib
O=Path('/private/tmp/review-drain-20260915');R=O/'pr8010';H='f29251ea68ba2bcd96c807881eae7bc8c6cfd48e';B='5deabeb698a27c2c3f68c5df685af2521ef15307'
def git(*a):return subprocess.check_output(['git','-C',str(R),*a]).decode().strip()
def sha(b):return hashlib.sha256(b).hexdigest()
paths=git('diff','--cached','--name-only').splitlines();assert len(paths)==18;assert not git('diff','--name-only')
final=[dict(path=p,blob=git('rev-parse',':'+p),sha256=sha((R/p).read_bytes()),coverage='Complete final added source/evidence read; existing tooling consumer context plus complete one-line change inspected where applicable') for p in paths]
topo=json.load(open(O/'topology.json'));old=next(p for p in topo['prs'] if p['number']==8010);ds=[]
for d in old['original_delta']:
 p=d['path'];target=None
 if p in paths:
  target=p;status='accepted unchanged' if git('rev-parse',':'+p)==d['new_blob'] else 'narrowed';reason='Canonical claim/evidence retained; note provenance pointer repaired; both tooling maps preserve all main entries plus one original helper entry.'
 elif '/native-wall-check/' in p:
  target='docs/work_history/repo/review_feedback/pr8010-native-wall/'+p.split('/native-wall-check/')[1];status='accepted unchanged';reason='Exact historical diagnostic provenance relocated with explicit non-authority README.'
 elif p=='docs/audit/data/citation_graph_manifest.json':status='rejected';reason='Stale generated manifest; regenerate from combined current-main source, not scientific authority.'
 else:status='superseded';reason='Historical planning/review/validation/port records or duplicate theorem/certificate. No independent current authority. Complete canonical notes/runners preserve mathematical content; unique native-grid results/preregistration restored separately. Frozen original Git objects remain the historical recovery handle.'
 ds.append(dict(original_path=p,original_blob=d['new_blob'],disposition=status,reason=reason,final_path=target,final_blob=git('rev-parse',':'+target) if target else None,recovery=H+':'+p))
inputspec=[('NATIVE_GAUGE_TRANSFER_WILSON_SECOND_ORDER_MULTIPLIER_BOUNDED_THEOREM_NOTE_2026-09-07.md','complete analytic source; PN and denominator2618,lower bound,normalizations'),('NATIVE_GAUGE_TRANSFER_KILLED_HEAT_SECOND_ORDER_KERNEL_BOUNDED_THEOREM_NOTE_2026-09-07.md','complete analytic source; uniform kernel remainder and general two-weight bound'),('NATIVE_GAUGE_TRANSFER_FULL_TOP_SECOND_ORDER_BOUNDED_THEOREM_NOTE_2026-09-07.md','complete source; only Euler-Maclaurin/quasimode/isolation consumed, not native coefficient or its discrete-insertion proof'),('NATIVE_GAUGE_TRANSFER_A2_REFLECTION_UNIFORM_HALF_LINE_GAP_THEOREM_NOTE_2026-09-02.md','sections1-5 complete; exact recurrence/reflection/Fourier and compact sandwich convergence'),('WILSON_SU3_GAUGE_TRANSFER_KERNEL_POSITIVITY_BOUNDED_NOTE_2026-05-30.md','complete source; Wilson kernel and Schur c/d normalization'),('SU3_CHARACTER_DIAGONAL_CONVOLUTION_EQUIVALENCE_NARROW_THEOREM_NOTE_2026-05-10.md','finite B4 source; dimension-generic index contraction independently checked; infinite labels also supplied by Wilson positivity section4'),('GAUGE_VACUUM_PLAQUETTE_TRANSFER_OPERATOR_CHARACTER_RECURRENCE_NOTE.md','section6 complete; actual six-neighbor recurrence and boundary omissions; full spatial transfer unconsumed'),('MINIMAL_AXIOMS_2026-06-29.md','complete authority'),('ai_methodology/skills/PRIMITIVE_REGISTRY_CHECK.md','complete authority'),('audit/data/axiom_premise_nodes.json','complete authority'),('SCALE_REFERENCE_PRIMITIVE_NOTE.md','complete authority; unconsumed units primitive'),('KINETIC_ISOTROPY_PRIMITIVE_NOTE_2026-06-09.md','complete authority; does not choose Wilson model'),('REALIZED_STATE_PRIMITIVE_NOTE_2026-06-11.md','complete authority; no state data imported')]
inputs=[dict(path='docs/'+p,blob=git('rev-parse',B+':docs/'+p),sha256=sha((R/'docs'/p).read_bytes()),coverage=role) for p,role in inputspec]
claims=[dict(claim='dimension-divided multiplier',disposition='accepted with provenance pointer correction',domain='every real beta>=2048 and every dominant integer label',result='uniform absolute1710/beta^2 remainder for c_p/(d_p c0); wall-uniform divided alternant; diagnostic21rows not proof',proof='CONDITIONAL on supplied Wilson recurrence/reflection,PN low remainder and denominator bounds'),dict(claim='central-character Gaussian sandwich spectrum',disposition='accepted unchanged',domain='supplied one-link character sandwich, Dirichlet chamber',result='complete spectrum theta^(3k+2n+1); simple leading theta^4 and theta^6 branches; k0=5-7/sqrt5,k1=8-21/(2sqrt5); o(beta^-1) branch remainder',proof='CONDITIONAL on divided multiplier,heat and Gaussian quadrature/compact convergence; no physical multi-link gap or finite onset')]
record=dict(pr=8010,reviewer_session='/root/backlog_topology',original_head=H,original_merge_base=old['merge_base'],confirmation_base=B,reviewed_tree=git('write-tree'),source_verdict='PASS',landing_verdict='not issued; coordinator combined gates still required',final_paths=final,original_constituent_dispositions=ds,claim_dispositions=claims,proof_inputs=inputs,runtime_scientific_input_files=[],finding_dispositions=[dict(id='8010-1',status='resolved same session',problem='Dropped unique diagnostic history while note asserted preserved loop pack',resolution='Seven byte-identical historical native-wall files plus README and corrected live note pointer; no receipt restamping')],imports={'Wilson SU3 action and sandwich':'explicit model/normalization conditions','Haar and Dirichlet chamber':'explicit normalization/boundary conditions','recurrence/reflection/heat/quadrature':'conditional mathematical source inputs inspected in consumed scope','observations/fits/PDG/state-data':'none'},evidence=[dict(path=str(p),sha256=sha(p.read_bytes())) for p in (O/'check8010').glob('*.json')],disposition_map_sha256=sha(json.dumps(ds,sort_keys=True).encode()),limitations='No full pipeline invoked. Source review does not apply an audit status or certify integrated current-main gates. Review markdown records analytic reasoning and all lenses.')
(O/'review-8010.json').write_text(json.dumps(record,indent=2)+'\n');print(record['reviewed_tree'],len(ds),len(final))
