#!/usr/bin/env python3
"""T54 test: can any state of the taste cube be the single dark candidate, and does the
choice of embedding (which qubit is the weak fibre) matter?  See PREREG.md (written first).

Parts
 A  rep content + Casimirs of the base x fibre embedding for fibre axis f = 1,2,3; S0,S3 triples
 B  Lie algebra generated by the three axis-conjugates; irreducibility (commutant); S3 (A1) overlap
 C  hypercharge tracelessness lemma
 D  many-body census (Fock space of the 8 modes): brute force N_g=1, characters N_g=1,2,3
 E  lifetime of N1 with the seesaw Yukawa that reproduces m_atm; required suppression
"""
import itertools, math
import numpy as np

np.set_printoptions(precision=4, suppress=True, linewidth=140)
s2 = math.sqrt(2.0)

# ---------------------------------------------------------------- embedding (as in CL3_COLOR_AUTOMORPHISM B,C,F,H)
U = np.zeros((4, 4))
U[0, 0] = 1; U[1, 1] = U[2, 1] = 1 / s2; U[3, 2] = 1; U[1, 3] = 1 / s2; U[2, 3] = -1 / s2
lam = [np.array(m, dtype=complex) for m in [
    [[0, 1, 0], [1, 0, 0], [0, 0, 0]], [[0, -1j, 0], [1j, 0, 0], [0, 0, 0]], [[1, 0, 0], [0, -1, 0], [0, 0, 0]],
    [[0, 0, 1], [0, 0, 0], [1, 0, 0]], [[0, 0, -1j], [0, 0, 0], [1j, 0, 0]], [[0, 0, 0], [0, 0, 1], [0, 1, 0]],
    [[0, 0, 0], [0, 0, -1j], [0, 1j, 0]], [[1, 0, 0], [0, 1, 0], [0, 0, -2]]]]
lam[7] = lam[7] / math.sqrt(3)
sx = np.array([[0, 1], [1, 0]]) / 2; sy = np.array([[0, -1j], [1j, 0]]) / 2; sz = np.array([[1, 0], [0, -1]]) / 2


def gens_fibre_last():
    """Generators with base = qubits (0,1), fibre = qubit 2."""
    T = []
    for l in lam:
        M = np.zeros((4, 4), dtype=complex); M[:3, :3] = l / 2
        T.append(np.kron(U @ M @ U.conj().T, np.eye(2)))
    J = [np.kron(np.eye(4), s) for s in (sx, sy, sz)]
    Psym = U @ np.diag([1, 1, 1, 0]) @ U.conj().T
    Y = np.kron((1 / 3) * Psym - (np.eye(4) - Psym), np.eye(2))
    return T, J, Y


def perm_matrix(perm):
    """Matrix moving tensor factor i -> perm[i] on (C^2)^3 (basis |b0 b1 b2>)."""
    P = np.zeros((8, 8))
    for idx, b in enumerate(itertools.product([0, 1], repeat=3)):
        nb = [0, 0, 0]
        for i in range(3):
            nb[perm[i]] = b[i]
        P[int("".join(map(str, nb)), 2), idx] = 1
    return P


T0, J0, Y0 = gens_fibre_last()
axes = {}
for f in (0, 1, 2):
    # move fibre qubit (2) to position f, keep base order: perm sends 2 -> f, and the other two to the others
    others = [i for i in range(3) if i != f]
    perm = [others[0], others[1], f]
    P = perm_matrix(perm)
    axes[f] = ([P @ t @ P.T for t in T0], [P @ j @ P.T for j in J0], P @ Y0 @ P.T)

labels = ["".join(map(str, b)) for b in itertools.product([0, 1], repeat=3)]

print("== PART A: rep content and Casimirs, fibre axis f = 1,2,3 (qubit index f-1 is the weak fibre)")
ok_A = True
for f in (0, 1, 2):
    T, J, Y = axes[f]
    C3 = sum(t @ t for t in T); C2 = sum(j @ j for j in J)
    H = C3 + 0.37 * C2 + 0.11 * Y
    w, v = np.linalg.eigh(H)
    blocks = {}
    for k in range(8):
        vec = v[:, k]
        key = (round((vec.conj() @ C3 @ vec).real, 4), round((vec.conj() @ C2 @ vec).real, 4), round((vec.conj() @ Y @ vec).real, 4))
        blocks[key] = blocks.get(key, 0) + 1
    print(f" f={f+1}: irreps (C_F, j(j+1), Y): multiplicity ->", blocks)
    # gauge singlets: joint kernel of all generators
    G = np.vstack([np.hstack([g for g in T + J + [Y]])])  # placeholder to keep shapes explicit
    S = sum(g.conj().T @ g for g in T + J + [Y])
    ev = np.linalg.eigvalsh(S)
    print(f"      smallest eigenvalue of sum G^dag G = {ev.min():.4f}  (0 would mean a gauge singlet)  count(<1e-9)={int((ev<1e-9).sum())}")
    for lab in ("000", "111"):
        i = labels.index(lab); e = np.zeros(8); e[i] = 1
        trip = ((e @ C3 @ e).real, (e @ C2 @ e).real, (e @ Y @ e).real)
        # eigenstate check: residual of C3 e, C2 e, Y e being proportional to e
        res = max(np.linalg.norm(A @ e - (e @ A @ e) * e) for A in (C3, C2, Y))
        print(f"      |{lab}>: (C_F, j(j+1), Y) = ({trip[0]:.4f}, {trip[1]:.4f}, {trip[2]:+.4f}); eigenstate residual {res:.1e}")
        if not (abs(trip[0] - 4 / 3) < 1e-9 and abs(trip[1] - .75) < 1e-9 and abs(trip[2] - 1 / 3) < 1e-9 and res < 1e-9):
            ok_A = False
    if ev.min() < 1e-9:
        ok_A = False
print(" P1 (all axes: 6 x (3,2)_{1/3} + 2 x (1,2)_{-1}, no singlet, S0/S3 = (4/3,3/4,+1/3)):", "PASS" if ok_A else "FAIL")

print("\n== PART B: covariant closure of the three axis-conjugate gauge algebras")
def vec(A):
    # A must be anti-Hermitian (i * Hermitian generator, or a commutator of such)
    return np.concatenate([A.real.ravel(), A.imag.ravel()])
basis_mats = []        # Hermitian generators (used for the commutant)
for f in (0, 1, 2):
    T, J, Y = axes[f]
    basis_mats += T + J + [Y]
anti = [1j * m for m in basis_mats]   # anti-Hermitian versions (used for the Lie closure)
def rank_of(mats):
    V = np.array([vec(m) for m in mats])
    s = np.linalg.svd(V, compute_uv=False)
    return int((s > 1e-9).sum())
print(" dim of each single embedding (real span):", rank_of([1j * m for m in axes[0][0] + axes[0][1] + [axes[0][2]]]))
cur = list(anti)
dim = rank_of(cur)
print(" dim of span of the 3 axis-conjugates (before closure):", dim)
for it in range(6):
    # add commutators of a maximal independent subset
    V = np.array([vec(m) for m in cur])
    u, s, vt = np.linalg.svd(V, full_matrices=False)
    idx = []
    # pick independent subset greedily
    sel = []
    Q = np.zeros((0, V.shape[1]))
    for m in cur:
        x = vec(m)
        if Q.shape[0] == 0:
            r = np.linalg.norm(x)
        else:
            r = np.linalg.norm(x - Q.T @ (Q @ x))
        if r > 1e-8:
            Q = np.vstack([Q, (x - (Q.T @ (Q @ x) if Q.shape[0] else 0)) / r]); sel.append(m)
    new = []
    for a, b in itertools.combinations(sel, 2):
        new.append(a @ b - b @ a)
    cur = sel + new
    nd = rank_of(cur)
    # compress
    print(f"  closure iteration {it+1}: dim = {nd}")
    if nd == dim:
        break
    dim = nd
print(" Lie algebra generated by the three axis-conjugates has real dimension", dim, "(u(8)=64, su(8)=63)")
# commutant: X with [X, g] = 0 for all generators of the closure basis
gens_all = basis_mats
rows = []
I8 = np.eye(8)
for g in gens_all:
    rows.append(np.kron(g, I8) - np.kron(I8, g.T))   # vec(gX - Xg) with row-major vec
Amat = np.vstack(rows)
sv = np.linalg.svd(Amat, compute_uv=False)
nullity = int((sv < 1e-9).sum()) + max(0, 64 - len(sv))
print(" commutant dimension of the three axis-conjugates together:", nullity, "(1 = irreducible: only scalars commute)")
# S3 A1 subspace
perms = [perm_matrix(p) for p in itertools.permutations(range(3))]
Proj = sum(perms) / 6
ev, evec = np.linalg.eigh(Proj)
A1 = evec[:, ev > 0.5]
print(" S3 (axis permutation) A1 subspace dimension:", A1.shape[1], " (states |000>,|111>, W, Wbar)")
# is the fibre-3 gauge algebra S3-covariant?  count how many distinct algebras the 6 permutations produce
def alg_key(f):
    T, J, Y = axes[f]
    A = [1j * m for m in T + J + [Y]]
    V = np.array([vec(m) for m in A])
    q, r = np.linalg.qr(V.T)
    return q[:, :rank_of(A)]
dists = []
for f in (1, 2):
    Q0 = alg_key(0); Qf = alg_key(f)
    dists.append(np.linalg.norm(Qf - Q0 @ (Q0.T @ Qf)))
print(" distance of algebra(f=2),(f=3) from algebra(f=1):", np.round(dists, 3), "(0 would mean the gauge algebra is axis-symmetric)")
irreducible = (nullity == 1)
print(" P2 (irreducible under the covariant closure):", "PASS" if irreducible else "FAIL")

print("\n== PART C: hypercharge lemma  Tr_C8 Y = 0  with two Y-neutral states")
a = sp = None
# 6 alpha + 2 beta = 0 ; beta = 0 => alpha = 0
alpha_sol = 0.0 / 6
print(" if the extra two states are Y-neutral (beta=0), tracelessness gives alpha =", alpha_sol,
      "; the landed pattern has alpha = +1/3, beta = -1 (beta = -3 alpha).")
print(" trace of Y in the embedding:", np.trace(Y0).real)

print("\n== PART D: many-body census (Fock space of the 8 taste modes)")
def jw_ops(n):
    I = np.eye(2); Zp = np.diag([1, -1]); a = np.array([[0, 1], [0, 0]])
    ops = []
    for k in range(n):
        m = np.array([[1.0]])
        for j in range(n):
            m = np.kron(m, Zp if j < k else (a if j == k else I))
        ops.append(m)
    return ops
ann = jw_ops(8)
cre = [c.T for c in ann]
def onebody(M):
    out = 0
    for i in range(8):
        for j in range(8):
            if abs(M[i, j]) > 1e-14:
                out = out + M[i, j] * (cre[i] @ ann[j])
    return out
Tg, Jg, Yg = axes[2]
Gops = [onebody(g) for g in Tg + Jg + [Yg]]
Nop = sum(cre[i] @ ann[i] for i in range(8))
Ndiag = np.diag(Nop).real.round().astype(int)
S = sum(g.conj().T @ g for g in Gops)
brute = []
for k in range(9):
    idx = np.where(Ndiag == k)[0]
    Sk = S[np.ix_(idx, idx)]
    ev = np.linalg.eigvalsh(Sk)
    brute.append(int((ev < 1e-9).sum()))
print(" brute force, N_g=1, gauge-neutral states by particle number k=0..8:", brute)

def census(Ng, nA=36, nB=32, nP=40):
    K = 8 * Ng
    a1 = 2 * np.pi * (np.arange(nA) + 0.13) / nA   # offset avoids grid points on Weyl-chamber walls
    a2 = 2 * np.pi * (np.arange(nA) + 0.29) / nA
    b = 2 * np.pi * (np.arange(nB) + 0.11) / nB
    ps = 2 * np.pi * (np.arange(nP) + 0.07) / nP
    A1_, A2_, B_, P_ = np.meshgrid(a1, a2, b, ps, indexing="ij")
    A3_ = -A1_ - A2_
    e = [np.exp(1j * A1_), np.exp(1j * A2_), np.exp(1j * A3_)]
    dens3 = np.abs((e[0] - e[1]) * (e[0] - e[2]) * (e[1] - e[2])) ** 2 / 6.0
    dens2 = 1 - np.cos(2 * B_)
    dens = dens3 * dens2
    zs = []
    for c in range(3):
        for s in (+1, -1):
            zs.append(e[c] * np.exp(1j * s * B_) * np.exp(1j * P_))
    for s in (+1, -1):
        zs.append(np.exp(1j * s * B_) * np.exp(-3j * P_))
    I = np.zeros(K + 1, dtype=complex)
    for j in range(K + 1):
        zeta = np.exp(2j * np.pi * j / (K + 1))
        prod = np.ones_like(dens, dtype=complex)
        for z in zs:
            prod = prod * (1 + zeta * z) ** Ng
        I[j] = (prod * dens).mean()
    coef = np.array([sum(I[j] * np.exp(-2j * np.pi * j * k / (K + 1)) for j in range(K + 1)) / (K + 1) for k in range(K + 1)])
    return coef

for Ng in (1, 2, 3):
    c = census(Ng)
    nz = {k: round(c[k].real, 3) for k in range(len(c)) if abs(c[k]) > 1e-6}
    print(f" characters, N_g={Ng}: gauge-neutral state counts by k (nonzero only):", nz,
          "  max imag/round err =", float(max(abs(c.imag).max(), abs(c.real - c.real.round()).max())))
c1 = census(1)
match = [int(round(c1[k].real)) for k in range(9)] == brute
print(" P4 check: character method reproduces brute force at N_g=1:", match)
P4 = (brute == [1, 0, 0, 0, 0, 0, 0, 0, 1]) and match
print(" P4 (one generation: only k=0 and k=8 neutral):", "PASS" if P4 else "FAIL")

print("\n== PART D2: multiplets with a Q=0 member inside the N_g=1 Fock space (Minimal-DM-type objects)")
C3f = sum(onebody(t) @ onebody(t) for t in Tg) if False else None
# second-quantised Casimirs from the one-body generators
T_ops = [onebody(t) for t in Tg]; J_ops = [onebody(j) for j in Jg]; Y_op = onebody(Yg)
C3_2q = sum(t @ t for t in T_ops); C2_2q = sum(j @ j for j in J_ops)
for k in range(1, 8):
    idx = np.where(Ndiag == k)[0]
    Hk = (C3_2q + 0.37 * C2_2q + 0.11 * Y_op)[np.ix_(idx, idx)]
    w, vv = np.linalg.eigh(Hk)
    cnt = {}
    for c in range(len(idx)):
        vec_ = vv[:, c]
        key = (round(float((vec_.conj() @ C3_2q[np.ix_(idx, idx)] @ vec_).real), 3),
               round(float((vec_.conj() @ C2_2q[np.ix_(idx, idx)] @ vec_).real), 3),
               round(float((vec_.conj() @ Y_op[np.ix_(idx, idx)] @ vec_).real), 3))
        cnt[key] = cnt.get(key, 0) + 1
    single = {kk: n for kk, n in cnt.items() if abs(kk[0]) < 1e-6 and kk[1] > 0.5}
    print(f" k={k}: colour-singlet, weak-charged (C_F=0, j(j+1)>0) states (C_F, j(j+1), Y): count ->", single)
print(" (k=3 entry (0, 3.75, +1.0) = one colour-singlet j=3/2 quadruplet of Y=+1 -> Q=T3+Y/2 = 2,1,0,-1: it has a Q=0 member; it is 3 quarks, B=1)")

print("\n== PART F: look-elsewhere for a keV node on the ladder M_k = alpha_LM^k M_Pl")
aLM = 0.090667836017286; MPl = 1.2209e19
nodes = [(k, MPl * aLM**k * 1e6) for k in range(20, 28)]   # in keV
print(" nodes (k, keV):", [(k, round(m, 3)) for k, m in nodes])
inwin = [k for k, m in nodes if 1.0 <= m <= 50.0]
print(" nodes inside [1, 50] keV:", inwin, " (ratio between nodes = %.2f; window ratio 50 -> expected %.2f nodes)" % (1/aLM, math.log(50)/math.log(1/aLM)))
print(" P7 (1 or 2 nodes in the window):", "PASS" if len(inwin) in (1, 2) else "FAIL")

print("\n== PART E: N1 stability with the seesaw Yukawa fixed by the atmospheric gap")
hbar = 6.582119569e-25          # GeV s
M1 = 5.323e10                   # GeV (DM_CANDIDATE_MASS_WINDOW note)
v = 246.282818290129
vh = v / math.sqrt(2)           # 174.1 GeV
m_atm = 0.0503e-9               # GeV  (sqrt(dm31^2), ~0.05 eV)
y2 = 2 * M1 * m_atm / vh**2     # m_nu = y^2 vh^2 / (2 M)  -> y^2 = 2 M m / vh^2   (one N carries the whole gap: benchmark)
Gam = y2 * M1 / (8 * math.pi)   # N -> (l H + lbar H*), Majorana
tau = hbar / Gam
print(f" y^2 = {y2:.3e}, y = {math.sqrt(y2):.3e};  Gamma = y^2 M/(8 pi) = {Gam:.3e} GeV;  tau = {tau:.2e} s")
print(f" lane's figure: Gamma = 47.24 H(T=M1) = 1.88e5 GeV, tau = 3.5e-30 s  -> ratio ours/lane = {tau/3.5e-30:.2f}")
t_univ = 4.35e17
Gmax = hbar / t_univ
y2max = 8 * math.pi * Gmax / M1
print(f" tau > age of universe needs y^2 < {y2max:.2e}, i.e. y smaller by a factor {math.sqrt(y2max/y2):.1e}")
P5 = 0.1 < tau / 3.5e-30 < 10
print(" P5 (tau within a factor 10 of the lane's 3.5e-30 s):", "PASS" if P5 else "FAIL")
# sterile-neutrino-DM window for the role-split route (nuMSM-type): keV state
Mst = 7e-6                      # GeV = 7 keV
theta2 = 1e-11                  # rough X-ray box order (not used as a claim; sets the scale of y needed)
y_needed = math.sqrt(theta2) * Mst / vh
print(f" role-split route: a 7 keV state with mixing^2 ~ 1e-11 needs y ~ {y_needed:.1e} (vs {math.sqrt(y2):.1e} for the atmospheric partner)")

print("\nSUMMARY  P1:", "PASS" if ok_A else "FAIL", " P2:", "PASS" if irreducible else "FAIL", " P4:", "PASS" if P4 else "FAIL", " P5:", "PASS" if P5 else "FAIL")
