"""Kill check on T36 P4: (1) does the '<=1.8x' result come from the attacker's perturbativity cap (sv<=2.5 at M_Pl)?
(2) can running create a ratio from a rank-deficient UV texture (not sampled by generic full-rank draws)?
Reuses the attacker's RGE (imported by exec of t36_p4_running.py's function block)."""
import numpy as np, re
src = open('t36_p4_running.py').read()
# take only the definitions (up to the sampling loop), reuse rk4/f/pack/unpack/sv/randY
head = src.split("t_UV, t_IR")[0]
ns = {}
exec(head, ns)
rk4, pack, unpack, sv, randY = ns['rk4'], ns['pack'], ns['unpack'], ns['sv'], ns['randY']
rng = np.random.default_rng(5)
t_UV, t_IR = np.log(1.22e19), np.log(173.0)
g0 = np.array([0.61, 0.50, 0.49])

def run(Yu, Yd, Ye, n=800):
    ns['np'] = np
    y1 = rk4(pack(Yu, Yd, Ye, g0), t_UV, t_IR, n=n)
    return None if y1 is None else unpack(y1)

print("(1) max amplification of a singular-value ratio vs UV perturbativity cap (Yu only nonzero + random Yd small)")
for cap in (2.5, 4.0, 6.0, 10.0):
    amps = []
    for _ in range(300):
        s = rng.uniform(0.3, cap)
        Yu = randY(s); 
        if sv(Yu)[0] > cap: continue
        # scale so that largest sv is uniform in [0.3,cap]
        Yu = Yu * (rng.uniform(0.3, cap) / sv(Yu)[0])
        Yd = randY(0.5); Ye = randY(0.5)
        r = run(Yu, Yd, Ye, n=600)
        if r is None: continue
        su1 = sv(r[0]); su0 = sv(Yu)
        for (i, j) in ((1, 0), (2, 0), (2, 1)):
            amps.append((su1[i] / su1[j]) / (su0[i] / su0[j]))
    amps = np.array(amps)
    print(f"  cap {cap:>4}: n={len(amps)}  max ratio-of-ratios {amps.max():.2f}  99pct {np.percentile(amps,99):.2f}  share >10: {np.mean(amps>10):.3f}")

print("\n(2) rank-1 UV textures (Yu = yt m m^dag, Yd = yb n n^dag): light singular values generated by running")
for ytUV, ybUV, ang in [(1.0, 0.02, 0.5), (1.0, 0.3, 0.5), (1.0, 1.0, 0.5), (1.0, 1.0, 0.05)]:
    m = np.array([1, 0, 0], dtype=complex)
    n = np.array([np.cos(ang), np.sin(ang), 0], dtype=complex)
    Yu = ytUV * np.outer(m, m.conj()); Yd = ybUV * np.outer(n, n.conj()); Ye = np.zeros((3, 3), dtype=complex)
    r = run(Yu, Yd, Ye, n=1200)
    if r is None: print("  blowup"); continue
    su = sv(r[0]); sd = sv(r[1])
    print(f"  yt={ytUV} yb={ybUV} angle={ang}: UV up sv = (1,0,0)*yt ; IR up sv ratios = {su[1]/su[0]:.3e}, {su[2]/su[0]:.3e} ; IR down sv ratios = {sd[1]/sd[0]:.3e}, {sd[2]/sd[0]:.3e}")
