import pathlib,subprocess,json,hashlib,datetime
root=pathlib.Path('/private/tmp/review-drain-20260915'); orig=root/'drain8166-originals';check=root/'check8166';inv=json.loads((orig/'inventory.json').read_text());repo=root/'integration-resume';pref='.claude/science/physics-loops/toe-compact-response-20260916/'
sha=lambda b:hashlib.sha256(b).hexdigest()
deps=[]
for rev,path,why in [(inv['main'],'docs/PRECONDITIONED_EXTENDED_GRADIENT_GAUSSIAN_REMAINDER_AND_FREE_CUBIC_RIESZ_BOUNDED_THEOREM_NOTE_2026-09-15.md','Sections 1-3 source variations and section 7 periodic Riesz proof only. Carrier expansion/physical-state claims are not imported.'),('c228dbcfc0a6b71639316915f460c32dbf479723','.claude/science/physics-loops/toe-compact-ground-path-20260916/notes/BLOCK02_CONTINUOUS_TIME_MAGNETIC_EXCURSIONS.md','Conditional application event bound.'),('c228dbcfc0a6b71639316915f460c32dbf479723','.claude/science/physics-loops/toe-compact-ground-path-20260916/notes/BLOCK04_TEMPORAL_OSCILLATIONS_AND_COARSE_CURRENTS.md','Conditional application temporal event and infinite-volume path premise; itself uses BLOCK03.')]:
 b=subprocess.check_output(['git','-C',str(repo),'show',rev+':'+path]);q=check/'dependencies'/path;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(b);deps.append(dict(revision=rev,path=path,sha256=sha(b),reason=why))
dis=[]
for f in inv['files']:
 rel=f['path'][len(pref):];row=dict(f);row['recovery_path']=str(orig/f['path']);row['recovery_revision']=inv['head']
 if rel.startswith('notes/'):
  row.update(disposition='narrowed',reason='Preserve complete positive conditional proof in canonical source with explicit supplied-model premises, real dependency links and registration. Topology negative certification explicitly deferred; no broader phase theorem.',proposed_destination='docs/'+pathlib.Path(rel).name)
 elif rel in ['evidence/'+n+'.py' for n in ['bridge_cubic_check','convex_carrier_check','integer_filling_check','magnetic_covariance_check']]:
  row.update(disposition='narrowed',reason='Preserve formulas/fixtures/tolerances; canonicalize wrapper and actual helper/input declaration; fresh source-bound capture required.',proposed_destination='scripts/'+pathlib.Path(rel).name)
 else:row.update(disposition='deferred',reason='Exact historical/operational source recovery. No author status, verifier result or old execution is promoted to current authority.',proposed_destination='docs/work_history/repo/review_feedback/pr8166-originals/'+rel)
 dis.append(row)
findings=[
 dict(id='8166-PACKAGING',kind='AUDIT_COMPATIBILITY',severity='required canonical repair',details='All original science is in a branch-local pack; notes lack canonical metadata/runner bindings, JSON-only output lacks canonical counted/N5 envelope. Preserve complete proofs and exact historical failures; capture only final reviewed canonical bytes.'),
 dict(id='8166-DEPENDENCIES',kind='REPO_GOVERNANCE',severity='required canonical repair',details='Gaussian note section 7 names main Riesz/source-variation source only in prose. Geometry application names draft event sources; its infinite Z4 law additionally relies on the path-limit input through BLOCK04. Use actual canonical links with scoped dependency roles; 8165 remains conditional pending its independent review.'),
 dict(id='8166-NCERT',kind='MISSING_ARTIFACT',severity='deferred negative certification',details='Original N1 checklist explicitly declines formal certification and does not give five normalized attempted routes. Convex section 5 asserts small principal flux need not guarantee globally small raw-curl lift and cites currents/harmonic sectors. The general torus distinction also appears in integer section 4. These topological exclusion statements must not receive packet PASS from one witness or formula mutations. Preserve exact originals; accept only positive conditional construction plus explicit statement that compact transfer is unestablished by this work, unless a genuine applicable certificate is separately completed. Preserve original branch if this exclusion/certification remains unlanded.')]
report=dict(schema_version=1,pr=8166,review_kind='original-independent-science-review',reviewer='/root/review_8166',model='gpt-6-astra',reasoning_effort='low',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),head=inv['head'],merge_base=inv['merge_base'],declared_base='main',current_main_for_review=inv['main'],fresh_github_head_verified=json.loads((check/'final_remote_head.json').read_text()),verdict='POSITIVE_CONDITIONAL_SCIENCE_ACCEPTABLE_FOR_CANONICAL_REPAIR; ORIGINAL_PACKET_NOT_LANDING_READY',landing_ready=False,formal_retained_grade=False,audit_verdict=None,broad_negative_certificate=False,material_math_findings=[],findings=findings,
claims_and_boundaries=[
'Bridge: positive Dirichlet grid precision and bounded Hessian give synchronous transport, all-p entrywise Green majorants, cubic F/R derivative estimates, then finite-volume physical-time limit. Constants independent of volume; no periodized compact log-derivative claim.',
'Convex extension: C2 clipped source, C4 potential and actual interacting bridge correction give global Hessian/cubic estimates and exact small-raw-curl equality for chosen lifts; interpolation carrier b(theta) retained.',
'Gaussian comparison: quotient actual nullspace; magnetic covariance factors into spatial curl projection, weighted diagonal Riesz ratio and small Neumann correction. Replication transfers published dimension-independent diagonal bound. Uniform cubic remainder yields only covariance-convergent diffuse-test Gaussian subsequences, not covariance identification.',
'Geometry: finite-set bad-vertex intersections plus Lambda(c)<1 imply finite enlarged-box components. Integer coordinate contraction fills conserved finite currents; disjoint actual components justify probability products. Contractibility gives integer lift and optional infinite/open-time temporal gauge. Application remains conditional on actual 8165 path/event bounds.'
],proof_obligations='CONDITIONAL: all four stated positive model/geometry implications are supported by their written proofs and disclosed mathematical tools; compact normalized measure/source matching is outside those implications.',imports={'supplied_model':'Compact rotor Hamiltonian, continuous angles, positive g and physical time, spatial cubic domains and boundary choices are supplied model data, not derived from framework axioms.','comparison':'Nonperiodic convex extension and alpha,T,g are explicit choices; no fitted or observed target.','geometry':'Finite-set probability bound is an explicit premise; Hamiltonian application requires separately reviewed path/event results.','mathematical_tools':'Finite-dimensional additive-noise flows, Brascamp-Lieb, Feynman-Kac, integer cellular cohomology, discrete Calderon-Zygmund interpolation and published diagonal Riesz theorem.','registered_primitives':'Authority memo and all three primitive sources read at frozen main. No registered primitive used as a bounded wall or enlarged into dynamics.'},
no_go={'status':'FAIL_OR_PENDING_FOR_ORIGINAL_NEGATIVE_CERTIFICATION','N1':'Fewer than five actually normalized attempted routes against the topological exclusion are documented. Coefficient mutations and distinct positive lemmas do not repair this quota. Mathematical truth is separate.','N2':'No independent physical-wall count claimed; analytic chain and geometric premise not independent walls.','N3':'Model, domains, time weights, norms and probability premise are explicit.','N4':'Finite source checks match their stated finite algebra; none tests normalized compact transfer.','N5':'Four JSON final receipts omit required five-line certificate; canonical actual execution must add honest resolution statements.','N6':'Normalized winding representation and direct response remain open positive routes; no new axiom required.','N7':'Exact normalized compact winding/source map could enable transfer; no class-wide failure conclusion accepted.','N8':'Earlier Hessian/path work supplies narrower inputs, not proof of compact transfer.','positive_scope':'The four main implications are positive conditional results, not five failed attacks or impossibility claims.','required_disposition':'Preserve stronger original exclusion in exact history and original branch if certification remains deferred; canonical accepted scope only asserts that this work has not established compact transfer.'},
read_scope={'complete_science':'All four complete proof notes; four full final runners; actual helper closure; mutation harness and focused verifier; all prior-source changes and diagnostics; all operational markdown and STATE; all 12 final mutation transformations and assertion stderr checked.','numeric':'All 17 nonempty JSON files parsed; final source/helper pins verified. Not every numerical leaf manually inspected.','authority':'Frozen main axiom memo, registry procedure/data and all primitive sources; same-revision review setup/units/lenses/fixes/audit-compatibility/salvage/operations, no-go discipline and proof-search governance. Governance context inspected; no current-main authority is inferred from moving checkout.'},dependencies=deps,
external_sources=[dict(url='https://arxiv.org/html/1507.03796v1',inspected='Definitions and Theorem 1; mixed cyclic groups explicit; only diagonal combination bound imported.'),dict(url='https://arxiv.org/abs/1106.0709',inspected='Primary source identity and covariance-tool scope; standard finite strongly convex covariance inequality used with verified hypotheses.')],
independent_controls=json.loads((check/'independent_controls.json').read_text()),targeted_mutations=json.loads((check/'targeted_mutation.json').read_text()),source_evidence=json.loads((check/'source_evidence_verification.json').read_text()),resource_plan={'original_timeout_seconds_each':120,'primary_reexecutions':0,'actual_independent_control_seconds':2.737771291984245,'historical_primary_seconds':[.1380992920603603,.08823325007688254,.07716333400458097,.35079066699836403],'memory':'Largest primary eigensystem is 768 square; largest Hermite rule uses 16^4 points in 4 coordinates. Individual dense float64 768-square matrix is 4.5 MiB, but several coexist and LAPACK/Python overhead is additional. Peak RSS not measured; do not restamp historical time as resource certification.','runtime_inputs':'No external scientific data read by original primary runners. Convex imports bridge helper and hashes both. NumPy/SciPy/mpmath required. Canonical wrappers must declare any newly read notes/helpers.'},original_inventory_sha256=sha((orig/'inventory.json').read_bytes()),original_delta_sha256=sha((orig/'original.diff').read_bytes()),original_dispositions=dis,
required_author_fix_scope=['Four complete canonical positive bounded theorem notes; preserve all equations/proof bodies and caveats, not summaries.','Four canonical runners, convex-to-bridge helper binding, real note-input pins, original 120-second timeouts, unchanged finite checks and thresholds.','Canonical evidence capture after final source freeze, actual counted assertions and N5 lines; preserve old receipts as old receipts.','Scope mathematical dependency links to actual Riesz/source-variation sections; do not import unrelated carrier hypotheses. Resolve 8165 application linkage without presuming its review.','Negative certificate remains deferred unless genuinely completed; preserve branch for unlanded exclusion and record exact source disposition.','Retain every original file, mode/blob/SHA including unsuccessful sign and helper attempts and superseded norm versions.'],
checks_skipped=['No primary main reruns, pipeline, audit worker, ledger/verdict changes, checkout/index mutation, staging, commit, push or closure. Combined gate and current-main science-loss review belong to coordinator final candidate.'],commits_created=[],pipeline_count=0,integration_retries=0,final_confirmation_required='Same reviewer session must inspect exact canonical affected source, dependencies, captures and interactions before any source PASS; original report is immutable.')
path=root/'drain8166-original-review.json';assert not path.exists();path.write_text(json.dumps(report,indent=2)+'\n')
md='''# PR 8166 original independent scientific review

Frozen head: `02bfa4eb99fce8329619a476775299567f735d4b`; merge base: `e0ef7cf4633034a8c1e6d57f5812cc4275bf1349`; authority main: `16574d8f023c06a3ef86fe6d8993a257e0936c81`.

## Result

The four positive conditional proofs are useful and no consequential mathematical defect was found. Original packet is **not landing ready**. Preserve complete bridge cubic/operator bounds, convex comparison, Gaussian magnetic subsequences, and conditional integer fillings. None proves compact-measure transfer, unique Maxwell covariance, a photon phase or framework model selection.

Canonical repair must supply actual note/runner registration, helper/input pins, fresh evidence and scoped dependency links. The geometry application needs the infinite-volume path premise through the current-source dependency, not only the two event formulas. The published [diagonal discrete Riesz theorem](https://arxiv.org/html/1507.03796v1) covers the mixed cyclic factors used by the explicit replication argument.

## Negative certification

Original N1-N8 packet expressly leaves certification pending. The convex note's small-principal-flux/global-lift exclusion is stronger than merely saying transfer is unestablished. Preserve it in original recovery. Do not certify it using coefficient mutations, positive lemmas, or one topology witness as five routes. If this exclusion remains outside accepted canonical scope, explicitly defer its certification and preserve the original branch. This procedural limitation does not disprove any positive conditional implication.

## Evidence

All 123 changed paths have exact mode/blob/SHA recovery and dispositions in the JSON report. Complete final proofs and runners were read; twelve historical mutation transformations and errors verified. Independent positive-integral differentiation, symbolic response/extension checks, bridge precision, integrated time carrier, covariance resolvent and box-count checks passed. Two targeted runner mutations were rejected against the independently differentiated integral. No primary program was rerun.

Four historical primary times total under one second, each with a 120-second timeout declaration. Peak memory was not measured. Current canonical source confirmation and the combined integration gate remain required. No repository source, index, status or audit authority was modified.
'''
p=root/'drain8166-original-review.md';assert not p.exists();p.write_text(md)
print(path);print('files',len(dis),'report_sha256',sha(path.read_bytes()))
